flux-framework/flux-core

src/bindings/lua/Test/Builder.lua, src/bindings/lua/flux-lua.c, src/bindings/lua/json-lua.c, src/bindings/lua/tests/t0001-zmsg.t, src/bindings/lua/tests/zmsg-test.c, src/bindings/lua/zmsg-lua.c, t/lua/t0001-send-recv.t, t/lua/t1000-reactor.t
Quick Lua bindings update for recent flux protocol/API changes:
- Add optional extra `nodeid` argument to `send` call, allowing lua api to target ranks as in flux api
- Error number is no longer transported in json payload, it is part of flux message, so add new index field to `zmsg_info` object to access error number. (There is no facility for setting an error number yet)
Also includes a couple minor fixes
- Lua-TestMore scripts should exit non-zero if any test fails
- NULL json_object is represented as `nil` in Lua
=> Minor updates to Lua API for recent flux protocol changes

src/broker/module.c, t/lua/t0002-rpc.t
As I was developing tests I inadvertently created a ping packet that was invalid (a json array instead of a json object), and this caused cmbd to segfault when trying to add the `route` entry to the json object
```
util_json_object_add_string (o, "route", s);
```
Yeah, this is more likely a json-c bug, but to be a bit defensive in the `ping` service, this patch checks to make sure the received object is specifically a `json_object`, and returns `EPROTO` if not.
(The patch also returns EPROTO on other `flux_msg_decode` errors as well to avoid ping hangs)
Probably other services should be audited at some point to verify data sent in the payload too, though this is probably more important when flux instances handle multiple users...
=> Fix for cmbd crash with invalid ping packet

src/bindings/lua/flux-lua.c, src/bindings/lua/zmsg-lua.c, t/lua/t0001-send-recv.t
Further stopgap measures to adapt to recent Flux protocol changes:
- Just enough "matchtag" support to get some other things working (Warning: no facility for freeing a matchtag at this time, not sure how that should work...)
- `recv` will now promote and non-zero `errnum` into the returned Lua table... this is just a temporary measure until `recv` can be replaced.
- `recvmsg` will eventually replace the simpler `recv`. Data such as `errnum` and `matchtag` are part of flux msg, not the JSON payload, so it no longer makes sense to pretend the message is json. For now we can use recvmsg where the matchtag is required.
=> lua: more updates to Lua API to adapt to recent flux message protocol changes

src/bindings/lua/flux-lua.c, src/bindings/lua/json-lua.c, t/lua/t0002-rpc.t
Updates `flux_rpc` lua binding for better compatibility with new protocol, fixes encoding of an empty Lua table in JSON (empty Lua table becomes JSON object, not JSON array), and fixes compile error for `l_flux_recv`
=> Misc lua binding fixes and updates

src/cmd/flux-comms-stats.c, src/common/libflux/info.c, src/common/libutil/jsonutil.c, src/common/libutil/shortjson.h, src/modules/kvs/kvs.c, src/modules/kvs/libkvs.c
In json-c-0.11 the function json_object_object_get() was deprecated in
favor of json_object_object_get_ex(). The prototypes differ like such:
struct json_object* json_object_object_get(struct json_object* obj,
const char *key);
vs
json_bool json_object_object_get_ex(struct json_object* obj,
const char *key,
struct json_object **value);
This commit updates all code using json_object_object_get() to use
the non-deprecated function. One note is that json_object_object_get_ex()
returns `true' if the key exists in the JSON object, but *value may
still end up NULL if the key points to a NULL JSON object. Presumably,
this is the reason the old function is being deprecated.
Fixes Issue #133.
=> Support build against json-c-0.11

src/common/libflux/handle.c, src/common/libflux/handle.h, src/modules/kvs/kvs.c, src/modules/kvs/kvs.h, src/modules/kvs/libkvs.c, src/modules/kvs/waitqueue.c, src/modules/kvs/waitqueue.h, src/test/tkvswatch.c, t/t1000-kvs-basic.t
This PR adds a `kvs_unwatch ()` call which was conspicuously absent from the original KVS API.  When a key is unwatched, server side (KVS comms module) resources are freed up and notifications will no longer be received by the handle when the key changes.  In addition, the matchtag used in the original watch request, and reused on watch notifications (responses), is freed back to the matchtag pool.
RFC 3 defines a 32-bit matchtag space, but the allocator in the generic handle code was just a toy and limited the available matchtags to 255.  (actually blocks of up to 2^24 tags could be allocated at once for `flux_json_multrpc()`, but internally even a single tag consumed a full block).  This was changed so that the formerly unused block 0 space is covered with a veb tree allocator.  The …
=> add kvs_unwatch() and improve matchtag allocator

doc/cmd/Makefile.am, doc/cmd/flux-exec.adoc, doc/cmd/spell.en.pws, src/broker/cmbd.c, src/cmd/Makefile.am, src/cmd/flux-exec, src/common/libutil/Makefile.am, src/common/libutil/subprocess.c, src/common/libutil/subprocess.h, src/common/libutil/test/subprocess.c, t/Makefile.am, t/sharness.d/flux-sharness.sh, t/t0005-exec.t, t/t1001-barrier-basic.t
Ok, trying again:
This PR adds a very simple remote execution service directly to `cmbd` as a `cmb.exec` service.
Subprocess management function are encapsulated into a new `subprocess_manager` API under `common/libutil` in the hopes this code can be reused by other remote and local execution services.
A `subprocess manager` instance is added to `cmbd` and is used to replaced the hand-coded fork/exec for the cmbd interactive shell, and subsequently the `cmb.exec` service is built using this same `subprocess manager` instance.
A new `flux-exec` utility is added to "execute" processes across a session as direct children of `cmbd` or individual ranks may be targeted. By default, `flux-exec` copies the current environment minus `FLUX_TMPDIR` and uses the current working directory, but these …
=> Add subprocess management and simple remote execution to flux-core 

src/common/libutil/subprocess.c
When a process using the subprocess_manager code is running
with fully buffered output, a child which fails during exec(2)
may flush the parent's buffers on the subsequent call to exit(127).
This is only a problem when child shares parent stdio streams,
and will be fixed when the subprocess code properly redirects
child fds to pipes or other destinations. For now, we close
stdout and stdin before exit() to avoid this issue.
This issue was causing failures in subprocess unit tests when run
under test drivers like `tap-driver.sh` or `prove(1)` (because lack of
a terminal caused unbuffered output to be used)
=> workaround for subprocess unit test failures under test driver

src/bindings/lua/flux-lua.c, src/common/Makefile.am, src/common/libflux/Makefile.am, src/common/libzio/Makefile.am, src/lib/libpmi/Makefile.am, t/lua/t1002-kvs.t
This set of small fixes are mainly minor build/test enhancements.
The first part of this PR fixes a couple dependency issues so that `make check` will work without
first running `make all` or `make`. This isn't a critical issue, but it seemed wrong that `make clean && make check` was failing, especially since some tests were failing in the middle due to missing *runtime* dependencies.
I also wanted to enhance the lua/kvs tests, and while doing that, ran across some bugs and missing functionality in the lua bindings. These minor issues are fixed here, and tests added.
=> Small build/test fixes and lua binding support for kvs_unwatch

src/common/libflux/reactor.c, src/modules/kvs/kvs.c, src/test/tkvswatch.c
Fix bug in `kvs_watch` handler logic introduced recently by commit 0232626.
This was causing watch callbacks to be called on each commit, when the value had not necessarily changed.
Add test coverage for this to `tkvswatch`.
Also address a missing trace call that came up while debugging.  Tracing would go silent when the reactor was entered.
=> fix issue #151 extraneous kvs_watch callbacks

src/common/libflux/conf.c, src/common/libflux/rpc.c, src/modules/api/libapi.c, src/modules/kvs/kvs.c
Some low hanging fruit from running valgrind on flux commands, inspired by issue #152.
There is a biggie in here where the response zmsg was leaked in every call to flux_json_rpc().
=> fix assorted memory leaks

t/fluxometer.lua.in
Fix fluxometer lua test library to allow a fluxometer session to
be nested within an existing flux session.
Fixes #155.
=> testing: lua: allow tests to run inside flux session

src/broker/module.c, src/common/libflux/handle.c, src/common/libflux/handle.h, src/common/libflux/handle_impl.h, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libutil/Makefile.am, src/common/libutil/coproc.c, src/common/libutil/coproc.h, src/common/libutil/test/coproc.c, src/modules/api/libapi.c, src/test/request/Makefile.am, src/test/request/coproc.c, src/test/request/req.c, src/test/request/treq.c, t/t0002-request.t
This PR implements getcontext(2) based coprocesses for Flux reactor message handlers.
A per-handle "opt-in" flag `FLUX_FLAGS_COPROC` enables the new capability.
When enabled, reactor message handlers are started in a coprocess context.  They can yield control back to the reactor by calling `flux_sleep_on()`, which takes a flux_match_t argument.  Once the handle produces a message matching the argument, it resumes the handler coprocess where it left off, with the matching message queued up to be read next by `flux_recvmsg()`.
Only one coprocess is allowed to be active per message handler.  If request messages arrive for a handler that is blocked waiting for an RPC response, it is queued and put back to the handle (where it can make the reactor ready once again) after the handler coprocess …
=> run reactor message handlers as coprocesses if FLUX_FLAGS_COPROC is set

src/common/libutil/coproc.c
This PR puts some finishing touches on the coproc class as discussed in issue #126
* increases stack size from 16K to 2MB
* replaces the trivial redzone with `mprotect()`ed guard pages
* check `swapcontext()` return value in `coproc_yield()`
=> improve coproc implementation

src/common/libutil/coproc.c, src/common/libutil/coproc.h, src/common/libutil/test/coproc.c
Here's a test that exceeding the coproc stack generates a `SIGSEGV` as discussed in PR #159
=> improve coproc tests

src/bindings/lua/flux-lua.c, src/cmd/flux-exec, src/cmd/flux-wreckrun, t/lua/t1004-sighandler.t
Use `signalfd(2)` in flux-lua to add signal handler support to the flux Lua bindings.
Other interfaces to the API can use `signalfd(2)` along with `flux_fdhandler_add()` to handle signals within the current flux reactor, but I didn't find a simple, available signalfd library for Lua, so took the easy way out and simulated reactor signal handlers internally in lua bindings.
This fixes Ctrl-C on `flux-wreckrun` and `flux-exec` utilities.
=> flux-lua reactor signal handler support

src/broker/module.c, src/test/request/req.c, src/test/request/treq.c, t/t0002-request.t
This PR addresses two issues, somewhat unrelated except I noticed the second while working on the first.
* issue #163: t0002-request.t has improper synchronization
* issue #164: modules don't exit cleanly when removed
=> fix coproc test, fix module unload

src/bindings/lua/flux-lua.c, src/bindings/lua/tests/zmsg-test.c, src/bindings/lua/zmsg-lua.c, src/broker/broker.c, src/broker/modservice.c, src/cmd/flux-comms-stats.c, src/cmd/flux-mping.c, src/cmd/flux-snoop.c, src/common/libflux/event.c, src/common/libflux/flog.c, src/common/libflux/info.c, src/common/libflux/message.c, src/common/libflux/message.h, src/common/libflux/request.c, src/common/libflux/request.h, src/common/libflux/rpc.c, src/common/libflux/rpc.h, src/common/libflux/test/message.c, src/modules/api/libapi.c, src/modules/barrier/barrier.c, src/modules/barrier/libbarrier.c, src/modules/kvs/kvs.c, src/modules/kvs/libkvs.c, src/modules/live/live.c, src/modules/mecho/mecho.c, src/modules/wreck/job.c, src/modules/wreck/wrexec.c, src/modules/wreck/wrexecd.c, t/t1003-mecho.t, t/t1004-log.t
Convert all uses of deprecated functions to newer equivalents, then remove them and their tests.
Add a few tests to cover areas that were touched and had no tests.
I will submit a PR to update `flux-sched`
resolves #180
=> remove deprecated functions

etc/Makefile.inc.in, flux-core.spec.in, src/common/libutil/test/coproc.c
This PR includes the fix to `Makefile.inc` proposed by @lipari in PR #193, plus fixes to two problems encountered when building a flux-core RPM on rhel6:
* Tweak a fragile coproc unit test
* Update spec file to include "connectors"
Still todo for RPM is to resolve unsatisfied liblive, libmodctl.  Waiting for @trws to settle PR #192 before tackling that one.
=> fixes for out of tree builds

src/modules/libzio/zio.c, src/modules/libzio/zio.h
Somehow during the shuffle in #200 a couple commits got dropped from the zio code
6fbe4fa50dc9e92775f288413b68af50b89e3e78
6053a339ba2280a780eaf117f3ab6df980ee9d6c
This PR pulls them back. I suppose this could wait until we have a PR with users of the new code, but since this code was already in there for a bit I figure I might as well throw them back up here. No problem if you guys want to wait.
=> zio: export zio_read

src/common/libflux/message.c, src/connectors/local/Makefile.am
Update the `Makefile.am` used to build the `local.so` connector so that it links against `libflux-core` and `libflux-internal`, and uses ldflags similar to that used to build comms modules.
This fixes a spurious segfault in the lua event test in anther PR I was working.  Full disclosure: I could not debug that segfault, except to get a general idea that something was failing in the main libflux code that was working perfectly well for many other tests.  I got a hunch that this had to do with missing symbols lazily resolved at runtime, discovered that the connector Makefile.am was probably not right, made this change, and it went away.
This PR also contains a tiny fix to `flux_msg_fprint()`.
=> link connectors in a manner similar to comms modules

configure.ac, src/cmd/Makefile.am, src/cmd/flux-jstat.c, src/common/core.h, src/common/libutil/shortjson.h, src/include/flux/core.h, src/modules/Makefile.am, src/modules/libjsc/Makefile.am, src/modules/libjsc/README.md, src/modules/libjsc/jstatctl.c, src/modules/libjsc/jstatctl.h, t/Makefile.am, t/t2001-jsc.t
Provide a high-level abstraction to allow monitoring and controlling
of the status of Flux jobs. Designed to expose the job status and
control abstraction in a way to hide the underlying data layout of
job information stored within Flux's KVS data store.
Expect that schedulers and runtime tools will be its main users. This
abstraction provides the producers of job information including
a task and program execution service module including wreckrun with
an opportunity to change and optimize the data layout of jobs within
the KVS without presenting major impacts to the implementation
of the schedulers and runtime tools.
- Abstract out implementation-dependent job states;
- Provide flexible and easily extensible mechanisms to pass job info;
- Use a minimalistic API set.
Our data schema …
=> Integrate Job Status and Control (JSC) interface

src/cmd/flux-start.c
This avoids a situation where an MPI program linked against the
old non-PMI mvapich and run by Flux, which is being run under Slurm,
thinks it is Slurm's job step 0, and gets the whole session killed
by connecting to srun and aborting.
The MPIRUN_* environment variables set by SLURM to facilitate PMGR
based MPI bootstrap are not set when --mpi=none is used.  This has
no impact on PMI based MPI.
Fixes issue #220
=> flux-start: use srun --mpi=none

src/broker/broker.c, src/common/libflux/handle.c
A couple of fixes arising from recent API rework churn:
* bad memory leak found by @grondo
* log decoding prob found by @SteVwonder
=> fix memory leak and log decoding

src/common/libutil/Makefile.am, src/common/libutil/base64.c, src/common/libutil/base64.h, src/common/libutil/jsonutil.c, src/common/libutil/jsonutil.h, src/common/libutil/test/base64_test.c, src/common/libutil/test/encode.c
This PR switches data encoding via `util_json_object_add_data` to base64 from the one-off Z85 implementation. This means that the following now works:
```
(flux-51954-0) grondo@hype356:~/git/flux-core.git$ src/cmd/flux kvs dir lwj.1.0.stdout
lwj.1.0.stdout.000000 = { "data": "SGksIFRoaXMgaXMgc29tZSBqb2Igb3V0cHV0Cg==" }
lwj.1.0.stdout.000001 = { "eof": true }
(flux-51954-0) grondo@hype356:~/git/flux-core.git$ echo SGksIFRoaXMgaXMgc29tZSBqb2Igb3V0cHV0Cg== | base64 -d 
Hi, This is some job output
```
I grabbed a standalone base64 implementation from @dun's MUNGE project and dropped it into libutil, along with Chris' existing test. This seems to work, but was quickly hacked up and could use another set of eyes. (Also need to wait for Travis)
Any other comments welcome. I was actually thinking …
=> use base64 for encoding "data" in json and kvs

src/bindings/lua/Test/Builder.lua, src/bindings/lua/Test/More.lua, src/test/tbarrier.c, t/Makefile.am, t/fluxometer.lua.in, t/lua/t0001-send-recv.t, t/lua/t0007-alarm.t, t/lua/t1003-iowatcher.t, t/sharness.d/flux-sharness.sh, t/t1000-kvs-basic.t, t/t1001-barrier-basic.t
This is a small set of patches to hush the noisy little sharness and lua tests in `/t`.
The main change is to send flux-broker log messages to files by default. During a normal run,
these logfiles are removed during `cleanup`. They are retained in the case of test failure or
a debug or verbose testsuite run. It would be nice if the logfiles could be kept in a per-test directory,
but since these directories are created after `flux-start` is run, that is not possible.
Other changes are pretty straightforward in the commit history. With the quiet output we can now run the testsuite nice and clean and in parallel with `prove`, e.g.
```
grondo@hype356:~/git/f/t$ prove -j32 *.t */*.t
loop/handle.t ........... ok                                            
loop/rpc.t .............. ok …
```
=> hush the testsuite

src/common/libflux/handle.c, src/common/libutil/msglist.c, src/connectors/local/local.c, src/modules/api/api.c
This PR corrects a very bad bug that crept into pr #225.  The local handle pollfd would remain "ready" even after its events had been consumed due to an epoll programming error.  This was causing a hang in pr #231
In addition to fixing this bug, some unnecessary reads and writes on the eventfd embedded in `msglist_t` were eliminated and some of its error handling code tightened up.
Finally, file descriptors in the handle, local connector, and api module are now opened with the close-on-exec flag to avoid leaking across exec.
=> fix local connector reactor spin

src/common/libcompat/reactor.c, src/common/libflux/handle.h, src/common/libflux/info.c, src/common/libflux/reactor.h, t/loop/reactor.c
This PR fixes two bugs
* libcompat reactor handler return codes were tested for !=0 instead of old behavior of <0
* `flux_rank()` coding error prevents rank from being cached on first call
It also adds missing inline documentation for the new functions in handle.h and reactor.h, and improves the reactor loop test incrementally.
=> minor bug fixes to reactor, documentation, tests

src/common/libflux/reduce.h, src/common/libflux/security.h, src/modules/barrier/barrier.h
Originally part of #236.
* flux_restack_count -> flux_redstack_count
* remove flux_sec_enabled, because it does not exist
* add <flux/core.h> include to barrier.h, apparently this was never a problem
because it was always included after flux.h in each .c file
=> header cleanup from the python binding branch

src/modules/wreck/job.c
label found in wait_for_lwj_watch_init which is wrapped in a
SIMULATOR_RACE_WORKAROUND ifdef.  integrating the simulator into the
existing scheduler framework and making the JSC race-free will eliminate
the need for this function and the ifdef.
=> sim/wreck: removed unused done label

doc/cmd/flux-ping.adoc, doc/cmd/spell.en.pws, src/cmd/flux-kvs.c, src/cmd/flux-ping.c, src/cmd/flux.c, src/common/libflux/event.c, src/common/libflux/message.c, src/common/libflux/reactor.c, src/common/libflux/request.c, src/common/libflux/response.c, src/common/libflux/response.h, src/common/libflux/rpc.c, t/t1000-kvs-basic.t
This PR includes an assortment of bug fixes and cleanups:
* Get rid of some internal use of `zmsg_t` in libflux-core
* Rework `flux-ping` to use new reactor API and allow request pipelining, used for test in #251
* Add `flux-kvs dir [-r]` option and `flux-kvs watch-dir [-r]` option per #256
* Change `flux_response_decode()` signature to make its msg argument a const
* Fix bug in `flux-snoop` and `flux --trace` output where unterminated string was printed
* Fix bug in `flux` command driver that prevented `flux --tmpdir` from working outside a session
=> assorted bug fixes and cleanups

src/modules/api/api.c, src/test/Makefile.am, src/test/tdisconnect.c, t/Makefile.am, t/t1006-apidisconnect.t
The api module was not issuing disconnects to services that were addressed by rank.  Contacting the same service on multiple ranks would only result in a single disconnect to the local rank.
A sharness test is added for the `FLUX_NODEID_ANY` and multiple ranks cases.
disconnects are described (briefly) in RFC 6.
Fixes issue #261
=> generalize api disconnect protocol

src/broker/broker.c, src/broker/shutdown.c, src/broker/shutdown.h
Change the shutdown grace period to a double, and add --shutdown-grace
command line option.
If option is not provided, choose the default based on the session size,
reducing hte default for small sizes used in our unit tests to 0.5s.
Fixes #237
=> broker: add --shutdown-grace option

.travis.yml, src/cmd/flux.c, src/test/travis-dep-builder.sh
This PR updates the travis-ci builder to their new container-based infrastructure. The main benefits of this change are
* faster build start times
* support for cache directories (i.e. for built dependencies)
The drawback is that `sudo` is no longer supported -- however this isn't really an issue since we can install all dependencies into subdirs of `$HOME`.
This PR enables the new container based builds by adding `sudo: false` to the `.travis.yml` file.
In order to manage caching, a new script is added that handles downloading dependencies only if they are not already cached. (Unfortunately, lua dependencies have to be special cased)
The script supports a max-cache-age, but this isn't enabled yet.
In order to support builds with non-standard Lua paths, the first commit here fixes the …
=> update travis-ci builds to new container-based builders

.travis.yml, doc/man1/flux-exec.adoc, src/broker/broker.c, src/cmd/flux-exec, src/modules/libsubprocess/subprocess.c, src/modules/libzio/zio.c, t/t0005-exec.t
For completeness, this PR adds stdin handling to `flux-exec`. The current behavior is to broadcast stdin to each process currently "running". `flux-exec` therefore waits until all tasks currently managed are either running or failed to start handling stdin.
If `flux-exec` is sent to the background, it may be stopped by `SIGTTIN` if/when it tries to read from the terminal. Therefore, it is recommended to redirect stdin from `/dev/null`, send over a pipe, or use the `-n` option when running in the background. (The tests are updated to use this approach).  However, since the `cmb.exec` service is message based, things actually turn out OK if `flux-exec` goes into the background and is stopped. Once put in the foreground and resumed, it appears that buffered messages are processed and …
=> cmd: support stdin broadcast for flux-exec

doc/test/spell.en.pws, t/t2001-jsc.t
For some reason, another aspell failure on Ubuntu 14.04 required dictionary additions.
Also, I split up the intermittently failing jsc tests so we can at least see which part is problematic.
=> minor test adjustments

.travis.yml, t/fluxometer.lua.in, t/t2000-wreck.t
commit e04e40b here may have a fix for #284, however I was unable to quickly reproduce the error documented therein, so I'd appreciate @garlick if you tried reproducing with this branch.
Additionally, this PR adds timeouts to all `flux-wreckrun` invocations in `t2000-wreck.t` to catch the occasional wreck hangs that we've seen in travis.
Finally, we fix up `pip` package caching.
I'm still working on enhancing the sharness based tests to somehow report more detailed errors on failure. That will come in a future PR.
=> more testing fixups

doc/man3/Makefile.am, doc/man3/flux_event_subscribe.adoc, doc/man3/flux_open.adoc, doc/man3/flux_recv.adoc, doc/man3/flux_rpc.adoc, doc/man3/flux_rpc_multi.adoc, doc/man3/flux_rpc_then.adoc, doc/man3/flux_send.adoc, doc/man3/tevent.c, doc/man3/topen.c, doc/man3/trecv.c, doc/man3/tsend.c, doc/test/spell.en.pws
The day after writing those RPC man pages, they looked badly written to me, so here's what I hope are improved versions.
Also I took the examples in flux_open(3), flux_send(3), flux_recv(3), and flux_event_subscribe(3) and turned them into standalone C programs that are compiled as check_PROGRAMS to be sure they at least compile.
=> Manpage cleanup

.travis.yml, doc/test/spell.en.pws, src/bindings/python/Makefile.am, src/test/travis-dep-builder.sh, t/Makefile.am, t/sharness.d/flux-sharness.sh, t/sharness.sh
A few testing, travis, and test environment updates/fixes:
* sharness tests now can log stderr/out to a file during testing for post-mortem analysis.
* travis tests set FLUX_TESTS_LOGFILE=t to get logs, and have an `after_failure:` hook to cat all tests output files from failures. This will hopefully help diagnose transient travis test failures.
* `travis-dep-builder.sh` now includes pip install so `sched` and other dependent projects will get python dependencies by default
* `travis-dep-builder.sh` has new `--printenv` option and travis-ci uses this to set the correct environment for build. (In my VM I now run
```
./src/cmd/travis-dep-builder.sh
$(./src/cmd/travis-dep-build.sh --printenv)
```
to download/build dependencies and set up my environment to use them)
* small fix for python …
=> test and build updates

.travis.yml, doc/man1/Makefile.am, doc/man3/Makefile.am, doc/test/Makefile.am, doc/test/spell.en.pws, doc/test/spellcheck, src/bindings/lua/flux-lua.c, src/bindings/lua/lutil.c, src/broker/broker.c, src/common/libflux/message.c, src/common/libflux/module.c, src/common/libflux/rpc.c, src/common/libutil/cleanup.c, src/common/libutil/env.c, src/common/libutil/jsonutil.c, src/common/libutil/optparse.c, src/modules/kvs/kvs.c, src/modules/libsubprocess/subprocess.c, src/modules/wreck/job.c, src/modules/wreck/luastack.c, src/modules/wreck/wrexec.c, src/modules/wreck/wrexecd.c, src/test/travis-dep-builder.sh, t/sharness.d/flux-sharness.sh
This PR adds support for  [Travis integrated Coverity scan](https://scan.coverity.com/travis_ci) in `.travis.yml`, and then subsequently fixes a few of the most egregious and easy to fix defects that were detected.
Currently I've only subscribed my personal fork to the free Coverity Scan service, but for now this will be sufficient and I can periodically push to my `coverity_scan` branch to enable checks. However, keeping the coverity settings in `.travis.yml` will make it much easier to do that, so hopefully that will be acceptable.
I can also send invites to project members so you can view the defect reports on the Scan website, take ownership of defects and mark them as false positives, etc. For now I'm just trying out the free service.
I considered squashing all these fixes together …
=> Support Coverity runs under Travis and fix some found issues and other cleanup

.travis.yml
apparently the check in travis for "am I on the coverity_scan branch" is aborting the actual compile and test on the main repo because COVERITY_SCAN_BRANCH is unset (it works in my repo, perhaps because I do actually have a `coverity_scan` branch)
Sadly, this wasn't detected as an error by travis, but a success :-(
Anyhow, the variable should probably be quoted, so let's try this.
=> travis-ci: add quoting to test for COVERITY_SCAN_BRANCH

src/cmd/flux.c, src/common/libutil/optparse.c, src/common/libutil/optparse.h, t/t1005-cmddriver.t
This PR starts with some simple functionality tests for the `flux-env` builtin in `t1005-cmddriver.t`.
During this work, I wanted to see `flux env --help` work so I started importing the `optparse` parser for builtin `flux(1)` commands to rerun option parsing on their own arguments. This led to the discovery of some fixes required for `optparse.[ch]`, which are included here.
The cleanest way to handle >1 internal command seemed to be to have a table of builtins, so I eventually settled on that. This approach makes it easy to add new builtins if need be, but also just maximizes the reduction of the now common code (and standardizes builtin cmd interface).
=> cmd/flux: env builtin tests and builtin updates

src/broker/module.c, src/common/libflux/message.c
Pointed out by @trws.  This will save some needless heap activity in the message path for modules.
=> avoid extra strdup in module message path

src/bindings/python/test_commands/sideflux.py
Turns out I had a mistake in my environment clearing, the inner flux was picking up the outer one and refusing to start as directed.  This ensures a new flux is run with the requisite parameters.
fixes #309
=> bindings/python: sideflux environment clearing fix

src/bindings/python/flux/core/trampoline.py, src/modules/pymod/echo.py, src/modules/pymod/py_mod.c
fixes #291
The argc/argv style arguments are now packed into a Python list, compatible
with all standard python argument parsing libraries meant for `sys.argv`.
=> modules/pymod: use argc, argv argument parsing

configure.ac, src/bindings/python/flux/core/trampoline.py, src/modules/pymod/echo.py, src/modules/pymod/py_mod.c
The C compiler macro has been updated to AC_PROG_CC_C99, for gcc and clang the
effect is that the C standard flag will be switched from the default
`-std=gnu90` (actually, recent GCCs use `-std=gnu11`, but whatever) to
`-std=gnu99`.  For non-gcc/clang compilers it will search for a C99 variant,
usually just the c99 binary, or the closest most extended c99 variant it can
recognize.  The AC_PROG_CC_C_O macro has also been removed, since it has been a requirement of the AC_PROG_CC and sub-macros since autoconf 1.14 anyway.
=> configure: switch from C (90/gnu90) default to C99

doc/man3/Makefile.am, doc/man3/flux_info.adoc, doc/man3/flux_reduce_create.adoc, doc/man3/tinfo.c, doc/man3/treduce.c, doc/test/spell.en.pws, src/broker/broker.c, src/cmd/flux-comms.c, src/cmd/flux-up.c, src/common/libflux/info.c, src/common/libflux/info.h, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libflux/reduce.c, src/common/libflux/reduce.h, src/modules/live/live.c, t/Makefile.am, t/loop/multrpc.c, t/loop/reduce.c
This PR is preliminary, not for merging.  It's posted as a PR mainly to keep @dongahn up to date with what I'm doing to stuff his work depends on.  (He should feel free to redirect me if I am making life harder rather than easier):
* Rename `flux_red_t` to `flux_reduce_t` and make opaque type conformant to flux style
* Rename functions to be prefixed with `flux_reduce_`
* Drop `flux_redstack_t` and add a standalone `flux_list_t` class instead.
* Revive the `flux-mon` command and `mon` module (update to modern interfaces)
* Update the live module to use the new `flux_reduce_t` names.
See comment at the top of `src/modules/mon/mon.c` for how to demo the mon module/program.
Coming soon: man page for reduce functions.
=> redesign/fix flux_reduce_t handle

src/broker/Makefile.am, src/broker/broker.c, src/broker/heartbeat.c, src/broker/heartbeat.h, src/broker/hello.c, src/broker/hello.h, src/broker/module.c, src/broker/module.h, src/broker/overlay.c, src/broker/overlay.h, src/broker/shutdown.c, src/broker/shutdown.h, src/broker/snoop.c, src/broker/snoop.h, src/broker/test/heartbeat.c, src/broker/test/hello.c, src/broker/test/shutdown.c, src/broker/test/snoop.c, src/common/libflux/Makefile.am, src/common/libflux/flux.h, src/common/libflux/heartbeat.c, src/common/libflux/heartbeat.h, src/common/libflux/message.c, src/common/libflux/message.h, src/common/libflux/test/message.c, src/connectors/shmem/shmem.c, src/modules/kvs/kvs.c, src/modules/live/live.c
This is not quite ready but I wanted to get it posted for early review.
This PR adds `flux_msg_sendzsock()` which takes a `const flux_msg_t *` argument.  This facilitates 
migration from `zmsg_send()` and its "destroy message on success" behavior.
The broker private classes, especially those for handling the overlay networks and comms modules, were converted, and in the process several spots where messages had to be duplicated in order to avoid getting them destroyed by `zmsg_send()` were revisted and copies avoided.  Probably not any big performance gains here but perhaps a little (I did not attempt to measure this).
This also moves some of our internals to the new `flux_msg_t` API.  A `flux_msg_recvzsock()` to match the sending function was added, as was `flux_msg_has_route()` which …
=> reduce gratuitous message duplication in broker

.clang-format, src/bindings/python/.style.yapf
The .clang-format file defines a style following the rules set down in our RFC
on the subject, and enforcing them across an entire file.  If possible, the
lines at the bottom should be uncommented to get the best alignment results,
but this requires a newer clang than we have on LC machines by default.  The
file as committed is compatible with the default clang 3.5 that is generally
available.  Use it just by running clang-format on a file, or a piped input
stream, from any directory below the file, it will be found and used as the
configuration automatically.  If possible, it would be nice to use this by
default, but for a while it will cause ancillary changes on pull-requests to
do that unless we do a global re-format at the start.
The .style.yapf file is an equivalent system for …
=> adds code formatters for c and python

src/common/libflux/module.c
Originally from #236.
I'm not sure this is the best way to handle it, but otherwise the error for a
module dependency being unavailable is "invalid argument" in the broker.  This
has to be more debuggable, but I'm open to suggestions for better handling
here.
=> Add an error print if dlopen fails

doc/man3/tevent.c, doc/man3/trecv.c, src/broker/test/heartbeat.c, src/broker/test/hello.c, src/broker/test/shutdown.c, src/cmd/flux-event.c, src/cmd/flux-ping.c, src/common/libcompat/handle.c, src/common/libflux/message.h, src/common/libflux/reactor.c, src/test/kap/kap_roles.c, t/loop/handle.c, t/loop/reactor.c
By prepending the type to these preprocessor macros, they are able to be used both as static initializers  and function arguments, as discussed in #312.
In addition to updating the existing macros, add FLUX_MATCH_REQUEST and FLUX_MATCH_RESPONSE which were missing.
Update users.
=> update FLUX_MATCH_* initializers

.travis.yml, configure.ac, src/broker/broker.c, src/modules/Makefile.am, src/modules/resource-hwloc/Makefile.am, src/modules/resource-hwloc/resource.c
Currently in for discussion, not ready for general use as yet.  When loaded on
all ranks, `flux module load -r all resource_hwloc`, and loaded, `flux event
pub resource.load`, populates the KVS with resource information for the flux
instance.  The full topology for each node is stored as xml at
`resource.hwloc.xml.<rank>` in the KVS, and a complete tree of resources,
including IO and caches, by individual key and value is available at
`resource.hwloc.<rank>.[<resource_type>_<resource_logical_id>...]`. It has not
been instructed to look outside of administrative limitations, but that hasn't
been tested either.
=> modules/resource_hwloc: new hwloc resource grokker

src/cmd/Makefile.am, src/cmd/flux-lstopo
This adds a flux-lstopo command, which wraps the hwloc lstopo command with some logic to get the entire topology of the current flux instance.  Arguments on the command line are passed through.
=> Flux lstopo

src/cmd/flux-kvs.c, src/modules/kvs/kvs.h, src/modules/kvs/libkvs.c, t/t1000-kvs-basic.t
This PR adds kvsdir_get_size() which returns the number of entries in a KVS directory, requested by @trws for the python binding internals.  Currently it just iterates over them on first call, then caches the value for subsequent calls, as kvsdir_t contents are immutable.  Later we can perhaps make this more efficient.
Update testing to use this.  Also get `flux-kvs` off of the recently deprecated KVS interfaces.
=> add kvsdir_get_size()

src/cmd/flux.c, src/common/libflux/conf.c, src/common/libflux/conf.h, src/common/libutil/Makefile.am, src/common/libutil/iterators.h, src/common/libutil/sds.c, src/common/libutil/sds.h, src/common/libutil/sdsalloc.h, src/common/libutil/usa.c, src/common/libutil/usa.h, src/common/libutil/vec.c, src/common/libutil/vec.h, t/t1005-cmddriver.t
fixes #311
There are a lot more changes here than I expected to need, the main reason is
that lua paths are horrendously difficult to treat like any other kind of
path, because of the way they treat two contiguous separators as a proxy for
the default path.  As it is, this version de-duplicates all path components
from all inputs, but when it finds an empty path component `<sep><sep>` or
`;;`, it inserts the separator twice into the path and then moves on.  This
works for the lua paths, but disallows any truly empty component.  It was the
best solution I could seem to come up with.
In making this work, I ended up with what seemed like it might be a useful string array class, so that is split out in the last commit.
=> Env updates

src/cmd/flux-event.c, src/modules/wreck/wrexecd.c, t/Makefile.am, t/README.md, t/scripts/event-trace.lua, t/t2000-wreck.t
As described in #337, simply emit an event for each job_state_update(). The event topic is `wreck.state.<statestring>` where statestring is starting, running, or completed. The body is simply `{ "lwj": ID}`.
In order to write a test that monitors for these events, I had to force `flux-event sub` to line-buffered output. Otherwise, no output is written to destination file when output is redirected for the 3 events of interest in the test.
=> emit events for wreck job state changes

src/bindings/python/flux/kvs.py, src/bindings/python/flux/wrapper.py, src/bindings/python/test/kvs.py
Make use of the new `kvsdir_get_size` interface #351, and use the reduction in length calculation cost to avoid the generation of some unnecessary lists.  This also makes an adjustment to argument handling in the wrapper, which is not externally visible other than wasting significantly less cycles.
=> Python lazyness

src/common/libutil/env.c
Not sure how long this has been lurking, but the _strtoia check for done
under getints becomes an infinite loop when used in counting mode.  This
came up when trying to use the PMI interface, which relies on this.
=> util/env: fix infinite loop in getints

src/cmd/flux.c, t/t1005-cmddriver.t
This is more a RFC than a real PR at this point.
I got sick of typing `src/cmd/flux` this and `src/cmd/flux` that so I wanted to work on a possible fix for #263. The changes implement the following rule:
* If the current `argv[0]` is literally `"flux"`, then it is assumed path to  *this* `flux` is already first in `PATH` so `PATH` is not modified
* Otherwise, directory to *this* `flux` is prepended to `PATH`, and hopefully this `flux` is found first in children of this process
The approach here could result in duplicate entries in `PATH` if flux is run with absolute or relative path even when its dir is first in PATH, but this approach simplifies the execution (Otherwise, we'd have to iterate over `PATH` entries to determine if modification is necessary or needed)
In order to handle …
=> cmd: prepend flux cmddriver directory to PATH

src/cmd/flux-wreckrun, src/common/libutil/env.c, src/lib/libpmi/pmi.c, src/modules/barrier/libbarrier.c, src/modules/libzio/zio.c, src/modules/wreck/wrexecd.c, src/test/tpmikvs.c, t/Makefile.am, t/t1001-barrier-basic.t, t/t2002-pmi.t
Add a sharness test that drives the existing `tpmikvs` test, which simulates PMIv1 access patterns of mvapich and openpmi.  This uncovered a few wreck bugs, which were addressed by @grondo.
The test is in liu of a proper test that Flux can launch an MPI program as requested in issue #340.
We still have one test that fails in the constrained travis-ci environment, but succeeds elsewhere, that is disabled pending more wreck debug work.  We thought we should get these fixes in without further delay.
Fixes #357
=> fix wreck buglets and add PMI test

src/bindings/lua/flux-lua.c, src/cmd/flux-wreckrun, src/modules/libsubprocess/subprocess.c, src/modules/libzio/zio.c, src/modules/libzio/zio.h, src/modules/wreck/wrexec.c, src/modules/wreck/wrexecd.c, t/t2000-wreck.t
This PR tackles two recent annoying bugs in the wreck code.
1. wrexecd now always puts individual lines in kvs. Multiple lines may be put in chunks, but only one kvs commit per chunk, therefore we shouldn't increase the number of commits due to IO with this change. I split the lines and do separate `kz_put` operations, but this could easily be moved to a `kz_put_lines` function later. As part of these changes `zio` was given a "raw" mode where we return character string to callbacks instead of JSON string (so we can process lines directly)
2. The wrexec-specific dealer router shenanigans are removed, thus closing some fd leaks and removing a lot of lame code.
A small bug in `flux-wreckrun` was also fixed (check your systems for spinning `flux-wreckrun`s), and a test added for signal …
=> wreck minor updates and fixes

t/sharness.d/flux-sharness.sh, t/t1005-cmddriver.t
Test for flux cmd driver prepending its path to PATH was breaking
with links in the path. Use readlink to canonicalize PATH, adding
a prereq for readlink in case it is missing on the target system.
=> testsuite: fix cmd PATH test and require hostlist Lua module in testsuite

src/bindings/python/flux/kvs.py, src/bindings/python/flux/wrapper.py, src/broker/broker.c, src/broker/module.c, src/common/libflux/message.c, src/connectors/local/local.c, src/connectors/loop/loop.c, src/connectors/shmem/shmem.c, src/modules/connector-local/local.c
This PR fixes several issues
1) The null uuid deref described in #378 and #379.  Make the code that was previously segfaulting (and several other areas like it) robust to a malformed message, and improve logging.
2) The cause of the null uuid deref, which was an RPC made by the shmem connector picking up a response that happened to match its matchtag, but was to be routed to a downstream handle (with a separate matchtag domain).  This was solved by tightening up `flux_msg_match()` so that it only matches matchtags when the route stack is empty.
3) The "fire and forget" subscription management in the local connector.  Close a possible race described in #375 by not returning to the caller until the subscription is in effect at the broker.
4) Improve subscription handling efficiency and …
=> fix problems with subscription management

.travis.yml, src/bindings/lua/wreck.lua, src/cmd/flux-jstat.c, src/cmd/flux-wreckrun, src/modules/pymod/py_mod.c, src/modules/resource-hwloc/resource.c, src/modules/wreck/wrexec.c, src/modules/wreck/wrexecd.c, t/t2000-wreck.t
This PR contains a bit more cleanup and bug fixing in wreck.
Main bugs fixed are related to requesting more tasks than core available (we now oversubscribe at will by default, sorry this is just a prototype), and requesting more nodes than ranks in the instance (generates an error). New tests are included for these bugs.
flux-wreckrun by default doesn't display the various log messages it did before, to get the old behavior use a new `--verbose` flag.
Exit code on `SIGALRM` is fixed -- this is nice for testing.
Finally, the log messages were cleaned up in wrexecd as suggested by @garlick. I also include a commit that removes `\n` from `flux_log` messages so that we don't get the double newline output from rank0 broker.
=> more cleanup in wreck

src/cmd/flux-jstat.c, src/modules/libjsc/jstatctl.c, t/t2001-jsc.t
- jsc rework to use wreck.state.* events instead of watching-chaining. 
As far as these job events are received by jsc in order, jsc will post 
its own job status events sequentially as well.
- depend on the in-order multi-module events delivery mechanism as realized in issue #337 
- also use the same synchronous eventing mechanism when updating the state of a job for its client
- support for some of the new core interfaces including new message watcher interface
- very minor cleanup
=> jsc: reliable collection of job events

doc/man1/flux-broker.adoc, doc/man1/flux-start.adoc, doc/man1/flux.adoc, doc/man3/flux_open.adoc, doc/test/spell.en.pws, etc/flux.conf.in, src/broker/Makefile.am, src/broker/broker.c, src/cmd/flux-start.c, src/cmd/flux.c, src/common/libflux/info.h, src/lib/libpmi/pmi.c, t/Makefile.am, t/sharness.d/flux-sharness.sh, t/t2000-wreck.t, t/t2003-recurse.t
This PR is for feedback (and maybe for your amusement?) only.  It is a very simple first step towards flux launching flux as discussed in #364.
The `flux-start` command now launches Flux with `wreckrun` if $FLUX_TMPDIR is set.  It provides the `--pmi-boot` option to the broker indicating that it should dlopen a PMI library to exchange endpoint information, as it does when starting under SLURM.
The broker now sets LD_LIBRARY_PATH for the initial program to prepend the installed flux libdir, and before that, any configured `program_library_path`, which the build system sets to include the pmi library directory when running in tree.  This way the broker finds the Flux PMI library instead of SLURM's.  Perhaps this approach will also remove one obstacle to running MPI programs under Flux.
With …
=> allow flux to launch flux

src/cmd/flux-wreckrun, t/t2000-wreck.t
Instead of trying to read resource.hwloc information in wreckrun for some cases and not others, just ignore this information and distribute tasks evenly over `-N, --nnodes`, or smaller of `f.size` and `ntasks` ranks.
This isn't very powerful but probably sufficient for this prototype.
Also expand the wreck tests to handle a couple corner cases.
=> Do not attempt to read resource info in wreckrun

.travis.yml, configure.ac, doc/man3/flux_rpc.adoc, doc/man3/flux_rpc_multi.adoc, doc/man3/flux_rpc_then.adoc, doc/man3/trpc.c, doc/man3/trpc_then.c, doc/man3/trpc_then_multi.c, doc/test/spell.en.pws, doc/test/spellcheck, src/broker/attr.c, src/broker/broker.c, src/cmd/flux-snoop.c, src/modules/resource-hwloc/resource.c, src/test/travis-dep-builder.sh
Here's an assortment of tiny fixes:
* ensure hwloc is the right version #402
* ensure spellcheck dictionary is installed #401
* broker/doc cleanup: whitespace, remove deprecated cmb.info handler
* broker should die if it can't load its builtin modules #403
=> get hwloc, spell check working in travis

Makefile.am, config/ax_code_coverage.m4, src/cmd/flux-event.c, src/cmd/flux-snoop.c, src/common/libutil/optparse.c, t/Makefile.am, t/scripts/kvs-watch-until.lua, t/t0010-generic-utils.t
This PR contains a few more coverage and testing updates tweaks. The main updates include a better scheme for reporting zero coverage files (see `config/ax_code_coverage.m4` updates), addition of more external code to the ignore list (`liblsd` and `sds.[ch]`) and some basic sharness tests for commands that had no testing (`flux-event, flux-up, and flux-ping`).
I also found there must be a problem with the generated python bindings and coverage testing. They only report 1% coverage even though there is a significant amount of python tests run at `make check`. Since the generated code was about 40-50% of the total, I removed them from the reporting for now so we can get more useful results from the rest of the codebase. We can add them back later if we want but it might be more useful to …
=> More coverage tweaks

Makefile.am, config/ax_code_coverage.m4
code coverage enhancements in this commit broke "make clean"
commit 4fee3a722d0cc4847b7a1084ed1dfe13610ba56d
Author: Mark Grondona <mark.grondona@gmail.com>
Date:   Mon Sep 14 03:52:56 2015 +0000
build: remove coverage files on clean
Remove *.gcno and baseline coverage output file on 'make clean'
when configured with --check-code-coverage.
because 'clean:' was used as the target instead of 'clean-local'.
But also the commands should have been wrapped in
```
ifeq ($(CODE_COVERAGE_ENABLED),yes)
endif
```
like the rest of the code coverage commands. However, use of `ifeq()`
doesn't work in Makefile.am files because of a conflict with Automake's
"endif" keyword.
Avoid this whole disaster and move our clean commands into the
config/ax_code_coverage.m4 so they are expanded cleanly with the
rest …
=> fix make clean

.travis.yml
Well I didn't realize that `make check-code-coverage` explicitly doesn't fail during `make check`.
Therefore all travis-ci builds right now succeed for `gcc`, since that build by default runs `make check-code-coverage`.
Instead of doing code-coverage testing on one of the main compiler builds, this PR adds another compiler to travis-ci "gcc+coverage", which the build script checks for and enables coverage. This keeps the 2 compiler builds using `make distcheck` and adds a special purpose coverage build that always succeeds, but at least is separate.
=> travis-ci: better scheme for coverage testing

config/adl_recursive_eval.m4, config/x_ac_expand_install_dirs.m4
Fix/workaround for issue #22, recursively eval variables in x_ac_expand_install_dirs.m4 to ensure unexpanded vars like `${prefix}` do not appear in final macros in config.h.
=> recursively eval install dirs in config.h

src/common/libflux/dispatch.c, src/common/libflux/reactor.c, t/loop/reactor.c, t/t0000-sharness.t
This PR adds a usecount to the reactor to make it less fragile when watchers and reactor are destroyed out of order, as is prone to happen with the way the reactor and dispatcher are attached to the handle aux cache.
It also adds a couple of tests to verify that out of order destruction doesn't segfault.
Without this, flux-sched tests would segfault because the sched module does not destroy its message handlers when unloaded, so the message dispatcher was being destroyed with an active handle watcher _after_ the reactor had already been destroyed.
=> add reactor/dispatcher usecount

src/common/libtap/tap.c, src/common/libtap/tap.h, src/common/libutil/Makefile.am, src/common/libutil/test/coproc.c, src/common/libutil/test/encode.c, src/modules/libsubprocess/test/loop.c, src/modules/libsubprocess/test/subprocess.c
This PR fixes the uncaught coproc test failure we were seeing on clang.  There were several problems:
* clang built-in `alloca()` was subverting test case's abuse of it, so compile test with `-fno-builtin`
* test was emitting an extra ok result on failure (fixed)
* libtap exit codes were based on number of failed tests; update libtap
Then due to the libtap update, several tests that used the `note()` function had to be updated to use `diag()`.
=> update libtap, fix coproc test under clang

src/bindings/lua/wreck.lua, src/modules/wreck/Makefile.am, src/modules/wreck/lua.d/timeout.lua, src/modules/wreck/wrexecd.c, t/t2000-wreck.t
This PR adds advisory timeout support to wreck jobs in the form of a new `timeout.lua` script under `lua.d`. If `lwj.<id>.walltime` exists the plugin starts a timer after the job reaches the `running` state. When the timer fires the job is killed with `SIGALRM`.
Additionally a `-T, --walltime` option is added to `wreck.lua` which takes walltime option in `NUMBER[SUFFIX]` form where `NUMBER` can be arbitrary floating point number and optional suffix is "s" for seconds (default), "m" for minutes, "h" for hours, or "d" for days (like GNU `sleep(1)`).
A default of `0` is used to indicate no timeout.
@surajpkn: Can you rebase #409 on top of this PR, and make any comments?
Example:
```
grondo@flux-core:~/workspace (wreck-timeout) $ flux wreckrun -N4 --walltime=.5m sleep 60
[1443326159.790466] …
```
=> wreck max walltime support

doc/man3/flux_rpc_then.adoc, doc/man3/trpc_then.c, src/common/libflux/handle.c, src/common/libflux/handle.h, src/common/libflux/rpc.c, src/modules/kvs/kvs.h, src/modules/kvs/libkvs.c
This PR adds an internal reference count to flux_rpc_t so that a flux_rpc_t object can be destroyed from within a continuation callback.  It was a nuisance that this didn't work before.
Add use reference counts to flux_t handles and flux_kvsdir_t objects, initially for use by the lua bindings as discussed in #424.
=> add reference counts to objects

src/bindings/lua/flux-lua.c, src/bindings/lua/flux-lua.h, src/bindings/lua/kvs-lua.c, src/bindings/lua/kvs-lua.h, src/modules/wreck/wrexecd.c
This is a proposed fix for #426.
Lua doesn't own `flux_t` handles or `kvsdir_t` objects "pushed" into Lua state from C context, but the metatables for these objects still had a `__gc` field causing normal garbage collection to possibly trigger early destruction and assertion failures or other crashes.
Use newly created `incref` primitives to increase reference count of these objects if they're passed in externally to Lua, thus avoiding premature destruction from Lua and/or C.
For a sanity check, I'd like to verify that `make check` passes for @garlick on toss desktop and @dongahn's sched tests pass before merging this one in.
I've verified the reproducer I had is now fixed.
=> bindings/lua: take reference counts on external handle and kvsdir objects

doc/man1/Makefile.am, doc/man1/flux-wreck.adoc, src/bindings/lua/Makefile.am, src/bindings/lua/flux-lua.c, src/bindings/lua/flux/lustache.lua, src/bindings/lua/flux/lustache/context.lua, src/bindings/lua/flux/lustache/renderer.lua, src/bindings/lua/flux/lustache/scanner.lua, src/bindings/lua/wreck.lua, src/bindings/lua/wreck/io.lua, src/cmd/Makefile.am, src/cmd/flux-wreck, src/cmd/flux-wreckrun, src/modules/wreck/Makefile.am, src/modules/wreck/job.c, src/modules/wreck/lua.d/output.lua, src/modules/wreck/wrexecd.c, t/t2000-wreck.t
Opening this PR for comments for now, there are still a couple items TODO.
This PR abstracts the status and stdout/err handling code from `flux-wreckrun` into `wreck.lua` module to enable multiple users of these interfaces (originally done for file output for wreckrun jobs). 
A new `wreck.io` module is used by an `output.lua` plugin for wrexecd which optionally sends output to one or more files per job. The `output.lua` plugin reads an output config block from either `lwj.<id>.output` (for job `id`), or from `lwj.output` as a default for all jobs. The config keys include:
* `output.labelio`: Label lines of output with source task id
* `output.files.stdout=FILE`: Copy stdout/err to `FILE`, where `FILE` may be a [mustache](http://mustache.github.io) template with keys `id` for jobid, `cmd` …
=> abstract wreckrun io and status code, add flux-wreck(1) command and file output

src/cmd/flux-event.c, src/cmd/flux-start.c, src/cmd/flux.c, src/common/libutil/optparse.c, src/common/libutil/optparse.h, src/common/libutil/test/optparse.c, src/modules/pymod/py_mod.c, src/modules/wreck/wrexecd.c, t/t2000-wreck.t
This work started as a fix for some `flux(1)` builtins that were emitting the wrong usage message, e.g.
```
grondo@flux-core:~/workspace (master) $ src/cmd/flux lsattr foo
Usage: flux [OPTIONS] COMMAND ARGS
-x,--exec-path PATH   prepend PATH to command search path
-M,--module-path PATH prepend PATH to module search path
-O,--connector-path PATH   prepend PATH to connector search path
...
```
In the meantime I decided it was a good time to convert `optparse_t` to rfc 7 compliance, as well as expand the testuite, which uncovered other minor issues. While I was in there I fixed an annoying problem with `optparse_t` where all information from options used more than once was simply discarded with the last usage winning.
Now an `optparse_t` object tracks the number of times an option was …
=> optparse_t rfc 7 compliance, argument list support, test updates, and related fixes

src/modules/kvs/kvs.c, src/test/Makefile.am, t/Makefile.am, t/kvs/torture.c, t/kvs/watch.c, t/t1000-kvs-basic.t
This fixes #441 and adds a regression test for it.
Also, kvs tests from `src/test/` were moved to `t/kvs/`  and their sharness drivers updated accordingly.
=> fix kvs walk: corrupt internal storage

t/Makefile.am, t/scripts/kvs-watch-until.lua, t/scripts/waitfile.lua, t/t2000-wreck.t
This PR includes fixes (probable fixes) for two intermittent failures in wreck tests
* failure in --error test (issue #444)
* intermittent failures in `flux wreck kill` test
=> testsuite: fix intermittent failures in t2000-wreck.t

src/bindings/lua/Makefile.am
The sed was not removing the last component, despite matching.  This
need not be the final solution, but with it as it was, I couldn't pass
building the lua bindings.
=> fix LN issue in lua binding makefiles on LC

doc/man3/Makefile.am, doc/man3/flux_child_watcher_create.adoc, doc/man3/flux_reactor_create.adoc, doc/man3/flux_signal_watcher_create.adoc, doc/man3/flux_stat_watcher_create.adoc, doc/test/spell.en.pws, src/broker/broker.c, src/cmd/flux-start.c, src/common/libflux/Makefile.am, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libflux/test/reactor.c, src/modules/libsubprocess/Makefile.am, src/modules/libsubprocess/subprocess.c, src/modules/libsubprocess/subprocess.h, src/modules/libsubprocess/test/loop.c, src/modules/libsubprocess/test/socketpair.c, src/modules/libsubprocess/test/subprocess.c, src/modules/libzio/zio.c, t/loop/reactor.c
Not ready to merge  - here for early review:
This PR adds reactor child watchers, for capturing change in status of child processes.  It's a thin  wrapper around ev_child watchers.  Since child watchers are only supported in libev's "main loop", I had to add a flag to `flux_reactor_create()` so that one can pass in FLUX_REACTOR_MAIN flag if one wants to use child watchers.   The idea is that only a "main thread" in a multi-threaded application would install signal handlers, and it would create its reactor loop with this flag.  If you try to add a child watcher to a reactor without this flag it is an EINVAL error.
Child watchers are then integrated with libsubprocess, so that each subprocess internally adds a child watcher, and the subprocess exit handlers are called via the child watcher …
=> add reactor child watchers

doc/man3/flux_stat_watcher_create.adoc, doc/test/spell.en.pws, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libflux/test/reactor.c
Add missing _interval_ parameter to `flux_stat_watcher_create()`.  If inotify is unavailable, this allows the interval between stat(2) calls to be tuned.
Update test and man page.
=> allow stat watcher polling interval to be specified

src/bindings/lua/flux-lua.c, t/Makefile.am, t/fluxometer.lua.in, t/lua/t0002-rpc.t, t/lua/t0008-mrpc.t, t/lua/t1002-kvs.t, t/lua/t1003-iowatcher.t, t/lua/t1004-statwatcher.t, t/lua/t1005-fdwatcher.t, t/scripts/waitfile.lua
This PR pulls some of the lua bindings work for #437 into a standalone PR. This is somewhat a set of changes required for stdin handling, but also various other fixes and updates found and made along the way, including:
* Add support from Lua for `stat_watcher` as well as a simpler `fd_watcher` than the `iowatcher` currently implemented
* Some direct bindings for kvs calls such as `kvs_symlink` and `kvs_type` as well as `kvs_put/get`
* support `flux_reactor_stop_error`
* support `is_dir = true` with kvswatcher to watch kvs directory
* Fixes for iowatcher return values
* Expand lua binding tests
* Lua tests now run in "trash directory" like sharness tests for easy cleanup
* Update `scripts/waitfile.lua` to use statwatcher
=> Update lua bindings with some new watchers and low level kvs calls

t/fluxometer.lua.in, t/lua/t1004-statwatcher.t, t/lua/t1005-fdwatcher.t
Oops, this fixes a couple issues I found after the latest PR was merged:
* subdirectory creation/removal for Lua tests wasn't working. Fixed.
* statwatcher test was leaking a file handle so its subdirectory couldn't be removed during cleanup
* skip all tests in fdwatcher test if `posix.pipe` binding isn't implemented.
=> lua testing fixes

src/modules/libjsc/jstatctl.c
This fixes a false error report when successfully extracting the walltime.
=> jsc: fixed log level typo in extract_raw_walltime()

configure.ac, doc/man1/flux-broker.adoc, doc/test/spell.en.pws, src/broker/broker.c, src/broker/snoop.c, src/broker/snoop.h, src/cmd/flux-start.c, src/common/Makefile.am, src/common/libpmi-client/pmi-client.h, src/common/libpmi-client/pmi-simple.c, src/common/libpmi-server/Makefile.am, src/common/libpmi-server/simple.c, src/common/libpmi-server/simple.h, t/Makefile.am, t/pmi/simple.c
This PR implements a small "protocol engine" for the PMI simple v1 wire protocol, for the server side and then uses it and the recently added `subprocess_socketpair()` call to implement PMI as a bootstrap option for brokers in `flux-start`.
We could go a step further and eliminate the `--rank, --size, and --boot-method=LOCAL` code in the broker and make this the default way that `flux-start` operates, but I stopped short of that.
It's worth noting that this subset of PMI1 lacks `PMI_Get_id()` (used to communicate a non-numeric job id) and `PMI_Get_clique_ranks()` (used to determine which ranks can communicate over ipc versus tcp).  
Also, in this iteration I didn't bother implementing the protocol operations for `PMI_Publish_name()` , `PMI_Unpublish_name()`, `PMI_Lookup_name()`, or …
=> implement library for PMI simple v1 wire protocol server side

doc/man1/flux-wreck.adoc, doc/man1/flux-wreckrun.adoc, doc/test/spell.en.pws, src/bindings/lua/wreck.lua, src/bindings/lua/wreck/io.lua, src/cmd/flux-wreck, src/cmd/flux-wreckrun, src/modules/libjsc/README.md, src/modules/libjsc/jstatctl.c, src/modules/libjsc/jstatctl.h, src/modules/wreck/Makefile.am, src/modules/wreck/lua.d/input.lua, src/modules/wreck/lua.d/output.lua, src/modules/wreck/lua.d/timeout.lua, src/modules/wreck/wrexecd.c, t/t2000-wreck.t, t/t2001-jsc.t
This PR includes a fix for Issue #435. The code probably never worked (as evidenced by lack of testing), but the fix was simple enough for now.
I should note that currently, `flux-wreckrun` only supports sending stdin to rank 0. Probably for completeness, stdin broadcast at least should be supported, and a `--input` option should be provided akin to `--output` to read stdin from a file.
=> Fix wreck stdin handling

src/modules/resource-hwloc/resource.c, src/modules/wreck/wrexecd.c
This PR has a couple small fixes, most notably a fix for wreckrun failures Tapasya was experiencing on cab. The issue here was uninitialized `errnum` in `rexecd_init`, which when randomly initialized to non-zero would trigger global failure of job as "initialization failure".
The other fix replaces fprintf() debug with a call to flux_log() in resource-hwloc. @garlick has a similar fix sitting in #471 -- I'm fine with either version.
=> fix invalid errors in wreckrun initialization, use flux_log instead of printf for debug in resource-hwloc

src/modules/kvs/kvs.c
I was running some valgrind tests, which seemed to indicate a small leak in the watch request callback of the kvs. I know @garlick is working in this area already, so feel free to close this PR if it is made invalid by your work, or you've already got a fix.
=> modules/kvs: plug leak in watch_request_cb

src/modules/wreck/wrexecd.c, src/test/travis-dep-builder.sh
This PR should resolve test failures for `flux wreck kill` as reported in #448. The problem is that the kill request is handled by sending a signal to the process group for each task, which the tasks should be moved to during startup. However, there is a small window where a job can be in "running" state, but one or more tasks has not yet been put in its own process group (this is done as a place holder for containment, and should be handled a different way in the wreck replacement). This PR addresses this race by first calling `setpgrp(2)` immediately in the child, and by falling back to a simple `kill(2)` if `killpg(2)` fails, as this likely means the task is still initializing anyway.
Also, due to missing libsodium-1.0.0 on downloads.libsodium.org, this PR also updates libsodium for …
=> fix race in signal delivery for jobs in "running" state

src/broker/broker.c, src/broker/module.c, src/cmd/flux-event.c, t/Makefile.am, t/scripts/t0004-event-helper.sh, t/t0004-event.t
Avoid re-processing events that are received on rank 0 over ring network.
Add a test to ensure that events originating from all ranks are received in the proper order, without dups on rank 0.
Fixes #477
=> fix duplicate event issue

doc/man1/Makefile.am, doc/man1/flux-submit.adoc, doc/man1/flux-wreck.adoc, src/bindings/lua/wreck.lua, src/broker/Makefile.am, src/broker/broker.c, src/broker/sequence.c, src/broker/sequence.h, src/cmd/Makefile.am, src/cmd/flux-submit, src/cmd/flux-wreck, src/cmd/flux-wreckrun, src/modules/wreck/job.c, t/Makefile.am, t/lua/t0009-sequences.t, t/t2000-wreck.t
This PR is still a bit of a work in progress, but I wanted to open it and get early comments.
This PR reworks the `job` module a bit and adds a simple `job.submit` service. The `job.submit` service simply creates a new job entry and sets the `submitted` state, iff the `sched` module is loaded -- returning ENOSYS otherwise.
New bindings are included in the `wreck.lua` module for `wreck:createjob()` and `wreck:submit()` to abstract common code, and a `flux-submit` command has been added directly to core. The `submit` command in flux-sched will still work, but can be removed once tests are updated to use the builtin submit command.
This PR also adds a simple named sequence service directly to the broker, and uses a `"lwj"` sequence to allocate jobids instead of using the `lwj.next-id` kvs …
=> add job.sumbit service, flux-submit(1) command, and global sequences for jobids

src/bindings/python/flux/Makefile.am, src/bindings/python/flux/wrapper.py, src/modules/libkz/kz.h
This patch adds a kz python module with the ability to "attach" a kz stream to
an output stream or file descriptor.  No support for arbitrary interactions
with a kz stream as yet, but sufficient to support cap/ATS efforts for the
time being.
In creating this, I found that python cffi does not like unnamed enums, hence the name added to the kz.h header's enum, and accessing those enums exposed a bug in the wrapper generator's accesses of C-defined non-callable, non-define data structures.
=> python: add minimal python kz support

src/bindings/python/flux/Makefile.am, src/common/libflux/flog.c, src/common/libflux/flog.h, src/common/libutil/Makefile.am, src/common/libutil/log.c, src/common/libutil/log.h, src/common/libutil/macros.h, src/modules/resource-hwloc/resource.c
This patch masks off cores that are disallowed for scheduling due to a cpuset
mask from the hwloc resource list in the kvs and elsewhere, includes quite a few more checks for intermediate failure of hwloc as well.  Fixes #461.
=> Mask cores outside the CPUSET of the spawning broker

doc/man3/Makefile.am, doc/man3/flux_respond.adoc, doc/man3/flux_rpc.adoc, doc/man3/flux_rpc_raw.adoc, doc/test/spell.en.pws, src/common/libflux/message.c, src/common/libflux/message.h, src/common/libflux/request.c, src/common/libflux/request.h, src/common/libflux/response.c, src/common/libflux/response.h, src/common/libflux/rpc.c, src/common/libflux/rpc.h, src/common/libflux/test/request.c, src/common/libflux/test/response.c, t/loop/rpc.c
This PR was split off from PR #471 (kvs backing store).  It adds high level message handling functions for raw payloads, which are used by the "content service" proposed in #471.  This includes variations of `flux_rpc()` and `flux_rpc_get()`:
```C
flux_rpc_t *flux_rpc_raw (flux_t h, const char *topic,
const void *data, int len,
uint32_t nodeid, int flags);
int flux_rpc_get_raw (flux_rpc_t *rpc, uint32_t *nodeid, void *data, int *len);
```
as well as a variant of `flux_respond()`:
```C
int flux_respond_raw (flux_t h, const flux_msg_t *request,
int errnum, const void *data, int len);
```
In addition there is some minor cleanup of low level message function prototypes, and cleanup of existing man pages.
I've added man pages and tests for the new functions.
=> add RPC functions for handling raw payloads

.travis.yml, src/broker/broker.c, src/cmd/flux.c, t/fluxometer.lua.in, t/t0001-basic.t, t/t1005-cmddriver.t, t/t2000-wreck.t
This PR mostly includes a few minor fixes and/or workarounds for flux config handling for installed Flux as described in #490 (mostly related to missing/unneeded config file for an installed version of flux)
Included as well are fixes and changes necessary for `FLUX_TEST_INSTALLED_PATH=/path/to/flux/bin make check`, and an additional Travis test target that uses this mechanism to test using an installed version of Flux, i.e. the equivalent of:
```
./configure --prefix=/tmp/flux
make && make install
FLUX_TEST_INSTALLED_PATH=/tmp/flux/bin make check
```
This should hopefully make it less likely we'll end up with code that works in-tree but not in the installed target.
=> temporary flux config fixes and workarounds, "make install" testing for Travis

src/test/travis-dep-builder.sh, t/scripts/waitfile.lua, t/t2000-wreck.t, t/t2001-jsc.t
This PR makes the updates described in #498 to hopefully improve reliability of t2000-wreck.t and t2001-jsc.t.
JSC tests are simplified to remove dependence on synchronization on multiple output files (pidfile *and* output file), and `waitfile.lua` is improved for usability, and given a `--count` option, which is used in wreck tests to wait until all output lines are written (or the timeout is reached)
=> update waitfile.lua, jsc, and wreck tests for robustness

src/common/libflux/dispatch.c, src/common/libflux/handle.c, src/common/libflux/tagpool.c, src/connectors/local/local.c, src/connectors/loop/loop.c, src/connectors/shmem/shmem.c, t/Makefile.am, t/issues/t0441-kvs-put-get.sh, t/issues/t0505-msg-handler-reg.lua, t/t1000-kvs-basic.t, t/t4000-issues-test-driver.t
This PR should address issue #505, where installing a message handler from within a message handler caused problems with message delivery.  It also addresses creating, destroying, and stopping a message handler from within a message handler.
This still needs a test but I wanted to get it out there for review.
Also, while developing this on c9.io, I began seeing intermittent failures of this test, which needs explaining:
```
$ lua/t1002-kvs.t --verbose --debugd
...
not ok 95 - reactor exited normally with Protocol error
```
=> allow message handlers to start stop from message handlers

doc/man1/flux.adoc, src/cmd/flux.c, src/common/libflux/conf.c, t/t1005-cmddriver.t
This PR implements some of what is described in #514.
These changes remove the following groups of options:
* `--lua-path`, `--lua-cpath`, and `--python-path`: These options are simply removed. The `flux(1)` utility still reads `LUA_PATH` `LUA_CPATH` and `PYTHONPATH` from the current environment, but the values are effectively appended instead of prepended as with the (now removed) cmdline options. If required, paths can be prepended using a config file, but it didn't seem like a valid approach to keep these language-specific options on the `flux` utlity at this time.
* `--broker-path`: I'm not sure this option was ever really used anywhere, so it is removed. `FLUX_BROKER_PATH` is still exported from the `flux` utility based on the current and built-in configuration, but this environment …
=> Remove some cmdline options from flux(1)

src/modules/libjsc/README.md, src/modules/libjsc/jstatctl.c, src/modules/libjsc/jstatctl.h, t/t2001-jsc.t
This PR is linked to [flux-sched#100](https://github.com/flux-framework/flux-sched/pull/100) and needed to test that PR. This allows schedsrv to target the correct broker-ranks set so as to spawn a job's processes on the allocated nodes. The managing rank information is now passed by schedsrv via the JSC_RDL_ALLOC_CONTAINING_RANK attribute. And JSC uses that information to target the right ranks set to request ncores.
=> jsc: support for JSC_RDL_ALLOC_CONTAINING_RANK

configure.ac, doc/Makefile.am, doc/man1/flux-broker.adoc, doc/man1/flux-getattr.adoc, doc/man3/flux_attr_get.adoc, doc/man7/COPYRIGHT.adoc, doc/man7/Makefile.am, doc/man7/flux-broker-attributes.adoc, src/broker/content-cache.c, src/cmd/flux.c, src/modules/content-sophia/content-sophia.c, src/modules/content-sqlite/content-sqlite.c, src/modules/kvs/Makefile.am, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/kvs.c, src/modules/kvs/libkvs.c, src/modules/kvs/proto.c, src/modules/kvs/proto.h, src/modules/kvs/test/proto.c, src/modules/kvs/test/waitqueue.c, src/modules/kvs/waitqueue.c, src/modules/kvs/waitqueue.h, src/modules/resource-hwloc/resource.c, t/Makefile.am, t/kvs/hashtest.c, t/t0011-content-cache.t, t/t0012-content-sqlite.t, t/t0013-content-sophia.t, t/t1000-kvs-basic.t
This PR Is not complete but I thought it should get some early high level review concurrently with progress refining it.
The [sophia](http://sphia.org/) embedable database engine is imported into `libflux-internal`, then a new module `cas` (content addressable store) is added which stores arbitrary blobs persistently.  The protocol is simple:  send a blob, get back an SHA1; send an SHA1, get back a blob.  blobs and SHA1's are sent using raw message payloads to avoid the overhead of json encoding.  Files are created in the same temporary directory as the ipc sockets and persist for the lifetime of the session only.  This module is then loaded automatically on rank 0 (only).
To test the cas service, two new operations were added to `flux-kvs`:  putobj and getobj.  These behave similar to …
=> kvs integration with content store

src/cmd/Makefile.am, src/cmd/flux-hwloc.c, t/Makefile.am, t/hwloc-data/1N/nonoverlapping/02-brokers/0.xml, t/hwloc-data/1N/nonoverlapping/02-brokers/1.xml, t/hwloc-data/1N/shared/02-brokers/0.xml, t/hwloc-data/1N/shared/02-brokers/1.xml, t/t2005-hwloc-basic.t
Add flux-hwloc as a high-level command to synchronously communicate with the resource-hwloc module. Add some test cases and fake hwloc data to drive testing. Details are in the commit messages.
=> hwloc: add front-end support for resource-hwloc module

src/cmd/flux.c, src/common/libutil/optparse.c, src/common/libutil/optparse.h, src/common/libutil/test/optparse.c
Ok, here's a series of fixes for some things I missed in the original PR. This includes a fix for segfault when running things like `flux content` with no extra args. Expected output is:
```
content: missing subcommand
Usage: flux content dropcache [OPTIONS]
or: flux content flush [OPTIONS]
or: flux content load [OPTIONS] BLOBREF
or: flux content store [OPTIONS]
Access content store
```
Hmm, should I also fix that error message to be `flux content: missing subcommand`?
=> optparse fixes

src/cmd/flux.c, t/t1005-cmddriver.t
This addresses, in some small part, issue #522.
It should at least allow `flux --secdir` to work as expected when running under an enclosing instance with a different secdir in the KVS config.
A test is added as well. I hope this was a good approach for now.
=> Fix or workaround Issue#522

t/fluxometer.lua.in, t/t2004-hydra.t
sharness tests in `t/` ostensibly allow testing with an installed `flux` binary by setting `FLUX_TEST_INSTALLED_PATH` (this of course doesn't work for all the build tests and built tests, but that is a slightly different issue)
When attempting to use `FLUX_TEST_INSTALLED_PATH` against the `/opt` install, I found the following minor problems and fixed them.
On this branch, a run of `FLUX_TEST_INSTALLED_PATH=/opt/flux-core/bin make check` seems to work (in this one instance, at least)
=> fix tests for FLUX_TEST_INSTALLED_PATH

src/cmd/builtin/broker.c, src/common/libutil/optparse.c, src/common/libutil/optparse.h, src/common/libutil/test/optparse.c
As described in #531, flux `broker` subcommand was eating options before passing to `flux-broker` because `optparse_run_subcommand` always pre-parses args for all subcommands.
This PR adds a new flag `OPTPARSE_SUBCMD_NOOPTS` to skip this auto-parse, and directly calls any subcommand callback before processing args.
For demonstration, `builtin/broker.c` is changed to use this flag, even though we talked about removing that builtin cmd in #531.
=> Allow optparse_run_subcommand to skip automatic parse_args

src/test/travis-dep-builder.sh
Adds the --no-check-certificate to wget in travis-dep-builder.sh to
eliminate the complaint that travis issues when onnecting to
www.open-mpi.org:
ERROR: no certificate subject alternative name matches
requested host name `www.open-mpi.org'.
To connect to www.open-mpi.org insecurely, use `--no-check-certificate'.
=> Eliminate no certificate subject alternative name matches

src/cmd/Makefile.am, src/cmd/builtin/version.c, t/t0010-generic-utils.t
Simply adds a `flux version` subcommand and a small test to ensure the basic functionality.
=> Add flux version

configure.ac, src/cmd/flux-comms.c, src/common/libflux/flog.c, src/common/libflux/flog.h, src/modules/barrier/barrier.c, src/modules/live/liblive.c, src/modules/live/live.c, src/modules/live/live.h, src/modules/resource-hwloc/Makefile.am, src/modules/resource-hwloc/resource.c
Replace resource-hwloc calls to `FLUX_CHECK_INT()` and `FLUX_CHECK_PTR()` with error paths that return RPC error responses or cause `mod_main()` to exit, with copious logging.  A bit of refactoring for clarity as well.
Fixes issue #536
=> clean up error paths in modules/resource-hwloc

src/modules/wreck/Makefile.am, src/modules/wreck/job.c, src/modules/wreck/wrexec.c
This PR includes some cleanup in `src/modules/wreck` to avoid exiting in broker context on error.
In addition:
- Removed unused mrpc interface from wrexec interface
- Fixed an old warning from `src/modules/wreck/Makefile.am` 
```
Makefile:923: target `-L/home/ubuntu/local/lib' given more than once in the same rule.
```
- Fix missing code coverage results for `job.c` and `wrexec.c`
=> Cleanup in modules/wreck

src/modules/connector-local/local.c
When the local connector needs to deliver a response or event
message to a client that has disconnected, it logs a "Broken pipe"
error that is not too helpful, as described in #542.
Make the eroror message a bit more helpful by including the topic
string and message type of the message that is being dropped.
=> connectors/local: improve broken pipe errors

etc/flux-core.pc.in
Fixes a couple stragglers which should have been included with commit
96e97dea2556680fda03d04cd3c607091523be82
Addresses:  https://github.com/flux-framework/flux-core/issues/551
=> correct flux library location

src/modules/connector-local/local.c
Will someone humor me and merge this PR?  I continue to see the problem first described in [Issue 556](https://github.com/flux-framework/flux-core/issues/556).  I have no idea why this problem only appears when building flux-core under flux-sched in the flux-framework travis build.  (I don't see the problem in my corresponding travis build).
The latest example: https://travis-ci.org/flux-framework/flux-sched/jobs/108577802
The offending lines start with this:
```
make[3]: Entering directory `/home/travis/flux-core/src/modules/connector-local'
CC     local.lo
local.c:56:5: error: unknown type name 'zlist_t'
zlist_t *clients;
^
local.c:60:5: error: unknown type name 'zhash_t'
zhash_t *subscriptions;
^
local.c:78:5: error: unknown type name 'zlist_t'
zlist_t *outqueue;  /* queue of outbound …
```
=> add #include <czmq.h> to local.c

doc/man1/flux-broker.adoc, doc/man1/flux-content.adoc, doc/man1/flux-dmesg.adoc, doc/man7/flux-broker-attributes.adoc, doc/test/spell.en.pws, src/bindings/python/test_commands/sideflux.py, src/broker/attr.c, src/broker/attr.h, src/broker/broker.c, src/broker/content-cache.c, src/broker/log.c, src/broker/log.h, src/broker/module.c, src/cmd/flux-start.c, src/modules/content-sophia/content-sophia.c, src/modules/content-sqlite/content-sqlite.c, t/fluxometer.lua, t/sharness.d/flux-sharness.sh, t/t0001-basic.t, t/t0008-attr.t, t/t0009-dmesg.t, t/t0011-content-cache.t, t/t0012-content-sqlite.t, t/t0013-content-sophia.t
Rather than postpone this until #508 is resolved, add `content-sqlite` to the hardwired module list in the broker so that we can avoid taking an OOM when running many jobs.
Fixes the long standing #259
=> load content-sqlite by default

.travis.yml, src/bindings/lua/flux-lua.c, t/lua/t1000-reactor.t, t/lua/t1002-kvs.t, t/sharness.d/flux-sharness.sh, t/t0001-basic.t, t/t0011-content-cache.t, t/t0012-content-sqlite.t, t/t0013-content-sophia.t, t/t1000-kvs-basic.t, t/t2002-pmi.t, t/t2005-hwloc-basic.t, t/t3000-mpi-basic.t
Ok, I wanted to open this PR and get feedback, haven't ensured Travis will pass yet though.
* Replace usage of `$(($(nproc)+1))` for sizing test sessions with a new function `test_size_large()` exported from th sharness suite. `test_size_large` gives a size of a "reasonably" large session for testing. The default size is `nproc+1` like before, but with a maximum of `17` and minimum of `4`. The max and min can be controlled with `FLUX_TEST_SIZE_MIN` and `FLUX_TEST_SIZE_MAX`
* Set `FLUX_TEST_SIZE_MAX=5` for Travis builds. We could do the same for RPM builds.
* Handle missing `lstopo` command in `t2005-hwloc-basic.t`
* Extend timeout in Lua kvs test, this was the cause of "Protocol Error" failures.
* Allow Lua API to return a "reason" string in `f:reactor_stop_error (reason)`, so we don't …
=> minor testsuite improvements

configure.ac, src/bindings/python/Makefile.am, t/Makefile.am, t/t9990-python-tests.t.in
The python tests are running to early, and making debugging difficult
for other parts of the system.  This patch moves the python test
execution to the end of the sharness tests.  It may need more
massaging, but seems to work for basic cases in my (partly
non-working) environment.
fixes #527 ?
=> Trial move of python test execution to ./t/

configure.ac
Change `${fluxcmddir}` from `${libexecdir}/flux/core`
to `${libexecdir}/flux/cmd`.  All framework projects can
put their subcommands in that directory.  The previous
naming implied that each would have its own sub-directory,
but that creates complications for maintaining FLUX_EXEC_PATH.
Affects flux-framework/flux-sched#115
=> build: change fluxcmddir to libexec/flux/cmd

NEWS
Consider this PR a proposal to tag flux-core.
See proposed release notes - I debated inserting PR and issue references and being much more detailed, but then I backed off thinking that detail is easily obtained from the git log as needed.   I ran this by @grondo offline and his comment was
> Good question and we should get one more opinion. However, I agree that any detail can be gleaned from the git commit log with a simple
```
git log 0.1.0..0.2.0
```
I could see adding a list of fixed issues, especially if there was
some way to gather it automatically. We'd have to be more careful
about putting "Fixes #XXX" in our commit messages
=> NEWS: update for 0.2.0 release

src/broker/content-cache.c, src/modules/content-sophia/content-sophia.c, src/modules/content-sqlite/content-sqlite.c
This patch adds some useful debug logging to the content cache flush code, as well as the shutdown code in each of the content backing stores.
Also address a logic error in the cache flush code which was causing many iterations through the content hash looking for dirty entries.
I hope this fixes #570.  If not, it adds some logging which will help us when it occurs.
=> content-cache: improve logging, fix flush logic

doc/man1/flux.adoc, doc/test/spell.en.pws, src/cmd/builtin.h, src/cmd/builtin/env.c, src/cmd/flux.c, t/sharness.d/01-setup.sh, t/sharness.d/flux-sharness.sh, t/t1005-cmddriver.t
Initial proposal that adds a set of environment variables `FLUX*PATH_PREPEND` to force the prepend of FLUX variables to the final environment.
This will be used mostly for testing, or to ensure some cmd or module overrides an installed version.
I also found that I'd dropped the functionality of `-v` from `flux(1)` before, so we add that back here...
=> Enhancements to ease development of framework project sharness testsuites

src/bindings/lua/wreck.lua, t/t2000-wreck.t
I can't get `waitfile.lua` tests to fail in travis right now, so let's just update the wreck tests to use the `-v, --verbose` flag on the script and hope that helps with diagnosis the next time there is a failure.
Also pushed a small fix for invalid reference to `self` in `src/bindings/lua/wreck.lua` uncovered by the tests.
=> testsuite: small fixes and debug enhancements for wreck tests

src/broker/content-cache.c, src/broker/module.c, src/connectors/shmem/shmem.c, src/modules/content-sophia/content-sophia.c, t/t0011-content-cache.t, t/t0012-content-sqlite.t, t/t0013-content-sophia.t
Requests might be "lost" if they arrive while a module is shutting down (e.g. while being unloaded).  This PR ensures those requests get an ENOSYS reply.  A debug message is logged for each message responded to here.
A theory for #570 is that store requests are lost and remain pending in the content-cache when the backing store module is unloaded.
=> ensure all requests to modules get a response

t/scripts/waitfile.lua, t/t0001-basic.t
The waitfile script held a vestige of a polling mode version that checked mtime of the target compared to the previous polling interval. With statwatcher, waitfile may wake up immediately on changes to the target file, and if this happens within one second of the previous check a false negative was returned from the `check()` function.
Remove the use of mtime, which shouldn't be required anyway if statwatcher is working.
This will likely resolve false timeouts as described in #569 -- however, I'd like to make sure we don't see any other failures for awhile before calling that Issue resolved.
I'd also like to attempt to write a testsuite for the waitfile script itself.
=> testsuite: attempt fix of statwatcher-based waitfile script

src/bindings/lua/wreck.lua, t/scripts/waitfile.lua, t/t0001-basic.t, t/t0006-build-basic.t, t/t2004-hydra.t
This PR fixes missing logfiles for tests that don't run `test_under_flux` when `FLUX_TESTS_LOGFILE` is set (for now we do this by hand in each test), a small fix for wreck.lua error output when nnodes requested > nnodes available, and an update for the `waitfile.lua` tests that allow dynamically loaded code to actually drive the tests to avoid synchronization problems when trying to "test the test".
=> Fix for waitfile.lua tests and missing logfiles of tests that don't use test_under_flux

src/cmd/flux-logger.c, src/common/libflux/flog.c, src/common/libflux/flog.h, t/Makefile.am, t/loop/log.c
Change `flux_log()` return to void, and preserve errno.
=> avoid clobbering errno in flux_log() functions

src/cmd/builtin/help.c, t/t0001-basic.t
This fixes a really minor issue with `flux help nosuchcommand` -- it exits with success. This PR just fixes `flux help` to exit with the same exit code as `man(1)` and also adds some basic tests for `flux help CMD`
=> flux-help: exit with nonzero exit code when man(1) does

src/broker/broker.c
Since the config file is optional, it's not appropriate to
complain if there isn't one.  Suppress the message unless
running with --verbose.
Fixes #602
=> broker: suppress config failed to load message

Makefile.am, configure.ac, src/broker/content-cache.c, src/broker/modservice.c, src/broker/module.c, src/common/Makefile.am, src/common/libflux/dispatch.c, src/common/libflux/module.c, src/common/libminilzo/COPYING, src/common/libminilzo/Makefile.am, src/common/libminilzo/README.LZO, src/common/libminilzo/lzoconf.h, src/common/libminilzo/lzodefs.h, src/common/libminilzo/minilzo.c, src/common/libminilzo/minilzo.h, src/common/libminilzo/test/mini.c, src/common/libutil/ipaddr.c, src/modules/content-sqlite/content-sqlite.c, src/modules/kvs/kvs.c, src/modules/wreck/wrexec.c, src/test/Makefile.am, src/test/soak-workload.sh, src/test/soak.sh, src/test/valgrind-workload.sh, src/test/valgrind.sh, t/Makefile.am
Here is an assortment of fixes for issues that came up when running a single node "soak test", basically starting an 8-way instance and running 8-way jobs back to back.
Eventually I was able to run close to 20K jobs (until I ran out of disk).  There are still some memory leaks (issue #607) and decaying launch times (issue #604) and a problem with the size of the on-disk content cache (issue #609), but prior to the fixes in this PR, I couldn't get past about 2K jobs, so progress.
=> misc fixes from soak testing

t/scripts/waitfile.lua
As described in #612, there was another race in the `waitfile.lua` script.
While the initial call to `self:check()` was done *after* the stat watcher was started, the `stat(2)` initialization in the script was for some reason done *before* the stat watcher creation. This means if a file was created or changed in the interval between that first `stat(2)` and stat watcher creation, the script would fail to detect that change.
This PR fixes that issue by moving the `stat()` call to right before the first `check()` and most importantly after the stat watcher is created.
Also, from an idea by @lipari, add the target filename to the scripts logging output -- useful for debugging.
=> Fix small race in t/scripts/waitfile.lua

src/modules/wreck/job.c, src/modules/wreck/wrexecd.c, t/t2000-wreck.t
This PR implements @garlick's ideas from #614 to limit object store growth while running many jobs.
The basic changes here include 
* The `job` module creates the new jobid entry in `lwj-active.<id>` instead of directly in `lwj.<id>`, then before the first `kvs_commit`, it creates a symlink: `lwj.<id> -> lwj-active.<id>`
* The rest of the wreck code operates as before via the `lwj.<id>` symlink
* At job completion, the relative rank 0 `wrexecd` uses `kvs_move` to move `lwj-active.<id>` to `lwj.<id>` replacing the destination soft link with the actual contents.
=> stash active jobs under alternate kvs heirarchy

src/modules/connector-local/local.c, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/kvs.c, src/modules/kvs/waitqueue.c, src/modules/kvs/waitqueue.h, src/modules/libkz/kz.c, t/t2000-wreck.t
This PR fixes a `kvs_watch()` state leak.  The watch request would be removed from the "watchlist" and placed on another wait queue if it needed to wait for content to be faulted in.  If in the mean time a disconnect request was received, the watch request would not be found on the watchlist.  Then once the fault was handled, the watch request would be restarted and would place itself back on the watchlist.
The fix is to also walk the KVS internal cache looking for a match when a client disconnects, and also when a watch request is explicitly unwatched.
=> fix KVS watch leak

doc/man7/flux-broker-attributes.adoc, etc/flux.conf.in, etc/rc1, src/broker/Makefile.am, src/broker/broker.c, src/broker/log.c, src/broker/runlevel.c, src/broker/runlevel.h, src/cmd/flux-comms.c, src/connectors/local/local.c, src/lib/libpmi/pmi.c, src/modules/Makefile.am, src/modules/live/Makefile.am, src/modules/live/live.c, src/test/soak.sh, t/mpi/hello.c, t/t0010-generic-utils.t, t/t2002-pmi.t
In this PR
* pmi tracing is improved, and redirected to the flux_log at LOG_DEBUG level
* a logic error in broker logging is fixed, and logging attribute docs updated
* set I_MPI_PMI_LIBRARY in environment for Intel MPI support
It seems a little wrong to always set the environment variable specific to the Intel MPI runtime, so wanted to get some feedback on that.  (Maybe it is OK for the short term, but what is the correct long term way to do this?)
=> some minor change related to MPI support + fixes

src/bindings/lua/wreck.lua, src/cmd/flux-wreck, src/common/libsubprocess/subprocess.c, src/common/libutil/Makefile.am, src/common/libutil/fdwalk.c, src/common/libutil/fdwalk.h, src/modules/wreck/lua.d/input.lua, src/modules/wreck/wrexecd.c, src/test/travis-dep-builder.sh
this PR might still be a bit of a WIP, but posting it now in case there are comments, requirements, etc.
This PR comprises the following somewhat minor fixes:
* in wrexecd, instead of closing all file descriptors from maxfd to `sysconf (_SC_OPEN_MAX)`, walk `/proc/self/fd` and close only open fds. Noticed on c9.io that `_SC_OPEN_MAX` was over 1M.
* Add a `flux wreck timing` subcommand that lists the following finer granularity times recorded by wrexecd, in case they are useful:
- STARTING: reserved->starting
- RUNNING:  starting->running
- COMPLETE: running->complete
- TOTAL:    starting->complete
* Do not use `affinity.cpuset` in `input.lua` plugin -- it doesn't support tasks > 1024
* In travis, pull libsodium from github, older openssl version in travis container apparently doesn't …
=> various minor wreck fixes

etc/rc1, etc/rc3, src/bindings/python/test/handle.py, src/broker/broker.c, src/broker/modservice.c, src/broker/overlay.c, src/cmd/flux-up.c, src/common/libflux/message.c, src/common/libflux/module.c, src/common/libflux/test/message.c, src/common/libutil/iterators.h, src/modules/kvs/kvs.c, src/modules/live/live.c, t/loop/multrpc.c, t/loop/rpc.c, t/lua/t0001-send-recv.t, t/lua/t0002-rpc.t
The main point of this PR is to comment out the live module in rc1, rc3 as proposed in #638.  Note that `flux up` still works, as it already contained fallback code to return all nodes up if the KVS key containing the live module's monitoring results is not found.
Not loading the live module broke some tests which send ping requests to the live module.  When updating those tests to ping the broker rather than a module, I hit the segfault discussed in #181, where a test was attempting to elicit EPROTO by sending a json array as payload to a ping request.  This would trigger a segfault in shortjson.h without workaround code that was added to the module ping handler but not the broker one.
It seemed like a good idea to tie up this loose end, so the few places where arrays were being sent as …
=> disable live module, require JSON payloads to be JSON objects

src/common/libutil/cleanup.c
O_PATH is unavailable on Centos 6 based distros.
If unavailable, simply define it to 0.  The openat()
call should still work fine.
Fixes #646
=> libutil/cleanup: handle undefined O_PATH flag

src/modules/resource-hwloc/resource.c
Compare at runtime the version of the hwloc library API against the
API hwloc version linked at compile time.  ctx_hwloc_init() fails if
the major release numbers do not match.
This replicates functionality added to flux-sched as part of [PR 152](https://github.com/flux-framework/flux-sched/pull/152)
=> Add hwloc API version check

src/bindings/python/flux/core/watchers.py
Newer python revisions accidentally collect the handle that contains the
C-compatible pointer to the python timer data.  This patch adds a
backreference to the object so that it will not be collected as long as
the user holds on to the python timer object.
Fixes #629
=> python: resolve accidental collection of watchers

configure.ac, doc/man1/Makefile.am, doc/man1/flux-proxy.adoc, doc/man3/flux_get_reactor.adoc, doc/test/spell.en.pws, src/broker/broker.c, src/cmd/Makefile.am, src/cmd/builtin/attr.c, src/cmd/builtin/proxy.c, src/cmd/flux-event.c, src/common/libflux/handle.c, src/common/libflux/message.c, src/common/libflux/message.h, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libflux/test/message.c, src/common/libutil/Makefile.am, src/common/libutil/popen2.c, src/common/libutil/popen2.h, src/common/libutil/test/popen2.c, src/connectors/Makefile.am, src/connectors/ssh/Makefile.am, src/connectors/ssh/ssh.c, src/modules/connector-local/local.c, t/Makefile.am, t/scripts/tssh, t/t1008-proxy.t
As discussed in #644, this PR implements a new ssh:// connector.
Unfinished but wanted to get it up here for any prelim. review.
I had to create a new `popen()` like function called `pxopen()` that uses a socketpair to establish bidirectional communication with a subprocess, which will usually be /usr/bin./ssh or maybe /usr/bin/rsh on our clusters.  It seems a bit odd to have `flux_open()` behind the scenes do a fork/exec - hopefully that is not going to cause problems.
The remote command is currently `flux proxy` as proposed in #645 although maybe the first pass on this should just use netcat.
=> implement ssh connector

doc/man1/flux-start.adoc, doc/test/spell.en.pws, src/broker/broker.c, src/cmd/flux-start.c, src/common/libutil/test/popen2.c, src/lib/libpmi/pmi.c, t/t0001-basic.t, t/t2003-recurse.t
As discussed in #643, the current usage for starting Flux under slurm is a bit awkward:
```
srun -N8 flux broker initial-program
```
If `flux-start` simply execs the broker whenever size=1 (the default size), and the broker attempts to bootstrap first with PMI, then with "local", we should be able to support
```
srun -N8 flux start initial-program
```
without needing to probe PMI from flux-start.
This PR takes that approach.   Apparently something in it has made the sharness runlevel tests sad as they seem to hang now, but I wanted to post this to get a little feedback as to whether this seems like the right approach.
=> better user interface for launching flux under flux/slurm

src/bindings/lua/flux-lua.c, src/bindings/lua/wreck.lua, src/lib/libpmi/pmi.c, src/modules/wreck/Makefile.am, src/modules/wreck/lua.d/intel_mpi.lua, src/modules/wreck/lua.d/mvapich.lua, src/modules/wreck/wrexecd.c, t/Makefile.am, t/lua/t0004-getattr.t, t/t2002-pmi.t
Who would vote against cleaning up the environment?
As discussed in #669, it may be desirable to localize an environment (or other) trickery needed to run a particular MPI runtime under Flux within a wreck lua plugin.
This PR first does a tiny bit of housekeeping, then moves the setting of MPIRUN_RANK, MPIRUN_NPROCS, and MPIRUN_RSH_LAUNCH from wrexecd.c and bindings/lua/wreck.lua to a new mvapich plugin.
Todo
The todos require a way to determine the path to the Flux libpmi.so, which is currently found by first checking the config in a broker attribute, and falling back to compiled-in install paths.
=> environment cleanup

src/cmd/builtin/help.c, t/t0001-basic.t
As described in #676 we have some cases where `flux help COMMAND` will confusingly display non-flux related manpages after a user quits the flux man page. (e.g. `flux help cron`, `flux help exec`)
This PR uses a simple heuristic to determine whether to prepend `flux-` to the topic to send to `man(1)`, instead of running `man flux-%s %s`. It assumes that if the help topic already starts with `flux`, we don't need to prepend `flux-` and runs `man %s` directly. If the topic does *not* start with `flux`, then likely this is a request for help with `flux` subcommand, so we run `man flux-%s` only.
This will break if ever there is a manpage `flux-flux-something` (unlikely) or if there is a man page for a command or API function that *doesn't* start with `flux`. So far I don't think that is the …
=> flux-help: better heuristic for display flux-related man pages

src/cmd/cmdhelp.c, src/cmd/flux.c, t/t0001-basic.t
As described in #655, `flux-help` search pattern for command list needs a way to be extended, for cases where flux framework projects are installed in a separate directory structure from flux-core.
This PR changes the function of the `FLUX_CMDHELP_PATTERN` environment variable, from replacing a default single search pattern, to appending a *list* of patterns separated by `":"`. There wasn't a use case for replacing the default pattern, so I don't think this change will have any negative effect.
=> flux-help: allow command help search pattern to be extended

src/common/libpmi-client/pmi.c, src/common/libsubprocess/subprocess.c
I'm not sure how long until PR #668 will be ready, but these two commits probably are, so I broke them out to their own PR here.
When launching large (e.g. 512 - 1024) flux sessions on a single node, I ran out of file descriptors and the zio constructors in `subprocess_create()` were failing.  This patch ensures that the right error gets back to the caller.
The little hack in the pmi client would allow a PMIx enabled RM to launch flux.  Why not?  There might be one that works someday.
=> subprocess error handling, pmix launch support

src/bindings/lua/flux-lua.c, src/bindings/python/flux/core/handle.py, src/bindings/python/flux/core/watchers.py, src/cmd/builtin/content.c, src/common/libcompat/reactor.c, src/common/libflux/dispatch.c, src/common/libflux/handle.c, src/common/libflux/handle.h, src/common/libflux/message.c, src/common/libflux/message.h, src/common/libflux/rpc.c, src/common/libflux/tagpool.c, src/common/libflux/tagpool.h, src/common/libflux/test/message.c, src/common/libflux/test/tagpool.c, src/modules/cron/task.c, src/modules/kvs/libkvs.c, src/modules/wreck/job.c, t/kvs/watch.c, t/t0011-content-cache.t
This PR replaces "matchtag blocks" with "matchtag groups" as discussed in #680.  Basically the 32 bit matchtag is divided into the high order (12 bit) group part and low order (20 bit) part.  When a `flux_rpc_multi()` call is made, instead of allocating a block of matchtags, it allocates a single "group matchtag", which has one or more high order bits set and low order bits zeroed.
The dispatcher and `flux_recv()` then simply match on the group tag, ignoring the lower order bits, rather than matching in a block (range).
Besides some cleanup/simplification, this allows the low order 20 bits to be "user defined" when a group matchtag is used.  For example, `flux_rpc_multi()` stores the nodeid in there and then doesn't have to use a lookup table to map matchtag to nodeid.
The `bsize` field …
=> Tagged response fastpath

.travis.yml, doc/man1/flux-cron.adoc, doc/man3/Makefile.am, doc/man3/flux_periodic_watcher_create.adoc, doc/man3/flux_watcher_start.adoc, doc/test/spell.en.pws, src/cmd/flux-cron, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libflux/test/reactor.c, src/common/libutil/Makefile.am, src/common/libutil/approxidate.c, src/common/libutil/approxidate.h, src/common/libutil/cronodate.c, src/common/libutil/cronodate.h, src/common/libutil/nodeset.c, src/common/libutil/nodeset.h, src/common/libutil/test/approxidate.c, src/common/libutil/test/cronodate.c, src/common/libutil/test/nodeset.c, src/modules/cron/Makefile.am, src/modules/cron/cron.c, src/modules/cron/datetime.c, src/modules/cron/entry.h, src/modules/cron/interval.c, src/modules/cron/types.c, src/test/travis-dep-builder.sh, t/Makefile.am, t/t0016-cron-faketime.t
This isn't quite ready yet, but I'm throwing it up here now because it may need more than usual review.
The main purpose of this work was to support cron-like date&time matching for flux-cron. Along the way a lot of other "improvements"(?)(remains to be seen) were developed to support the main goal of calculating the amount of time until the next scheduled wakeup for a datetime matching interface such as that cron expressions provide.
Furthermore, to ensure wakeup on the scheduled datetime, the [`ev_periodic`](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#code_ev_periodic_code_to_cron_or_not) watcher is now exposed via a `flux_periodic_watcher`.
The kind of "date and time cron expression matching" interface is abstracted here into a small module called `cronodate`, which is simply …
=> cron-o-date: cron expression support for flux-cron 

doc/man3/flux_periodic_watcher_create.adoc, src/modules/cron/cron.c
This PR fixes some oops in the recently mergeed PR #686. Most of these are the most egregious buglets found by Coverity run on recent master, however there was also a bad typo in the manpage for `flux_periodic_watcher_create` which was causing an error from asciidoc.
I quickly threw these up so as to fix the build failure in doc/man3, so there might still be more work or issues.
=> Cronodate PR fixups

t/t0016-cron-faketime.t
Instead of using ldd to check to see if libfaketime.so
can be found, try a test by setting a faketime for /bin/date
using a known epoch and check for expected result.
This should be more reliable than the previous test.
@garlick can you give this commit a test on your desktop? Thanks!
=> t/t0016-cron-faketime.t: improve faketime check

.travis.yml, src/bindings/lua/tests/zmsg-test.c, src/common/libutil/test/msglist.c, src/test/cppcheck.sh, src/test/kap/kap_opts.c, src/test/kap/kap_personality.c, src/test/travis-dep-builder.sh
This PR adds a new `cppcheck` build to the Travis CI build matrix for flux-core.
For the cppcheck build, a trivial script in `src/test/cppcheck.sh` is run instead of the normal  build. In my short amount of testing this seemed to find some obvious errors like memory leaks, etc. A couple of these (in tests only) were fixed in this branch in order to run with a "clean" cppcheck initially.
There are also a list of paths that `cppcheck.sh` ignores by default, including upstream packages like liblsd, libsophia, and liblsd, as well as the autogenerated python bindings etc. The full list can be viewed (and updated) in the simple `cppcheck.sh` script.
=> Add cppcheck run to travis build matrix

.travis.yml, src/test/backtrace-all.sh
Experimental PR to support coredump backtraces in travis-ci.
The travis-ci containers have `/proc/sys/kernel/core_pattern` as `|/usr/share/apport/apport %p %s %c %P`, possibly inherited from the host kernel (See travis-ci/travis-ci#3754). When apport is not installed, all coredumps are lost. Until travis implements a method to reset core_pattern, installation of apport package seems to direct corefiles to the cwd of the dumping process so we can at least examine them.
apport also seems to respect current corefile limit, so if `ulimit -c unlimited` is also set for travis run, we do seem to be able to get corefiles inside a travis.
To analyze any coredump that might be generated during travis run, a `backtrace-all.sh` script is added and run from the `after_failure` hook.
Proof of concept …
=> Enable coredumps on travis-ci

src/modules/wreck/lua.d/intel_mpi.lua, src/modules/wreck/lua.d/mvapich.lua, t/issues/t0704-mpirun-rank.sh
As noted in #630, Intel MPI seems to need some SLURM environment variables for now.
Also, we're setting MPIRUN_RANK incorrectly in the `mvapich.lua` plugin. This PR fixes that and adds a test for it.
If we want to wait on the `intel_mpi.lua` changes for now, I can back that one out.
=> wreck: fix MPIRUN_RANK, set SLURM env vars for Intel MPI

src/cmd/flux-start.c, src/common/libpmi-server/simple.c, src/common/libpmi-server/simple.h, src/modules/kvs/kvs.h, src/modules/kvs/libkvs.c, t/pmi/simple.c, t/t2004-hydra.t, t/t3000-mpi-basic.t
Here's the split kvs_fence call discussed in #707 and #706.
I'll add the libpmi-server barrier completion callback after lunch.
=> modules/kvs: add async fence operations

.travis.yml, src/bindings/lua/wreck.lua, src/common/libsubprocess/zio.c, src/common/libsubprocess/zio.h, src/modules/wreck/Makefile.am, src/modules/wreck/lua.d/pmi-mapping.lua, src/modules/wreck/wrexecd.c, t/t2002-pmi.t, t/t3000-mpi-basic.t
This PR is a quick and dirty addition of pmi-simple server to `wrexecd`. By default wrexec jobs will have `PMI_FD` etc set in environment and, if supported, simple-pmi enabled MPI and other programs will use PMI-1 wire protocol instead of a `libpmi.so` library.
To disable pmi-server, set `-o no-pmi-server` on `flux wreckrun` cmdline.
This has only had cursory testing at this point, but up for early review. It is based on top of #708
=> Add pmi-simple server to wrexecd

src/bindings/lua/flux-lua.c, src/common/libsubprocess/subprocess.c, src/common/libsubprocess/test/zio.c, src/common/libsubprocess/zio.c, src/common/libsubprocess/zio.h, src/modules/wreck/wrexecd.c
I was going to wait to include this commit in a future PR with zio work/replacement, but this is a needed cleanup and standalone, so I'm just including it now. It removes a bit of unused code, and an unnecessary argument/member to the zio struct.
=> libsubprocess/zio: remove ancient zmq socket arg

doc/man1/flux-hwloc.adoc, src/cmd/builtin/hwloc.c, src/modules/resource-hwloc/resource.c, t/t2005-hwloc-basic.t
Fixes #716.
This PR disables `walk_topology()` by default as described in #716, with some other minor fixes along the way. A new module option, `walk_topology`, can be used to force the topology walk and broken down entries in the kvs, or a new `flux hwloc reload --walk-topology=yes` can be used to force the behavior at reload time (this will be the default for the next reload as well).
Along the way, it seemed like the `resource-hwloc.load` request was no longer used, so it is removed. I assume the `reload` request is what we want.
Some possible weirdness that I might need to fix:
* json payload in reload request is optional -- not sure if that is a good idea or not. If there is a payload, and `walk_topology` boolean is set, that is used as the new value for `ctx->walk_topology`
* `flux …
=> resource-hwloc: disable walk_topology() by default

src/bindings/python/flux/core/handle.py, src/bindings/python/flux/rpc.py, src/bindings/python/test/handle.py
rpc.py:
- flux_rpc_get allows a NULL to be passed in for nodeid, so for
rpc.get_str (in python), don't allocate space for an additional uint
that ends up being free'd immediately after the function call, just pass
in NULL
handle.py:
- remove erroneous bsize argument from MessageWatcher constructor call
- Add a get_rank method/interface to the handle
=> python: minor fixes and addition to the bindings

config/x_ac_sanitize.m4, configure.ac, src/bindings/lua/Makefile.am, src/bindings/python/flux/Makefile.am, src/common/Makefile.am, src/common/libutil/test/cronodate.c, src/common/libutil/test/nodeset.c, src/connectors/local/Makefile.am, src/connectors/loop/Makefile.am, src/connectors/shmem/Makefile.am, src/connectors/ssh/Makefile.am, src/modules/libjsc/jstatctl.c
Initial support for AddressSanitizer (ASan) and ThreadSanitizer (TSan).
This is tested with `clang-omp-3.5.0` installed at LLNL TOSS2 systems (e.g., Cab). For example, 
```
% use clang-omp-3.5.0
% ./configure CC=clang
```
Also mildly tested with `gcc 4.9.3p.` For example, 
```
% use gcc 4.9.3p
% ./configure
```
=> Add support for Sanitizer tools

src/modules/kvs/Makefile.am, src/modules/kvs/json_dirent.c, src/modules/kvs/json_dirent.h, src/modules/kvs/kvs.c, src/modules/kvs/libkvs.c, src/modules/resource-hwloc/resource.c, t/Makefile.am, t/kvs/asyncfence.c, t/t1000-kvs-basic.t
This PR was created to address issue #729, where wreck's use of the async fence operations `kvs_fence_begin()`, `kvs_fence_finish()` was in rare cases allowing a put to be issued while a fence was in progress.  This was not allowed by the KVS, not for any good reason, just because of the simplistic  way client state was tracked.
In trying to decide how to fix this without destabilizing the KVS code base,  it seemed like a low-risk
approach was to move "put" processing to the client, and piggyback the put data on the commit/fence message.  This could be done without changing the protocol since the commit request already included an optional "operations" JSON array.  The put, mkdir, symlink, unlink calls now return immediately (no RPC), except in the case of a put of a value larger than its …
=> consolidate kvs put and commit requests internally

src/common/Makefile.am, src/common/libpmi/pmi.c, src/common/libpmi/test/pminfo.c, src/common/libpmi/wrap.c, t/t2002-pmi.t
The `flux_pmi_library` symbol should not be exported from `libflux.so`, only `libpmi.so`, as noted in #736.
A test of the above failsafe for self-dlopen were added to the PMI sharness test.
Finally, I noticed and corrected inappropriate use of PMI_ERR_INIT in the main PMI library, and added some additional sanity checks on PMI environment variables and a run of "pminfo" to the PMI sharness test.
=> Fix PMI failsafe symbol and error codes + tests

configure.ac, doc/man1/flux-start.adoc, src/broker/broker.c, src/broker/module.c, src/cmd/flux-start.c, src/common/libflux/dispatch.c, src/common/libflux/handle.c, src/common/libflux/rpc.c, src/connectors/shmem/shmem.c
This PR is a continuation of #672, which extends the work of @garlick and @trws with
* fix missing `pkg-config` argument when building with `libcaliper-stub`
* New option `--caliper-profile=ARG` to `flux start`, which exports proper `LD_PRELOAD`, `CALI_CONFIG_PROFILE=ARG` and `CALI_LOG_VERBOSITY=0` to brokers (`CALI_*` vars are not overwritten)
Also, when I was working another angle I abstracted the caliper init routines for broker and modules into their own functions. I left that in here, but could easily remove it as it isn't necessary right now (thought I could get runtime initialization working)
I also realize I need to document the `--caliper-profile` option to flux-start.
=> Support Caliper based profiling

etc/rc3, t/Makefile.am, t/t2006-joblog.t
If the persist-directory attribute is set to DIR, run
`flux wreck ls >DIR/joblog` in the rc3 teardown script.
Fixes #661
=> rc3: create joblog if persist-directory is set

src/bindings/lua/wreck.lua, src/cmd/flux-start.c, src/common/Makefile.am, src/common/libpmi/Makefile.am, src/common/libpmi/pmi.c, src/common/libpmi/pmi2.c, src/common/libpmi/pmi2.h, src/common/libpmi/simple_client.c, src/common/libpmi/simple_server.c, src/common/libpmi/simple_server.h, src/common/libpmi/test/simple.c, src/common/libpmi2.map, src/modules/wreck/Makefile.am, src/modules/wreck/lua.d/openmpi.lua, src/modules/wreck/wrexecd.c
The main point of this PR is to support OpenMPI when configured for SLURM's pmi2 MPI personality.  When configured this way, OpenMPI plugins are linked against SLURM's libpmi2.so.
Although SLURM's libpmi2.so is a wire protocol client, it does not honor the protocol version negotiation as noted in #746.  To get OpenMPI working, Flux can provide a stripped down libpmi2.so, internally implemented on top of PMI-1, then set LD_LIBRARY_PATH to include this library.
This seems to circumvent the problem in tests with a hello world MPI program.
=> Improve PMI tracing and support PMI-2 subset for OpenMPI

src/test/travis-dep-builder.sh
In 2cd2b95d79128453aa0d7bbc8a9ddb4a8c3c09bf, caching of checkouts
was "fixed" to include build options etc. Unfortunately, the
cache name wasn't sanitized, and includes slashes and whitespace,
causing creation of the cachefile to fail, and thus builds of checkouts are
*never* cached.
This change sanitizes the cachefile name, replacing whitespace
and slashes with `_` so at least the file can be created.
This should speed up Travis builds since they slowed after #744
=> travis-ci: sanitize cache file name in dep-builder

.travis.yml, codecov.yml
Add codecov.io for coverage results in addition to coveralls.io.
CodeCov seems to have a much better interface than Coveralls, and includes "coverage diffs" in PRs which I think will come in very useful.
Check out basic example [here](https://codecov.io/gh/grondo/flux-core/tree/7cea614b61dc4a998a7b66d7947e92e05d6f8da4/src)
Will rebase on #749 once that is separately merged.
=> travis-ci: upload coverage to CodeCov

NEWS.md, configure.ac
This PR updates News.md for the 0.4.0 release, fixes some markdown in the 0.3.0 notes, and strips the leading "v" from tag names when generating PACKAGE_ variables from `git describe`.
=> Prepare NEWS for 0.4.0 tag

.travis.yml
Ok, sorry I typo'd the tarball glob and unfortunately the release didn't work. I've deleted the tag so we can try again, and hopefully this is the only issue with the travis-ci based deploy.
Apologies!
=> travis-ci: fix release file glob

.travis.yml
The travis-ci deploy releases provider doesn't seem to work with file
globbing, unless I've somehow got the syntax incorrect.
Switching to doing the glob in the `before_deploy` section, exported
as an environment variable, seems to work however. So this update
uses that approach.
(I did test using a throwaway tag in the flux-framework/flux-core repo, now deleted.
Sorry if that caused some noise!)
=> travis-ci: don't use glob in deploy section

src/bindings/python/flux/kvs.py
Fixes an error that occurs when kvs_watch returns a NULL value.
Also added in the dropcache funtion to the python bindings and cleaned up some unused imports.
Fixes: #752
=> python: kvs_watch fix

src/test/travis-dep-builder.sh
`shift` wasn't passed any arguments, so only `--prefix` was being gobbled
up and the actual prefix path was being left to be parsed as an argument
flag.
=> travis: fix parsing of prefix in dep build script

.travis.yml
I noticed this one-line discrepancy in the latest mods to flux-sched in the definition of ANCHOR.  This change will match the pattern used in flux-sched.
=> travis.yml:  Fix ANCHOR definition

codecov.yml, src/cmd/flux-start.c, src/common/liboptparse/optparse.c, src/common/liboptparse/test/optparse.c
This is  a few minor fixes and improvements for optparse:
- Remove the requirement for a non-printable option `key` for long-only options. Instead we use the `longindex` returned by `getopt_long` to find the option used
- Fix some issues with usage output line splitting
- Add tests for long-only options, usage output corner cases, and optional argument options
=> optparse: remove requirement for option key on long-only options (and other fixes)

src/broker/broker.c, src/broker/overlay.c, src/broker/overlay.h, src/broker/runlevel.c, src/broker/runlevel.h, src/modules/content-sqlite/content-sqlite.c, src/modules/wreck/job.c
The goal of this PR is to get useful timings and other log information out of a large session launched with
```
srun flux start -o,-Slog-stderr-level=6 [COMMAND]
```
First, some messages, especially those emitted from every rank, were changed from LOG_INFO to LOG_DEBUG.  Next, elapsed time was added to the log messages for wireup, rc1, and rc3 completion.
Finally, the "last heard from" messages from idle peers are suppressed during wireup and the wireup progress reporting interval was increased from 1s to 10s.   Net result is something like this:
```
$ ./flux start -s512 -o,-Slog-stderlevel=6 flux getattr size
2016-08-15T19:28:43.195512Z broker.info[0]: nodeset: [0-511] (complete) 0.6s
2016-08-15T19:28:43.195571Z broker.info[0]: Run level 1 starting
2016-08-15T19:28:46.642082Z …
```
=> clean up LOG_INFO output, log wireup, rc1, rc3 times

autogen.sh
While I don't understand why it is necessary, and it might just be an artifact of the way spack works, I don't exactly see the harm in an extra call to `libtoolize` at the top of `autogen.sh`, and this also gives us an opportunity to update flux-core `autogen.sh` to use `autoreconf`.
@trws or @SteVwonder, can you see if this fixes spack build for flux-core?
Fixes #770
=> autogen.sh: run libtoolize before autoreconf

doc/man3/Makefile.am, doc/man3/flux_reactor_now.adoc, doc/man3/flux_timer_watcher_create.adoc, src/broker/heartbeat.c, src/broker/hello.c, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libflux/test/reactor.c, src/modules/kvs/kvs.c, t/lua/t1002-kvs.t, t/t2000-wreck.t
This PR increases the KVS commit aggregation window from 1ms to 50ms and switches the timeout logic to use `flux_reactor_now()` instead of `clock_gettime()`.
There's still a problem with the lua kvs test failing on my desktop, and @grondo offered to have a look, so I'm posting this PR earlier than I normally would.
The failure is the kvs watcher test:
```
PASS: lua/t1002-kvs.t 103 - kvswatcher: 2nd callback has correct result
FAIL: lua/t1002-kvs.t 104 - reactor exited normally with Timed out after 1.5s!
PASS: lua/t1002-kvs.t 105 - Can remove kvswatcher without error
```
it's odd because the KVS watcher worked as expected, but the 1.5s timer fires also before the reactor exits, causing the error.
=> increase KVS commit window

doc/man1/flux-wreckrun.adoc, src/bindings/lua/flux-lua.c, src/bindings/lua/lua-hostlist/hostlist.c, src/cmd/flux-wreck, src/cmd/flux-wreckrun, src/modules/wreck/lua.d/input.lua, src/modules/wreck/wrexecd.c, t/t2000-wreck.t
This is a list of minor fixes and workarounds encountered during scale testing of program launch. Most notable is the kludge to workaround use of hostlist for lists of tasks (eventually we'll use something more apt), and a convenience option for `flux wreckrun` to avoid processing stdio and task exit states, but simply wait until a job reaches a given state (`--wait-until=state`).
The kvs_watch for lwj.state is moved before the run request event, mainly to support `--wait-until` but also because it was found to be confusing to have "missing" states in verbose output during large scale program launch.
=> wreck: minor enhancements for scale testing

doc/man3/flux_reduce_create.adoc, doc/man7/flux-broker-attributes.adoc, doc/test/spell.en.pws, src/broker/Makefile.am, src/broker/broker.c, src/broker/hello.c, src/broker/hello.h, src/broker/test/hello.c, src/common/libflux/reduce.c, src/modules/live/live.c, t/loop/reduce.c
This PR should speed up the "hello" protocol executed during wireup a little bit.
The old protocol was for every node to send a small message directly to rank 0.
Once all the messages were received, wireup was complete.
The new protocol uses TBON topology-informed reduction to reduce a count.  Once the count reaches the target size wireup is complete.
I guess this is also another simple example of how the reduction handle works.
See long comment in ddc83ef
=> implement scalable reduction for wireup protocol

src/broker/hello.c
The flux_rpc() use in broker/hello.c seemed to assume integer return
and tested for error code `< 0`. Fix the call so that the flux_rpc_t
returned from the call is captured, and test for NULL on error.
This also allows the rpc object to be freed, fixing a small leak.
I don't know why this is not a compilation error, or why `cppcheck` didn't catch the leak. If I missed something simple there, I apologize in advance.
=> broker/hello: fix leak/error detection in flux_rpc

src/bindings/python/flux/constants.py, src/bindings/python/flux/core/watchers.py, src/bindings/python/flux/jsc.py, src/bindings/python/flux/kvs.py, src/bindings/python/flux/wrapper.py, src/bindings/python/test/kvs.py
Several python binding fixes wrapped into one PR:
- Add constants for FDWatcher
- Switch kvs.py to use the latest KVS interface (remove use of json-c)
- Add interface to JSC
Fixes #793
=> python: Several fixes for the bindings

src/bindings/lua/flux-lua.c, src/bindings/lua/wreck/io.lua, src/cmd/flux-wreck, src/cmd/flux-wreckrun, t/lua/t1002-kvs.t, t/lua/t1003-iowatcher.t
This PR adds some lamentably missing error checks in the Lua bindings, as well as `flux-wreckrun` and `flux-wreck`. The end result is that in specific cases of kvs and fd watch failures, wreck and wreckrun will emit errors instead of mysterious hangs.
=> Fix missing error checks in Lua bindings, flux-wreckrun, flux-wreck

doc/man1/flux-kvs.adoc, doc/test/spell.en.pws, src/cmd/flux-kvs.c, src/modules/kvs/json_dirent.c, src/modules/kvs/json_dirent.h, src/modules/kvs/kvs.c, src/modules/kvs/kvs.h, src/modules/kvs/libkvs.c, src/modules/kvs/proto.c, src/modules/kvs/proto.h, src/modules/kvs/test/proto.c, t/Makefile.am, t/kvs/watch_disconnect.c, t/t1000-kvs-basic.t
This PR implements the KVS functions suggested in issue #778 for accessing the blobref of a key, and for creating a key with a blobref in place of a value.  The new functions are
```C
/* Get blobref associated with a key.  Caller must free.
* If value is stored "by value", return EINVAL.
*/
int kvs_get_value_blobref (flux_t h, const char *key, char **blobref);
int kvs_get_directory_blobref (flux_t h, const char *key, char **blobref);
/* Create a reference to a value/directory object stored in content cache.
*/
int kvs_put_value_blobref (flux_t h, const char *key, const char *blobref);
int kvs_put_directory_blobref (flux_t h, const char *key, const char *blobref);
```
In addition the kvs.get and kvs.commit protocols were cleaned up, switching from a dictionary with  a plethora of boolean …
=> add KVS blobref access functions

src/common/libflux/flog.c, src/common/libflux/handle.c, src/common/libflux/tagpool.c, src/common/libflux/tagpool.h, src/common/libflux/test/tagpool.c, src/common/libutil/Makefile.am, src/common/libutil/log.c, src/common/libutil/test/veb.c, src/common/libutil/veb.c, src/modules/kvs/kvs.c, src/modules/kvs/libkvs.c, t/kvs/watch.c, t/t1000-kvs-basic.t
Rather than failing at 64K matchtags, allow the non-group tagpool to grow up to 1M in size.
Also: change kvs_watch to use the non-group tagpool to hopefully address wreck scalability issues discussed in #802.
This took a while due to some disturbing behavior by libveb where initialization to "allocated" did not work, depending on the size of the veb tree - this is why I've added so many assertions to the code.  I did verify that the old implementation worked as it should.  In fact this condition was caught by an existing unit test that tries to run out the pool and verify that it really got all the tags.  I couldn't find any memory clobbering with valgrind, so I assume this is an internal bug in libveb, and it doesn't seem to occur when the tree is initialized to "not allocated".  That is …
=> when tagpool is exhausted, grow up to RFC 6 limits

src/common/libutil/veb.c
Quiet uninitialized variable warning in vebnew() for `T.M` by initializing it to 0.
Fixes #808
=> libutil/veb: quiet uninitialized variable warning in vebnew

src/bindings/python/flux/core/handle.py, src/bindings/python/flux/kvs.py, src/bindings/python/flux/message.py, src/bindings/python/flux/rpc.py, src/bindings/python/flux/sec.py, src/bindings/python/flux/wrapper.py, src/bindings/python/test/handle.py, src/bindings/python/test/wrapper.py
This is an early pull request that still needs some cleanup, but adds uniform destruction support to all wrapped objects, and as part of that reorganizes the init calls and so-forth to better handle exceptions.  Chances are this will help with the resource usage problems.
=> Python destructor refactoring and exception safety

src/bindings/python/flux/wrapper.py, src/bindings/python/test/wrapper.py
Fixes an invalid test, adds a new test for the corrected behavior and a
check with assertions, and test, for the invalid assignment that caused
the initial issue.
fixes #818
=> python: add a check for invalid handle types

src/common/libutil/shortjson.h, t/Makefile.am, t/issues/t0821-kvs-segfault.sh
Fix #821 and possible similar bugs by protecting most return by reference calls in `shortjson.h` from NULL args.
Also, add a regression test to the issues test driver for the kvs pattern that initially triggered the bug.
=> Fix #821: crash in kvs due to NULL arg in Jget_str()

src/bindings/lua/flux-lua.c, src/bindings/lua/kvs-lua.c, src/bindings/python/flux/Makefile.am, src/common/libflux/rpc.c, src/modules/kvs/Makefile.am, src/modules/kvs/json_dirent.c, src/modules/kvs/json_dirent.h, src/modules/kvs/kvs.c, src/modules/kvs/kvs.h, src/modules/kvs/test/dirent.c, src/test/valgrind.sh, t/Makefile.am, t/kvs/dtree.c, t/t1000-kvs-basic.t
This PR contains some misc. hopefully non-controversial improvements culled from PR #820 which was withdrawn.  There are three batches here:
* testing: unit test for `json_dirent.[ch]`,  new `dtree` test for populating kvs namespace
* memory corruption: fix two use-after-free bugs in kvs module, protect `flux_rpc_t` with magic cookie, get valgrind test working again
* api: add format attributes on varargs kvs functions, update a few callers; drop deprecated kvs interfaces from python bindings
=> kvs: testing, fix use-after-free, streamline python bindings

configure.ac, etc/rc1, src/bindings/lua/Makefile.am, src/bindings/lua/flux-lua.c, src/bindings/lua/wreck.lua, src/bindings/lua/wreck/io.lua, src/cmd/Makefile.am, src/cmd/flux-aggregate, src/cmd/flux-wreckrun, src/modules/Makefile.am, src/modules/aggregator/Makefile.am, src/modules/aggregator/aggregator.c, src/modules/wreck/Makefile.am, src/modules/wreck/wrexecd.c, t/Makefile.am, t/rc/rc1-wreck, t/scripts/kvs-get-ex.lua, t/t2100-aggregate.t
For comment only. The purpose of this experiment is to play with the reduction/aggregation interface for possible use with wrexec task exit status. The PR is posted early to assist with design of generic reduction handle, get early feedback,e tc.
The current `aggregator` module reduces set of `id, value` pairs into a kvs directory with the contents:
```
key.max
key.min
key.count
key.values.
```
Where the `key.values` directory has one entry per value, with the contents of each values entry a nodelist of ids that reported that value.
A `flux-aggregate` test command is also available for testing aggregation of a value across a session (currently version assumes one value per rank, i.e. run `flux aggregate <key> <value>` once per rank) The `flux-aggregate` command running on rank 0 waits for …
=> experimental aggregator module

doc/man1/flux-kvs.adoc, doc/test/spell.en.pws, src/broker/hello.c, src/cmd/flux-kvs.c, src/common/libpmi/single.c, src/common/libpmi/test/single.c, src/modules/kvs/kvs.c, src/modules/kvs/kvs.h, src/modules/kvs/libkvs.c, src/modules/kvs/proto.c, src/modules/kvs/proto.h, src/modules/kvs/test/proto.c, t/kvs/dtree.c, t/t1000-kvs-basic.t
Resubmitting work from the withdrawn PR #820, cleaned up:
This PR adds the following new KVS interfaces:
```C
/* Like kvs_get() but lookup is relative to 'treeobj'.
*/
int kvs_getat (flux_t h, const char *treeobj,
const char *key, char **json_str);
int kvs_get_dirat (flux_t h, const char *treeobj,
const char *key, kvsdir_t **dirp);
int kvs_get_symlinkat (flux_t h, const char *treeobj,
const char *key, char **val);
```
and modifies the `kvsdir_get_*()` implementations so that a `kvsdir_t` created by `kvs_get_dirat()` can be walked recursively relative to the original treeobj, regardless of what is changing in the KVS, which finally addresses #64.
I also implemented @grondo's suggestion of making `kvsdir_put_*()` fail on a "snapshot" `kvsdir_t`.
The `flux-kvs` command has a couple of new …
=> kvs: add kvs_getat() and related functions

src/broker/broker.c, src/broker/overlay.c, src/broker/overlay.h, src/broker/snoop.c, src/broker/snoop.h, src/cmd/flux-keygen.c, src/cmd/flux-snoop.c, src/common/libflux/security.c, src/common/libflux/security.h, src/test/tmunge.c
Remove the pointer from the definition of the typedef
flux_sec_t to comply with the Coding Style Guide and
to make it easier to use.
=> security: Remove pointer from typedef flux_sec_t

src/broker/broker.c, src/broker/module.c, src/broker/module.h, src/cmd/flux-module.c, src/common/libflux/module.c, src/common/libflux/module.h, src/common/libflux/test/module.c, t/module/parent.c
Remove the pointer from the definition of the typedef
flux_modlist_t to comply with the Coding Style Guide and
to make it easier to use.
flux-sched will need a one-line change to accommodate
this change.
=> module: Remove pointer from typedef flux_modlist_t

t/t2000-wreck.t
I don't have the test framework's code/internals fully understood yet, but this didn't look right.  Outputs are named ```output.1``` and ```expected.1```, but we're comparing ```output.0``` and ```expected.1```?
=> t/t2000-wreck.t: Fix invalid compare on 'wreckrun: --input=0 works' test

t/t2000-wreck.t
Found similar invalid compare just like #836
=> t/t2000-wreck.t: Fix invalid compare on per-task affinity test

doc/man3/flux_attr_get.adoc, doc/man3/flux_aux_set.adoc, doc/man3/flux_event_subscribe.adoc, doc/man3/flux_fatal_set.adoc, doc/man3/flux_flags_set.adoc, doc/man3/flux_get_rank.adoc, doc/man3/flux_get_reactor.adoc, doc/man3/flux_handle_watcher_create.adoc, doc/man3/flux_msg_handler_addvec.adoc, doc/man3/flux_msg_handler_create.adoc, doc/man3/flux_open.adoc, doc/man3/flux_pollevents.adoc, doc/man3/flux_recv.adoc, doc/man3/flux_reduce_create.adoc, doc/man3/flux_requeue.adoc, doc/man3/flux_respond.adoc, doc/man3/flux_rpc.adoc, doc/man3/flux_rpc_multi.adoc, doc/man3/flux_rpc_raw.adoc, doc/man3/flux_send.adoc
Update the man pages to also reflect the recent change of the flux_t
typedef no longer containing a pointer.
Fixes #843
=> Update flux_t * references in man pages

configure.ac, src/bindings/lua/Makefile.am
=> Fix make distcheck

doc/man1/flux-module.adoc
Environment variable for searching modules is FLUX_MODULE_PATH,
not FLUX_MODPATH.
=> doc/man1/flux-module.adoc: Fix environment variable error

src/broker/broker.c
=> src/broker/broker.c: Fix typo flux_repond -> flux_respond

src/broker/module.c, src/common/libflux/handle.c, src/common/libflux/module.c, src/modules/live/Makefile.am, src/modules/live/live.c, t/t0010-generic-utils.t
This is an attempt to solve flux-framework/flux-sched#211
Not sure if this is the right approach, discussion continues in the issue.
=> add dlopen RTLD_DEEPBIND flag

doc/man1/flux-start.adoc
Noticed this didn't work:
```
$ src/cmd/flux start -s8 -o,log-stderr-level=7
log-stderr-level=7: Command not found.
2016-10-13T20:59:52.618549Z broker.err[0]: Run level 2 Exited with non-zero status (rc=1) 0.1s
flux-start: 0 (pid 53483) exited with rc=1
```
Which I got out of the manpage.  I think it should be: ```-o,--setattr=log-stderr-level=7``` now?
=> doc/man1/flux-start.adoc: Fix example option usage

t/t0005-exec.t
The fake file 'nosuchprocess' does not have a relative or absolute path specified.  So the file will be searched for in all directories in the users PATH.  If the user does not have access to one of the directories in their PATH, an EACCES error can occur instead of ENOENT, leading to a failed test.  So put "./" in front of 'nosuchprocess' to ensure it is not searched for in PATH.
=> t/t0005-exec.t: Fix corner case in test for file not found

t/t2001-jsc.t
Add a timed wait on a job-state pattern to allow flux-jstat
to receive all of the job events within up to 2 seconds.
If and when a wreck.state.* event is delayed to be received
by "flux-jstat notify" used in some subtests,
they can end up prematurely comparing the result
against incomplete jstat outputs.
A timed wait helps avoid such false alarms. Resolve #512.
=> jsc test: Add timed waits to avoid races

doc/man1/Makefile.am, doc/man1/NODESET.adoc, doc/man1/flux-exec.adoc, doc/man1/flux-hwloc.adoc, doc/man1/flux-module.adoc, doc/man1/flux-ping.adoc, doc/man1/flux-ps.adoc, doc/man1/flux-start.adoc, doc/man1/flux-submit.adoc, doc/man1/flux-wreck.adoc, src/cmd/flux-comms.c, src/cmd/flux-exec, src/cmd/flux-ping.c, src/cmd/flux-ps, t/t0003-module.t, t/t0005-exec.t, t/t0007-ping.t, t/t2005-hwloc-basic.t
Well, what began as noticing a doc error in the ping manpage lead to a lot more.  I should maybe split this up into multiple PRs, but I'll leave it all in as it is generally a large batch of small things.  LMK if it'd be better to split up.  
- Per discussion in #854 , support --rank="all" across all tools and add tests appropriately.  Nothing too fancy here.
- Support tests for invalid ranks in tools.  Found bugs in flux-ps and flux-ping as a result.  I'd appreciate review on the bug fixes commits 31b6c2697d815b1c6b702b17686e59e19658bfa4 and
1bd8f9393f17e76bfa8c6da81fb394d179164c57, particularly the latter.  Perhaps there is something nifty that can be done in the flux api that I don't see at the moment.
- Added misc tests I thought should be there, invalid ping targets, invalid modules, …
=> Fix --rank issues, add NODESET documentation, and minor cleanup

src/common/libflux/security.c, src/common/libflux/security.h, src/modules/kvs/libkvs.c, src/modules/libjsc/jstatctl.c, src/test/tmunge.c, t/Makefile.am, t/t0017-security.t, t/t1000-kvs-basic.t, t/t1008-proxy.t
This PR contains an assortment of minor fixes:
* fix errors in a test that isn't run automatically (due to trickiness setting up munge in test environment)
* silence warnings
* add a small bit of test coverage
* improve proxy test that was found to be brittle with respect to /tmp contents
=> misc minor fixes

.travis.yml, src/test/backtrace-all.sh, src/test/travis-dep-builder.sh
Some minor cleanup and fixes for Travis:
- Fix a few bugs in `backtrace-all.sh` to clean up spurious errors and allow backtrace of executables in `$PATH` (e.g. `/usr/bin/lua`)
- Remove `libjson-c` build, it is built-in to flux-core now
- Pull in `munge` as a package since it is now whitelisted
- Do not perform multiple builds on `coverity_scan` branch
=> travis-ci: minor updates

README.md
"src/cmd/flux-broker" no longer exists, update to
"src/cmd/flux start".
=> README.md: Update srun instructions

src/modules/kvs/libkvs.c
See: https://github.com/flux-framework/flux-sched/issues/214
=> kvs: allow get_double to be called on an int

configure.ac
This may help address LLNL/spack#2109
=> build: add --disable-docs configure option

src/broker/broker.c, src/common/libpmi/simple_server.c, src/common/libutil/base64_json.c, src/modules/cron/cron.c, src/modules/cron/task.c, src/modules/kvs/libkvs.c, src/modules/libjsc/jstatctl.c, src/modules/resource-hwloc/resource.c, src/modules/wreck/job.c, src/modules/wreck/wrexecd.c
Nothing major here, but a series of minor fixups for issues flagged by Coverity.
Most of these are in error handling so we were unlikely to hit them.
A few of these were cleaned up by moving from raw JSON handling through json-c to use of `flux_rpcf`, `flux_rpc_getf` and `flux_respondf` etc.
=> fixes for minor issues detected by Coverity

t/Makefile.am, t/kvs/getas.c, t/t1000-kvs-basic.t
This PR adds a test program `t/kvs/getas` and a new test in `t1000-kvs-basic.t` to make sure the fix @SteVwonder added in #872 stays fixed.
=> add test to verify KVS int can be read as double

doc/man1/flux-wreck.adoc, doc/man1/flux-wreckrun.adoc, src/cmd/flux-wreck, src/cmd/flux.c
Of particular review interest, commit b4fca3eaf70dbb9cfd8b9cdf4ecd82d1b8c8b485 documents ```flux-wreckrun``` environment variables.  Hopefully I got resource manager lingo correct.
=> Various minor cleanup and documentation updates

src/modules/barrier/barrier.c, src/modules/barrier/libbarrier.c
This switches the barrier module over to the new JSON payload encode/decode functions and adds some debugging log messages to help track down hung barriers.
=> barrier module cleanup and debug logging

src/modules/barrier/barrier.c, src/modules/barrier/libbarrier.c
Please note comment change in 86c650db3b6eb8ba71419cbae17d75ac813a490f.  I'm pretty sure this is a correct change given the code below it, but would like a double check.
=> Fix barrier protocol incompatability with older jansson versions and minor cleanup

src/common/libutil/Makefile.am, src/common/libutil/lru_cache.c, src/common/libutil/lru_cache.h, src/common/libutil/test/lru_cache.c, src/modules/libjsc/jstatctl.c
When libjsc was converted over to use the new hierarchical directory scheme under `lwj.`, the mapping between jobid and kvs path was memoized in an internal hash. At the time, no management of entries in this hash was also added, so the current code has the potential for unbounded memory growth when an application using libjsc is long running or managing many jobs.
This PR changes the internal hash of jobid to kvs path mappings into an LRU cache. The cache, for now, has a max size of 256. If needed, this could be made configurable or adjustable later.
The simple LRU cache implementation is added to libutil in case it can be used elsewhere.
=> fix possible unconstrained memory growth in modules/libjsc

src/modules/resource-hwloc/resource.c, t/t2005-hwloc-basic.t
Had this commit sitting on a branch for a while, getting stale. It might be useful so I'm proposing it as a PR for discussion.
Adds a resource.hwloc.by_rank.<id>.HostName key containing the hwloc-provided hostname for the current rank.
=> resource-hwloc: put HostName in by_rank directory

doc/man1/flux-kvs.adoc, doc/test/spell.en.pws, src/cmd/flux-kvs.c, t/t1000-kvs-basic.t
Wanted to add a simple option to list kvs entries without the values since some entries are gigantic and flood stdout.  Sometimes just want to know what entries were there.  Lead to a lot of cleanup along the way.
The new ```-d``` option I added to several subcommands was chosen b/c I likened the option to the ```-d``` option of ```ls```.  I know that may just be my weird way of thinking about it and maybe most won't think of it that way.
The subcommand option parsing could be cleaned up, but I decided to leave it be, let the code have one more "strike" before cleanup.
=> kvs: doc updates, consistency fixes, new convenience options

src/modules/wreck/wrexecd.c, t/Makefile.am, t/issues/t0900-wreck-invalid-cores.sh
This should resolve the specific issue from #900. A reproducer was added under `t/issues` and I've verified it fails before and passes after this PR is applied.
There may be other cases where unexpected values cause hangs during wreck job launch, but those are not tackled here.
=> wreck: check for invalid tasks to run on node and issue fatal error

doc/man1/flux-ping.adoc, src/cmd/flux-ping.c, t/t0007-ping.t
Splitting off these "minor cleanups" of flux-ping from #898.
=> Minor flux-ping cleanup

Makefile.am, codecov.yml, src/common/liboptparse/Makefile.am, src/common/liboptparse/getopt.c, src/common/liboptparse/getopt.h, src/common/liboptparse/getopt_int.h, src/common/liboptparse/optparse.c
This is an alternate approach to #906, which instead of adding NLS support to flux-core, makes another small change to GNU `getopt.c` and adds
```
#define _(msgid) msgid
```
Which effectively works around the requirement for `gettext()`.
I should probably devise a way to test the MT-safety of the optparse_parse_args() version that uses `getopt_internal_r`
=> liboptparse: make optparse_parse_args() reentrant

doc/man3/Makefile.am, doc/man3/flux_rpc_multi.adoc, src/common/libflux/rpc.c, src/common/libflux/rpc.h, t/loop/multrpc.c
Another spin-off from #898 as the patch series is long.  A fair amount of refactoring, adding support for ```flux_rpcf_multi()``` the jansson equivalent to ```flux_rpc_multi()```.  Compared to my original patch series in #898, ```flux_rpc[f]_multi``` now constructs a single flux message for all rpcs instead of a message on each iteration.  So the refactoring is now cleaner and it should shave off a few instructions for the old case.
An ```"any"``` special case option for the ```nodeset``` input was added to the ```flux_rpc[f]_multi``` functions for convenience.  Passing "FLUX_NODEID_ANY" appears to be the one case that can't be
handled by ```flux_rpc[f]_multi```.  So tools needed a special case to deal with that and call ```flux_rpc()```.  This hopefully removes that need for that special …
=> libflux/rpc: add flux_rpcf_multi(), add "any" nodeset option, various refactoring

src/cmd/flux-start.c, src/common/liboptparse/optparse.c, src/common/liboptparse/optparse.h, src/common/liboptparse/test/optparse.c
Another spinoff from #898.  WIth the minor exception of the test count in ```test/optparse.c```, I don't believe anything here will conflict with PR #910 .
Most notable fix is ```optparse_get_int``` can return negative values, so it's up the caller to check for correctness of the inputted value.
Most notable addition is ```optparse_get_double``` convenience function.
=> liboptparse: cleanup, minor fixes, minor additions

doc/man1/flux-ping.adoc, src/cmd/flux-ping.c, t/t0007-ping.t
Per discussion in PR #860 and some offline discussion, cleanup flux-ping to use jansson API.  I'm not 100% done as I noticed a few things, but thought I'd start w/ this PR.
Lots of mini-cleanup.  Notable changes:
For consistency to ping(8), change ```--delay``` to ```--interval``` in flux-ping.  This is an outright breakage of old command line but thought important to make it consistent and now's the time to do it.  acc62ef7337fbdbd7ed1dca527e0c99a3a21fcab
Refactor ```flux_rpc_multi``` and add a ```flux_rpcf_multi``` jansson equivalent.  Stuck typdef of callback in the middle of the file, right before usage.  It's not the style I normally use, but noticed it elsewhere.  Could cleanup usage all around if not liked.  96171838a9a299a8e6cd2044796bd8b418134830 & …
=> flux-ping refactor and cleanup

src/broker/broker.c, src/broker/overlay.c, src/cmd/flux-ping.c, t/t0007-ping.t
This PR simply changes an inappropriate errno response of ENOSYS to EHOSTUNREACH when a message reaches the rank 0 broker that was _from_ rank 0 and has the FLUX_MSGFLAG_UPSTREAM message flag set.
It also modifies `flux-ping` to display the `rank!service` that elicited the error.
=> broker: adjust errno response to "upstream" request on rank 0

src/bindings/python/flux/Makefile.am, src/bindings/python/flux/kz.py
The kz bindings have been getting built, but their native interface file
was not being installed.  This fixes that issue.
Fixes flux-framework/capacitor#6
=> python: install kz bindings file

configure.ac, etc/Makefile.am, etc/flux-pmi.pc.in, src/common/libpmi/test/kvstest.c
This PR adds a pkg-config package for Flux's libpmi.so in support of an OpenMPI "flux" component under discussion in rhc54/ompi#1.
libpmi.so is purposefully excluded from flux-core's pkg-config package because in general we want the selection of a PMI library to be a runtime decision.  The new component will normally try to dlopen our library at `$FLUX_PMI_LIBRARY_PATH`.  However in cases where OpenMPI builds all its modules statically (apparently common on big systems), dlopen is not permitted and it needs to find our libpmi.so at build time.  Using pkg-config for this avoids hard wiring a search heuristic in the configuration m4sh for the flux component.
Unrelated fix to a silly output typo in a PMI test program is tacked on here as well.
=> create a pkg-config package for Flux PMI

src/cmd/builtin/attr.c, src/cmd/builtin/content.c, src/cmd/builtin/dmesg.c, src/cmd/builtin/env.c, src/cmd/builtin/heaptrace.c, src/cmd/builtin/help.c, src/cmd/builtin/hwloc.c, src/cmd/builtin/nodeset.c, src/cmd/builtin/proxy.c, src/cmd/flux-event.c, src/cmd/flux-ping.c, src/cmd/flux-start.c, src/cmd/flux.c, src/common/liboptparse/optparse.c, src/common/liboptparse/optparse.h, src/common/liboptparse/test/optparse.c
This is a nitpick patch.  I'm not going to fight too hard over it if it's disliked.
I noticed in a number of places ```optind``` was used as a variable name when parsing args with ```liboptparse```.  ```optind``` is a global variable used by ```getopt(3)```.  Sometimes the variable was used without declaration, as code just used the global one from ```getopt```.
To try and disentangle the two parsing libraries I renamed variable usage everywhere, and declared variables when appropriate.
I then (perhaps going too far) renamed ```optparse_optind()``` to ```optparse_option_index()```.  I felt the function name invited people to use ```optind``` as a variable name.
=> Nitpick cleanup of liboptparse usage

src/broker/broker.c, src/common/libpmi/pmi.c, src/common/libpmi/simple_client.c, src/modules/wreck/lua.d/openmpi.lua, src/modules/wreck/wrexecd.c
This PR fixes a couple more issues that came up while building openmpi support for flux.
Some general cleanup, environment cleanup as discussed in #923, implementing the clique functions, and suppressing a log for failed `PMI_KVS_Get()` since that's not necessarily a flux error.
All pretty minor.
=> tighten up PMI implementation for OpenMPI

src/cmd/flux.c, src/common/liboptparse/optparse.c, src/common/liboptparse/optparse.h, src/common/liboptparse/test/optparse.c
I thought it was sort of inconvenient to remove the default "help" option and then re-add it back just so we can set an alternate (or no) usage callback function.  Since I was duplicating the code in ```cmd/flux``` into ```cmd/flux-kvs```, figured could refactor a bit.  So I added an option to allow the user to set an alternate usage callback function.  The callback can be disabled by setting the callback to NULL.
Also fix one nit along the way.
=> liboptparse: Support setting alternate usage callback function

doc/man1/flux-kvs.adoc, src/cmd/flux-kvs.c, t/Makefile.am, t/kvs/basic.c, t/t1000-kvs-basic.t, t/t1002-kvs-cmd.t, t/t1007-kz.t, t/t1008-proxy.t
Per #897 , cleaned up a bunch of flux-kvs command, trying to make it a more "user facing" tool instead of the unit-testing tool it was before.  Refactor w/ liboptparse along the way.  Copied the old tool into ```t/kvs/basic``` for unit testing.
Ended up axeing ```get-treeobj```, ```put-treeobj```, ```getat```, ```dirat```, ```readlinkat```, ```type```, ```dirsize```, and ```exists``` as I felt they were more for testing the KVS api & implementation than really something users need.  Casual users will just use ```wc -l``` or ```-n $str``` in scripts with ```dir``` and ```get```.
Other minor fixes along the way:
- make ```watch``` command logic more in line with user thinking that it means "N changes" occured.  Add ```-o``` option to output current value.
- Rename ```-r``` to ```-R``` for …
=> initial flux-kvs cleanup

src/broker/broker.c, src/broker/runlevel.c, src/broker/runlevel.h, src/cmd/flux-start.c, src/common/libsubprocess/subprocess.c, src/common/libsubprocess/subprocess.h
Kinda random, but after running into this setting up little one-liner tests a lot lately I thought it would be worth fixing.  I'm open to adjusting this if it doesn't behave the way others think it should, but it makes one-off testing rather more ergonomic at least for me.
Both flux-start and flux-broker have classically taken the user command
through an argz_stringify, causing all arguments to be flattened into a
single argument and requiring odd double quoting to make many commands
work.  This makes flux-start propagate all arguments as-is through to
the next stage.  The flux-broker case is a bit more complicated, because
of the shell default, but is currently set up to default to a shell with
no command, use `${shell} -c <arg>` when there is only one argument, and
directly invoke …
=> flux-{start,broker}: propagate argument quoting

src/bindings/python/.pylintrc, src/bindings/python/Makefile.am, src/bindings/python/flux/Makefile.am, src/bindings/python/flux/__init__.py, src/bindings/python/flux/command_helpers.py, src/bindings/python/flux/constants.py, src/bindings/python/flux/core/__init__.py, src/bindings/python/flux/core/handle.py, src/bindings/python/flux/core/inner.py, src/bindings/python/flux/core/trampoline.py, src/bindings/python/flux/core/watchers.py, src/bindings/python/flux/jsc.py, src/bindings/python/flux/kvs.py, src/bindings/python/flux/kz.py, src/bindings/python/flux/message.py, src/bindings/python/flux/rpc.py, src/bindings/python/flux/sec.py, src/bindings/python/flux/wrapper.py, src/bindings/python/make_binding.py, src/test/travis-dep-builder.sh
This is the start of the changes mentioned in #807 to have lints for the python bindings.  I've been using flake8 as a start, because it's less freaked out by the generated modules.  So far this reformats most of the bindings, but it's waiting for the merge of #799 rather than conflicting on code that's just going to be removed.  As soon as everything passes, I'll add another commit in here to run flake8 or pylint with make check if it's available.
=> python: add flake8/pylint checking

t/t1002-kvs-cmd.t
Fix race with kvs watch background processes in which output
from a prior test's watch_out output is seen by the current
test.
Fixes #936
=> test/kvs-cmd: Fix race in tests

doc/man3/topen.c, doc/man3/treduce.c, src/bindings/lua/lua-affinity/cpuset-str.c, src/broker/broker.c, src/broker/content-cache.c, src/broker/log.c, src/broker/module.c, src/broker/overlay.c, src/cmd/builtin/proxy.c, src/cmd/flux-comms.c, src/cmd/flux-ping.c, src/common/libcompat/reactor.c, src/common/libflux/message.c, src/common/libsubprocess/subprocess.c, src/common/libutil/nodeset.c, src/common/libutil/popen2.c, src/common/libutil/test/nodeset.c, src/modules/connector-local/local.c, src/modules/kvs/libkvs.c, src/modules/libjsc/jstatctl.c, src/modules/live/live.c, src/modules/wreck/job.c, src/modules/wreck/wrexecd.c, t/kvs/commit.c, t/kvs/torture.c, t/loop/multrpc.c
Change the printf conversion specifiers to use the portable
macros from inittypes.h.  For instance, instead of guessing %lu for
a uint32_t, use the PRIu32 macro.
Also change the length modifier for size_t types to "z", which is
an explicit printf length modifier for size_t and ssize_t arguments.
Finally, any %m conversion specifiers are replaced with explicit
%s and strerror(errno).  The %m is convenient, but it is explicitly
listed as a Glibc extension and therefore less portable.
Closes #394
=> Convert to inttypes.h conversion specifiers

src/broker/broker.c, src/cmd/flux-comms-stats.c, t/t2006-joblog.t
Minor cleanups mostly to check for errors on strtoul() and strtod() calls, plus a typo error I found in the broker.
=> Fix racey behavior in job log test + minor cleanups

doc/man1/flux-start.adoc, src/cmd/flux-start.c, t/t0001-basic.t
=> Change flux start to only exec broker if --size is not specified

src/broker/broker.c, t/t0001-basic.t
=> Add broker.pid attribute to broker, Fix broker corner case with scratch-directory-rank

src/modules/wreck/wrexecd.c
=> wrexecd: move sending of wreck.state.complete event after job archival

src/cmd/flux-logger.c, src/common/libflux/flog.c, src/common/libutil/stdlog.c, src/common/libutil/stdlog.h, t/t0009-dmesg.t
Here's a fix for #939 that simply strips the eighth bit from all characters in logged messages.
I added a test that failed before and works with the fix.
=> sanitize log entries before they enter circular buffer

doc/man3/flux_reactor_create.adoc
Improve the flux_reactor_create.adoc man page in the following ways:
Document flux_reactor_run() behavior when FLUX_REACTOR_NOWAIT or
FLUX_REACTOR_ONCE is used.
Explicitly list flags using using asciidoc labeled lists, similar to
how open(2) lists flags.
Add flux_reactor_destroy() documenation.
Fixes #899
=> man: Improve flux_reactor_create documentation

src/modules/kvs/kvs.c
Initialize check watcher with flux_check_watcher_create() instead
of flux_prepare_watcher_create().
=> modules/kvs: Fix cut & paste error

Makefile.am, src/Makefile.am
Many of flux-core's tests live down in subdirectories with
the core that that it is testing.  However, some of those tests
also have dependencies on other subdirectories higher up the
source tree.  With the recursive Makefiles approach, there is
no easy way to express that build dependency in a way that will
actually trigger the build of the that dependency.  The following
check-local rule, in conjunction with putting "." _first_ in this
file's SUBDIRS, ensures that "all" is built before any of the
recursive checks.
"check-local" is the only way that was found to add a dependency to
the "check" target.  But "make check" is a recursive operation by
default, so the this dependency can only happen first if we also
make "." the first subdirectory in the SUBDIRS list.
Note that this approach …
=> build: Add dependency on "all" to top-level make check

src/broker/broker.c
First pass at reducing the use of globals and increasing encapsulation
in broker.c.
=> broker: Reduce use of globals

src/broker/module.c, t/Makefile.am, t/kvs/commit.c, t/kvs/commitmerge.c, t/t1000-kvs-basic.t
Test for disabling commit-merge in kvs per discussion in issue #813
=> Add test for disabling commit-merge in kvs + additional minor cleanup patches

src/broker/broker.c, src/broker/modservice.c, src/cmd/builtin/proxy.c, src/common/libflux/attr.c, src/connectors/local/local.c, src/connectors/loop/loop.c, src/connectors/shmem/shmem.c, src/connectors/ssh/ssh.c, src/modules/barrier/barrier.c, src/modules/barrier/libbarrier.c, src/modules/connector-local/local.c, src/modules/content-sqlite/content-sqlite.c, src/modules/kvs/kvs.c, src/modules/live/live.c, src/modules/resource-hwloc/resource.c, t/kz/kzutil.c, t/request/req.c
Rename all ctx_t structs to give them a unique name.   While they are
ll used in ways that avoid conflict (usually local to a single file),
it makes it more difficult for the new developer to navigate through
the code when many different structs share the same name (because
ools like cscope and ctags will show many definition locations for
the struct rather than showing the one correct location).
Fixes #972
=> Rename all ctx_t structs to make them unique.

src/bindings/lua/flux-lua.c, src/bindings/lua/kvs-lua.c, src/bindings/python/flux/kvs.py, src/bindings/python/test/kvs.py, src/cmd/builtin/hwloc.c, src/cmd/flux-kvs.c, src/modules/aggregator/aggregator.c, src/modules/kvs/kvs.c, src/modules/kvs/kvs.h, src/modules/kvs/libkvs.c, src/modules/kvs/proto.c, src/modules/kvs/proto.h, src/modules/kvs/test/proto.c, src/modules/libjsc/jstatctl.c, src/modules/libkz/kz.c, src/modules/live/live.c, src/modules/resource-hwloc/resource.c, src/modules/wreck/job.c, src/modules/wreck/wrexecd.c, src/test/kap/kap_roles.c, t/kvs/asyncfence.c, t/kvs/basic.c, t/kvs/commit.c, t/kvs/commitmerge.c, t/kvs/dtree.c, t/kvs/torture.c, t/kvs/watch.c, t/t1000-kvs-basic.t
Here's an initial try at issue #813.  Note that I duplicated a bunch of functions by appending ```_flags``` to the name (e.g. ```kvs_commit_flags()```).  I didn't want to break ABI for the time being.  Will convert appropriately later on.  In hindsight, I think I should have two commits, one introducing a "flags", then another introducing the flag ```KVS_NO_MERGE```.  Will redo that when I cleanup.
I elected to the make the "mergeable" boolean in each fence wire packet optional.  I can sort of go either way on this.  It could be made a mandatory boolean in each packet?
Probably need some additional tests too, minimally to test flags on the fence functions.
Wasn't sure how to go about the ABI breakage.  Obviously I can fix everything in flux-core, but should I just send PR to flux-sched as …
=> Support KVS no merge flag

src/common/libutil/test/ev.c
Update zmq test to verify and document underlying behavior of using
ZMQ_FD & ZMQ_EVENT along with poll().
Fixes #524
=> libutil/test: Update zmq test

src/modules/kvs/kvs.h, src/test/travis-dep-builder.sh
As discussed in #984, this PR de-anonymizes the enum in kvs.h containing KVS_NO_MERGE, as this was causing build problems under python-cffi 1.1.  Later versions such as 1.5 worked OK but since configure checks that cffi is >= 1.1, flux-core is supposed to build with that version.
cffi in travis-ci is rolled back to 1.1 so that we catch problems like this in the future.
Note: I initially submitted just the travis-ci change and verified that it failed, then added the kvs.h fix.  Those commits are in the reverse order in this PR so that git bisect won't break.
=> address build problem under cffi-1.1

doc/man1/flux-start.adoc, src/cmd/flux-start.c, t/t0001-basic.t
Add --bootstrap option to flux-start, preceded by a number of cleanup patches.
=> Add --bootstrap option to flux-start

doc/man1/flux-start.adoc, doc/man7/flux-broker-attributes.adoc, doc/test/spell.en.pws, src/bindings/python/test_commands/sideflux.py, src/broker/broker.c, src/cmd/flux-start.c, src/common/libflux/Makefile.am, src/common/libflux/conf.c, src/common/libflux/handle.c, src/connectors/local/local.c, src/modules/content-sqlite/content-sqlite.c, src/modules/wreck/lua.d/openmpi.lua, t/t0001-basic.t
This PR adds a new broker attribute `broker.rundir` which replaces both `scratch-directory` and `scratch-directory-rank`.  The intent is to allow systemd to manage a single `/run` directory for a flux broker started as part of the system instance.
`flux-start` and `sideflux.py` were updated to match the simplified directory scheme.
In addition, the local connector was changed so that it no longer tries to send a signal to the broker as discussed in #987.
Finally, `flux_open()` was modified so that if a URI is not specified, and FLUX_URI is not set, it will try the local connector of the system instance (using $localstatedir/flux as the path).
This PR was split off of #980, which is focused on message security credentials.
=> establish single run directory and default URI for system instance

src/bindings/python/test/event.py, src/cmd/flux-event.c, src/connectors/local/local.c, src/modules/connector-local/local.c, t/lua/t0003-events.t
This PR fixes a bug in the local connector that suppressed errors from the subscribe/unsubscribe methods.  This uncovered bugs in flux-event and a python test which were fixed.
=> return event subscribe/unsubscribe errors to local connector users

doc/man1/flux-logger.adoc, doc/man3/Makefile.am, doc/man3/flux_log.adoc, src/broker/log.c, src/cmd/flux-logger.c, src/common/libflux/dispatch.c, src/common/libflux/flog.c, src/common/libflux/flog.h, src/common/libflux/handle.c, t/t0017-security.t
This PR changes the return value of `flux_log()` and `flux_vlog()` from void to int, and adds a flag FLUX_LOG_CHECK (ored with "severity")  which enables these functions to return an error.
If that flag is set, switch `flux_log()` from "fire and forget" mode to a synchronous RPC with the possibility of an error response.  Issue the optional response in the broker "log.append" RPC handler.  Then use the flag in `flux-logger` where attempting to log to an instance without appropriate permission really should be reported as an error.
Also: fix a mem leak in the `flux_open()` error path, and change the EPERM response logic to NOT send a response to fire and forget RPC's (based on the matchtag value).
Add a couple tests.
=> allow flux-logger(1) and flux_log(3) to get an EPERM error, optionally

src/broker/exec.c, src/broker/sequence.c, src/cmd/builtin/heaptrace.c, src/cmd/builtin/hwloc.c, src/modules/live/live.c, src/modules/resource-hwloc/resource.c
While doing a lot of conversion to jansson-style functions in #495, fixed of variety of cleanup things along the way.  Decided to split them all off onto another pull request, before sending over the beefier changes.
Most fixes are obvious, the notable exception may be 57a29a9ead64740acd4f3534f271dc914ab6f6d2.  It was necessary b/c jansson is pickier on types.  (i.e. ```"1"``` is a string while ```1``` is an int).  My lua is weak, would appreciate look to make sure ```toboolean``` local function is a smart solution?
=> Issue 495 - misc cleanup

t/t1008-proxy.t
In particular, cover op_event_subscribe() and op_event_unsubscribe()
in ssh connector.
=> test/proxy: Add event test to increase coverage

src/broker/broker.c, src/broker/content-cache.c, src/broker/exec.c, src/broker/hello.c, src/broker/log.c, src/broker/modservice.c, src/broker/sequence.c, src/broker/shutdown.c, src/cmd/builtin/heaptrace.c, src/cmd/builtin/hwloc.c, src/cmd/builtin/proxy.c, src/cmd/flux-cron, src/common/libflux/heartbeat.c, src/connectors/shmem/shmem.c, src/connectors/ssh/ssh.c, src/modules/content-sqlite/content-sqlite.c, src/modules/cron/cron.c, src/modules/kvs/kvs.c, src/modules/kvs/libkvs.c, src/modules/kvs/proto.c, src/modules/kvs/proto.h, src/modules/kvs/test/proto.c, src/modules/libjsc/jstatctl.c, src/modules/resource-hwloc/resource.c, src/modules/wreck/wrexecd.c
Various refactoring to update rpc calls from json-c to jansson style.  Such as calling ```flux_rpcf()``` over ```flux_rpc()```.
There are more that can be done, but I limited this PR to only those rpcs that dealt with simple int, string, etc. types.  Dealing with more complex objects/arrays require using the jansson library to create/manipulate said objects/arrays instead of the json-c library, and that's refactoring/cleanup for another day.
Most fixes should be self explanatory hopefully.  The noteable exception is https://github.com/flux-framework/flux-core/pull/1002/commits/37be05995855e21573b983422f58fd875655665d.  The jansson style functions are pickier on typing.  So a ```"1"``` (in quotes) is a string and not an integer, so I updated ```flux-cron``` to send the right type.
=> Issue 495 - jansson style rpc calls

src/broker/broker.c, src/broker/log.c, src/broker/module.c, src/broker/module.h, src/cmd/flux-start.c
As discussed in #25, instance shutdown is far from clean.  It's a bit better than before, now that we have the rc1, rc2, and rc3 run levels  (modules loaded in rc1 are unloaded in rc3), but the "normal" path is to let the shutdown timer (started at the beginning of rc3) expire and call exit from its reactor callback.
Since the reactor never returns, we never get back to `main()` to call destructors.
Ideally we'd like to get to the point where all reactor watchers are stopped after their subsystems are torn down and the reactor would exit naturally, with the timeout acting as a fallback rather than the main path.   That will require some design work to ensure the overlay is torn down in an orderly fashion without deadlocking distributed services, and is not attempted here.  
This PR takes …
=> call destructors in broker shutdown path

src/broker/exec.c, src/broker/ping.c, src/cmd/builtin/hwloc.c, src/common/libflux/content.c, src/common/libflux/test/response.c, src/modules/cron/cron.c, t/kvs/watch.c, t/loop/multrpc.c, t/loop/rpc.c, t/request/treq.c
Minor fixes/cleanup found while fixing issue #495.  Split off PR before the bigger fix PR.  Also includes  minor test additions.
=> Issue495 - Cleanup #2

src/modules/resource-hwloc/resource.c
Fix potential corner case if string buffer length includes
the NUL character at the end.  We do not wish to include it
in the rpc.  Instead, just write the string to the rpc directly
without the length (i.e. "{ s:s }" instead of "{ s:s# }").
Fixes #1010
=> modules/resource-hwloc: Fix potential corner case

src/common/libutil/Makefile.am, src/common/libutil/cleanup.c, src/common/libutil/cleanup.h, src/common/libutil/test/cleanup.c, src/common/libutil/test/unlink.c, src/common/libutil/unlink_recursive.c, src/common/libutil/unlink_recursive.h
This PR was originally in #1013 but wasn't quite on topic there, hence was broken out.
After the reactor exits, the broker sets up a SIGALRM handler in case its last ditch attempts to unload modules hangs.  This signal handler calls `exit()` which causes any registered `atexit()` functions to run, including one to clean up temporary files and `zsys_shutdown()` to close dangling zeromq sockets.  This latter one is installed automatically through the use of various libczmq classes.
`zsys_shutdown()`  has an internal mutex that would appear to only protect against concurrent calls to itself, not against calls to other socket operations.  Since zeromq sockets are not thread safe, this can lead to segfaults.  This became evident in PR #1013 when converting from zsocket to zsock classes.
To …
=> add unit tests for cleanup functions

src/test/travis-dep-builder.sh
Download and install latest autotools in travis builds.
This should resolve #925, though that is a bit difficult to test for certain...
Switching to spack for dependencies can come later, as discussed in #920
=> travis-ci: build with latest autotools

etc/rc3, src/broker/broker.c, src/broker/module.c, src/broker/module.h, t/Makefile.am, t/rc/rc3-kvs, t/rc/rc3-testenv, t/rc/rc3-wreck, t/sharness.d/flux-sharness.sh, t/t0001-basic.t, t/t0012-content-sqlite.t, t/t0015-cron.t, t/t0016-cron-faketime.t, t/t1001-barrier-basic.t, t/t2005-hwloc-basic.t
This PR takes another step towards cleaning up the broker shutdown path.
rc3 unloads modules that were loaded in rc1.   A reactor timer is set when rc3 is entered so that if it takes too long, the reactor is terminated and we can clean up and exit.  Due to #1006, we actually always let this timer run out to completion.
In this post-reactor cleanup path is some code that sends a "shutdown" request to any modules still loaded, and then calls `modhash_destroy()` which tries to destroy each module starting with a `pthread_join()`.  This is prone to hanging because for whatever reason, modules may not have processed the shutdown message (for example, they may be blocked in an RPC).
A SIGARLM timer was set up to break out of _this_ hang and move things along, however it's a kludge, another …
=> improve reliability of module unloading

configure.ac, src/bindings/lua/lua-affinity/lua-affinity.c, src/broker/content-cache.c, src/broker/test/attr.c, src/cmd/flux-jstat.c, src/cmd/flux-ping.c, src/common/libflux/flog.c, src/common/libutil/coproc.c, src/common/libutil/log.c, src/common/libutil/test/coproc.c, src/modules/wreck/wrexecd.c, t/t0007-ping.t
This PR gets flux-core working on the 32-bit arm7l architecture used in the Raspberry PI and other embedded platforms, e.g.
* fix 64 bit values used as printf-style arguments with ambiguous format specifier (e.g. `%lu`)
* relax some arbitrary test timeouts
* fix 64-bit pointer assumption in `makecontext()`  usage
* reduce VM footprint of test that tried to malloc 20gb of memory
There are a few unrelated minor bug fixes here as well:
* fix NULL deref in content-cache error path
* fix missing newlines in log output
* get working with the latest zeromq (4.2.1)
=> fix several arm7l portability issues

src/modules/connector-local/local.c, t/t0001-basic.t
This PR fixes issue #1025, in which a sched test fails due to a `flux-start` timeout during post-reactor shutdown.  It turns out there is a pretty obvious deadlock potential in the connector-local module.
The connector-local module is removed manually as a special case after reactor shutdown, thus it cannot make any RPCs as part of its shutdown path since they cannot be answered.  However, it does attempt to call `flux_event_unsubscribe()` during shutdown if any clients are still connected at this point, and have active subscriptions.
The fix is to disable these unsubscribes in the tear-down path.  Their state gets removed anyway when the module context is destroyed.
Add a regression test for this case.
Also, the back-to-back instances run in t0001-basic.t take a really long time due to …
=> avoid deadlock when unloading connector-local module

src/common/libflux/test/security.c
Check for EACCES depends on system setup and errno may be something
else such as EROFS or EPERM.  Genericize test to simply check for
failure.
=> test/security: Fix test corner case

src/modules/connector-local/local.c
In if statement caller checks return value from function both != 0
and non-NULL.  Remove the != 0 check.
=> modules/connector-local: Fix compiler warning

config/systemd.m4, config/x_ac_expand_install_dirs.m4, configure.ac, etc/Makefile.am, etc/flux.service.in, etc/rc1, src/common/libflux/Makefile.am
A few small tweaks here to improve the default systemd service unit file included with flux.
* Use AC variable "runstatedir" instead of $localstatedir/run for *both* "default" (i.e. system) FLUX_URI and the `broker.rundir` passed to the systemd initiated flux broker.
* If `--with-systemdsystemunitdir=` is not explicitly used, always prepend `${prefix}` to this PATH, so that the unit file is not installed outside of the chosen `$prefix`. This could get us into trouble if systemd pkg-config file already has `$prefix` in the systemdsystemunitdir variable, but I don't think this is an issue in practice.
* Don't install systemd unit file with executable bits
* Add `Delegate=yes` to systemd unit to delegate cgroup for flux.service to flux user.
When installing flux-core to `/usr/local` on your …
=> Small improvements for systemd unit file and install paths

doc/man1/flux-broker.adoc, doc/man7/flux-broker-attributes.adoc, doc/test/spell.en.pws, src/broker/broker.c, src/cmd/flux-start.c, t/t0001-basic.t
Support new attributes that allow the end user to configure endpoints for the flux broker.
=> Issue385: Support tbon.endpoint and mcast.endpoint attributes

doc/man1/flux-hwloc.adoc, doc/test/spell.en.pws, src/cmd/Makefile.am, src/cmd/builtin/hwloc.c, src/modules/resource-hwloc/resource.c, t/t2005-hwloc-basic.t
A bit of a diversion here. While playing with system instance of flux, I found it handy for FLUX_ROLE_USER to be able to query hwloc topology. No other `resource-hwloc` service is exposed further than the owner role.
Additionally, for a terse view of resources across the instance, I added a `flux hwloc info` subcommand, which gives the simplest possible view of Machines, Cores, and PUs available from the instance. This should be viewed as a stand-in for a better replacement down the road (it should use a separate service in `resource-hwloc` to calculate counts at each broker, reduce and forward results for scalability, and other resources like Memory should be added), however, this simple approach has proved useful for now.
```
$ srun --pty -N24 --mpi=none src/cmd/flux start
(flux-923ktt) …
```
=> hwloc: open topology request to user role, add simple "info" subcommand

doc/man7/flux-broker-attributes.adoc, src/broker/broker.c, t/t0001-basic.t
Update broker attribute names given recent additions of ```tbon.endpoint``` and ```mcast.endpoint```
=> Issue1040: Update broker attribute names

src/common/liboptparse/optparse.c, src/common/liboptparse/optparse.h, src/common/liboptparse/test/optparse.c, src/test/travis-dep-builder.sh
Initially started working on this because I thought POSIXLY_CORRECT behavior of optparse was broken. In order to test properly, an `optparse_reset()` function was added to allow a full reset of a parser (mostly useful in testing perhaps), then tests for this new interface as well as posixly-correct parsing behavior were added.
In the end, there wasn't a problem with POSIXLY_CORRECT functionality of optparse. Instead of throwing away all the new testing, I added an ability to disable POSIXLY_CORRECT for GNU getopt in optparse, which could come in handy in the future (?).
Additionally, I had to add a fix for #1048 here in order to get travis to pass in my branch.
=> optparse: test and allow adjustment of posixly-correct behavior

src/broker/broker.c, src/broker/exec.c, src/broker/heartbeat.c, src/broker/modservice.c, src/broker/module.c, src/broker/overlay.c, src/broker/overlay.h, src/broker/ping.c, src/broker/runlevel.c, src/broker/rusage.c, src/broker/service.c
This PR is more cleanup.  It converts the remaining broker C modules that use json-c to jansson.
@grondo it may be good for you to have a quick look over the exec.c commit proposed here.   It's passing tests on my c9 image, but I did need to change it more than I wanted to make the error paths more clear (to me) as I worked through it.  If this causes grief in your imp test branch, we can always skip this commit here and try again later.
=> convert broker from json-c to jansson (cleanup)

doc/man1/flux-content.adoc, doc/man7/flux-broker-attributes.adoc, src/broker/content-cache.c, src/common/libutil/blobref.c, src/common/libutil/blobref.h, src/common/libutil/test/blobref.c, src/modules/content-sqlite/content-sqlite.c, src/modules/kvs/kvs.c, t/Makefile.am, t/t0011-content-cache.t, t/t0012-content-sqlite.t, t/t2008-althash.t
Although the content cache was written so the hash type could be configured to use an algorithm other than the default sha1, there are a few obstacles to overcome to make that work.
First is to allow the hash type to be configured on the broker command line, e.g.
```
$ flux start -o,-Scontent.hash=sha256
```
Next is to have the KVS pick up the configured hash type and use it, since it pre-generates blobrefs to use as hash keys in its internal cache when content store requests are sent off (they can't wait for the response to get the hash key).
Finally, add a test that makes sure this works.
Along the way I updated the names of all the attributes used by the content store to be namespaced in the more modern way:  `content.name-of-attr` rather than `content-name-of-attr`, and updated users …
=> allow hash type to be configured

src/broker/content-cache.c, src/cmd/flux-ping.c, src/common/libflux/Makefile.am, src/common/libflux/dispatch.c, src/common/libflux/flux.h, src/common/libflux/handle.h, src/common/libflux/message.c, src/common/libflux/message.h, src/common/libflux/rpc.c, src/common/libflux/rpc.h, src/common/libflux/test/message.c, src/common/libflux/types.h, src/modules/kvs/kvs.c, t/loop/rpc.c
This is some cleanup peeled off of PR #1055.
Relatively minor stuff:  adding aux get/set functions to flux_rpc_t and flux_msg_t,
making `flux_msg_copy()` more efficient, and adding tests covering these changes.
=> cleanup of flux_msg_copy(), flux_rpc_aux_set() etc. and tests

src/modules/kvs/kvs.c, t/t1000-kvs-basic.t
Minor changes to allow ELOOP to be returned to user when KVS links go too deep.  Add appropriate tests as well.
Remove unnecessary and potentially confusing no-op line of code.
=> KVS directory walk return error fixes

src/common/libflux/handle.c, src/common/libflux/module.c, src/common/libutil/Makefile.am, src/common/libutil/dirwalk.c, src/common/libutil/dirwalk.h, src/common/libutil/test/dirwalk.c, src/common/libutil/unlink_recursive.c
This PR adds a new "dirwalk" class to libutil, encapsulating a common case of recursively walking a directory tree. `dirwalk` is like a simplified `ftw(3)`, however it allows the passing of a user context so results can be collected without the use of globals.
Since recursive directory search of a colon-separated path may be a common case, a `dirwalk_find` wrapper around `dirwalk` is also provided, which passes all entries that match a glob pattern to the user callback, and collects marked paths in a zlist_t on behalf of the user.
This may be a bit of overkill, but it was hard to stop once I started collecting common code together.
Current users of readdir were also updated to the new interface.
Fixes #1054
=> Add dirwalk interface to libutil, update readdir callers

src/common/libutil/test/dirwalk.c
Hit this on catalyst:
```
FAIL: test_dirwalk.t 20 - breadth-first visited directories with DIRWALK_REALPATH works
```
Debugged a bit, had to fix what I think is a corner case in the debug output:
```diff
@@ -158,11 +158,12 @@ int check_zlist_order (zlist_t *l, const char *base, char *expected[])
BAIL_OUT ("asprintf");
result = strcmp (exp, dir);
-        free (exp);
if (result != 0) {
-            diag ("check_zlist: %d: expected %s got %s", i, expected[i], dir);
+            diag ("check_zlist: %d: expected %s got %s", i, exp, dir);
+            free (exp);
return 0;
}
+        free (exp);
i++;
dir = zlist_next (l);
}
```
Result:
```
not ok 20 - breadth-first visited directories with DIRWALK_REALPATH works
```
My ```TMPDIR``` happens to default to ```/var/tmp```, which is a symlink. …
=> Add fixes to dirwalk tests

src/modules/kvs/kvs.c
This PR addresses an invalid memory read in `getroot_rpc()` noted by @grondo in #1064.
It also fixes similar problematic code in `setroot()`, although it doesn't look like that one was actually causing a problem.
=> fix invalid memory read in kvs module

src/cmd/cmdhelp.c, src/common/libflux/connector.h, src/common/libflux/handle.c, src/connectors/ssh/ssh.c
As discussed in #1062, we were seeing memory corruption from an error path in ssh connector because of the order of destruction of connector implementation object and flux handle object. Since `flux_handle_destroy` wanted to nullify its argument, but called the implementation's destroy method first, this could result in writing to freed memory if the handle was stored *within* the implementation (as in ssh connector).
Long story short - it is probably simplest to avoid the "destroy nullifies its argument" idiom in this case, as it is rarely used in the rest of flux API, and we can thereby avoid other accidental cases of memory corruption like this in the future.
I also found a small memory leak in cmd/cmdhelp.c that I threw in here (after some valgrind runs)
=> Change flux_handle_destroy prototype to avoid potential memory corruption, fix small leak in flux cmd help

src/common/libutil/dirwalk.c, src/common/libutil/test/dirwalk.c
Oops, I noticed that some functions in dirwalk.c needed to be marked `static`.
Along the way I added a couple basic tests for symlinks, and dirwalk_find() on non-directories.
=> dirwalk: add tests for a couple corner cases, fix symbol leakage

src/modules/kvs/cache.h, src/modules/kvs/kvs.c
A few cleanups spliced out of PR #1066
=> KVS Cleanup

src/modules/kvs/Makefile.am, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/json_util.c, src/modules/kvs/json_util.h, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/lookup.h, src/modules/kvs/test/cache.c, src/modules/kvs/test/lookup.c
In this PR, we convert the KVS walk function from a recursive implementation into a non-recursive one and simplified the logic as well.  The predominant logic changes are:
A) In preparation for maintaining "state" so that RPCs aren't fully replayed, the entire path of the kvs get request is pre-parsed and stored in a list.
B) The walk() function has been made non-recursive and "depth" is maintained in a stack.  This is also in preparation for maintaining "state" for removal of RPC replay.
C) A variety of	code logic changes to make the walk() function simpler.
The predominant logic changes that may look strange in this PR are:
A) The pre-parsing of the path makes things more inefficient for the time being b/c RPCs are still completely replayed (i.e. it is fully parsed on every RPC-then …
=> KVS refactor of lookup() / walk() functions

src/modules/kvs/kvs.c
Remove unnecessary cache_entry_create() call, as it is impossible
to reach.
=> modules/kvs: Cleanup content_load_completion()

src/common/libflux/reactor.c, src/common/libflux/reactor.h
This PR is not intended to be merged, but just to get feedback.
Following up on @garlick's similar changes to allow creation of custom watchers outside of `reactor.c`, these changes slightly modify watcher internals and expose `flux_watcher_create` and some accessors for the opaque watcher type.
However, I'm not sure if the approach goes too far, or not far enough, or if we should try something else.
The changes are pretty simple, however, highlights are:
* The integer per-class `signature` was dropped because it didn't seem like there was a feasible way to guarantee uniqueness for new and/or custom watchers.
* The watcher operations structure was replaced with a pointer to a global per-class `flux_watcher_ops` structure, since there should just be one global/static operations structure …
=> tweak watcher structure, add external watcher construction interface

doc/man3/flux_reactor_create.adoc, src/common/libflux/reactor.c, src/common/libflux/test/reactor.c, t/lua/t1002-kvs.t, t/rolemask/loop.c, t/rpc/rpc.c, t/rpc/util.c
This PR was split out of PR #1083.  It alters the return value of `flux_reactor_run()`.  On success, return the active watcher count so >= 0 indicates success, not just zero.  Drop the code that returned -1 with errno = EWOULDBLOCK if the FLUX_REACTOR_NOWAIT or FLUX_REACTOR_ONCE flag was specified as agreed in #963.
=> flux_reactor_run() should return active watcher count

doc/man3/flux_reactor_create.adoc, src/common/libflux/reactor.h
Fix a comment in reactor.h for FLUX_REACTOR_NOWAIT that was out of date, as noted by @grondo in #1085.
Also, fix an out of date flag description in flux_reactor_create(3).
=> improve reactor documentation

t/rolemask/loop.c, t/rpc/rpc.c, t/rpc/util.c, t/t0001-basic.t, t/t5000-valgrind.t
These are some assorted test improvements split out of PR #1083
=> Minor test improvements

doc/man3/Makefile.am, doc/man3/flux_future_create.adoc, doc/man3/flux_future_then.adoc, doc/man3/flux_open.adoc, doc/test/spell.en.pws, src/common/libflux/Makefile.am, src/common/libflux/dispatch.c, src/common/libflux/dispatch.h, src/common/libflux/flux.h, src/common/libflux/future.c, src/common/libflux/future.h, src/common/libflux/handle.c, src/common/libflux/handle.h, src/common/libflux/test/future.c, t/Makefile.am, t/loop/dispatch.c
This is a preliminary PR not for merging yet.
It's an implementation of futures, as discussed in #1053.  The core API is:
```C
typedef struct flux_future_struct flux_future_t;
typedef void (*flux_continuation_f)(flux_future_t *f, void *arg);
flux_future_t *flux_future_create (flux_reactor_t *r);
void flux_future_destroy (flux_future_t *f);
int flux_future_set_timeout (flux_future_t *f, double timeout);
int flux_future_get (flux_future_t *f, void *result);
bool flux_future_check (flux_future_t *f);
int flux_future_then (flux_future_t *f, flux_continuation_f cb, void *arg);
void flux_future_set_result (flux_future_t *f,
void *result, flux_free_f free_fn);
void flux_future_set_error (flux_future_t *f, int errnum);
```
The basic idea is that a future is completed by calling `set_result()` or …
=> implement flux_future_t API

src/common/libpmi/pmi.c, t/t5000-valgrind.t
Problem: Valgrind test reports leaks in slurm's libpmi.so
on TOSS 2 systems.
The broker, or rather our internal PMI library, will try
hard to use an external PMI environment if available.
On systems where slurm's libpmi.so is installed, the
broker, when run without flux-start, will use that, and
our valgrind test reports leaks in it.
Add environment variable FLUX_PMI_SINGLETON which can be used
to force (internal) singleton bootstrap if no other
environment variables are set to influence PMI bootstrap.
Fixes #1090
=> add FLUX_PMI_SINGLETON env variable to avoid SLURM's libpmi in valgrind test

t/t5000-valgrind.t
Quick attempt at w/a for false positive valgrind results observed in #1097.
Even if `valgrind/valgrind.h` is not found, the test can be forced if the `-d` or `--debug` option is used on the cmdline, e.g.:
```
grondo@hype2:~/git/flux-core.git/t$ ./t5000-valgrind.t 
1..0 # SKIP skipping valgrind tests b/c valgrind.h not found. Use -d, --debug to force
grondo@hype2:~/git/flux-core.git/t$ ./t5000-valgrind.t -d    
sharness: loading extensions from /g/g0/grondo/git/flux-core.git/t/sharness.d/01-setup.sh
sharness: loading extensions from /g/g0/grondo/git/flux-core.git/t/sharness.d/flux-sharness.sh
not ok 1 - valgrind reports no new errors on single broker run
#	
#		flux ${VALGRIND} \
#			--tool=memcheck \
#			--leak-check=full \
#			--gen-suppressions=all \
#			--trace-children=no \
# …
```
=> only run valgrind tests if valgrind/valgrind.h was found

t/t2000-wreck.t
Fix failure:
not ok 49 - wreck job is linked in lwj-complete after failure
which may occur if lwj-complete.<epoch> directory has not appeared
in kvs by the time of the *first* pass in the check_complete_link()
function.
Instead of checking for the last epoch dir once in the function,
check it on every loop.
Fixes #1101
=> Fix intermittent failure of t2000-wreck.t

src/modules/kvs/Makefile.am, src/modules/kvs/test/json_util.c
A simple addition.  I was playing with converting the fence unit tests to jansson, but those tests use ```json_compare``` in ```json_util```, so really need to convert that first.  Thus some unit tests were in order.
=> modules/kvs: Add json_util unit tests

t/t2000-wreck.t
The check for the last complete job via
```
flux kvs dir lwj-complete | tail -1
```
is not safe b/c there is no guarantee that the directory entries
are sorted when output.  In combination with the lastjobid, the
test may try to retrieve a kvs field that will never exist.
Sort lwj complete entries by epoch and then use ```tail -1```.  Adjust
surrounding code appropriately.
=> t2000-wreck.t: fix logic in check for archive job

src/common/libkvs/kvs_classic.c
jansson format string for packing a double is "f" as opposed to "F"
Partial fix to https://github.com/flux-framework/flux-sched/issues/256
=> kvs_classic: fix kvs(dir)_put_double

src/bindings/lua/flux-lua.c, src/common/libkvs/kvs_classic.c, src/common/libkvs/kvs_classic.h, t/kvs/basic.c
This PR collects some odds and ends that were left out of pr #1107:
* A fix to #1112 after @grondo verified with valgrind that it's needed (I thought might fix a problem I was looking for in #1107 but that turned out to be something else).
* Drop some "classic" functions that have no users in sched or core: `kvs_put_double()` and `kvs_put_boolean()`.
* Drop `kvs_put_treeobj()` which had only one test user (test converted to `flux_kvs_txn_put()`)
=> KVS lua refcount fix, drop unused deprecated functions

src/bindings/python/.pylintrc, src/bindings/python/flux/kvs.py, src/bindings/python/flux/rpc.py, src/bindings/python/make_binding.py
remove the deprecated `unused-argument`:
- remove the unused argument in kvs walk
- rename `then_wrapper` to `cb_then_wrapper`; pylint won't check
functions prefixed with `cb_` for unused arguments
remove the deprecated `required-attributes` and `ignore-iface-methods`
swap the deprecated `ignore-all` for `skip-file`
Related: https://github.com/flux-framework/flux-core/issues/1046 (I don't believe this fully fixes it, but it addresses several of the issues)
=> python: make bindings compatible with newer versions of pylint

src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/kvs.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c
I was in the process of doing a lot of random cleanup (remove oom() calls, remove use of xzmalloc(), etc.) and found a number of circumstances where there were cleanup errors along error/cleanup
paths.  Here are descriptions of some of the bigger ones:
17d1764947d23e6ccef34875205f44ad9578e39a - if RPCs are already in flight when an error occurs, stall and let them finish, before returning error to user.  This was in older KVS code and I broke it while refactoring.
a41bfed76c04ca4f7f616262660bc2b2e6d6e217 - Way back in commit 0cbeacc09aba444f2c972cd7cd83846d721922f7, there was a relatively harmless logic error (i.e. had no effect except for possibly a tad less optimal).  But with the commit API refactoring, it actually mattered a bit more b/c it complicated some logic.  This logic has been …
=> Kvs cleanup error paths

src/cmd/flux.c
The check for whether the flux command driver is installed or in
the build tree does not canonicalize X_BINDIR, so if this path
includes a symlink the test will incorrectly fail.
Canonicalize the path using `realpath(3)` before the comparison
to avoid missing detection of installed flux. If realpath() returns
ENOENT, then the install path doesn't exist and we must be running
from the builddir.
Fixes #1121
=> Fix flux path detection when install path contains symlinks

src/cmd/flux-kvs.c, src/common/libkvs/kvs_classic.c, src/common/libkvs/kvs_classic.h, t/kvs/basic.c, t/kvs/commit.c, t/kvs/commitmerge.c, t/t1000-kvs-basic.t, t/t1002-kvs-cmd.t
This PR converts some KVS users to new API functions and jansson, and removes several "classic" functions: `kvs_move()`, `kvs_copy()`, and `kvsdir_symlink()` from the API.
=> [cleanup] convert KVS users to new API and jansson, drop some old API functions

src/common/libkvs/jansson_dirent.c, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/fence.c, src/modules/kvs/kvs.c, src/modules/kvs/kvs_util.c, src/modules/kvs/kvs_util.h, src/modules/kvs/lookup.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/fence.c, src/modules/kvs/test/kvs_util.c, src/modules/kvs/test/lookup.c, src/modules/kvs/test/waitqueue.c, src/modules/kvs/waitqueue.c, src/modules/kvs/waitqueue.h
Like other refactorings that have been going on in flux-core, this one removes a large number of ```oom()``` calls and functions that call ```oom()``` (notably ```xzmalloc()``` and ```xstrdup()```).  Instead
ENOMEM is detected, properly return as an error, check for error, log error, etc.
A few ```oom()```s remain (```wait_runqueue()``` and the merging ops functions).  Those will require a tad more re-architecture and logic updates so I will put those in another PR.  The changes in this PR are relatively more grunted out fixes without much thought except for cleanup path handling.
I suspect the coverage on this diff will be bad.  I'd be surprised if it was even greater than 50% coverage, as almost the entirety of it is handling ENOMEM errors and the cascading checks for functions that can …
=> KVS oom() and xzmalloc() cleanup

src/broker/broker.c, src/broker/runlevel.c, src/broker/runlevel.h, t/t0001-basic.t
Add an optional timeout on the initial program (rc2) - something @grondo and I were discussing this morning.  The idea was that sharness `test_under_flux` might use this to make travis test hangs more easy to debug.
The timeout is set as an attribute.  When the timeout expires, a SIGTERM is sent to the initial program.  For example
```
$ ./flux start -o,-Sinit.rc2_timeout=0.1 sleep 1
2017-07-26T17:53:31.306006Z broker.err[0]: runlevel 2 timeout, sending SIGTERM
2017-07-26T17:53:31.306390Z broker.err[0]: Run level 2 Terminated (rc=143) 0.1s
$ echo $?
143
```
This is mainly useful for testing, or at least I didn't have another use case in mind as I wrote this.
=> add optional initial program timeout, for test scripts

src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/fence.c, src/modules/kvs/fence.h, src/modules/kvs/kvs.c, src/modules/kvs/kvs_util.c, src/modules/kvs/lookup.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/waitqueue.c, src/modules/kvs/waitqueue.c, src/modules/kvs/waitqueue.h
These are fixups for two remaining ```oom()``` paths left in the KVS.  These were trickier and required some additional logical changes, so I wanted to put them in another PR.
In ```wait_runqueue()```, the primary change that had to occur to return an error to the user is that either all of the elements would be copied off of the queue, or none of them.  We can't have an error occurring in the middle while we remove elements off one queue and put them on another.  There's no way to get back to what you had before.  Performance wise, this is effectively a change from 2 loops to 3 loops.
There are several catastrophic-like scenarios in the main KVS code if ```wait_runqueue()``` fails.  I chose not to ```assert()``` them.  But maybe I should have.  I went back and forth on it.  Dunno what …
=> KVS more oom() fixes

src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/test/cache.c
The function cache_entry_force_clear_dirty() should also destroy the
dirty waitqueue, as the entries in the waitqueue no longer matter
and it would prevent the cache entry from ever being reclaimed.
=> modules/kvs: Fix forced dirty bit clear error

.travis.yml, codecov.yml, src/common/libflux/test/security.c, t/sharness.d/flux-sharness.sh, t/t0016-cron-faketime.t
This branch started out as a small fix to propagate sharness' `--chain-lint` option to `test_under_flux` so that broken `&&`-chains can be detected for tests that run under a flux instance.
After that, I went through all the tests and fixed broken `&&`-chains so that `--chain-lint` ran clean.
In most cases the broken `&&` chain wasn't an actual problem, but I fixed the test anyway. In other cases it wasn't possible to make `--chain-lint` happy (e.g. test that use `&` to run a process in the background). For these cases I added a `NO_CHAIN_LINT` prereq that can be explicitly added to a tests so that test is skipped during a run with `--chain-lint`.
Finally, the `flux version` check (once it was fixed) didn't work in travis (at least on my personal branch) because travis uses a shallow …
=> Fix testsuite --chain-lint option, add timeout to some tests, and other testing fixes

src/common/libutil/base64.h
base64_encode_block() and base64_decode_block() require dstlen
to be passed in, but the header files say they are optional.  Adjust
documentation appropriately.
=> common/libutil: Fix base64 API documentation

.travis.yml, src/test/travis-dep-builder.sh
This PR adds `-j2` to many of the make commands during travis-ci builds (both builds of dependencies and  make distcheck for the code itself)
This helps mitigate the problem described in #1141.
=> travis-ci: mitigate slow builds

doc/test/spellcheck, src/connectors/local/local.c, t/t5000-valgrind.t
As @garlick suggested in #677, add an exponential backoff to local connector connect retries, rename the variable to tune the retry count from `FLUX_RETRY_COUNT` to `FLUX_LOCAL_CONNECTOR_RETRY_COUNT`, and use this variable in t5000-valgrind.t to give up to 10 retries.
I tried to make the the default retry count of 5 still time out after ~500ms, so I made the starting sleep 16ms, which should sleep a total of 496ms in the default cause -- unless in my haste I did some math wrong.
=> connector/local: add exponential backoff to connect retry count

doc/man1/flux-cron.adoc, src/cmd/flux-cron, src/common/libutil/cronodate.c, src/common/libutil/cronodate.h, src/common/libutil/shortjson.h, src/common/libutil/test/cronodate.c, src/modules/cron/cron.c, src/modules/cron/datetime.c, src/modules/cron/entry.h, src/modules/cron/event.c, src/modules/cron/interval.c, src/modules/cron/task.c, src/modules/cron/task.h, src/test/travis-dep-builder.sh, t/t0015-cron.t
This PR updates the cron module to use jansson instead of json-c, removes other uses of xzmalloc that would result in calls to `oom()` and friends, and fixes some other leaks and issues found along the way.
A new function for was added to the cronodate interface to allow adding non-range integers to a cronodate object, for cases where arguments to cron "datetime" entries are encoded by the caller as numbers and not strings (as is done for ranges, e.g. "0-3" or glob "*"). The datetime argument parser was then updated to check for whether individual arguments were encoded as strings or numbers, and uses the appropriate function `cronodate_set` or `cronodate_set_integer`. This is required because unlike json-c, jansson doesn't allow decoding a number value as a string.
This PR is based on …
=> cron: avoid use of json-c and xzmalloc

src/bindings/lua/flux-lua.c, src/common/libkvs/kvs_txn.c, src/modules/kvs/commit.c, src/modules/kvs/fence.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/fence.c, t/kvs/watch.c
Spliced out set of cleanup patches or minor bug fixes from TreeObject work both @garlick and I have been working on.
Note that @garlick has one patch in this PR, but it's only addition of a copyright header.  Dunno if its safe for him to hit the button.  But copyright header probably counts as "non-source documentation" (https://github.com/flux-framework/rfc/blob/master/spec_1.adoc).
=> Misc Cleanup/Minor Fixes from KVS TreeObject Work

src/common/libkvs/Makefile.am, src/common/libkvs/kvs.h, src/common/libkvs/kvs_commit.c, src/common/libkvs/kvs_commit.h, src/common/libkvs/kvs_dir.c, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_txn.c, src/common/libkvs/kvs_txn.h, src/common/libkvs/kvs_txn_private.h, src/common/libkvs/test/kvs_dir.c, src/common/libkvs/test/kvs_lookup.c, src/common/libkvs/test/kvs_txn.c
Spliced out patches from a larger RFC11 PR that @garlick and I are working on.  Apologies I missed these and didn't put them in #1152 as I couldn't quite see their independence at first.
All patches are from @garlick.  I've reviewed and it looks good to me.  But as I'm opening this PR, think it's wrong for me to hit the button.
=> Misc Refactoring & Cleanup in libkvs

NEWS.md
Add NEWS.md entry for v0.8.0. Once this is merged we can add the v0.8.0 tag.
I guess we should first go through the 0.8.0 milestone and move everything off to 0.9.0 and 0.10.0.
=> update NEWS.md for flux-core v0.8.0

.travis.yml, t/t0001-basic.t, t/t0003-module.t, t/t0005-exec.t, t/t0007-ping.t, t/t0009-dmesg.t, t/t0010-generic-utils.t, t/t0015-cron.t, t/t0016-cron-faketime.t, t/t1000-kvs.t, t/t1001-barrier-basic.t, t/t1002-kvs-extra.t, t/t1008-proxy.t, t/t2000-wreck.t, t/t2001-jsc.t, t/t2005-hwloc-basic.t, t/t3000-mpi-basic.t
This PR reverts Travis-CI to use the vm builder instead of container builders by replacing `sudo: false` with `sudo: true` in `.travis.yml`. In my testing, this change completely resolves the intermittent (but high frequency) failures under travis such as hangs the `write error` problem, and really slow builds (#1145, #1141, etc.)
WIth that change in place, I was able to rebase many (minor) testsuite fixes I had on a branch, which fix up all the broken `&&`-chains in the testsuite, as well as add timeouts to some tests which have the potential to hang.
I think because many people have moved to the container build infrastructure, the VM build queue is not quite as long as it was getting before, so I don't think this change will slow down the turnaround time on Travis reporting.
This PR …
=> testsuite: revert travis-ci to vm builds and fix many broken &&-chains in tests

doc/man3/flux_future_create.adoc, src/common/libflux/future.c, src/common/libflux/test/future.c, src/common/libkvs/test/kvs_lookup.c
Add missing input checks to various future functions and add appropriate unit tests.
Add missing unit tests in libkvs, as that was what prompted issue #1157.
=> libflux: Add input checks to future functions

src/cmd/flux-start.c, t/t0001-basic.t
If user specifies --bootstrap=selfpmi but does not specify --size,
output error message indicating it is needed.
Add unit test to test for this particular failure.
Fixes #1026
=> cmd/flux-start: Add input error check

doc/man1/flux-kvs.adoc, src/cmd/Makefile.am, src/cmd/flux-kvs.c, src/common/libkvs/kvs_dir.c, src/common/libkvs/test/kvs_dir.c, t/t1000-kvs.t
This adds a `flux kvs ls` subcommand that behaves similar to ls(1), as discussed in #1158.
```
Usage: flux-kvs ls [-R] [-d] [-w COLS] [-1] [-W] [-C] [key...]
List directory
-1, --1                Force one entry per line
-C, --columns          List entries by columns
-F, --classify         Append indicator (one of .@) to entries
-R, --recursive        List directory recursively
-d, --directory        List directory instead of contents
-w, --width            Set output width to COLS.  0 means no limit
```
=> kvs: add flux kvs ls subcommand

t/sharness.d/flux-sharness.sh, t/t0001-basic.t
This PR adds a minor enhancement to `test_under_flux` to detect when modules are not unloaded that were loaded manually during the course of the tests as suggested in #1020.
Unfortunately, the only place that we can insert code at test completion is by adding another "final cleanup" hook. These run *after* the final test summary, so this is not ideal, however we can still get the test overall to exit with non-zero status, and a fatal `error` message emitted to stdout so that it appears in output and logfiles.
```
grondo@flux-core:~/workspace/t (test_under_flux) $ cat test.t
#!/bin/sh
test_description="test_under_flux with module loaded, but not unloaded"
. ./sharness.sh
test_under_flux 2 minimal
test_expect_success "flux module load kvs" "
flux module load -r 0 kvs
"
test_done …
```
=> sharness: test_under_flux: add fatal error if modules loaded during test aren't unloaded at test completion

autogen.sh
Make autogen.sh exit after any of the commands fail.
Remove the "-I config" option from the autoreconf command
which appears to be redundant with either AC_CONFIG_AUX_DIR([config])
or AC_CONFIG_MACRO_DIR([config]) in the configure.ac file.
Stop removing autom4te.cache.  We can't remember why we did that.
Resolves #1162
=> build: Exit on error in autogen.sh plus other cleanup

src/modules/kvs/kvs.c
This PR fixes needless alarming error messages noted in #1174, and eliminates the last use of the (internal) KVS  `load()` function with wait == NULL.  That allows `load()` to be simplified a bit.
=> modules/kvs: handle root dir object caching more precisely

src/modules/cron/cron.c
Problem: cron module segfaults during travis testing on arm7l.
Change a json_pack() format string to use "I" not "i" to
refer to uint64_t values.
Fixes #1176
=> modules/cron: fix segfault on 32 bit systems

src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/kvs_util.c, src/modules/kvs/kvs_util.h, src/modules/kvs/lookup.c, src/modules/kvs/test/kvs_util.c, t/t1000-kvs.t
This PR adds code to deal with extra path separators in keys.
Duplicate,  leading, and trailing separators are removed, which addresses #1180 and #1173.
Sharness and unit tests are added.
=> modules/kvs: normalize keys before use

src/common/liboptparse/optparse.c, src/common/liboptparse/optparse.h, src/common/libsubprocess/subprocess.c, src/common/libsubprocess/subprocess.h, src/test/travis-dep-builder.sh
This PR fixes newer compiler warnings that complain about passing default type promoted objects as an argument to `va_start`. In both places this is done in the current code, an enum is passed as the last argument before the ellipsis in a variadic function, and I guess this could cause undefined behavior depending on how the enum is promoted.
The fix for now is to simply change the argument to an integer.
This should fix current failures in travis, since the warning causes  a fatal error with `-Werror`
=> build: fix newer compiler warnings about enum passed to va_start

src/common/liboptparse/optparse.c, src/common/liboptparse/test/optparse.c
As described in #1179, optparse error message for unrecognized option is not correct when an invalid short option is used and grouped with one or more valid options.
Fix this by assuming an invalid short option when `optopt != '\0'` and use the char in `optopt` as the unrecognized option in the error output. Otherwise, assume a long option and use `argv [optind-1]` as the invalid option to display.
Simple tests were also added to ensure valid error messages for unrecognized short options, grouped and ungrouped.
=> optparse: fix incorrect error message when invalid short option is grouped with valid short options

src/broker/Makefile.am, src/broker/broker.c, src/broker/service.c, src/broker/service.h, src/broker/test/service.c
This PR was prep work for dynamic service registration, but I switched to other priorities before getting too far into it a month ago.  What was completed is valid cleanup, so I thought it preferable to submit as a cleanup PR than let it languish until I get back to the original topic.
Some exit-on-ENOMEM behavior was avoided, some style violations were set right, and some poor naming was (hopefully) improved.  The broker "service hash" was prepped to allow for an arbitrary association of service names to callbacks (which refer to broker services or modules), instead of the hardwired primary name and secondary alias.  And a test was added for that class.
=> broker/service: cleanup and prepare for dynamic service registration

doc/man3/flux_future_create.adoc, doc/man3/flux_future_then.adoc, src/common/libflux/future.c, src/common/libflux/future.h, src/common/libflux/rpc.c, src/common/libflux/test/future.c
I noted when implementing some (forthcoming) KVS work that used composite futures (futures within futures, e.g. futures that perform multiple RPCs) that the internal future interfaces were not quite flexible enough to support composite futures, and that we had no tests for composite futures.
This PR makes a minor change to those interfaces, dropping the reactor argument from `flux_future_create()` and `flux_future_init_f`, and adding reactor get/set functions.
Tests for several composite future use cases are added and man pages adjusted.
=> libflux/future: minor interface changes to support composite futures

doc/man3/flux_log.adoc, src/common/libflux/flog.c, src/common/libflux/flog.h, t/Makefile.am, t/loop/logstderr.c, t/t0001-basic.t
Make flux handle optional in logging functions.  If flux handle
is NULL, output to stderr.
Add unit tests appropriately.
Fixes #1191
=> libflux/flog: Support output to stderr

src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/kvs.c, src/modules/kvs/kvs_util.c, src/modules/kvs/lookup.c, src/modules/kvs/lookup.h, src/modules/kvs/test/commit.c, src/modules/kvs/test/lookup.c
Replace lingering log calls that log to stderr with calls that
log to flux logging facility.  Requires passing optional flux_t
handle to internal lookup and commit APIs.
Remove lingering unnecessary includes of log.h throughout.
Fixes #1165
=> modules/kvs: Log to flux not stderr

src/modules/content-sqlite/content-sqlite.c
If thread cancellation interrupts sqlite operation, the main thread may not be 
able to acquire lock inside sqlite calls during clean up and hangs.
=> Issue#1194: delay thread cancellation during sqlite.

etc/.gitignore, etc/Makefile.am
Add flux.service to .gitignore, since it is generated from
flux.service.in at configure time.
Remove the EXTRA_DIST of flux.service. Since this is generated
at configure time from flux.service.in and flux.service.in
is already part of the dist by way of being declared in AC_CONFIG_FILES,
it does not appear that flux.service should be EXTRA_DIST.
=> flux.service: Fix EXTRA_DIST and .gitignore

doc/man3/flux_content_load.adoc, doc/man3/flux_mrpc.adoc, doc/man3/flux_request_decode.adoc, doc/man3/flux_response_decode.adoc, doc/man3/flux_rpc.adoc, src/broker/content-cache.c, src/broker/log.c, src/cmd/builtin/content.c, src/common/libflux/content.c, src/common/libflux/content.h, src/common/libflux/message.c, src/common/libflux/message.h, src/common/libflux/mrpc.c, src/common/libflux/mrpc.h, src/common/libflux/request.c, src/common/libflux/request.h, src/common/libflux/response.c, src/common/libflux/response.h, src/common/libflux/rpc.c, src/common/libflux/rpc.h, src/common/libflux/test/message.c, src/common/libflux/test/request.c, src/common/libflux/test/response.c, src/common/libutil/readall.c, src/common/libutil/readall.h, src/modules/content-sqlite/content-sqlite.c, src/modules/kvs/kvs.c, t/request/req.c, t/rpc/rpc.c
As noted in #1211, `flux_msg_get_payload()`  and all the functions based on it should use const on the `void **data` paramter, since the payload belongs to the message (also const).
New prototypes:
```c
int flux_msg_get_payload (const flux_msg_t *msg, int *flags,
const void **buf, int *size);
int flux_request_decode_raw (const flux_msg_t *msg, const char **topic,
const void **data, int *len);
int flux_response_decode_raw (const flux_msg_t *msg, const char **topic,
const void **data, int *len);
int flux_content_load_get (flux_future_t *f, const void **buf, int *len);
int flux_rpc_get_raw (flux_future_t *f, const void **data, int *len);
int flux_mrpc_get_raw (flux_mrpc_t *mrpc, const void **data, int *len);
```
All the internal code that touches these functions was also updated.
Man pages …
=> API: add const to message payload accessor functions

src/modules/kvs/cache.c, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/lookup.c
Pulling out these cleanup & minor fix patches from another patch series for #1187.  Includes simple fixes (comments, code styles), minor cleanup (putting things in functions, removing unused parameters in function calls), some corner case fixes, and returning error on bad inputs to some functions.
=> Misc KVS cleanup & minor fixes

src/common/libkvs/test/treeobj.c, src/common/libkvs/treeobj.c, src/common/libkvs/treeobj.h, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/lookup.h, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/lookup.c, t/t1002-kvs-extra.t
This series of patches updates the KVS so that treeobj valref objects will read/write data to the content store in raw/unencoded form.
The key work was to ensure the internal KVS cache could handle storing raw data instead of only json.  After this work, the remaining work sort of "fell out" of this.  On lookup, create cache entries that contain raw data and handle them appropriately for valref objects.  On commits, cache entries with raw data will be written out as raw data (instead of everything being assumed json).
=> kvs: store data pointed by valref raw and unencoded in content store

doc/man3/Makefile.am, doc/man3/flux_kvs_lookup.adoc, doc/man3/flux_kvs_txn_create.adoc, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_lookup.h, src/common/libkvs/kvs_txn.c, src/common/libkvs/kvs_txn.h, src/common/libkvs/test/kvs_lookup.c, t/kvs/basic.c, t/t1002-kvs-extra.t
This PR adds `flux_kvs_lookup_get_raw()` to the KVS API, to go with `flux_kvs_txn_put_raw()`, then modifies `t/kvs/basic` to use them instead of an extra base64 encoding layer for `copy-tokvs` and `copy-fromkvs` subcommands.  Finally add a couple of sharness tests  to fill test gaps identified in #1214 (lookup unencoded content)  and #1215 (zero length value).
This is based on top of #1214
=> kvs: add flux_kvs_lookup_get_raw()

src/common/libkvs/kvs.h
Fix missing extern "C" wrapper in kvs.h from issue #1223 PR, as mentioned in issue #1224.
=> kvs.h add extern "C" wrapper

src/broker/broker.c
Minor code cleanup in the flux broker.
=> Broker cleanup 1

src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/kvs.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c
Spliced out these patches from #1227 and a forthcoming PR for #1232.
=> KVS: Misc cleanup, add test coverage, minor bug fix

src/broker/attr.c, src/broker/attr.h, src/broker/broker.c, src/broker/overlay.c, src/broker/overlay.h, t/lua/t0004-getattr.t
Additional broker clean up along the path to supporting multiple bootstrap methods.
=> Broker cleanup 2

src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/test/cache.c, t/t1002-kvs-extra.t
This series of patches is to support valref treeobjects pointing to zero-length blobref data.
This seems like a lot of code for a pretty dumb corner case, but it came down to updating the KVS cache API to not assume non-NULL data pointer means valid and NULL data pointer is invalid.  A flag was placed into the KVS cache entry to handle this, but it beget a number of API style changes.
For starters, ```cache_entry_get_raw ()``` had to be modified so that a NULL data buffer returned wasn't automatically assumed to be error.  This is an obvious refactoring that was needed.  The rest are more subtle.
Under the old API:
```cache_entry_create_json (NULL)``` - creates an empty/invalid cache entry
```cache_entry_create_raw (NULL, 0)``` - creates a valid cache entry???
```cache_entry_set_json (hp, …
```
=> KVS: Support valref pointing to zero length blob objects

src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/lookup.h, src/modules/kvs/test/lookup.c, t/kvs/basic.c, t/t1002-kvs-extra.t
To support #1193 and #1202, this PR adds support to read valref treeobjs with multiple blobrefs in it.  Note that outside of manual creation of multiple valref objects, there is no present easy mechanism to write multi-blobref valref objects.  The "write" half of these features is for later subtasks in #1193 and #1202.
There are two major parts to this PR.  One was to refactor the internal KVS lookup API to support multiple missing references being returned to callers.  The second major part was to support loading multiple blobrefs in the internal KVS lookup API and creating a single val object to return the value to the caller.
=> KVS: Support reading valref objects with multiple blobrefs

src/modules/kvs/commit.c, src/modules/kvs/lookup.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/lookup.c
Previously EPERM was generally used as the errno to signify that
the state without the KVS was inconsistent/illogical (e.g. a
dirref points to a val object).  To remove confusion that a
potential security issue is in play, change the errno from EPERM
to ENOTRECOVERABLE.
Update unit tests appropriately.
Fixes #1228
=> modules/kvs: Replace EPERM w/ ENOTRECOVERABLE

src/broker/broker.c, src/broker/overlay.c, src/broker/overlay.h
More cleanup and refactoring of the broker in preparation for issue #1236.  The next step will likely be to break up boot_pmi() to split out the things that are really specific to PMI, and those that are not.
=> Broker cleanup 3

src/common/libkvs/kvs.h, src/common/libkvs/kvs_commit.c, src/common/libkvs/kvs_lookup.h, src/common/libkvs/kvs_txn.c, src/common/libkvs/kvs_txn_private.h, src/common/libkvs/test/kvs_txn.c, src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/fence.c, src/modules/kvs/fence.h, src/modules/kvs/lookup.c, src/modules/kvs/test/commit.c, src/test/travis-dep-builder.sh
This PR changes the request message format for KVS commit/fence to incorporate a `flags` parameter in each of the operation objects in the "ops" array.  This prepares for a KVS append operation, as discussed in #1193.
Since operations were encoded/decoded in several places, I added new (internal to KVS client and server) functions `txn_encode_op()` and `txn_decode_op()`, and used them in the client transaction code, and server commit code.  The decoding function uses the JSON_STRICT `!` flag to tighten things up a bit.
While adding this to the commit code, I fixed an error handling oversight that would allow a commit request to silently ignore a malformed operation and return success to the caller.
Finally, the KVS flags definitions were moved to kvs.h from kvs_lookup.h.  They are not …
=> KVS modify commit protocol in preparation for append

src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/test/cache.c
Spliced out of a bigger PR for #1239.  Nothing too exciting.
=> kvs: Misc cleanup & bug fixes

.travis.yml, t/t2004-hydra.t
Attempt to make travis builds more reliable by abandoning the use of `-j 2` for `make distcheck`. This will hopefully reduce the occurrence of #1145.
We also hit the hydra test errors quite a bit (#1169). This PR doesn't change the tests but adds more debug to the output so we can hopefully see something interesting when the test does fail. (I didn't get it to fail in my testing, of course)
=> travis-ci: attempt to make builds more reliable

src/modules/kvs/Makefile.am, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/lookup.h, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/lookup.c, t/t1002-kvs-extra.t
This PR refactors the KVS cache to favor the storage of raw data over json objects.  This accomplishes several goals.
1) before this PR, KVS cache entries had a data "type" associated with it.  This can lead to a "race" in which how the data was loaded into the KVS cache the first time and could lead to errors/bugs later.  For example, if data was incorrectly loaded into the KVS cache as type json, a later attempt to read the data out of the KVS cache as raw data would fail, leading to an error.
2) This should clean up the code and hopefully make it less confusing.  Many unit tests were removed in this PR, so I feel the less confusing part was accomplished.
The primary idea behind this refactor to remove the "type" system with KVS cache entries and make the KVS cache primarily for storing …
=> kvs: refactor kvs cache to handle raw data as "primary" data

src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/test/cache.c
As discussed in PR #1246, a minor cleanup & refactoring that I wanted to split off b/c it would involve additional API changes.  This solves cleanup described in #1247.
=> kvs: minor cleanup & refactoring

config/ax_compiler_vendor.m4, configure.ac
Import AX_COMPILER_VENDOR autoconf-archive macro and use the
discovered vendor to determine whether to set WARNING_CFLAGS and
WARNING_CXXFLAGS instead of using $GCC = "yes". Turns out that $GCC is
set to "yes" whenever __GNUC__ is defined by the compiler, and this
doesn't imply strict compatibility with gcc.
Fixes #1251
=> build: only set warning flags for GNU and Clang

.travis.yml, configure.ac, src/bindings/python/flux/Makefile.am
This PR disables the pylint check for the python bindings by default, and adds a new configure option `configure --enable-pylint` to get them back. That option is enabled on one of the travis-ci builders so that we still get pylint run on every PR submission and push to the repo.
The pylint implementation seems to be rather brittle, extremely version dependent, etc. as described in #1250, so this will hopefully make those problems invisible for most users (while still enabling those working on the python bindings to enable the check as they need it)
=> disable pylint check of python bindings by default

doc/man3/Makefile.am, doc/man3/flux_kvs_lookup.adoc, doc/man3/flux_kvs_txn_create.adoc, doc/test/spell.en.pws, src/bindings/lua/flux-lua.c, src/cmd/flux-kvs.c, src/common/libjsc/jstatctl.c, src/common/libkvs/Makefile.am, src/common/libkvs/kvs_classic.c, src/common/libkvs/kvs_dir.c, src/common/libkvs/kvs_dir.h, src/common/libkvs/kvs_dir_private.h, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_lookup.h, src/common/libkvs/kvs_txn.c, src/common/libkvs/kvs_txn.h, src/common/libkvs/kvs_watch.c, src/common/libkvs/test/kvs_dir.c, src/common/libkvs/test/kvs_txn.c, t/kvs/basic.c
This PR makes some minor changes to public KVS API functions, and restructures the lookup and txn implementations a bit to be more efficient and maintainable.  The public-facing API changes are, first, to add three new functions:
```c
int flux_kvs_txn_put_treeobj (flux_kvs_txn_t *txn, int flags,
const char *key, const char *treeobj);
int flux_kvs_lookup_get_symlink (flux_future_t *f, const char **target);
int flux_kvs_lookup_get_treeobj (flux_future_t *f, const char **treeobj);
```
rather than overloading `flux_kvs_txn_put()` and `flux_kvs_lookup_get()`; and second, to relax `flux_kvs_txn_put()` and `flux_kvs_lookup_get()` with respect to requiring values to be in encoded JSON form.  You can now use those interfaces to put/get any NULL terminated string in the KVS.
The man pages …
=> KVS: clean up lookup and txn API's

configure.ac
In commit bd4fee8dac192025a88a8fc8cf273c864f687a9b the pylint check
was accidently left enabled by default. The intent was to have the
default be *disabled* and only run pylint on --enable-pylint.
Sorry! Not sure how that slipped through (I promise I tested functionality several times) :cry:
=> build: actually disable pylint by default

doc/man3/Makefile.am
Apparently we've asked asciidoc to generate one too many
man page stubs from flux_kvs_txn_create.adoc.
Since it's not generated, make install fails.  For now,
drop the stub from the Makefile.am so make install can work.
Fixes #1256
=> build: drop man page stub that cannot be generated

doc/man1/flux-kvs.adoc, src/cmd/flux-kvs.c, t/issues/t0441-kvs-put-get.sh, t/issues/t0821-kvs-segfault.sh, t/kvs/basic.c, t/lua/t1002-kvs.t, t/t0017-security.t, t/t1000-kvs.t, t/t1002-kvs-extra.t, t/t2000-wreck.t, t/t2001-jsc.t, t/t2002-pmi.t, t/t2005-hwloc-basic.t
This PR updates the `flux kvs` command to handle non-JSON values.  These deficiencies were discussed  in #1158 and #1159.
A summary of the changes proposed here are:
* `flux kvs dir` displays non-JSON values
* `flux kvs dir` truncates output to fit terminal width, controlled with `--width=COLS`
* `flux kvs put` and `flux kvs get` now accept the `--raw`, `--json`, and `--treeobj` options to allow greater control over how values are stored and interpreted.
As a reminder the KVS just stores raw values now, imposing no structure.  We have convenience functions for get/put of strings (NULL terminated), and JSON (encoded as strings).  The get/put subcommands now default to storing strings, as opposed to JSON-encoded strings.  The `--json` option was  added to emulate the past behavior.  The …
=> kvs: handle non-JSON values in flux kvs get, put, dir

doc/man1/flux-kvs.adoc, doc/man3/flux_kvs_lookup.adoc, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_txn.c, src/common/libkvs/kvs_watch.c, src/common/libkvs/test/kvs_txn.c, src/common/libkvs/test/treeobj.c, src/common/libkvs/treeobj.c, src/common/libkvs/treeobj.h, t/t1000-kvs.t, t/t1002-kvs-extra.t
As described in #1261, strings were stored in the KVS with terminating NULL, but this complicates the implementation of atomic append (#1193) and the reasons for doing it no longer exist.
Drop the NULL byte. 
Update tests and docs.
=> kvs: string/JSON values should not be stored with NULL termination

src/modules/kvs/cache.c, src/modules/kvs/commit.c, src/modules/kvs/kvs_util.c, src/modules/kvs/kvs_util.h, src/modules/kvs/test/cache.c
This is the server equivalent of PR #1262 / issue #1261.  Although not necessary, PR #1262 should probably be merged first.
=> kvs: do not store NUL byte on json encoded strings in kvs server

doc/man1/flux-kvs.adoc, doc/man3/flux_kvs_txn_create.adoc, src/cmd/flux-kvs.c, src/common/libkvs/kvs.h, src/common/libkvs/kvs_txn.c, src/common/libkvs/test/kvs_txn.c, src/common/libkvs/test/treeobj.c, src/common/libkvs/treeobj.c, src/common/libkvs/treeobj.h, src/modules/kvs/commit.c, src/modules/kvs/test/commit.c, t/t1000-kvs.t
This PR implements basic append support in the KVS and a basic ```--append``` option in flux-kvs.
=> kvs: support append operation

t/valgrind/valgrind.supp
As noted in #1240, the valgrind test fails when building under spack on recent ubuntu because the stack trace for getaddrinfo() leak is slightly different than the existing suppression entry in this environment. This PR just generalizes that suppression so that *any* leak under getaddrinfo() is suppressed.
=> generalize valgrind suppression for getaddrinfo

src/common/libkvs/test/treeobj.c, src/common/libkvs/treeobj.c, src/common/libkvs/treeobj.h, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/lookup.c
This is part one if issue #1264.  A minor refactor, renaming several "json" functions to "treeobj" and adjusting the logic accordingly.
I'm splitting it up b/c the second half of #1264 is growing and seems particularly distinct.
=> kvs: refactor server cache functions

src/common/libkvs/test/treeobj.c, src/common/libkvs/treeobj.c, src/common/libkvs/treeobj.h, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/test/cache.c
This is a refactor for the ```cache_entry_get_json()``` function to return a const json_t pointer.  It's not valid for a caller to modify a json object that is sitting in the KVS cache.  The idea to make this const came from #1265, as it took me awhile to hunt down a corruption issue when I began modifying json objects stored in the cache.
Making ```cache_entry_get_json()``` return a const pointer had a lot of fallout.
A very large number of treeobj functions had to be made const, which is the right thing to do and is semi-obvious (i.e. functions like ```treeobj_is_dir()``` or ```treeobj_get_count()```).
In the few cases that it made no sense for a treeobj function to take or return a const, an alternate function to take / return const was supplied (i.e. ```treeobj_peek_entry()``` over …
=> kvs: return const from cache_entry_get_json()

src/common/libkvs/test/treeobj.c, src/common/libkvs/treeobj.c, src/common/libkvs/treeobj.h, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/kvs_util.c, src/modules/kvs/kvs_util.h, src/modules/kvs/lookup.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/kvs_util.c, src/modules/kvs/test/lookup.c
part three of issue #1264.  This is the easy set of cleanups/refactoring.  Don't think anything here will be considered too fascinating.
Only thing to note is the old ```kvs_util_json_has()``` function took a ```href_t```, but ```treeobj_hash()``` takes a ```char *``` and int.  It's b/c ```href_t``` is only defined for the KVS server right now.  Considered removing ```href_t``` and generalizing it with ```char ref[NUM]```, but I elected not too.
=> kvs: additional cleanup and refactoring

config/ax_lua.m4
The older version of ax_lua.m4 that we used was failing to
abort when AX_LUA_HEADERS failed to find headers.  That is
no longer a problem in the new ax_lua.m4.
Fixes #1270
=> Update to the latest ax_lua.m4

src/common/libkvs/kvs.c, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/lookup.c
As discussed in #1264, `cache_entry_set_raw()` and `cache_entry_set_treeobj()` take ownership of a data/json_t pointer allocated in the caller.  The caller must be trusted not to free or modify the data afterward, or the cache will be corrupted.  This seems a bit unsafe.
Copy the data, increasing isolation between the cache and its callers.
In the treeobj case, avoid caching the json_t object directly, since it is hard to ensure that the caller won't change it later.  We could `json_deep_copy()` it, but it is perhaps cheaper to skip caching it here, and instead allow the object to be regenerated from the encoded data on first use (if it gets used at all).
Plus one small optimization:  avoid an extra call to treeobj_encode in the commit path, where we had to first encode the object to …
=> kvs: [cleanup] improve isolation in internal cache

src/broker/content-cache.c, src/common/libkvs/test/treeobj.c, src/common/libkvs/treeobj.c, src/common/libkvs/treeobj.h, src/common/libutil/blobref.c, src/common/libutil/blobref.h, src/common/libutil/test/blobref.c, src/modules/content-sqlite/content-sqlite.c, src/modules/kvs/Makefile.am, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/lookup.c, src/modules/kvs/types.h, t/kvs/blobref.c
This is mainly cosmetic.  As noted in #1222 the use of the "hp" variable name to refer to an internal KVS cache entry is ubiquitous and confusing.  Change it to "entry".
Drop the `href_t` typedef in the KVS and create an identical definition called `blobref_t` over in libutil/blobref.h.  Change some of the blobref functions to accept the fixed length char array rather than char pointer and length to make less verbose to use by its primary user in the KVS.
Drop the `treeobj_hash()` function which no longer has any users (replicating it in unit tests that need it, and changing it to use a blobref_t argument).
=> kvs: [cleanup] fix blobref_t typedef and unfortunate variable names

config/x_ac_yamlcpp.m4
When yamlcpp support is found, check that the yaml-cpp/yaml.h header can be included without error, and issue a fatal error from configure if not.
(Sorry, not much time to get anything else done today so I decided to tackle this one)
=> build: detect broken libyaml-cpp during configure

doc/man3/flux_msg_handler_addvec.adoc, doc/man3/treduce.c, src/broker/attr.c, src/broker/attr.h, src/broker/broker.c, src/broker/content-cache.c, src/broker/exec.c, src/broker/heaptrace.c, src/broker/hello.c, src/broker/log.c, src/broker/sequence.c, src/broker/shutdown.c, src/cmd/builtin/proxy.c, src/common/libflux/msg_handler.c, src/common/libflux/msg_handler.h, src/common/libjsc/jstatctl.c, src/modules/aggregator/aggregator.c, src/modules/barrier/barrier.c, src/modules/connector-local/local.c, src/modules/content-sqlite/content-sqlite.c, src/modules/cron/cron.c, src/modules/kvs/kvs.c, src/modules/resource-hwloc/resource.c, src/modules/userdb/userdb.c, src/modules/wreck/job.c, t/module/parent.c, t/request/req.c, t/rpc/mrpc.c, t/rpc/rpc.c
This is following up on an idea @morrone had in #1135 to clean up the bulk message handler reg/unreg functions.  The `flux_msg_handler_t` member is dropped from `struct flux_msg_handler_spec`, and instead a new array of message handlers is returned from `flux_msg_handler_addvec()`.
`flux_msg_handler_delvec()` then accepts the array of message handlers, destroying them and freeing the array.
In addition, a small mention about rolemask security is added to the message handler man pages.
Updated users, tests, and man pages.
This will require a PR to flux-sched.  Please don't merge until that's queued up.
=> libflux: clean up bulk message handler registration functions

t/t1001-kvs-internals.t, t/t2000-wreck.t
While working on #1286 , noticed there was no coverage for kvs.stats.clear.  So added a few tests.
Also fixed a typo I found.
=> kvs: Add stats.clear test coverage

src/common/libjobspec/jobspec.cpp
Make the implementation come to compliance with RFC14's JRC rule section.
Tested with resource-query and this one-liner seems enough.
=> jobspec: replace minus operator to multiplication

src/bindings/lua/Makefile.am, src/bindings/lua/lua-affinity/lua-affinity.c, src/bindings/lua/lua-hostlist/hostlist.c, src/common/libflux/test/reactor.c, src/common/liblsd/Makefile.am, src/common/libsubprocess/zio.c, src/common/libutil/Makefile.am, src/common/libutil/test/cronodate.c, t/t5000-valgrind.t
I trashed my OpenBox Ubuntu VM and had to reinstall.  For fun I chose a newer Ubuntu 32 bit image.  This PR addresses some issues I ran into.
I'm not completely sure that the error tolerance increase I added to the cronodate unit test is completely above board, so that one could use some validation.
I have two other problems that I'll open issues on:
* valgrind sharness test detects an invalid read of size 1 in libev/ev.c::3634, which is a use of the ECB_MEMORY_FENCE macro.
* lua affinity test 16: large value to new causes numeric overflow is failing with "expected numeric overflow, got 0xff".
for now I'm just going to work around those.
=> portabilty fixes for gcc 7.2 and Ubuntu 17.10 i686 

doc/man1/flux-kvs.adoc, doc/man3/Makefile.am, doc/man3/flux_kvs_commit.adoc, doc/man3/flux_kvs_lookup.adoc, doc/man3/flux_kvs_namespace_create.adoc, doc/test/spell.en.pws, src/cmd/flux-kvs.c, src/common/libkvs/Makefile.am, src/common/libkvs/kvs.c, src/common/libkvs/kvs.h, src/common/libkvs/kvs_commit.c, src/common/libkvs/kvs_commit.h, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_lookup.h, src/common/libkvs/kvs_private.h, src/common/libkvs/kvs_watch.c, src/common/libkvs/kvs_watch.h, src/common/libkvs/test/kvs.c, src/modules/kvs/kvs.c, t/Makefile.am, t/kvs/watch.c, t/kvs/watch_disconnect.c, t/t1004-kvs-namespace.t, t/t1103-apidisconnect.t, t/t2000-wreck.t
As described in #1197, here is the part 1 pull request where we refactor the KVS to not initialize itself automatically and we store KVS metadata in a hash table.  All in preparation for private namespace support.
After doing this, I'm debating if this should be a separate PR, b/c there's going to be a fair amount of code paths that I don't believe can be tested until private namespace support is added.
We'll see what the coverage looks like after it goes through travis and determine if we should have this as part of the mega-PR later on for private namespaces.
=> kvs: Refactor in preparation for private namespaces

doc/man3/flux_kvs_commit.adoc, doc/test/spell.en.pws, src/modules/kvs/fence.c, src/modules/kvs/test/fence.c
Fix corner case in which nprocs could be exceeded and additional
operations appended onto a fence.  Now, user will receive an EOVERFLOW
error if they have exceeded the nprocs count.
=> modules/kvs: Fix potential to exceed nprocs

src/common/libjobspec/flux-jobspec.pc.in
Fix a flux-sched autoconf problem when it uses
PKG_CHECK_MODULES to gather libraray info on jobspec
package.
Apparently pkg-config doesn't like the dependent
package name: "Yaml-cpp."
On quartz:
$ uname -a
Linux quartz1916 3.10.0-693.5.2.1chaos.ch6.x86_64 #1
SMP Wed Oct 25 16:20:31 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
$ pkg-config --cflags flux-jobspec
Package Yaml-cpp was not found in the pkg-config search path.
Perhaps you should add the directory containing `Yaml-cpp.pc'
to the PKG_CONFIG_PATH environment variable
Package 'Yaml-cpp', required by 'flux-jobspec', not found
Get a simiar configure error when
PKG_CHECK_MODULES([JOBSPEC],[flux-jobspec],[],[]) is used.
=> jobspec: Use "yaml-cpp" instead of "Yaml-cpp"

doc/man1/flux-kvs.adoc
A number of open source projects have been removing the term "slave" from their lexicon.  So to be up with the times, remove "slave" nomenclature that lingered in this manpage.
=> doc/man1/flux-kvs: Update language

src/common/libkvs/kvs.h, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/test/commit.c
misc patches spliced out of my larger remove namespace PR.  All simple and obvious.
=> kvs: minor cleanup

src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/kvs.c, src/modules/kvs/test/commit.c
This PR is peeled off from my namespace remove work.  It feels semi-independent of the larger work and decided it may be useful to put it off in its own PR.
This is independent of #1309 .
=> kvs: add more kvs stats

src/modules/kvs/kvs.c
Note that this PR comes after #1308 (patches in #1308 are included here).  I will rebase after #1308 is merged in.
I originally had this patch mixed in with my remove namespace PR, but it seems independent of everything else, so I've now spliced it into its own PR.
The ```relayfence_request_cb()``` function presently does not return an error to the original rpc fence/commit request if an error occurs within this function.  An error could be returned to the user only within the ```commit_apply()``` path of the code if we reached that path and an error occurred within there.
This patch fixes the problem by effectively calling the error path from ```commit_apply()``` if an error occurs within this function.
Unfortunately, outside of some serious code instrumentation, this patch is basically …
=> kvs: Return error that occurs in kvs.relayfence

t/Makefile.am, t/kvs/kvs-helper.sh, t/t1000-kvs.t, t/t1002-kvs-watch.t, t/t1004-kvs-namespace.t
Some simple kvs test cleanup I wanted to do.  Mostly put some common functions into ```kvs/kvs-helper.sh```, but some tiny things beyond that too.
=> kvs test cleanup

src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/fence.c, src/modules/kvs/fence.h, src/modules/kvs/kvs.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/fence.c
This PR has a few tiny corner case fixes, some general refactoring/abstraction fixes in the internal commit API, and some code re-organization in the core KVS file.
=> kvs: general refactoring and cleanup

src/modules/kvs/Makefile.am, src/modules/kvs/kvs.c, src/modules/kvs/msg_cb_handler.c, src/modules/kvs/msg_cb_handler.h, src/modules/kvs/test/msg_cb_handler.c, src/modules/kvs/test/waitqueue.c, src/modules/kvs/waitqueue.c, src/modules/kvs/waitqueue.h
Per discussion in #1197, make ```getroot()``` call asynchronous.
In this PR, a ```struct getroot_handler``` was added to handle information needed in getroot continuation calls.  Two design notes on this:
1) The getroot call is needed in kvs.get, kvs.watch, kvs.sync, and kvs.fence.  This collection of request handlers were different enough from each other that it seemed more work than would be reasonable to place the getroot call within the lookup interface, commit interface, and whatever I would do for kvs.sync.  So I elected to handle getroot asynchronous-ness outside of those interfaces.
2) This getroot handler code is 90% similar to what is in ```waitqueue.c``` code.  But b/c of the abstraction of ```wait_t```, I couldn't quite exploit using it.  Refactoring a common "callback …
=> kvs: Make getroot() asynchronous

src/modules/kvs/kvs.c
If a namespace has not been touched/modified on a follower node
for a long period of time, and no one is watching a key on it,
and no unfinished fences are lingering, remove the namespace from the node.
The namespace still lives on in the rank 0 leader node, but data/info
is not replicated on follower nodes.
=> modules/kvs: Support namespace timeout

src/modules/kvs/Makefile.am, src/modules/kvs/commit.c, src/modules/kvs/kvs.c, src/modules/kvs/kvsroot.c, src/modules/kvs/kvsroot.h, src/modules/kvs/test/kvsroot.c
This branch isn't ready for merging (need to add documentation & unit tests) but thought I'd push to ask for comments.
I had originally gone down the path of abstracting the kvsroot way more than what is done in this PR.  But as I was refactoring, it became clear abstracting ```struct kvsroot``` was creating a complex and probably unnecessary level of abstraction.
For example, abstracting ```start_root_remove()``` in ```kvs.c```.  It's a good idea to want to abstract it away, but its difficult to abstract away the cleanup of fences sitting in the commit manager.  Do we ask the user to pass in a callback function to deal with the cleanup of fences?  We aren't abstracting very well if we're asking the user for that.
I briefly considered moving everything related to commits into …
=> kvs: refactor with internal kvsroot file

src/common/libjsc/jstatctl.c
I think the returned object should be caught and freed. Valgrind reported this leak, so likely legit.
=> Fix memleak: free the job object returned.

doc/man1/flux-kvs.adoc, doc/man3/flux_kvs_namespace_create.adoc, src/cmd/builtin/user.c, src/cmd/flux-kvs.c, src/common/libkvs/kvs.c, src/common/libkvs/kvs.h, src/common/libkvs/test/kvs.c, src/modules/kvs/kvs.c, src/modules/kvs/kvsroot.c, src/modules/kvs/kvsroot.h, src/modules/kvs/test/kvsroot.c, t/Makefile.am, t/t1005-kvs-security.t
This PR allows instance owners to create a namespace that is owned by a non-instance owner, and thus can let that non-instance owner read/write to that KVS namespace.  In this implementation, only a single non-instance owner can read/write to a namespace.  Instance owners are always able to read/write to any namespace under their creation.  Only instance owners are only able to create/remove a namespace.
After writing the unit tests, I realized there's a lot of cleanup that could be done in both the t1004 kvs tests and t1005 kvs tests (sharing common code, writing better common functions, etc.).  But I am going to let that cleanup be for another day, to limit churn in this PR.
=> kvs: support non-instance owners of namespaces

doc/man1/flux-kvs.adoc, doc/man3/Makefile.am, doc/man3/flux_kvs_commit.adoc, doc/man3/flux_kvs_lookup.adoc, doc/man3/flux_kvs_set_namespace.adoc, src/cmd/flux-kvs.c, src/common/libkvs/Makefile.am, src/common/libkvs/kvs.c, src/common/libkvs/kvs.h, src/common/libkvs/kvs_commit.c, src/common/libkvs/kvs_commit.h, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_lookup.h, src/common/libkvs/kvs_private.h, src/common/libkvs/kvs_watch.c, src/common/libkvs/kvs_watch.h, src/common/libkvs/test/kvs.c, src/common/libkvs/test/kvs_commit.c, src/common/libkvs/test/kvs_watch.c, t/kvs/fence_namespace_remove.c, t/kvs/kvs-helper.sh, t/t1004-kvs-namespace.t, t/t1005-kvs-security.t
Previously, the only way to set/use a non-default KVS namespace was through the environment variable ```FLUX_KVS_NAMESPACE```.  This is inconvenient.  This PR adds a ```flux_kvs_set_namespace()``` and ```flux_kvs_get_namespace()``` set of functions, which allows a namespace to be set for a particular flux handle.
This allows a simple ```--namespace``` option to be added to the ```flux-kvs``` command.
This is a far more simple way to specify a namespace.  The environment variable option is still there, but using the functions/kvs option takes precedence over the environment variable.
This option allows us to clean up the unit tests a ton, as there was no need to constantly set/unset ```FLUX_KVS_NAMESPACE``` everywhere.
=> kvs: support non-environment variable mechanism to choose namespace

src/common/libkvs/kvs.h
"namespace" is a keyword in C++, so flux will want to avoid using
that in public headers.  We change the function parameter name
in kvs.h from "namespace" to "name_space" to reallow C++ linkage.
=> kvs: Change "namespace" to "name_space" in external header

src/common/libkvs/kvs.h, src/modules/kvs/fence.c, src/modules/kvs/fence.h, src/modules/kvs/kvs.c, src/modules/kvs/test/fence.c, t/Makefile.am, t/kvs/fence_invalid.c, t/t1001-kvs-internals.t
This fixes #1305, as fence documentation and kvs server behavior did not match.  IMO, the documentation indicated what the appropriate behavior should be, so code was adjusted to match it, and unit tests added.
=> kvs: check that fence parameters are identical

doc/man1/flux-kvs.adoc, doc/man3/Makefile.am, doc/man3/flux_kvs_namespace_list.adoc, doc/test/spell.en.pws, src/cmd/flux-kvs.c, src/common/libkvs/kvs.c, src/common/libkvs/kvs.h, src/common/libkvs/test/kvs.c, src/modules/kvs/kvs.c, t/t1004-kvs-namespace.t, t/t1005-kvs-security.t
Support a simple iterator to allow users to list the KVS namespaces that exist, along with the owner and current flags.  The ```flux kvs namespace-list``` option would list something like this:
```
NAMESPACE             OWNER      FLAGS
primary                8556 0x00000000
```
=> kvs: Support ability to list namespaces

doc/man3/flux_mrpc.adoc, src/cmd/builtin/hwloc.c, src/cmd/flux-ping.c, src/common/libflux/mrpc.c, src/common/libflux/mrpc.h, t/kvs/watch_disconnect.c, t/rpc/mrpc.c
For consistency, rename flux_mrpcf() to flux_mrpc_pack()
and rename flux_mrpc_getf() to flux_mrpc_get_unpack() just
as the changes were done in these prior commits.
libflux/rpc: rename rpcf->rpc_pack
9a5c28b170315e3fac5b8031cf5268e48c1cf078
and
libflux/rpc: rename rpc_getf->rpc_get_unpack
1a3626ba318f6adcba9479dc5cdc01240b8029a6
Fixes #1290
=> libflux/rpc: Rename flux_mrpcf() and flux_mrpc_getf()

src/common/libkvs/kvs.c, src/common/libkvs/kvs_commit.c, src/common/libkvs/kvs_lookup.c, src/modules/kvs/kvs.c
Minor cleanup of the callback names in the kvs module.  Some changes reflect more current naming styles within the KVS, and some were to remove use of periods per RFC 5.
=> kvs: cleanup callback names

src/common/libkvs/kvs_commit.c, src/common/libkvs/test/kvs_commit.c, src/modules/kvs/commit.c, src/modules/kvs/fence.c, src/modules/kvs/fence.h, src/modules/kvs/kvs.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/fence.c, src/modules/kvs/test/kvsroot.c
Minor things I fixed up on the way to fixing #1337.
=> kvs: minor fixes/cleanup

src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/fence.c, src/modules/kvs/fence.h, src/modules/kvs/kvs.c, src/modules/kvs/test/commit.c, src/modules/kvs/test/fence.c
In preparation for issue #1337 and not making that PR huge, this does a decent-refactoring on the commit & fence.  The core change is the commit & fence data structures are now more decoupled.  The commit data structure no longer contains a pointer to a fence and instead copies data in from the fence and stores it internally.  The need for this is hopefully somewhat obvious for #1337 .
As a consequence, the internal fence data structure was cleaned up.  I'm really happy with this refactoring, as the fence data structure now logically represents a "fence" more accurately.  In that fences are no longer mergeable, can't have > 1 name, can't have more than one fence's operations stored in it, etc.
=> kvs: refactor commit & fence

src/modules/kvs/commit.c, src/modules/kvs/commit.h, src/modules/kvs/fence.c, src/modules/kvs/fence.h, src/modules/kvs/kvs.c, src/modules/kvs/kvsroot.c, src/modules/kvs/kvsroot.h, src/modules/kvs/test/commit.c, src/modules/kvs/test/fence.c, src/modules/kvs/test/kvsroot.c
Following up #1343, this de-couples portions of the "commit manager" and creates a new "fence manager".  As the internal commit API and internal fence API were decoupled in #1343, additional portions could be spliced off.
=> kvs: Refactor commit & fence - part 2

src/common/libkvs/kvs_commit.c, src/modules/kvs/Makefile.am, src/modules/kvs/kvs.c, src/modules/kvs/kvstxn.c, src/modules/kvs/kvstxn.h, src/modules/kvs/test/kvsroot.c, src/modules/kvs/test/kvstxn.c
Instead of sending all commit and fence RPCs to the same kvs handler, have one for commits (```kvs.commit```) and one for fences (```kvs.fence```).
This makes the code far clearer on how commits and fences are different.
A) commits do not require "nprocs" and "name" to be sent in their  RPCs, so they are now removed.
B) a nice chunk of code is not needed for commits b/c nprocs is always 1 (i.e. don't need to do a lookup), so all that code is now removed in the commit path.
This completes issue #1344.
I was curious if this would improve performance, as commits are now far simpler than fences (less allocations, etc.).  A soak test showed:
before
```
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.210   0.230   0.240   0.238   0.240   0.300 
```
after
```
Min. 1st Qu.  Median    Mean 3rd Qu. …
```
=> kvs: have two request handlers for commits & fences

src/modules/kvs/kvstxn.c, src/modules/kvs/test/kvstxn.c
While working on #1352 (which is now closed and won't be done), I found these little things to be cleaned up / fixed.  All minor and they still apply.
=> kvs: minor fixes/cleanups

src/common/libkvs/kvs.h
Subject says it all, no clue why this works elsewhere but a build on toss2 died without this change.
=> anonymous enums kill bindings

src/cmd/flux-wreck, t/t2000-wreck.t
Fix typo/incorrect method call in `flux wreck purge` as noticed by @trws in #1356.
Also added a quick sanity of check of `flux wreck purge` in tests (don't know why this was never done!), and a few other runtime fixes I stumbled across during testing.
=> Fix flux-wreck purge

config/x_ac_yamlcpp.m4
As proposed in #1360, alter build system to build the jobspec library by default, failing at configure time if prereqs are missing, unless opting out with `configure --disable-jobspec`.
The enable option is added in configure.ac, and the call to the X_AC_YAML_CPP macro is made conditional on lack of `--disable-jobspec`.
The X_AC_YAML_CPP macro is modified so that PKG_CHECK_MODULES on yaml-cpp takes its normally fatal default _action-if-notfound_.
=> build: add --disable-jobspec opt-out configuration

doc/man1/flux-wreck.adoc, src/bindings/lua/flux/posix.lua, src/bindings/lua/flux/timer.lua, src/cmd/flux-cron, src/cmd/flux-wreck, src/modules/wreck/lua.d/01-env.lua, src/modules/wreck/lua.d/timeout.lua, t/t2000-wreck.t
This adds a `flux wreck cancel` command in support of #1359.
Along the way I was hitting #1364 in travis so had to add a workaround for that here as well.
The actual implementation of `flux wreck cancel` is very simple and the majority of the important work will be on the sched side.
=> wreck: add flux-wreck cancel command

src/cmd/flux-wreck, src/cmd/flux-wreckrun
Fix for encoding of `jobid` argument in `sched.cancel` command sent by `flux wreck cancel` as noted by @dongahn.
Also included is some removal of duplicated code in `flux wreckrun`
=> flux-wreck cancel should send jobid as JSON number

src/bindings/lua/flux/posix.lua
The workaround for broken `posix.clock_gettime` legacy function in
luaposix 34 wasn't quite correct, and breaks on versions that
include a `posix.time` module, but don't include `clock_gettime` in
that module. This fix checks to ensure `clock_gettime` is actually
available before trying to use it.
=> bindings/lua: fix clock_gettime workaround

doc/man1/flux-wreck.adoc, doc/test/spell.en.pws, src/bindings/lua/wreck.lua, src/cmd/flux-wreck, t/t2000-wreck.t
The `flux-wreck ls` and `timing` commands currently always attempt to list information for *all* jobs stored in the kvs. For large sessions running many jobs, the commands will always be very slow, and in some cases won't work if the table of jobs grows beyond the max size of a Lua table.
This PR addresses this problem with the following changes to these commands:
* By default, `flux-wreck ls` and `flux-wreck timing` will only list the last (by jobid number) 25 jobs in the kvs. This can be adjusted with a new `-n, --max=COUNT` option.
* These commands can now accept a list of JOBIDs as arguments (after all option arguments). The JOBIDs can appear as host ranges for convenience or multiple arguments on the command line, e.g: `flux wreck ls 1 2 3 4 5 10` or `flux wreck ls 1-5,10` or `flux …
=> flux-wreck: address scalability issue in 'ls' and 'timing' subcommands

src/common/libjsc/jstatctl.c, src/common/libjsc/jstatctl.h
Promote jsc_job_state2num () to be public as this convenience routine can help w/ writing test cases for schedulers.
This should have been public as it is paired with jsc_job_num2state () anyway.
=> jsc: Make jsc_job_state2num public

src/modules/kvs/kvs.c, src/modules/kvs/kvs_util.c, src/modules/kvs/kvs_util.h, src/modules/kvs/kvsroot.c, src/modules/kvs/kvsroot.h, src/modules/kvs/lookup.c, src/modules/kvs/lookup.h, src/modules/kvs/test/kvsroot.c, src/modules/kvs/test/kvstxn.c, src/modules/kvs/test/lookup.c, src/modules/kvs/test/waitqueue.c
Prep work for #1341, this is random cleanups and minor refactoring.
=> kvs: misc cleanup & refactoring

src/cmd/flux-wreck, t/t2000-wreck.t
This addresses issue #1379 with a couple minor changes to `flux wreck cancel`. When sched is loaded and it gets `EINVAL` error, `cancel` will fall back to equivalent of `flux wreck kill -9` on the job.
I also added a `-f, --force` option which allows `flux wreck cancel` to work even if sched is not loaded, mainly so the code could be tested in `t2000-wreck.t`.
=> flux-wreck cancel: fall back to kill -9 if job is not pending

src/modules/kvs/Makefile.am, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/lookup.h, src/modules/kvs/test/kvstxn.c, src/modules/kvs/test/lookup.c
This PR does a lot of refactoring on the internal kvs lookup API.  The two major accomplishments of this PR are:
1) Allow kvs namespaces to be looked up within the lookup API itself.
2) When a namespace is missing/not available, inform callers that it is missing and has to be brought in.
Then of course there are tons of unit tests along the way.
=> kvs: Refactor prep work for namespace prefix support

src/common/libjsc/README.md, src/common/libjsc/jstatctl.c, src/modules/wreck/job.c, t/t2001-jsc.t
This is in preparation for the upcoming flux-sched PR
and requires @grondo's `job.submit` change that is available
at [wreck-experimental](https://github.com/grondo/flux-core/tree/wreck-experimental).
The new wreck.state.submitted event will be piggybacked with
job request info such as the number of nodes and walltime and
the scheduler will make use of this front-loaded information to 
cut down on KVS accesses.
This also removes the null to null job transition code path
which is legacy code to break a race condition way
back when jsc was using KVS watch for job state monitoring.
Adjust jsc test case and README.
=> jsc: support for augmented wreck.state.submitted event

doc/man1/flux-wreckrun.adoc, src/bindings/lua/wreck.lua, src/cmd/builtin/hwloc.c, src/cmd/flux-wreck, src/cmd/flux-wreckrun, src/common/libjsc/jstatctl.c, src/common/libjsc/jstatctl.h, src/modules/resource-hwloc/resource.c, src/modules/wreck/Makefile.am, src/modules/wreck/job.c, src/modules/wreck/lua.d/pmi-mapping.lua, src/modules/wreck/rcalc.c, src/modules/wreck/rcalc.h, src/modules/wreck/wrexecd.c, t/Makefile.am, t/issues/t0900-wreck-invalid-cores.sh, t/t2000-wreck.t, t/t2001-jsc.t, t/wreck/rcalc.c
This is a set of changes accumulated in wreck to support the splash app issue #1358. It still needs work and tests added, but features are functional, including:
* Do not arbitrarily set nnodes in the kvs if the user didn't provide it, and preserve other user provided options in an `.opts` key in the kvs
* Fix `flux-wreck purge` sort order, as well as removal of empty `lwj.x.y.z` dirs after a purge.
* Add new `job.submit-nocreate` RPC to "submit" a job with an existing KVS entry, in support of:
* Schedule `flux wreckrun` jobs if a scheduler is present and the new `-I, --immediate` option is not provided
* Fix crash in `job.kvspath` #1394 
* Distribute the `lwj.ntasks` global ntasks properly across all cores in wrexecd, instead of assuming `rank.X.cores` is the number of tasks to run on …
=> wreck incremental improvements

src/modules/kvs/lookup.c, src/modules/kvs/test/lookup.c
Fix corner case in which a symlink in the kvs points to the root dir, i.e. ```"."```.
I discovered this corner case while working on #1341.  I realized users will probably often do:
```
mysymlink -> namespace/.
```
i.e. a symlink simply points to the root of another namespace.  But root dirs were not handled at all within symlinks.
=> kvs: Fix corner case in which symlink points to root dir

src/modules/wreck/rcalc.c, src/modules/wreck/rcalc.h, src/modules/wreck/wrexecd.c, t/Makefile.am, t/t1999-wreck-rcalc.t, t/t2000-wreck.t, t/wreck/input/1r1c.json, t/wreck/input/1r2c.json, t/wreck/input/4r4c4r1c.json, t/wreck/input/8r1c.json, t/wreck/output/1r1c.1.expected, t/wreck/output/1r2c.1.expected, t/wreck/output/1r2c.2.expected, t/wreck/output/4r4c4r1c.16.expected, t/wreck/output/4r4c4r1c.20.expected, t/wreck/output/4r4c4r1c.4.expected, t/wreck/output/4r4c4r1c.8.expected, t/wreck/output/4r4c4r1c.9.expected, t/wreck/output/8r1c.4.expected, t/wreck/output/8r1c.8.expected, t/wreck/output/8r1c.9.err, t/wreck/output/8r1c.9.expected, t/wreck/rcalc.c
This adds `rcalc_total_nnodes_used()` call to the wreck/rcalc class, and then uses that to set nnodes internally in wrexecd. This should prevent jobs with larger allocations than tasks from hanging (but this needs testing)
I also added some R-lite inputs for testing under `t/wreck/input`, and verification of output in a new `t1999-wreck-rcalc.t` test.
This isn't ready for merge yet, but put up as a placeholder.
=> wreck: small fix for jobs with more nodes in R lite than tasks

src/bindings/lua/wreck.lua, src/cmd/flux-wreck, t/Makefile.am, t/t2000-wreck-env.t
I was thinking that perhaps reducing content in per-job environment `lwj.x.y.ID.environ` might reduce the size of content store with many jobs. Turns out in most cases of submitting a long series of jobs, the environment in the KVS is identical and squashed by the content-store, but I thought I'd push up the work I did  in support of better integration of the "global" job environment `lwj.environ`, which might be useful if each job has a slightly different environment, or just for better control of the environment.
This PR adds support to wreckrun/submit to first check `lwj.environ` table by default and only submit any different variables as the per job environment. A set of utility commands `flux wreck setenv,getenv,unsetenv` are provided to set and manipulate this global environment. A …
=> wreck: better integration of global lwj.environ environment for wreck jobs

src/common/libjsc/jstatctl.c, src/modules/wreck/job.c, src/modules/wreck/wrexecd.c
=> jsc,job,wreck: change key from `lwj` to `jobid` for consistency

src/bindings/lua/flux-lua.c, src/bindings/python/flux/kz.py, src/common/libkz/kz.c, src/common/libkz/kz.h, src/modules/wreck/wrexecd.c, t/kz/kzutil.c, t/t1104-kz.t
Here are some changes libkz to defer the `kz_ready_f` callback until data is actually available, so it doesn't have to be fetched with a synchronous RPC from the callback.  I hope this will solve the excessive re-queue calls noted in #1406.
There is some other unrelated cleanup too - just what I needed to fix up to keep my sanity in this old code.
@grondo if you have a chance to look at the changes in the lua bindings and wrexecd I'd appreciate it.  The goal there was to avoid looping on `kz_get()` in the user callback since only the first call will be non-blocking.
=> libkz: avoid blocking RPCs in reactor callbacks

doc/man3/flux_kvs_lookup.adoc, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_lookup.h, src/common/libkvs/test/kvs_lookup.c
When writing code that uses `flux_kvs_lookup()` with continuations, it's useful to be able to access the original key from within the continuation, so the continuation can be shared for multiple lookups  This PR adds an accessor for the key.
Tests and docs updated.
=> kvs: add flux_kvs_lookup_get_key()

src/bindings/lua/flux/Subcommander.lua, src/bindings/lua/wreck.lua
Very minor fix to flux-wreck `ls` `timing` etc. for confusing error message from when there are no jobs in the kvs yet (#1416). Also fixed a typo causing `flux-wreck` error messages to include the full path to the script instead of a short name.
I didn't have time to go through `flux-wreck` script and fix other cases where `strerror (errno)` is attempted to be passed off as a helpful error. Sorry.
=> wreck: minor improvements to flux-wreck util

src/modules/kvs/kvs.c, src/modules/kvs/kvs_util.c, src/modules/kvs/kvs_util.h, src/modules/kvs/kvstxn.c, src/modules/kvs/lookup.c, src/modules/kvs/test/kvs_util.c, src/modules/kvs/test/kvstxn.c, src/modules/kvs/test/lookup.c, t/t1004-kvs-namespace.t, t/t1005-kvs-security.t
This is the first half of the big patches to support namespace prefixes in issue #1341.
The first patches in this series are to support parsing of namespace prefixes.  Then the support is added into the internal lookup and kvstxn APIs.  Then finally some unit tests are added.
Note that I know I did not add documentation for namespace prefixes.  I will do that later on as #1341 is completed.
=> kvs: Support namespace prefix in key passed in by user

configure.ac, doc/man1/flux-wreck.adoc, etc/Makefile.am, etc/rc1.d/01-enclosing-instance, src/cmd/flux-wreck, src/modules/wreck/wrexecd.c, t/t2003-recurse.t
This PR is an attempt to address #1422 by writing an instance's rank 0 FLUX_URI and a derived ssh:// URI to `lwj.X.X.X.flux.local-uri` and `lwj.X.X.X.flux.remote-uri` in the enclosing instance.
I need to provide a test but thought I'd post early to get any feedback from @trws.
=> store rank 0 instance URIs in enclosing instance KVS

src/modules/kvs/lookup.c, src/modules/kvs/test/lookup.c, t/t1005-kvs-security.t
Fixes issue #1401, where on replays namespaces were always checked for validity even if user originally passed in at reference.
At unit tests appropriately.
=> kvs: don't check namespace if user passes in at reference

src/cmd/flux-wreck, t/t2000-wreck.t
This is an experimental PR. Please don't merge yet.
Add support for exclusion and inclusion by node name.
Only supported when the scheduler is loaded.
This is required to test out the new experimental feature added in sched: #PR [305](https://github.com/flux-framework/flux-sched/pull/305)
=> wreck: Add support for node exclusion and inclusion

src/modules/kvs/kvs.c, t/t1005-kvs-security.t
Per discussion in #1433.
In addition, tweak some unit tests so they do not generate some confusing log messages.
=> kvs: Remove unnecessary/superfluous log messages

src/cmd/flux-kvs.c, src/common/libkvs/kvs_dir.c, t/t1000-kvs.t, t/t1004-kvs-namespace.t
With the dir and ls commands in flux-kvs, if a user specifies a
namespace prefix without a key, assume the user desires the root
(i.e. ".") directory within that namespace.
Update/adjust unit tests appropriately.
Fixes #1434
=> cmd/flux-kvs: Update dir and ls usage

src/cmd/flux-kvs.c, t/t1000-kvs.t
Fix output corner case where empty directories were not
output with dir -R.
Add unit test coverage.
Fixes #1449
=> cmd/flux-kvs: Fix dir -R corner case

src/bindings/lua/flux-lua.c, src/bindings/lua/wreck.lua, src/bindings/lua/wreck/io.lua, src/cmd/flux-wreck, src/cmd/flux-wreckrun, src/common/libkz/kz.c, src/common/libkz/kz.h, src/modules/aggregator/aggregator.c, src/modules/wreck/job.c, src/modules/wreck/lua.d/output.lua, src/modules/wreck/wrexecd.c, t/kz/kzcopy.c, t/t1104-kz.t, t/t2000-wreck.t
Here's a collection of small fixes related to the splash use case for consideration.
This PR includes:
* General reduction in logging including removal of unnecessary log messages, reduction of some "info" level log messaages to debug, and fix for #1439 to log only from rank 0 instead of all ranks
* Fix for crash in `flux-wreck status` when `exit_status` is not in kvs yet (#1437)
* Increase NOFILE_LIMIT in wrexecd (#1441)
* Error checking during task setup in wrexecd (#1441)
* Add line buffering to output files with `flux submit/wreckrun -O file`
* Check for errors from kz stream in output.lua and log errors  (#1427)
* Terminate io "flush" loop early on encountering any error from `f:reactor ("once")` 
* New command `flux-wreck dumplog ID` to dump the "logstream" error log for a job
* Add …
=> Collection of small fixes for splash project

src/common/libkvs/kvs_commit.c, src/modules/kvs/kvs.c, src/modules/kvs/test/treq.c, src/modules/kvs/treq.c, src/modules/kvs/treq.h
As discussed in #1446, do not generate a uuid for commit transactions, which is expensive.  Instead, use a fixed algorithm to generate a name for each transaction, using the rank and sequence number incremented on each rank.
The commit RPC no longer needs to include the "name" field anymore as a result.  As the name can be generated within the kvs module.
=> kvs: do not generate uuid for commit transactions, use fixed algorithm for 'name'

src/broker/broker.c, src/broker/overlay.c, src/common/libjsc/jstatctl.c, src/common/libjsc/jstatctl.h, src/modules/resource-hwloc/resource.c
This PR contains a couple of items from @trws's #1396 [WIP] Splash PR, and a broker error handling tweak resulting from #1451.
=> Colllection of small fixes for splash project (part 2)

.gitignore, doc/man1/flux-broker.adoc, src/broker/broker.c, src/cmd/flux-start.c, t/fluxometer.lua, t/sharness.d/flux-sharness.sh, t/t0001-basic.t, t/t2000-wreck.t
This is a set of minor fixes for a couple broken sharness tests, a fix for the generation of the broker.log from `test_under_flux` and a small addition to `.gitignore`
=> fixes for broken tests, addition to gitignore

src/modules/kvs/kvs.c, src/modules/kvs/test/kvstxn.c, t/t1004-kvs-namespace.t
Add a few unit tests based on #1463 discussion.
Remove a log message per #1462.
=> kvs: couple of minor fixes

src/broker/broker.c, src/modules/wreck/Makefile.am, src/modules/wreck/job.c, src/modules/wreck/test/wreck_job.c, src/modules/wreck/wreck_job.c, src/modules/wreck/wreck_job.h
This is a hopefully somewhat better structured version of PR #1471.
This one doesn't add a hash of active jobs and doesn't limt the job module's ability to ingest jobs on ranks other than 0.
It adds a `struct wjob` data structure (with unit tests), and reworks the `job.submit`, `job.create`, and `wrexecd.run` request handlers to manipulate the KVS etc using continuations  rather than synchronous RPC's, to improve job module responsiveness.
It also satisfies a long standing feature request for an ability to synchronously publish events; that is, get a response indicating that the event has received a sequence number, as discussed in #337 and #342.  That was necessary to remove the final synchronous step in job.create and job.submit, where the handlers block listening for an event to be …
=> wreck: rework job.submit, job.create, wrexecd.run handlers with continuations

src/common/libsubprocess/zio.c, src/common/libsubprocess/zio.h
A number of comments were out of date, leading to some confusion
of how zio worked.
=> libsubprocess/zio: Update comments

src/common/libjsc/jstatctl.c
The job submission flux event that was being unpacked in
`get_submit_jcb` had a missing "s:i" parameter.  Without this
parameter, the walltime of all jobs was staying at 0.
Fixes the errors that manifested in the easy backfilling testcase failure
seen in flux-sched/pull/313
=> jsc: add missing "s:i" parameter to event unpack in `get_submit_jcb`

src/modules/kvs/kvs.c
Problem: valgrind test fails when private KVS namespace
is made part of job setup.
Looks like some memory allocated in namespace_create()
that was freed in the error path, was not freed in
the non-error path.  Fix that.
Fixes #1483
=> modules/kvs: fix memory leak in namespace_create()

src/cmd/flux-jstat.c, src/common/libjsc/README.md, src/common/libjsc/jstatctl.c, src/common/libjsc/jstatctl.h, t/t2001-jsc.t
This PR supports the `R_lite` writer PR which I will post soon to flux-sched.
Also add some minor fixes along the way:
- Fix encoding errors for RDL query and update within JSC (https://github.com/flux-framework/flux-sched/issues/312#issuecomment-384064662)
- Remove trailing whitespace in `flux-jstat` command.
- Adjust an RDL test needed for the encoding fix.
Add a very simple `R_lite` test to a JSC test.
=> Extend JSC to add R_lite support

doc/man3/Makefile.am, doc/man3/flux_event_decode.adoc, src/common/libflux/event.c, src/common/libflux/event.h, src/common/libflux/test/event.c
This PR fills in some gaps noted in #1474, adding:
Functions for encoding/decoding events with raw payloads:
```c
/* Encode an event message with optional raw payload.
*/
flux_msg_t *flux_event_encode_raw (const char *topic,
const void *data, int len);
/* Decode an event message, with optional raw payload.
* If topic is non-NULL, assign the event topic string.
* Data and len must be non-NULL and will be assigned the payload and length.
* If there is no payload, they will be assigned NULL and zero.
* Returns 0 on success, or -1 on failure with errno set.
*/
int flux_event_decode_raw (const flux_msg_t *msg, const char **topic,
const void **data, int *len);
```
Functions for encoding and sending events in one go:
```c
/* Send an event message with no confirmation of acceptance by broker.
* …
```
=> libflux: add flux_event_encode_raw(), flux_event_decode_raw()

src/bindings/lua/wreck.lua, src/cmd/flux-wreck, src/modules/wreck/job.c, src/modules/wreck/test/wreck_job.c, src/modules/wreck/wreck_job.c, src/modules/wreck/wreck_job.h, t/t2000-wreck.t
This PR adds a bit of code to the job module to track active jobs.
It listens for all job state transitions, enters jobs into a hash when they first appear, and removes them when the terminal "complete" or "failed" states are reached.  The hash exists on all ranks.
There's a simple `job.list` request that returns a sorted array of jobs including id, kvs_path, and state, e.g.
```json
[
{"jobid":1, "kvs_path":"lwj.0.0.1", "state":"running"},
{"jobid":2, "kvs_path":"lwj.0.0.2", "state":"starting"},
{"jobid":3, "kvs_path":"lwj.0.0.3", "state":"submitted"}
]
```
Next step is to add an option to `flux wreck ls` to show only active jobs.  The addition of that command would address #1456.
=> wreck: track active jobs

src/cmd/flux-wreckrun, src/modules/wreck/job.c, t/Makefile.am, t/scripts/event-trace.lua, t/t2000-wreck-dummy-sched.t, t/wreck/sched-dummy.c
This fixes #1491 by caching  the `struct wreck_job` created in `job.create` in the `active_jobs` hash, so it can be fetched and reused in `job.submit-nocreate`. The `job.submit-nocreate` rpc now only requires the `jobid` member be sent along in the payload.
In order to test the `submit` and `submit-nocreate` handlers better, a dummy sched module is built for the testsuite under `wreck/sched-dummy.la` and is used by a new test `t2000-wreck-dummy-sched.t` to test that the `submitted` events for `job.submit` and `job.submit-nocreate` are properly formed.
=> wreck: fix event payload and memory leak in job.submit-nocreate

src/common/libjsc/jstatctl.c
Fix a few minor leaks in jstatctl.c found when running valgrind
with flux-sched sched module loaded:
* ` get_reserve_jcb` and `get_submit_jcb`: free result of xasprintf()
* `freectx`: add missing free() for `ctx`
=> libjsc: fix leaks detected by valgrind

configure.ac, doc/man3/Makefile.am, doc/man3/idset_create.adoc, doc/test/spell.en.pws, etc/Makefile.am, etc/flux-idset.pc.in, src/common/Makefile.am, src/common/libflux-idset.map, src/common/libidset/Makefile.am, src/common/libidset/idset.c, src/common/libidset/idset.h, src/common/libidset/test/idset.c
As discussed in #1496, this adds a new library that contains a minimal subset of the libutil/nodeset class, cleaned up and reworked for public consumption.
@dongahn, you might give this a try in flux-framework/flux-sched#330, e.g.
```c
#include <flux/idset.h>
struct idset *idset = idset_decode (s_in);
if (!idset)
// handle error
char *s_out = idset_encode (idset, IDSET_FLAG_RANGE);
if (!s_out)
// handle error
// do something with s_out, a range-compressed version of s_in
free (s_out);
idset_destroy (idset);
```
=> libidset: public lib for numerically sorted, non-negative integer sets

doc/man3/tmrpc_then.c, doc/man3/treduce.c, src/cmd/cmdhelp.c, src/cmd/flux-comms.c, src/cmd/flux-jstat.c, src/cmd/flux.c, src/common/libflux/test/module.c, src/common/libjsc/jstatctl.c, src/common/libsubprocess/subprocess.c, src/common/libsubprocess/test/loop.c, src/common/libsubprocess/test/socketpair.c, src/common/libsubprocess/test/subprocess.c, src/common/libsubprocess/test/zio.c, src/common/libutil/tstat.c, t/request/req.c, t/request/treq.c, t/rpc/mrpc.c, t/rpc/rpc.c
This PR converts a number of residual users of json-c over to jansson.  This is mostly the small stuff.
I skipped wreck/job.c because I think @grondo has already fixed that one offline.
The remaining areas in flux-core that still use json-c are:
* ./src/modules/wreck/wrexecd.c
* ./src/modules/aggregator/aggregator.c
* ./src/common/libjsc/jstatctl.c
* ./src/bindings/lua/flux-lua.c
* ./src/bindings/lua/json-lua.c
=> [cleanup] partial migration from json-c to jansson

doc/man1/Makefile.am, doc/man1/flux-hostlist.adoc, doc/test/spell.en.pws, etc/Makefile.am, etc/rc1.d/02-hostlist, src/broker/broker.c, src/cmd/Makefile.am, src/cmd/flux-hostlist, src/cmd/flux-wreckrun, t/Makefile.am, t/t2009-hostlist.t
This is somewhat experimental, but I'm posting for feedback on the general appraoch. This PR adds a simple `flux hostlist` command that prints the list of hostnames, one per line in rank order, for the instance.
If an optional `jobid` is provided, it will print the list of hostnames for that job (again one per node, *not* per task).
The script will look for `resource.hosts` and, if set, will assume this is the list of hostnames for the instance (one per rank). `resource.hosts` is kept in "hostlist" format.
If `resource.hosts` is not set, `flux hostlist` will fall back to `flux exec hostname`
For jobs, `flux hostlist` will attempt to read the hostnames directly out of `R_lite` if the `node` field exists, otherwise it will just lookup the hostname from `resource.hosts` by rank.
A new `rc1` …
=> Add flux-hostlist command and initialize resource.hosts in rc1

doc/man3/Makefile.am, doc/man3/flux_content_load.adoc, doc/man3/flux_future_create.adoc, doc/man3/flux_future_get.adoc, doc/man3/flux_future_then.adoc, doc/man3/flux_kvs_commit.adoc, doc/man3/flux_rpc.adoc, doc/test/spell.en.pws, src/common/libflux/future.c, src/common/libflux/future.h, src/common/libflux/rpc.c, src/common/libflux/test/future.c, t/rpc/rpc.c
This PR adds `flux_future_reset()`, to "unfulfill" a future.
The driving use case was RPC with multiple response messages.  One can now do this:
```c
flux_future_t *f = flux_rpc (...)
do {
flux_rpc_get (f, ...);
flux_future_reset (f);
} while (condition);
flux_future_destroy (f);
```
or in a continuation, one can conditionally call either `flux_future_reset()` or `flux_future_destroy()` before returning.  If reset, the continuation will be called on the next fulfillment (RPC response, or whatever).
Added unit tests and updated man pages.  I reworked the "user" man page a bit for better readability also.
I'd say test coverage might be a little light here, so I'll see how that goes and possibly add more tests.
=> libflux: add flux_future_reset()

src/modules/wreck/job.c, t/t2000-wreck-dummy-sched.t
This is a partial fix of #1504, once flux-framework/flux-sched#334 is closed then the fix will be complete.
I had to relax the requirement for `kvspath` in the wreck.state payload in `wreck_state_cb`, since the scheduler will not easily have access to the kvs path at the time the job is cancelled. This should not be a problem since kvs_path should not be used when processing the terminal state of a job anyway.
=> wreck: ensure cancelled jobs are no longer in active job hash

doc/man1/flux-event.adoc, doc/man3/Makefile.am, doc/man3/flux_event_publish.adoc, doc/test/spell.en.pws, src/broker/Makefile.am, src/broker/broker.c, src/broker/publisher.c, src/broker/publisher.h, src/cmd/flux-event.c, src/common/libflux/event.c, src/common/libflux/event.h, src/common/libflux/message.c, src/common/libflux/message.h, src/common/libflux/test/message.c, src/modules/wreck/job.c, t/lua/t0003-events.t, t/t0004-event.t
This PR adds functions for "synchronous" event publication.  That is, they encapsulate an event in a request message and send it as an RPC to a broker service that assigns a sequence number to it,  then responds to the RPC in parallel with the event propagation.
This was added in a more ad-hoc way recently, with the `cmb.pub` broker service.  That is replaced here  with a more elaborate `event.pub` service that breaks event publishing out from broker.c to  `publisher.[ch]`.  The new implementation adds a couple of missing features, like raw payloads and privacy flag.
The following missing API functions were added:
```c
/* Publish an event.
* The future is fulfilled once the event has been assigned a sequence number,
* and does not indicate that the event has yet reached all subscribers. …
```
=> libflux: add flux_event_publish() interface

src/bindings/lua/wreck.lua, src/cmd/flux-wreckrun, src/common/libjsc/jstatctl.c, src/common/libjsc/jstatctl.h, src/modules/wreck/Makefile.am, src/modules/wreck/lua.d/epilog.lua, src/modules/wreck/wrexecd.c, t/Makefile.am, t/t2000-wreck-epilog.t, t/t2000-wreck.t, t/t2001-jsc.t
This is an experimental PR to address the request for job epilogs detailed in #1497.
Instead of choosing either an epilog that runs before the job is "complete" or after, this PR adds both, an `epilog.pre` that runs during a new "completing" state, and an `epilog.post` that runs after the job is "complete" (and thus resources have been returned to the system).
`flux-wreckrun` will now exit on `completing` state, since it doesn't need to wait for the epilog.pre to finish, but keeping the job in "completing" state is meant to hold resources during epilog execution. There is no concept of partial release of resources in wreck, so the job doesn't hit "complete" state until *all* epilog.pre scripts have finished.
As with the wreck job environment, `epilog.pre` and `post` may be set globally in …
=> wreck: add support for job epilogs

src/cmd/flux.c, src/common/libflux/Makefile.am, src/common/libflux/conf.c
Instead of comparing `/proc/self/exe` to `$prefix/bin`, compare to `${abs_top_builddir}/src/cmd}`.
This may help when running flux under spindle, where the installed flux executable is relocated from its installed path.
The problem is discussed in #1514.
=> commands: relax run-from-build-tree detection

src/common/libidset/idset.c, src/common/libidset/idset.h, src/common/libidset/test/idset.c
This was the beginning of a larger PR to migrate the remainder of `libutil/nodeset` functionality to a public API `libidset`.  Recall this was started in #1498 but the bulk of the work deferred.
After a discussion of priorities wtih @grondo this morning, I decided to work on something else, but this groundwork actually can stand alone as cleanup, so I thought I'd go ahead and submit it as its own PR.
=> libidset: internal cleanup

src/cmd/flux-aggregate, src/modules/aggregator/aggregator.c
Minor update to the aggregator module to convert to jansson. No other cleanup was attempted at this time (except to use pack/unpack where appropriate)
Still need to do a little more testing here, but wanted to go ahead and post the PR.
=> modules/aggregator: convert to jansson

src/common/libpmi/simple_server.h, src/modules/wreck/wrexecd.c
Per discussion in #1523, fix corner case if data is buffered and not sent immediately.
Also fix a tiny documentation miss.
=> wreck:  flush PMI server response before closing zio

src/bindings/lua/wreck.lua, src/modules/wreck/wrexecd.c, t/t2001-jsc.t
The main intent of this PR is a quick conversion of `wrexecd` to jansson.
Along the way, the unused per-task `procdesc` information was removed. If we need similar functionality in the future we can implement something more scalably. The `pdesc` JSC tests were removed, but the code from jstatctl.c isn't touched since I know @garlick is working in there.
This was quick work, so could use a good review.
=> wreck: convert wrexecd to jansson

Makefile.am, README.md, codecov.yml
This PR removes json-c references in `README.md` and codecov.io and check-code-coverage ignore lists.
While I was in there, I quickly simplified and updated the `README.md` to modernize it. I probably didn't do a complete job, but didn't want to spend too much time on it presently. If someone else wants to make another/alternate pass, that would be fine with me.
=> Remove last references to json-c, simplify/update README.md

src/common/libflux/flog.c, src/common/libutil/stdlog.c, src/common/libutil/stdlog.h, src/common/libutil/test/stdlog.c, t/t0009-dmesg.t
This PR sanitizes log messages that have trailing newlines or contain multiple lines.  Any trailing CR or LF characters are stripped, and multiple lines are split into separate log messages.
=> libflux/flog: sanitize log messages containing line breaks

src/bindings/python/flux/kz.py
This PR contains one commit that fixes some issues in KZ Python binding.
I worked with @twrs to fix these issues so this is credited to him.
Fix two errors that prevented us from using Python kz binding
for @koning's testing.
- A Python handle temporary object was garbaged collected
before being passed to C kz function.
- One of the variable was set to False when it should be set
to None.
Resolve #1536.
=> python: Fix kz python binding errors

src/cmd/flux-aggregate, src/modules/aggregator/aggregator.c, t/t2100-aggregate.t
This is overall a fairly minor improvement to the aggregator module.
First the remaining synchronous RPCs were removed. Then the `int64_t` "value" (the target of the aggregate) was replaced with a generic `json_t` value. This allows identical values to be aggregated other than just integers, including floating-point, strings, and even JSON objects. As long as `json_equal()` returns true between two values, they will be coalesced by integer identifier.
The "summary statistics" (min, max) are generalized into a summary object, however this is (currently) only supported for real and integer values.
=> aggregator: remove synchronous RPCs and extend to generic values

src/common/libflux/Makefile.am, src/common/libflux/buffer.c, src/common/libflux/buffer.h, src/common/libflux/buffer_private.h, src/common/libflux/ev_buffer_read.c, src/common/libflux/ev_buffer_read.h, src/common/libflux/ev_buffer_write.c, src/common/libflux/ev_buffer_write.h, src/common/libflux/flux.h, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libflux/test/buffer.c, src/common/libflux/test/reactor.c
Initial flux buffer + read/write buffer reactor implementation for #1052.  Not ready for commiting, but wanted to get initial comments.
=> Flux buffer w/ initial buffer reactors

doc/man1/flux-start.adoc, doc/test/spell.en.pws, src/cmd/flux-start.c, t/sharness.d/flux-sharness.sh, t/t0001-basic.t
This is an experimental PR that adds a `--wrap` option to `flux-start` that wraps `flux-broker` execution in arbitrary arguments. Posting here for any comments. If we move forward with this, I'd just need to add some tests and cleanup a bit.
The main use case for `--wrap` is to run valgrind on flux brokers in a test session without all the `--trace-children=yes --trace-children-skip=pattern` shenanigans.
e.g.
```console
t$ src/cmd/flux start -s4 -vX --wrap=libtool,--mode=execute,valgrind,--leak-check=full,--suppressions=t/valgrind/valgrind.supp flux getattr rank
flux-start: warning: setting --bootstrap=selfpmi due to --size option
flux-start: 0: libtool --mode=execute valgrind --leak-check=full --suppressions=t/valgrind/valgrind.supp /g/g0/grondo/git/flux-core.git/src/broker/flux-broker …
```
=> Experimental: add --wrap=arg0,arg1,... option to flux-start

src/common/libflux/buffer.c, src/common/libflux/buffer.h, src/common/libflux/test/buffer.c
As discussed in #1546 and #1547, this adds a "drain" flag that indicates users are allowed to finish reading everything in the buffer, but can no longer write to it.  It should be useful in #1547 to indicate to users that a buffer is closed and no longer available for writing.
Note that I decided to use the word "drain" for this setting.  It's the best word I could come up with given the usage.  Terms like "close" or "complete" didn't seem quite right.  Open to suggestions of a different word.
Also, the errno I chose to return when a user attempts to write to the buffer when drain is set, is EROFS, i.e. read only file system.  Not the most perfect errno, but I couldn't think of a better one.
=> common/libflux: Add buffer readonly setting

src/common/libflux/ev_buffer_write.c, src/common/libflux/ev_buffer_write.h, src/common/libflux/reactor.c, src/common/libflux/reactor.h, src/common/libflux/test/reactor.c, t/Makefile.am, t/reactor/reactorcat.c, t/t0001-basic.t
As discussed in #1546, add a simple method for scheduling a call to `close(2)` once buffer has been emptied for flux buffer write watchers. This is basically the simplest approach for now while we continue to discuss alternatives.
Also added is the `reactorcat` test case, which implements something like `cat(1)` with the Flux reactor and buffer watchers.
Still need to add unit tests and a sharness test driver for `reactorcat`.
Fixes #1546
=> libflux: add flux_buffer_write_watcher_close()

src/common/libsubprocess/subprocess.c, src/common/libsubprocess/test/subprocess.c
Just a few comment typos I ran across
=> common/libsubprocess: Fix comment typos

doc/man3/Makefile.am, doc/man3/flux_future_and_then.adoc, doc/man3/flux_future_wait_all_create.adoc, src/common/libflux/Makefile.am, src/common/libflux/composite_future.c, src/common/libflux/future.c, src/common/libflux/future.h, src/common/libflux/test/composite_future.c, src/common/libflux/test/future.c
As described in #1550, this PR adds a first stab at support for composable `flux_future_t` to the API. The testing here so far is minimal, I wanted to make sure the interface was ok before proceeding further.
This doesn't go as far as the proposal in #1550 -- instead of turning `flux_future_t` into a composite type, it extends the interface with two composite containers (which are also of type `flux_future_t`), "wait all" and "wait any", which are created with specific constructors:
```C
flux_future_t *flux_future_wait_all_create (void);
flux_future_t *flux_future_wait_any_create (void);
```
The constructors "extend" the base type by adding composite specific data to the `flux_future_t` `aux` hash. The "type" is checked simply by ensuring the `flux::composite` entry exists. The current …
=> libflux: extend flux_future_t with composite types

src/modules/resource-hwloc/resource.c
This PR makes IO hierarchy visible to the scheduler. The sched-side change is in https://github.com/flux-framework/flux-sched/pull/354.
Because this will generally increase the overhead of resource-hwloc module, I can wrap this with an option if desired. Let me know if that's the case.
=> resource: Add IO_DEVICES to pick up GPUs through hwloc

src/common/libpmi/pmi.c
Problem: The logic that dlopens libpmix.so, expecting to
find PMI-1 symbols there if PMIX_SERVER_URI is set in
the environment no longer works since PMI-1 symbols
were moved to a separate compatibility library.
On the LSF/jsrun based IBM system where PMIX is the native
PMI, we have requested that IBM supply the libpmi.so compatability
library.  Once they do, flux should be able to find it in the
usual way.
Meanwhile delete the PMIX heuristic.
Fixes #918
=> libpmi: drop PMIX heuristic

src/bindings/lua/wreck.lua, src/modules/wreck/wrexecd.c
Add support for optionally giving a hint about the MPI type being used in a job with an `-o mpi=TYPE` option.
Also adds a method for wreck/lua plugins to check for options set with `-o` via `wreck:getopt()`, e.g. an MPI Lua plugin could be optionally enabled by adding something like
```lua
if wreck:getopt ("mpi") ~= "spectrum" then return end
```
to the top of the file.
Still need to add at least one sanity test, but opening the PR early to ensure the general approach is acceptable.
=> wreck: support `-o mpi=TYPE`

configure.ac, src/broker/boot_config.c
This PR fixes two issues that came up during initial system instance testing on the `upgrade` cluster.
=> system instance: fix default socket path, config file parsing

src/cmd/flux-wreck
Support for [sched/issue337](https://github.com/flux-framework/flux-sched/issues/337). 
Add `flux wreck sched-params set/get` options to support getting/setting runtime parameters in sched. `flux wreck sched-params get`, `flux wreck sched-params get queue-depth`, and `flux-wreck sched-params get queue-depth,delay-sched' should all work.
=> wreck: add support to set/get scheduler parameters at runtime

.travis.yml, config/x_ac_pmix.m4, configure.ac, src/broker/Makefile.am, src/cmd/Makefile.am, src/common/Makefile.am, src/common/libpmi/Makefile.am, src/common/libpmi/pmi.c, src/common/libpmi/pmi_operations.h, src/common/libpmi/pmix_client.c, src/common/libpmi/pmix_client.h, src/common/libpmi/simple_client.c, src/common/libpmi/simple_client.h, src/common/libpmi/single.c, src/common/libpmi/single.h, src/common/libpmi/test/simple.c, src/common/libpmi/test/single.c, src/common/libpmi/test/wrap.c, src/common/libpmi/wrap.c, src/common/libpmi/wrap.h, src/modules/wreck/Makefile.am, src/test/travis-dep-builder.sh
This PR adds code to Flux to enable it to bootstrap from PMIx, if built `--with-pmix`.  I used the pmix PMI-1 compat library as a guide and pulled the code into flux-core's libpmi.  The broker will use it to bootstrap if it finds PMIX_SERVER_URI or _URI2 set as discussed in #1555
This recipe works to build it on sierra:
```
$ LDFLAGS="-L/opt/ibm/spectrum_mpi/lib" \
CPPFLAGS="-I/opt/ibm/spectrum_mpi/include" \
./configure --with-pmix --disable-jobspec
$ make -j8
$ make -j8 check
```
I'm having some difficulty running _anything_ on sierra at the moment but I'll get back to it and hopefully spin up some tests on monday.  @dongahn provided some nice bsub/jsrun runes for me to cut and paste from in #1555 (thanks!)
I did notice that on my desktop, libpmix links against hwloc, and the hwloc on …
=> libpmi: add ability to bootstrap Flux using pmix

src/modules/wreck/Makefile.am, src/modules/wreck/lua.d/spectrum.lua, t/Makefile.am, t/t3001-mpi-personalities.t
Add support for spectrum MPI on Sierra via optional wreck plugin.
Activated by calling `wreckrun` or `submit` with `-o mpi=spectrum`.
Credit goes to @grondo and @garlick.
Closes #1584 
Closes #1382
=>  wreck: add wreck plugin for spectrum MPI 

src/modules/wreck/luastack.c, t/Makefile.am
Problem: The Lua stack is not reset anywhere in luastack.c when
loading and running Lua wrexecd plugins. We got away with this
when each script was run in its own lua_thread (coroutine), because
the stacks were not shared between scripts, but when the use of
coroutines was removed, the stack growth was large enough to cause
crashes in some tests that ran many tasks.
Fix the bug by resetting the Lua stack before executing a callback
function in each lua script.
Fixes #1592
=> wreck/lua: fix crash due to Lua stack overflow

src/bindings/lua/wreck.lua, src/cmd/flux-wreckrun, src/modules/wreck/Makefile.am, src/modules/wreck/lua.d/cuda_devices.lua, t/t2000-wreck.t
I thought I'd throw the current version of the CUDA_VISIBLE_DEVICES plugin into a PR.
This version also sets CUDA_DEVICE_ORDER as @dongahn instructs in #1598.
The per-task behavior can be requested with `-o gpubind=per-task` and the plugin can be disabled with `-o gpubind=off`.
Probably should figure out some way to test this in CI, but we first need a way to simulate gpu resources I guess...
=> wreck: set CUDA_VISIBLE_DEVICES when gpus are in R_lite

NEWS.md
Add a NEWS entry for v0.10.0 before tagging the release.
=> NEWS.md: udpate for flux-core v0.10.0

doc/man3/Makefile.am, doc/man3/flux_future_create.adoc, doc/man3/flux_future_get.adoc, doc/man3/flux_rpc.adoc, doc/test/spell.en.pws, src/common/libflux/composite_future.c, src/common/libflux/future.c, src/common/libflux/future.h, src/common/libflux/rpc.c, src/common/libflux/rpc.h, src/common/libflux/test/composite_future.c, src/common/libflux/test/future.c, t/rpc/rpc.c
The PR handles the issues discussed in #1589.  A summary.
- Refactor futures so that values (e.g. msgs) and errors are both valid fulfillments (or "results") of a future.
- Support the concept of a "fatal error" in futures, in which such an error takes precedence over any other results in a future.  This is set via the ```flux_future_fatal_error()``` function.  This allows  catastrophic errors to be set and reported to a user.
- Support an optional "error string" in any error fulfilled in a future.  This error string can give additional information to a user on where an error came from.  For example, if an EPROTO error occured, an error string of "client" or "server" could be set to differentiate where it occurred from.  The string can be retrieved with ```flux_future_error_string()```.
- …
=> Support queue of future fulfillments in flux futures + other structural improvements

doc/man3/flux_future_get.adoc, src/common/libflux/composite_future.c, src/common/libflux/future.c, src/common/libflux/future.h, src/common/libflux/rpc.c, src/common/libflux/test/composite_future.c, src/common/libflux/test/future.c, src/common/libkvs/kvs_watch.c, src/modules/wreck/job.c
Per #1602, replace ```void *``` parameter with ```const void **``` parameter, so code is consistent to changes done in #1144 and #1212.
I was in the area of this code in PR #1610 and just decided to fix it.  This PR follows PR #1610 and should be merged after it.
=> flux_future_get: void * -> const void **

src/modules/wreck/job.c
Simple fallthrough bug I found.  By not returning on error, the code continued on in the "good path".
=> modules/job: Fix fallthrough error case bug

configure.ac, doc/man1/flux-kvs.adoc, doc/man3/Makefile.am, doc/man3/flux_kvs_getroot.adoc, doc/man3/flux_rpc.adoc, doc/test/spell.en.pws, etc/rc1, etc/rc3, src/cmd/flux-kvs.c, src/common/libflux/rpc.c, src/common/libflux/rpc.h, src/common/libkvs/Makefile.am, src/common/libkvs/kvs.h, src/common/libkvs/kvs_getroot.c, src/common/libkvs/kvs_getroot.h, src/common/libkvs/test/kvs_getroot.c, src/modules/Makefile.am, src/modules/kvs-watch/Makefile.am, src/modules/kvs-watch/kvs-watch.c, src/modules/kvs/kvs.c, src/modules/kvs/kvstxn.c, src/modules/kvs/kvstxn.h, src/modules/kvs/test/kvsroot.c, src/modules/kvs/test/kvstxn.c, t/Makefile.am, t/rc/rc1-kvs, t/rc/rc1-wreck, t/rc/rc3-kvs, t/rc/rc3-wreck, t/t1006-kvs-getroot.t
(N.B. just realized I didn't finish reworking commit messages - please hold off on any detailed review)
This PR is a precursor to reworking the KVS watch mechanism.  It adds a new module `kvs-watch` that currently only supports "watching" the root hash of a namespace. (I thought this was complicated enough for a PR, and the generic watch could wait for another PR).
This PR adds the following API:
```c
/* Request the current KVS root hash for namespace 'ns'.
* If flags = FLUX_KVS_WATCH, a response is sent each time the root
* hash changes.  In that case, the user must call flux_future_reset()
* after consuming the response to re-arm the future for the next response.
*/
flux_future_t *flux_kvs_getroot (flux_t *h, const char *ns, int flags);
/* Decode KVS root hash response.
*
* treeobj - …
```
=> kvs: add kvs-watch module

src/broker/broker.c, src/common/libflux/buffer.c, src/common/libflux/buffer.h, src/modules/cron/task.c, t/t0005-exec.t
Minor stuff I did / found along the way for issue #1331.
=> subprocess rework - minor fixes & enhancements

.travis.yml, config/x_ac_yamlcpp.m4, configure.ac, src/cmd/Makefile.am, src/cmd/flux-job.c, src/common/Makefile.am, src/common/libjob/Makefile.am, src/common/libjob/job.c, src/common/libjob/job.h, src/common/libjob/test/job.c, src/common/libutil/fluid.c, src/common/libutil/test/fluid.c, src/modules/Makefile.am, src/modules/job-ingest/Makefile.am, src/modules/job-ingest/job-ingest.c, src/modules/job-ingest/jobspec.h, src/modules/job-ingest/jobspec_wrap.cpp, src/test/travis-dep-builder.sh, t/Makefile.am, t/rc/rc1-job, t/rc/rc3-job, t/t2200-job-ingest.t, t/t2201-job-cmd.t
This PR resurrects #1543.
The interface in job.h (under libjob) for submitting work is:
```c
typedef uint64_t flux_jobid_t;
/* Submit a job to the system.
* J should be RFC 14 jobspec signed by flux_sign_wrap(), provided
* flux was built --with-flux-security.  If not, then J should be bare jobspec.
* Currently the 'flags' parameter must be set to 0.
* The system assigns a jobid and returns it in the response.
*/
flux_future_t *flux_job_add (flux_t *h, const char *J, int flags);
/* Parse jobid from response to flux_job_add() request.
* Returns 0 on success, -1 on failure with errno set - and an extended
* error message may be available with flux_future_error_string().
*/
int flux_job_add_get_id (flux_future_t *f, flux_jobid_t *id);
```
The `flux job` command currently has two subcommands: …
=> job-ingest: add ingest module, flux job command, libjob library

src/broker/broker.c, src/broker/runlevel.c, src/cmd/flux-start.c, src/common/libflux/test/buffer.c, src/modules/cron/cron.c, src/modules/cron/entry.h, t/t0015-cron.t
Misc minor fixes peeled off of PR #1564
=> Misc cleanup & fixes

src/common/libflux/buffer.c, src/common/libflux/buffer.h, src/common/libflux/test/buffer.c
For convenience, support flux_buffer_peek_trimmed_line() and
flux_buffer_read_trimmed_line() variants, which will read lines
but strip off any trailing newline characters.
Fixes #1624
=> libflux/buffer: Add trimmed peek/read line variants

t/t2000-wreck.t
Problem:  the wreck cpu-affinity=per-task test
fails on systems with only one CPU.
The MULTICORE prereq is set if "scripts/cpus-allowed.lua
count" -gt 0.  It should be -gt 1.
Fixes #1635
=> test: fix off by one bug in t2000-wreck.t cpu-affinity=per-task test

.travis.yml, src/test/travis-dep-builder.sh, t/t2200-job-ingest.t
These are the "other fixes" for the testsuite and travis-ci taken from #1642.
=> testsuite: small set of travis-ci and test fixes

.travis.yml, src/common/libflux/test/security.c, src/common/libutil/macros.h, src/common/libutil/test/cf.c, src/common/libutil/test/cleanup.c, src/common/libutil/test/unlink.c, src/connectors/local/local.c, src/test/travis-dep-builder.sh
This PR fixes the GCC 8 warning mentioned in #1633 by sizing the `sockfile` buffer in `connector_init` to the size of the `addr.sun_path` instead of PATH_MAX+1, since Unix domain socket pathname length would seem to be constrained to the sun_path array size, not PATH_MAX.
Other GCC 8 warnings came from the use of snprintf() in tests where source and destination buffers are the same length.  Checking the return code from snprintf() for truncation suppressed these warnings as suggested by @trws.
I also tried to update the "newer" GCC in travis-ci from 4.9 to 8.1, but ran into an error linking against libjobspec, which I do not pretend to understand:
```
CXXLD    job-ingest.la
libtool: warning: '/lib64/libmunge.la' seems to be moved …
```
=> Fix GCC 8 output truncation warnings

README.md, configure.ac, doc/man1/Makefile.am, doc/man3/Makefile.am, doc/man7/Makefile.am
This adds support for an alternate asciidoc translator.  The unwritten docbook deps on a2x have been giving me heartburn on building a base docker image, this has a lot fewer deps (ruby, and... ruby AFAIK).  May want to wait for the PR with a docker-based travis conf, which will be coming shortly.
fixes #873 
Commit message with explanation below:
This allows asciidoctor to be used in place of a2x, which removes the
dependency on goodness-knows what docbook package our a2x generator
depends on that isn't in either our dependency list or theirs.  This
exists primarily because after making three versions of a docker image
trying to get one that could build the docs the other way, this works
faster, with less deps, and seemingly the same result.
=> add support for asciidoctor as manpage generator

doc/man1/flux-kvs.adoc, doc/man3/Makefile.am, doc/man3/flux_kvs_lookup.adoc, doc/man3/flux_rpc.adoc, src/cmd/flux-kvs.c, src/common/libflux/rpc.c, src/common/libflux/rpc.h, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_lookup.h, src/common/libkvs/test/kvs_lookup.c, src/modules/kvs-watch/kvs-watch.c, t/Makefile.am, t/kvs/commit_order.c, t/rpc/rpc.c, t/t1000-kvs.t, t/t1006-kvs-getroot.t, t/t1007-kvs-lookup-watch.t
This PR finishes the alternate KVS watch API, based on passing a FLUX_KVS_WATCH flag to `flux_kvs_lookup()`; and the lightweight `kvs-watch` service, which only checks watched keys when they are mentioned in a commit.   This strategy was discussed in #1556.
N.B. this PR falls short of implementing the "bulk" watch described in #1631 - this is for another PR.
In addition to the API and `kvs-watch` modifications, the `flux kvs get` subcommand now has a `--watch` and related options.
Still TODO:  doc updates and sharness test(s).
=> kvs: implement lightweight key watch and API

src/modules/cron/cron.c, src/modules/cron/entry.h, src/modules/cron/task.c, src/modules/cron/task.h
In #1564, ```modules/cron``` was converted to use the new subprocess library.   While everything works, some code seems wrong/out of place/wrong style given differences between the old and new subprocess library.  This PR cleans up / adjusts ```modules/cron``` accordingly.
=> modules/cron: misc cleanup

src/cmd/flux-start.c, src/common/subprocess/local.c, src/common/subprocess/subprocess.h, src/common/subprocess/test/subprocess.c, src/common/subprocess/test/test_echo.c, t/t0005-rexec.t
Do not append the string "_FD" to the channel environment variables
created for subprocesses.  Instead, use the channel name itself.
If the caller wishes for the environment variable to have "_FD"
at the end, they should name their channel with "_FD" at the end.
=> common/subprocess: Do not append _FD to channels

doc/man1/flux-kvs.adoc, doc/man3/Makefile.am, doc/man3/flux_kvs_eventlog_create.adoc, doc/test/spell.en.pws, src/cmd/flux-kvs.c, src/common/libkvs/Makefile.am, src/common/libkvs/kvs.h, src/common/libkvs/kvs_eventlog.c, src/common/libkvs/kvs_eventlog.h, src/common/libkvs/test/kvs_eventlog.c, t/Makefile.am, t/t1007-kvs-lookup-watch.t, t/t1008-kvs-eventlog.t
This is a small class for manipulating RFC 18 KVS eventlogs, as discussed in #1654.
@grondo's idea of keeping this decoupled from futures and KVS transactions was a great one.  This is completely standalone and can be covered well with unit tests.
I added a `flux kvs eventlog append|get` subcommand that allows events to be appended to an eventlog, and the logs to be dumped and also watched.  The get implementation illustrates how the iterators can be used with `flux_kvs_eventlog_update()` in a continuation to "consume" only the new eventlog entries.
This still needs a man page but any feedback on the API would be useful at this point.
One thing I waffled on was the static buffer typedefs for event name and context.  The RFC didn't establish any maximum field widths for this, but I assumed …
=> kvs: add RFC 18 eventlog support

configure.ac, doc/man1/Makefile.am, doc/man3/Makefile.am, doc/man7/Makefile.am
Problem: only recent version of asciidoctor handle man
page stubs properly, but if both asciidoctor and asciidoc
are installed, the former will be used.
Change config logic to prefer a2x if both are installed.
Also, simpifly the doc/man*/Makefile.am files by setting
$(ADOC) to either asciidoc or a2x, and setting
$(ADOC_FORMAT_OPT) to either --backend or --format, so that
a single command line can be used for both formatters.
Fixes #1672
=> build: prefer asciidoc (a2x) over asciidoctor

configure.ac
Problem: configure --disable-docs no longer works.
The recent change to prefer a2x over asciidoctor broke
logic for --disable-docs.  If docs are not enabled,
ADOC is unset, but the logic requires it to be
set to "not-found" to disable docs building.
Drop the default "not-found" value in AC_CHECK_PROGS(),
and check for ADOC unset.
Tested
- with a2x installed, docs enabled
- with a2x installed, docs disabled
- with nothing installed, docs enabled
Fixes #1677
=> build: fix --disable-docs logic error

src/cmd/flux.c, src/common/libutil/environment.c, t/t1102-cmddriver.t
This pulls off the cmd/flux fixes from #1670 into their own PR. These fixes were more general than just testsuite changes required for the docker environment.
=> cmd/flux: ensure selfdir always at front of PATH, and fix issue when builddir is inaccessible

.travis.yml, Makefile.am, codecov.yml, src/bindings/lua/Makefile.am, src/common/libflux/test/reactor.c, src/common/liblsd/Makefile.am, src/common/libminilzo/Makefile.am, src/common/libutil/Makefile.am, src/common/subprocess/test/test_echo.c, src/test/cppcheck.sh, src/test/docker/bionic-base/Dockerfile, src/test/docker/centos7-base/Dockerfile, src/test/docker/centos7-base/config.site, src/test/docker/docker-run-checks.sh, src/test/docker/travis/Dockerfile, src/test/travis_run.sh, t/Makefile.am, t/sharness.d/flux-sharness.sh, t/t0001-basic.t, t/t1006-kvs-getroot.t, t/t2000-wreck-epilog.t, t/valgrind/valgrind.supp
Ok, finally have a working docker integration with travis, built off @trws Dockerfiles and initial work in this area. The changes of note from Tom's work include:
- Combine gcc (default), gcc 8, and clang 6.0 into a single Ubuntu 18.04 (bionic) image (it was just easier for me to work with one "base" ubuntu image)
- Add missing deps to Dockerfiles to satisfy all tests
- Since flux-security will soon be a moving target, remove its build from the "base" image(s), install a "travis" Dockerfile that builds a specified version of flux-security and optionally installs a user matching the userid running `docker build`. This is done so that we don't have to chown the working directory, which then becomes unreadable by the testing user after the build.
- Added a …
=> travis-ci: run tests using docker

src/test/docker/docker-run-checks.sh
The main changes are for better compatibility with Mac OSX, but one of the changes is also for users that don't use `/bin/bash` as their `${SHELL}`.
Changes:
- Support BSD getopt
- Add option to skip mounting home directory: `--no-home`
- Launch interactive container with `/bin/bash` regardless of `${SHELL}`
=> Tweaks to docker build script

.travis.yml, config/tap-driver.sh, src/test/docker/docker-run-checks.sh
This is an experimental PR to quiet the output from `make check` in travis (and elsewhere).
It is experimental because it adds code to `tap-driver.sh` and I'm not sure that's a good idea.
The main change is the addition of a quiet mode for `tap-driver.sh` which suppresses output for each line of TAP, instead issuing a one-line summary for each test. This dramatically reduces the output in travis from about 11.5K lines to 5500 lines. The new output looks like:
```
shmem/backtoback.t: PASS: N=10  PASS=10  FAIL=0 SKIP=0 XPASS=0 XFAIL=0
loop/log.t: PASS: N=3   PASS=3   FAIL=0 SKIP=0 XPASS=0 XFAIL=0
loop/handle.t: PASS: N=33  PASS=33  FAIL=0 SKIP=0 XPASS=0 XFAIL=0
rpc/rpc.t: PASS: N=79  PASS=79  FAIL=0 SKIP=0 XPASS=0 XFAIL=0
loop/dispatch.t: PASS: N=53  PASS=53  FAIL=0 SKIP=0 XPASS=0 XFAIL=0 …
```
=> travis-ci: quiet tests

src/broker/content-cache.c, src/common/libkvs/treeobj.c, src/common/libutil/blobref.c, src/common/libutil/blobref.h, src/common/libutil/test/blobref.c, src/modules/content-sqlite/content-sqlite.c, src/modules/kvs/kvs.c, src/modules/kvs/kvsroot.c, src/modules/kvs/kvsroot.h, src/modules/kvs/kvstxn.c, src/modules/kvs/kvstxn.h, src/modules/kvs/test/kvstxn.c, src/modules/kvs/test/lookup.c, t/kvs/blobref.c
Per RFC7, typedefs should not point to fixed length arrays.  So remove
blobref_t typedef globally.  Adjust functions to take a char array
and an array length parameter.
Fixes #1692
=> common/libutil: Remove blobref_t type

src/modules/wreck/wreck_job.c
Per RFC7, remove typdefs that point to fixed length arrays.
Fixes #1703
=> modules/wreck: Remove hashkey_t type

src/test/docker/docker-run-checks.sh, t/Makefile.am, t/t5000-valgrind.t
As discussed in #1699, this PR adds a timeout to the t5000-valgrind.t test (2 minutes, should be plenty of time I think, but we could make it longer). Also, this PR adds the missing issues test to EXTRA_DIST, and small output fix for docker-run-checks.
=> testsuite: add timeout to valgrind test, add missing test to EXTRA_DIST

src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/test/lookup.c
With #1696 done, the 'magic' field is no longer needed in a few locations.  In addition, this fixes #1711.
=> kvs: remove 'magic' field in a few structures

doc/man3/flux_kvs_eventlog_create.adoc, src/cmd/flux-kvs.c, src/common/libkvs/kvs_eventlog.c, src/common/libkvs/kvs_eventlog.h, src/common/libkvs/test/kvs_eventlog.c
I've been sitting on this for a while, moving it around between pull requests I've been working on.  Maybe better to just submit standalone rather than keep withholding it.
=> libkvs/eventlog: drop typedefs that violate RFC 7

.travis.yml, configure.ac, src/bindings/python/_flux/Makefile.am, src/bindings/python/flux/Makefile.am, src/bindings/python/flux/security.py, src/bindings/python/make_binding.py, src/test/docker/docker-run-checks.sh, t/Makefile.am, t/python/t0009-security.py
Enables submitting signed jobspec via python 
This will be less necessary once #1715 is handled, but in the meantime, I believe it is the only way to submit jobs to flux instances configured with flux-security.
=> python: flux-security bindings

.travis.yml, configure.ac, src/broker/module.c, src/common/libflux/handle.c, src/common/libflux/module.c, src/test/docker/centos7-base/Dockerfile, src/test/travis_run.sh, t/Makefile.am, t/t0001-basic.t, t/t0010-generic-utils.t, t/t0015-cron.t, t/test-under-flux/expected.modcheck, t/test-under-flux/t_modcheck.t, t/test-under-flux/test.t
This is a collection of changes to reduce the non-determinism in the tests and to prepare for using the address sanitizer in an automated way.  Mainly meant to address #1687 and the various issues related to it.  As predicted, turning on asan produces a non-trivial number of errors, I've filed issues for all of the ones that crop up before the sharness tests start, hopefully squashing some of those will help with the sharness ones.
=> testsuite: improve test reliability and prepare for asan testing

src/modules/kvs/kvstxn.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/kvstxn.c
Includes a mem-leak found in ```kvstxn_append()```, as well as lazy not cleaning up properly fixes in tests, and several use after free errors in tests.
=> [asan] fix memory leaks and use-after-free found by address sanitizer

src/broker/test/shutdown.c, src/common/liboptparse/optparse.c, src/common/liboptparse/test/optparse.c, src/common/libpmi/clique.c, src/common/libtomlc99/test/toml.c, src/common/libutil/test/tomltk.c, src/common/libzio/test/zio.c, src/test/docker/docker-run-checks.sh
Fixes various memory leaks caught by leak sanitizer.  Most of the leaks were just in test code, but at least one was in an actual library.
This PR is on top of #1733, so that should go in first before merging this.
=> Fix memleaks caught by leak sanitizer

src/cmd/flux-job.c, src/common/Makefile.am, src/common/core.h, src/common/libjob/Makefile.am, src/common/libjob/job.c, src/common/libjob/job.h, src/common/libjob/sign_none.c, src/common/libjob/sign_none.h, src/common/libjob/test/job.c, src/common/libjob/test/sign_none.c, src/include/flux/core.h, src/modules/job-ingest/job-ingest.c, t/Makefile.am, t/ingest/job-manager-dummy.c, t/t2200-job-ingest.t
This PR solves a few problems with the `flux_job_submit()` API call and the `job-ingest` module identified in discussions and while building the `job-manager` module.
First, `flux_job_submit()` requires the user to sign jobspec before submitting it, which means the user must interact with the flux-security API.  This is extra work for little gain, since most of the time the default config file and signing method is appropriate.  In addition, flux-core can be built without flux-security, and then `flux_job_submit()` expects jobspec to be sent in the clear.  This means the user has to know how flux-core was built.
To clean this up, add a `FLUX_JOB_PRE_SIGNED` flag to indicate that jobspec is already signed when passed to `flux_job_submit()` for the uncommon case.  In the common case, this …
=> libjob and job-ingest: improve submit API and submit/queue synchronization

src/bindings/lua/kvs-lua.c, src/bindings/python/flux/core/handle.py, src/bindings/python/flux/kvs.py, src/modules/wreck/wrexecd.c
Also fix random trivial things I found along the way.
=> update python/lua KVS bindings to not use kvs classic functions

t/kvs/dtree.c, t/t1003-kvs-stress.t
Rename --mkdir to --mkdir-classic and remake --mkdir into a test that uses non-deprecated kvs classic functions.  This is simply to prepare for when ```kvs_classic``` is removed and we won't have to update this test later.
=> t/kvs/dtree: Add non-kvs classic functions mkdir test

src/modules/kvs/kvs.c, src/modules/kvs/kvstxn.c, src/modules/kvs/test/kvstxn.c, t/Makefile.am, t/issues/t1760-kvs-use-after-free.sh, t/kvs/issue1760.c
Per #1751 - add some extra tests to cover this specific behavior and add some comments to clarify how some things work.
Per #1760 - add reproducer from @garlick, add fix for use-after-free issue in kvstxn, add unit test for kvstxn.
=> kvs: add tests, comments, and use after free fix

doc/man3/flux_future_and_then.adoc, src/common/libflux/composite_future.c, src/common/libflux/future.c, src/common/libflux/future.h, t/Makefile.am, t/rpc/chained.c
Unfortunately, the composite future implementation was committed with only sanity unit tests, and as was determined by @garlick in #1750, the current code was broken for use with RPCs (and probably any other real-world usage).
The problem is that current executing context of the future on which the user may call `flux_future_then(3)` or `flux_future_wait_for(3)` was not properly propagated to all futures that may be involved in the composite. E.g. if a user composes a future from several back-to-back RPCs, then calls a blocking `flux_future_get(3)` on the composite, the `get()` will be sleeping on the "now" context reactor and associated "cloned" `flux_t` handle, but the predecessor futures will by default use the "main" `flux_t` handle, and thus those responses will be parked until …
=> libflux: fix composite future implementation

doc/man3/flux_kvs_lookup.adoc, src/cmd/flux-kvs.c, src/common/libkvs/kvs_getroot.c, src/modules/kvs-watch/kvs-watch.c, t/kvs/kvs-helper.sh, t/t1002-kvs-watch.t, t/t1004-kvs-namespace.t, t/t1005-kvs-security.t
misc fixes / cleanup while working on #1651.
- return ENOTSUP instead of ENOENT when a namespace is removed, is more consistent with other error returns.
- use ```waitfile``` script in tests, b/c I didn't know it existed when I wrote a lot of the watch tests eons ago.
- remove now unnecessary waits and buffering in tests
- remove an unnecessary flag clear
- fix some cut & paste typos
=> kvs: misc fixes & cleanup

src/broker/broker.c, src/broker/content-cache.c, src/broker/content-cache.h
This PR removes some code in the broker that attempted to set up for the content-cache to use its enclosing instance as a tertiary level of content storage.  That feature was not fully implemented, is not motivated by a use case, and creates a complication for test environments, as pointed out in #1784.
There is a corresponding PR to make this feature optional instead of mandatory in RFC 10 in flux-framework/rfc#141.
=> broker: don't connect to enclosing instance

doc/man1/flux-kvs.adoc, etc/rc3, src/cmd/flux-kvs.c, src/modules/content-sqlite/content-sqlite.c, t/Makefile.am, t/t2010-kvs-snapshot-restore.t
This PR builds on @grondo's experiment in #777, which was further discussed recently in #1754:
* If the `persist-directory` is set, save the final kvs root reference to `kvsroot.final` in that directory
* Fix a bug in `content-sqlite` that was unconditionally unlinking the sqlite db file on exit, despite obvious intentions not to elsewhere in the code
* Misc cleanup in `content-sqlite` (errno, exit on error, etc)
* Add `flux kvs put --treeobj key=- <value` capability
* Modify @grondo's sharness test to create previous root as a snapshot in current root using `flux kvs put --treeobj`
One caveat is that the shutdown timer could interrupt rc3 before the content cache is fully flushed to disk, in which case it's possible the snapshot will have dangling references.  I  would prefer to treat …
=> kvs: provide mechanism to load KVS root from completed instance in subdir of another instance

src/modules/kvs-watch/kvs-watch.c, src/modules/kvs/kvs.c, t/t1004-kvs-namespace.t
This PR follows #1812.
A bunch of fixes and refactoring.  The most major one is the refactoring of ```kvs.namespace-remove``` event into the ```kvs.namespace-remove-<namespace>``` event, so that subscribers need only subscribe to remove events for the namespaces they are concerned about.
=> kvs: cleanups & refactoring

doc/man1/flux-exec.adoc, src/cmd/builtin/proxy.c, src/cmd/flux-exec.c, src/common/libflux/reactor.c, src/common/libflux/test/reactor.c, src/common/libsubprocess/local.c, src/common/libutil/Makefile.am, src/common/libutil/fdutils.c, src/common/libutil/fdutils.h, src/common/libutil/popen2.c, src/common/libutil/test/fdutils.c, src/common/libzio/zio.c, src/connectors/local/local.c, src/connectors/ssh/ssh.c, src/modules/connector-local/local.c, src/modules/wreck/luastack.c, t/reactor/reactorcat.c, t/t0001-basic.t, t/t0004-event.t, t/t0005-exec.t, t/t0007-ping.t, t/t0011-content-cache.t, t/t0012-content-sqlite.t, t/t1001-kvs-internals.t, t/t1003-kvs-stress.t, t/t1004-kvs-namespace.t, t/t1005-kvs-security.t, t/t1101-barrier-basic.t, t/t2000-wreck.t, t/t2100-aggregate.t
This hopefully fixes #1803, a problem mainly seen with bash on Ubuntu based systems, where after running `make check`, sometimes the next commands run by the shell fail with EAGAIN.  The culprit was narrowed down to `flux-exec` and its handling of the O_NONBLOCK flag on the sometimes inherited stdin file descriptor.
First, several sharness tests that use `flux exec` are modified so that if stdin is not required, the `-n` option is used.
Then `buffer_read_watcher_create()` no longer sets O_NONBLOCK on its file descriptor.  Instead, the user must pass it in that way (or fail with EINVAL).  Various, users such as in `libsubprocess`, `flux exec`, and unit tests, are then modified to set this flag before calling the function.  Special care is taken in `flux exec` save and restore the original …
=> flux-exec: ensure stdin is restored to blocking mode on exit

.gitignore, config/ax_split_version.m4, configure.ac, src/broker/broker.c, src/cmd/builtin/version.c, src/cmd/flux-start.c, src/common/libflux/Makefile.am, src/common/libflux/test/version.c, src/common/libflux/version.c, src/common/libflux/version.h.in, t/t0010-generic-utils.t
This adds a new broker attribute `version` which reports the broker's compiled in version, e.g.
```
$ flux getattr version
0.10.0-469-g0605e1a0
```
Then it adds a  `--remote` option to `flux version` so that, in addition to reporting _its_ compiled in version, it can fetch the broker's version if desired:
```
$ flux version --remote
flux-core-0.10.0-469-g0605e1a0
```
We mused in #1810 that this might come in handy as our flux deployments get more complicated, and it was super simple to add, so here it is.
=> flux-version: show broker, library, and command version, and add API version access

configure.ac, src/cmd/flux-job.c, src/common/libjob/job.c, src/common/libjob/job.h, src/common/libjob/test/job.c, src/modules/Makefile.am, src/modules/job-manager/Makefile.am, src/modules/job-manager/active.c, src/modules/job-manager/active.h, src/modules/job-manager/job-manager.c, src/modules/job-manager/job.c, src/modules/job-manager/job.h, src/modules/job-manager/list.c, src/modules/job-manager/list.h, src/modules/job-manager/priority.c, src/modules/job-manager/priority.h, src/modules/job-manager/purge.c, src/modules/job-manager/purge.h, src/modules/job-manager/queue.c, src/modules/job-manager/queue.h, src/modules/job-manager/test/list.c, src/modules/job-manager/test/queue.c, t/Makefile.am, t/rc/rc1-job, t/rc/rc3-job, t/t2200-job-ingest.t, t/t2201-job-cmd.t, t/t2202-job-manager.t
This PR adds a `job-manager` module that handles `submit` requests from ingest module(s) and builds a queue.   It orders the queue by 1) job priority, 2) jobid.
It supports the following operations
* list - list queue (entire thing or some number from head of queue), with configurable attributes
* purge - remove a job (including all KVS vestiges) if it hasn't yet been seen by the scheduler
* priority - set priority of a job that has already been submitting (changing its queue position)
The module can be unloaded and reloaded, and it rebuilds its state.
Each operation is going to need more work once we have scheduler allocations and exec requests involved.  I tried to keep the module functionality divided up in multiple source files to make it easier to follow as we add to it.
This is …
=> add job-manager and corresponding API and flux-job subcommands

configure.ac, doc/man3/Makefile.am, doc/man3/flux_kvs_copy.adoc, doc/test/spell.en.pws, src/cmd/builtin/version.c, src/cmd/flux-kvs.c, src/common/libkvs/Makefile.am, src/common/libkvs/kvs.h, src/common/libkvs/kvs_copy.c, src/common/libkvs/kvs_copy.h, src/common/libkvs/test/kvs_copy.c, t/Makefile.am, t/t1000-kvs.t, t/t1009-kvs-copy.t
This PR adds the `flux_kvs_copy()` and `flux_kvs_move()` composite operations that were discussed in #1747.
=> kvs: add flux_kvs_copy(), flux_kvs_move()

doc/man1/flux-kvs.adoc, src/common/libutil/iterators.h, src/modules/kvs/cache.c, src/modules/kvs/cache.h, src/modules/kvs/kvs.c, src/modules/kvs/kvstxn.c, src/modules/kvs/test/cache.c, src/modules/kvs/test/kvstxn.c, src/modules/kvs/test/lookup.c, src/modules/kvs/test/waitqueue.c, src/modules/kvs/waitqueue.c, src/modules/kvs/waitqueue.h, t/t1001-kvs-internals.t
Previously, all asynchronous loads/stores in the kvs that failed would not return an error to the original kvs rpc request.  The rpc request would just hang.  Example errors are when a blobref is invalid or if the store size is larger than the maximum allowed.
The fix for this was semi involved.
- support the ability for an error callback to be registered on waiters.  On an error condition, that callback can be called on a waiter.  Ultimately, these are used so that ```set_aux_errnum()``` functions can be called, leading to replays that can be informed that an error occurred during a load/store.
- functions in the cache were added so that the error callbacks above can be called on specific cache entries and their waitqueues.
- stores were a little bit more complex to handle than loads, …
=> kvs: return errors to callers on asynchronous load/store failures

doc/man1/flux-kvs.adoc, src/cmd/flux-kvs.c, src/common/libkvs/kvs.h, src/common/libkvs/kvs_lookup.c, src/modules/kvs-watch/kvs-watch.c, t/t1007-kvs-lookup-watch.t
This implements FLUX_KVS_WATCH_PEDANTIC as discussed in #1653.
Note that I still dislike the option being called "pedantic" and am wondering what a better name is.  I originally wrote this using the word "classic", but that felt wrong, as "classic" implies the API would stay the same, which is not the case.
=> kvs: Support FLUX_KVS_WATCH_FULL

doc/man1/flux-kvs.adoc, src/cmd/flux-kvs.c, src/common/libkvs/kvs.h, src/common/libkvs/kvs_lookup.c, src/modules/kvs-watch/kvs-watch.c, t/t1007-kvs-lookup-watch.t
Per #1847.  The addition was even more trivial than I had originally suspected.
=> kvs-watch: Support FLUX_KVS_WATCH_UNIQ

src/common/libflux/future.c, src/common/libflux/test/future.c
As described in #1839, this PR improves efficiency of asynchronous use of `flux_future_t` by eliminating the `prepare` watcher and only starting the `check` and `idle` watchers at the time of fulfillment instead of immediately when `flux_future_then(3)` is called. This reduces the number of active watchers significantly when there are many unfulfilled futures associated with the reactor loop.
This PR should be carefully examined and tested to ensure I haven't missed some  subtle use case that is not covered in our testsuite. During development, I did find one case that was missed by the unit tests and luckily caught by another test in `make check`. I'll see if I can figure out what that particular use case was, and codify it in the future_t unit tests.
=> Improve efficiency of asynchronous futures

src/modules/kvs-watch/kvs-watch.c, src/modules/kvs/kvs.c, src/modules/kvs/lookup.h, t/t1007-kvs-lookup-watch.t
while working on #1838, misc cleanups and bug fixes.
=> kvs & kvs-watch: misc cleanup & bug fixes

src/modules/kvs-watch/kvs-watch.c
It occurred to me this morning that ENOTSUP handling in kvs-watch was more complicated than necessary.  It was an aha moment after dealing with the getroot removal in #1868
=> modules/kvs-watch: Fix ENOTSUP handling

src/common/libkvs/kvs_lookup.c, t/Makefile.am, t/kvs/waitcreate_cancel.c, t/t1007-kvs-lookup-watch.t
nothing too extraordinary here.  Fixes #1877
=> kvs-watch: Allow cancellation of lookups with only WAITCREATE

src/modules/kvs-watch/kvs-watch.c, t/Makefile.am, t/issues/t1876-kvs-watch-cancel-race.sh, t/kvs/issue1876.c
In #1876, a race was found in which a namespace monitor was destroyed before a continuation was called, leading to a use after free error.
@garlick, I was never able to reproduce the segfault you show in the ticket.  So I'm just assuming this use-after-free is what causes your segfault but just somehow doesn't show up for me.  If you can, double check it solves the segfault.
=> kvs-watch: Fix race condition on getroot continuation

src/cmd/flux-module.c
Increase width of size field when listing modules, to handle modules >= 10 megs in size.
Fixes #1872
=> cmd/flux-module: Increase width of size field

src/common/libkvs/kvs_watch.h
Problem: we don't want new users of the old KVS
watch API.
Add the deprecated attribute to the old functions,
and add a pointer to the new ones in the header.
Fixes #1851
=> libkvs/watch: add deprecated attr to old API

doc/man1/flux-kvs.adoc, src/cmd/flux-kvs.c
The old watch interface is being deprecated, so similarly hide
the option from flux-kvs help output and remove documentation
of it from the manpage.
Fixes #1888
=> cmd/flux-kvs: Hide watch subcommand

doc/man1/wreck-options.adoc, doc/test/spell.en.pws, src/bindings/lua/wreck.lua, src/cmd/flux-wreck, t/t2000-wreck.t
Add new `-J, --name=JOBNAME` option to `flux-wreckrun` and `flux-submit`. This option simply saves `JOBNAME` in the kvs for the job, and displays this name instead of `argv[0]` if it exists in the output of `flux wreck ls`.
=> wreck: add new -J, --name=JOBNAME option to flux-wreckrun and submit

src/bindings/python/flux/core/trampoline.py, src/modules/pymod/py_mod.c
PyLong_FromVoidPtr overflows on 32-bit architectures.
Switch to using PyLong_FromLong.
Include support for architectures where a pointer is larger than `long` (i.e., PyLong_FromLongLong).
Also includes two minor cleanups.
Fixes #1801
=> Fix pymod on 32 bit architectures

doc/man1/flux-wreckrun.adoc, doc/man1/wreck-extra-options.adoc, doc/test/spell.en.pws, etc/rc1, src/bindings/lua/wreck.lua, src/modules/wreck/lua.d/output.lua, src/modules/wreck/wrexecd.c, t/t2000-wreck-nokz.t
As discussed in #1865, add a `-o kz` option to more easily override global `nokz` setting.
Also add the option to `flux-wreckrun(1)` and `flux-submit(1)` and a simple test.
=> wreck: set nokz by default in rc1, support '-o kz' to force use of kvs for output

src/broker/broker.c, src/common/libev/ev.c, src/common/libev/ev.h, src/common/libev/ev_epoll.c, src/common/libev/ev_vars.h, t/t5000-valgrind.t, t/valgrind/valgrind.supp
This PR includes a gratuitous update of libev from 4.24 to 4.25.  I pulled it in to see if it would fix #1897 because it happened to touch the ECB_MEMORY_FENCE macros, but then left it in since the changes were fairly minor and it's probably useful to track upstream releases.  (maybe the darwin fix is useful when @trws gets back to flux mac port?)
```
4.25 Fri Dec 21 07:49:20 CET 2018
- INCOMPATIBLE CHANGE: EV_THROW was renamed to EV_NOEXCEPT
(EV_THROW sitll provided) and now uses noexcept on C++11 or newer.
- move the darwin select workaround higher in ev.c, as newer versions of
darwin managed to break their broken select even more.
- ANDROID => __ANDROID__ (reported by enh@google.com).
- disable epoll_create1 on android because it has broken header files
and google is unwilling to fix …
```
=> update to libev 4.25, ensure valgrind runs clean on i686

src/cmd/flux-wreck, src/cmd/flux-wreckrun
This PR includes a couple small fixes for wreck jobs with `nokz`.
- #1899: fix flux-wreck attach with flux-wreckrun nokz jobs that are complete
- Save output in kvs with flux-wreckrun for `nokz` jobs when `--detach` or `--wait-until` is used to avoid dropping all output.
=> wreck: small fixes for nokz job output

NEWS.md, README.md
This PR is a placeholder for release notes for 0.11.0.   I ran the script `src/test/relnotes.sh` to get merge commit messages since 0.10.0, then hand edited the output to produce the proposed change to NEWS.md.
In addition, since the dependent package names are a bit different for redhat and ubuntu, and I happened to be installing a new Ubuntu system, I turned our dependency list in the README.md into a table with columns for both OS's.
I'll push changes to the release notes as we add our final changes.
=> build: add release notes for 0.11.0, and update README.md

.travis.yml
Unfortunately, the `'style checks'` build stage broke Travis build of tags, because each stages tries to run all scripts, including `before_deploy` and `deploy`, which make no sense in this stage.
This PR is an attempt to set these targets to be ignored by in the style-checks stages. I considered making `deploy` a separate stage, but I don't think the results of one stage are available in subsequent stages, so this might have to do for now.
I'm not 100% sure this will work. I'll test on my personal repo I guess. I'll have to delete and repush the `v0.11.0` tag.
=> travis-ci: fix travis build for tags

.travis.yml
Oops, one more fallout with the switch to build stages in Travis.
The auto-deploy hook for Github release was triggered off of travis build number "1", however, now the test builds start at index 3. Sorry, I should have noticed this in my previous PR.
All along, the deploy hook should have used a custom variable, so this commit adds that to the first "real"  build.
=> travis-ci: fix github release auto-deploy

.travis.yml
I apologize, but I put the GitHub deploy into the wrong travis builder (it doesn't run make distcheck, so there was no tarball to deploy).
I've tested this now as best I could on my own branch, and I believe it should be fixed this time.
Really sorry about the extra noise!
=> travis-ci: try harder to fix deploy

src/modules/kvs/kvs.c, src/modules/kvs/kvsroot.c, src/modules/kvs/kvsroot.h, t/Makefile.am, t/kvs/setrootevents.c, t/t1001-kvs-internals.t, t/t1005-kvs-security.t
=> kvs: add read-your-writes consistency tests

autogen.sh, configure.ac
Use of `AM_MAINTAINER_MODE` (which disables so-called maintainer-mode by default) has been discouraged for awhile, See 
https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html
https://autotools.io/automake/maintainer.html
https://blogs.gnome.org/desrt/2011/09/08/am_maintainer_mode-is-not-cool/
This also explains why flux-core wasn't suffering from the same issue as flux-sched, where configure was forced be rerun after `./autogen.sh && ./configure && make` -- it is because the maintainer-mode rules were disabled by default.
Add the `enable` option to `AM_MAINTAINER_MODE` as suggested by internet fiat, and fix the issue with `aclocal.m4` by removing the lines that move it into `config/` from `autogen.sh`
=> configure: enable maintainer-mode by default

README.md, configure.ac, src/modules/job-ingest/job-ingest.c, src/test/docker/bionic-base/Dockerfile, src/test/docker/centos7-base/Dockerfile, src/test/docker/travis/Dockerfile, t/jobspec/y2j.py, t/python/t0010-job.py, t/t2200-job-ingest.t, t/t2201-job-cmd.t, t/t2202-job-manager.t
This is a #1809, updated
* to use PyYAML instead of ruamel.yaml (I _think_ this is what we decided)
* pass black formatting
* fix travis Dockerfile to restore apt/yum cache prior to installing python-yaml
Whether this is the right direction may be an open question - #1909 was opened to track that decision.
(I still might need a bit of help understanding the proper procedure for submitting a PR with new package dependencies - though this seems to have worked for getting the initial PR through travis).
=> submit jobspec as JSON

README.md, configure.ac, src/cmd/Makefile.am, src/common/libjobspec/Makefile.am, src/common/libjobspec/test/validate.cpp, src/test/docker/bionic-base/Dockerfile, src/test/docker/centos7-base/Dockerfile, src/test/docker/travis/Dockerfile, t/Makefile.am, t/jobspec/schema.json, t/jobspec/validate.py, t/t0018-jobspec.t, t/t0019-jobspec-schema.t
This PR adds a [json-schema](https://json-schema.org/) schema for jobspec and a python script for validation based [python-jsonschema](https://github.com/Julian/jsonschema).  It might form the basis for a future ingest validation plugin, as described in #1908.  The schema and test script are exercised by a new sharness test, using the test jobspec in `t/jobspec`.
Walking through the explicit checks in libjobspec, validation by this schema is is on a par with the explicit checks there, as they exist now.  I did find one check that seemed inexpressible in the schema - the test for `max < min` in the non-scalar count.  This limitation of json-schema was discussed at length in json-schema-org/json-schema-spec#51.
Other things that seemingly ought to be caught in validation, but aren't …
=> jobspec: add schema for validation

src/test/docker/README.md, src/test/docker/travis/Dockerfile, src/test/travis_run.sh
This PR removes the dependencies manually added by past PRs to `travis/Dockerfile` (I've rebuilt `fluxrm/testenv:bionic-base` and `fluxrm/testenv:centos7-base` and pushed to Docker Hub).
I've also added a `README.md` to `src/test/docker/` describing the theory behind these Dockerfiles, and the instructions for propagating new dependencies from `travis/Dockerfile` to the `fluxrm/testenv` images.
While working on this I found that MPI tests were being skipped in the CentOS builds because `mpich-3.0` rpms do not install to any default PATH (they need to be loaded with environment-modules)
=> docker: clean up travis dockerfile, add README

etc/rc1, etc/rc3, src/cmd/flux-job.c, t/Makefile.am, t/ingest/submitbench.c, t/t2200-job-ingest.t, t/t2201-job-cmd.t, t/t2202-job-manager.t
This PR moves `flux job submitbench` to a standalone, noinst test program, and replaces it with `flux job submit` a "plumbing" command that submits JSON jobspec.
Sharness tests are updated to use one of the two job submission interfaces.
In addition, sharness tests that formerly forced the "none" security mechanism when configured `--with-flux-security` no longer do that, now that munge is being started in our travis docker images.
To make it easier to work with the new `job-ingest` and `job-manager` modules, add them to rc1/rc3 so that they are automatically loaded/unloaded.
Finally, fix a bug introduced in #1913, which moved the C++ jobspec validator without updating its path in code that checks for its existence used as evidence that `job-ingest` should be expected to reject invalid …
=> Add flux job submit plumbing command, load new job modules in rc1

t/sharness.d/01-setup.sh
This fixes the problem described in #1924 by determining the real `HOME` in `01-setup.sh` and appending `site.USER_SITE` from python to `PYTHONPATH` before executing tests. This allows python to find user site installed installed modules (e.g. with `pip install --user`), even though sharness reassigns the `HOME` variable.
=> allow python under sharness to find modules installed with pip --user

t/jobspec/emit-jobspec.py, t/jobspec/minimal-schema.json, t/jobspec/validate.py, t/t0020-emit-jobspec.t
Adds a python script that emits jobspec json based on the common resource mananger CLI args: `-N` (number of nodes), `-n` (number of tasks), `-c` (cores per task), and a command.
Tests are added that validate the jobspec output against the full jobspec schema and the minimal schema that we whiteboarded.  As part of these tests, I tweaked the `validate.py` script to support reading from stdin (as well as a few other hiccups I ran into).
I have not added tests for the minimal json schema. As low hanging fruit, it would be good to feed some of the more complex jobspecs through and ensure they fail validation.  Potentially more useful would be to hand construct some simple jobspecs that still fail.
@garlick, @grondo: any other functionality that we want from `emit-jobspec.py` at this point? …
=> Jobspec emission script

doc/man1/flux-kvs.adoc, src/cmd/flux-kvs.c, src/common/libkvs/Makefile.am, src/common/libkvs/kvs_commit.c, src/common/libkvs/kvs_commit_private.h, src/common/libkvs/kvs_copy.c, src/common/libkvs/kvs_copy.h, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_lookup_private.h, src/common/libkvs/kvs_txn.c, src/common/libkvs/test/kvs_copy.c, t/t1009-kvs-copy.t
first part of issue #1860.  I've elected to make the new functions ```flux_kvs_commit_ns()``` and ```flux_kvs_lookup_ns()``` private.  The API should have more of these functions (```flux_kvs_fence_ns()```, ```flux_kvs_lookupat_ns()```, kvsdir, etc.) and tests, but I am leaving that work for another day.
=> kvs: Add src and dst namespace to kvs copy & move

t/t5000-valgrind.t, t/valgrind/valgrind-workload.sh, t/valgrind/workload.d/wreck
This PR makes 2 small improvements to the valgrind sharness test:
* Run valgrind on an instance of size=2 instead of just a single broker. Some code in Flux is only active on rank > 0, so this will help find leaks and errors in those code paths.
* The valgrind-workload.sh ignored errors from the underlying workload scripts. Log an error on non-zero exit code from any one of these scripts and cause a test failure.
This PR will fail until #1940 is addressed.
=> small valgrind test fixes

src/modules/kvs/kvstxn.c
In kvstxn_create_empty(), the 'keys' array was created that
could be overwritten without being destroyed.  This was a corner
case in PR #1859, when key generation was altered.
Fixes #1944
=> modules/kvs/kvstxn: Fix mem-leak in kvs merge

src/common/libsubprocess/Makefile.am, src/common/libsubprocess/server.c, src/common/libsubprocess/server.h, src/common/libsubprocess/subprocess.c
Fix mem-leak when subprocess server is being torn down but a local subprocess has not yet completed.
=> libsubprocess: fix mem-leak on subprocess server teardown

doc/man1/flux-kvs.adoc, doc/man3/flux_kvs_lookup.adoc, doc/man3/flux_kvs_txn_create.adoc, src/bindings/lua/flux-lua.c, src/bindings/python/flux/kvs.py, src/cmd/flux-kvs.c, src/common/libkvs/kvs_classic.c, src/common/libkvs/kvs_lookup.c, src/common/libkvs/kvs_lookup.h, src/common/libkvs/kvs_txn.c, src/common/libkvs/kvs_txn.h, src/common/libkvs/test/kvs_dir.c, src/common/libkvs/test/kvs_txn.c, src/common/libkvs/test/treeobj.c, src/common/libkvs/treeobj.c, src/common/libkvs/treeobj.h, src/modules/kvs/kvstxn.c, src/modules/kvs/lookup.c, src/modules/kvs/test/kvstxn.c, src/modules/kvs/test/lookup.c, t/t1000-kvs.t, t/t1005-kvs-security.t
This is the third part to issue #1860, implementing namespace symlink support as described by RFC change https://github.com/flux-framework/rfc/pull/147.
Basically, we're changing the treeobj of a symlink to:
```
{ "ver":1,
"type":"symlink",
"data":{"namespace":"a","target":"b.b"},
}
```
where the "namespace" field is optional.  Adjustments to all functions that relate to symlinks are done (```treeobj_create_symlink()```, ```flux_kvs_lookup_get_symlink()```, and ```flux_kvs_txn_symlink()```
are the obvious ones).  Subsequently new options to ```flux kvs link``` and ```flux kvs readlink```.
The one part of this PR I really like is how so little changed in ```modules/kvs``` and there were no changes in ```modules/kvs-watch```.  So I think this was a much better choice than the ns prefix we …
=> kvs: support symlinks with namespaces within them

src/modules/kvs-watch/kvs-watch.c
=> modules/kvs-watch: Remove left over debugging

doc/man3/flux_kvs_commit.adoc, doc/man3/flux_kvs_lookup.adoc, doc/man3/flux_kvs_set_namespace.adoc, src/cmd/flux-kvs.c, src/common/libkvs/kvs_classic.c, src/common/libkvs/kvs_lookup.c, src/modules/kvs-watch/kvs-watch.c, src/modules/kvs/kvs.c, src/modules/kvs/lookup.c, src/modules/kvs/lookup.h, src/modules/kvs/test/lookup.c, src/modules/wreck/wrexecd.c, t/Makefile.am, t/kvs/dtree.c, t/kvs/lookup_invalid.c, t/t1000-kvs.t, t/t1001-kvs-internals.t
```flux_kvs_lookupat()``` would lookup a namespace, which does not make sense given it takes a rootref.   Also, the rootref was optional and would call ```flux_kvs_lookup()``` if it was not set.  This doesn't really make sense.  So require a root reference to be passed in, don't call ```flux_kvs_lookup()```, and don't lookup a namespace.
As a side effect, don't send a namespace in the lookup RPC if an at reference is mentioned.  So in the kvs module, make it so a lookup rpc is required to specify a namespace OR a root reference, but does not require both.
Also fix up some stupid documentation and typos found along the way.
=> kvs: flux_kvs_lookupat() should not assume namespaces and always take rootref

src/common/libidset/idset.h
Problem: idset.h uses bool type without including its
definition, thus cannot be used standalone.
Include stdbool.h.
Fixes #1973
=> libidset: include stdbool.h in header

src/common/libflux/rpc.c, src/common/libflux/test/rpc.c
Add input parameter checks to flux_rpc(), flux_rpc_raw(), and
flux_rpc_vpack().  NULL handle could lead to a segfault.  Add
appropriate unit tests.
Fixes #1979
=> libflux/rpc: Add input parameter checks

doc/man1/flux-kvs.adoc, src/cmd/flux-kvs.c, t/t1000-kvs.t, t/t1001-kvs-internals.t, t/t1004-kvs-namespace.t, t/t1005-kvs-security.t, t/t1007-kvs-lookup-watch.t, t/t1009-kvs-copy.t
Convert namespace-create, namespace-remove, and namespace-list
into a general namespace subcommand with "create", "remove", and
"list" sub-sub-commands.
Fixes #1445
=> cmd/flux-kvs: Create namespace subcommand

src/cmd/builtin/hwloc.c
Problem: flux-hwloc reload occasionally segfaults.
Drop an extra flux_future_destroy() call.
Fixes #1986.
Also, drop a redundant flux_future_get() call (cleanup).
=> cmd/flux-hwloc: fix double-free

src/modules/job-ingest/schemas/jobspec.jsonschema, t/jobspec/valid/use_case_1.3.yaml, t/jobspec/valid/use_case_2.5.yaml, t/jobspec/valid/use_case_2.6.yaml
Update jobspec schema to make `min` the only required property for resource `count` specification. If any of `max`, `operator`, or `operand` are present, then all are required. (I think I got this right)
Update test input to latest examples from rfc14, which should now pass the validation tests in the testsuite.
Closes #1995
=> job-ingest: update rfc14 examples and jobspec schema to allow optional "max" property for resource counts

doc/man1/flux-exec.adoc, doc/test/spell.en.pws, src/cmd/flux-exec.c, src/common/libsubprocess/subprocess.c, src/common/libsubprocess/test/subprocess.c
Support a pdsh-ish mechanism to support forced exits on flux-exec when processes hang or are ignoring signals.  Because flux-exec sends a signal on the first ctrl+c (which pdsh doesn't), I decided for it to behave a bit differently than pdsh.  Instead, on the second ctrl+c, you get the "please ctrl+c within a second to exit" message.  So it really takes 3 ctrl+c to force exit.  I know it's a tad different, but it made sense to me.
Also fixed up a corner case where I foolishly output verbosity for each subprocess instead of for all subprocesses.
Also fixed up ```flux_subprocess_kill()``` to allow users to send signals multiple times.  I have no idea why I didn't allow this at first, it makes no sense.
=> flux-exec:  support forced exit & misc fixes

.mergify.yml, codecov.yml
Add an initial config file for mergify.io with strict merge enabled.
This config file enables the mergify bot to auto-rebase and merge
PRs once all of the following conditions are met:
- The label "merge-when-passing" is applied
- The label "work-in-progress" is not applied
- The PR title doesn't start with "[wip|WIP]" or "wip" or "WIP"
- Travis-CI checks pass
- Codecov doesn't report a drop in project coverage
- There is at least one approving review by a member of flux team
- There are no outstanding changes requested.
I have the strict mode set to "auto" instead of "true" which supposedly will only rebase one PR at a time instead of all pending PRs on a change to master.
I haven't been able to test some of the features, i.e. I'm not sure if I got the title matching right, and I …
=> mergify.yml: add config file for mergify.io

src/cmd/flux-exec.c, src/common/libsubprocess/subprocess_private.h, t/t0005-exec.t
On normal completion, output to stderr the tasks that exited with non-zero exit status.  Here's example output:
```
>flux exec -n sh -c ~/test.sh
[1,3]: Exit 1
2: Exit 2
```
and when I ctrl+c
```
>flux exec -n sh -c "sleep 10"
^C[0-3]: Exit 130
```
Also output a list of tasks that were still running when you do a force-exit (multiple ctrl+c in under a second).  Example output:
```
>flux exec -n sh -c ~/ignore_sigint.sh
^C^Cinterrupt (Ctrl+C) one more time within 1.000000 sec to exit
^C[0-3]: command still running at exit
```
and one dumb commit to remove a struct var that is no longer used.
and one dumb commit to limit the decimal places in a message output.
=> flux-exec: add two helper outputs

t/kvs/watch_disconnect.c, t/t1103-apidisconnect.t
Add several loops / waits to wait for rpcs / disconnects to be
processed, to hopefully avoid several racy scenarios.
Fixes #2015
=> t/kvs/watch_disconnect: Fix racy behavior

README.md, scripts/check-format, scripts/format, src/cmd/Makefile.am, src/cmd/flux-jobspec, t/Makefile.am, t/jobspec/summarize-minimal-jobspec.py, t/t0020-emit-jobspec.t, t/t0021-flux-jobspec.t
As promised today over coffee, here is what I have so far.  It currently supports several flags that are common amongst `sbatch` and `srun`.  Including `-N` (nodes), `-c` (cores), `-n` (tasks), `--time`, and `--output`.  I don't think there is anything else we need for Corona other than `-g` (gpus) and `--error`.
Oh, it also needs to actually do something when someone supplies `--output` (whoops, forgot that one).
Related #1929 (still needs oar support before closing it)
Closes #2003
=> flux-jobspec command

src/modules/kvs/Makefile.am, src/modules/kvs/kvs.c, src/modules/kvs/kvsroot.c, src/modules/kvs/kvsroot.h, src/modules/kvs/kvssync.c, src/modules/kvs/kvssync.h, src/modules/kvs/test/kvssync.c, t/t1004-kvs-namespace.t
The last vestige of watch in ```modules/kvs``` was the use of the "watchlist" by ```kvs.sync```.  I considered leaving the code there b/c it was still useful by ```kvs.sync```, but the implementation was inefficient.  It would continually run through the whole watchlist (err "synclist") on every setroot event.
Instead, I created a new internal lib called "kvssync", that is a very simplified version of the former "watchlist" just for ```kvs.sync```.  The "synclist" is sorted by the sequence number people are waiting on.  So everytime a setroot even occurs, you only traverse the list as far as you need to to alert syncers.
=> kvs: re-work kvs.sync

doc/man1/flux-kvs.adoc, doc/man3/Makefile.am, doc/man3/flux_kvs_commit.adoc, src/cmd/flux-kvs.c, src/common/libkvs/kvs_commit.c, src/common/libkvs/kvs_commit.h, src/common/libkvs/kvs_getroot.c, src/common/libkvs/test/kvs_commit.c, src/modules/kvs/kvs.c, t/Makefile.am, t/kvs/fence_api.c, t/t1000-kvs.t, t/t1001-kvs-internals.t
After a kvs commit/fence, have the rpc return the root reference / seq of the resulting root that has all of the changes in a transaction.  This root ref / seq can then be used for causal consistency.  Add associated library "get" functions in ```libkvs/kvs_commit```.
The more questionable part of this PR is probably all of the new options I added in ```flux-kvs```.  Now every write operation (put, mkdir, link, unlink) can output the resulting treeobj, root ref, or sequence number after the write operation has completed.  Is it too much?  If it's too much, I'd have to add tests another way.
=> kvs: commit/fence return root ref / sequence after transaction

t/kvs/transactionmerge.c
=> t/kvs: fix racy possibility in kvs/transactionmerge

src/modules/job-ingest/job-ingest.c, src/modules/job-manager/Makefile.am, src/modules/job-manager/job.c, src/modules/job-manager/job.h, src/modules/job-manager/priority.c, src/modules/job-manager/raise.c, src/modules/job-manager/restart.c, src/modules/job-manager/restart.h, src/modules/job-manager/test/restart.c, src/modules/job-manager/test/util.c, src/modules/job-manager/util.c, src/modules/job-manager/util.h, t/t2202-job-manager.t
This PR is definitely a WIP, but I wanted to get it out there for some early review if that's OK.
The job eventlog is a sort of fine grained synchronization facility for single jobs, and also a record of what has happened so far to a job sitting in the queue.  In addition, the job manager implements a "restart" capability where active jobs are pulled in from the KVS and their job manager state recreated by replaying the job's eventlog.
The first thing this PR does is ensure that full in-memory job state can be recreated from the eventlog, as the number of events increases.  The "restart" code is refactored so that replay occurs in a new constructor for a `struct job`.  Some util functions for parsing key=value attributes out of the event context were added to make this job easier.  The …
=> job-manager:  improve internal eventlog support

.travis.yml
On travis-ci the version of git(1) inside of our docker image may
be too old for the `git fetch --unshallow --tags` to succeed, as
evidenced by errors like:
git fetch --unshallow --tags
fatal: unknown value for config 'protocol.version': 2
in our travis builds. To ensure we don't hit this error, run
the command to fetch tags *before* running docker, using the version
of git installed in travis.
Fixes #2024
=> travis-ci: unshallow git repo before running docker

t/t1004-kvs-namespace.t
=> t/kvs: Fix multiple minor issues in t1004-kvs-namespace.t

doc/man3/Makefile.am, doc/man3/idset_create.adoc
Add a reference to the freshly minted RFC 22, fill in missing functions, and fix punctuation error.
=> doc: clean up idset_create(3) man page

src/bindings/python/_flux/Makefile.am, src/bindings/python/_flux/callbacks.h, src/bindings/python/flux/Makefile.am, src/bindings/python/flux/core/handle.py, src/bindings/python/flux/core/watchers.py, src/bindings/python/flux/future.py, src/bindings/python/flux/message.py, src/bindings/python/flux/rpc.py, src/bindings/python/flux/wrapper.py, src/bindings/python/make_binding.py, src/common/libkvs/kvs_txn.h, t/Makefile.am, t/python/t0001-handle.py, t/python/t0002-wrapper.py, t/python/t0012-futures.py, t/python/t1000-service-add-remove.py, t/t9001-pymod.t
Adds a `Future` class that inherits from `WrapperPimpl`, and makes `RPC` a subclass of `Future`.  `f.rpc_create()` and `f.rpc_send()` are now dropped in favor of  `f.rpc()` and `f.rpc().get()`, respectively.  The `Future` class wasn't designed to be directly instantiated, it is more of an abstract class currently.
This PR also switches the bindings over to the [new-style cffi callbacks](https://cffi.readthedocs.io/en/latest/using.html#extern-python-and-void-arguments).  They should be faster and avoid any issues with SELinux [[1]](https://cffi.readthedocs.io/en/latest/using.html#callbacks-old-style).  The unfortunate side-effect being that the default compiler on TOSS3 doesn't appreciate the auto-generated C code:
```
_core.c:2272:3: warning: missing initializer for field ‘reserved1’ of …
```
=> Python Future Support
