flux-framework/flux-core

src/broker/module.c
src/modules/api/libapi.c

Modify zloop handlers in comms module and api handle implementations so that they don't deadlock or fail in other ways if called a) after their zloop poller was cancelled or b) when the socket is no longer ready.

work around zloop gotchas in issue #135

---

.travis.yml

flux-sched depends on this version of czmq, and I believe hype/ipa are at this level also.
Fixes #198

travis: update czmq to czmq-3.0.0-rc1

---

src/modules/libmrpc/Makefile.am

added mrpc header to installation list

---

.travis.yml
src/test/Makefile.am
src/test/kap/kap_roles.c

Fix KAP tests compile on master (convert a couple calls to new API)

test/kap: convert KAP tests to new flux event api

---

src/modules/libkz/kz.c
src/modules/wreck/wrexecd.c

Fix some of the obvious memory leaks seen via runs of valgrind on current master.

memory leak fixes

---

src/broker/broker.c
src/common/libflux/flog.c
src/common/libflux/flog.h

fix flux-broker log redirection

---

src/modules/kvs/kvs.c

kvs: fix commit batching timeout math error resulting in commit hang

---

src/cmd/flux-module.c

changed 'module unload' to 'module remove'

flux-module: corrected usage message

---

etc/Makefile.inc.in
t/Makefile.am
t/build/hello.mk
t/build/hello_czmq.c
t/build/hello_flux_core.c
t/build/hello_flux_internal.c
t/build/hello_jsonc.c
t/t0006-build-basic.t

update Makefile.inc used by flux-sched after build changes

---

doc/man3/Makefile.am
src/broker/module.c
src/common/libflux/message.c

These were extracted from pr #289 per @grondo's request.

Leaks and minor build fixes

---

src/modules/libjsc/jstatctl.c

Fixes the problem reported in flux-sched [Issue 58](https://github.com/flux-framework/flux-sched/issues/58).  The fix replaces a fixed buffer that was too short to hold lwj.100.rank.0.cores with a dynamically sized buffer.  The mods also address suggestions made in the original [PR 391](https://github.com/flux-framework/flux-core/pull/391).

Jsc keylen fix fix

---

src/bindings/lua/flux-lua.c

Under at least one version of Lua 5.1 an assertion was being
triggered in lua_push_flux_handle() when under use by the lua
plugins in wrexecd. The invariant that was violated was that
the "flux" entry existed in the flux reftable, but the userdata
pointer to the real flux_t handle was invalid.
It is unclear why this was happening, but may be due to the
local/global/coroutine shenanigans used in luastack.c to
run multiple plugins against the same global state.
In this case, it is safe to recreate the flux_t userdata, so instead
of asserting here just fall through if no userdata found.

fix assertion failure in lua_push_flux_handle

---

src/modules/libjsc/README.md
src/modules/libjsc/jstatctl.c
src/modules/libjsc/jstatctl.h
t/t2001-jsc.t

I deleted the previous one and creating a new PR for this. The JSC and the tests are updated.

Walltime extensions to JSC

---

src/modules/kvs/kvs.c
src/modules/wreck/wrexecd.c

A couple of small changes to help move issue #463 along.

fix unchecked flux_fence() call, enhance KVS log message

---

src/modules/wreck/wrexecd.c

Include lwj id in "rexecd_init" fence name to make it
globally unique.  Possible fix to #463.

modules/wreck: ensure fence name is unique

---

src/modules/resource-hwloc/resource.c

This adds support to load pre-made xml files for hwloc rather than reading the configuration from the system.  For now, the main benefit of this is testing and integration with the new sched hwloc xml support, but loading from XML is also *much* faster than dynamically reading all of the information when dealing with large nodes, so it may also serve as an optimization later.  The implementation uses the existing config mechanism, and accepts either a per-rank or a default topology, which is then loaded by each rank as normal and presented just like a dynamically loaded topology.  An example config might look like this:
```
resource
hwloc
default_xml = /g/g12/scogland/projects/flux/bolt.xml
xml
2 = /g/g12/scogland/projects/flux/cab.xml
```
An easy test for correctness, the one I used and …

Hwloc import

---

src/bindings/python/flux/core/handle.py
src/bindings/python/flux/core/watchers.py
src/bindings/python/flux/json_c.py
src/bindings/python/flux/kvs.py

This pull request contains a number of support updates, python fixes and extensions to improve support for the capacitor tool as well as python applications in general.

Cap support

---

src/modules/resource-hwloc/resource.c

The reload event has been converted into an RPC so that its results can be
waited upon, and so that reloading by path can report an error to the caller
while falling back to the initial context.  If the initial context load,
during startup, fails then it still kills the application currently.
fixes #492

resource-hwloc: reload event converted to RPC

---

src/broker/attr.c
src/broker/broker.c
src/broker/content-cache.c
src/broker/module.c
src/broker/sequence.c

Some relatively minor coverity fixes, originally from pr #576.

Coverity fixes

---

src/cmd/flux-kvs.c
src/common/libflux/dispatch.c
src/common/libflux/event.c
src/common/libflux/handle.c
src/common/libflux/message.c
src/common/libflux/reduce.c
src/common/libflux/response.c
src/common/libflux/rpc.c
src/common/libutil/cleanup.c
src/modules/kvs/kvs.c
src/modules/kvs/kvs.h
src/modules/kvs/libkvs.c
src/modules/kvs/proto.c
src/modules/kvs/proto.h
src/modules/kvs/test/proto.c
src/test/soak.sh
t/t1000-kvs-basic.t

This PR includes some unremarkable memory leak fixes, and some KVS fixups to support the work in #614.

fix memory leaks + KVS behavior in a few corner cases

---

src/broker/runlevel.c
src/cmd/builtin/content.c
src/cmd/cmdhelp.c
src/cmd/flux.c
src/common/libflux/info.c
src/common/libsubprocess/zio.c
src/common/libutil/cleanup.c
src/modules/wreck/wrexecd.c

Working through some of the recently reported coverity fixes.  Not yet complete.

misc coverity fixes

---

etc/flux-core.pc.in

Removes mrpc to match commit f8163cc2d42a45e24419e981c185e922fff509e1
Fixes https://github.com/flux-framework/flux-sched/issues/171

flux-core.pc:  Remove -lflux-mrpc

---

src/modules/wreck/job.c

Removes code made obsolete by the JSC
Closes #710

wreck: remove old sim workaround code

---

doc/man7/Makefile.am

build: fix typo in man7/Makefile.am

---

NEWS.md
configure.ac
src/test/Makefile.am
src/test/relnotes.sh

This can be tweaked as we get ready to release but wanted to get it out there.

0.5.0 release notes, script for generating them, configure warning change

---

NEWS.md
src/test/relnotes.sh

0.6.0 NEWS

---

src/common/libev/ev.c
src/common/libev/ev.h
src/common/libev/ev_epoll.c
src/common/libev/ev_poll.c
src/common/libev/ev_select.c

All source files updated directly from libev source release without
modification.
Fixes #717

libev: update embedded libev to 4.24

---

doc/man1/flux-submit.adoc
doc/man1/flux-wreckrun.adoc

Update with options added since last manpage update.

Update flux-submit(1) and flux-wreckrun(1) manpages

---

src/cmd/flux-comms.c
t/Makefile.am
t/module/basic.c
t/request/req.c
t/t0001-basic.t
t/t0003-module.t

Added tests for ```flux_lspeer()```, ```flux_rmmod()```, ```flux_lsmod()```, and ```flux_insmod()```.
A couple of minor cleanups along the way.

Add some tests to increase code coverage

---

AUTHORS
NEWS.md

This is a placeholder PR to be merged once we are ready to tag 0.7.0 and people are happy with the NEWS file. If we merge a few more fixes onto master before 0.7.0 tag, it will be easy to add appropriate NEWS entries to this branch and rebase the result.
Fixes #1019

Update NEWS.md, AUTHORS for flux-core 0.7.0

---

src/modules/kvs/kvs.c

Just a few tiny cleanups I found while doing some other work.  All trivial changes.

Few miscellaneous KVS cleanups

---

src/test/soak-workload.sh

Update content dir from scratch-directory to broker.rundir.
Use flux module stats instead of flux comms-stats.
Fixes #1070

soak: Update for recent flux changes

---

src/common/libutil/ev_zmq.c

It is by happenstance that I came across this, and I noticed the typo in my name. I'm glad that my blogging has been helpful!

Typo in my name is now corrected

---

src/common/libflux/ev_flux.h
src/common/libflux/reactor.c
src/common/libflux/reactor.h

Some very simple reactor code cleanups.

Reactor cleanup

---

NEWS.md

I'm submitting the new NEWS entry for v0.9.0 as a PR so that other developers can push updates and edits directly here. Before merging we'll squash any edits.
I've already added entries for PRs #1513 and #1515

NEWS.md: update for flux-core v0.9.0

---

configure.ac
src/common/Makefile.am

This is an initial attempt at library versioning support.  A very basic one, where prior to release, the appropriate version numbers would have to be updated in configure.ac.

Add library versioning support

---

doc/man1/COPYRIGHT.adoc
doc/man3/COPYRIGHT.adoc
doc/man7/COPYRIGHT.adoc
doc/test/spell.en.pws

doh!  This update should have been in #1901

man*/COPYRIGHT.adoc: update copyright notice

---

src/common/libidset/idset.c
src/common/libidset/idset.h
src/common/libidset/test/idset.c

libidset: add idset_last()

---

src/common/libsubprocess/local.c
src/common/libsubprocess/remote.c
src/common/libsubprocess/server.c
src/common/libsubprocess/subprocess.c
src/common/libsubprocess/subprocess.h
src/common/libsubprocess/subprocess_private.h

some misc fixes I saw while working on #2008.

libsubprocess: misc fixes

---

NEWS.md

This is a rough first draft of a NEWS entry for v0.12.

NEWS.md: add news for flux-core v0.12

---

NEWS.md

Update NEWS.md for 0.13.0 tag.

NEWS.md: update release notes for 0.13.0

---

src/modules/job-info/job-info.c
src/modules/job-info/job_state.c
src/modules/job-info/job_state.h
t/t2204-job-info.t

nothing too extraordinary in this PR, it's about what you expect.  Copied a decent amount of code from `job-manager`.  Perhaps could make a convenience lib?

job-info: re-load job state from KVS

---

src/shell/Makefile.am
src/shell/builtins.c
src/shell/mpir/mpir.c
src/shell/mpir/nodelist.c
src/shell/mpir/nodelist.h
src/shell/mpir/proctable.c
src/shell/mpir/proctable.h
src/shell/mpir/ptrace.c
src/shell/mpir/rangelist.c
src/shell/mpir/rangelist.h
src/shell/mpir/test/nodelist.c
src/shell/mpir/test/proctable.c
src/shell/mpir/test/rangelist.c
src/shell/shell.c
src/shell/shell.h
t/Makefile.am
t/shell/mpir.c
t/shell/plugins/invalid-args.c
t/t2610-job-shell-mpir.t

Posting this PR early so I can more easily align with @dongahn 
This PR adds two new builtin shell plugins:
* The `ptrace` plugin adds support for starting tasks in a stopped state using `PTRACE_TRACEME` when the `-o stop-tasks-in-exec` option is provided to the shell. Once all tasks have been verified as stopped, the `shell.start` event will be emitted with `{"sync":true}` set in the context.
* The `mpir` plugin adds support for `flux-job attach` or another tool gathering `MPIR_proctable` information on demand via new shell `.proctable` service on the leader rank. Once the leader rank receives this request, it takes care of gathering the proctables from all other ranks and reducing the data before sending it back in the RPC response. In case shells have exited before they can respond …

shell: add support for debugger synchronization and MPIR_proctable gather

---

src/broker/broker.c

As discussed in #2593, file descriptor exhaustion may cause the broker to hit an assertion failure in `zuuid_new()` due to failure to open `/dev/urandom`, likely due to many API users. (The reproducer creates 1000 simultaneous `flux mini run` invocations). 
Though not a real fix, increase the number of open file descriptor limit in the broker to the current hard limit. This avoids the need for users to remember to do this by hand if their use case hits this issue.

broker: increase nofile limit to avoid assertion failure in zuuid_new()

---

src/broker/content-cache.h
src/broker/liblist.h
src/broker/pmiutil.h
src/cmd/builtin.h
src/common/libaggregate/aggregate.h
src/common/libflux/reactor.c
src/common/libidset/idset_private.h
src/common/libschedutil/schedutil_private.h
src/common/libutil/cleanup.h
src/common/libutil/mnemonic.h
src/common/libutil/unlink_recursive.h
src/modules/kvs/kvstxn.c
src/shell/mpir/rangelist.h
src/shell/rc.c
t/job-manager/bulk-state.py
t/job-manager/submit-sliding-window.py
t/job-manager/submit-wait.py
t/job-manager/submit-waitany.py
t/job-manager/wait-interrupted.py

Ran across lgtm.com which was already [scanning this project](https://lgtm.com/projects/g/flux-framework/flux-core/?mode=list), and thought I'd just go ahead and fix some of the obvious errors it caught.
Overall, it seems like lgtm catches some valid (though simple) errors, and it might be nice to turn this service on for pull requests (free for open source projects), if that is ok.

fix minor issues found by lgtm scan

---

src/common/libtomlc99/README.md
src/common/libtomlc99/test/toml.c
src/common/libtomlc99/toml.c
src/common/libtomlc99/toml.h
src/common/libtomlc99/toml_cat.c
src/common/libtomlc99/toml_json.c
t/conf.d/good-ipc2/boot.toml
t/conf.d/good-tcp4/boot.toml

Update libtomlc99 to lastest master, which updates TOML conformance from 0.4.0 to 0.5.0.
The TOML UTF-8 TODO tests are now working.

libtomlc99:  update for TOML v0.5.0  support

---

.github/workflows/main.yml
.mergify.yml
src/test/docker/docker-run-checks.sh

Same PR as #2677, but resubmitting to see if the issues with Travis-Ci not responding are fixed.

github: check flux-sched@master against submitted flux-core PRs

---

NEWS.md

Here are some proposed release notes for 0.15.

NEWS.md: add release notes for 0.15.0

---

src/cmd/flux-job.c
t/t2501-job-status.t

Fix `flux job status` for jobs that get an exception before the `start` event (e.g. unsatisfiable request, or canceled). `flux job status` only waits for the `finish` event, so currently reports any job without a finish event as exit code 0 (success). (As seen in flux-framework/flux-sched#602)

Fix flux-job status for jobs with exceptions before start

---

src/cmd/flux-jobs.py

Problem: flux-jobs requests all attribute information from the job-info list service, regardless of the information that is actually needed by the user.  As the job-info list service grows to support more
information, this can become excessive and lead to very large RPC responses.
Solution: Limit the attributes requested to only those attributes needed based on the output format input by the user.
Fixes #2637
Notes:
- was a little trickier than I had thought it would be.  Some of the format fields require multiple attributes to be returned from job-info, so I did a Python dict from field name to tuple of attributes (majority of which contain a single element).
- to my surprise Python did not appear to have a builtin `uniq()` like in Perl.  So I instead used sets to built up the "list" of …

cmd/flux-jobs: limit attributes requested

---

t/t2204-job-info.t
t/t2603-job-shell-initrc.t
t/t2608-job-shell-log.t
t/t2609-job-shell-events.t
t/t2610-job-shell-mpir.t

Just a few very minor issues I ran across while trying to reproduce hangs and intermittent test failures with the sharness testsuite.

testsuite: minor fixes and slight improvements

---

.gitignore
.travis.yml
mypy.ini
src/bindings/python/.mypy.ini
src/bindings/python/flux/future.py
src/bindings/python/flux/job.py
src/bindings/python/flux/kvs.py
src/bindings/python/flux/message.py
src/bindings/python/flux/wrapper.py
src/cmd/flux-jobspec.py
t/python/sideflux.py
t/python/t0005-kvs.py
t/python/tap/pycotap/__init__.py

This is dependent on #2805, but ended up essentially ready to go as soon as that goes forward.

Mypy: add static type checking for python to travis

---

t/t2204-job-info.t

Fix tests that could be racy.  It is possible for the job-info module
to have not yet seen the state change by the time "flux job list" is
called, so wait for that state change to be seen before continuing
in the test.
Fixes #2850

t2204-job-info: Fix racy tests

---

src/cmd/flux-job.c
src/common/libjob/test/job.c
src/common/libschedutil/hello.c
src/modules/job-info/job_state.c
src/modules/job-info/list.c
src/shell/output.c
t/ingest/submitbench.c
t/job-manager/list-jobs.c
t/job-manager/sched-dummy.c

per issue #2884  and #2885, pretty minor stuff

job-info: cleanup list attributes code and use %ju instead of %llu

---

NEWS.md

First cut at a NEWS.md entry for v0.17.0, quickly done. Will update again before tagging and as more PRs go in, but wanted to get a stake in the ground.
If people want to make an editing pass or change wording, feel free to push to this branch.
Fixes #2978

Update NEWS for v0.17.0

---

NEWS.md

First attempt at v0.18.0 release notes.  Others feel free to push to this branch!

NEWS.md: add release notes for v0.18.0

---

src/broker/pmiutil.c

If FLUX_PMI_DEBUG is set in the environment, log each PMI operation completed by the broker.

broker: restore client-side PMI logging

---

CONTRIBUTING.md
README.md

Update rfc links to RTD site

---

src/cmd/flux-module.c

flux-module: extend first column of flux-module list output

---

NEWS.md

OK, this is kinda premature, but I wanted to see what we'd done since last release and figured I may as well open a pull request.  Force push at will.

NEWS.md: release notes for 0.20.0

---

config/x_ac_jansson.m4
src/modules/job-manager/event.c
src/modules/kvs/kvstxn.c

also cleanup some code to take advantage of features in newer jansson versions

build: increase minimum version of jansson to 2.10

---

src/modules/job-info/job-info.c
src/modules/job-info/job_state.c
src/modules/job-info/job_state.h
src/modules/job-manager/event.c
t/t2211-job-manager-events.t

various cleanup / minor refactorings as I worked on #3233, #3209, #3234, #3245.

job-manager / job-info: misc cleanup

---

doc/man1/flux-jobs.rst
doc/test/spell.en.pws

i elected not to cut & paste example output, as that can always change as we update things.  Figured the sample command line options were enough.
Could add more ... ???

doc: add flux-jobs(1) examples

---

NEWS.md

Here's a start on 0.21.0 release notes which we'll try to get tagged on Wed AM.   Feel free to push directly to this PR if you have changes.

NEWS.md: prepare for 0.21.0 release

---

src/broker/broker.c
src/common/libjob/job.c
t/ingest/submitbench.c

As discussed in #3305, this PR changes `flux_job_submit()` so that, when built `--with-flux-security`, instance owner jobs are not signed with the default signing mechanism.  This allows `make check` to work when the default signing mechanism is inoperable, such as when it is `munge` and the munge daemon is not running.  It should also improve the bulk job submission rate in a single user instance that is built `--with-flux-security` (such as a batch job) since each job submission does not need to make a round trip to the munge daemon.
It does introduce a synchronous RPC to the broker on first job submission to fetch the instance owner from a broker attribute.  The value is cached in the `flux_t` handle for subsequent job submissions.  I'm not sure if this is OK, and also I need to test …

libjob: always sign owner jobs with the 'none' signing mechanism

---

src/shell/gpubind.c
t/t2604-job-shell-affinity.t

This PR should fix the issues described in #3315 and #3221

shell: fix issues with CUDA_VISIBLE_DEVICES value

---

src/broker/log.c
src/common/libflux/flog.c
t/t0009-dmesg.t

broker: update log.dmesg to use rpc streaming

---

src/modules/sched-simple/sched.c
t/t2300-sched-simple.t

Per #3343 discussion.  Note that the first commit I still from @grondo's comment in the ticket, so someone other than @grondo would have to approve.

testsuite: fix shed-simple test races

---

src/bindings/python/flux/future.py
t/python/t0012-futures.py

It seems restrictive to only allow a single "then_cb" argument to Python continuation functions passed to `future.then()`. This requires packing multiple arguments into dicts or tuples by hand, and generally doesn't seem very "pythonic" (says the non-python programmer).
It turns out this wasn't too difficult to fix (assuming I haven't done something very wrong).
This PR updates the `future.then()` interface to take `*args` and `**kwargs`, and stores them both to later pass to the registered continuation callback. This allows calling a `then()` callback with multiple and/or keyword arguments to work as expected. The existing use cases still work, so this luckily doesn't break any existing code.

python: allow future.then() callbacks to take variable and keyword args

---

doc/man1/flux-jobs.rst
src/bindings/python/flux/job/info.py
src/bindings/python/flux/job/list.py
src/cmd/flux-job.c
src/cmd/flux-jobs.py
src/modules/job-info/job_util.c
src/modules/job-info/list.c
t/t2230-job-info-list.t
t/t2234-job-info-list-update.t
t/t2800-jobs-cmd.t

Built on top of #3404.  Shouldn't be too much surprising in this PR.

Support query of priority in job listing tools

---

NEWS.md

Here's a start at release notes for 0.22.0.  Feel free to push updates here.

NEWS.md: update for 0.22.0 release

---

src/modules/job-manager/jobtap.c

Some compilers complain about `va_list ap` being used uninitialized in `jobtap_get_priority()`.
Split the plugin args creation function into two parts, one that take a `va_list` and one that doesn't so that an uninitialized `va_list` doesn't need to be used when the calling function doesn't take variable arguments.

job-manager: fix uninitialized variable warning in jobtap.c

---

src/modules/job-manager/jobtap.c

job-manager: fix compilation error on gcc-10

---

src/cmd/flux-kvs.c
src/common/liboptparse/optparse.c
t/issues/t3492-kvs-subcommand-help.sh

flux-kvs: fix help output in nested subcommands

---

doc/man1/flux-mini.rst
src/cmd/flux-mini.py
t/t2213-job-manager-hold-single.t
t/t2214-job-manager-hold-limited.t
t/t2215-job-manager-hold-unlimited.t
t/t2700-mini-cmd.t

flux-mini: support special urgency values "default", "hold", "expedite"

---

NEWS.md

Work in progress release notes for v0.24.0.
Feel free to directly push any changes or updates here.

NEWS.md: add release notes for flux-core v0.24.0

---

src/bindings/python/flux/job/executor.py
t/python/t0023-executor.py

I noticed that ``flux.job.submit`` gained some new parameters since #3468, so this PR changes the signature of ``FluxExecutor.submit`` from ``def submit(self, jobspec)`` to ``def submit(self, *args, **kwargs)``. The positional and keyword arguments are passed directly to ``flux.job.submit``. The only difference between the two signatures is that ``FluxExecutor.submit`` doesn't accept a Flux handle, since it supplies that parameter to ``flux.job.submit`` itself.
Now the signatures of ``FluxExecutor.submit`` and ``flux.job.submit`` should stay synchronized.

python: expand FluxExecutor.submit parameters

---

NEWS.md

First try at some release notes for 0.25.0.  As always, feel free to push directly here.

NEWS.md: update for 0.25.0 release

---

src/modules/kvs/kvs.c

Problem: Every setroot event includes the current rootdir tree object
in the event.  This allows all event receivers to "prime" their KVS
cache with the newest root directory object.  However, there is never
a guarantee that this new rootdir will ever be used.  For example, a
subsequent setroot event will overwrite the prior setroot event's
data before it is used.
During testing, it was determined that the cost of sending the rootdir
object on each setroot event and the processing of this event might
have a negative performance impact.  It appears it is a net win for
KVS clients to lookup root objects as they are needed.  Upon code
review, this makes sense, as treeobj_validate() and several blobref
functions are regularly called.  These are known to be relatively
slow iterating functions …

kvs: remove rootdir from setroot events

---

NEWS.md

First cut at release notes for 0.26.0.

NEWS: add news items for release 0.26.0

---

src/broker/content-cache.c
t/t0012-content-sqlite.t

Split from PR #3639 (this should go in first).

content-cache: general cleanup, small bug fixes, and test improvement

---

src/bindings/python/flux/job/executor.py
t/python/t0023-executor.py

A bugfix and a behavioral change that I'm happy to split if you think it would be better.
The bug is that calling ``Future.cancel()`` more than once will raise an error. I've already been bitten by this more than once.
The behavior change is that when a future is cancelled, calling ``Future.jobid()`` will now raise a ``CancelledError`` rather than returning -1.

python: fix FluxExecutorFuture cancellation bug

---

src/common/libsubprocess/command.c
src/common/libsubprocess/test/cmd.c
src/shell/jobspec.c
src/shell/shell.c
src/shell/task.c

Environment-related fixes peeled off of #3661, since these are not directly related to that PR.

shell: misc environment-related fixes

---

src/modules/kvs/cache.c

This is built on top of #3663.  I'll just cut & paste the commit message here:
```
Problem: During profiling runs the cache_expire_entries() function
is shown to be a minor bottleneck.  It appears to be busy due to a
call to zhashx_keys().  The function creates a zlistx of all keys
in the primary cache's hash.  This requires iterating through the
entire hash (all hash buckets, including empty ones), and allocating
memory for every string added to the zlistx.
Solution: Support a list 'entries_list' which maintains a list of
all current cache entries.  When cache_expire_entries() is called,
simply iterate through this list instead.  It eliminates the iteration
of the entire cache hash and eliminates the excess memory allocations.
```
After doing some benchmark tests, this was overall deemed …

kvs: reduce cache expiration overhead

---

NEWS.md

Here's a proposed set of release notes for our end of the month release.  As always, feel free to push here directly as needed.

NEWS.md: update for 0.27.0

---

src/common/libflux/message.c
src/common/libflux/message.h
src/common/libflux/test/message.c
src/common/librouter/sendfd.c

I accidentally closed #3697 and can't re-open it.   
Fixed the remaining comment mentioned by @garlick.

libflux: msg API cleanup

---

doc/man1/flux-broker.rst
src/broker/Makefile.am
src/broker/broker.c
src/broker/broker.h
src/broker/module.c
src/broker/publisher.c
src/broker/publisher.h
t/t0001-basic.t

This is just a random assortment of broker cleanups:  removing unused options, switching to optparse, conslidating unlikely error paths, etc..

broker: misc cleanup

---

src/common/libflux/message.c
src/common/libflux/test/message.c

peeling off these cleanups / re-orgs from #3701 as the number of cleanups / re-orgs / minor stuff was starting to get big.

libflux: msg API cleanup, test cleanup, and test enhancement 

---

NEWS.md

Candidate release notes - feel free to push changes directly to this branch.

NEWS: add release notes for 0.28

---

src/broker/ping.c
src/common/libflux/message.c
src/common/libflux/test/message.c
src/common/libterminus/pty.c
src/modules/resource/rutil.c
src/modules/resource/rutil.h
src/modules/resource/test/rutil.c

Misc commits peeled off from #3746

various cleanups and fixes (typos, code style, mem-leaks, dead code, minor refactoring)

---

doc/Makefile.am
doc/conf.py
doc/man1/flux-job.rst
doc/man1/index.rst
doc/man3/index.rst
doc/test/spell.en.pws
src/cmd/flux-job.c

This was peeled off of pr #3741.

add flux-job(1) manual page, plus minor fixes

---

src/common/libflux/message.c
src/common/libflux/message.h
src/common/libflux/test/message.c

Split off from #3746 as the cleanups were getting long.

libflux: minor msg API fixes / cleanup (typos, refactor, code logic)

---

src/bindings/python/flux/job/executor.py
t/python/t0023-executor.py

As mentioned in #3783, FluxExecutor instances only work with jobs that they submit themselves, not jobs that are submitted by other instances or by other mechanisms. This PR adds a `FluxExecutor.attach(jobid)` method that takes a job ID and returns a future. The futures behaves identically to those that are returned by `FluxExecutor.submit(jobspec)`. The only difference is that the job ID of the `attach` futures is available immediately, so `attach_future.jobid(0)` should never fail.
Tagging @andre-merzky .

python: allow executor to attach to jobs

---

src/common/libflux/fripp.c
src/common/libflux/fripp.h
src/common/libflux/stats.c
t/scripts/stats-listen.py
t/t1200-stats-basic.t

Fixing some minor nits with the fripp stats collection code, encountered while  instrumenting #3822.
(Apologies to @garrettbslone for not catching some of these during the review window!)

fripp: misc cleanup

---

src/modules/job-manager/plugins/dependency-after.c
t/t2271-job-dependency-after.t

This PR builds on top of #3863 and changes the behavior of the dependency-after plugin to release `after:JOBID` jobs after the `start` event instead of on transition to `RUN` state (i.e. after the `alloc` event). This will allow for better synchronization of dependent jobs when there may be delay between job allocation and job start (e.g. for service jobs or k8s containers, etc)
Still WIP because I need to work on testing. However, putting it up now for early feedback.

job-manager: release after:JOBID dependencies after "start" instead of "alloc" event

---

NEWS.md

Here are draft notes for flux-core 0.32.0.  As always, feel free to push changes here.

NEWS: add release notes for 0.32.0

---

doc/Makefile.am
doc/conf.py
doc/man1/flux-mini.rst
doc/man3/JSON_PACK.rst
doc/man3/JSON_UNPACK.rst
doc/man3/flux_child_watcher_create.rst
doc/man3/flux_fd_watcher_create.rst
doc/man3/flux_handle_watcher_create.rst
doc/man3/flux_idle_watcher_create.rst
doc/man3/flux_kvs_commit.rst
doc/man3/flux_kvs_lookup.rst
doc/man3/flux_log.rst
doc/man3/flux_msg_handler_create.rst
doc/man3/flux_periodic_watcher_create.rst
doc/man3/flux_service_register.rst
doc/man3/flux_shell_get_info.rst
doc/man3/flux_shell_get_jobspec_info.rst
doc/man3/flux_signal_watcher_create.rst
doc/man3/flux_stat_watcher_create.rst
doc/man3/flux_timer_watcher_create.rst
doc/man3/idset_add.rst
doc/man3/index.rst
doc/man7/flux-broker-attributes.rst
src/common/libflux/service.h

splitting off from #4007 
- various minor fixes
- update jansson text
- add a missing manpage that was referenced from other manpages

doc: misc updates and fixes

---

src/common/libterminus/client.c
t/t2612-job-shell-pty.t

This PR fixes the issues described in #4005 with two updates to the pty client code:
1. Terminate and detach the pty client on error response from a pty write message. It is unlikely things will get any better, and since the forced detach character `^\` requires a response from the server, trying to stay "connected" just causes the client to get stuck with no way out.
2. Add periodic zero-length writes from the client to act as keepalives. This prevents a `flux job attach` to a job with a pty from hanging forever when there is no client activity and the remote is killed (e.g. after a timeout or other error)
Now this construct doesn't hang:
```console
$ flux mini alloc -N2 -n2 -o exit-timeout=1 sh -c 'flux overlay disconnect 1 && sleep inf'
flux-overlay: asking rank 0 to disconnect child …
```

fix uninterruptible hang when attached to terminated jobs with -o pty

---

src/connectors/local/local.c
src/connectors/loop/loop.c
src/connectors/shmem/shmem.c
src/connectors/ssh/ssh.c

Some connector cleanup that was part of the withdrawn #3998.

connector cleanup

---

t/t2801-top-cmd.t
t/t2802-uri-cmd.t

hit some corner cases on my machine, minor fixes

testsuite: minor testsuite fixes

---

src/cmd/builtin/overlay.c

Problem: The flux-overlay status command output doesn't connect
parent ranks to all their children, making output slightly difficult
to read.
Add support for a prettier tree output using compact Unicode tree
"connectors". To properly maintain current node indent and prefix,
a "stack" of connectors is maintained throughout the traversal,
where the appropriate parent prefix is pushed on descending to a child,
and popped when recursive descent is complete.
Unfortunately, this doesn't work prefectly with the --down option
since in that case there is no way to know when the traversal has
encountered the last child of a parent, but still the output even
in this case is slightly improved.
before:
```
0 asp: full
└1 asp: full
└3 asp: full
└7 asp: full
└15 asp: full
└8 asp: full
└4 asp: full
└9 …
```

flux-overlay: enhance tree for overlay status

---

src/modules/job-exec/job-exec.c

This is a possible fix for #4036.
When running a high throughput series of jobs with very short durations, a delay between when R is created by the scheduler and the job is actually started by the job-exec module can be long enough to cause jobs to be prematurely terminated due to timeout, or for very short durations jobs can even get an exception due to starting after the expiration set in R.
This simple change adds an adjustment in the job-exec module to take into account the time difference between R starttime and the time at which the job-exec module is actually starting the job.
Long term there may be a better solution, but this should work around the specific issue in #4036.
I ran the reproducer several times with this fix and didn't hit any timeout failures.

add workaround for invalid job timeouts when system is busy

---

NEWS.md

Update release notes for flux-core v0.33.0.
I tried to summarize the usability enhancements in this release before the detailed notes.
As always, feel free to force push any updates or improvements directly to this branch.

NEWS.md: add release notes for v0.33.0

---

src/bindings/python/flux/uri/resolvers/pid.py
t/sharness.d/flux-sharness.sh
t/t1105-proxy.t
t/t2802-uri-cmd.t

This PR has proposed fixes for #4048 and #4049.
@jameshcorbett, could you try this branch on Perlmutter and see if it resolves the test failures?

Fix issues found on Cray Shasta (perlmutter)

---

src/cmd/flux-perilog-run.py
t/t2274-manager-perilog.t

When attempting to set up prolog/epilog support on a system, it was discovered that errors from remote prolog/epilog execution were being copied to the logs without an identifying rank or hostname, which made diagnosis of errors unnecessarily difficult.
This PR improves the logging of the `flux perilog-run` script when used to execute per-rank `prolog` and `epilog` by including the rank and hostname in any lines of stderr generated by these scripts, along with other small improvements.

flux-perilog-run: improve usefulness of logging when prolog/epilog fails

---

NEWS.md

Notes for our next release at the end of the week.  As always, please feel free to push directly to this PR.

NEWS.md: add release notes for v0.34.0

---

src/cmd/builtin/overlay.c
t/t3300-system-basic.t
t/t3301-system-latestart.t
t/t3303-system-healthcheck.t
t/t3304-system-rpctrack-down.t
t/t3305-system-rpctrack-up.t
t/t3306-system-routercrash.t
t/t3307-system-leafcrash.t

This fixes a couple of issues with `flux overlay` identified during testing on fluke yesterday.

flux-overlay: improve timeouts, hostname handling

---

configure.ac
src/cmd/builtin/version.c
src/common/Makefile.am
src/common/libsdprocess/Makefile.am
src/common/libsdprocess/sdprocess.c
src/common/libsdprocess/sdprocess.h
src/common/libsdprocess/sdprocess_private.h
src/common/libsdprocess/strv.c
src/common/libsdprocess/strv.h
src/common/libsdprocess/test/sdprocess.c
src/common/libsdprocess/test/strv.c
src/common/libsdprocess/test/test_echo.c
src/common/libsdprocess/test/test_env.c
t/Makefile.am
t/sdprocess/job-signal-exit.c
t/sdprocess/sim-broker.c
t/t2410-exec-systemd.t

per some discussion in https://github.com/flux-framework/flux-core/issues/3815 I'd thought I'd post my initial implementation of `libsdprocess` to see if there are any initial comments.  Probably the header file `sdprocess.h` is the most important thing to skim over.

Support new libsdprocess to launch processes under systemd

---

t/t2250-job-archive.t

Problem: The helper functions in t2250-job-archive.t do not
have descriptive comments.
Add some comments to help.

testsuite: add clarification comments

---

NEWS.md

This is a draft of release notes for flux-core v0.36.0.
As usual, feel free to directly push any changes to this branch as necessary.

NEWS.md: add release notes for v0.36.0

---

NEWS.md

Release notes for flux-core v0.37.0 (assuming #4192 will go in).
Feel free to edit as needed.

NEWS.md: update release notes for flux-core v0.37.0

---

src/common/libsdprocess/sdprocess.c
src/common/libsubprocess/test/subprocess.c
src/modules/job-exec/bulk-exec.c
src/modules/job-exec/job-exec.h
src/modules/job-exec/testexec.c
t/t3202-instance-restart-testexec.t
t/valgrind/workload.d/job-info
t/valgrind/workload.d/job-list

Splitting these out from #4070, as number of commits was growing large.

misc minor fixes and cleanup

---

src/modules/sched-simple/sched.c
t/t2900-job-timelimits.t

This PR is pretty trivial. If there is no duration set in a jobspec, and the current instance has a nonzero `expiration`, then propagate that expiration to the _R_ generated for the job.
This change does _not_ check if a job with a nonzero duration would exceed the current instance lifetime. That will be in a separate PR.

sched-simple: set expiration of jobs with no duration to instance lifetime

---

src/modules/job-manager/event.c
src/modules/job-manager/job.c
src/modules/job-manager/submit.c

Just a few minor cleanup patches peeled off of other work.

job-manager: misc cleanup

---

src/common/libsdprocess/sdprocess.c
src/common/libsdprocess/sdprocess.h
src/common/libsdprocess/strv.c

Pulling out some minor libsdprocess fixups from #4070 and a forthcoming branch about systemd properties.

libsdprocess: minor fixups

---

src/bindings/python/flux/hostlist.py
src/bindings/python/flux/idset.py
src/broker/liblist.c
src/test/docker/README.md
src/test/docker/fedora35/Dockerfile
src/test/docker/fedora35/config.site
src/test/generate-matrix.py

This adds a Dockerfile and CI build for fedora35 and fixes a couple issues found as a result.

ci: add build for Fedora 35

---

t/README.md

Noticed some trailing whitespace in the README, then decided to just fix up other things.

testsuite: minor README fixes / updates

---

src/common/librlist/rlist.c
src/common/librlist/test/rlist.c

As noted in #4290, librlist and thus sched-simple ignores up/down state of nodes when the `--exclusive` flag is used (implicitly or explicitly). This is because the `exclusive` branch in `rlist_alloc_nnodes()` simply ignored the state of nodes while trying to allocate them exclusively.
This patch fixes the algorithm to sort down nodes to the end of the list, then abort the search on encountering the first used _or_ down node.
A unit test is added to ensure basic operation of the fix.

sched-simple: do not allocate down nodes with --exclusive

---

src/modules/job-list/job_state.c

misc cleanups I found will working on the `job-db` prototype in #4273.  Forgot they were sitting around on a branch :-)

job-list: misc cleanups

---

src/modules/content-s3/s3.c
src/modules/content-s3/s3.h

This PR contains a couple of cosmetic cleanup commits that I dropped from pr #4303 since they were a bit off topic there.

content-s3: cosmetic cleanup

---

t/README.md
t/job-list/list-id.py
t/t0000-sharness.t
t/t0018-content-files.t
t/t0024-content-s3.t
t/t1005-kvs-security.t
t/t1009-kvs-copy.t
t/t2100-job-ingest.t
t/t2260-job-list.t
t/t2261-job-list-update.t

All I wanted to do was document the TEST_LONG environment variable, b/c I always forget what environment variable to set.  Then I fixed up more stuff :-)

teststuite: document and fixup LONGTEST tests

---

NEWS.md

Here's a start on release notes for flux-core 0.39.0.  Feel free to push directly to this PR as needed.

NEWS.md: add items for 0.39.0 release

---

src/bindings/python/flux/resource/ResourceSet.py
src/bindings/python/flux/resource/list.py

Hobbs was asking me how to use the `flux.resource.list` module this morning and I realized it wasn't especially clear.

docs: add python resource_list docstrings

---

NEWS.md

Here's an early draft of release notes for flux-core v0.40.0.
As always, feel free to directly push edits to this branch.

NEWS.md: add release notes for v0.40.0

---

NEWS.md

Problem: upcoming 0.41.0 release requires release notes.
Add a news entry.

NEWS.md: add release notes for 0.41.0

---

src/modules/job-exec/sdexec.c
src/modules/kvs/kvs.c
src/modules/kvs/kvsroot.c
src/modules/kvs/kvsroot.h
src/modules/kvs/kvstxn.c
src/modules/kvs/test/kvsroot.c
src/modules/kvs/test/kvstxn.c

Peeling off from #4383, that PR is going to pivot in a new direction and these cleanups wouldn't necessarily be relevant to the shift.  But they are still decent cleanups.

kvs: misc cleanups

---

src/modules/job-archive/job-archive.c

Problem: The error
job-archive.err[0]: job_info_lookup_continuation: parse job
was recently observed, which did not provide insight into the deeper
problem.
Solution: Improve the error message by using json_unpack_ex() to
get parsing error information.  Also add the job ID to the error
output.
Fixes #4403

job-archive: improve logging on parse job error

---

doc/man5/flux-config-bootstrap.rst

Problem: there is too much prose crammed into the key table
hosts entry.
Add some background information to the DESCRIPTION section,
so that the key descriptions can be made more concise, then
break out a section on host entry keys.
Convert the WARNING paragraph in the description to a restructured
text warning box.
Fixes #4408

flux-config-bootstrap(5): improve hosts description

---

.github/workflows/build-container.yaml
etc/docker/Dockerfile.base
etc/docker/README.md

Note that there is a bug in spack that must be fixed for the multistage build (the next container coming) to work.
Bug: https://github.com/spack/spack/pull/31939

add start of spack base image for flux-core

---

t/t2010-kvs-snapshot-restore.t

splitting out from #4492, as that PR has evolved this cleanup / extra tests sort of don't belong there anymore.

testsuite: add more checkpoint sequence tests

---

.github/workflows/build-container.yaml
etc/docker/Dockerfile
etc/docker/README.md
etc/docker/git-config

Not multi-stage build yet because we do not have copy view, only symlink! I tested running a piece of the tutorial in here and the basics worked!

spack: add flux-core container build

---

src/modules/job-list/idsync.c
src/modules/job-list/job_state.c
src/modules/job-list/list.c

a few misc cleanups that were peeled off of a now-tabled PR

job-list: misc cleanup

---

src/broker/module.c

Problem: on Ubuntu 22.04, t0014-runlevel.t triggers a segfault when it runs the broker with broker.rc3_path=/bin/false.
If a module has not been fully unloaded by the time modhash_destroy() is called, the module's context could be destroyed before its service entry is removed.  Then a disconnect message sent when another module context is destroyed may cause the destroyed module context to be dereferenced.
Add code to ensure the service hash is removed when the module is destroyed, if that hasn't happened already.
Fixes #4564.

broker: fix use-after-free segfault

---

src/modules/job-manager/event.c

Problem: we get 'error preserving inactive job: no such file or directory' errors on occasion.
The event_job_action() function is documented as idempotent so expect that the INACTIVE state action may be executed multiple times, and do not log this as an error.
Fixes #4585

job-manager: print better errors on inactive move

---

src/modules/job-list/job_data.c
t/t2800-jobs-cmd.t

Problem: Under several special cases to work around Jobspec V1
limitations, the shell per-resource options are used to specify
number of tasks in a job.  This case was not handled by job-list.
Solution: Handle this special case and set ntasks accordingly.

job-list: handle per-resource ntasks special case

---

src/shell/pmi/pmi.c

Problem: when a Flux instance has multiple brokers on one node, PMI cliques are generated using "single" mode, but when an instance has multiple brokers on multiple nodes, cliques are generated using "pershell" mode.  Propagating "single" through sub-instances causes information to be lost in the broker.mapping attribute, rendering it useless for determining the hierarchical relationships between brokers.
Always use "pershell" (unless overridden).
Fixes #4619

flux-shell: always use pmi=pershell by default

---

src/modules/job-list/job_data.c
src/modules/job-list/job_data.h
t/t2260-job-list.t
t/t2800-jobs-cmd.t

second attempt at this after failed attempt in #4601

job-list: handle per-resource "cores" special cases

---

src/modules/job-ingest/job-ingest.c
t/t2100-job-ingest.t

As discussed in #4520, this drops `attributes.system.environment` from the `jobspec` stored in the KVS.  The original jobspec is still available via `J` (signed).

drop environment from KVS jobspec

---

src/bindings/lua/flux-lua.c
src/bindings/lua/lutil.c
src/common/librlist/rlist.c
src/common/libterminus/terminus.c
src/common/libutil/ipaddr.c
src/modules/cron/task.c
src/modules/job-manager/submit.c
src/shell/log.c
src/shell/rc.c

This PR fixes all the critical issues flagged by CodeQL security scanning, most of which were non-constant format strings in various places.

codeql: fix some critical issues found by security scanning

---

NEWS.md

Here's a stab at release notes for 0.45.0.  As always, feel free to push corrections/additions directly to this branch.

NEWS.md: add release notes for v0.45.0

---

t/t2201-job-cmd.t

Problem: A number of more basic flux job raise / cancel / kill tests are not covered.  In some cases they may be covered by use in other testsuite areas, but a more basic and clear coverage of usage and options doesn't exist.
Add missing raise, cancel, and kill coverage.
Fixes #4736

testsuite: add flux job raise/cancel/kill tests

---

src/common/libutil/test/fileref.c
t/t0029-filemap-cmd.t

proposed solutions for issue #4809 and #4810

testsuite: fix several corner cases in t0029-filemap-cmd

---

src/bindings/python/flux/util.py
src/common/libutil/fsd.c
src/common/libutil/test/fsd.c

This PR updates the C and Python interfaces in flux-core to support RFC 23 "infinity" special case.

libutil: support "infinity" in FSD

---

doc/man1/flux-job.rst
doc/man1/flux-mini.rst
doc/test/spell.en.pws

tackling all the tough issues before the holiday break!

doc: document subcommand wait in flux-job(1)

---

doc/man1/flux-resource.rst
doc/test/spell.en.pws

tackling the most difficult issues before the holiday break!  
Hopefully I got all of this right, had to go through code to figure out what was available / allowed.

 doc: document format fields in flux-resource(1) 

---

src/modules/job-manager/plugins/perilog.c

Problem: A rare segfault seems to be triggered by the job manager 'perilog' plugin. Coredump analysis shows that when an internal subprocess kill future is fulfilled with ETIMEDOUT, the perilog_proc structure is invalid, resulting in a segfault when the plugin tries to send SIGKILL to the prolog subprocess. It is unknown why this occurs, since the future should be destroyed when the `struct perilog_proc` is, therefore the future should never be fulfilled if the perilog_proc entry has been freed.
However, it may make the code more clear and robust if the kill timeout is implemented with a traditional timer watcher, instead of abusing the timeout of the original kill future to trigger SIGKILL. Perhaps something in this use case is causing a race when the process is exiting or has exited. …

job-manager: switch to timer watcher in perilog plugin

---

src/cmd/flux-resource.py
t/t2350-resource-list.t

Per discussion in #4891.
Only minor thing to debate is what I did in commit https://github.com/flux-framework/flux-core/commit/f4cbdd5dc6a5c5872c38331eb5928172c3da81ac.  I like it, but I can see others may not.

flux-resource: handle queues with no configured constraints

---

README.md
vscode.md

This fixes a couple spelling errors and a dropped heading  that were missed in the PR that was just merged.  Sorry for the extra noise!

README: fix a couple typos

---

configure.ac
src/bindings/python/flux/Makefile.am
src/bindings/python/flux/cli/fortune.py
src/cmd/Makefile.am
src/cmd/flux-fortune.py
t/t0001-basic.t

Problem: we do not have enough fun in Flux.
Solution: we can take advantage of the "bug" that we can add commands to Flux and have them not show up. "The bug is a feature!" This should add a bit of hidden fun that we can tweak over the years to add to the surprise. :)

add some fun to flux 🎉️🪅️

---

src/common/libpmi/upmi_libpmi.c
src/common/libpmi/upmi_libpmi2.c

Problem: when libpmi and libpmi2 upmi plugins fail, they do not include the full path the dso in errors.
This was a regression from flux-framework/flux-core#5058.
Restore paths to error messages.

libpmi: improve error messages from upmi plugins

---

NEWS.md

First draft of release notes for v0.49.0. Feel free to modify as needed.

NEWS.md: add release notes for v0.49.0

---

debian/control
doc/test/spell.en.pws
etc/completions/flux.pre
src/modules/job-manager/conf.h
t/t1007-kvs-lookup-watch.t
t/t2208-job-manager-wait.t
t/t2270-job-dependencies.t
t/t2276-job-requires.t
t/t2611-debug-emulate.t
t/t2613-job-shell-batch.t
t/t2616-job-shell-taskmap.t

Just like #4934, the PR for minor typos so we don't have a ton of them littered in every release.

Fix minor typos and formatting

---

src/common/librlist/match.c
src/common/librlist/match.h

librlist: fix memleak + misc cleanup

---

src/common/libutil/test/fileref.c
src/modules/resource/exclude.c
t/t0016-cron-faketime.t

This PR is a set of small fixes required to build on fedora36 and GCC 12.

fixes for build/test on Fedora 36 (GCC 12)

---

NEWS.md

First draft of release notes for v0.50.0. Feel free to push updates and changes directly here.

NEWS.md: add release notes for v0.50.0

---

t/t2801-top-cmd.t

Problem: On rare occasions some tests in t2801-top-cmd.t fail when running large parallel runs of the testsuite.  The suspicion is that the job-list module has not yet synced up to have knowledge of the jobs that have been submitted in the tests.
Add a function to wait until jobs in t2801-top-cmd.t are known by job-list and have reached the state we want to ensure tests will pass.

testsuite: fix race in flux top tests

---

etc/completions/flux.pre

The bash completions are slightly out of date. This PR updates them (for the changes I found) and also fixes a minor annoyance I have noticed lately.

completions: update bash completions with recent command changes

---

NEWS.md

As always, feel free to push additions or changes directly here.
I preemptively added #5237 and #5236.

NEWS.md: add release notes for v0.51.0

---

src/cmd/top/joblist_pane.c

Problem: When jobids are being encoded with ascii 'f', jobs in the flux-top(1) joblist pane are not aligned with the header row. This occurs because mvwprintw(3) doesn't seem to handle multibyte UTF-8 characters properly. (This appears to be why the JOBID column is formatted with %12s while the jobs are formatted with %13.13s currently).
e.g.
Detect whether ascii 'f' is being used in jobids by testing the result of strlen(3) for jobid 0. If the result is 2 then ascii jobids are being used, so use 13 for the JOBID column width, otherwise the multibyte 'ƒ' is most likely being used so use 12 for the JOBID width.

flux-top: fix formatting with ASCII jobids

---

t/t2800-jobs-cmd.t

Problem: In several tests in t2800-jobs-cmd.t, a job is sent a signal immediately after the job starts.  There is a rare race that can occur when signaling a job very quickly after it has started.  This race can lead to unexpected results.
Solution: Instead of calling "sleep inf", run a script that will echo some output then call "sleep inf".  Ensure that data has been output from the job before signaling it.  This will ensure that the job has started and the process is fully running before being sent a signal.
Fixes #5210

testsuite: workaround job start signal race

---

src/cmd/flux-job.c
src/common/libjob/job.h
src/common/libjob/test/unwrap.c
src/common/libjob/unwrap.c
src/common/libjob/unwrap.h
src/shell/info.c

Per comment in #5311 splitting this into its own PR.

libjob: export flux_unwrap_string(3) function

---

src/common/librlist/match.c
src/common/librlist/test/match.c

This updates a corner case and adds tests given updates in RFC31.  Marking this as WIP as this assumes https://github.com/flux-framework/rfc/pull/377 will be accepted, so we shouldn't merge until after it is merged.

librlist: fix RFC31 corner cases

---

t/t2304-sched-simple-alloc-check.t

After reworking this test for fluxion, I realized some improvements should be made to the copy in flux-core.
(sorry I rushed the review earlier!)

testsuite: improve alloc-check test

---

src/broker/brokercfg.c
src/modules/job-manager/alloc.c
src/modules/job-manager/annotate.c
src/modules/job-manager/drain.c
src/modules/job-manager/event.c
src/modules/job-manager/getattr.c
src/modules/job-manager/job-manager.c
src/modules/job-manager/job.c
src/modules/job-manager/jobtap.c
src/modules/job-manager/journal.c
src/modules/job-manager/kill.c
src/modules/job-manager/list.c
src/modules/job-manager/plugins/begin-time.c
src/modules/job-manager/plugins/dependency-after.c
src/modules/job-manager/plugins/perilog.c
src/modules/job-manager/plugins/priority-default.c
src/modules/job-manager/plugins/validate-duration.c
src/modules/job-manager/raise.c
src/modules/job-manager/start.c
src/modules/job-manager/submit.c
src/modules/job-manager/urgency.c
src/modules/job-manager/wait.c

Maybe we can leave this PR open for a bit to catch typo fixes and the like for the next release.

fix assorted typos and adjust whitespace per project norms

---

src/bindings/python/flux/job/list.py
src/cmd/flux-jobs.py
t/t2800-jobs-cmd.t

Built on top of #5126, these are solutions for the flux jobs filtering corner cases described in #5142 and #5149.

flux-jobs: correct several filtering corner cases

---

src/modules/job-list/list.c
t/t2260-job-list.t

Per discussion in #5363
note, I contemplated adding some type of "--old-rpc" option to `flux-jobs` so we could do a super thorough coverage, basically running t2800-jobs-cmd.t twice, but given desire to get this into the next release didn't do that.  So I added a healthy mix of old RPC format tests into t2260-job-list.t.
Did a hand test running older version of flux inside newer instance.

job-list: support older RPC protocol

---

NEWS.md

Feel free to amend as necessary. I've already added #5359 and #5360 assuming they'll be merged before EOD.

NEWS.md: add release notes for v0.53.0

---

src/bindings/python/flux/kvs.py
t/python/t0005-kvs.py

This originally started out as an experiment just to see if A) could we add some modernization to the Python kvs module without breaking/obliterating the old API and B) see if anything comes up to surprise us design wise in how we'd want to move forward with a modernized API.
In this PR I add namespace support to the kvs module via an optional namespace argument to all appropriate functions.  Overall I think it's ok.  I think it could go in w/o much fanfare.  Notes:
- Order of parameters still left for intended positional arguments.  My anal retentive side dislikes this, as "flags" is often listed positional before "namespace".  Left as is unless we want to intentionally break things.
- Also did a big cleanup of the t0005-kvs.py tests.  Both grouping/organizing the tests  (i.e. `walk()` …

python: add namespace support to KVS module

---

NEWS.md

Here are release notes for 0.54.0 - please amend/modify as needed.

NEWS: add news items for release 0.54.0

---

NEWS.md

This PR is a first draft of release notes for flux-core v0.56.0.
I've already added entries for the 3 pending PRs. As usual, feel free to push directly to this branch with fixes/additions/updates.

NEWS.md: add release notes for v0.56.0

---

src/test/checks_run.sh
src/test/docker/alpine/Dockerfile
src/test/docker/docker-run-checks.sh
src/test/generate-matrix.py
t/python/t0015-job-output.py

Pushing this here as a place to coordinate on a fully working Dockerfile for alpine to eventually include in CI.
This version works (with some changes) with flux-security. I've pushed the result to `fluxrm/testenv:alpine` so that a PR for flux-security can be developed (and tested), but feel free to amend/change/update this PR as needed for flux-core.

ci: add alpine Dockerfile and CI build

---

src/common/librouter/test/usock_epipe.c
src/modules/job-exec/testexec.c
src/test/docker/alpine/Dockerfile
src/test/generate-matrix.py
t/Makefile.am
t/lua/t0002-rpc.t
t/scripts/runpty.py
t/scripts/strerror_symbol
t/sharness.d/flux-sharness.sh
t/t0001-basic.t
t/t0005-exec.t
t/t0005-rexec.t
t/t0007-ping.t
t/t1001-kvs-internals.t
t/t1004-kvs-namespace.t
t/t1007-kvs-lookup-watch.t
t/t1102-cmddriver.t
t/t1106-ssh-connector.t
t/t2802-uri-cmd.t
t/t3301-system-latestart.t
t/t3303-system-healthcheck.t
t/t3304-system-rpctrack-down.t

This is a working branch in which various portability issues are worked through to get flux running on alpine linux.  Posting it early since others may be looking at it.

get sharness tests working on alpine linux

---

src/modules/kvs-watch/kvs-watch.c

When profiling Flux during a throughput test, I noticed an unexpectedly large percentage of the broker's time was spent in `watcher_cancel_all()`. As previously discussed, this is because `flux_cancel_match()` needs to unpack a matchtag from the payload of a cancel request before comparison, and this since the function is called for each watcher in the list, the operation is repeated N times for each N watcher for a namespace. Given the profiling results, this appears to be a quite expensive operation.
This PR adjusts `watcher_cancel_all()` so that the matchtag is unpacked once is passed down to `watcher_cancel()` for each attempted match. The watchers list is also updated to a zlistx so that a copy of the list need not be taken each time a disconnect or cancel message is received.
This …

kvs-watch: improve performance of kvs-watch disconnect/cleanup handling

---

t/t2233-job-info-update.t

Problem: Several tests in t2233-job-info-update.t that test the job-info.update-lookup target can be racy.  Internally, the eventlog append may not yet have been seen by a job-info watcher, and the update is therefore not yet seen in the lookup test.
Solution: Add a wait loop around the check to ensure any raciness is avoided.
Fixes #5594

testsuite: fix race in job info update lookups

---

src/modules/job-manager/plugins/history.c
t/t2812-flux-job-last.t

Problem: the job history plugin uses an integer userid as hash key, but the hash implementation won't accept a key (NULL) for userid 0.  This results in errors like:
```
jobtap: job.new: callback returned error
jobtap: job.inactive.add: callback returned error
```
Map userid 0 to `(uid_t)-1` since that value is reserved in POSIX.
Fixes #5475

history: track root jobs

---

src/modules/job-list/list.c
t/t2260-job-list.t

This PR fixes #5619 and with it a class of job-list tests that occasionally fail in ci.

job-list: fix `flux job list-ids --wait-state`

---

etc/completions/flux.pre

This PR includes some minor updates to bash completions (missing options and other tweaks)

minor updates and improvements to bash completions

---

src/bindings/python/flux/job/event.py
src/bindings/python/flux/kvs.py
t/python/t0005-kvs.py

Built on top of #5373 and #5374.
I basically did what was done with `event_watch_async()` and `JobEventWatchFuture`.  Then I created a parent class for both to avoid code duplication.
Notes:
- I call the parent class `WatchABC`, dunno if that's the best name.  I nearly went with "WatchInterface", but knew that wasn't Pythonic wording.  I went with "ABC" (Abstract Base Class), but don't love that either.
- I left `WatchABC` in `kvs.py` which maybe isn't the best place.  Could be in a `watch.py`??  Ehh ...
- I didn't add a synchronous `kvs_watch()` function like `event_watch()`.  As I began testing and I thought about it more, there is probably less need for the function.  Unlike "eventlog watching", general "KVS watch" does not generally have a "known end" to the stream.  Without a known …

python: support interface to perform KVS watch

---

NEWS.md

Here are some proposed release notes for flux-core v0.59.0 that assume the following are merged
- #5715 
- #5719

NEWS: add release notes for v0.59.0

---

doc/man1/common/job-shell-options.rst
doc/man1/flux-shell.rst
src/shell/hwloc.c
t/t2619-job-shell-hwloc.t

shell: unset `HWLOC_COMPONENTS` with `hwloc.xmlfile`

---

src/modules/job-exec/bulk-exec.c
src/modules/job-exec/job-exec.c

This PR fixes the issue described in #5790. If a job is canceled or gets a fatal job exception while the namespace create RPC is in flight, the fact that a namespace exists for the job is dropped and the namespace will be leaked.
Also included in this PR is an improvement to the `exec_kill` error message handling to reduce a non-trivial amount of log noise for large jobs.

job-exec: fix potential leak of job KVS namespaces

---

src/cmd/top/joblist_pane.c

Problem: In rare circumstances a job list record may not contain all the expected fields.  This can lead to a fatal exit in flux-top.
Solution: Instead of exiting in these rare scenarios, just skip the job record.
Fixes #5705

flux-top: skip poorly formed job list records

---

src/broker/overlay.c

Problem: we're seeing the broker spend a lot of time in `child_lookup()` on a system with a large, flat TBON when many nodes are down.
When a message is received from a TBON child that is not currently in the child hash because it is offline, it is either processed as a new hello request, or sent a DISCONNECT control message.  Older code used to log whether the child's UUID was known or unknown by looking it up with a linear search in the child array.  The logging has all been removed at this point, so the search can be dropped.
Fixes #5864
p.s. I manually tested a couple of the scenarios that cause this code path to be traversed:
- a network partition that causes the parent to initiate child disconnect, followed by partition resolution
- an abrupt rank 0 crash (kill -9) that causes the …

broker: avoid slow offline child UUID lookup

---

src/broker/groups.c
src/broker/state_machine.c
src/common/libzmqutil/zap.c
src/modules/job-ingest/worker.c
src/modules/resource/acquire.c
t/t3300-system-basic.t

Well, this is just the big system log noise annoyance du jour.  Feel free to add to this PR.

broker: reduce log noise

---

doc/man1/flux-cron.rst
src/cmd/flux-cron

just knocking off #5600 from the todo list, ended up finding a number of other small things along the way

doc: various minor flux-cron(1) fixes and improvements

---

src/cmd/job/attach.c
t/t2500-job-attach.t

This PR amends the `flux job attach` status line if a queue is stopped. That is, instead of a status of just `waiting for resources` a user will see:
```
flux-job: ƒ97BKDZ7MZ waiting for resources (default queue stopped)     00:00:14
```
where `default` would be replaced with a queue name if the job was submitted to a named queue.

notify user of stopped queue in `flux job attach`

---

NEWS.md

Getting an early start on release notes for a Tuesday release.

NEWS.md: add release notes for v0.62.0

---

doc/man1/flux-exec.rst
doc/man1/flux-shell.rst
doc/test/spell.en.pws

This fixes a couple of issues recently opened about our man pages.

doc:  misc man page cleanup

---

src/common/libsubprocess/remote.c

Problem: When handling status changes for remote subprocesses in rexec_continuation(), it is assumed that a process has reached the EXITED state when the rpc stream receives ENODATA.
A recent broker crash shows that this may not always be the case when systemd (i.e. sdexec) is used to launch remote subprocesses.  In this case, the stream ended before the initial PID was reported.  It is assumed under extreme error scenarios, that systemd may not necessarily report information in the order one would expect with a simple fork/exec.
Solution: If the status stream ends early, do not assume the remote process has exited.  Instead, handle this as an EPROTO error and fail the subprocess.
Fixes https://github.com/flux-framework/flux-core/issues/5956

    libsubprocess: handle remote protocol errors

---

src/cmd/flux-exec.c
src/common/libsdexec/Makefile.am
src/common/libsdexec/channel.c
src/common/libsdexec/channel.h
src/common/libsdexec/outbuf.c
src/common/libsdexec/outbuf.h
src/common/libsdexec/test/channel.c
src/common/libsdexec/test/channel_outbuf.c
src/modules/sdexec/sdexec.c
t/t2411-sdexec-job.t

This adds output buffering to sdexec.
I'll mark WIP temporarily while  I ponder more tests.

add output buffering to sdexec

---

NEWS.md

As usual, feel free to add/amend as needed.

NEWS.md: Add release notes for v0.63.0

---

src/common/librouter/msg_hash.h
src/modules/job-list/match.h
src/modules/job-list/test/match.c
src/modules/job-list/test/state_match.c
src/modules/kvs/kvs.c
src/modules/kvs/kvsroot.c
src/modules/kvs/kvsroot.h

a misc cleanups PR ... mostly wanted to pick off cleanups from multiple branches/PRs/WIPs.

kvs: replace list of message with msglist

---

doc/guide/admin.rst

Problem: we don't have any documentation to help with the selection of overlay network topology.
Add a section to the admin guide "Overview and Background" section.

doc: add overlay network to overview section

---

src/modules/job-exec/exec.c
src/modules/job-exec/job-exec.c

While working on something else, I found a couple places where the job-exec module leaks `struct jobinfo` refcount. This causes jobs to stay resident in the job-exec module even after they are inactive.
This won't show up as a leak with valgrind because the jobinfo objects are eventually destroyed when the job-exec module is unloaded.

job-exec: fix job refcount leaks

---

src/bindings/python/flux/kvs.py
src/modules/kvs/kvs.c

just a couple of minor cleanups, collecting from other work branches

kvs: minor cleanups

---

.typos.toml
src/common/liboptparse/optparse.c
src/test/docker/docker-run-checks.sh
t/sharness.d/flux-sharness.sh
t/sharness.d/heredoc.sh
t/sharness/vim/ftdetect/sharness.vim
t/sharness/vim/indent/sharness.vim
t/sharness/vim/syntax/sharness.vim
t/t0001-basic.t

This aggregates a couple of docker-run-checks, flux-sharness and sharness updates.

add support for new wrap options in tests and heredoc support for sharness

---

t/t2406-job-exec-cleanup.t

Problem: The kill-timeout test races with max-kill-count in t2406-job-exec-cleanup.t. That is, in some cases, max-kill-count (which is forced to 3 attempts in the test) is triggered before the test checks that the kill-timeout value has been increased by the job-exec module, leading to a spurious test failure.
Split up the tests for kill-timeout and max-kill-count. When testing kill-timeout, set max-kill-count to a large number so it is unlikely to be reached. Then separately test max-kill-count after reloading the job-exec module with max-kill-count=3.
Fixes #6184

testsuite: fix racy test in t2406-job-exec-cleanup.t

---

NEWS.md

Release notes for flux-core v0.65.0. This just contains PRs already merged at this time.
As usual, feel free to directly push updates and additions here.

NEWS.md: add release notes for v0.65.0

---

src/modules/kvs/kvs.c
t/t1000-kvs.t

really minor, something dumb i just noticed yesterday

kvs: correct transaction-merge option parsing

---

src/common/libsubprocess/Makefile.am
src/common/libsubprocess/bulk-exec.c
src/common/libsubprocess/bulk-exec.h
src/common/libsubprocess/test/bulk-exec-einval.c
src/common/libsubprocess/test/bulk-exec.c
src/modules/job-exec/exec.c
src/modules/job-manager/housekeeping.c

This PR is peeled off from some other work, and just includes some fairly minor cleanup and improvements for bulk-exec.

libsubprocess: minor improvements to bulk-exec

---

src/shell/output.c

Problem: If stdout or stderr becomes large, it runs the risk of hitting the 1G limit.
Solution: If a user job outputs between 100M and 1G of stdout or stderr output a message to the user recommending to redirect to a file instead.
Fixes #6269
---
time to bike shed the actual message? :-)  Can also debate the size picked.  100M was suggested in #6268, which seems like a fine starting point to output the message.

shell: output stdio output size warning

---

src/modules/job-manager/plugins/perilog.c

Problem: When using the IMP to run the prolog/epilog in the perilog plugin, the IMP path is not set in the bulk_exec object, so it doesn't know to use `flux-imp kill` to signal the subprocess. This results in failure to cancel job prologs when a job gets an exception.
Add a boolean to the perilog configuration if using the IMP. When this boolean is true, set the IMP path in the bulk_exec implementation so that it uses `flux-imp kill`.
Fixes #6296.

perilog: fix kill of prolog/epilog when using IMP

---

etc/completions/flux.pre

This is just a very small set of updates to the bash completions.

etc: minor improvements for bash completions

---

doc/Makefile.am
doc/man3/flux_idle_watcher_create.rst
doc/man3/flux_watcher_set_priority.rst
doc/manpages.py
src/common/libflux/reactor.c
src/common/libflux/reactor.h
src/common/libflux/test/reactor.c

half @garlick and half me (just the testing & docs), so someone else needs to approve :-)

libflux: support modifying watcher priority via flux_watcher_set_priority()

---

NEWS.md

Add release notes for v0.67.0 assuming all PRs with MWP will be merged.
As usual, feel free to push directly here for corrections and additions.

NEWS.md: add release notes for v0.67.0

---

src/common/libfluxutil/policy.c

Problem: when an error is encountered in the [policy] or [queues] TOML configuration tables, the error messages don't leave much to go on, and the fact that the code may be logged from different modules tends to set people off on the wrong path.
Add contextual information.
t2245-policy-config.t covers this code and now produces the following errors:
```
error parsing [policy] config table: 1 object item(s) left unpacked: foo
error parsing [policy.jobspec] config table: 1 object item(s) left unpacked: foo
error parsing [policy.jobspec] config table: 'defaults.system.duration' is not a valid FSD
error parsing [policy.jobspec] config table: 'defaults.system.queue' is not a string
error parsing [policy.limits] config table: 1 object item(s) left unpacked: foo
error parsing …
```

improve policy/queues config error messages

---

src/modules/kvs/cache.c
src/modules/kvs/kvs.c
src/modules/kvs/kvs_checkpoint.c
src/modules/kvs/kvs_wait_version.c
src/modules/kvs/kvs_wait_version.h
src/modules/kvs/kvsroot.c
src/modules/kvs/kvsroot.h
src/modules/kvs/kvstxn.c
src/modules/kvs/kvstxn.h
src/modules/kvs/lookup.c
src/modules/kvs/treq.c
src/modules/kvs/treq.h
src/modules/kvs/waitqueue.c
src/modules/kvs/waitqueue.h

This updates code style for the kvs module.  There should be no functional changes in this PR, only cosmetic.

kvs: fix whitespace issues

---

doc/Makefile.am
doc/guide/debug.rst
doc/guide/internals.rst

Problem: debugging flux is not always easy and we accumulated some tricks along the way that ought to be shared with new developers.
Start a page for this in the flux-core docs.

doc: add debugging notes

---

src/common/libsubprocess/local.c
src/common/libsubprocess/remote.c

Problem: There is always a chance a user may destroy a subprocess object when a callback is called (i.e. output callback, state change callback, etc.).  This can lead to problems if libsubprocess believes the object is still valid when the callback returns.  References are taken on the subprocess object when issuing some callbacks, but it is missing in other callbacks.
Take reference on all callbacks to ensure safety if the user choses the destroy the subprocess in the callback.

libsubprocess: take reference on callbacks

---

src/bindings/python/flux/job/frobnicator/plugins/defaults.py
t/t2112-job-ingest-frobnicator.t

As noted in #6400, queue defaults currently do not override global defaults because the global default is applied before queue defaults are checked.
This PR fixes that.
Fixes #6400

frobnicator: allow queue-specific defaults to override global defaults

---

src/common/libsubprocess/subprocess.c
src/common/libsubprocess/test/subprocess.c

Problem: libsubprocess duplicates the child ends of channel socketpairs onto stdin, stdout, stderr in the child, but leave the original copies open.
Exclude those channels from the idset generated by `subprocess_childfds()`.  Both `fork.c` and `posix_spawn.c` already include logic to close descriptors that do not appear in this idset after stdio is duplicated.
Add a test.

libsubprocess: close extra file descriptors

---

configure.ac
debian/control
src/common/libschedutil/alloc.c
src/common/libschedutil/init.c
src/common/libschedutil/ops.c
src/common/libschedutil/schedutil_private.h

This fixes some minor miscellaneous build issues I happened to notice.

build: misc cleanup

---

src/modules/kvs-watch/kvs-watch.c

kvs-watch: misc cleanup

---

NEWS.md

As usual, feel free to push here directly for updates or modifications.
The release notes should already contain all current PRs that are pending merge.

NEWS.md: add release notes for v0.69.0

---

NEWS.md

As usual feel free to push changes/additions directly here.

NEWS.md: add release notes for v0.70.0

---

src/cmd/flux-exec.c

ignore, trying to get more debug from the CI.  Can't reproduce locally despite best efforts.

flux-exec: fix credits list update race

---

NEWS.md

As usual, feel free to edit or push updates directly here.

NEWS.md: Add release notes for v0.71.0

---

src/modules/kvs-watch/kvs-watch.c
src/modules/kvs/kvs.c
src/modules/kvs/kvs_wait_version.c
src/modules/kvs/kvsroot.c
src/modules/kvs/kvsroot.h
src/modules/kvs/test/kvs_wait_version.c
src/modules/kvs/test/kvsroot.c

just a bunch of small misc cleanups

kvs: more misc cleanups

---

NEWS.md

Feel free to directly push changes or updates.

NEWS.md: add release notes for v0.73.0

---

src/modules/content-files/content-files.c
src/modules/content-s3/content-s3.c
src/modules/content-sqlite/content-sqlite.c
src/modules/content/checkpoint.c
src/modules/kvs/kvstxn.c
src/modules/kvs/test/lookup.c
t/t0028-content-backing-none.t
t/t1012-kvs-checkpoint.t

A collection of miscellaneous cleanups pilfered from multiple branches, just wanted to shave off long commit histories from all of them  :-)

Misc cleanups

---

src/common/libeventlog/eventlogger.c

Problem: The error callback in libeventlog's eventlogger is not called when there is an error.  The issue arises from the fact that the "current" batch is reset after a call to eventlogger_commit(). If an error occurs, eventlog_batch_get() is called to get the "current" batch, which was just reset and is empty.  So no error callback is issued.
Create a new wrapper function commit_batch() that is identical to eventlogger_commit(), but also returns the value of the recently committed batch.  Use this value instead of calling eventlog_batch_get().
Fixes #6753

libeventlog: fix uncalled error callback

---

src/modules/sdmon/sdmon.c

Problem: sometimes rank 0 shows as offline in flux resource status output.
This is because an sdmon unit name glob is too inclusive and finds systemd units for flux-accounting and flux-coral2.
Add addional unit name filtering.
Fixes #6761

sdmon: only match job related systemd units

---

README.md

Add information about availability of up-to-date container images  on DockerHub
closes #6766

Update README.md with pre-built container information

---

src/modules/job-manager/queue.c
t/t2219-job-manager-restart.t

This PR fixes issue #6789. The dequeue of jobs from a stopped queue on restart was missing, probably since all named queues are created in the stopped state. This isn't the case for the default anonymous queue, however, so this PR adds the dequeue to the restart path.
I guess an alternate solution here would be to recover the queues and their state before reloading jobs from the KVS. However, I wanted to change as little as possible in this PR and just fix the issue (which is probably not a critical issue anyway)

job-manager: avoid starting jobs in a stopped anonymous queue on restart

---

src/common/libutil/cronodate.c
src/common/libutil/test/cronodate.c

This PR fixes the hang reported in #6886.

cron: fix potential module hang in `cronodate_next()`

---

t/job-manager/sched-helper.sh
t/sharness.d/flux-sharness.sh
t/t0002-request.t
t/t0012-content-sqlite.t
t/t0017-security.t
t/t0018-content-files.t
t/t0035-content-sqlite-checkpoints.t
t/t2202-job-manager.t
t/t2208-job-manager-wait.t
t/t2210-job-manager-events-journal.t
t/t2230-job-info-lookup.t
t/t2260-job-list.t
t/t2402-job-exec-dummy.t
t/t2407-sdbus.t
t/t2602-job-shell.t
t/t2800-jobs-cmd.t

Per a comment in #6798, some misc cleanups

t: clean up use of jq

---

NEWS.md

Here are some release notes.  They assume the following pending PRs will get merged today:
- #6946 
- #6945
- #6774 
Of course please edit and force push as needed!

NEWS.md: add release notes for v0.77.0

---

src/broker/overlay.c
src/common/libeventlog/eventlogger.c
src/common/libflux/reactor.c
src/common/libflux/watcher.c
src/common/libjob/info.c
src/common/libjob/job.c
src/common/libjob/job.h
src/common/libjob/jobspec1.c
src/common/libjob/kvs.c
src/common/libjob/list.c
src/common/libjob/result.c
src/common/libjob/sign_none.c
src/common/libjob/submit.c
src/common/libjob/wait.c
src/modules/job-manager/housekeeping.c
src/modules/job-manager/plugins/perilog.c

fix minor issues/clean up

---

t/issues/t2492-shell-lost.sh
t/issues/t4583-free-range-test.sh
t/t0019-tbon-config.t
t/t2801-top-cmd.t

The testsuite has become pretty flaky in CI in the last week.
This PR adds some obvious fixes and some extra debug for some tests that fail in CI without a clear cause.

testsuite: various fixes and extra debug

---

NEWS.md

Here's a start at release notes for v0.78.0. I've added #6982 already.
Feel free to push changes or additions directly here.

NEWS.md: add release notes for v0.78.0

---

src/common/libkvs/kvs_checkpoint.c

Problem: In
b0e47dbefc010b030091434ca2f2a72a238aa745
the checkpoint API was altered to support the handling of multiple checkpoints in checkpoint history.  This broke the ability to read checkpoints against older versions of flux.
Support ability to read checkpoints from older versions of flux.
---
hand tested on docker w/ v0.76.0.  I don't think we have infrastructure to do a "current master" vs "random older versions", that's perhaps something to consider for another day?

libkvs: allow checkpoint read on older versions 

---

t/python/subflux.py

Problem: The Python `rerun_under_flux()` function does not sanitize the environment of the newly created Flux instance, which allows environment variables that could potentially affect test results to pass down to the new instance.
Clear the same set of environment variables handled by sharness `test_under_flux()` in `rerun_under_flux()`.

testsuite: sanitize environment in python/subflux.py

---

doc/man1/flux-modprobe.rst
src/bindings/python/flux/modprobe.py

Just a few things I think would help in the modprobe docs.  Wording is highly debatable :-)

doc: add extra clarification to modprobe docs

---

src/broker/runat.c

Problem: now that the broker rc scripts are run as a "remote" sub-processes (in another thread), line buffering is handled remotely and local buffer management, with its large buffer and multiple watchers, is not needed locally.
Set the FLUX_SUBPROCESS_FLAGS_LOCAL_UNBUF flag on the runat remote sub-processes and change the stdio callback to use `flux_subprocess_read()` instead of `flux_subprocess_getline()`, as required by that flag.

broker: disable duplicate buffering on rc subprocs

---

src/bindings/python/flux/modprobe.py
t/t0100-modprobe.t

This PR changes modprobe behavior so it no longer continues running all active tasks after a task failure.
Instead, no more future tasks are scheduled to run, and scheduled but non-running tasks are cancelled.
Tasks that have already started, however, are allowed to finish.

modprobe: abort operation on first task failure

---

src/cmd/builtin/fsck.c
t/t2816-fsck-cmd.t

before getting into some meatier changes, a PR with just the cleanups (since it's a lot of LOC changes).

flux-fsck: misc cleanup

---

NEWS.md

Problem: There are no release notes for v0.79.0.
Add them.

NEWS.md: add release notes for v0.79.0
