flux-framework/flux-core

- src/bindings/python/flux/rpc.py
- t/python/t0001-handle.py
Prevents early GC of `Flux` handles by tying the lifetime of a `Flux` object used to create an `RPC` to the `RPC` lifetime.
Closes #2045
> python: prevent early garbage collection of flux handles

- .travis.yml
- configure.ac
- src/cmd/builtin/hwloc.c
- src/modules/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/sched-simple/Makefile.am
- src/modules/sched-simple/libjj.c
- src/modules/sched-simple/libjj.h
- src/modules/sched-simple/rlist.c
- src/modules/sched-simple/rlist.h
- src/modules/sched-simple/rnode.c
- src/modules/sched-simple/rnode.h
- src/modules/sched-simple/sched.c
- src/modules/sched-simple/test/rlist-query.c
- src/modules/sched-simple/test/rlist.c
- src/modules/sched-simple/test/rnode.c
- t/Makefile.am
- t/sched-simple/jj-reader.c
- t/t0022-jj-reader.t
- t/t2005-hwloc-basic.t
- t/t2300-sched-simple.t
Putting this draft PR up mainly to synchronize with #2031 and proffer a simple (embarrassingly so) scheduler for flux-core, to be used for experimentation and testing of the job-manager/scheduler interface, as well an in-tree testing target and possible vehicle for simulated execution and other upcoming sprints.
This scheduler (really a node/core allocator) just maintains a list of nodes an free cores, generated from the `resource.hwloc.by_rank` object, and attempts to allocate to the current job based on a simple strategies (allocate from "most available" node by default).
I can put more detail up a bit later, but wanted to get the initial PR up in case @garlick (or anyone else) wanted to give early feedback.
In case I have to defend myself, we did say we wanted a simple allocator …
> add simple fcfs node and core scheduler

- t/t2300-sched-simple.t
A bug crept in to the new timeout support for `t2300-sched-simple.t` -- I accidentally used `date +%S` instead of `date +%s`. This makes the test very unreliable if seconds roll over, so fix the test.
Unfortunately failed tests didn't start cropping up until after my PR was merged - sorry!
> fix typo in sharness test for sched-simple

- src/cmd/flux-job.c
- src/common/libjob/job.h
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/alloc.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/test/job.c
- src/modules/job-manager/test/list.c
- src/modules/job-manager/test/queue.c
- t/ingest/submitbench.c
- t/t2201-job-cmd.t
- t/t2203-job-manager-dummysched.t
This PR adds a debug flag to the submission API, and a `--debug` option to `flux job submit` as proposed in #2033.
This causes the job manager to emit some "extra" events that are not justified for every job but which might be useful to provide context when debugging. For now, it just adds `alloc-request` and `free-request` debug events indicating that the `sched.alloc` or `sched.free`  request has been _sent_.  Normally events are only logged when the response is received.
The sharness test with the dummy scheduler is modified to verify that these events are added as expected for sched mode=single.
This scheme may be too simple, but perhaps its a reasonable first step?
> job-manager: add job submit debug flag

- doc/man3/flux_kvs_eventlog_create.adoc
- src/cmd/flux-kvs.c
- src/common/libkvs/kvs_eventlog.c
- src/common/libkvs/kvs_eventlog.h
- src/common/libkvs/test/kvs_eventlog.c
With addition of FLUX_KVS_WATCH_APPEND, the flux_kvs_eventlog_update()
function is no longer needed.
Internally adjust flux_kvs_eventlog_append() to be able to handle more than
a single event append.
Update documentation and unit tests appropriately.
Update callers in flux-kvs.
> common/libkvs: Remove flux_kvs_eventlog_update()

- doc/man3/Makefile.am
- doc/man3/idset_create.adoc
- src/common/libidset/idset.c
- src/common/libidset/idset.h
- src/common/libidset/idset_private.h
- src/common/libidset/test/idset.c
- src/modules/sched-simple/rlist.c
As a sanity check I was running a test workload to exercise the ingest->job-manager<->scheduler logic, and while doing some profiling I noticed the workload was spending 10% of the total CPU cycles in `vebsucc()`. As it turns out `sched-simple` is a heavy user of `idset_count(3)` (to sort nodes by least or most available), and currently that function needs to traverse the entire vEB tree for every call.
This PR adds a `count` member to `struct idset` and keeps the counted updated with `idset_set` and `idset_clear` calls.
This small change had a large improvement, so at the risk of premature optimization, I went ahead and proposed it here.
On current master, a set of 4K 1 core jobs submitted to a instance with 4K cores across 128 nodes shows
```
sched-bench: starting test with 4096 jobs. …
```
> libidset: add idset_equal(3), improve efficiency of idset_count(3)

- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job.h
- src/modules/job-manager/priority.c
- src/modules/job-manager/priority.h
- src/modules/job-manager/raise.c
- src/modules/job-manager/raise.h
- src/modules/job-manager/test/job.c
- src/modules/job-manager/test/util.c
- src/modules/job-manager/util.c
- src/modules/job-manager/util.h
- t/t2202-job-manager.t
This removes some duplicated code in the job manager for appending to a job's eventlog, replacing it with a more sophisticated mechanism to batch KVS eventlog updates that occur close together in time.
Logic is added to ensure that any in-flight commits are finalized (and callbacks invoked, if any) if the job manager module is unloaded while busy, thus ensuring no data is lost from KVS job records.
> job-manager: combine coincident eventlog updates into single KVS commit

- src/modules/kvs-watch/kvs-watch.c
Ignore root sequences <= to the initial root sequence number, not
just < it.
Fixes #2063
> modules/kvs-watch: Fix consistency error

- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/priority.c
- src/modules/job-manager/raise.c
- src/modules/job-manager/raise.h
- src/modules/job-manager/restart.c
- src/modules/job-manager/restart.h
- src/modules/job-manager/submit.c
- src/modules/job-manager/submit.h
- src/modules/job-manager/test/job.c
- src/modules/job-manager/test/list.c
- src/modules/job-manager/test/queue.c
- src/modules/job-manager/test/submit.c
- t/t2202-job-manager.t
This PR is a refactoring of the job manager to put all of the job state machine logic in `event.c` rather than sprinkling it all around.  Hopefully this will make it easier to understand and modify.  Parts of the system like the request handlers, and handlers for alloc/free responses now simply log events, and the event now is not only committed to the KVS, but also drives a state machine update, which in turn initiates new actions.
One other change that wasn't strictly required:  The priority and "raise" RPC's now respond to the user before the event has been committed to the KVS.  This was to simplify some code that seemed gratuitously complex to me as I was refactoring.  However it caused a race in the `t2202-job-manager.t` test, which then had to be addressed by borrowing a clever …
> job-manager: centralize job state machine

- configure.ac
- etc/rc1
- etc/rc3
- src/cmd/flux-job.c
- src/cmd/flux-kvs.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/Makefile.am
- src/modules/job-info/Makefile.am
- src/modules/job-info/job-info.c
- t/Makefile.am
- t/rc/rc1-job
- t/rc/rc3-job
- t/t2200-job-ingest.t
- t/t2202-job-manager.t
- t/t2203-job-manager-dummysched.t
- t/t2204-job-info.t
- t/t2300-sched-simple.t
After several WIPs (#2066, #2065), I think this PR is a candidate for merger.
At this moment, the module only supports getting/watching eventlog entries by jobid.  Included are two new job subcommands, `flux job eventlog` and `flux job wait-event`.  They do about what you think they would do.
Adjusted tests that previously used `flux kvs eventlog get` to use new subcommands, removing the need to do `flux job id` commands to get paths.  `flux job wait-event` conveniently removes a big function in `t2300-sched-simple.t` that emulated the same exact thing (Edit: after rebase, also in t2202-job-manager.t`).
I had begun to add a proxy to ensure guest access to the eventlog was possible, but when I tried to add tests, it wasn't clear to me how one submits a job as a guest user, or if I have to …
> modules/job-info: New module

- src/modules/job-ingest/schemas/jobspec.jsonschema
- t/jobspec/minimal-schema.json
- t/jobspec/valid/attributes_system.yaml
- t/jobspec/valid/attributes_user.yaml
- t/t2200-job-ingest.t
This relaxes the requirement that jobspec user and system attributes must be of type string.  They can be anything with this change.
Adds a couple of valid yaml inputs that demonstrate this.
Also fixes a bug in the ingest sharness test that would mask ingest failures of valid jobspec.
Finally, makes the same change to `minimal-schema.json` in anticipation of adding the ability to set arbitrary attributes to `flux jobspec`.
A corresponding change (or is it a clarification?) to RFC 14 is proposed in flux-framework/rfc#172
> jobspec: allow non-string attributes

- src/modules/job-info/job-info.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/event.c
- src/modules/job-manager/restart.c
- src/modules/job-manager/submit.c
- src/modules/job-manager/util.c
- src/modules/job-manager/util.h
- t/t2204-job-info.t
A few misc fixes I fixed along the way while working on #2076.  The most notable one is requiring that all submit events in the eventlog must contain userid, priority, and flags.  Faking a dummy submit even is no longer allowed.
> job: misc fixes

- src/cmd/flux-ping.c
- t/t0007-ping.t
Problem: flux-ping exits indicating success even when
it receives an obviously fatal failure response,
such as ENOSYS.
Just have ping call err_exit() upon receiving any
kind of error response.
Update sharness ping test.
Fixes #2087
> cmd/flux-ping: exit(1) immediately on error

- configure.ac
- etc/rc1
- etc/rc3
- src/bindings/lua/flux-lua.c
- src/cmd/flux-jobspec
- src/modules/Makefile.am
- src/modules/job-exec/Makefile.am
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/rset.c
- src/modules/job-exec/rset.h
- src/modules/job-exec/test/rset.c
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job.h
- src/modules/job-manager/start.c
- src/modules/job-manager/start.h
- src/modules/job-manager/test/job.c
- src/test/Makefile.am
- src/test/sched-bench.sh
- t/Makefile.am
- t/job-manager/exec-service.lua
- t/t2203-job-manager-dummysched.t
- t/t2400-job-exec-test.t
- t/t2401-job-exec-hello.t
- t/valgrind/workload.d/job
This is an early draft PR that implements the exec rpc protocol in the job-manager (by @garlick) along with a prototype job-exec module which implements that protocol and simulates execution of jobs by sleeping for the duration specified in the jobspec (or a default duration)
I will let @garlick follow up with a detailed description of the implemented exec protocol.
Other things of note included in this PR:
- `flux jobspec srun` now converts any Slurm timeout given into a duration string (floating point seconds with optional `s,m,h,d` suffix.
- `t5000-valgrind.t` now runs with `sched-simple` and `job-exec` loaded, and includes synchronization at the end using `flux job wait-event`
- I've cleaned up and added the simple `sched-bench.sh` test into `src/test/scripts` which can be used to …
> implement exec protocol in job-manager, add prototype job-exec service

- doc/man3/flux_future_get.adoc
- src/cmd/flux-job.c
- src/common/libflux/future.c
- src/common/libflux/test/future.c
- src/common/libflux/test/rpc.c
- t/ingest/submitbench.c
Per discussion in #2075 and updated usage where I felt it could be updated.  Note that I did re-order logic of some error output, but I don't believe it's an issue.
@SteVwonder given your comment in #2075 I thought the python `check_future_error` should be tweaked, but it ended up breaking a test when I changed it.  The function `flux_future_wait_for()` will simply return -1 and ETIMEDOUT if you pass in a timeout of 0.  So in that particular case, the future is never fulfilled with an error.  So keeping `if errmsg is None` is still necessary.
> flux_future_error_string: return optional error string or strerror of errnum

- doc/man3/flux_future_and_then.adoc
- src/common/libflux/composite_future.c
- src/common/libflux/future.h
- src/common/libflux/test/composite_future.c
- src/common/libflux/test/rpc_chained.c
- src/common/libkvs/kvs_copy.c
- src/modules/job-exec/job-exec.c
Add error string parameter to flux_future_continue_error() so an
optional error string an be set on the future.
Update callers appropriately and add unit tests.
Fixes #2079
> libflux: Add error string to continue error

- src/broker/broker.c
- src/broker/heartbeat.c
- src/broker/hello.c
- src/broker/runlevel.c
- src/broker/test/heartbeat.c
- src/cmd/builtin/hwloc.c
- src/cmd/flux-aggregate.c
- src/cmd/flux-job.c
- src/cmd/flux-ping.c
- src/cmd/flux-start.c
- src/common/Makefile.am
- src/common/liboptparse/optparse.c
- src/common/liboptparse/optparse.h
- src/common/liboptparse/test/optparse.c
- src/common/libutil/Makefile.am
- src/common/libutil/fsd.c
- src/common/libutil/fsd.h
- src/common/libutil/test/fsd.c
- src/modules/cron/cron.c
- src/modules/job-exec/job-exec.c
This PR adds a libutil function to parse the proposed RFC 23 Flux Standard Duration, and uses that function to add an`optparse_get_duration()` call. Several commands using `optparse_get_double()` were update to `optparse_get_duration()` to allow them to take duration strings with `s,m,h,d` suffixes.
At the same time, all uses of jobspec duration were updated to take duration as a strict float number of seconds as proposed in flux-framework/rfc#177. Unfortunately, this had to go in as one big commit since everything depends on everything else.
In retrospect perhaps the jobspec duration should be a separate PR, but first people could comment on the change. It is best to get this done now, since making the change in the future will likely be more work.
> libutil: add fsd_parse_duration(), support standard duration string in some utilities

- src/cmd/flux-jobspec
- src/modules/job-exec/job-exec.c
- src/modules/job-ingest/schemas/jobspec.jsonschema
- t/jobspec/emit-jobspec.py
- t/jobspec/invalid/attributes_bad_entry.yaml
- t/jobspec/minimal-schema.json
- t/jobspec/valid/example1.yaml
- t/jobspec/valid/example2.yaml
- t/jobspec/valid/use_case_1.1.yaml
- t/jobspec/valid/use_case_1.2.yaml
- t/jobspec/valid/use_case_1.3.yaml
- t/jobspec/valid/use_case_1.4.yaml
- t/jobspec/valid/use_case_1.5.yaml
- t/jobspec/valid/use_case_1.6.yaml
- t/jobspec/valid/use_case_1.7.yaml
- t/jobspec/valid/use_case_2.1.yaml
- t/jobspec/valid/use_case_2.2.yaml
- t/jobspec/valid/use_case_2.3.yaml
- t/jobspec/valid/use_case_2.4.yaml
- t/jobspec/valid/use_case_2.5.yaml
- t/jobspec/valid/use_case_2.6.yaml
- t/t2400-job-exec-test.t
As mentioned in #2095, make jobspec and minimal jobspec `attributes.system.duration` into a strict number of seconds, instead of an arbitrary string.
Updates all the tests, parsers, schemas and modules. Unfortunately, this had to be done in one big commit.
This should be merged after #2095.
> jobspec: make attributes.system.duration a number of seconds

- src/common/libflux/composite_future.c
- src/common/libflux/test/composite_future.c
This is something I ran across in the `job-exec` module, when building `flux_future_and_then` chains of composite futures.
Currently, composite "wait all" and "wait any" futures are fulfilled with success as soon as all or any of their child futures are fulfilled, whether with success or failure. This makes it challenging to use `and_then` chains, which are supposed to break immediately (propagate the error) when an intermediate future is fulfilled with error.
This PR just sets up the check for composite future fulfillment to propagate any error from the children to the "parent". To see the exact error or more detail, the user should still iterate over child futures (e.g. to see which future or futures were fulfilled with error)
> libflux/composite_future: propagate child errors to parent

- .travis.yml
- configure.ac
- doc/man3/Makefile.am
- t/Makefile.am
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t2401-job-exec-hello.t
This is an assortment of build/test bug fixes for things @grondo and I stumbled over this morning.
There is also a bit of gratuitous cleanup in `t/Makefile.am` to avoid listing test scripts twice.
> build/test: fix asciidoc build in travis and run_timeout() macro + misc test fixes

- src/cmd/flux-job.c
- src/modules/job-exec/job-exec.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/drain.c
- src/modules/job-manager/drain.h
- src/modules/job-manager/event.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/queue.c
- src/modules/job-manager/queue.h
- src/modules/job-manager/submit.c
- src/modules/job-manager/submit.h
- t/Makefile.am
- t/job-manager/drain-cancel.py
- t/job-manager/drain-undrain.py
- t/t2202-job-manager.t
- t/valgrind/workload.d/job
Add a "drain" method to the job manager which 1) shuts off new job submissions, then 2) waits for the queue size to reach zero.  This supports the use case of an initial program that submits some jobs and exits as soon as they are all transitioned to INACTIVE.
Add a corresponding command `flux job drain [--timeout SECONDS]` which uses the drain RPC.  No API wrapper as yet - not sure if there will be a need?  (Easy to add if needed).
This was described in #2044.  I did make two changes from that description:
* `flux job drain --timeout N` was implemented with `flux_future_wait_for()`, not built in to the protocol.
* Multiple waiters are allowed.
> add flux job drain

- src/modules/job-info/job-info.c
- t/Makefile.am
- t/t2205-job-info-security.t
Per discussion i #2041.  I know it's not much, but wanted to get the structure of this in as well as the tests.  The tests fake job submission under a guest account for the time being.
Nice chunk of code lifted from @garlick's branch in https://github.com/garlick/flux-core/tree/flux_job_eventlog
> job-info: Add guest access to eventlogs

- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/priority.c
- src/modules/job-manager/raise.c
- src/modules/job-manager/start.c
- src/modules/job-manager/submit.c
- src/modules/job-manager/test/job.c
- src/test/sched-bench.sh
- t/Makefile.am
- t/job-manager/bulk-state.py
- t/t2205-job-info-security.t
- t/t2206-job-manager-bulk-state.t
As discussed in #2094, this PR adds a simple notification mechanism for bulk job state transitions based on published event messages.  This is just the job-manager end.  The events could be consumed by subscribing to `job-state` and interpreting each message (see below).  I would expect the simulator front end to be the first customer of this feature.
Eventually we may want to put a nicer interface in front of this, but I think that could be a separate PR and will require some more design (and maybe some experience using the raw event interface first?)
Each job state transition is represented as a [jobid,state] tuple, and is batched up in array form for publication after the event that triggered the state transition has landed in the KVS.  Each published message can included state …
> job-manager: add job state transition announcements

- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-info/lookup.c
- t/t2204-job-info.t
- t/t2205-job-info-security.t
part 2 peeled off from #2107.  This supports reading more than just the eventlog via the `job-info` module.  The bulk read isn't in this PR.  This adds the `flux job info` command.  There some extra cleanup in this PR at the end.
> job-info: Allow reading more than eventlog

- src/cmd/flux-job.c
- src/common/libjob/test/job.c
- src/modules/job-info/lookup.c
- t/t2204-job-info.t
- t/t2205-job-info-security.t
- t/valgrind/workload.d/job
This last PR from #2107 supports reading multiple information from a job in bulk via a single RPC.  It at first does two RPCs, a guest access check & then information retrieval.  Then later commits collapse both RPCs into a single composite RPC.
In addition, some cleanup in `libjob` tests.  Also added `job info` call to valgrind test.
> job-info: read job data in bulk

- doc/man1/flux-start.adoc
- doc/man7/flux-broker-attributes.adoc
- doc/test/spell.en.pws
- etc/flux.service.in
- src/broker/broker.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/cmd/flux-start.c
- t/t0001-basic.t
This should be considered an experimental PR for now, because some of the design choices made here need some thought and agreement.
This PR changes the current `broker.rundir` attribute into a "global" `rundir` attribute which, as before, is designed to be overridden on the command line. If not set, a temporary path is chosen with `mkdtemp(3)` as before, and in either case the directory is created (and subsequently cleaned up at exit) if it doesn't exist.
The `broker.rundir` attribute is now always derived from `rundir` as `${rundir}/<rank>` to seamlessly allow multiple brokers per node in either of the `rundir` situations (random directory vs preset directory).
After this change, `flux-start` no longer needs to set a different `broker.rundir` per broker it is launching (for the `--size` …
> experimental: add global rundir from which broker.rundir is derived

- src/cmd/flux-kvs.c
- src/common/libkvs/test/kvs_eventlog.c
- t/t1008-kvs-eventlog.t
- t/t2204-job-info.t
Peeled off from #2117, just misc fixes before the bigger #2106 fixes.
> misc RFC18 fixes / cleanups / refactorings

- src/modules/barrier/barrier.c
- src/modules/job-exec/job-exec.c
- t/request/rpc.c
- t/t0002-request.t
- t/t0004-event.t
- t/t0008-attr.t
- t/t0010-generic-utils.t
- t/t0017-security.t
- t/t1007-kvs-lookup-watch.t
- t/t1101-barrier-basic.t
- t/t2200-job-ingest.t
- t/t2202-job-manager.t
- t/t2204-job-info.t
- t/t2400-job-exec-test.t
This PR adds some more tests that send a malformed request to services and make sure they get an EPROTO response.  In addition it addresses a problem with the encoding of request messages by the `t/request/rpc` test program and adds tests for that.
A couple of response handlers needed some minor tweaks to behave properly on error paths.
> testsuite: improve coverage of malformed RPC requests

- src/cmd/flux-kvs.c
- t/t1000-kvs.t
Started just wanting to fix issue #2086, and found two other issues along the way.
For issue #2129 (fix issues unlinking symlinks), the `unlink_safety_check()` function was a little tricky to begin with, so I re-worked the whole function do the check based on the lookup
of a `TREEOBJ`, hopefully minimizing the number of KVS lookups that have to be done to do an `unlink_safety_check()`.
> flux-kvs: misc fixes

- src/cmd/flux-job.c
- src/common/libeventlog/test/eventlog.c
- t/t2202-job-manager.t
- t/t2204-job-info.t
As discussed in #2083, it would be useful for `flux job wait-event` to wait not just for an event but for some condition in the context.  As an initial step, add the ability for the user to specify an optional `key=val` to check in the context too.
Initial feature supports only one `key=val` input, it could be > 1, but didn't see a need for > 1 at the moment.
On the way, reverted a behavior change from #2085 where strings output from contexts were quoted (i.e. `data="foo"` instead of `data=foo`).  Users would have to be mindful of quoting strings in contexts, which I think is confusing.  So I decided to remove those quotations everywhere.
> flux-job: Add context test in wait-event

- doc/man3/flux_kvs_lookup.adoc
- doc/test/spell.en.pws
Per #2012 , add `FLUX_KVS_WAITCREATE`, reorganized & added some text to make it more clear how `flux_kvs_lookup_cancel()` should be used.
> flux_kvs_lookup: Documentation fixes

- doc/man1/flux-kvs.adoc
- src/cmd/flux-job.c
- src/cmd/flux-kvs.c
- t/t2204-job-info.t
As discussed in #2074, it'd be nice to format job eventlog entry timestamps.
- Support a new `--time-format` option in `flux-job` that takes `raw`, `iso`, and `offset` as inputs.  Outputting floating point value, ISO8601, or offset from 0.0 (for the first entry).
- I considered making `flux-job eventlog` and `flux-kvs eventlog get` consistent with each other (both have `--format` and `--time-format` options), but my gut told me that `flux kvs eventlog get` doesn't have to support all of the "pretty" options that `flux-job` does. The `flux kvs` option is more for debugging/testing?
So I elected to have `flux kvs eventlog get` just output timestamps in floating point and that's it.
Obviously we can do differently, dunno what people's opinions are.
> flux-job: Add --time-format option

- doc/man3/flux_future_and_then.adoc
- doc/man3/flux_future_create.adoc
- src/common/libflux/composite_future.c
- src/common/libflux/future.c
- src/common/libflux/future.h
- src/common/libflux/test/composite_future.c
- src/common/libflux/test/future.c
This PR fixes #2127 by adding a new function `flux_future_fulfill_with(3)`, which allows a fulfilled future to be used to fulfill another future. This is what `fulfill_next()` in `composite_future.c` tried to do, but its scope was limited because it didn't have access to `flux_future_t` internals.
`flux_future_fulfill_with(3)` copies any fatal error, error result, or normal result into the destination future. It also "embeds" the source future into the target future, so that calls to `flux_future_aux_get()` can access the source future aux list. This allows futures that are a result of calls which use aux data as part of custom `get()` methods to work after `flux_future_fulfill_with(3)`.  This function steals a reference to the source future, so `flux_future_destroy()` should not be …
> Allow flux_future_continue(3) to work with flux_kvs_lookup(3)

- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/common/libschedutil/alloc.c
- src/common/libschedutil/hello.c
- src/common/libschedutil/ops.c
- src/modules/job-exec/job-exec.c
- src/modules/job-info/lookup.c
- src/modules/job-info/watch.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/event.c
- src/modules/job-manager/restart.c
- t/t2200-job-ingest.t
- t/t2201-job-cmd.t
- t/t2204-job-info.t
- t/t2205-job-info-security.t
- t/t2300-sched-simple.t
- t/t2400-job-exec-test.t
As discussed in #2107 and #2093, remove the `job.active` and `job.inactive` directories, instead putting all job information simply in the `job` directory.
This is first step towards more work.  Future work to archive inactive jobs TBD.
> Remove job.active/inactive directory

- src/broker/runlevel.c
- src/cmd/builtin/proxy.c
- src/cmd/flux-start.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/subprocess.c
WIP for #2008 .  Ignore most of this code & commits, which are garbage and I haven't even tested really.  Mostly posting this to get initial thoughts on the API in `subprocess.h`.  After going back and forth on a few ideas, I think this is not bad, but there's one hairy issue which I detail below.
```C
typedef enum {
FLUX_SUBPROCESS_HOOK_TYPE_PRE_EXEC,
FLUX_SUBPROCESS_HOOK_TYPE_POST_FORK,
} flux_subprocess_hook_type_t;
flux_subprocess_hooks_t * flux_subprocess_hooks_create (void);
flux_subprocess_hooks_t * flux_subprocess_hooks_copy (
const flux_subprocess_hooks_t *hooks);
void flux_subprocess_hooks_destroy (flux_subprocess_hooks_t *hooks);
int flux_subprocess_hooks_add (flux_subprocess_hooks_t *hooks,
flux_subprocess_hook_type_t type,
flux_subprocess_f cb);
```
```
@@ -246,11 +288,13 @@ …
```
> libsubprocess: pre-exec & post-fork hooks

- doc/man3/flux_future_get.adoc
- src/cmd/flux-job.c
- src/common/libflux/future.c
- src/common/libflux/future.h
- src/common/libflux/test/future.c
- src/common/libjob/job.c
- src/modules/job-ingest/job-ingest.c
- t/ingest/submitbench.c
Per discussion in #2160
- `flux_future_error_string()` now returns NULL if the future passed in is NULL, not fulfilled, or fulfilled with a non-error result.  The last one was not discussed in the issue, but after making changes, it no longer felt right that `flux_future_error_string()` return "Success" on a future fulfilled with a normal result.  We can debate on this.
- Added a `flux_future_has_error()`.
- Added `FLUX_FUTURE_STRERROR()`, which wraps a call to `flux_future_has_error()` and calls `flux_future_error_string()` or `flux_strerror (errno)` accordingly.
- Use `FLUX_FUTURE_STRERROR()` in code, most notably in `flux-job`.
> libflux: Fix how flux_future_error_string() obscures errors

- src/cmd/flux-exec.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
- src/modules/cron/task.c
- src/modules/job-ingest/worker.c
- t/t0005-rexec.t
Remove the "Started" state, which serves little purpose, especially
after the addition of pre-exec and post-fork hooks.
Update all uses of the Started state outside of libsubprocess.
Fixes #2154
> libsubprocess: Remove STARTED state

- src/broker/broker.c
- src/broker/exec.c
- src/broker/exec.h
- src/broker/shutdown.c
- src/broker/shutdown.h
- src/broker/test/shutdown.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/server.h
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/subprocess.c
This PR fixes up a long standing issue.  Any leftover subprocesses that are lingering when a broker is shutdown are killed via SIGKILL.  This fix will send a SIGTERM before hand, to give subprocesses some time to exit cleanly.  Accomplished by:
- adding `flux_subprocess_server_subprocesses_kill()` which allows a caller to send a signal to all subprocesses on a server, then waits some amount of time to see if all subprocesses have exited.
- calling this in the broker and sending SIGTERM.
- in addition, I elected to send SIGKILL to all lingering subprocesses BEFORE the shutdown of the broker begins.  I think this is safer than letting any lingering subprocesses possibly continue running as we begin to shutdown the broker (i.e. unload modules, etc.).
- For the time being, I hard coded a 5 …
> broker / libsubprocess : SIGTERM lingering subprocesses before shutting down broker

- src/common/libflux/test/reactor.c
This PR fixes issue #997, test failure was due to race in test.  The stat watcher test performs a append & unlink and wants the stat watcher to detect both changes.  However, the append + unlink can occur in between polling loops of the stat watcher, thus the append can be missed.  The solution was to add a state variable that would not unlink the file until the stat watcher noticed the file size change from the append.
This PR also reverts 7a319e36719991898a3373c74f3ef9e06b13b33d, which
temporarily disabled the test due to it failing so much.
Ran through travis several times before fix and hit the issue many times.  After the fix, ran through travis 3 times and never hit the problem again.
> libflux/test: Fix race in stat watcher test

- src/broker/attr.c
- src/broker/attr.h
- src/broker/broker.c
- src/broker/heartbeat.c
- src/broker/hello.c
- src/broker/module.c
- src/broker/overlay.c
- src/broker/publisher.c
- src/broker/runlevel.c
- src/broker/shutdown.c
- src/broker/shutdown.h
- src/broker/test/shutdown.c
While looking at #1036, fixed up a bunch of tiny issues I saw.  Also refactored a few things for consistency.  Note that some of these might eventually lead to more cleanup / refactoring (i.e. some type of `ctx_init()` type of the function), but I'll leave that for another day.  I thought this was a good stopping point of cleanups.
> broker: misc cleanup / refactoring

- src/broker/content-cache.c
Asserts added in
f8521c0ca734f3417cadeaa0ee1871fcbb81297c
were added to check that cache entry removal during normal
operations (e.g. dropcache) was handled correctly.  However, the
asserts are also checked during broker teardown, which may not
care about normal operations at that point.  This can lead to
an unexpected assert / core dump.
To solve this, move the asserts from cache_entry_destroy() to
remove_entry(), so the asserts are only checked during normal
cache entry removal operations.
Fixes #1267
> broker: Fix invalid assert in content-cache destroy

- src/cmd/Makefile.am
- src/cmd/flux-job.c
- src/cmd/flux-srun
- t/Makefile.am
- t/t0002-request.t
- t/t0003-module.t
- t/t0005-exec.t
- t/t0009-dmesg.t
- t/t0012-content-sqlite.t
- t/t0013-config-file.t
- t/t1103-apidisconnect.t
- t/t2008-althash.t
- t/t2201-job-cmd.t
- t/t2202-job-manager.t
- t/t2400-job-exec-test.t
- t/t2500-job-attach.t
This is probably wrong.
Recall the idea for `flux srun` is to provide a simple run command that can be backported to the 0.11 series and provide a stable porting target across 0.11 -> 0.12, and take a little pressure off of having a complete porcelain run command right off in 0.12.
I added a `--wait` option to `flux job submit` so that the command will pause until the job reaches INACTIVE state, exiting with the highest exit code of the job shells, or 1 if the job was terminated by an exception.
Then I added the worlds simplest shell script that just called `flux jobspec srun $* | flux job submit --wait`.
I kind of think it would be better to do this as a python script that generates the jobspec (replicating some of what's in `flux jobspec` and then starts `flux job submit` as a …
> add flux-srun

- src/broker/Makefile.am
- src/cmd/Makefile.am
- src/cmd/flux-start.c
- src/common/Makefile.am
- src/common/libpmi/Makefile.am
- src/common/libpmi/simple_server.c
- src/common/libpmi/simple_server.h
- src/common/libpmi/test/server_thread.c
- src/common/libpmi/test/simple.c
The "server" end of the PMI-1 code in libpmi was pretty crufty, lacked documentation, and was sparse on tests.
This PR implements a little refactoring that hopefully makes it clearer, and adds tests for code that wasn't being exercised.
It also removes the server code from the installed `libpmi.so.0.0.0` because it was causing that library to have dependencies on zeromq and other libs.  (I don't know if this is really a problem, but since it was unnecessary and I did go to some trouble early on to make the library standalone, I went ahead and fixed it).
> libpmi: clean up simple server wire protocol code

- src/broker/broker.c
- src/broker/exec.c
- src/broker/heartbeat.c
- src/broker/heartbeat.h
- src/broker/modservice.c
- src/broker/module.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/shutdown.c
- src/broker/shutdown.h
In #1036, it was discovered that an assert can occur inside `zmq` b/c the broker calls `exit()` without doing some proper cleanup.
Generally speaking, I re-worked part of the overlay and broker to not call `log_err_exit()` and instead go through the cleanup path of the broker.
There are still a lot of `log_err_exit()` calls I got to remove, but wanted to throw up this PR for now to see if there are any comments.
> broker: go through main cleanup path, do not call log_err_exit()

- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/broker.c
- src/broker/heartbeat.c
- src/broker/heartbeat.h
- src/broker/modservice.c
- src/broker/modservice.h
- src/broker/module.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/runlevel.c
- src/broker/shutdown.c
- src/broker/shutdown.h
- src/broker/test/heartbeat.c
- src/broker/test/shutdown.c
While PR #2181 is still half fresh in my mind, wanted to do these small cleanups & refactorings.
Obviously, way more refactoring can be done as I've listed things in #2182, but this is more of a refactoring "setup" for bigger things later.
Mostly small changes to slowly decouple objects from each other or clarify lack of dependency between objects.
Also, removed a few more `log_err_exit()` and similar paths, forcing callers to go through the main broker cleanup path.
> broker: various cleanup + refactoring

- src/modules/sched-simple/rlist.c
- src/modules/sched-simple/test/rlist.c
This PR fixes #2202. The problem was a dumb implementation of an idset comparator internal to `sched-simple`'s `rlist` object. The `idset_cmp()` function compared non-equal idsets using `idset_count()`, but of course two idsets can have the same count but still not be equivalent.
The new implementation detects unequal idsets that have the same "count" and then falls back to comparing the first different stored integer.
This appears to fix the weirdness under Slurm with cpu-affinity:
```
$ srun --pty -N32 -n128 src/cmd/flux start
$ 
$ src/modules/sched-simple/rlist-query 
rank[2,6,10,14,18,22,26,30,34,38,42,46,50,54,58,62,66,70,74,78,82,86,90,94,98,102,106,110,114,118,122,126]/core2 rank[1,5,9,13,17,21,25,29,33,37,41,45,49,53,57,61,65,69,73,77,81,85,89,93,97,101,105,109,113,117,121,125]/cor …
```
> sched-simple: fix alloc/free for resource sets with equal size but different cpusets

- src/cmd/flux-jobspec.py
- src/modules/job-exec/Makefile.am
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/bulk-exec.h
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/test/bulk-exec.c
- src/modules/job-exec/testexec.c
- src/test/sched-bench.sh
- t/Makefile.am
- t/job-exec/dummy.sh
- t/t0021-flux-jobspec.t
- t/t2400-job-exec-test.t
- t/t2402-job-exec-dummy.t
- t/t2500-job-attach.t
This PR is still a work in progress,  but I wanted to get a PR open in its current form to ensure I'm able to address likely feedback before I go away for a bit.
This PR adds the ability of the `job-exec` service to *actually* execute job shells for a job on receipt of a `start` request from the job manager. In the current implementation, the job shell used is set from configuration (the `job-exec.job-shell` broker attribute, falling back to `/bin/true`) overridden by the `attributes.system.exec.job-shell` key of submitted jobspec.
The refactoring of the `job-exec` module to support multiple execution "implementations" did not turn out as clean as I'd hoped, and it is still a bit rough around the edges. I tried to keep nice incremental commits as I worked on the refactor, but ended up …
> job-exec: implement ability to execute job shells

- src/broker/attr.c
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/broker.c
- src/broker/content-cache.c
- src/broker/heartbeat.c
- src/broker/hello.c
- src/broker/log.c
- src/broker/modservice.c
- src/broker/module.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/runlevel.c
- src/broker/service.c
- src/broker/shutdown.c
Final cleanup/refactor before I would something big as discussed in #2182.  Can discuss if #2182 is something we want to go down the path of or if we should hold out on that work.
> broker: remove many ooms and xzmalloc/xstrdup/xasprintf calls

- src/common/libutil/fsd.c
- src/common/libutil/test/fsd.c
Adding a check to disallow zeros, NaNs and infinites in flux standard
duration format parsing in fsd.  This came up while looking into #2213.
Just to see if we actually had issues with this, I tried a broker with shutdown grace duration of `NaNs`, which hangs and has to be killed with signal 9 to die so, unlikely as this may be, may as well head it off.
This probably needs an update in the RFC as well, but thought we could work it out here first.
> check for invalid FP types in fsd

- scripts/check-format
- scripts/format
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/future.py
- src/bindings/python/flux/job.py
- src/bindings/python/flux/util.py
- src/bindings/python/flux/wrapper.py
- src/cmd/flux-jobspec.py
- t/python/t0012-futures.py
Main changes are fixing streaming RPCs, fixing `job.get_id()`, and adding a `CLIMain` decorator for uniform exception handling by CLI tools written in Python.
Minor changes include adding some methods to the Flux handle class, improve error messages, and extending the check-format/format scripts to be usable as git commit hooks.
Fixes #2155
> python: misc fixes, refactors, and additions

- .travis.yml
- src/test/docker/centos7/Dockerfile
Problem: without the valgrind-devel package, valgrind.h is not found
during configure and the valgrind test is disabled by default. When
run with -d, the t5000-valgrind.t is forced to run, but may encounter
false positives and bad stack traces due to modules that are dlclosed.
Add valgrind-devel to the centos7 docker image. (valgrind.h is part of
the base valgrind package in Ubuntu)
> docker: update centos7 image to python3.6 and add valgrind-devel

- src/cmd/flux-jobspec.py
- t/t0021-flux-jobspec.t
Add support in `flux-jobspec` for adding the current environment to generated jobspec by default. In addition, the `srun` `--export` option is supported in `flux jobspec srun`.
e.g.
* `flux jobspec srun --export=FOO`: only export variable `FOO` from current env
* `flux jobspec srun --export=FOO=bar`: explicitly export `FOO=bar`
* `flux jobspec srun --export=ALL,FOO=bar`: export all current vars and add `FOO=bar`
* `flux jobspec srun --export=NONE`: export empty environment
I think I got exception handling for `flux jobspec srun --export=NONEXISTENT` working correctly. Without the try,except block, I got a generic error like
```console
$ src/cmd/flux jobspec srun --export=SOUP hostname 
util: ERROR: 'SOUP'
```
Maybe something to look into there regarding generic exception handling in the …
> flux-jobspec: Add environment to jobspec, support srun --export option

- src/common/libschedutil/hello.c
- src/common/libschedutil/hello.h
- src/modules/job-manager/alloc.c
- src/modules/sched-simple/sched.c
- t/job-manager/sched-dummy.c
- t/t2203-job-manager-dummysched.t
Per discussion in flux-framework/flux-sched#493.
The  job-manger - scheduler "hello" handshake supports scheduler state recovery.  The initial interface in libschedutil issued a callback containing only  `R` for each job that has resources allocated.  Internally the job manager returned an array of job ID's, which libschedutil used to look up corresponding `R` values in the KVS.
In addition to simply marking resources allocated, flux-sched wants to reconstruct queue entries for running jobs, so it needs the same metadata that was passed in with the alloc request.  This is low overhead since the data is part of the active job record that job-manager keeps in memory.  This PR extends the hello handshake to send an array of "job objects" instead of an array of job ID's.  The job object …
> libschedutil: extend hello protocol

- src/common/libsubprocess/local.c
- t/t0005-rexec.t
As discussed in #2211 and #2228, there was an invalid EOF calculation / assumption in local processes in `libsubprocess`.
Unfortunately, I have been unable to create a reproducer that works solely against the `libsubprocess` library.  I can't seem to find that magic combination that makes this trigger regularly.
Perhaps the reproducer with `flux-shell` in #2211 could be added as an additional test in that PR or a later PR (which I can add after #2211 is merged or I can try and add one on that branch).
Also fixed something stupid I found in `t/t0005-rexec.t`.
> libsubprocess: Remove invalid EOF calculation

- src/shell/Makefile.am
- src/shell/info.c
- src/shell/info.h
- src/shell/io.c
- src/shell/pmi.c
- src/shell/pmi.h
- src/shell/rcalc.c
- src/shell/shell.c
- src/shell/shell.h
This PR addresses #2237.
I apologize in advance because this will be a difficult PR to review. I attempt to make a minor advance by adding a `struct flux_shell` structure to contain the independing `io` `info` and `pmi` structures used by the various components of the shell, but ended up making more changes than I wanted. Perhaps with the luxury of more time, this PR could be made cleaner, but hopefully after some rounds of feedback this approach could be acceptable.
As noted above, this branch adds a new `struct flux_shell` structure as container for the most of the other structures used by the shell. This structure can then be passed to callbacks that may require access to multiple shell components and data, without requiring those callers to use custom structures or push multiple …
> job shell: add flux_shell_t and completion references

- src/common/libflux/ev_buffer_read.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
This is a cleaned up version of #2245 which is cleaned up/merge-able.  It is a temporary solution to #2239 until that can be completed and should allow #2246 to be merged in.
I'll let it be @garlick's decision if he wishes to cherry pick this into his branch or if should be merged into master via this PR.
> libsubprocess: Add new EOF reached function

- src/cmd/flux-job.c
- src/common/libflux/rpc.c
- src/common/libflux/rpc.h
- src/modules/job-exec/exec.c
- src/shell/Makefile.am
- src/shell/info.c
- src/shell/io.c
- src/shell/io.h
- src/shell/shell.c
- src/shell/shell.h
- src/shell/svc.c
- src/shell/svc.h
- src/shell/task.c
- src/shell/task.h
- t/Makefile.am
- t/shell/lptest.c
- t/t2500-job-attach.t
- t/t2601-job-shell-standalone.t
- t/t2602-job-shell.t
- t/t3000-mpi-basic.t
- t/valgrind/workload.d/job
- t/valgrind/workload.d/job-cancel
- t/valgrind/workload.d/job-info
This PR adds the most basic output handling to the shell as proposed in #2190.
Task I/O is sent to a service on the leader shell (shell rank 0).  Each line of I/O is represented as a JSON object.  The lines are accumulated in a JSON array which is committed to the job's kvs guest namespace upon completion.
.
Flux attach then outputs the lines on its stdout and stderr.
Thus
```
$ flux srun -N4 -n8 printenv FLUX_TASK_RANK
0
1
2
4
5
3
6
7
```
or
```
flux job attach --label $(flux jobspec srun -n4 hostname | flux job submit)
2: morbo
1: morbo
0: morbo
3: morbo
```
A reusable I/O forwarding service library has been proposed in #2208.  This PRwas  worked on in parallel with that, so I will look at converting the quick and dirty "service" in here over to that (this one, for example, doesn't …
> flux-shell: add output handling

- src/cmd/flux-exec.c
- t/t0005-exec.t
Fix bug in which stdin was not forwarded if the user specified less
than the number of ranks available in the flux instance (i.e. less
than flux_get_size() ranks).
Add new tests appropriately.
Fixes #2247
> cmd/flux-exec: Fix stdin forwarding bug

- src/common/libsubprocess/Makefile.am
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
- src/common/libsubprocess/test/test_multi_echo.c
- src/common/libsubprocess/util.c
- src/common/libsubprocess/util.h
- src/modules/job-exec/bulk-exec.c
- t/Makefile.am
- t/rexec/rexec_count_stdout.c
- t/t0005-rexec.t
To limit callbacks to the `on_stdout` and `on_stderr` callbacks, support the ability to specify if stdout/stderr/channel output should be line buffered.
Originally, I made this option to "enable" line buffering.  But upon further investigation, everything in flux reads lines.  So I enabled line buffering by default, but allow it to be disabled.
Lots of stupid cleanups/fixes along the way.
> libsubprocess: Support line buffering stdout/stderr

- src/cmd/flux-job.c
Small change to `flux job attach` to use the `job.info` service rather than direct KVS access to fetch job output, since guests won't have direct KVS access.
The output handling code is just a super simple first cut that will need to be replaced anyway as we expand to cover more I/O modes (#2241), and it's not possible to write a test to verify that it works for guests since guests can run jobs yet, so the main value here is just getting implementation on track with the design so the next person modifying this code doesn't wind up wondering what's going on.
> cmd/flux-job: use job-info to obtain output in attach

- src/broker/runlevel.c
- src/cmd/flux-exec.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/subprocess.c
- src/modules/job-exec/bulk-exec.c
- src/shell/task.c
- t/Makefile.am
- t/rexec/rexec_count_stdout.c
- t/rexec/rexec_getline.c
- t/rexec/rexec_signal.c
- t/t0005-rexec.t
This PR does two things (it could be split into two PRs, but keeping it as one given #2255 thought process).
After a lot of thought on how to 1) make it easier to deal with EOF scenarios with read streams and 2) how to make it easier / more convenient for callers, in this PR:
- The `flux_subprocess_read_eof_reached()` temporary function that was introduced in PR #2254 is now "promoted" into a real library function because there are a few circumstances it is useful and the convenience function (described below) couldn't' be used.  Renamed it to `flux_subprocess_read_stream_closed()`, added header usage information, added tests.
- Added a new convenience function `flux_subprocess_read_line_until_eof()`, that will always read a line from the stream, but once EOF has been reached, it can …
> libsubprocess: rename/cleanup read_eof_reached() add flux_subprocess_read_until_eof()

- src/common/libpmi/Makefile.am
- src/common/libpmi/clique.c
- src/common/libpmi/clique.h
- src/shell/pmi.c
- t/t2601-job-shell-standalone.t
- t/t2602-job-shell.t
I forgot to populate this key, which, if present, is used by MPI to determine which procs can used shared memory to communicate because they are on the same node.
Add a helper function to libpmi, then use it in the shell's pmi implementation.
Add some tests that verify cliques work as intended for simple cases.
> flux-shell: populate PMI_process_mapping key

- src/cmd/flux-start.c
- src/modules/cron/cron.c
- t/t0001-basic.t
This PR fixes the segv in the `cron` module found by @dongahn in issue #2274.
A test for `flux-start` run from a removed directory was also added.
Finally, while `flux-start` fails gracefully with the cron module fix, there is a huge number of errors. So a check was added early to `flux-start` `main()` to exit with an error if `getcwd()` fails to evoke an early exit.
> flux-start: exit gracefully with error when getcwd() fails

- src/modules/connector-local/local.c
- t/Makefile.am
- t/issues/t2281-service-add-crash.sh
Straightforward fix and test for #2281.
> connector-local: fix crash in local service registration when client detaches

- src/broker/runlevel.c
- src/cmd/builtin/proxy.c
- src/common/libsubprocess/command.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/cmd.c
- src/modules/cron/task.c
- src/modules/job-exec/exec.c
- t/Makefile.am
- t/issues/t2284-initial-program-format-chars.sh
Rename `flux_cmd_argv_append()` to `flux_cmd_argv_appendf()` to indicate this function takes printf style arguments. The new `flux_cmd_argv_append()` takes a string argument only, which satisfies most use cases and simultaneously fixes #2284, by avoiding passing user provided string as the `fmt` arg, as these strings may contain `%` characters.
This issue could have also been fixed by simply calling
```
flux_cmd_argv_append (cmd, "%s", arg);
```
as one would do for `printf`, however it seemed important to try to avoid this confusion in the future, and perhaps the rename will help with that. (I'd be willing to redo the PR, though, if others feel different)
> broker: avoid accidentally consuming % format characters in initial program args

- src/cmd/flux-job.c
- src/common/libsubprocess/command.c
- src/common/libsubprocess/test/cmd.c
- src/shell/io.c
- src/shell/io.h
- src/shell/task.c
- src/shell/task.h
A few cleanups that I peeled off of #2271's work.
> Misc shell/libsubprocess fixes/cleanups

- src/common/libsubprocess/local.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/subprocess.c
- src/common/libsubprocess/test/test_echo.c
- src/common/libsubprocess/test/test_multi_echo.c
- src/common/libsubprocess/util.c
- src/common/libsubprocess/util.h
- t/t0005-rexec.t
Per discussion in #2235, support ability to start/stop output callbacks (most notably `on_stdout` and `on_stderr`).
- Support three new functions, `flux_subprocess_stream_start()`, `flux_subprocess_stream_stop()`, and `flux_subprocess_stream_status()`, which do what you would think they do.
- To support a stream being stopped on start of the subprocess, support a cmd option `STREAM_STOP`.
- Interesting development notes:
- I only support this on local subprocesses.  Doing it over remote subprocesses "correctly", would be difficult, doing it over remote subprocesses "ok" would not be too hard.  But talking to @garlick, this isn't needed on remote subprocesses right now, so I'm punting.
- Had to manually track if a watcher was started/stopped through flags.  If we implement something in …
> libsubprocess: Support ability to start/stop output callbacks

- src/common/libflux/buffer.c
- src/common/libflux/buffer.h
- src/common/libflux/ev_buffer_read.c
- src/common/libflux/test/buffer.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
Fixes #2287 
This PR includes the addition of `flux_buffer_has_lines()` and its use in place of `flux_buffer_lines()` as discussed in #2287.
Additionally, the "multiple callback" support for `flux_buffer_t` read callbacks was removed -- while it makes sense for standalone use, in the larger context of use by libsubprocess in a reactor, repeatedly calling the buffer callback until no more data was consumed could result in other parts of the system getting starved out by a heavily used buffer.
Since the multiple callback support was removed, I just removed the tests for that aspect of the code. Hope that was an ok approach.
Here's some timing results, before:
```console
Executing: git log --oneline -n1; make -j 12 >/dev/null 2>&1 && time src/cmd/flux start flux srun t/shell/lptest 79 10000 …
```
> increase efficiency of line buffered I/O

- configure.ac
- src/cmd/flux-job.c
- src/common/Makefile.am
- src/common/libioencode/Makefile.am
- src/common/libioencode/ioencode.c
- src/common/libioencode/ioencode.h
- src/common/libioencode/test/ioencode.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/shell/io.c
This simple convenience library encodes/decodes io into json objects.  Being the non-creative person I am, I call the library `libioencode`.  The objects encode stream, rank, data in base64, or EOF.
Cleanup was nice, to remove alot of the random calls to `libsodium` all over the place and to common-ize code between `libsubprocess` and `shell`.
Design choice: When encoding I elected to have a different object for EOF.  When decoding, you can get data or EOF, but not both.  I felt this made things simpler in `libsubprocess`, but can understand there are circumstances this is not optimal.
> libioencode: convenience library for encoding io

- src/shell/io.c
- src/shell/pmi.c
- src/shell/task.c
- src/shell/task.h
- t/t2602-job-shell.t
When tasks produce a lot of output quickly, many write requests to the leader shell can be concurrently in flight.  This PR adds a hard coded high water mark of 1000 requests per shell, with a low water mark of 100, such that I/O is paused when the high water mark is reached, and resumed when the low water mark is reached.  This utilizes the subprocess stream start/stop mechanism added in #2271.
This limits the consumption of client resources such as matchtags, and also should meter the overall message rate somewhat, although this simple mechanism is completely local to a shell and has no idea what other shells are doing, so a many-task job can still overwhelm the leader shell.  Complexity is very low so it seemed like a good first step.
Without this patch, when running an lptest 79 X, …
> flux-shell: limit the number of I/O requests in flight + cleanup

- src/modules/job-info/lookup.c
- src/modules/job-info/watch.c
I realized in the job-info eventlog watch code, I don't cancel a lookup under several circumstances, such as when the user has a permission issue.  So this could lead to a matchtag leak.  So added a lookup cancellation call in the error path of some cleanup.
Also includes some random cleanup fixes.
> job-info: Watcher - cancel lookup on several error paths

- src/broker/broker.c
- src/cmd/flux-exec.c
- src/cmd/flux-job.c
- src/common/libeventlog/eventlog.c
- src/common/libeventlog/eventlog.h
- src/common/libeventlog/test/eventlog.c
- src/common/libioencode/ioencode.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
- src/common/libsubprocess/test/test_echo.c
- src/modules/cron/task.c
- src/modules/job-exec/test/bulk-exec.c
- src/modules/job-ingest/worker.c
- src/shell/io.c
- t/rexec/rexec.c
- t/rexec/rexec_count_stdout.c
- t/rexec/rexec_getline.c
- t/t0005-rexec.t
This PR changes the format of the `guest.output` key in the KVS from a JSON array of "iodecode" objects to an RFC 24 eventlog.
This opens the door to more work such as
* "compressing" identical output that occurs within a time window down to one event
* UTF-8 encoding option
* committing output at regular intervals or upon reaching some buffer threshold
However in this PR, only the output format is changed.
> flux-shell: use RFC 24 eventlog output

- src/modules/job-exec/Makefile.am
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/bulk-exec.h
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/test/bulk-exec.c
- src/modules/sched-simple/Makefile.am
- t/t2402-job-exec-dummy.t
This PR fixes some of the issues hit by @dongahn's stress test described in #2275. It doesn't fix the race described in #2279, which requires a rework of the exception protocol.
I'm still trying to figure out exactly how to test some of these conditions, especially the one that triggers cancellation of a partially running job (pending commands are descheduled in the bulk-exec implementation). However, on this branch, the current version of the cancel stress test:
```sh
#!/bin/bash
NREPEATS=100
NJOBS=12
flux jobspec srun -n 2 hostname >j
for j in $(seq 1 ${NREPEATS}); do
t/ingest/submitbench -f 24 -r 100 j || exit 1
flux job list
flux job list | grep -v USERID | xargs -L 1 flux job cancel
echo "Iteration"
sleep 1
done
flux dmesg|grep "job-manager.err"
```
No longer reproduces the "start …
> job-exec: fix exception handling of jobs in transition states

- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-exec/job-exec.c
- t/t2201-job-cmd.t
- t/t2402-job-exec-dummy.t
As discussed #2313, this PR adds a new `flux_job_kvs_namespace(3)` function to libjob, a `flux-job namespace` command, and uses `flux_job_kvs_namespace` for naming the guest namespace for jobs. The guest namespace is now `job-<id>`.
Fixes #2306
> Add flux_job_kvs_namespace(3) and use it in job-exec for guest namespace

- src/modules/connector-local/local.c
Problem: logs fill up with client_respond() "Broken pipe"
errors when clients disconnect while connector-local is
in the process of sending messages to them.
If EPIPE occurs, call it success and let the read path
handle disconnect errors.
Fixes #2310
> connector-local: suppress EPIPE write errors

- etc/rc1.d/01-enclosing-instance
- src/broker/broker.c
- t/Makefile.am
- t/t3100-flux-in-flux.t
To assist tools that need to look up the URI for child instances, repair  `rc1.d/01-enclosing-instance` to work with the new exec system and write e.g.
```
job.0000.0029.d400.0000.guest.flux.local_uri
job.0000.0029.d400.0000.guest.flux.remote_uri
```
> rc: set URI's in enclosing instance for hierarchical flux

- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-info/Makefile.am
- src/modules/job-info/guest_watch.c
- src/modules/job-info/guest_watch.h
- src/modules/job-info/info.h
- src/modules/job-info/job-info.c
- src/modules/job-info/watch.c
- t/t2204-job-info.t
- t/t2205-job-info-security.t
As discussed in meetings and #2105, this PR will allow users to read from and watch guest event logs.
There is a new `guest_watch.c` file in the job-info module that handles the new `job-info.guest-eventlog-watch` callback.  This callback handles a number of tricky scenarios as discussed in #2105.  Effectively, `job-info.guest-eventlog-watch` is a wrapper around `job-info.lookup` and `job-info.eventlog-watch` RPCs.
Interesting notes on development:
- Supporting an alternate eventlog path to `job-info.lookup` is easy.  It already takes a path argument, so just passing in something like `guest.exec.eventlog` is easy enough.
- The original `job-info.eventlog-watch` now takes an optional path to an eventlog and a flag that indicates if the eventlog should be read from the guest namespace. …
> job-info: Support reading / waiting on guest event logs

- src/modules/job-info/guest_watch.c
Per discussion in #2331, I think there may be a race where a user attempts to cancel the watch, but as the cancellation is in flight, the namespace is deleted.  Internally job-info gets a ENOTSUP, and therefore will never send ENODATA to the caller.
Labeling WIP for now - as we'll want to run this through travis many times to see if the issue hits.
> job-info: Fix racy cancel

- src/cmd/flux-job.c
- src/shell/io.c
As discussed yesterday, this PR changes `flux job attach` to use a job-info eventlog watch instead of a job-info lookup of of the `guest.output` log.    This is a step change for when `job attach` will attach to a running job and output stdout/err as it happens.
One corner case that came up in this change is when a job never runs, (e.g. resources are impossible), this would hang `flux job attach` b/c nothing ever gets output to `guest.output`.  So we have to check to make sure the job actually ran (event "start" occurs).
One other issue that had to be solved in this change is how to determine that all output has completed.  It's easy to count EOF occurrences, but `flux job attach` needs to know how man EOF occurrences to expect.  For the time being, I just stuffed a `task_count` into the …
> flux-job: watch guest output instead of doing a lookup

- src/cmd/flux.c
- src/common/libutil/Makefile.am
- src/common/libutil/intree.c
- src/common/libutil/intree.h
- src/common/libutil/test/intree.c
- src/modules/job-exec/exec.c
- src/modules/job-ingest/validate.c
This is split off the shell plugin work, since it is fairly independent and may actually generate some discussion on its own.
In the shell we want to load a different default initrc depending on if we're running "in-tree" or not, but the code to detect if an executable was only available in `cmd/flux.c`. The `flux` command does export `FLUX_CONF_INTREE=1` if it detects it is running out of a build tree, but there are several potential problems with this approach -- including that `FLUX_CONF_INTREE` is set, but never unset. (Also I'm not sure if that env var would always be exported to flux-shell, e.g. if `--standalone` is used)
This PR abstracts the in-tree detection into `libutil/intree.c`, including two new functions:
```C
int executable_is_intree (void);
const char *executable_selfdir …
```
> abstract in-tree detection into libutil, remove FLUX_CONF_INTREE environment variable

- doc/man1/flux-proxy.adoc
- doc/man7/flux-broker-attributes.adoc
- etc/boot.conf
- src/broker/boot_config.c
- src/broker/boot_config.h
- src/broker/boot_pmi.c
- src/broker/broker.c
- src/cmd/builtin/proxy.c
- src/cmd/flux-start.c
- src/shell/pmi.c
- t/conf.d/bad-missing.conf
- t/conf.d/bad-rank.conf
- t/conf.d/priv2.0.conf
- t/conf.d/priv2.1.conf
- t/conf.d/private.conf
- t/conf.d/shared.conf
- t/conf.d/shared_ipc.conf
- t/conf.d/shared_none.conf
- t/t0013-config-file.t
- t/t1105-proxy.t
- t/t3100-flux-in-flux.t
As discussed in #2344, the `session-id` attribute no longer works properly with flux-in-flux.  This PR replaces it with a `jobid` attribute, passed in from the enclosing instance (the shell) using the PMI KVS rather than the PMI appnum, which was restricted to 32 bits.  The implementation tracks that of `instance-level`, added in #2326.
If flux is at instance level 0, the `jobid` attribute is unset.
This also drops the moribund `flux-proxy` feature that allowed a jobid to be specified instead of a URI, and derived the URI from the jobid by assuming a particular socket path.  That approach proved fragile, and thus I removed it rather than try to fix it now that the untruncated jobid is available.  We will need better ways of finding URI's for running flux instances anyway.
> flux-in-flux: set jobid attribute

- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-info/guest_watch.c
- src/modules/job-info/watch.c
- src/shell/output.c
- src/shell/task.c
- src/shell/task.h
- t/t2204-job-info.t
Various misc cleanups & minor fixes peeled off of my now closed PRs (#2359, #2353, #2352).
Only one of note is the refactoring I did which added "flags" support to job-info event watches.  Even though the flags are not used, I figure we can keep it just in case for the future.
> misc cleanups & minor fixes

- doc/man3/flux_msg_cmp.adoc
- src/common/libflux/module.c
- src/common/libflux/module.h
- src/common/libflux/test/module.c
- src/modules/connector-local/local.c
- t/job-manager/sched-dummy.c
Another tidbit peeled off of #2302 
Add a public API function for testing and optionally clearing module debug flags, as set with `flux module debug`.  This cleans up the couple of places where those debug flags are used, including in local connector authentication, where clarity of the code is somewhat critical.
This capability is mentioned in the `flux-module` man page as well as [RFC 5](https://github.com/flux-framework/rfc/blob/master/spec_5.adoc).
> libflux/module: add flux_module_debug_test()

- src/common/libschedutil/Makefile.am
- src/common/libschedutil/alloc.c
- src/common/libschedutil/alloc.h
- src/common/libschedutil/free.c
- src/common/libschedutil/hello.c
- src/common/libschedutil/hello.h
- src/common/libschedutil/init.c
- src/common/libschedutil/init.h
- src/common/libschedutil/ops.c
- src/common/libschedutil/ops.h
- src/common/libschedutil/ready.c
- src/common/libschedutil/ready.h
- src/common/libschedutil/schedutil.h
- src/common/libschedutil/schedutil_private.h
- src/modules/sched-simple/sched.c
- t/Makefile.am
- t/job-manager/exec-service.lua
- t/job-manager/sched-dummy.c
- t/schedutil/req_and_unload.py
- t/t2301-schedutil-outstanding-requests.t
- t/valgrind/valgrind.supp
Refactor schedutil to track outstanding messages and automatically respond with `ENOSYS` when the `schedutil_t` is destroyed.
Having a count of the outstanding messages will also be useful for the ongoing simulator work.
Closes #2193 
Still TODO:
- Will fix python3.4 failure in Travis
> libschedutil: destroy pending futures on scheduler unload

- src/common/libflux/Makefile.am
- src/common/libflux/flux.h
- src/common/libflux/plugin.c
- src/common/libflux/plugin.h
- src/common/libflux/test/plugin.c
- src/common/libflux/test/plugin_foo.c
This PR isn't meant for merging, but just to put up some code for discussion.
After trying several different approaches this simple `flux_plugin_t` class was factored out of the work on shell plugins. While working on that PR I ended up with a `flux_shell_plugin_t` class that seemed like it might be useful as a more generic interface, so I moved the code under libflux and propose it here before moving my other shell work on top of it.
I had started by resurrecting the "`flux_extensor_t`" work, but unfortunately didn't quite have the mental capacity at this point to get a universal solution like that going in the short time I needed to get the shell plugin work done.
There's a full description of this plugin interface design in 0e49922. At a high level, a `flux_plugin_t` object is a simple …
> libflux: add simple plugin interface

- configure.ac
- etc/Makefile.am
- etc/flux-schedutil.pc.in
- src/Makefile.am
- src/common/Makefile.am
- src/common/libflux-schedutil.map
- src/common/libschedutil/Makefile.am
- src/common/libschedutil/hello.c
- src/common/libschedutil/hello.h
- src/common/libschedutil/init.c
- src/common/libschedutil/init.h
- src/common/libschedutil/ops.h
- src/common/libschedutil/schedutil_private.h
- src/common/schedutil.h
- src/include/flux/schedutil.h
- src/modules/sched-simple/sched.c
- t/job-manager/sched-dummy.c
- installs the compiled schedutil shared library
- adds a libschedutil map file for `ld`
- installs the schedutil headers
- creates a schedutil .pc file
- prefixes all public function typedefs with `schedutil_`
Closes #2377
> libschedutil: export library for use by flux-sched and others

- src/broker/Makefile.am
- src/broker/boot_pmi.c
- src/broker/pmiutil.c
- src/broker/pmiutil.h
- src/broker/test/pmiutil.c
- src/common/Makefile.am
- src/common/libpmi/Makefile.am
- src/common/libpmi/ltrace.conf
- src/common/libpmi/pmi.c
- src/common/libpmi/pmi2.c
- src/common/libpmi/pmi2.h
- src/common/libpmi/simple_client.c
- src/common/libpmi/simple_client.h
- src/common/libpmi/test/canonical2.c
- src/common/libpmi/test/pmi_info.c
- src/common/libpmi/test/simple.c
- src/common/libpmi2.map
- src/shell/pmi.c
As discussed in #2347, this PR adds back the PMI-2 API implementation we used to have, in order for our existing mvapich2 configurations to continue to work with the new exec system.   It's effectively a rewrite, and now includes unit tests for the API.   This will need to be deployed along with an MPI "personality" that sets `LD_LIBRARY_PATH` such that our library gets picked up before slurm's by `dlopen()`.
Still todo: test that this actuall works with our mvapich2's  (the whole point!)
> WIP: export libpmi2.so.0.0.0 for MPICH derivatives configured --with-pm=slurm --with-pmi=pmi2

- src/cmd/flux-job.c
- src/modules/job-info/guest_watch.c
- src/modules/job-info/watch.c
- t/t2204-job-info.t
- t/t2205-job-info-security.t
Per discussion #2338.  This is built on top of #2366.
- It is easy to "reach the end" of
- the main job eventlog (event "clean")
- a guest eventlog in the guest namespace
- a guest eventlog copied into the primary KVS namespace
- It is hard to know how to "reach the end" of a hypothetical namespace in the primary KVS that we don't know about.  So I did not support that case.  In that situation, the wait-event watches until it receives a cancellation notice.
- I don't return any events after "clean" in the main job eventlog.  So if the user were to do something stupid like, "flux kvs eventlog append" on it, that event won't show up via an eventlog watch.
- As a side effect of this work #2356 and #2361 are basically closed too.
- Once finishing this work, removed the now unncessary calls to …
> job-info: Return ENODATA when reaching the end of eventlogs

- src/cmd/flux-job.c
- src/shell/output.c
- src/shell/shell.h
- src/shell/task.c
- t/Makefile.am
- t/job-attach/outputsleep.sh
- t/t2500-job-attach.t
builds on top of my misc cleanups PR in #2360.
- have shell send output to KVS live as it happens
- have shell emit a "output-ready" event to `exec.eventlog`
- good name?  I considered "output {"ready":"true"}" as well.
- job attach checks for "output-ready" from `exec.eventlog`, and then reads / outputs from `guest.output` as it occurs.
- Fix racy completion in shell as discussued in #2363
> shell: live output

- doc/man3/Makefile.am
- doc/man3/flux_reactor_create.adoc
- doc/test/spell.en.pws
- src/cmd/flux-job.c
- src/common/libflux/reactor.c
- src/common/libflux/reactor.h
- src/common/libflux/test/reactor.c
- src/common/libpmi/pmi2.c
Per discussion in #2289, add two new reactor functions to manipulate active watcher counts.  When you want to start a watcher that should not increase the active watcher count, use:
```c
flux_watcher_start()
flux_reactor_active_decref()
```
to stop it use:
```c
flux_reactor_active_incref()
flux_watcher_stop()
```
This allowed for a bit of cleanup in the `flux job attach` command, which needed to externally track the "real" active watchers in order to stop some signal watchers that fall into the above category.
There's a loose PMI fix in here too (very minor, but was bugging me).
> libflux/reactor: add flux_reactor_active_incref(), _decref()

- src/cmd/flux-job.c
- t/t2500-job-attach.t
This PR adds timestamps (with t=0 normalized to the submit event) to events displayed with the `flux job attach --show-events` option.  It also adds a new `--show-exec` option that displays events from the guest.exec.eventlog in the same format.
> cmd/flux-job attach: add timestamps, --show-exec option

- src/shell/initrc.lua
- src/shell/jobspec.c
- src/shell/jobspec.h
- src/shell/lua.d/spectrum.lua
- src/shell/rc.c
- src/shell/shell.c
- src/shell/shell.h
- t/Makefile.am
- t/shell/initrc/tests/0004-getopt.lua
- t/shell/plugins/getopt.c
- t/shell/plugins/invalid-args.c
- t/t2603-job-shell-initrc.t
- t/t3001-mpi-personalities.t
This PR adds a new set of functions for managing the shell "options" set in jobspec via the public shell api:
```c
/*  Get shell option as JSON string as set in jobspec
*   attributes.system.shell.options
*
*  Returns 1 on success, 0 if option "name" was not set, or -1 on failure.
*/
int flux_shell_getopt (flux_shell_t *shell, const char *name, char **json_str);
/*  Unpack shell option from attributes.system.shell.options.<name> using
*   jansson style unpack arguments.
*
*  Returns 1 on success, 0 if option was not found, or -1 on error.
*/
int flux_shell_getopt_unpack (flux_shell_t *shell,
const char *name,
const char *fmt, ...);
/*  Set shell option as a JSON string. Future calls to getopt will return
*/
int flux_shell_setopt (flux_shell_t *shell,
const char *name,
const char …
```
> shell: add functions to get/set shell "options"

- t/Makefile.am
- t/t5000-valgrind.t
- t/valgrind/workload.d/job
This PR adjusts the `--killer-timeout` for the valgrind test so that `flux-start` will be much less likely to kill brokers that are slow to exit.
Additionally, output is added to the current `job` workload to give better coverage during the valgrind run.
Finally, this may be controversial, but I noticed with `make -j2` the fact that the valgrind and `flux-in-flux` tests were run last really seems to delay the overall time to complete `make check`. So, these tests are moved first in `TESTS` in Makefile.am, allowing them to start first and get better overlap with faster tests.
> testsuite: valgrind test improvements

- src/common/libsubprocess/local.c
- src/shell/Makefile.am
- src/shell/affinity.c
- src/shell/builtins.c
- src/test/docker/centos7/Dockerfile
- t/Makefile.am
- t/t2604-job-shell-affinity.t
This PR adds a default `affinity` plugin for the shell. By default the affinity of the shell is set to the specified cores list in *R*. If the `cpu-affinity` shell option is set to `"per-task"`, then the tasks managed by the shell are spread across the allocated cores using `hwloc_distrib(3)`. Setting the `cpu-affinity` option to `"off"` disables the affinity plugin.
> shell: add builtin core affinity plugin

- configure.ac
I keep annoyingly hitting the python sanity check at build time.
Reduce the chance of hitting this build-time error by removing `$(pwd)/src/cmd` from `PATH` for the duration of the PYTHON configure checks, so that the path the in-tree python wrapper script is less likely to be found.
> build: fix python insanity

- src/cmd/flux-job.c
- src/shell/output.c
- t/Makefile.am
- t/t2605-job-shell-output-redirection-standalone.t
- t/t2606-job-shell-output-redirection.t
This PR adds support to the shell to output stdout/stderr to a file instead of writing to the KVS. All task stdout/stderr is written to a single file.
Notes:
- To set this, the user must set the `attributes.system.shell.options.output.<stream>.type` field to "file". The setting defaults to "kvs".
- The file to be written uses `attributes.system.shell.options.output.<stream>.path`.
- `attributes.system.shell.options.output.<stream>.label` will label each line of output with the task number it came from.
- I wasn't sure what the mode should be on files created. I just did 644 for now.
- Writes to files just calls `write(2)` everytime there is data to write. It'll block if the filesystem is busy. Could attach to a FD watcher instead?
> shell: Support stdout/stderr redirect to a file

- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/gpubind.c
- src/shell/rcalc.c
- src/shell/rcalc.h
- src/shell/shell.c
- t/shell/input/1r1c2gpu.json
- t/shell/output/1r1c2gpu.1.expected
- t/shell/rcalc.c
- t/t2604-job-shell-affinity.t
This PR adds support for parsing `gpu` resources from *R* if assigned into the shell internal `rcalc` class. The gpu resources are then exposed to plugins via `flux_shell_get_rank_info()` and a `gpubind.c` builtin plugin is introduced to read the gpu list and set `CUDA_VISIBLE_DEVICES` appropriately.
The plugin can be controlled via the `gpu-affinity` shell option. `gpu-affinity="off"` disables plugin operation, `gpu-affinity="on"` is the default and sets `CUDA_VISIBLE_DEVICES` once per job, and `gpu-affinity="per-task"` divides available GPUs evenly among local tasks. (If GPUs do not evenly divide among tasks the current behavior is undefined :wink:. Probably should fix this, but I don't think it could actually happen in the current system)
I couldn't directly port the …
> shell: add gpu affinity support

- doc/man1/flux-mini.adoc
- doc/test/spell.en.pws
- src/cmd/flux-mini.py
- t/t2700-mini-cmd.t
This fixes an error pointed out by @grondo and makes mention of affinity plugin shell options.  That raises a question about where we should be documenting shell plugin options.  Since they'll be usable from multiple front end tools, this may be the wrong place.
> flux-mini: add --gpus-per-task option, update flux-mini(1) man page

- doc/man1/Makefile.am
- doc/man1/flux-version.adoc
- doc/man1/flux.adoc
- src/cmd/flux.c
- t/t0010-generic-utils.t
This PR adds a simple manpage for `flux-version(1)` (allowing `version` to appear in output of `flux-help(1)`.
Also, a quick hack is added to make `flux -V, --version` an alias for `flux version` (suggested by @SteVwonder)
It would be easy to just provide the flux-version manpage if the `flux -V` flag is a step too far.
> flux-version: make flux --version an alias, add manpage

- src/cmd/flux.c
- t/t0010-generic-utils.t
When `flux -V` re-execs `flux version`, it doesn't find flux unless PATH includes it. For example, itt fails when run as `./flux -V` in a build tree, outside of a running instance.
Per suggestion from @grondo, exec the original argv[0] rather than "flux".
Update sharness test to reset the PATH in addition to FLUX_URI, and run `flux -V` using its builddir path.
> flux -V: small fix to allow it to work outside of an instance

- src/modules/sched-simple/libjj.c
- t/t0022-jj-reader.t
- t/t2300-sched-simple.t
The sched-simple implementation only supports resource types of `node` `slot` and `core`. If a request with more than one resource at  a level includes a non-supported type, then that type was being ignored and the job run just on the nodes/cores requested.
This PR fixes that oversight by requiring the scheduler to look at every resource at any given level in the jobspec request.
Note: Instead of canceling these jobs with the generic "unsatisfiable request" message as specified in #2417, the error message is more explicit:
```console
$ flux mini run -g1 hostname
job-event: exception type=alloc severity=0 Unsupported resource type 'gpu'
```
If that isn't ok then it is probably trivial to make the error message more generic.
> sched-simple: reject requests with unknown resource types

- src/broker/broker.c
- src/cmd/flux.c
- t/issues/t2284-initial-program-format-chars.sh
- t/python/subflux.py
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t0013-config-file.t
- t/t0014-runlevel.t
This is an attempted fix for #2304. The use of `FLUX_RC{1,3}_PATH` is deprecated in favor of setting the broker attribute directly. The broker now sets the default for these paths from the static "conf", and allows them to be overridden on the command line.
All tests were updated to use the new scheme. Still need to test with flux-under-flux, but this should solve that issue in theory.
> broker: don't read FLUX_RCX_PATH to set rc1,rc3 paths

- configure.ac
- src/common/libflux/Makefile.am
- src/modules/job-ingest/Makefile.am
- src/modules/job-ingest/validators/validate-schema.py.in
Problem: validator.py uses #!/usr/bin/env python shebang,
which can pick up a user python without jsonschema installed.
Have configure substitute the configured python path instead.
Fixes #2434
> job-ingest/validator: configure python shebang

- t/issues/t2284-initial-program-format-chars.sh
- t/kvs/watch_disconnect.c
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t0011-content-cache.t
- t/t0012-content-sqlite.t
- t/t0014-runlevel.t
- t/t0015-cron.t
- t/t1000-kvs.t
- t/t1001-kvs-internals.t
- t/t1003-kvs-stress.t
- t/t1004-kvs-namespace.t
- t/t2602-job-shell.t
- t/t3100-flux-in-flux.t
I instrumented `test_expect_success` in sharness in order to find the longest running tests in hopes of getting `make check` to run a little faster (in Travis, and on my machine with only 4 cores).
Some of the more obvious fixes were done here (run more in parallel, use a reduced `--shutdown-grace`, disable rc1/rc3 where possible), and some other minor errors were addressed.
Some other issues with `LONGTEST` tests were also addressed (all but #2443).
Finally, an error recently introduced by me in 91b493bf13940020526ca3af19fb6f071528bbbc was fixed.
> testsuite: fix LONGTEST and other small improvements

- doc/man1/flux-kvs.adoc
- src/cmd/flux-kvs.c
- src/common/libkvs/kvs_txn.c
- src/common/libkvs/test/kvs_txn.c
- t/t1008-kvs-eventlog.t
Pulled this off of an old abandoned PR #2352.  As we begin creating more eventlogs in guest namespaces (`guest.output`, `guest.input`, etc.) being able to get the logs via `flux kvs eventlog get` will be useful for debugging.
> flux-kvs: Add eventlog namespace option

- src/cmd/flux-job.c
- src/common/libioencode/ioencode.c
- src/common/libioencode/ioencode.h
- src/common/libioencode/test/ioencode.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/shell/output.c
Per RFC24, ranks in I/O events are idset strings not integers.  Therefore
ioencode() and iodecode() should take/return string ranks as parameters,
not ints.
Update all callers appropriately for changes.
Fixes #2437
> libioencode: make rank parameters strings

- t/t0001-basic.t
- t/t5000-valgrind.t
The last few builds under travis-ci have failed in the `t0001-basic.t` `run_timeout` tests, likely because Travis is getting even slower and the small 10ms timeout fires before `/bin/true` runs in one case and before `exec()` returns an error in the missing file case.
Similarly, even with the 20s killer-timeout we've still seen some valgrind test failures due to the `flux-start` killer-timeout firing. This PR extends the killer timeout to 120s (effectively disabling it)
> testsuite: extend some testing timeouts 

- .mergify.yml
Finally emailed mergify support to ask why our title match regex wasn't working, and it turned out the regex should not have been double-quoted.
Fixed and pushed in this small PR.
> mergify: fix rule that prevents merging of "WIP" PRs

- src/cmd/flux-job.c
- src/cmd/flux-mini.py
- src/common/libsubprocess/test/test_echo.c
- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/input.c
- src/shell/output.c
- t/Makefile.am
- t/t2602-job-shell.t
- t/t2606-job-shell-output-redirection.t
- t/t2607-job-shell-input.t
After a lot of back and forth experimenting, initial stdin shell support via piping in via `flux job attach` and via file input (typically via `--input` in `flux mini`).
- if stdin is via file, leader shell reads file and writes to `guest.input`, otherwise service is started on leader shell to receive stdin and write to `guest.input`
- all tasks watch `guest.input` to get stdin, write to stdin via `flux_subprocess_write()`.  This was easier to implement for the time being and gives parity to wreck.
- Should do single watcher per shell?
- how to deal with potential buffer overflow in `flux_subprocess_write()` TBD.  `cbuf` can autogrow buffer size, but `cbuf` still requires a max-buffer size be specified.
- several corner cases handled via the service on leader not starting / shutting down. …
> Initial shell stdin support

- src/common/libutil/intree.c
A really dumb error in `is_intree()` caused the crash reported in #2467.
A NULL returned from `realpath(3)` should cause the function to return either `-1` or `0`, but in the case of `EACCES` or `ENOENT`, the function dropped through and called `strlen` on `NULL` value anyway. :roll_eyes: 
Sorry about that!
(I'm trying to think of a way to test this in the unit tests, but nothing simple comes to mind at the moment)
> fix crash in is_intree() with EACCESS or ENOENT from builddir

- src/modules/sched-simple/rlist.c
- src/modules/sched-simple/test/rlist.c
This fixes two scheduler problems noted in #2464:
* `flux mini run -N3 -n3` allocated 3 cores on one node
* `flux mini run -N3 -n8` failed when it should not have
> sched-simple:  fix rlist_alloc_nnodes() algorithm

- .travis.yml
- README.md
- config/ax_python_devel.m4
- configure.ac
- src/cmd/Makefile.am
- src/cmd/flux-jobspec.py
- src/cmd/flux-mini.py
- t/job-manager/bulk-state.py
- t/job-manager/drain-cancel.py
- t/job-manager/drain-undrain.py
- t/jobspec/summarize-minimal-jobspec.py
- t/jobspec/validate.py
- t/jobspec/y2j.py
- t/schedutil/req_and_unload.py
- t/t0019-jobspec-schema.t
- t/t0021-flux-jobspec.t
- t/t0022-jj-reader.t
- t/t2200-job-ingest.t
- t/t2202-job-manager.t
- t/t2206-job-manager-bulk-state.t
- t/t2300-sched-simple.t
- t/t2301-schedutil-outstanding-requests.t
This (should be) the absolute minimum to remove python 2 support.  Updates the config, README, and travis.  I'm not sure all of our docker images have a python 3 available, so we'll see on travis.
> bindings/python: change minimum python version to 3.6

- src/shell/jobspec.c
- t/python/subflux.py
- t/python/t0010-job.py
The python job test was submitting jobspec that represented the command as a bare string, rather than an array of string arguments.  This caused the `flux-shell` to segfault.  Since this is valid v1 jobspec, change the shell jobspec parser to detect this and convert it to an array of one string.
Also, noticed that there was a typo in the "rc personality" selection in the python subflux module that caused all tests to run under the "full" personality.  This explains why the shell was running in the first place, since the test had selected the "job" personality, which would not have loaded the exec module.
Finally, now that the "job" personality includes the full job manager, don't try to load the fake test one in the job test.  That must have been silently failing since the job manager was …
> flux-shell: handle jobspec command as bare string

- src/common/libutil/Makefile.am
- src/common/libutil/fdwalk.c
- src/common/libutil/fdwalk.h
- src/common/libutil/test/fdwalk.c
This is an experimental alternative to #2476.
Instead of removing `fdwalk` completely, use an implementation inspired from glib's [safe_fdwalk](https://github.com/GNOME/glib/blob/master/glib/gspawn.c#L1189) that uses `getdents64` on Linux instead of `opendir`, which should make this call safe to use between fork and exec.
If not on Linux, or if `open (/proc/self/fd)` fails, fall back to iterating over all possible fds.
This is an experiment to see if it works and subsequently passes asan.
> libutil: replace fdwalk with version that uses getdents64

- .travis.yml
- README.md
- config/ax_python_devel.m4
- configure.ac
Drop the minimum version of python back from 3.6 => 2.7.
Update docs, travis, and revert autoconf macro hack to find `python3` before `python3`.
Fixes #2480 and #2478 (hopefully).
> bindings/python: reinstate python2 support

- doc/man1/flux-mini.adoc
- src/cmd/flux-mini.py
- t/t2700-mini-cmd.t
Adjust `flux-mini -o, --setopt=OPT=VAL` to allow optional `VAL` (default = 1). This is useful for "flag" style options, allowing a user to use `-o verbose` to enable verbose shell logging for example.
For `--setattr`, improve the error when a value is not given (e.g. `--setattr=foo`) from
```
flux-mini: ERROR: list index out of range
```
to
```
flux-mini: ERROR: --setattr: Missing value for attr foo
```
> flux-mini: improve handling of --setattr and --setopt

- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-info/Makefile.am
- src/modules/job-info/info.h
- src/modules/job-info/job-info.c
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/list.c
- src/modules/job-info/list.h
- t/Makefile.am
- t/job-manager/list-jobs.c
- t/t2202-job-manager.t
- t/t2204-job-info.t
- t/valgrind/workload.d/job-info
This is an initial implementation for #2454.  This will not pass travis right now due to #2470.
- In this initial implementation, the internal lists of jobs in the `job-info` module grow without bound.
- Restart by loading job history from the KVS is not supported in this round.
- Per discussion, in #2454, three lists are used to store jobs.  `pending` jobs are sorted by priority first, then submission time.  `running` jobs are sorted by start time of running.  And `inactive` jobs are stored by time completed.  Note that the latter two lists don't need to be "sorted" per-se.  You can just append to the end of the list when events happen.
- Flags are supported to allow callers to ask for the `pending`, `running`, or `inactive` jobs.  `flux job list` defaults to `PENDING | RUNNING`.
- Per …
> job-info: Store full job-history, allow users to query pending, running, and inactive jobs

- doc/man3/flux_respond.adoc
Small docfix that came up when I was digging around for the C++ wrapper interface over on sched.
> doc: flux_respond_raw doesn't take an errnum

- configure.ac
- src/common/libflux/Makefile.am
- src/modules/job-ingest/Makefile.am
- src/modules/job-ingest/validate.c
- src/modules/job-ingest/validators/validate-schema.py
- t/Makefile.am
- t/ingest/fake-validate.sh
- t/t2200-job-ingest.t
`validate-schema.py.in` was an autoconf input file with a `#!@PYTHON@`
template at the top of the file.  This ensured that the
`validate-schema.py` script always ran with the python interpreter that
Flux was configured with.  This works as long as the python interpreter
path is short enough.  When the path is > 127 characters, the script
fails to execute due to kernel limits.
Rename `validate-schema.py.in` to `validate-schema.py` and remove the
`#!@PYTHON@` template shebang line.  Update the `job-ingest` module to
launch validators ending with `.py` with the configured python
interpreter.  `job-ingest` executes other scripts as before.
Add a test to ensure that non-python executables can still be launched
as validators.
Fixes #2491
> job-ingest: launch `.py` validators with configured python

- README.md
The markdown table was a mixture of spaces and tabs that, depending on your editor configuration, did not line up well.  Convert everything to spaces and re-align the columns. (Note: this doesn't affect the exported HTML at all).
Copying and pasting from the requirements table is very difficult.  You end up grabbing packages from both distros plus the version and note info.  To make it easier to install our build requirements, make the package names easily copied and pasted into the terminal.
> README: minor source cleanup

- t/lua/t1004-statwatcher.t
Running this test on Ubuntu 19.10 would always cause a timeout.  For
whatever reason, the second call to the statwatcher callback would not
read any additional data from the newly appended to file.  After
attempting to `strace` and `ltrace` the test, we concluded it is mostly
likely due to the EOF error flag being set on the FILE stream and not
being cleared before additional reads are attempted.
Fix by always open anew the file each time the statwatcher callback is
called.
Also add a reason string for the `reactor_stop_error` in the same test.
Fixes #2508
> t1004-statwatcher: fix test on Ubuntu 19.10

- src/broker/broker.c
- src/broker/test/heartbeat.c
- src/broker/test/hello.c
- src/broker/test/reduce.c
- src/broker/test/shutdown.c
- src/cmd/builtin/proxy.c
- src/common/libflux/handle.c
- src/common/libsubprocess/test/subprocess.c
- src/connectors/local/local.c
- src/modules/connector-local/local.c
- t/loop/issue2337.c
- t/shmem/backtoback.c
This PR addresses two issues with `flux_open()` when running outside of an instance
* Use builtin FLUX_CONNECTOR_PATH If unset in environment (e.g. not run under `flux(1)`)
* Try to get `flux_uri` from TOML config file before resorting to builtin path
The specific use case I was hoping to enable by the last one is setting up flux utilities on a login node to connect to a remote instance when a broker is not running locally.   Sys admins could set `flux_uri` in `/etc/flux/conf.d/flux.toml`.
Finally, somewhat unrelated:  I cherry-picked the commit from #2464 that includes the final socket component in `local://` URI's, rather than ending the URI with the directory, with final component hardwired to `local`.  That made it easier to tunnel broker sockets through ssh, and unwinds some …
> libflux: fall back to builtin connector search path

- src/common/libutil/test/cronodate.c
I ran into this while testing some the python run command, it was causing early failures of check about one in 3 runs on my test system.
> test: fix random cronodate test failure

- src/broker/modservice.c
- src/broker/ping.c
- src/broker/rusage.c
- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/msg_handler.c
The C++ compiler was squawking about assigning const strings into topic_glob.  How exactly we never had this issue on the C compiler eludes me, but we didn't as far as I can tell.  This cleans that up.
> msg_handler: make topic_glob const char *, fix fallout

- src/modules/job-exec/job-exec.c
This PR fixes the main valgrind error detected in #2519, along with a leak caused by the EPROTO test.
Valgrind now runs clean on `t2400-job-exec-test.t` on my system, but this could use a test Ubuntu 19.10 for good measure.
> job-exec: fix memory errors detected by valgrind

- src/common/libpmi/pmi.c
- src/common/libpmi/pmi2.c
- src/common/libpmi/simple_client.c
- src/common/libpmi/simple_client.h
- src/common/libpmi/simple_server.c
- src/common/libpmi/simple_server.h
- src/common/libpmi/test/pmi_info.c
- src/shell/input.c
- src/shell/log.c
- src/shell/output.c
- src/shell/pmi.c
- src/shell/shell.c
- src/shell/shell.h
- t/shell/plugins/log.c
- t/t2602-job-shell.t
This is a quick proof-of-concept fix for #2252. I'm not sure at all if I've done this correctly, so I'm posting now before I have any tests.
As a demo, I modified `t/mpi/hello.c` to call `MPI_Abort()` after `MPI_Init` from task 1 only.
```console
$ flux mini run -N4 -n4 t/mpi/hello
[fluke108:mpi_rank_0][smpi_load_hwloc_topology] WARNING! Invalid my_local_id: -1, Disabling hwloc topology broadcast
0: completed MPI_Init in 0.715s.  There are 4 tasks
0.849s: flux-shell[1]: FATAL: MPI_Abort: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
0.850s: job.exception type=exec severity=0 MPI_Abort: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
flux-job: task(s) exited with exit code 143
```
The previous behavior is that the application would hang after the Abort.
> shell: generate job exception on MPI_Abort

- t/scripts/event-trace.lua
- t/scripts/t0004-event-helper.sh
- t/t0004-event.t
- t/t1105-proxy.t
- t/t2402-job-exec-dummy.t
`t0004-event.t`, `t1105-proxy.t`, and `t2404-job-exec-dummy.t` were all failing when run under `make -j` and occasionally failing on Travis.
This PR prevents races by switching to `event-trace.lua`, reduce timeouts by increasing the timeout windows, and avoids tests interfering with one another by removing duplicate event names.
Closes #2522
Closes #2518 
Closes #2517
> t: fix tests prone to races or timeouts on constrained systems

- src/common/libkvs/test/treeobj.c
- src/common/libkvs/treeobj.c
- src/common/libkvs/treeobj.h
- src/modules/kvs/kvstxn.c
As discussed in issue #2505, this fixes performance issue "part 1" by trying to reduce calls to `treeobj_validate()` (which calls `blobref_validate()`) on appends.  The constant interating through
append blobref arrays eats up tons of CPU time.
I was originally going to create a function like `treeobj_append_blobref_to_entry (dir, key, blobref)`, but as I implemented it, the function became stupid.  Basically just a cut & paste of:
```
treeobj_get_entry()
treeobj_deep_copy()
treeobj_append_blobref()
treeobj_insert_entry()
```
which was basically the the exact same code for appending in `kvstxn.c`, except I'd replace
`treeobj_insert_entry()` with an implementation without calling `treeobj_validate()`.
So I instead created a new function which is exactly the same as `treeobj_insert_entry()` …
> kvs: improve append performance

- src/modules/kvs/cache.c
- src/modules/kvs/cache.h
- src/modules/kvs/lookup.c
- src/modules/kvs/test/cache.c
- src/modules/kvs/test/lookup.c
My proposed change for #2500.  I hope I'm not posting this prematurely :-)  I was able to reproduce within unit tests once I figured out what was going on. Ran user reproducer and didn't get a segfault, although unclear if user's reproducer was successful, need to talk to user.
Basically, in the lookup handle I store a pointer to a treeobject (`wl->dirent`) which is owned by a cache entry.  I assume this pointer is valid, even after a lookup is stalled and restarted.
If the cache entry that owns the treeobj is destroyed via normal expiration methods -> lookup restarts after stall -> tries to read treeobj -> use-after-free.
In order to fix this, added some reference counters for cache entries, which I incref/decref as I save off pointers.
Went back and forth on multiple options, and this …
> kvs: fix memory use-after-free corner case

- src/common/libkvs/Makefile.am
- src/common/libkvs/kvs_commit.c
- src/common/libkvs/kvs_commit.h
- src/common/libkvs/kvs_txn.c
- src/common/libkvs/kvs_txn_compact.c
- src/common/libkvs/kvs_txn_private.h
- src/common/libkvs/test/kvs_txn.c
- src/common/libkvs/test/kvs_txn_compact.c
- src/shell/eventlogger.c
- src/shell/eventlogger.h
- src/shell/output.c
- t/kvs/fence_invalid.c
Per discussion in #2528 (and #2505), improve performance of shell stdout/stderr by reducing
A) the number of times we call KVS commit
This is accomplished using the shell `eventlogger` API, patch provided by @grondo.  I added an additional `eventlogger_flush()` call so that we flush all pending KVS transactions when we receive all EOFs we're going to get.
@grondo, I left your patch intact except for removing some lingering `fprintf()` calls.  In order to avoid unit test failures due to an additional log output, tweaked your parsing of `batch-timeout`.  I left it as a separate commit, but we could just squash that into your commit later.
B) the number of appends on the output eventlog
This is accomplished with a new function `flux_kvs_txn_append_consolidate()`.  In a single KVS …
> shell: improve stdout/stderr performance

- src/cmd/flux-job.c
- src/modules/job-exec/job-exec.c
- src/shell/Makefile.am
- src/shell/events.c
- src/shell/events.h
- src/shell/input.c
- src/shell/internal.h
- src/shell/output.c
- src/shell/shell.c
- src/shell/shell.h
- t/Makefile.am
- t/shell/plugins/invalid-args.c
- t/shell/plugins/test-event.c
- t/t2607-job-shell-input.t
- t/t2609-job-shell-events.t
As discussed in #2539, this PR replaces the non-useful exec.eventlog "running" event emitted by the `job-exec` module with a `shell.init` event emitted by the shell after exit from the initialization barrier.
Since the `shell.init` event now guarantees all shells have completed shell initialization, the redundant `output-ready` and `input-ready` are removed, and `flux job attach` synchronizes on `shell.init` instead.
In addition to the `shell.init` event, a `shell.start` event is also added, which is used to indicate when all shells have launched all tasks. This does add another barrier in the shell, so it might be controversial. The event will be necessary for debugger/tool synchronization (the `sync` event) though, however the barrier could be reconfigured to only be triggered when …
> replace exec "running" event with "shell.init" and "shell.start"

- src/shell/shell.c
- t/shell/plugins/log.c
Slightly rework shell finalization to avoid segfault caused by shell logging functions found by @chu11 in #2543.
Adds a test to ensure shell logging function in a plugin destructor does no harm.
> shell: fix segfault if logging function is called in or after shell_finalize()

- src/cmd/flux-job.c
- src/modules/job-info/job-info.c
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- t/t2204-job-info.t
Per discussion in #2498, have a way to supply the number of jobs in each of the various job states.  I expose the counters via stats.
The meat of this PR is the job state counting.  How the user gets the data could be something else, but I decided to do it via stats.
> job-info: Add stats for number of jobs in each state

- src/modules/job-manager/alloc.c
- src/modules/job-manager/priority.c
- src/modules/job-manager/raise.c
- src/modules/job-manager/restart.c
- src/modules/job-manager/start.c
- src/modules/job-manager/submit.c
- t/t2201-job-cmd.t
As @grondo noted in #2551, some error paths in the job manager, where job ID's are looked up, are no longer functioning properly.  This was due to my change in #2536 from `queue_lookup()` which set errno, to `zhashx_lookup()` which does not.
This puts things right, and also cleans up some error formatting that was nearby.
> job-manager: fix job lookup error handling

- src/shell/input.c
- t/t2607-job-shell-input.t
This PR fixes an issue found in the shell input plugin during testing. Currently, any error from `flux_subprocess_write()` is a fatal error and results in a fatal job exception. However, some write errors (e.g. EPIPE) should not cause the job to be killed (and in fact should probably just be ignored)
For example, if `flux mini run` is run with default arguments and some tasks (but not all) have exited, and the user types a character on the terminal running `flux mini run`, this will kill the job. This is because the `flux_subprocess_write()` to the exited/exiting tasks gets `EPIPE` which results in a fatal exception.
This can be reproduced simply as:
```console
$ flux mini run -o verbose -n2 sh -c 'sleep $FLUX_TASK_RANK'
0.043s: flux-shell[0]: DEBUG: 0: task_count=2 slot_count=2 …
```
> shell: stdin write to exited task should not cause fatal job exception

- src/modules/job-info/job_state.c
- src/modules/kvs/kvstxn.c
- src/modules/kvs/test/kvstxn.c
Per discussion in #2547, fix corner case in which append could be duplicated.  Solution was to cache the root directory used to make the root cpy.  If a stall + replay occurs, replay on a brand new root cpy that has been refreshed via `json_deep_copy()`.
Added unit test.  Confirmed unit test failed on master, but works after fix.
Also fixed #2545 (which found this issue) in this PR, since it's trivial once the core issue was fixed.
> kvs: Fix duplicate append corner case

- src/bindings/python/flux/job.py
- src/cmd/flux-job.c
- src/cmd/flux-mini.py
- src/common/libflux/msg_handler.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/event.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/list.c
- src/modules/job-manager/restart.c
- src/modules/job-manager/submit.c
- src/modules/job-manager/wait.c
- src/modules/job-manager/wait.h
- t/Makefile.am
- t/job-manager/submit-sliding-window.py
- t/job-manager/submit-wait.py
- t/job-manager/submit-waitany.py
- t/job-manager/wait-interrupted.py
- t/t2207-job-manager-wait.t
- t/t2700-mini-cmd.t
- t/valgrind/workload.d/job-wait
This PR adds a simple job synchronization mechanism.  One submits a job with a new flag, and then one can "wait' on the job and get back its status.   If the job is still active, "wait" blocks until it becomes inactive, as you might guess from the name.  The result of the job is distilled down to a boolean `success` and a human readable error string.
There is a new submit flag and a couple API calls:
```c
enum job_submit_flags {
...
FLUX_JOB_WAITABLE = 4,      // flux_job_wait() will be used on this job
};
enum {
FLUX_JOBID_ANY = 0xFFFFFFFFFFFFFFFF, // ~(uint64_t)0
};
/* Wait for jobid to enter INACTIVE state.
* If jobid=FLUX_JOBID_ANY, wait for the next waitable job.
* Fails with ECHILD if there is nothing to wait for.
*/
flux_future_t *flux_job_wait (flux_t *h, flux_jobid_t id);
int …
```
> job-manager: add flux_job_wait()

- src/bindings/python/flux/job.py
- src/bindings/python/flux/wrapper.py
- src/common/libev/Makefile.am
- src/common/libev/ev.c
- src/common/libev/ev.h
- src/common/libev/ev_epoll.c
- src/common/libev/ev_linuxaio.c
- src/common/libev/ev_poll.c
- src/common/libev/ev_vars.h
- src/common/libev/ev_wrap.h
- src/common/libev/libev.m4
- src/common/libflux/ev_flux.c
- src/common/libutil/ev_zmq.c
It turns out that updating libev from 4.25 to 4.27 promotes the `epoll_ctl()` failure discussed in #2554 to an assertion failure:
```
ev_epoll.c:134: epoll_modify: Assertion `("libev: I/O watcher with invalid fd found in epoll_ctl", errno != EBADF && errno != ELOOP && errno != EINVAL)' failed.
```
so this PR updates the vendored copy of libev.
Additionally, it seems that our `ev_flux` and `ev_zmq` composite watchers mask errors thrown by libev.  They both embed io watchers, but use them for the side effect of unblocking the reactor so prep/check/idle callbacks can do the real event management.  However, when libev has a file descriptor problem on an io watcher, it calls `ev_feed_event()` to make an EV_ERROR event pending on the watcher.  Our composite watchers weren't checking for that, …
> bindings/python and libev:  work around future leak

- README.md
Problem: PYTHON_VERSION must be set to build with Python 3
on modern distros, since /usr/bin/python is usually Python 2,
but this is not documented.
Since the intent is to eventually get rid of Python 2 support,
we want to encourage new users to go with Python 3.  Therefore,
change README.md to list the Python 3 prerequisite packages instead
of python2 ones, and add PYTHON_VERSION=3.6 to the configure line.
Describe how PYTHON_VERSION works, what to do if you really need
Flux to use Python 2, and warn that Python 2 support in Flux
should be considered on its way out.
Fixes #2556
Fix an unrelated spelling error.
> README.md: update build docs for Python 3

- src/cmd/flux-job.c
- src/cmd/flux-mini.py
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/list.c
- t/t2204-job-info.t
- t/t2700-mini-cmd.t
Per RFC PR https://github.com/flux-framework/rfc/pull/214, support job-names in the job-info module's job listing service, and then the `flux job list` tool.  Job names will be the first string in the command list OR can be set by the user.
example use case:
`flux mini submit --setattr system.job-name=myjobname hostname`
example output in job listing:
```
JOBID		STATE	USERID	PRI	NAME		T_SUBMIT
503064821760	I	8556	16	hostname       	2019-11-27T17:37:24Z
422450298880	I	8556	16	myjobname       2019-11-27T17:37:20Z
```
Note: I elected to close issue #2401 in one of the commits in this PR.  Issue #2401 is quite generic in this statement of having "wreck parity".  It's possible this isn't full wreck parity, but I figure it's close enough.
> initial job-name support

- src/common/libflux/future.c
- src/common/libflux/handle.c
- src/common/libflux/handle.h
- src/common/libflux/rpc.c
- src/common/libflux/test/future.c
This is maybe a solution to the use-after-free reported in #2567 
The first straightforward thing I tried seems to have worked (just have future call flux_incref() on the handle).  I was not expecting that - hence the unit test added to libflux/test/future.c does more work than it needs to to simulate the use after free in a way that I thought I could more readily debug.
I ran the unit test under valgrind and it seems OK.  If this gets through travis-ci, we should probably try the unit test under ASAN, and retry the python test that was failing in #2567 too.
Also: I tweaked `flux_incref()` to return a `flux_t *` instead of void, and added a `flux_decref()` that's identical to `flux_close()` but the asymmetry was bugging me.
> have future take a ref on flux_t handle

- .travis.yml
- config/x_ac_sanitize.m4
- src/broker/module.c
- src/broker/overlay.c
- src/broker/pmiutil.c
- src/cmd/builtin/version.c
- src/cmd/flux-exec.c
- src/common/libflux-core.map
- src/common/libflux-idset.map
- src/common/libflux-optparse.map
- src/common/libflux-schedutil.map
- src/common/libflux/handle.c
- src/common/libflux/plugin.c
- src/common/libioencode/test/ioencode.c
- src/common/libpmi.map
- src/common/libpmi2.map
- src/modules/job-manager/raise.c
- src/shell/flux-shell.map
- src/test/docker/docker-run-checks.sh
- src/test/travis_run.sh
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t0005-exec.t
- t/t0016-cron-faketime.t
- t/t1003-kvs-stress.t
- t/t2700-mini-cmd.t
- t/t3001-mpi-personalities.t
- t/t5000-valgrind.t
This is in progress, but showing some general promise.  I am slightly ashamed to admit I don't know how to manipulate M4 well enough to add the check for the new flag to the sanitizer file, but this is the configure line I'm using for testing:
`../configure --prefix=/usr/local --enable-sanitizer=address CC=gcc CXX=g++ CFLAGS='-Og -g -fsanitize-recover=address' LDFLAGS='-fsanitize-recover=address'`
The significant thing is that asan can recover and continue when built with the recover flag as above.  Tests run with ASAN_OPTIONS=detect_leaks=0 for now almost all *run* (not necessarily *pass* mind you, but *run* at least).  There is one significant exception that I'm really perplexed by.  @grondo and I have passed some messages back and forth on this, but the jist of it is that when built …
> asan/lsan: in-progress making asan usable

- src/bindings/python/flux/future.py
- src/bindings/python/flux/job.py
- src/bindings/python/flux/wrapper.py
- t/python/t0012-futures.py
As documented in #2566, futures are being leaked due to a circular reference in the `Wrapper` class.  Use `weakref` to avoid this.
Fix a reference counting bug in the `Flux` class exposed by the previous fix (along with a test for the issue).
Closes #2566.
> python: fix circular reference in `Future` class

- src/shell/affinity.c
- src/shell/gpubind.c
- src/shell/mpir/mpir.c
- src/shell/mpir/ptrace.c
- src/shell/shell.c
- src/shell/shell.h
- src/shell/task.c
- src/shell/task.h
- t/shell/plugins/invalid-args.c
The `flux_shell_get_info`, `flux_shell_get_rank_info` and `flux_shell_task_get_info` calls are all very cumbersome to use from C shell plugins. The internal shell/task information is encoded into a Jansson object, dumped to a string, only to be immediately parsed on the caller side, then unpacked.
This results in a fair bit of boilerplate code, extra mallocs, etc -- duplicated between plugins. (many of the builtin plugins sidestep this issue by dereferencing the `shell` and `task` objects directly)
This PR adds unpack-style getters for these calls. The Jansson `json_t` objects are cached as aux data in the shell or task objects for later destruction, ensuring that `const char *` strings that are unpacked stay valid for the duration of the shell/task. O/w, the new calls just wrap …
> shell: add unpack-style helpers for get_info shell plugin api calls

- src/bindings/python/flux/job.py
- src/bindings/python/flux/util.py
- src/cmd/flux-mini.py
- t/job-manager/bulk-state.py
- t/job-manager/submit-sliding-window.py
- t/job-manager/submit-wait.py
- t/job-manager/submit-waitany.py
- t/job-manager/wait-interrupted.py
- t/python/t0010-job.py
Moves the `Jobspec` class out of `flux-mini` and into the main python bindings.  Includes refactoring, new `walk` features, and testing against valid and invalid jobspecs in `t/jobspec`.
Closes #2415 
Closes #2393 
I'd love some feedback on the arguments to the two `__init__` methods.   I initially did not want to have `version` in the JobspecV1 constructor, but that precludes the ability to do things like `JobspecV1(**yaml.safe_load(jobspec_yaml_file))`.  What I have right now is `Jobspec(resources, tasks, version, attributes=None)` and `JobspecV1(resources, tasks, attributes=None, version=1)`.   The re-ordering of the last two arguments is bothersome to me, but I'm not a fan of the idea of adding a default value to the `version` in `Jobspec`s constructor.
> python: add jobspec classes to main bindings

- src/cmd/flux-job.c
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/list.c
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/submit.c
- t/t2204-job-info.t
Wanted to post this WIP to mostly get comment on the first bullet below, since it's sort of fudgable.
- When the job "start" and "end" time occur is actually something we can wiggle to different states of the job.
I decided the job start time goes with the job state `FLUX_JOB_RUN`  / eventlog event "alloc".  I don't think the start time will be too controversial
I decided the end time goes with `FLUX_JOB_CLEANUP` and the eventlog event "finish" OR "exception" with severity 0.  We could have the end time be the "inactive" state instead.  But I think
having it be `FLUX_JOB_CLEANUP` makes more sense b/c that is the transition that can occur immediately after an exception.
- The `job-manager`'s transitions publication also publishes timestamps associated with the state transitions.  For …
> Support job state times in job listing service

- .github/workflows/main.yml
This is an experimental PR which uses GitHub workflow support to support simple validation of commits in a pull request. The validation is performed via a custom "action" ( [flux-framework/pr-validator](https://github.com/flux-framework/pr-validator)), which currently just verifies that commits in a PR are not merge commits or have `fixup` or `squash` in the subject.
The custom GitHub action is kept separately from this repo so it can more easily be shared between flux-framework projects, and be updated out-of-band as new validations of PRs is required.
Example of validator functionality:
> github: enable a workflow to validate commits in a PR

- src/cmd/flux-job.c
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/list.c
- t/t2204-job-info.t
Nothing too surprising in this PR, it's pretty small:
- Support a new `task-count` field in job info job listing service.
- In order to parse the task count I basically cut & pasted the code that was in the job shell for the same purpose.  I contemplated writing a convenience library to do the parsing in both parts, but given we don't quite have all the parsing needs for the jobspec down yet, I figured writing a convenience library was a little premature?
- also did some unit test cleanup
> job-info: Support task-count in listing service

- src/modules/job-info/list.c
- t/t2204-job-info.t
> job-info: honor `max_entries` option in job-info.list

- .mergify.yml
Add a rule to `.mergify.yml` to avoid merging PRs that do not pass the GitHub pr-validator action. (Avoid merging PRs with fixup/squash commits)
> mergify: do not auto-merge PRs with invalid commits

- src/modules/job-info/job_state.c
- t/t2204-job-info.t
Per issue #2588.
Only interesting question was to use posix vs gnu `basename()`.  I decided to use GNU version as that removes the need to create a copy of the arg0 string.  But there is corner case in which GNU `basename()` could return the empty string.
It wouldn't be the biggest deal in the world if we returned an empty string for the jobname if the user inputted something, but I disliked the idea of that.  So I decided to return the full arg0 if the user input something stupid on the command line.
e.g.
user runs: `/foo/bar`, job-name is `bar`
user runs: `/foo/bar/`, job-name is `/foo/bar/` (b/c of the trailing slash)
> job-info: use basename of arg0 for job-name

- README.md
- configure.ac
- doc/man3/Makefile.am
- src/bindings/lua/Makefile.am
- src/bindings/python/_flux/Makefile.am
- src/broker/Makefile.am
- src/broker/broker.c
- src/broker/module.c
- src/cmd/Makefile.am
- src/common/Makefile.am
- src/common/libflux/Makefile.am
- src/common/libjob/Makefile.am
- src/common/libkvs/Makefile.am
- src/common/libpmi/Makefile.am
- src/common/librouter/Makefile.am
- src/common/librouter/usock.c
- src/common/libtestutil/Makefile.am
- src/common/libtestutil/util.c
- src/common/libutil/Makefile.am
- src/common/libutil/zsecurity.c
- src/connectors/local/Makefile.am
- src/connectors/loop/Makefile.am
- src/connectors/shmem/Makefile.am
- src/connectors/ssh/Makefile.am
Since zuuid asserts when `/dev/urandom` cannot be opened (as hit recently in #2593), this PR replaces it with `libuuid`, a better option because it implements an internal fallback to pseudo-random when that happens, and also because its functions don't require error checking.
Unfortunately, this adds a new dependency, but one we already required in flux-security.
This fixes #2281
> use libuuid instead of zuuid

- .travis.yml
- configure.ac
- src/test/docker/centos8/Dockerfile
- src/test/docker/centos8/config.site
This PR adds a new Dockerfile for CentOS 8 in `src/test/docker/centos8/Dockerfile`. An image from this Dockerfile has already been pushed up to Docker Hub as `fluxrm/testenv:centos8`.
Additionally, one of the CentOS builds in Travis-CI is updated to CentOS 8 (python 3.6 build)
> docker: add image and travis tests on CentOS 8

- doc/man1/Makefile.am
- doc/man1/flux-jobs.adoc
- doc/test/spell.en.pws
- src/bindings/python/flux/job.py
- src/cmd/Makefile.am
- src/cmd/flux-jobs.py
- t/Makefile.am
- t/t2800-jobs-cmd.t
This is an initial hacked up `flux-queue.py` that I wrote up (built on top of PR #2580) just to get my python bearings.  Example output:
```
JOBID		STATE	TASKS	NAME	USERID	TIME
21357395968	R	1	sleep  	8556	0:00:01
18756927488	R	1	sleep  	8556	0:00:01
16190013440	R	1	sleep  	8556	0:00:01
```
Options are:
```
-c N, --count N       Limit output to N jobs
-p, --pending         List pending jobs
-r, --running         List running jobs
-i, --inactive        List inactive jobs
-s, --suppress-header
Suppress printing of header line
-u UID, --userid UID  Limit output to specific userid (Specify "all" for all
users)
```
So options aren't all that different from `flux job list` for the time being, but it:
A) lists task count
B) lists run time
C) caps output to 1000 jobs (random max I thought was …
> Add porcelain flux jobs command

- src/cmd/flux-job.c
This PR has some minor fixes for `flux-job attach`.
* Block `SIGTTIN` `SIGTTOU` in `flux-job attach` to avoid the process getting stopped in the background
* Remove `stdin EOF could not be sent` warning message 
* Improve error message for invalid jobids.
> flux-job: misc fixes for attach

- .travis.yml
When adding the CentOS 8 builder, I forgot to deploy the resulting images with flux-core installed to `fluxrm/flux-core:centos8*`. Without this, dependent projects like flux-sched cannot build against CentOS 8.
> Ensure CentOS 8 docker image is deployed

- src/bindings/python/flux/job.py
- src/common/libflux/Makefile.am
- src/common/libflux/conf.c
- src/modules/job-ingest/Makefile.am
- src/modules/job-ingest/job-ingest.c
- src/modules/job-ingest/validate.c
- src/modules/job-ingest/validate.h
- src/modules/job-ingest/validators/validate-jobspec.py
- t/t2200-job-ingest.t
- t/t2300-sched-simple.t
Adds a new jobspec validator that uses the (also new) validation function within the python bindings rather than jsonschema to validate user-submitted jobspec.
Sets this new validator as the default for the job-ingest module since it should provide more meaningful error messages to the user than jsonschema does.  I haven't seen a huge performance difference on my local machine, but I'd expect it to be faster on a busy filesystem since it does not require reading in a jsonschema file.
Error output from the jsonschema validator on our invalid jobspec examples:
```
→ for x in ./*.json; do cat $x; echo ""; done | ../../../src/cmd/flux python ../../../src/modules/job-ingest/validators/validate-schema.py --schema ../../../src/modules/job-ingest/schemas/jobspec.jsonschema
ready …
```
> job-ingest,python/job: switch to a py bindings based jobspec validator

- doc/man1/flux-jobs.adoc
- src/common/libtomlc99/test/toml.c
- src/common/libtomlc99/toml.c
This fixes #2630.  I tossed in a couple other minor fixes: a missed copyright header, and a cut-and-paste error in the `flux-jobs(1)` man page.
> libtomlc99: fix use after free

- NEWS.md
Posting this early because I need to head home.  I've pulled in the merge commit messages since 0.13.0 using `relnotes.sh` script and attempted to sort the raw entries into "New features", "Improvements", and "Fixes" categories.
I did drop these two entries which cancel each other out
* bindings/python: reinstate python2 support (#2482)
* bindings/python: change minimum python version to 3.6 (#2452)
and addded entries for PR"s that are sitting there with merge-when-passing set:
* libtomlc99: update for TOML v0.5.0 support (#2619)
* job-ingest,python/job: switch to a py bindings based jobspec validator (#2615)
I'll have a go at reducing and adding a summary sometime this weekend (likely sunday if anyone else feels like pushing improvements to this PR in the mean time).
> add release notes for 0.14.0

- src/cmd/flux-job.c
- t/t2201-job-cmd.t
- t/t2203-job-manager-dummysched.t
- t/t2204-job-info.t
- t/t2700-mini-cmd.t
As proposed in #2629, this PR makes `flux job list` produce json output by default, and updates tests that were parsing the human readable output to use `jq` instead to extract what they need (or in a couple cases, use the test-only `t/job-manager/list-jobs` utility).
Side note:  I think we could get rid of `t/job-manager/list-jobs` once we address #2635.
> flux job list: make json output the default

- src/cmd/flux-job.c
- src/common/libjob/job.h
- t/t2204-job-info.t
- t/valgrind/workload.d/job-info
This updates state filtering options in the `flux job list` plumbing command to match those in `flux-jobs(1)`, namely:
* Drop `--pending`, `--running`, and `--inactive` options
* Add `--states=STATES` where STATES a comma-separated list of states (virtual or real)
* Add `-A,--all-jobs` (all users, any job state)
* Add `-a,--all-my-jobs` (my jobs, any job state)
I went ahead and defined the `FLUX_JOB_PENDING`, `FLUX_JOB_RUNNING`, and `FLUX_JOB_ACTIVE` "virtual states" as a mask of actual RFC 21 states in `job.h`.  I structured `flux job list` to construct a state mask and derive the `job-info.list` request flags from that, to minimize required changes when #2628 (job-info: support listing jobs in specific states) lands.
Note that I had suggested that `t/job-manager/list-jobs` could be …
> flux job list: make filtering options match flux jobs(1)

- doc/man1/flux-jobs.adoc
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/list.c
- t/t2204-job-info.t
- t/t2800-jobs-cmd.t
Globally adjust tools, tests, manpages, variable names, etc.
Per discussion in #2640
> job-info: Rename 'job-name' attribute to 'name' and 'task-count' attribute to 'ntasks'

- t/t2204-job-info.t
- t/t2800-jobs-cmd.t
Per issue #2665, this will fix some eventual consistency racyness in `t2204-job-info`.  It won't fix all racyness (such as the one @dongahn saw in #2654), some will be fixed later via issue #2592.
There's some tiny cleanups in here.  Assuming this PR will go in first, I went ahead and cherry-picked some cheapo cleanups from PR #2655 too.
> t/t2204-job-info: Add checks to avoid racyness

- src/modules/job-manager/alloc.c
- src/modules/sched-simple/sched.c
- t/Makefile.am
- t/t2204-job-info.t
- t/t2210-job-manager-bugs.t
This is the trivial fix for issue #2664, where the right combination of submits and cancels results in the scheduler complaining of
```
sched-simple.err[0]: alloc received before previous one handled
sched-simple.err[0]: alloc: flux_respond_error: Invalid argument
```
because the job manager loses count of how many alloc requests it has sent to the scheduler.
> job-manager: fix counting problem that leads to scheduler sadness

- src/common/libpmi/test/canonical.c
- src/common/libpmi/test/canonical2.c
- src/common/libpmi/test/server_thread.c
- src/test/docker/centos7/Dockerfile
- t/t0005-exec.t
- t/t0005-rexec.t
- t/t0015-cron.t
This PR has some small fixes for tests, including fixes for #2668 and #2663.
The Dockerfile for centos 7 is also changed to make /tmp a symlink to /var/tmp, so that we don't accidentally commit future tests that have the same issue as described in #2663.
Once this PR is merged, I will push an update to our `fluxrm/testenv:centos7` image.
> testsuite: fix unsafe getenv in libpmi tests, use of /tmp in sharness tests

- src/cmd/flux-jobs.py
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/list.c
- t/flux-jobs/tests/issue#2634/description
- t/flux-jobs/tests/issue#2634/input
- t/t2204-job-info.t
This PR is a pre-PR for issue #2590.  Before supporting #2590, `job-info` has to be refactored.  I'll just use the comment from one of my commits to describe what had to be done and why.
```
At the moment the only data that has to be retrieved from the KVS
occurs when the job is submitted, i.e. state DEPEND.  Code was designed
to not allow users to see a job in the DEPEND state until this data
had been retrieved from the KVS.  After this point, it was assumed
that no additional data would be retrieved from the KVS.
During the time that data is retrieved from the KVS, there is a racy
component of the list service, where additional state transitions could
occur.  For example, the job could complete and be in INACTIVE state
before data from the KVS is retrieved.  This is considered …
```
> job-info: Refactor job-info to transition to any state after retrieving data from KVS

- doc/man1/flux-module.adoc
- etc/rc3
- src/cmd/flux-module.c
- t/t0003-module.t
This PR adds a `-f, --force` option to `flux module remove` which causes the program to ignore nonexisting modules.
The option is then added to all `flux module remove` commands in `rc3`. This improves the reliability of shutdown, where we only care that modules are unloaded, not that they are being unloaded by this specific `flux module remove` command.
The `-e` option to the shell is also removed under the assumption that `rc3` is running important shutdown work, and we should not skip all remaining commands just because of one error. Errors will still be printed but it is ok to move on.
These two changes should fix the annoying errors during shutdown for every instance that we are currently seeing with v0.14 + flux-sched v0.8.
> Improve rc3 reliability

- src/cmd/flux-exec.c
- src/common/libsubprocess/local.c
- src/shell/shell.c
- t/t0005-exec.t
- t/t2608-job-shell-log.t
Quick attempt to improve error messages per discussion in #2481.
BEFORE
```
>flux mini run nosuchprocess
0.451s: flux-shell[0]: FATAL: failed to start taskid=0
0.453s: job.exception type=exec severity=0 failed to start taskid=0
flux-job: task(s) exited with exit code 1
>flux exec nosuchprocess
flux-exec: Error: rank 0: No such file or directory: Success
```
AFTER
```
>flux mini run nosuchprocess
0.249s: flux-shell[0]: FATAL: task 0 failed: nosuchprocess: No such file or directory
0.251s: job.exception type=exec severity=0 task 0 failed: nosuchprocess: No such file or directory
flux-job: task(s) exited with exit code 1
>flux exec nosuchprocess
flux-exec: Error: rank 0: nosuchprocess: No such file or directory
```
I debated how to tweak the one in the shell.  I didn't want to output `exec …
> shell / exec: Improve error messages to users on exec failures

- src/common/libsubprocess/local.c
- src/shell/shell.c
- t/t2608-job-shell-log.t
In order to solve #2679, create a new `shell.init` call that will `chdir()` into the job's current working directory, so that each task does not have to `chdir()` into it.
Example output:
```
>src/cmd/flux start flux mini run --setattr="system.cwd=/foo" pwd
0.088s: flux-shell[0]: ERROR: tasks: Could not change dir to /foo: going to /tmp instead: No such file or directory
/tmp
```
Notes/Thoughts:
- I could have stuck the `chdir()` in any number locations, but in keeping with the plugstack architecture in the job-shell, I created the new "shell.init" function.  Putting it in `task.c` didn't feel 100% right, but I disliked the idea of creating a new file for just this `chdir()`.  Maybe I should have.  It's one of the reasons that the plugstack function is labeled "tasks" instead of "task", …
> shell: Add new shell init call to chdir() into current working directory

- src/shell/Makefile.am
- src/shell/shell.h
It was an oversight that `shell.h` was never added to `fluxinclude_HEADERS` so it got installed in the include path.
This PR fixes that issue, plus removes `optparse.h` from the header, a leftover from when this was the main include file for the shell.
> install shell.h: the public api for shell plugins

- src/shell/input.c
- src/shell/output.c
- src/shell/shell.c
- t/Makefile.am
- t/issues/t2686-shell-input-race.sh
As detailed in #2686 there's a potential race between guest.input eventlog creation, and the tasks which watch this eventlog for any input.
This is due to a confusing aspect of the shell design, where all initialization steps that must be guaranteed to be complete before the shell.init barrier must be done synchronously. In this case, the creation of `guest.input` eventlog was done asynchronously, and thus could race with readers (since there is no WAITCREATE feature for eventlogs)
This PR closes that race by synchronously ensuring the eventlog has been committed to the KVS before proceeding. 
I've also added a reproducer under the t4000-issues test driver, however, it wasn't 100% reproducible (more like 80%), but I figured it can't hurt. If it slows down Travis significantly, we may want …
> shell: fix race between stdin/out readers and eventlog creation

- src/cmd/flux-job.c
- src/common/liboptparse/optparse.c
- src/common/liboptparse/test/optparse.c
- t/t2500-job-attach.t
It is slightly inconvenient that to dump all log information from the `guest.output` eventlog, a call to `flux job eventlog` is required, since there's no way to entice `flux-job attach` to dump file and line info.
This PR started by adding a `-v, --verbose` option to `flux job attach` which presently just adds the file and line prefix to log messages if present. Therefore we can just tell users to run `flux job attach -v ...` to get this info into issue reports etc. We can expand `-v` to add other verbosity later.
I'm amenable to a different option name if someone has an idea.
Along the way, I was annoyed that log messages are ignored when the shell fails to initialize (#2490). I thought of a workaround for that and added it here. If a "complete" event is seen in the exec.eventlog, and …
> flux-job attach: don't ignore log messages on shell init failure, add -v option

- src/cmd/flux-job.c
- src/modules/job-manager/drain.c
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/kill.c
- src/modules/job-manager/kill.h
- src/modules/job-manager/raise.c
- src/modules/job-manager/raise.h
- t/t2201-job-cmd.t
- t/t2204-job-info.t
This PR adds job manager support for sending signals and raising exceptions on groups of jobs, and adds `flux job killalll`, `flux job raiseall`, and `flux job cancelall` front end commands.   By default these commands target the jobs of the invoking user. The instance owner can additionally specify a `--user` option to target the jobs of a specific user, or `all` for all users.  The commands by default run in a "dry run" mode where the number of affected jobs is reported, and must be run with `--force` to have any effect.   Example:
```
$ fflux job cancelall
flux-job: Command matched 44 jobs (-f to confirm)
$ flux job cancelall -f
flux-job: Canceled 44 jobs (0 errors)
$ flux job cancelall
flux-job: Command matched 0 jobs
```
Still need to write tests, but wanted to get some feedback on …
> add flux job raiaseall, cancelall, killall

- src/cmd/flux-job.c
- src/cmd/flux-queue.c
- src/common/libschedutil/alloc.c
- src/common/libschedutil/alloc.h
- src/common/libschedutil/init.c
- src/common/libschedutil/init.h
- src/common/libschedutil/ops.c
- src/common/libschedutil/ops.h
- src/common/libschedutil/schedutil_private.h
- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/event.c
- src/modules/job-manager/raise.c
- src/modules/sched-simple/sched.c
- src/test/sched-bench.sh
- t/t2201-job-cmd.t
- t/t2202-job-manager.t
- t/t2208-queue-cmd.t
- t/t2210-job-manager-bugs.t
- t/t2300-sched-simple.t
- t/t2402-job-exec-dummy.t
This PR adds `flux queue stop [reason]` and `flux queue start` to tell the job manager to stop allocating resources temporarily, without affecting the ability to submit new work. This is one step towards being able to cleanly shutdown an instance, as discussed in #2649. 
To implement this, I added a `sched.cancel`  RPC between job manager and scheduler.  All pending alloc requests are canceled when resource allocation is stopped.  This cancels the requests so new jobs won't start as running ones complete, but the jobs remain in SCHED state.
The cancel request is also a solution for the job cancellation race described in #2279, where a job canceled at just the right time could theoretically get stuck in CLEANUP state until the scheduler allocated resources for it.  This was because the …
> add capability to administratively suspend scheduling

- src/shell/lua.d/intel_mpi.lua
- src/shell/lua.d/mvapich.lua
- src/shell/lua.d/openmpi.lua
- src/shell/lua.d/spectrum.lua
- src/shell/rc.c
- t/t2603-job-shell-initrc.t
This PR mainly fixes #2698, however some other deficiencies in the shell initrc were fixed along the way. While debugging this I found the lack of a logging interface from initrc.lua a bit frustrating, so that was added here as well.
Before, we see this if the posix module is not found:
```
$ flux mini run hostname
flux-job: No job output found
flux-job: task(s) exited with exit code 1
```
After, just a wee bit more detail.
```
$ flux mini run hostname
0.063s: flux-shell[0]: ERROR: /home/grondo/git/f.git/src/shell/lua.d/mvapich.lua:11: module 'posix' not found:
no field package.preload['posix']
no file '/home/grondo/git/f.git/src/bindings/lua/posix.lua'
no file '/home/grondo/git/f.git/t/posix.lua'
no file '/usr/local/share/lua/5.2/posix.lua'
no file …
```
> shell: do not exit from shell initrc scripts when posix module not found

- doc/man1/flux-jobs.adoc
- src/bindings/python/flux/job.py
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-info/list.c
- t/t2204-job-info.t
- t/t2800-jobs-cmd.t
Per discussion in #2628.
Most of this PR shouldn't be that surprising, just mild modifications to use the virtual job states FLUX_JOB_PENDING/RUNNING/ACTIVE, use some bitmasks to return only the desired states to the user, adjust `flux-job` and `flux-jobs.py` accordingly to support settings states + "active", add new tests.
But after doing all of the above, you set various job states in the `flags` key of the RPC to `job-info.list`.  This didn't feel right, b/c its not really a flag, they are job states.  A completely different set of bitmasks compared to "flags".  So I created a new key in the `job-info.list` service called `states`.
This changes the `flux_job_list()` function to add a parameter, leading to fallthrough changes everywhere in the last commit (bindings, callers, tests, …
> job-info: support listing jobs in specific states

- src/bindings/python/flux/job.py
I found myself a little annoyed when I couldn't pass `gpus_per_task=0` to the JobspecV1 constructor. I did notice that `mini run` won't accept an argument of `-g0`, though, so I suppose this introduces some minor API inconsistency. I think there are some reasons why `mini run` should accept `-g0`, but I think the reasons are stronger in this case, because 'mini run' commands are (I suspect, and certainly in my case) hard-coded or constructed piece-by-piece, while it makes less sense to have to make two different API calls based on the value of `gpus_per_task`.
If you don't like the change, I could very easily change my own code, I just thought I would propose this.
> Allow JobspecV1 to accept 0 gpus_per_task.

- src/bindings/python/flux/job.py
- t/python/t0010-job.py
Previously, setting the duration of a job to an integer value would raise a ValueError. Now it simply converts the int to a float.
> python: accept integer job duration

- src/common/libflux/handle.c
- t/Makefile.am
- t/issues/t2711-rpc-in-aux-item-destructor.sh
- t/loop/issue2711.c
This PR is split off #2710. It fixes two issues discussed there:
1. Prevent use of flux_send and its derivatives during handle destruction (e.g. in aux_item destructors). Attempts to send messages when the handle is being destroyed will now return ENOSYS.
2. Fix potential re-entry into `flux_handle_destroy()` by adding a `destroy_in_progress` flag to flux handles.
Also adds a trivial testcase that segfaulted before these fixes.
> libflux: disallow message send; prevent segfaults during flux_handle_destroy()

- src/broker/broker.c
- src/broker/module.c
- src/broker/module.h
As described in #2709, there exists a potential broker deadlock during module unload if the broker tries to send a message to a module after it has closed its handle, but before  the module is removed from the modhash.
This PR introduces a "muted" flag for modules, which allows the broker to disable message send to modules while they are in the process of exiting. The documented but unused RFC 5 `FLUX_MODSTATE_FINALIZING` module state is used by modules to request from the broker that they be muted, and modules synchronize by waiting for the broker to reply that the mute operation is complete. After this synchronization, the module continues along the existing shutdown path.
There was one other bit of cleanup in the module state handling, since modules no longer go directly from `INIT` to …
> broker: add FINALIZING state to address possible module unload deadlock

- src/common/libflux/composite_future.c
- src/common/libflux/test/composite_future.c
This PR has a couple minor fixes for composite futures pulled out of some other work for the sake of release notes.
* Allow a `NULL` `name` parameter in `flux_future_push (flux_future_t *f, const char *name, flux_future_t *child)`, in which case a sequence string is assigned. It was annoying when pushing indistinct futures into a composite to have to come up with names for them.
* Make sure an empty "wait all" future is fulfilled immediately as you might suspect. Before `flux_future_wait_for` would hang on an empty composite wait_all.
> libflux: minor improvements for composite futures

- src/broker/module.c
- src/modules/job-ingest/validate.c
- src/modules/job-ingest/worker.c
- src/modules/job-ingest/worker.h
- t/Makefile.am
- t/ingest/bad-validate.sh
- t/t2200-job-ingest.t
Ok, this is the PR from which the past 3 or 4 PRs have spawned. The idea was to fix just a few minor issues in the job-ingest modules management of its validation workers. These fixes include:
* When logging, print the basename of the script, not of the python interpreter.
* When the validator script unexpectedly exits, don't "leave the submitter hanging"
* Signal any active worker processes on module unload, o/w they will stay running for-evah
Also, this fixes a *very bad no good* bug I introduced in #2710: When messages to modules were dropped due to `p->muted` a debug message was logged, but unfortunately *using the module's flux_t handle*! This caused Bad Things:tm: when the broker and the module used the handle at the same time :frowning_face:
For now I just dropped the debug …
> job-ingest: fixes for validation worker management

- AUTHORS
- etc/rc3
- src/cmd/flux-job.c
- src/cmd/flux-queue.c
- src/common/libflux/response.c
- src/common/libflux/response.h
- src/common/libflux/test/response.c
- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/drain.c
- src/modules/job-manager/drain.h
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/restart.c
- t/rc/rc3-job
- t/t2208-queue-cmd.t
This PR provides a command `flux queue idle`, similar to `flux queue drain`, that waits until there are no pending alloc requests to the scheduler, and no jobs in RUN or CLEANUP state.  One can now cleanly terminate running work when shutting down an instance with
```console
$ flux queue stop
$ flux job cancelall -f --states=RUN
$ flux queue idle
```
The `stop` prevents the job manager from sending new alloc requests to the scheduler, and sends cancel messages for any pending ones.  The `cancelall` terminates running work.  The `idle` then blocks until the canceled jobs have transitioned to INACTIVE state (with eventlogs etc committed to the KVS).
I added this sequence to rc3 (speculatively).
As discussed in #2649, in a system instance this could be preceded with something like
```
$ flux …
```
> flux-queue: add idle subcommand

- src/modules/job-ingest/worker.c
As described in #2718, a race was introduced in PR #2716 in the handling of unexpected subprocess exits. If a process exiting normally races with the startup of a new process, the request for the new process is rejected with "validator exited unexpectedly"
This PR fixes that issue, as well as fixing a minor related issue in `worker_completion_cb`
> job-ingest: fix handling of unexpected validation worker exit

- src/bindings/python/flux/job.py
- src/cmd/flux-mini.py
- t/job-manager/submit-sliding-window.py
- t/job-manager/submit-wait.py
- t/job-manager/submit-waitany.py
- t/job-manager/wait-interrupted.py
This PR follows through on a suggestion in #2717 for a better public interface in `job.submit()` and `job.submit_async()`.  Add boolean `debug` and `waitable` flags so that user's don't have to OR values from `flux.constants`, which is more verbose and error prone.
I left the optional `flags` argument alone for now since using the binary flags would actually be slightly more code in `flux-mini.py`, and to avoid breaking just-committed workflow examples.  Maybe we should just go full speed ahead and get rid of it?
Feedback welcome.
> bindings/python: add boolean flags to job.submit(), submit_async()

- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- t/t2204-job-info.t
PR #2655 introduced a bug in which pending jobs were not ordered correctly.  This fixes it & adds tests & some extra comments.
Confirmed that the tests passed on a tree that was before #2655 as well.
> job-info: Fix pending jobs ordering

- src/modules/sched-simple/sched.c
- src/test/sched-bench.sh
- t/sharness.d/flux-sharness.sh
- t/t2300-sched-simple.t
This is some experimental work I had laying around to add a simple queue in sched-simple so that `unlimited` alloc mode can be implemented (mostly for testing purposes)
I'm posting this here because it had some interesting testing results, and the selection of `unlimited` mode for the simple scheduler may help in testing flux-core facilities, and also so I don't lose track of the code.
The scheduler is still left in `single` alloc mode by default. This is because there are some ill side effects when you run many short jobs (i.e. my benchmark) with `unlimited` mode. In a larger instance, the storm of jobs moving from SCHED to RUN brings the exec system (likely the KVS) to its knees, and job throughput and interactivity suffers. There may be some easy work on batching we could do in the …
> add 'unlimited' alloc mode to simple-sched

- src/broker/pmiutil.h
This PR gets around an apparent incompatibility with openpmix's PMI compat library by increasing the PMI kvsname buffer size used in the broker.
Edit: dropped flux-pfoxy(1) since @dongahn already submitted it as a separate PR.
> broker: fix a problem bootstrapping under openpmix PMI-1 compat library

- doc/man1/flux-proxy.adoc
Problem: flux-proxy now requires "local" appended
to the end of the URI for both local and remote
connection, but the manpage still uses the old format.
Resolve Issue #2745.
> doc: use a new URI format for flux-proxy

- config/ax_compiler_version.m4
- configure.ac
- src/cmd/flux-aggregate.c
A little more testing needed, but here's the approach I came up with for fixing older Clang compile with flux-core. 
1. fix the actual bug in `src/cmd/flux-aggregate.c`
2. Disable `-Werror=missing-field-initializers` for Clang < 4.0. I assume the bug that flags acceptable static initializers was fixed by 4.x, but I have to check that before this is merged.
Fixes #2740 
Fixes #2741
> Fix compilation errors in older clang compilers

- src/bindings/python/flux/job.py
- src/cmd/flux-jobs.py
As described in #2730, this PR subclasses the return values of some of the functions exported by `flux.job` for ease of use:
* `job.wait_async()` returns `JobWaitFuture` with a custom `get_status()` getter
* `job.submit_async()` returns `SubmitFuture` with a custom `get_id()` getter
* `job.job_list` returns `JobListRPC` with a custom `get_jobs()` getter
(BTW, listing these above I notice the incongruity between the `job.` functions here. Should we rename `job.job_list` to `job.list()`?
In the case of `wait_async()` and `submit_async()`, the old functions `wait_get_status()` and `submit_get_id()` are retained since they've been around awhile.
For `job.job_list()` the `job_list_get()` function is removed after `flux-jobs.py` is updated.
Fixes #2730
> python: improve interface to flux.job functions with Future and RPC subclasses

- t/rc/rc1-job
- t/rc/rc3-job
- t/t2201-job-cmd.t
- t/t2204-job-info.t
- t/t2205-job-info-security.t
- t/t2300-sched-simple.t
- t/t2301-schedutil-outstanding-requests.t
- t/t2400-job-exec-test.t
- t/t2401-job-exec-hello.t
- t/t2402-job-exec-dummy.t
- t/t2602-job-shell.t
- t/t2606-job-shell-output-redirection.t
- t/t2607-job-shell-input.t
- t/t2800-jobs-cmd.t
This addresses issue #2739 by essentially allowing the job-exec and sched-simple modules to be loaded in `rc3-job` when `flux job cancelall -f --states RUN` is executed, so the command is able to actually terminate jobs in RUN state, avoiding a subsequent hang in `flux queue idle`.
All modules required for job execution are now loaded in the "job" `test_under_flux` personality, which long-term is probably less confusing. For the few tests that require no `job-exec` module because they need jobs to enter the RUN state without actually running, this module is removed.
One small cleanup to `t2800-job-cmd.t` was added here as well. Since jobs are terminated in `rc3-job` now, the "cleanup" section of the test was removed.
> testsuite: fix possible hangs in rc3-job by loading sched-simple,job-exec modules by default

- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/memoized_property.py
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
This is another bit of experimental work I had stashed away that I figured I'd propose as a PR.
This work doesn't change too much functionality in `flux jobs`, but it will hopefully make future additions to the utility slightly easier, as well as some other minor improvements in error handling of user-supplied formats.
I realized that parsing of Python's string.format specifiers is publicly available via a `string.Formatter` class. This PR adds an `OutputFormat` class which uses a `string.Formatter` internally to pick apart the current format and put it back together depending on context (e.g. a "string safe" version for headers, and a modified version for jobs due the 2nd change described below). Another benefit is that format string errors can be caught early (before fetching jobs and …
> flux-jobs: refactor using new JobInfo and OutputFormat classes

- src/shell/shell.c
- t/t2608-job-shell-log.t
Per discussion in #2752, quick fix to handle special case exit codes in the job shell.
> shell: Update exit code for special cases

- src/test/travis_run.sh
- t/sharness.d/flux-sharness.sh
- t/t3000-mpi-basic.t
This fixes the testsuite when under under Slurm/Flux job as described in #2749.
I found a simpler approach than the patch described there. All `PMI_*` and `SLURM_*` environment variables are scrubbed at the beginning of each test by `flux-sharness.sh`.
This is more future proof than attempting to ensure `flux start` is always run with `-s1` or `--bootstrap=selfpmi`. Additionally, it works with `flux broker` which doesn't provide a way to force singleton mode.
Additionally, the MPI tests in t3001-mpi-basic.t are not disabled by default. 
This is WIP because, while `make check` seems to be reliable within a Slurm job, there are still some tests that fail when run as a Flux job.
However, when it does work you can do this fun thing:
```
$ srun -N16 --pty --mpi=none --mpibind=off  \ …
```
> testsuite: fix tests when run as a job and disable MPI tests by default

- etc/rc1
- t/t5000-valgrind.t
This PR contains some simple changes to `rc1` to do some of its work in parallel (as worked out by @grondo in #2771).  It also increases the `flux_open()` timeout in `rc1` since some timing changes in PR #2733 make timing out more likely than before, especially under valgrind.
Drop the grace period and open timeout tunings from the valgrind sharness test, as these should no longer be necessary.
> speed up Flux instance initialization (rc1) and make it more reliable under valgrind

- src/cmd/flux-job.c
- t/Makefile.am
- t/t2501-job-status.t
In a recent meeting a question was brought up about how to get the completion status of jobs without having to do `flux job attach JOBID >/dev/null 2>&1`.
This PR adds a new `flux job status` command which fetches the `finish` event for one or more JOBIDs listed on the command line, exiting with the highest exit status over all listed jobs. This is much more heavyweight than `flux job wait`, but can be run on non-waitable jobs, or jobs on which the wait status has already been reaped from the job-manager. It is meant simply as an alternative to `flux job attach` when the user doesn't want to also dump all job output/logs/etc.
Since the command uses `flux_job_event_watch()` internally, `flux job status ID` can be run on jobs in any state. The command will return only after all listed …
> cmd: add flux-job status command to get job completion status

- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-info/job-info.c
- src/modules/job-info/list.c
- src/modules/job-info/list.h
- t/t2204-job-info.t
Per discussion on #2683, this allows callers to get a subset of the inactive jobs in the job info module.  The subset is limited via a timestamp parameter, which allows callers to only get jobs newer than an inputted timestamp (i.e. job t_inactive > inputted timestamp).
This is quite specific for the issue problem and not very generic.  I went back and forth on making it a bit more generic, but eventually came to this very specific implementation.  One of the major reasons is b/c the pending jobs list is sorted in priority order, so making a generic "limit based on timestamp" service would have to scan the entire pending jobs list.
This is built on top of issue #2720.  It could be spliced out, but given the likely conflicts, just thought it'd be easier to build on top of it.
> job-info: add new job-info.list-inactive service

- src/cmd/flux-job.c
- t/t2207-job-manager-wait.t
Here's an attempt to implement the `flux job wait --all` option suggested by @grondo in #2758.
> add flux job wait --all

- src/broker/broker.c
- src/broker/overlay.c
- src/common/libsubprocess/server.c
- src/modules/job-ingest/Makefile.am
- src/modules/job-ingest/job-ingest.c
- src/modules/job-ingest/types.h
- src/modules/job-ingest/validate.c
- src/modules/job-ingest/validate.h
- src/modules/job-ingest/worker.c
- src/modules/job-ingest/worker.h
(peeled off of #2733)
As discussed in #2751, his PR adds the zeromq ROUTER_MANDATORY flag to the ROUTER socket used to communicate with downstream (towards the leaves) TBON peers.  The this changes how the socket handles messages addressed to peers that are not connected.  Before, they would be silently dropped.  Now they cause an error that we can log. 
There is also some cleanup of the broker functions used to route messages, which had gotten a little crufty over time (or maybe weren't that great from the start).
Finally, since this change now logs errors for some expected loose response messages from the exec service following `job-ingest` validator cleanup, I added some code to try to stop validators by giving them an EOF on stdin and collect their completion info, under a 5s timeout. …
> broker: log dropped responses sent down TBON

- NEWS.md
We plan on tagging flux-core v0.16 soon, so here's a quick stab at release notes update as of now.
> NEWS.md: add release notes for flux-core v0.16

- src/modules/kvs/kvs.c
- t/t2402-job-exec-dummy.t
Per discussion in #2727.  I'll just throw up my commit message here:
```
On rank 0, we have to subscribe to all events on all KVS namespaces,
as rank 0 must have knowledge of all KVS namespaces.  On the other
hand, workers only need to know about the KVS namespaces that
callers are using on that rank.
To improve KVS namespace create performance, subscribe to all KVS
namespaces on rank 0 once on initialization, instead of subscribing
to each KVS namespace as it is created.  On workers, subscribe
to only the KVS namespaces that are necessary.
```
Also threw in a fix for #2762
> kvs: eliminate per-job namespace event subscriptions on rank 0

- src/common/libutil/cleanup.c
- src/common/libutil/cleanup.h
This PR fixes a few style anomalies in the cleanup code, and cleans up out of memory error paths.
Split from #2783 to thin that one down a bit.
> libutil/cleanup: improve out of memory handling, conform to RFC 7

- doc/man1/flux-content.adoc
- src/broker/content-cache.c
- src/modules/content-sqlite/content-sqlite.c
- t/t0011-content-cache.t
- t/t2501-job-status.t
This is primarily a refactoring and cleanup of the content-sqlite module, with a bit of content-cache involvement, in preparation for changes to come for KVS checkpoint/restart.
Splitting a (hopefully) easily digestible chunk from #2783
> content-sqlite, content-cache: cleanup and refactoring

- src/bindings/python/flux/job.py
- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/modules/job-info/list.c
- t/python/t0013-job-list-inactive.py
- t/t2204-job-info.t
As described in #2776, there is no Python binding for `flux job list-inactive`. This command is planned to be used by the Bank/Accounting interface for Flux, which for the time being is being written in Python. 
This PR proposes the following changes:
- adds a Python binding for `flux job list-inactive` so it can be used in an RPC to get job record data.
- renames the **timestamp** option to **since** to more accurately describe what the option is doing. 
- changes the default value of **max_entries** in `job_list()` to **1000** to match the default value in `job_list_inactive()` (discussed in the comments thread in #2776).
> bindings/python: add 'flux_job_list_inactive' Python binding

- src/modules/kvs-watch/kvs-watch.c
- src/modules/kvs/kvs.c
- t/t0017-security.t
Per discussion in #2779 
Did another run of experiments, over 5 runs with 1024 jobs
on master - average 67.6 jobs/s, high 68.2, low 66.9
on branch - average 67.76 jobs/s, high 69.1, low 67.1
Dunno if it was an unlucky run and perhaps NFS is busy or something, but not as good as the first set of runs I did last week.
Over 5 runs doing 4096 jobs.
on master - average 65.66 jobs/s, high 66.0, low 65.3
on branch - average 65.56 jobs/s, high 66.1, low 64.6
So average was actually worse in this case, as well as haven't the worst run.  Eek!  Dunno if my earlier runs were just lucky.
As we discussed, perhaps its still a net win on average for this change.  But it's not as obviously better than we had hoped for.
> kvs: rename kvs namespace events to limit calls to `flux_event_subscribe()`

- doc/man7/flux-broker-attributes.adoc
- etc/rc3
- src/broker/broker.c
- src/broker/log.c
- src/modules/content-sqlite/content-sqlite.c
- src/modules/kvs/kvs.c
- t/Makefile.am
- t/kvs/checkpoint.c
- t/t0001-basic.t
- t/t2010-kvs-snapshot-restore.t
Thought I'd park this although it needs further work.
This adds a table to the content-sqlite database that can store arbitrary key-value pairs, then modifies the KVS to read its root blobref from this table (if available) during startup, and write its final root blobref during shutdown.  In the future, the table could accommodate multiple keys for live namespaces if we want to go that way (but right now we don't need to support that).
If an instance has the `content.backing-path` attribute set to the path to a sqlite file when the content-sqlite module is loaded, then it is used (existing content preserved).  If it is set but the file does not exist, it is created empty, and retained on exit.
The net result is the systemd unit file _could_ set this attribute to say …
> add KVS checkpoints

- doc/man1/flux-dmesg.adoc
- doc/man3/idset_create.adoc
Fixes two trivial documentation typos.
> doc: Fix typos in man pages

- src/common/libsubprocess/command.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/subprocess.c
This changes the cmd and subprocess destructors to avoid clobbering errno, and fixes a couple of cases of unchecked `calloc()` return value.
Peeled off of #2794
> libsubprocess:  don't clobber errno in destructors, handle ENOMEM

- src/broker/broker.c
- src/broker/modservice.c
- src/broker/ping.c
- src/broker/ping.h
- src/common/libflux/message.c
This fixes problems with the ping response generated for the broker and modules, as described in #2281 
Before:
```console
$ flux ping kvs
kvs.ping pad=0 seq=0 time=0.550 ms (09df78ee-5eeb-4642-b9c5-76f880b2f0c4!55c52d64-1ebd-460e-96d3-b74b7c5ca2aa!0!0)
kvs.ping pad=0 seq=1 time=0.637 ms (09df78ee-5eeb-4642-b9c5-76f880b2f0c4!55c52d64-1ebd-460e-96d3-b74b7c5ca2aa!0!0)
kvs.ping pad=0 seq=2 time=0.637 ms (09df78ee-5eeb-4642-b9c5-76f880b2f0c4!55c52d64-1ebd-460e-96d3-b74b7c5ca2aa!0!0)
```
after
```console
$ flux ping kvs
kvs.ping pad=0 seq=0 time=1.006 ms (8966cd4a!4d6e745a!0!5a516989)
kvs.ping pad=0 seq=1 time=1.220 ms (8966cd4a!4d6e745a!0!5a516989)
kvs.ping pad=0 seq=2 time=1.260 ms (8966cd4a!4d6e745a!0!5a516989)
```
Now the output more or less matches the example in the `flux-ping(1)` man …
> flux-ping: fix problems with route string

- src/broker/broker.c
- src/broker/runlevel.c
- src/broker/runlevel.h
- t/rc/rc1-testenv
- t/t0001-basic.t
- t/t0014-runlevel.t
This PR preps for a clean Flux shutdown on SIGTERM, which is how systemd will shut down the broker.
First, eliminate the requirement that there is always an initial program.  If the `broker.rc2_none` broker attribute is set, the broker enters rc2 and stays there until...
Second, handle SIGTERM (and other signals) by aborting the current runlevel.  If the runlevel has a subprocess, it is terminated (resulting in the broker exiting with a nozero exit code).  If it doesn't have a subprocess, it simply advances to the next runlevel without error.
The runlevel code was tidied up, some little used runlevel features removed, and minor runlevel bugs fixed.
Combining this PR and #2783 I was finally able to demonstrate saving the KVS content across a systemd stop/start of Flux. 
Edit: description …
> broker: clean shutdown on SIGTERM, add broker.rc2_none attribute

- doc/man1/flux-kvs.adoc
- src/cmd/flux-kvs.c
- src/test/sched-bench.sh
- t/issues/t0441-kvs-put-get.sh
- t/issues/t0821-kvs-segfault.sh
- t/kvs/kvs-helper.sh
- t/sharness.d/flux-sharness.sh
- t/t0017-security.t
- t/t1000-kvs.t
- t/t1001-kvs-internals.t
- t/t1003-kvs-stress.t
- t/t1004-kvs-namespace.t
- t/t1005-kvs-security.t
- t/t2100-aggregate.t
Per #2796, remove legacy `--json` options in flux kvs and remove json output from `flux kvs dir`.
The meat of this PR is the changing on the tests, which is in 1 huge commit.  Outside of just removing the `--json` calls, there had to be tweaks to the tests and the removal of a few that were `--json` specific.
> cmd/flux-kvs: Remove legacy --json options and json output

- src/broker/broker.c
- src/cmd/flux-job.c
- src/common/librouter/servhash.c
- src/shell/svc.c
- t/shell/mpir.c
- t/t0017-security.t
- t/t2610-job-shell-mpir.t
As discussed in #2385, this PR prepares for multi-user by reducing the allowable service names that can be registered by guests to names prefixed with `<userid>-`.  This prevents users from interfering with each others' shell services, and with instance services.  The shell service is renamed to `<userid>-shell-<jobid>` and is now emitted in the `guest.exec.eventlog` `shell.init` event and picked up by `flux job attach`.
I had to change `t/shell/mpir` to get the service name from the  eventlog instead of deriving it from the job id.  My guess is changes pending in #2654 will need adjustment too?
Edit:  I should probably squash the shell, flux-job, and related test changes into one commit to avoid breaking git-bisect.  Also I missed closing #2385 in any of the commits.  I'll leave the …
> broker: only allow "<userid>-" prefixed services to be registered by guests

- etc/flux.service.in
- etc/rc3
- src/broker/broker.c
- src/broker/runlevel.c
Systemd unit file changes needed to stop flux cleanly via `systemctl stop flux` with reasonable logs and KVS content preserved.
This needs some more testing hence the WIP.  My initial results were that `TimeoutStopSec` needed to be set to avoid an immediate second SIGTERM, but I just saw that behavior recurring with `TimeoutStopSec` set.   More poking needed.
This relies on features of PR #2794
> systemd: add broker options for simple system instance support

- t/t0005-exec.t
Increase timeout lengths of all tests to work around timeouts
in slow travis runs.
Fixes #2827
> t/t0005-exec: Increase timeout lengths

- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- t/Makefile.am
- t/t2402-job-exec-dummy.t
- t/t2403-job-exec-conf.t
- t/t2602-job-shell.t
- t/t2608-job-shell-log.t
This PR switches the job-exec module away from using broker attributes for "configuration" to using config file and/or module cmdline args. The standard precedence is observed, the conf file overrides build-time defaults, and the cmdline overrides the config (or defaults if config not set).
The only two config parameters in the `job-exec` module were mainly for testing, and included the job-shell path and "kill timeout" for jobs (interval after the first SIGTERM when SIGKILL will be sent), so there is not much user visible change here. However, this prepares the way for a coming required config parameter, the path to the IMP.
As a side benefit, two calls to `flux_attr_get(3)` that were made *for every job* are removed as a result.
> job-exec: drop use of broker attrs, use conf file or cmdline instead

- etc/rc1
- src/common/libutil/fluid.c
- src/common/libutil/fluid.h
- src/common/libutil/test/fluid.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/restart.c
- src/modules/job-manager/restart.h
- src/modules/job-manager/submit.c
- t/Makefile.am
- t/ingest/job-manager-dummy.c
- t/rc/rc1-job
- t/t2200-job-ingest.t
- t/t2202-job-manager.t
- t/t2203-job-manager-dummysched.t
- t/t2300-sched-simple.t
- t/t3200-instance-restart.t
As discussed in #2816 and #1545, the job-ingest module may issue duplicate jobid's if the module is reloaded on a live system, or if the instance restarts.
This PR adds the ability to start a FLUID generator at an initial timestamp other than zero.
The job manager now tracks the highest valid jobid and allows it to be queried by an RPC.  The job manager ensures this value remains valid across instance restart by saving it inside a JSON object to `checkpoint.job-manager`, which it reads back in on startup, if it exists.
The job ingest on rank 0 queries this `max_jobid` on startup and uses it to form the initial timestamp for its FLUID generator.   Job ingest on rank > 0 query the current timestamp for an upstream job-ingest module and use that to initialize their FLUID generator.
This adds …
> job-ingest: ensure duplicate jobids are not issued across instance restart

- t/t0013-config-file.t
Rather than repeatedly waiting for all processes, wait for specific pids
launched in the test, this appears to work around the hang I was
experiencing.
I *think* this resolves #2834, but I'm not sure *why* it resolves it or 100% sure that it does since I can't completely reliably replicate the original issue.
> test: explicitly wait on specific pids config-test

- .mergify.yml
Problem: The move of flux-core Travis-CI testing from travis-ci.org
to travis-ci.com changed the name of the status check, so mergify
cannot merge any PRs.
Update the name of the Travis status check to fix mergify.
This PR will need to be manually merged.
> mergify: update travis-ci check name

- src/bindings/python/flux/job.py
- src/modules/job-info/list.c
- t/python/t0013-job-list-inactive.py
I just thought I'd throw this up for comments before I write tests.  (For Issue #2817)
- it's clearly just a hack for the need mentioned in https://github.com/flux-framework/flux-sched/pull/621
- There's nothing wrong with it per se, but am concerned with the long term.  What if we need to filter on more than this.  Perhaps there should be something more extendable for filtering, for this and normal job list?  Hypothetically something like `filter="name:hostname,userid:13543"`?
- But the above would take time.  Do we consider this an acceptable short term solution?
> job-info: filter job list inactive results by name

- .travis.yml
- config/tap-driver.sh
This is an alternative to #2833, it's immensely simpler but only works when the test is run under the automake test harness, and only works for full test executables.
> tests: timeout in automake harness

- README.md
We recently switched from travis-ci.org to travis-ci.com. Update the CI badge link accordingly.
> README: update Travis CI badge after transition to travis-ci.com

- src/cmd/flux-kvs.c
Fix segfault in flux-kvs dir -R due to pass of full value to
kv_printf() instead of outputting it as a string.
Add format check to kv_printf() and correct several other locations
that passed values to kv_printf() incorrectly.
Fixes #2830
> cmd/flux-kvs: Fix segfault in dir -R

- .travis.yml
- config/tap-driver.sh
- t/Makefile.am
- t/python/t0003-barrier.py
- t/scripts/run_timeout.py
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t0014-runlevel.t
- t/t0016-cron-faketime.t
- t/t1101-barrier-basic.t
- t/t1103-apidisconnect.t
- t/t2204-job-info.t
Test fixes originally from the #2836 PR, should make python barriers clean up and timeout correctly, also allows job-info tests to time out, removes an implicit dependency on perl, and fixes possible headaches with handled SIGALRM and run_timeout.
@grondo, if you'd like to do a rollup with some of the test fixes you mentioned feel free to add on.
> test rehab: new flexible run_timeout, speeding up asan, and many more timeouts and test repairs

- .github/workflows/main.yml
- .mergify.yml
- .travis.yml
- src/bindings/python/flux/job.py
- src/bindings/python/flux/security.py
- src/cmd/flux-job.c
- src/common/liboptparse/optparse.h
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/bulk-exec.h
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/test/docker/docker-run-checks.sh
- src/test/docker/travis/Dockerfile
- t/Makefile.am
- t/job-exec/imp.sh
- t/scripts/sign-as.py
- t/t2403-job-exec-conf.t
- t/t2404-job-exec-multiuser.t
This PR tweaks the job-exec 'exec' implementation to attempt to run the IMP for any multiuser job requests, i.e. those where job->userid != getuid().
The `exec.imp` config parameter must be set to a path of a `flux-imp` installed setuid for multiuser to be enabled. Currently, if the IMP isn't configured, multi-user job requests get an exec exception at start. `exec.imp` can be overridden by `imp=` on the module load cmdline.
This PR implments the bare minimum to get this working. We need to re-architect the  job-exec module soon anyway, so it wouldn't be prudent to spend extra time with an optimal integration.
The PR is still a WIP so I can add at least *some* testing.
Edit: this is built on top of #2821 
Also edit: the current work here doesn't check if the `flux_imp_path` is actually …
> job-exec: minimal support for multiuser exec

- doc/man1/flux-jobs.adoc
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
- t/flux-jobs/tests/issue#2634/format
- t/t2800-jobs-cmd.t
Per issue #2859, create a new conversion type to output a hyphen (`-`) instead of several special cases when data is not yet available (such as "0s" or an empty string).
This allows us to remove the `_hyphen` format specifiers throughout the code and tests, which began to explode in PR #2831 and #2858.
note to self: #2831 and #2858 will have to be adjusted
> flux-jobs: Add custom conversion type to output '-'

- configure.ac
- src/bindings/python/_flux/Makefile.am
- src/bindings/python/_flux/_core_build.py
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/debugged.py
- src/cmd/Makefile.am
- src/cmd/flux-job.c
- src/cmd/flux-mini.py
- src/common/Makefile.am
- src/common/libdebugged/Makefile.am
- src/common/libdebugged/debugged.c
- src/common/libdebugged/debugged.h
- src/common/libdebugged/test/test_debugged.c
- src/common/libflux-core.map
- src/shell/mpir/nodelist.c
- t/Makefile.am
- t/debug/stall.c
- t/t2611-debug-emulate.t
This PR is work in progress. At least three things are required before it can be merged.
- `flux-info` module provides a single job query, an equivalent of ba95bf6 and 
6068c24. Tagging @chu11 and @grondo for this as this is their planned task.
- I need to find a way to disable compilers to optimize (e.g., inlining) `MPIR_Breakpoint` (fec88d6) so that this function can remain empty as it should. (Currently, I added two printf statements lest totalview cannot reliably get its MPIR_Breakpoint event). Tagging @jdelsign in case he has some insight. 
- Test this on the LC environment as I did my manual totalview testing under my docker development environment. 
Having said that, this PR adds MPIR front-end support for parallel debuggers like totalview.
- Add the MPIR debug interface within …
> mpir: add front-end support for parallel debugging

- src/shell/input.c
- src/shell/output.c
- src/shell/shell.c
- t/t2610-job-shell-mpir.t
Wrap all message handlers registered with `flux_shell_service_register(3)` and check `shell_svc_allowed` before calling the real msg handler. This makes shell services accessible only to the shell user (and instance owner) by default, instead of having services "open to all" when first registered. This should greatly reduce the potential for accidental security vulnerabilities introduced by shell plugins.
If ever there is a need for a shell service that is open to all users, we can add a new shell.h API call which *explicitly* registers a multiuser accessible service.
> shell: make registered services secure by default

- src/bindings/python/flux/future.py
- src/bindings/python/flux/rpc.py
- src/bindings/python/flux/wrapper.py
Rather than caching in the instance, this should remove dangling
reference issues like in #2671, and hopefully also be somewhat faster in
that the lookup happens once per *type* rather than once per *instance*.
I'm not sure where best to put this, but hopefully it will address some of the weakref issues.
> python: cache python wrappers in the class

- doc/man1/flux-jobs.adoc
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/job_util.c
- src/modules/job-info/list.c
- t/t2204-job-info.t
- t/t2800-jobs-cmd.t
Just throwing this up for some initial reactions.
Support a new "success" attribute in the job list service, which simply returns True / False if a job completed successfully (status = 0 on `finished` in the eventlog).  I sort of dislike the attribute name of "success", but I couldn't really think of anything better.  I'll mull over that.
Added a new "success" and "success_hyphen" format option to `flux-jobs`, nothing too exciting
there.  Example output:
```
>flux jobs -A --format="{id} {success}"
JOBID SUCCESS
109734619250688 
10590399496192 True
335712092160 False
293936824320 True
```
```
>flux jobs -A --format="{id} {success_hyphen}"
JOBID SUCCESS
109734619250688 -
10590399496192 True
335712092160 False
293936824320 True
```
The interesting addition, which no idea if I did it well or …
> job-info: Support new "success" attribute

- etc/flux.service.in
- src/broker/broker.c
- src/broker/brokercfg.c
- src/broker/brokercfg.h
- src/broker/module.c
- src/broker/module.h
- src/cmd/Makefile.am
- src/cmd/builtin/config.c
- src/common/libflux/conf.c
- src/common/libflux/conf.h
- src/modules/connector-local/local.c
- t/t0017-security.t
This PR implements a command `flux config reload` which synchronously reloads the TOML config (e.g. after a change on disk).  It is wired into the system unit file via `ExecReload=` so `systemctl reload flux` works.
The `flux config reload` command seds a `config.reload` RPC to the broker.  The broker responds by 1) re-parsing TOML config, and 2) sending a  `<name>.config-reload` RPC to each loaded module.  The module may optionally implement a handler for this if it is capable of handling config changes on the fly.  Once the modules respond, a response is sent back to the command.
The `connector-local` `[access]` config now implements this handler.
Error handling:
* If TOML parsing fails, a textual error is sent back to the command and the broker continues on with the existing config.
* …
> support systemctl reload flux

- doc/man1/flux-jobs.adoc
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/job_util.c
- src/modules/job-info/list.c
- t/t2204-job-info.t
- t/t2800-jobs-cmd.t
Build on top of PR #2831, support 4 new job listing attributes, "exception", "exception_severity", "exception_type", and "exception_note".  Hopefully what these are don't require explanation.
If an exception occurred, return true/false for `exception`.  if true, the others will contain the values for the highest severity and the type/note that went along with it.
```
>flux jobs -A --format="{exception},{exception_severity},{exception_type},{exception_note}"
EXCEPTION,EXCEPTION-SEVERITY,EXCEPTION-TYPE,EXCEPTION-NOTE
True,0,exec,task 0: start failed: fdasfdasf: No such file or directory
```
I'm not the most excited about the long format names and the headers, but just put those in for place holders.  Wasn't sure of the best abbreviation ... google says abbreviation is "exc", but my gut says …
> job-info: Support new "exception" list attributes

- doc/man3/Makefile.am
- doc/man3/flux_shell_add_completion_ref.adoc
- doc/man3/flux_shell_add_event_context.adoc
- doc/man3/flux_shell_add_event_handler.adoc
- doc/man3/flux_shell_aux_set.adoc
- doc/man3/flux_shell_current_task.adoc
- doc/man3/flux_shell_get_flux.adoc
- doc/man3/flux_shell_get_info.adoc
- doc/man3/flux_shell_getenv.adoc
- doc/man3/flux_shell_getopt.adoc
- doc/man3/flux_shell_killall.adoc
- doc/man3/flux_shell_log.adoc
- doc/man3/flux_shell_plugstack_call.adoc
- doc/man3/flux_shell_rpc_pack.adoc
- doc/man3/flux_shell_service_register.adoc
- doc/man3/flux_shell_task_channel_subscribe.adoc
- doc/man3/flux_shell_task_get_info.adoc
- doc/man3/flux_shell_task_subprocess.adoc
- doc/test/spell.en.pws
These will need to be converted to rst.  Several files cover multiple functions; there should be one file per function eventually.
Here is the list of new files:
flux_shell_add_completion_ref.adoc
flux_shell_add_event_context.adoc
flux_shell_add_event_handler.adoc
flux_shell_aux_set.adoc
flux_shell_current_task.adoc
flux_shell_get_flux.adoc
flux_shell_get_info.adoc
flux_shell_getenv.adoc
flux_shell_getopt.adoc
flux_shell_killall.adoc
flux_shell_log.adoc
flux_shell_plugstack_call.adoc
flux_shell_rpc_pack.adoc
flux_shell_service_register.adoc
flux_shell_task_get_info.adoc
flux_shell_task_subprocess.adoc
> doc: add flux job shell API manpages

- configure.ac
- doc/man3/flux_shell_get_info.adoc
- src/cmd/Makefile.am
- src/cmd/flux-job.c
- src/cmd/flux-terminus.c
- src/common/Makefile.am
- src/common/libterminus/Makefile.am
- src/common/libterminus/client.c
- src/common/libterminus/pty.c
- src/common/libterminus/pty.h
- src/common/libterminus/terminus.c
- src/common/libterminus/terminus.h
- src/common/libterminus/test/pty.c
- src/common/libterminus/test/terminus.c
- src/common/libtestutil/util.c
- src/common/libutil/Makefile.am
- src/common/libutil/llog.h
- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/pty.c
- src/shell/shell.c
- src/shell/shell.h
- src/shell/svc.c
- src/shell/svc.h
- t/Makefile.am
- t/scripts/runpty.py
- t/sharness.d/01-setup.sh
- t/sharness.d/flux-sharness.sh
- t/t0020-terminus.t
- t/t2612-job-shell-pty.t
This PR introduces the *simple* pty support for Flux jobs mentioned in #282 (wow has it really been 5 years). It started out as an attempt to tunnel a basic terminal session manager like [`dtach`](https://github.com/crigler/dtach) or [`abduco`](https://github.com/martanne/abduco) over flux message endpoints, but it ended up being much easier to implement a clone of these utilities, rather than implementing something like transparent Unix domain socket tunneling.
At some point in the future we can implement a more featured solution using a per-job ssh and/or tmux session to get perfect pty support, but for now this interim solution should work for the 90% use case.
Try:
```
$ flux mini run -o pty bash
```
also
```
$ flux terminus start
^\ # (detach)
$ flux terminus list
server at …
```
> initial pty support

- t/scripts/runpty.py
- t/t2612-job-shell-pty.t
This will hopefully fix the race in final set of tests in `t2612-job-shell-pty.t` that we've been seeing in Travis.
> testsuite: fix racy job-shell pty test

- src/cmd/flux-job.c
This is a stupid fix.  i realized the new "success" and "exception" attrs were not supported in `flux job list inactive` or `flux job list-ids`, b/c I forgot to copy them in there.
I could stick this into another PR, but it seemed to be independent of other work.
> cmd/flux-job: Use common attrs for list cmds

- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/test/message.c
As discussed in #2900, add a `struct json_error_t` to `struct flux_msg` to capture the last error string from message pack/unpack functions. One drawback I hadn't considered is that this adds about 252 bytes to the allocated size of every `flux_msg_t`.
I didn't update any of the call sites. I figure maybe this could be done on an as needed basis, but could be convinced otherwise.
> libflux: add flux_msg_last_json_error()

- src/broker/broker.c
- src/broker/hello.c
- src/broker/hello.h
- src/broker/test/hello.c
- src/cmd/builtin/comms.c
- t/Makefile.am
- t/t0023-comms.t
This PR modifies the "hello" protocol so that it reduces idsets rather than counts, and then adds an RPC that allows the current set of live brokers to be monitored.  It also adds a 'flux comms idset [--watch]' utility interface.
At the moment, the hello protocol waits for all brokers to report in, then starts rc1, so practically speaking, this will currently only return a "full" idset.  However that will change once #2641 is solved and brokers start up independently.
This may be useful for building the `resource` module described in #2908, which would provide execution target availability to schedulers, and fetch hwloc resource data on demand, or as targets come online.
TODO: tests
> broker: add interface for monitoring broker liveness

- src/broker/Makefile.am
- src/common/libioencode/Makefile.am
- src/common/librouter/Makefile.am
- src/common/libsubprocess/Makefile.am
- src/common/libterminus/Makefile.am
- src/modules/job-exec/Makefile.am
- src/modules/job-manager/Makefile.am
- src/modules/kvs/Makefile.am
- src/modules/sched-simple/Makefile.am
- src/shell/Makefile.am
- t/t0001-basic.t
As described in #2916, add the libtool `-no-install` flag to all unit tests that were currently being built with libtool wrappers. This not only removes the built wrapper scripts, but also fixes the issue where some unit tests were being built against installed flux libs when using `--with-flux-security`.
I wanted to add a `make check` test to ensure no unit tests are built with libtool wrappers in the future, but the `check-local` target runs at the wrong time during the build, so I ended up adding a test to `t0001-basic.t`. Not sure if that is an acceptable approach...
> ensure unit tests do not link against installed flux libraries

- src/broker/broker.c
- src/broker/module.c
- src/broker/module.h
- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/response.c
- src/common/libflux/rpc.c
- src/common/libflux/test/message.c
- src/common/librouter/disconnect.c
- t/Makefile.am
- t/disconnect/watcher.c
- t/request/req.c
- t/request/treq.c
- t/t1103-apidisconnect.t
This PR solves two long standing problems:
1) Unlike clients of `connector-local`, modules that are unloaded do not cause `<service>.disconnect` messages to be sent to services used by the module, so modules using some services (for example KVS watch) would cause services to leak state when the modules are unloaded.
2) There is no way for the sender of a request to tell the recipient that a response should not be sent.  As a consequence, services that don't implement `disconnect` methods automatically respond to them with ENOSYS.
A new message flag: FLUX_MSGFLAG_NORESPONSE is added, and `flux_rpc*()` now sets this in requests when FLUX_RPC_NORESPONSE is specified.  If `flux_respond*()` is called on a message with this flag, the response is suppressed without error.
Disconnect messages now …
> broker: send <service>.disconnect requests on module unload

- README.md
As caught by @SteVwonder in #2921, the documented required version of Lua doesn't include 5.3. This PR simply adjusts the requirements table to allow 5.3.x.
> README.md: fix required Lua version

- src/test/docker/docker-run-checks.sh
- src/test/docker/travis/Dockerfile
- src/test/docker/travis/entrypoint.sh
This PR adds an `ENTRYPOINT` to the flux-core docker images published from travis-ci which starts munged and runs its arguments by default, simply:
```sh
#!/bin/sh
sudo runuser -u munge /usr/sbin/munged
exec "$@"
```
`CMD`is set to `flux start /bin/bash` by default, and since `CMD` is passed to `ENTRYPOINT`, the docker image now runs `/usr/bin/flux start /bin/bash` when run with no arguments. If you pass args on the cmdline, this overrides `CMD`, so this also works:
```
$ docker run -ti fluxrm/flux-core flux start -s 4 bash
flux@01b99e4e0e24:~$ flux getattr size
4
flux@01b99e4e0e24:~$ flux mini run -N4 -n4 hostname
01b99e4e0e24
01b99e4e0e24
01b99e4e0e24
01b99e4e0e24
```
or, simply
```
$ docker run -ti fluxrm/flux-core bash
flux@01b99e4e0e24:~$ flux getattr size
flux: flux_open: No such …
```
> docker: start munge in published docker images

- src/test/docker/bionic/Dockerfile
- src/test/docker/docker-run-checks.sh
- src/test/docker/travis/Dockerfile
- src/test/docker/travis/bashrc
Based on a suggestion by @trws and @dongahn, add a default `PS1` to our published docker images that gives a hint to users that they are dropped into a flux instance of size=1.
```console
$ docker run -ti fluxrm/flux-core
ƒ(s=1,d=0) flux@5c453629442b:~$ flux mini run -n4 -o pty flux start
ƒ(s=4,d=1) flux@5c453629442b:~$ flux mini run -n2 -o pty flux start
ƒ(s=2,d=2) flux@5c453629442b:~$ 
```
Also includes `,builddir` if flux is running out of a build directory:
```console
ƒ(s=1,d=0) flux@5b2a9c5ab824:~/flux-core.git$ src/cmd/flux start -s 8
ƒ(s=8,d=0,builddir) flux@5b2a9c5ab824:~/flux-core.git$ 
```
> docker: add default PS1 that includes flux instance size, depth

- README.md
Point to the readthedocs site which is more up-to-date at this point.
> README: update documentation link

- src/common/librouter/Makefile.am
- src/common/librouter/test/usock_epipe.c
- src/common/librouter/usock.c
- src/common/librouter/usock.h
As described in #2931, there is a potential for dropping messages from api socket clients that write messages and immediately exit or call `flux_close()`. This happens if the connector-local module (a usock_server) gets EPIPE writing messages *to* a client before it reads pending messages *from* the client. The connection is immediately torn down in this case instead of reading any pending data from the client.
This patch adds specific handling for EPIPE. <essages to the client are dropped and the output watcher is stopped, but the connection is not destroyed until EOF/ECONNRESET is received when *reading* from the client. (I think this is guaranteed since we don't have partial close).
It took a bit to come up with a good reproducer. In order to synchronize properly in the tests, I had to …
> librouter: avoid dropping messages on EPIPE

- t/t2204-job-info.t
- t/t2603-job-shell-initrc.t
- t/t2610-job-shell-mpir.t
- t/t2612-job-shell-pty.t
- t/t2700-mini-cmd.t
Add missing `HAVE_JQ` test prereq to various tests that fail when `jq` is not installed.
Closes #2935
> t: add `HAVE_JQ` prereq to tests that use `jq`

- src/modules/job-info/job_state.c
- src/modules/job-info/list.c
- t/t2204-job-info.t
- t/t2800-jobs-cmd.t
Splicing out a few cleanups + test enhancements from #2926
- remove dead code
- add some missing tests
- refactor a little code in job-info
- add "failed job" and "cancelled job" tests to t2204-job-info and t2800-jobs-cmd
> job-info: module & test cleanup

- .travis.yml
- src/test/docker/docker-run-checks.sh
- t/sharness.d/flux-sharness.sh
- t/t0002-request.t
- t/t0017-security.t
- t/t0021-flux-jobspec.t
- t/t0022-jj-reader.t
- t/t2005-hwloc-basic.t
- t/t2100-aggregate.t
- t/t2200-job-ingest.t
- t/t2202-job-manager.t
- t/t2204-job-info.t
- t/t2400-job-exec-test.t
- t/t2402-job-exec-dummy.t
- t/t2404-job-exec-multiuser.t
- t/t2500-job-attach.t
- t/t2603-job-shell-initrc.t
- t/t2605-job-shell-output-redirection-standalone.t
- t/t2610-job-shell-mpir.t
- t/t2611-debug-emulate.t
- t/t2700-mini-cmd.t
- t/t2800-jobs-cmd.t
- t/t3001-mpi-personalities.t
As described in #2935 add a way for the testsuite to check that use of `jq` occurs either under `HAVE_JQ` or in a tests script that would otherwise be skipped if `jq` is not present.
This is done by optionally creating a wrapper script in `$SHARNESS_TRASH_DIRECTORY/bin` for each prereq (currently, only `jq`), and putting that directory first in `PATH`. The script(s) check that an appropriate prereq occurs in `test_prereq` environment variable, and invoke the real program if so. Otherwise an error is generated.
The above works for `HAVE_JQ`, but fails when entire test script is skipped at the top due to missing prereq. For this case, a new `skip_all_unless_have()` function is added, which replaces the existing duplicated tests for `jq` with subsequent `skip_all`, and additionally exports a …
> testsuite: add ability to ensure programs are used under appropriate prereqs

- t/sharness.d/flux-sharness.sh
As described in #2938, use of `$jq` subverts the `TEST_CHECK_PREREQS` wrapper script.
This PR fixes the issue by redirecting `$prog` to the wrapper script instead of the original program when `TEST_CHECK_PREREQS` is active.
> sharness: fix TEST_CHECK_PREREQS for tests using $jq

- doc/man1/flux-jobs.adoc
- doc/test/spell.en.pws
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
- t/t3200-instance-restart.t
Per discussion in #2869, add a "derived state" output to `flux-jobs` that is easier for users to understand.  I decided to call the output field "status".  The "status" outputs can be PENDING, RUNNING, COMPLETED, FAILED, CANCELLED, or UNKNOWN. 
Here's a simple output example with the output format `{id:>18} {state:<8.8} {status:<10.10}`
```
13345621016576 SCHED    PENDING   
13337601507328 RUN      RUNNING   
13329951096832 RUN      RUNNING   
13325219921920 RUN      RUNNING   
966870958080 INACTIVE COMPLETED 
945379344384 INACTIVE COMPLETED 
1226951360512 INACTIVE CANCELLED 
802152251392 INACTIVE CANCELLED 
544034783232 INACTIVE FAILED    
```
I'm incredibly happy with how simple this was to implement, all the work on refactoring so many things + the new info fields `success` and …
> cmd/flux-jobs: Add 'status' field output

- doc/man1/flux-jobs.adoc
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
Built upon PR #2910 and utilizing the "result" attribute,  colorize "completed" and "failed" jobs green/red accordingly.  It's a super simple patch (just the last one in this commit stream).
- Added a `--color` option which takes `never` or `auto` as args, modeled it after the `ls --color` option.
- I decided not to color cancelled jobs, maybe I should?  I figure cancelled jobs, the user cancelled for a reason and knows.  They could be red?  Or another color?
- It'd be easy to support a configuration (environment variable or option) where we have rules to say "completed=34;failed=36" or whatever, where users can select color via the ansi code.  Easy to parse and easy to check inputs and then use in escape codes.  Feels like too much for now, given I'm only colorizing two outputs, but …
> flux-jobs: color completed, failed, cancelled jobs

- t/t2800-jobs-cmd.t
Fix race in test where `grep -o` should be used to count
occurrences of a string, not lines containing the string.
Fixes #2950
> t/t2800-jobs-cmd: Fix racy test

- configure.ac
- src/modules/Makefile.am
- src/modules/job-archive/Makefile.am
- src/modules/job-archive/job-archive.c
- t/Makefile.am
- t/job-archive/query.py
- t/t2220-job-archive.t
Per #2863, part 1 first attempt at job-archival.  Instead of going into a DB, it just goes into a text file.  Just want to get the basics working and get some basic tests written up.  Some things to consider:
- how should user consider period / location of file.  I just have command line args to the module right now.  Perhaps need an equivalent to `content-backing.patch` for the file location (and eventual DB location).
- Working on #2778 (job-info list RPC restart) may be important to do to avoid huge returns from job-info
> job-archive support

- .travis.yml
- src/cmd/Makefile.am
- src/cmd/builtin/hwloc.c
- src/cmd/builtin/version.c
- src/shell/Makefile.am
- src/shell/affinity.c
- src/test/docker/README.md
- src/test/docker/focal/Dockerfile
- src/test/docker/travis/Dockerfile
- t/Makefile.am
- t/hwloc-data/1N/hwloc-versions/v1.11.11/0.xml
- t/hwloc-data/1N/hwloc-versions/v2.1.0/0.xml
- t/hwloc-data/1N/hwloc-versions/v2to1/0.xml
- t/hwloc/hwloc-convert.c
- t/hwloc/hwloc-version.c
- t/t2005-hwloc-basic.t
- t/t2006-hwloc-versions.t
- t/t2800-jobs-cmd.t
Problem: Hwloc v2.0+ is needed to detect on-node storage.  v2.0+ deprecates custom topologies (used to build a full-system topology aggregated from many, single-node topologies) and replaced several functions with new ones.  The XML format also changed, but v2.0+ is capable of outputing v1-compatible XML.
Solution: drop the `lstopo` command and refactor the `topology` command to avoid using custom topologies.  Add `#ifdef`s with usage of the new interfaces, including a flag that ensures all exported XML is v1-compatible.
Side-notes: Also adds the hwloc version to the `build-options` output of `flux version`.  Hwloc 2.0+ no longer has `NUMANode`s be parents of a package/cores, it is a sibling of them.  Rather than increase the complexity of `flux hwloc aggregate-load` with special cases to …
> Add support for hwloc v2.0+

- configure.ac
- etc/rc1
- etc/rc3
- src/cmd/flux-kvs.c
- src/modules/Makefile.am
- src/modules/resource/Makefile.am
- src/modules/resource/acquire.c
- src/modules/resource/acquire.h
- src/modules/resource/discover.c
- src/modules/resource/discover.h
- src/modules/resource/drain.c
- src/modules/resource/drain.h
- src/modules/resource/exclude.c
- src/modules/resource/exclude.h
- src/modules/resource/monitor.c
- src/modules/resource/monitor.h
- src/modules/resource/reslog.c
- src/modules/resource/reslog.h
- src/modules/resource/resource.c
- src/modules/resource/resource.h
- src/modules/resource/rutil.c
- src/modules/resource/rutil.h
- src/modules/resource/test/rutil.c
- t/Makefile.am
- t/rc/rc1-job
- t/rc/rc3-job
- t/request/rpc.c
- t/request/rpc_stream.c
- t/t2310-resource-module.t
This is a bare bones starting point for a resource module as discussed in #2908.
It just tries to look up `resource.hwloc.by_rank`.  If that succeeds, do nothing.  If that fails, wait for all brokers to come online according to `hello.idset`, then run `flux hwloc reload` as a subprocess.  Since the schedulers both look up `resource.hwloc` keys using FLUX_KVS_WAITCREATE before they say HELLO to the job manager, they just work as before.
This allows `flux hwloc reload` to be taken out of rc1 so that rc1 on rank 0 can start up before the other brokers are online in a future PR.
I named the module `resource` but temporarily register its name internally with `MOD_NAME ("xresource")`, until flux-framework/flux-sched#485 is addressed.
I'm not sure if this is worthy of being merged on its own, …
> add resource module

- src/cmd/flux-terminus.c
- src/modules/job-ingest/validate.h
- t/valgrind/valgrind.supp
The latest version of GCC reports two new errors.  One is a linker error due to duplicate declaration, and the other is a possible unintialized access due to an error condition that doesn't exit/return.
Also tossing in a small tweak to the valgrind suppression file to handle newer versions of `libdl` (a function changed names).
Closes #2953
> Fix compilation under GCC 10.1.0

- .travis.yml
- src/cmd/builtin/hwloc.c
- src/modules/sched-simple/rlist.c
- src/modules/sched-simple/rlist.h
- src/modules/sched-simple/sched.c
- src/modules/sched-simple/test/rlist.c
- src/shell/affinity.c
- t/rc/rc1-job
- t/t2208-queue-cmd.t
- t/t2210-job-manager-bugs.t
- t/t2300-sched-simple.t
- t/t2302-sched-simple-up-down.t
- t/t2700-mini-cmd.t
This fixes the issue @rountree reported in #2965, and probably will fix a similar complaint in #2961 (@garrettbslone if you could try this patch on your system that would be great)
The issue seemed to be that, at least on quartz, the flags that the shell affinity plugin was passing to `hwloc_topology_restrict()` were causing a re-indexing of core ids that then caused hwloc_distribute to pick incorrect cpuset ids. (TBH, I still don't really understand exactly what is going on, more evidence reported in the issue)
In any event, using the same flags in shell/affinity.c as used in flux-hwloc seemed prudent, so we make that change here.
I could not really think of a good reproducer that would work in CI, so this PR is only the fix, no new tests.
> sched-simple: schedule cores instead of PUs by default

- src/broker/test/runat.c
Set bourne shell requirement in test/runat.c, as tests require
a bourne shell equivalent.
Issue #2977
> broker/test: Fix shell portability in tests

- src/bindings/python/flux/future.py
- src/bindings/python/flux/job.py
- t/python/t0010-job.py
This PR adds Python bindings for `flux_job_cancel(3)` and `flux_job_kill(3)` as described in #2893 .
As part of this work, a default `.get()` method was added to the `Future` base type. This makes it so that *every* method returning a future with no result doesn't have to subclass the `Future` type. If there's a better way to accomplish that, let me know.
In order to test `kill` I needed an implementation of `job_wait_event` (see #2652). Currently, a synchronous version is sitting in `t0010-job.py`. Maybe that should be promoted to public function in `job`?
I also have a version of `job_wait_event()` that returns a `Future` and thus can be used with a `.then()` method. Unfortunately, this version fails when `.get()` is used synchronously (probably because there is no way to register a …
> python: add bindings for job cancel and kill

- scripts/pylint
- src/bindings/python/_flux/callbacks.h
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/core/watchers.py
- src/cmd/flux-jobs.py
- src/modules/pymod/echo.py
- t/job-info/list-id.py
- t/python/t0007-watchers.py
- t/python/t0012-futures.py
- t/python/t1000-service-add-remove.py
This PR most notably fixes #2707, where Python scripts using `flux_reactor_run()` can't be interrupted via SIGINT. The fix is pretty straightforward, a real binding for `reactor_run` is added to `flux.Flux` handles, which installs a signal watcher for SIGINT, stopping the loop and setting a sentinel which is checked before leaving the function. If the loop was interrupted, `KeyboardInterrupt` is thrown.
Along the way, #1779 was fixed, the default reactor for `reactor_run` is `handle.get_reactor()`, so Python users can now call simply `h.reactor_run()`. The same support was added for `reactor_stop` and `reactor_stop_error`.
To be able to use a signal watcher in the Flux class, a `SignalWatcher` class was added along with constructor `handle.signal_watcher_create()`.
> python: allow reactor_run() to be interrupted and other small improvements

- src/shell/info.c
- src/shell/info.h
- src/shell/jobspec.c
- src/shell/rcalc.c
- src/shell/rcalc.h
- src/shell/shell.c
- t/shell/initrc/tests/0001-shell-info.lua
As described in #2967, the `R` member of the JSON object returned from `flux_shell_get_info(3)` is currently missing. Add it.
> shell: add R to shell info JSON object

- src/bindings/python/flux/job.py
- src/cmd/flux-jobspec.py
- src/modules/job-exec/testexec.c
- src/modules/job-ingest/schemas/jobspec.jsonschema
- src/modules/job-ingest/schemas/jobspec_v1.jsonschema
- t/jobspec/invalid/attributes_null.yaml
- t/jobspec/valid/attributes_system.yaml
- t/jobspec/valid/attributes_user.yaml
- t/jobspec/valid/basic.yaml
- t/t2300-sched-simple.t
`job-ingest` validators explicitly allowed `"attributes": null`, though this is not valid jobspec as documented in RFCs 14 and 25.
This PR fixes the jsonschema and Python Jobspec validators to  reject jobspec with `null` attributes, and updates `basic.yaml` to be valid jobspec.
Note also that RFC 25 at least specifies that the `system` key and specifically `system.duration` are required keys, but neither validator enforces this. I thought it best to leave that be for now, as fixing it may break existing users. Perhaps we should go back and fix the RFCs.
Edit: Also note: the `job-info` module *does* require `attributes.system`, so I wonder if actually it would be ok to fix validators and all the tests to make the `system` key in `attributes` required.
> job-ingest: fix validation of V1 jobspec

- t/t2005-hwloc-basic.t
This fixes a couple minor issues in the hwloc "basic" tests
* Remove hwloc version-specific testing by testing individual entries in `by_rank` output with `jq`, instead of comparing whole objects.
* delete `pci_link_speed` entries in output XML to workaround #2988
> testsuite: minor fixes in t2005-hwloc-basic.t

- .github/workflows/main.yml
- src/cmd/flux-jobs.py
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/rset.c
- src/modules/job-info/job_state.c
- src/modules/job-info/list.c
- src/modules/sched-simple/libjj.c
- src/modules/sched-simple/libjj.h
- src/modules/sched-simple/sched.c
- src/shell/signals.c
- t/Makefile.am
- t/sched-simple/jj-reader.c
- t/t0022-jj-reader.t
- t/t2233-job-info-security.t
- t/t2400-job-exec-test.t
- t/t2900-job-timelimits.t
This PR makes the minimal changes necessary to support enforcing job time limits.
It requires changes in #2994, so is currently based on top of that branch. 
The `starttime` and `expiration` keys are now set in `R` by sched-simple, and `job-exec` "expires" jobs when the resource allocation expiration time is reached.
(Side note: I have a nagging worry about using an absolute time for  `expiration`, what happens if a job is assigned just before a DST change, for example. We may be setting ourselves up for bugs here. However, I'm ignoring all that for now)
When a job reaches its limit a `timeout` exception is thrown and `SIGALRM` is sent to the shells of the job, which forward on to the job tasks. In case `SIGALRM` is blocked by the job, this is followed up by `SIGKILL` after kill_timeout …
> support job timelimits

- etc/rc1
- etc/rc3
- t/rc/rc1-job
- t/rc/rc3-job
- t/t2200-job-ingest.t
- t/t2202-job-manager.t
- t/t2203-job-manager-dummysched.t
- t/t2230-job-info-list.t
Problem: job-info might grow a significant memory footprint over time with some workloads, yet we are loading it on all broker ranks.
Load on rank 0 only for now.
Fixes #3007
> rc: load job-info on rank 0 only

- doc/man1/flux-jobs.adoc
- doc/test/spell.en.pws
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/util.py
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/job_util.c
- src/modules/job-info/list.c
- t/flux-jobs/tests/issue#2634/format
- t/flux-jobs/tests/issue#2658/format
- t/t2230-job-info-list.t
- t/t2800-jobs-cmd.t
This PR adds support for collecting job `expiration` time from _R_ in job-info, along with the changes necessary to support the new fields `expiration` and `t_remaining` in `flux-jobs`.
So that it wasn't necessary to add `t_remaining_fsd` and `t_remaining_hms` etc fields in flux-jobs, support for custom "conversion specifiers" was added to the `JobFormatter` class. Now, a `!F` converts a float time to FSD, `!H` converts to H:M:S, and for datetime objects `!D` converts to an ISO 8601 date and time string (no timezone).
A `!d` was also added for flexibility to convert to a `datetime` object, which then has its own custom format spec (`strftime()` based):
```
$ flux jobs -ao '{t_inactive!d:%Y-%m-%d}'
T_INACTIVE
2020-06-15
2020-06-15
2020-06-15
```
However, this form doesn't allow for …
> flux-jobs: add support for job expiration and remaining time

- src/bindings/python/flux/job.py
- src/modules/job-info/job_state.c
- src/modules/job-info/job_util.c
- src/modules/job-info/job_util.h
- src/modules/job-info/list.c
- src/test/travis_run.sh
- t/Makefile.am
- t/job-info/list-rpc.py
- t/t2230-job-info-list.t
This PR addresses #2997 by
* Adding an error string to `flux_respond_error(3)` in many EPROTO/EINVAL cases of the `job-info.list*` suite of RPCs.
* In the Python bindings for these interfaces, attempt to cast values passed in by user to the appropriate type, so type errors are caught _before_ sending RPC. (e.g. jobid as string)
Fixes #2997
> Improve error responses from job-info.list* RPCs

- doc/man3/Makefile.am
- doc/man3/idset_create.adoc
- doc/man3/idset_encode.adoc
- doc/test/spell.en.pws
This fixes the problem pointed out by @dongahn in #3011.  It also splits the single man page into two since it was getting a little busy and the 8-stub limit of a2x had already been exceeded.  Finally, it adds entries and stubs for `idset_ndecode()` and `idset_format_map()` which had been added without updating the documentation.
> doc: update idset manpages

- src/bindings/python/flux/job.py
- t/python/t0010-job.py
This is a WIP stab at adding both synchronous and asynchronous Python functions that use the job eventlogs. This PR adds the following new functions to the `job` module:
* `job.event_wait(h, jobid, name, eventlog="eventlog")`: Wait for an event named `name` in `eventlog` synchronously. Blocks and returns an `EventLogEvent` for the matched event, or `None` if the eventlog ended with no match.
e.g.
```python
import sys
import flux
from flux import job
jobid = int(sys.argv[1])
name = sys.argv[2]
print(f"waiting for {name}")
print (job.event_wait (flux.Flux(), jobid, name))
```
```console
$ flux python we.py $(flux mini submit sleep 3) 'finish'
1591649139.01139: finish {'status': 0}
```
* `job.event_watch_async(h, jobid, name="*", eventlog="eventlog")`: returns a JobEventWatchFuture which can …
> python: add functions to facilitate watching job eventlog events

- .github/workflows/main.yml
- configure.ac
- t/t0005-exec.t
- t/t0007-ping.t
- t/t0014-runlevel.t
- t/t0020-terminus.t
- t/t2400-job-exec-test.t
- t/t2612-job-shell-pty.t
- t/t2900-job-timelimits.t
- t/t3001-mpi-personalities.t
- t/t5000-valgrind.t
Collecting a set of fixes for build and test problems found during or just after the release.
This is still a WIP as there are some other failing tests with `make -j N` where N is arguably a bit too big :wink:
However, this at least fixes tests that were failing reliably, and running all tests as Flux jobs works, so we can do this again (run all tests in parallel under `prove`, each as a Flux job, so whole testsuite completes in the time of the slowest test)
```
ƒ(s=95,builddir) grondo@fluke2:~/git/flux-core.git/t$ prove -j128 --merge --timer --exec="flux mini run -c4" ./t*.t
[17:37:46] ./t0016-cron-faketime.t ............................ skipped: libfaketime not found. Skipping all tests
[17:37:47] ./t2004-hydra.t .................................... skipped: skipping …
```
> build and test fixes

- src/bindings/python/flux/job.py
- src/cmd/flux-mini.py
- t/python/t0010-job.py
One of the features that is still lacking in the python bindings with respect to the CLI is the ability to redirect the stdio streams. All of the UQP's jobs have their stdio redirected, so I thought I would go ahead and implement it.
> python: add stdio properties to Jobspec class

- .travis.yml
Will allow flux-sched to also build and test against 20.04
> travis: tag a docker image for ubuntu 20.04

- .travis.yml
This _should_ fix the failed build for Ubuntu 20.04 docker image seen after merge of #3022 
Instead of copying correct `ARGS` to the 20.04 build, this fix enforces the correct `ARGS` if `DOCKER_TAG` is set.
Unfortunately, we won't know if it works until it is merged...
> travis-ci: enforce correct configure ARGS for docker tags

- src/bindings/python/flux/job.py
- src/cmd/flux-mini.py
- t/python/t0010-job.py
I like #2962 so much I want to start using it in the UQP---and in the Python bindings in particular. This PR would add a `flux.job.Jobspec` interface to `mini batch` behavior (and in fact changes the `mini batch` implementation to use the new interface). It adds a new method `from_batch_command` that is a little different than `from_command`: it takes the _contents_ of the script as a string, rather than the _path_ to the script as a string (technically as one string in a sequence). This is because the script contents are copied over to the broker, and also because the `mini batch` command can read in the "script" from stdin. The arguments to the script are accepted separately, as are broker options.
Let me know what you think, and if you generally like it I'll add some tests.
> Python interface to 'mini batch'

- .travis.yml
- src/test/docker/docker-run-checks.sh
It appears that the problem causing the Ubuntu focal builder to fail when attempting to push a new docker image is due to an incompatibility with the `configure` args used for a docker image and the `make distcheck` target. `make distcheck` tries to do reconfigure the project by appending a new `--prefix` to its special `_inst` directory, but it keeps previous `configure` args, so `--sysconfdir=/etc` tries to install files outside of `_inst` which fails.
This PR adds a new fatal error if `docker-run-checks.sh --distcheck` is used with a couple common `configure` args like `--sysconfdir` or `--with-systemdsystemunitdir`. Then the `DISTCHECK=t` flag is removed from the Ubuntu 20.04 builder. 
This will hopefully finally cause the docker tag to work and be automatically pushed to dockerhub.
> docker: really actually fix Ubuntu 20.04 (focal) docker tags

- .travis.yml
- scripts/.pylintrc
- src/bindings/python/flux/__init__.py
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/future.py
- src/bindings/python/flux/job.py
- src/bindings/python/flux/kvs.py
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
- src/cmd/flux-resource.py
Per #3034, update pylint from 2.2.2 to 2.4.4 to get around `isort` module errors.  Update python to handle new pylint errors.
Most of the Python changes should be simple and obvious.  Perhaps the only one to consider was the `invalid-name` fixes.  New variable names acceptable?  I chose to disable `invalid-name` for one function parameter (`raiseJobException`), which seemed quite specific.  I did change the variable name for another function parameter (`io` -> `iotype`).
Also, i chose to ignore `too-many-lines` errorrs.  Could increase the max-lines instead (default 1000)?
> pylint: Update pylint to 2.4.4

- configure.ac
- doc/man7/flux-broker-attributes.adoc
- etc/rc1
- etc/rc3
- src/broker/content-cache.c
- src/common/Makefile.am
- src/common/libcontent/Makefile.am
- src/common/libcontent/content-util.c
- src/common/libcontent/content-util.h
- src/modules/Makefile.am
- src/modules/content-files/Makefile.am
- src/modules/content-files/content-files.c
- src/modules/content-files/filedb.c
- src/modules/content-files/filedb.h
- src/modules/content-files/test/filedb.c
- src/modules/content-files/test/load.c
- src/modules/content-files/test/store.c
- src/modules/content-sqlite/Makefile.am
- src/modules/content-sqlite/content-sqlite.c
- t/Makefile.am
- t/request/rpc.c
- t/t0011-content-cache.t
- t/t0012-content-sqlite.t
- t/t0018-content-files.t
- t/t2008-althash.t
- t/t3200-instance-restart.t
This PR adds a new content backing store option, mainly as a demo, with lots of inline comments.
For now it just stores objects in one big flat directory using blobrefs as the file names, which will not be very scalable (depending on the file system used).
To allow flux to be invoked with a non-default backing store module, one can start flux with e.g.
```
flux start -o,-Scontent.backing-module=content-files
```
This attribute is peeked at by the rc1 script.  This needs more thought and probably isn't the complete or final solution to #2984.
Still more to do here but wanted to get this up early for @garrettbslone to peek at when he's ready.
> content-files: add alternate content backing store

- src/broker/runat.c
- src/common/libterminus/pty.c
- src/common/libterminus/pty.h
- src/common/libterminus/test/pty.c
- src/common/libtomlc99/test/toml.c
- t/test-terminal.perl
I was curious what scripts we had laying around that used the "master" branch, since github will be changing that.  Saw that `libterminus` still used "master-slave" terminology.  I converted to "leader-follower", picking "leader-follower" somewhat randomly.  Could pick an alternate word set too.
> Update terminology to use more inclusive words

- src/cmd/builtin/hwloc.c
Problem: When the `HWLOC_OBJ_GROUP` is ignored, the GPUs on the
Sierra/Lassen clusters are represented in the resource topology as
direct children of the node.  This topology ignores the fact that the
GPUs actually have locality with respect to the CPU sockets.  This
topology also is causing downstream affects with the fluxion scheduler
and its testsuite.  Depending on how the hwloc is read (either via
flux-core's flux-hwloc or directly via the hwloc API), the resource
topology changes (i.e., GPUs are children of the node versus the
sockets).  Also worth noting that the GPUs are children of the sockets
when using the hwloc V2 API, so ignoring the group creates a significant
difference in the topologies between hwloc versions.
Solution: remove the call to ignore `HWLOC_OBJ_GROUP` so that …
> flux-hwloc: remove ignore of `HWLOC_OBJ_GROUP`

- src/cmd/flux-resource.py
- t/Makefile.am
- t/resource-status/fluxion.expected
- t/resource-status/fluxion.json
- t/resource-status/missing.expected
- t/resource-status/missing.json
- t/resource-status/normal-input.expected
- t/resource-status/normal-input.json
- t/resource-status/null.expected
- t/resource-status/null.json
- t/t2350-resource-list.t
This PR makes a small change to `flux  resource list` to allow missing  or null `all` `allocated` or `down` keys in the `sched.resource-status` RPC response to indicate the empty set.
This is meant to help other schedulers more succinctly emit this RPC response when some resource sets are empty.
/cc @dongahn
> Allow JSON null or missing key to designate empty set in flux-resource list

- .travis.yml
Problem: flux-core docker images are built with localstatedir
set to `/usr/var` instead of `/var`. This causes persistent state
files to be written to an incorrect path under /usr, which may
cause confusion.
Add --localstatedir=/var to the DOCKER_TAG configure args to force
the correct value.
> travis-ci: Add --localstatedir=/var to docker tag builds

- .travis.yml
- configure.ac
- etc/rc3
- src/modules/Makefile.am
- src/modules/content-files/content-files.c
- src/modules/content-s3/Makefile.am
- src/modules/content-s3/content-s3.c
- src/modules/content-s3/s3.c
- src/modules/content-s3/s3.h
- src/modules/content-s3/test/load.c
- src/modules/content-s3/test/store.c
- src/test/docker/docker-run-checks.sh
- src/test/docker/travis/Dockerfile
- t/Makefile.am
- t/t0024-content-s3.t
- t/t2008-althash.t
- t/t3200-instance-restart.t
This is a work in progress pr that adds an s3 backing store. It is very light weight and doesn't have much error checking at this point. This pr is based on #2992. 
For testing, I suggest pulling down [Minio](https://www.google.com/search?client=ubuntu&channel=fs&q=minio+quickstart+guide&ie=utf-8&oe=utf-8) and following these steps:
1. Install the s3 library: `apt/yum install libs3-dev`
2. From your flux build directory spin up the Minio server: `minio server ./s3-data &`
3. Set the necessary env vars: 
`S3_HOSTNAME=127.0.0.1:9000`
`S3_SECRET_ACCESS_KEY={secretkey}`
`S3_ACCESS_KEY_ID={accesskey}`
`S3_BUCKET=flux-bucket`
4. Invoke the content-s3 backing store: `src/cmd/flux start -o,-Scontent.backing-module=content-s3`
TODOs:
1. Add error checking
2. Add TOML config hook
3. Add sharness …
> content-s3: add alternate backing store

- .travis.yml
- README.md
- src/test/docker/bionic/Dockerfile
- src/test/docker/centos7/Dockerfile
- src/test/docker/centos8/Dockerfile
- src/test/docker/focal/Dockerfile
- src/test/docker/travis/Dockerfile
This PR makes some small updates to the base `testenv` build images.
- Consistently handle `LANG` across our docker containers. Use `C.UTF-8` where supported, `en_US.UTF-8` otherwise.
- Move `libs3-dev` out of the travis Dockerfile into the base images.
- In expectation of adding more content-s3 tests, slightly refactor content-s3 env vars in `.travis.yml`
- Add patch and diffutils to CentOS 8 images
This might make conflicts for #3033. Sorry, I can help resolve if necessary.
I've already pushed up the new images to DockerHub.
> docker: small updates for testenv images, travis builds

- src/cmd/flux-jobs.py
- t/scripts/runpty.py
- t/t2230-job-info-list.t
- t/t2800-jobs-cmd.t
This PR is split off from work in #3045.
It includes the custom `HeaderFormatter` class for `flux-jobs`, the update to force UTF-8 output encoding, and removal of some unused code.
However, the majority of changes here is to the `t2800-jobs-cmd.t` test, which by the end was largely rewritten to get rid of hardcoded job counts and redundant calls to `flux-jobs` which made the test one of the longest in the suite.
The resulting runtime is reduced by half.
Before:
```
$ time ./t2800-jobs-cmd.t 
[snip]
real	0m52.974s
user	0m48.355s
sys	0m8.883s
```
After:
```
$ time ./t2800-jobs-cmd.t 
[snip]
real	0m28.932s
user	0m26.798s
sys	0m5.828s
```
> flux-jobs: small functionality and testing updates

- src/modules/job-info/job_state.c
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/event.c
- src/modules/job-manager/raise.c
- src/modules/job-manager/test/annotate.c
- src/modules/sched-simple/sched.c
- t/job-manager/sched-dummy.c
- t/job-manager/sched-helper.sh
- t/t2203-job-manager-dummysched-single.t
- t/t2204-job-manager-dummysched-unlimited.t
- t/t2300-sched-simple.t
Spun out of my annotations work the following is a set of misc cleanups.  
The most major change is the re-working of annotations to in sub-objects, not at the top level.  What I mean is:
- re-worked annotations to store "namespace" keys within an object of a key. i.e.
`{"sched.reason_pending": "no cores"}`
is now
`{"sched":{"reason_pending": "no cores"}}`
- re-worked annotations updates to be "recursive". e.g.
updating
`{"sched": { "reason_pending": "no cores"}}`
with
`{"sched": { "t_estimate": 1234}}`
should result in
`{"sched": { "reason_pending": "no cores", "t_estimate": 1234}}`
Of the minor cleanups, perhaps the only one worth debating is e32391bec4914985e954fd8852cc50611bc01a1f, should the error be ENOENT instead of EINVAL?
> job-manager/job-info/annotations: misc cleanup + refactor (annotations part 2)

- src/bindings/python/flux/job.py
- src/bindings/python/flux/wrapper.py
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/common/libutil/fluid.c
- src/common/libutil/fluid.h
- src/common/libutil/test/fluid.c
- t/python/t0010-job.py
- t/t2201-job-cmd.t
- t/t2800-jobs-cmd.t
This PR adds support for the proposed RFC19 F58 encoded JOBIDs.
It is a WIP because the final set of testing is not in place yet, in case the result is not acceptable for merging.
At its core, this PR adds a new FLUID string type `FLUID_STRING_F58`, which represents the Base58 encoding of FLUIDS (and therefore Flux JOBIDs).
Since all supported FLUID string representations are somewhat unambiguous, a `fluid_parse()` function is introduced which can automatically parse a FLUID from a string in any supported encoding.
The `fluid_parse()` function is then used to implement a `flux_job_id_parse()` to the public API (FLUIDs do not seem to be directly exposed in libflux API). `flux_job_id_parse()` is then used throughout `flux-job.c` to allow input of a JOBID in any supported encoding, instead …
> Add support for RFC19 F58 encoded JOBIDs

- doc/man1/flux-exec.adoc
- doc/man1/flux-mini.adoc
- doc/test/spell.en.pws
- src/cmd/flux-exec.c
- src/cmd/flux-mini.py
For consistency throughout flux commands, change --labelio to
--label-io in flux-exec.  Support -l short option in flux-mini.
Update documentation accordingly.
Fixes #2915
> cmd: Make label io options consistent

- src/modules/job-manager/priority.c
- t/t2210-job-manager-bugs.t
This adds @grondo's fix for the job manager segfault reported by @dongahn in #3051 plus a regression test.
> job-manager: avoid segfault on priority change with pending alloc

- t/sharness.d/flux-sharness.sh
This reverts commit a63df26c3d4a1ef810780cc6afb0d483cb531b67.
When building in a virtual environment, site packages may be needed
for testing.
Fixes #3074
> testsuite: remove use of -S option in run_timeout

- src/shell/affinity.c
This fixes a bug in the shell affinity plugin found by @eleon.
I was unable to add a test, since the reproducer requires presence of HTs.
(We should test on corona before merging.)
> shell: fix bug in cpu-affinity=per-task

- doc/man1/flux-jobs.rst
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/modules/job-info/job-info.c
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/job_util.c
- src/modules/job-info/list.c
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/annotate.c
- src/modules/job-manager/annotate.h
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/test/annotate.c
- t/Makefile.am
- t/job-manager/sched-helper.sh
- t/t2203-job-manager-dummysched-single.t
- t/t2204-job-manager-dummysched-unlimited.t
- t/t2205-job-manager-annotate.t
- t/t2230-job-info-list.t
- t/t2800-jobs-cmd.t
Built on top of PR #3062, this PR completes phase 1 job annotation support in `flux-core`.
- job-manager - support a new annotations event, which will publish annotations
- job-info - read in annotations events from the above for querying by job-list services
- job-manager - support a new user annotation service, allowing users to annotate their jobs
- add command support in `flux job annotate`
- is the user interface ok?  I supported a simple `flux job annotate id key value` syntax, and `value` can be `-` for stdin.
- by default, everything is put under the `user` object in the annotations.
- flux-jobs - support listing any annotations
- the annotation fields listed by the user can be arbitrary.  `flux-jobs` has a rule that any annotation that doesn't exist results in an empty string. …
> job-info & job-manager& flux-jobs: Support job annotations (annotations part 3)

- doc/man1/flux-jobs.rst
- doc/test/spell.en.pws
This PR adds the documentation of the new JOBID representations available to `flux-jobs(1)`. The doc update was delayed until after conversion to rst.
> doc: update flux-jobs(1)

- doc/conf.py
- doc/requirements.txt
Problem: The spelling plugin defined in doc/conf.py sphinx config
requires users to have the plugin installed, even though it is unused.
This unnecessarily breaks the build for users.
Remove the unused plugin and its associated configuration.
Fixes #3083
> doc: remove spelling plugin from sphinx conf.py

- doc/conf.py
- doc/man1/flux-kvs.rst
- doc/man3/flux_fd_watcher_create.rst
- doc/man3/flux_handle_watcher_create.rst
- doc/man3/flux_pollevents.rst
- doc/man3/flux_stat_watcher_create.rst
- doc/man3/flux_zmq_watcher_create.rst
- doc/test/spellcheck
- etc/gen-cmdhelp.py
Per discussion in #3071.  Not sure if others want to add other fixes on top of this one (such as #3076).
Please take note of my removal of unicode chars changes.  Some are obvious (unicode  `…` to plain old ascii `...`).  I replaced a "-- in other words" with an "i.e." and some `"or"` with `OR` instead of just reverting to what was in the original asciidoc files.
> doc: Remove unicode characters, update build to assume utf-8 locale

- src/common/libflux/message.c
- src/common/libflux/test/message.c
- src/common/libioencode/ioencode.c
- src/shell/input.c
- src/shell/output.c
This PR experimentally switches the encoding used by libioencode from base64 to utf-8.
The benefit of this change is to allow easier access to job IO from external entities, e.g. this will make it trivial for a Python script to get job output.
One change of note is that the flag `JSON_ALLOW_NUL` is added to `flux_msg_vunpack(3)` use of `json_loads`. This allows anything that could be base64 encoded to safely be encoded as UTF-8 (jansson will escape unencodable characters, e.g. `\u0000` for NUL).
> switch to utf-8 for subprocess and job io encoding

- src/shell/lua.d/openmpi.lua
Problem: OpenMPI fails to bootstrap under Flux on some systems, like
Cori at NERSC
Solution: automatically set OMPI_MCA_{schizo,pmix} to flux so that
flux's pmi is used rather than pmix or vendor-specific plugins like cray
> shell/lua.d/openmpi: set env vars to force the use of flux plugins

- etc/gen-cmdhelp.py
- src/common/libflux/module.c
- src/common/libflux/module.h
- src/common/libflux/test/module.c
- src/modules/sched-simple/sched.c
- t/Makefile.am
- t/module/running.c
- t/t0003-module.t
Problem: `flux module load` blocks until the module enters the reactor,
but in some cases it is desirable for the command to complete before
the reactor is entered.
Give modules control over when they enter RUNNING state, and therefore
when `flux module load` returns, by exposing a new function,
`flux_module_set_running ()`.
Change simple scheduler to call this before its synchronous resource and job-manager handshake, to prepare for broker startup changes in #3057.  This approach will be much easier to apply to the fluxion scheduler than the one in #3063
> libflux: add flux_module_set_running()

- src/broker/broker.c
- src/broker/broker.h
- src/broker/overlay.c
- src/broker/runat.c
- src/broker/runat.h
- src/broker/state_machine.c
- src/broker/state_machine.h
- src/broker/test/runat.c
- t/rc/rc1-job
Here are some commits peeled off of #3057 that don't functionally change anything about how the broker bootstraps.  The primary component of this PR is the state machine refactor, in which it gets a more abstract interface, and internally becomes table-driven and reactive.  There are some other minor changes to the `runat` class, the broker's "global context", and couple other minor bits.
I thought peeling this off might decrease the complexity of #3057 a bit and make it easier to review.
> broker: state machine refactoring

- src/bindings/python/flux/job.py
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/cmd/flux-mini.py
- src/common/libschedutil/init.c
- src/common/libschedutil/ops.c
- src/common/libschedutil/schedutil_private.h
- src/shell/pmi.c
- src/shell/task.c
- t/job-manager/sched-helper.sh
- t/t2200-job-ingest.t
- t/t2201-job-cmd.t
- t/t2202-job-manager.t
- t/t2203-job-manager-dummysched-single.t
- t/t2220-job-archive.t
- t/t2230-job-info-list.t
- t/t2401-job-exec-hello.t
- t/t2402-job-exec-dummy.t
- t/t2404-job-exec-multiuser.t
- t/t2601-job-shell-standalone.t
- t/t2602-job-shell.t
- t/t2606-job-shell-output-redirection.t
- t/t2612-job-shell-pty.t
- t/t2701-mini-batch.t
- t/t2800-jobs-cmd.t
- t/t3200-instance-restart.t
This PR updates many user-facing commands to represent JOBIDs in the RFC 19 F58 encoding.
This first required "normalizing" the use of jobids throughout the testsuite, such that tests which assumed integer jobids, or a a common jobid representation between "plumbing" tools (such as `flux job list`) and "porcelain" tools (like `flux jobs`, `flux mini`, etc), would not break. In most spots, the jobids were normalized by passing them to `flux job id`, which can ingest a jobid in any format and will output integer jobid by default.
I will check if any tests break in flux-sched due to these changes and make a similar fix. Since the normalization doesn't require F58 jobid output, the changes to the flux-sched testsuite should not depend on this PR.
Once the the testsuite was prepared, then …
> Use F58 as the default representation for JOBIDs in most user-facing commands

- src/modules/content-s3/content-s3.c
- src/modules/content-s3/s3.c
- src/modules/content-s3/s3.h
- src/modules/content-s3/test/load.c
- src/modules/content-s3/test/store.c
- t/t0024-content-s3.t
- t/t2008-althash.t
- t/t3200-instance-restart.t
This pr is a work in progress to allow the influential accessor information for the content-s3 module to be accessed from toml config files. There should be and initial conifg file passed into `flux start` with the `-o,--config-path=dir` option as well as an s3 credential file with the s3 access keys. Here is a example set up:
/home/user/config/config.toml:
```
[content-s3]
credential-file = "/home/user/.s3-creds"
uri = "http://my-s3-endpoint:9000"
bucket = "my-bucket"
virtual-host-style = false
```
/home/user/.s3-creds:
```
access-key-id = "access-key"
secret-access-key = "secret-key"
```
Note: the current sharness test will not work yet.
> content-s3: add toml config hook

- doc/man1/flux-exec.rst
- doc/man1/flux-hwloc.rst
- etc/gen-cmdhelp.py
A couple minor doc fixes:
* Fix `literalinclude` of `NODESET.rst` in `flux-exec(1)` and `flux-hwloc(1)`
* Fix a bug in `gen-cmdhelp.py` which resulted in `flux-` prefix on some commands in `flux-help` output, e.g.
```
Usage: flux [OPTIONS] COMMAND ARGS
-V, --version          Display command and component versions
-p, --parent           Set environment of parent instead of current instance
-v, --verbose          Be verbose about environment and command search
Common commands from flux-core:
flux-broker        Invoke Flux comms message broker daemon
content            Access instance content storage
flux-cron          Schedule tasks on timers and events
flux-dmesg         manipulate broker log ring buffer
flux-env           Print the flux …
```
> doc: fix flux-help(1) output and rendering of NODESET.rst

- .travis.yml
- configure.ac
- src/modules/content-s3/s3.c
- src/test/docker/travis/Dockerfile
As noted in issues #3113 and #3114, libs3has multiple different package versions on different distros. This pr addresses that in configure, and adds the `--enable-content-s3` option to both the Centos 7 and 8 travis tests.
This pr is also from the previous version of the content-s3 module without the use of the TOML config parameters for right now. The TOML changes will be added after pr #3067 is merged.
> content-s3: add support for different versions of libs3

- .travis.yml
Problem: When DOCKER_TAG is set, ARGS is overwritten with the correct
installation configure arguments. This erases other required args
for the build including --enable-content-s3.
Be sure to keep existing ARGS when setting the DOCKER_TAG args.
This fixes a problem with builds on master because `--enable-content-s3` is being overwritten by the installation args enforced by `DOCKER_TAG=t`. This only affects merges to master.
> travis-ci: fix ARGS when DOCKER_TAG set

- .travis.yml
Due to a variable expansion bug, the automated build and push of the `fluxrm/fluxorama` image is still not working on merges to the main Flux branch. (Sorry!)
This small fix simplifies the section of `.travis.yml` and in turn fixes the bug.
> travis-ci: fix fluxorama image build

- configure.ac
An extra comma in the libs3 API probing now performed by configure was causing an error to be emitted on configure's stderr.
While I was in there I moved the second compile test into the "else" leg of the first one, since only one can succeed and there is no need to always run both.
The indenting may be a bit easier to follow, although it's m4, so still pretty awful.
> build: fix innocuous configure error

- src/common/libflux/module.h
Problem: A comment in libflux/module.h references an old URL for RFC 5.
Update the URL to the readthedocs site, which will be a more readable
version of the RFC anyway.
> libflux: fix comment in module.h to reference readthedocs

- etc/Makefile.am
- etc/completions/flux.pre
- etc/completions/get_builtins.sh
This is a work in progress pr. It provides command completion for the top-level commands for flux-core in bash. This feature was requested in issue #1647. It still needs to be integrated into the makefile to be properly installed. For now, the completions can be sourced directly from flux-core/etc/completions/flux-core.
> bash: top level command completions for flux

- doc/man1/flux-shell.rst
- etc/flux-core.pc.in
- src/broker/broker.c
- src/common/libflux/plugin.c
- src/common/libflux/plugin.h
- src/common/libflux/test/plugin.c
- src/shell/affinity.c
- src/shell/gpubind.c
- src/shell/jobspec.c
- src/shell/shell.c
- t/Makefile.am
- t/shell/plugins/setopt.c
- t/t2603-job-shell-initrc.t
- t/t2604-job-shell-affinity.t
This PR has a set of fixes mainly for roadblocks to job shell plugin development.
This includes:
* Addition of `flux_plugin_get_conf(3)`
* Add `conf.shell_initrc` and `conf.shell_pluginpath` broker attributes. These can be used to query/set the the default shell initrc.lua path and plugin searchpath. (Hm, This might need more thought for multi-user instances)
* Fix #3158 (flux_shell_getopt_pack(3) fails with ENOENT when no shell options already set)
* Log when gpu and core affinity plugins are disabled for informational purposes and debugging
* add more variables to pkg-config (#3147)
Also threw in:
* Fix #3154 (set `CUDA_VISIBLE_DEVICES=-1` for jobs without allocated GPUs)
> improve support for shell plugin developers

- src/modules/job-info/job_state.c
- src/shell/jobspec.c
- src/shell/test/jobspec.c
Non-V1 jobspec causes a fatal error in `job-info` when it is calculating the number of tasks and in `job-shell` when it is calculating the number of slots, cores-per-slot, and slots-per-node.
Drop the `job-info` error to just a warning and add a recursive parser of jobspec that allows non-V1 resources to be interspersed within the resource tree of an otherwise v1-compliant jobspec.
Enable the jobspec in #3152 (i.e., `node->socket->(core[2],gpu)`) to work properly.
Close #3151
> job-info,job-shell: allow non-V1 jobspec

- .travis.yml
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/job.py
- src/cmd/flux-admin.py
As noted in #3166, spurious `black` format errors are appearing in travis-ci since we allow `black` to be upgraded before running `check-format`.
This PR pins `black` to the latest version, v20.08b1, and then reformats python files with this version.
This should avoid future CI failures due to format changes between `black` versions.
Fixes #3166
> python: reformat with latest black formatter, then pin black version

- src/shell/lua.d/spectrum.lua
- t/t3001-mpi-personalities.t
Problem: running the latest SMPI under Flux causes the following error:
```
Error: OMPI_COMM_WORLD_RANK is not set in environment like it should be.
Error checking ibm license.
flux-job: task(s) exited with exit code 255
2020-08-28T21:46:20.722507Z broker.err[0]: rc2.0: flux mini run -N1 -n1
-o mpi=spectrum ./mpi-hello-spectrum-2020.06.25 Exited (rc=255) 0.8s
```
Solution: set OMPI_COMM_WORLD_RANK to `task.info.rank` for each task in
the job via the `spectrum` shell MPI personality
> shell: fix Spectrum 2020.06 bootstrap

- mypy.ini
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/future.py
- src/bindings/python/flux/job/JobID.py
- src/bindings/python/flux/job/__init__.py
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/job/list.py
- src/cmd/flux-jobs.py
- t/python/t0010-job.py
This PR promotes the `JobInfo` and `JobsOutpuFormat` classes to the Python API for use by other entities in Flux or Flux users. (The `JobsOutputFormat` class gets a rename to `JobInfoFormat`) and switches `flux-jobs` to use these classes.
In addition to the `get_jobs()` and `get_job()` methods for `JobListRPC` and `JobListIdRPC` which get only  the raw payload (as a dict) from the job-info.list-jobs RPC, new methods `.get_jobinfos()` and `get_jobinfo()` are added to return `JobInfo` objects instead of a list of dicts. I thought about naming these `.jobs()` and `.job()` since they will likely be the main interface used by users -- let me know what everyone things about that.
An *attempt* at a better interface for `job_list()` is also made with the addition of a `JobList` class (sorry I'm …
> python: promote JobInfo and formatter class to API and add JobList class

- src/modules/job-info/job_state.c
- src/modules/job-info/job_util.c
- t/Makefile.am
- t/job-info/jobspec-permissive.jsonschema
- t/t2230-job-info-list.t
- t/t2800-jobs-cmd.t
Per #3153 and #2964, there are issues if there is invalid data such as an invalid jobspec or R.  The job-info module would not know how to process this invalid data and never advance a job's state to the next state (e.g. from running to cleanup)
I also handled invalid eventlog data, but I wasn't 100% sure about this.  eventlog data should never be wrong b/c it comes from the
`job-manager` instead of the user (jobspec) or scheduler (R).  But I figured, why not just in case.
Have tests for invalid jobspec, but not for R or eventlog yet.  I *think* I can create tests by pausing the job-info module's job state
processing and then overwriting R / eventlog in the KVS to get the test I want.  But wanted to post this for now.  (Partially to feel like I'm contributing after being gone for a month …
> job-info: do not fail on invalid jobspec / R / eventlog

- NEWS.md
Here's a first cut on release notes for next week's v0.19.0, based on what's been landed since v0.18.0.
Please add any outstanding issues that we need to get into this release to the `flux core 0.19.0` milestone.
Fee free to push/force push to this PR as changes need to be made.
> NEWS.md: add v0.19.0 release notes

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/job/list.py
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
Per #3161 discussion.  Threw in 3 random cleanups as well.
> flux-jobs / python bindings: handle empty string conversions

- src/test/docker/centos8/Dockerfile
This PR installs the Sphinx dependency in our docker Centos8 image via RPM instead of using pip.
This will presumably help us catch use of sphinx options that wouldn't be supported by the version of Sphinx available in RHEL/CentOS 8.
Note: I've already pushed the modified `fluxrm/testenv:centos8` image to docker hub.
> docker: do not install Sphinx via pip in Centos8 image

- etc/rc1
Problem: fluxion rc1 scripts have to unload sched-simple because
flux-core rc1 loads it unconditionally.
Change rc1 so that sched-simple is loaded only if an external
rc1 script did not load a module that registered the `sched` service.
This will require a fluxion PR as well - just wanted to post this to see whether people thought this was an acceptable stopgap to avoid the overhead of reloading the scheduler, in lieu of a comprehensive solution, such as one of those discussed in #2273.
> rc: load sched-simple only if no other scheduler is loaded

- src/common/libutil/fluid.c
- src/common/libutil/test/fluid.c
As discussed in #3199, if `FLUX_F58_FORCE_ASCII` is set force ascii `f` when encoding F58 FLUIDs.
This may be useful in situations where Python and C utilities are displaying differently, or when Python coercion of C locale to UTF-8 causes display or cut-and-paste problems.
> Allow fallback to ascii f prefix for F58 FLUIDs with FLUX_F58_FORCE_ASCII

- doc/man1/flux-mini.rst
- doc/test/spell.en.pws
- src/shell/Makefile.am
- src/shell/log.c
- src/shell/log.h
- src/shell/mustache.c
- src/shell/mustache.h
- src/shell/output.c
- src/shell/pty.c
- src/shell/test/mustache.c
- t/t0025-broker-state-machine.t
- t/t2605-job-shell-output-redirection-standalone.t
- t/t2606-job-shell-output-redirection.t
- t/t2701-mini-batch.t
Use the F58 encoding for jobids by default when expanding `{{id}}` in output file mustache template in the job shell. This makes the default output file from `flux mini batch` consistent with the default output of `flux jobs`.
Also, accept `{{jobid}}` as an alternate for `{{id}}`.
Finally, allow alternate encodings to be specified if desired by specifying `{{id.<type>}}` where `type` is any encoding supported by `flux_job_id_encode(3)`, e.g.
```
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux mini run --output=flux-{{id}}.out hostname
0: stdout redirected to flux-ƒEMqPeRm.out
0: stderr redirected to flux-ƒEMqPeRm.out
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux mini run --output=flux-{{id.dec}}.out hostname
0: stdout redirected to flux-662515482624.out
0: stderr …
```
> shell: render output file template {{id}} as F58 by default, allow other id encodings

- etc/flux.service.in
- etc/rc1
- etc/rc3
- src/broker/state_machine.c
- src/modules/resource/acquire.c
- src/modules/resource/discover.c
- src/modules/resource/drain.c
- src/modules/resource/monitor.c
- src/modules/resource/monitor.h
- src/modules/resource/resource.c
- src/modules/resource/resource.h
- src/modules/resource/rutil.c
- src/modules/resource/rutil.h
- src/modules/resource/test/rutil.c
- t/rc/rc1-job
- t/rc/rc3-job
- t/t0010-generic-utils.t
- t/t0025-broker-state-machine.t
- t/t2300-sched-simple.t
- t/t2302-sched-simple-up-down.t
- t/t2310-resource-module.t
This PR changes the resource module's monitoring code so that it's now possible to `systemctl stop flux` on a compute node and have it be marked down for scheduling automatically.
The resource module is now loaded on all ranks, and when the broker is shutdown and unloads the module on a rank > 0, the resource module sends a "goodbye" message upstream.  For symmetry, it also sends a "hello" message upstream when the module is loaded.  These two messages are reduced as they move towards rank 0.  With the addition of the "hello" message, it was trivial to decouple the resource module from the broker "quorum" code - prob a good thing to let that remain as simple as possible, while this one learns how to detect non-responsive execution targets however we want to define that, etc..
There is a …
> resource: mark nodes down when they are stopped

- src/bindings/python/flux/future.py
- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/rpc.py
- src/bindings/python/flux/util.py
- t/Makefile.am
- t/issues/t3186-python-future-get-sigint.sh
- t/t4000-issues-test-driver.t
As described in #3186, Python scripts that use synchronous RPC and Future `get()` or `wait_for()` and derived functions are not interruptible by Ctrl-C while blocked in these calls. This is because the Python default SIGINT handler waits until the program returns to Python from C to "deliver" the signal.
This PR takes the simple approach. These blocking functions are wrapped in a decorator that disables the Python default SIGINT handler for the duration the call is off in C-land. This allows the blocking calls to be interrupted, though the behavior in this case is to exit the program (i..e we never return back to Python to dump beautiful stack traces) However, the issue at hand is fixed.
> python: allow Future.get() and wait_for() to be interrupted by Ctrl-C

- src/shell/jobspec.c
- src/shell/jobspec.h
- src/shell/test/jobspec.c
Problem: Jobspecs that contain `node->...->slot->...->core` but have
multiple resource at a given level are currently rejected, even if there
is only 1 of each of node, slot, and core.  This prevents near-term
relevant jobspecs like `cluster->(node->slot->core,storage)`.
Solution: extend the recursive jobspec parsing function to fully
traverse the entire jobspec without bailing out early due to multiple
resources at a given level.  This version still requires that there only
be one node, slot, and core per jobspec and that they appear in that
exact order.
Submitted as a draft PR because I am still testing the flux-sched PR
that will rely on this one.
> shell: allow multiple resources per level in jobspec

- src/cmd/builtin/hwloc.c
- t/t2005-hwloc-basic.t
Problem: On GPU-enabled clusters, `flux hwloc info` only prints `X
Machines, Y Cores, Z PUs`.  This makes it more difficult to debug
unsatisfiable jobspecs and if the hwloc that Flux is using was
configured with CUDA support.
Solution: add counting of the number of GPUs to `cmd_info` so that the
output on GPU-enabled clusters is now `X Machines, Y Cores, Z PUs, W GPUs`.
The output on non-GPU clusters is unaffected.
Closes #3216
> hwloc: add printing of num GPUs to `flux hwloc info`

- src/modules/job-manager/priority.c
- t/t2201-job-cmd.t
- t/t2210-job-manager-bugs.t
An attempt to fix #3218.  I hit a segfault when I accidentally tried to re-prioritize a running job (vs a pending job).
> job-manager: fix segfault when attempting to change priority of a running job

- t/issues/t3186-python-future-get-sigint.sh
This small change should fix the race in `t/issues/t3186-python-future-get-sigint.sh` which keeps hitting us in Travis. If the process at first don't die, try, try again. :shrug:
I tested this in my own branch against Travis-CI and ran several times with no failures (before, it used to hit on every other run or so)
> testsuite: fix race in python SIGINT test

- README.md
- doc/Makefile.am
List `python3-sphinx` as an optional build requirement instead of `asciidoc` / `asciidoctor`.
I verified that this package is sufficient to build and check man pages on Ubuntu focal, bionic, and centos8, but not centos7.  I wagered that a note was not warranted for centos7 given that
* the `python3-sphinx` packages does exist, so yum won't fail
*  `configure` handles the situation properly by disabling man page generation (and warning you)
* man page generation is optional
* centos7 is old
If others disagree we could add a note about it.
Fixed a couple of other doc related nits also.
> doc: update README.md to list sphinx as a doc dependency

- src/common/librouter/router.c
- src/common/libschedutil/ops.c
- src/modules/job-ingest/worker.c
- src/modules/job-manager/submit.c
- t/t1105-proxy.t
Drop some LOG_DEBUG level messages that add to log noise and are not all that interesting to see anymore.  Now the only debug logging that occurs for each job comes from the scheduler which seems appropriate for now.
I thought this might be a good idea in preparation for system instance testing since the logs may be consulted to run down problems, and a better signal is good.
> reduce log noise

- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- t/t2230-job-info-list.t
There is a small chance that a job-annotation could arrive to the
job-info module before the job-info module is aware of a jobs
existance.
In the event this occurs, save the annotation off to a new
"early_annotations" hash.  When the job-info modules becomes
aware of the job via a job-state transition, load the annotation
out of the hash.
Fixes #3165
> modules/job-info: handle annotations race

- etc/rc1
- etc/rc3
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/priority.c
- src/modules/job-manager/submit.c
- src/modules/job-manager/wait.c
- src/modules/job-manager/wait.h
- t/Makefile.am
- t/job-manager/event_stream.c
- t/rc/rc3-job
- t/t2200-job-ingest.t
- t/t2202-job-manager.t
- t/t2203-job-manager-dummysched-single.t
- t/t2204-job-manager-dummysched-unlimited.t
- t/t2205-job-manager-annotate.t
- t/t2211-job-manager-events.t
- t/t2234-job-info-list-update.t
Per discussion in #3052, the `job-manager` did not have a way to inform the `job-info` module that a job's priority had changed, thus leading to invalid job listings.
Several issues were discussed in #3052, this PR just tried to look at the notification of the priority change between `job-manager` & `job-info`.
For prototyping purposes, I implemented about the most straightforward thing I could think of, adding a new `job-updates` event that the `job-manager` publishes.  It publishes a change record of "jobid, timestamp, field that changed, value", such as "JOBID, TIMESTAMP, "priority", 14" would be a potential change.  I transfer the "value" as a json object.  In the future, I believe a json null can serve as "cache invalidate", when the data that has changed isn't known to the …
> job-manager / job-info: get job data changes from job-manager to job-info so job listings will have up to date information

- src/bindings/python/flux/job/info.py
- t/t2800-jobs-cmd.t
Problem: the header of state_single and status are both "ST", which
can be confusing since both may output identical states.
Solution: rename the header of state_single to the single character
"S".
Update test appropriately.
Fixes #3214
> python/job: Update state_single default header

- src/bindings/python/flux/util.py
shield the signal handler code from being invoked in subthreads (i.e., not the main thread),
Python does not like that.  Since the KeyboardInterrupt which codes wants to enable arrives
in the MainThread anyway, this should be fine.  Subthreads are difficult to terminate then
though, it is adviseable to declare them as deamon threads so that MainThread interruptions
do not hang on pending thread activities.
This fixes #3264.
@grondo : I hope this helps - let me know if you think anything is missing.  For example, I was not sure if you want a unit test for this - it's a bit tricky to test as it is so timing sensitive, but it's certainly possible.
> python: fix signal handler management in threads

- src/cmd/flux-job.c
- src/shell/output.c
- t/t2602-job-shell.t
per discussion in #3041
part 1 of the PR, support a new "output.<stdout|stderr>.buffer.type" configuration in the shell, which determines if stdout/stderr will be line buffered or unbuffered.
part 2 of this PR per #3041, default stderr to be unbuffered by default.
update some tests as needed
note that for the moment I did not include this configuration as a new option in `flux-mini` as I wasn't sure if it was something truly needed.  Would be trivial to add of course.
> shell: support stdio buffering options / default stderr to unbuffered

- src/modules/job-info/job_state.c
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/annotate.c
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/journal.c
- src/modules/job-manager/journal.h
- src/modules/job-manager/submit.c
- src/modules/job-manager/submit.h
- t/Makefile.am
- t/job-manager/event_stream.c
- t/job-manager/events_journal_stream.c
- t/t2202-job-manager.t
- t/t2211-job-manager-events-journal.t
- t/t2211-job-manager-events.t
Built on top of PR #3254.  It's the final in my series of job-manager / job-info refactoring / changes.
A few notes (mostly same notes as my prior attempted PR on this, #3238)
- introduces a `seq` into the wrapped entries, so listeners can determine if they have seen the event for a job before (via the KVS).
- b/c the `annotations` object of a job can change, we have to  `json_deep_copy()` job annotations that go into the journal so they can be preserved.
- i made the maximum journal length configurable.  The default is 1000 entries, which translates to 100-125 jobs on average (8 entries for a typical successful job, not counting any extra annotations that may come from the scheduler).  Dunno if this is too small?  Would we want longer?
- b/c of the journaling, I don't really need to …
> job-manager: support events journal

- doc/man1/flux-mini.rst
- src/cmd/flux-mini.py
- t/t2702-mini-alloc.t
As noted in #3274, there is currently no way to get `flux mini alloc` to emit the submitted jobid, which makes either checking on a `flux mini alloc` job or scripting the `flux mini alloc` command difficult.
This PR simply adds a `-v` option to `flux mini alloc` which prints the jobid on stderr like `flux mini run`.
> cmd: display jobid with flux-mini alloc -v, --verbose

- src/modules/job-info/job-info.c
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- t/t2230-job-info-list.t
- t/t2800-jobs-cmd.t
Built on top of #3253.
Per issue #3234, refactor the job-info module to use only the job-manager event stream, not job-state transitions.
> job-info: use job manager journal to track job state

- src/common/libeventlog/eventlog.h
- src/common/libflux/buffer.h
- src/common/libhostlist/hostlist.h
- src/common/libidset/idset.h
- src/common/libkvs/kvs_txn.h
- src/common/libpmi/pmi.h
- src/common/libpmi/pmi2.h
- src/common/libschedutil/alloc.h
- src/common/libschedutil/free.h
- src/common/libschedutil/hello.h
- src/common/libschedutil/init.h
- src/common/libschedutil/ops.h
- src/common/libschedutil/ready.h
- src/common/libsubprocess/subprocess.h
- src/common/schedutil.h
Add missing C++ header guards in all installed header files.
Fixes #3267
> libflux: Add missing C++ header guards

- src/cmd/flux-job.c
- t/t2231-job-info-lookup.t
Per idea from @SteVwonder  in #2851, when a key is not specified for flux job info, output possible keys by going through the list of KVS keys in the KVS job path.
I thought this was going to be super simple, so I was just going to program this up while I got woken up by the baby at 3am.  But it ended up being a tad trickier than I was hoping for.
Basically, there's always the chance that when you're going through all the possible KVS keys in the job path, there's a chance that the guest namespace will disappear and be re-absorbed back into the primary namespace.  To solve this, if I get a ENOTSUP indicating that the namespace has disappeared, I just re-do the entire KVS search again.  This leads to the code being more annoying that I'd like it to be.
Maybe it's overkill.  Instead, I …
>  cmd/flux-job: Output key options for job info

- src/common/liboptparse/optparse.c
- src/common/liboptparse/optparse.h
- src/common/liboptparse/test/optparse.c
It has annoyed me for awhile that optparse sorts options and subcommands alphanumerically by default. Many times the caller wants control over the order of options and/or subcommands so that similar content can be collected together. The obvious way to allow this is to preserve the order in which options and commands are inserted into the optparse object.
This PR adds a new flag to set an optparse object to "sorted" and makes all optparse object unsorted by default. If a program wants its options sorted alphanumerically within an option group, this option can be used to re-enable the old behavior.
While working on this feature, a few other small issues and testing gaps were found, and these issues were fixed along the way.
> optparse: don't sort options/subcommands by default and other improvements

- etc/rc1
Problem: FLUX_LOCAL_CONNECTOR_RETRY_COUNT has no effect in rc1
This is a shell programming error.  The construct
VAR=value FOO=$(cmd)
has no effect on cmd, since VAR is not exported.  Restructure as
FOO=$(VAR=value cmd)
Revert the retry increase in 8bafb4fd310446ab665faeb223fb7b61a2c75d96
since that change had no effect, and this bug is the real problem.
> rc: fix local connector retries

- src/common/libsubprocess/local.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
Problem: In the pre_exec and post_fork hooks, the user has the potential
to destroy the subprocess, which can lead to potential segfaults later on.  We
should treat hooks as only having "read only" access to flux_subprocess_t
contents.
Solution: Do not allow the user to call flux_subprocess_ref() or
flux_subprocess_unref() while in hooks.
Fixes #2225
> libsubprocess: do not allow ref/unref in hooks

- t/t2005-hwloc-basic.t
When using lstopo in tests, only use lstopo-no-graphics, as the
lstopo command has the ability to launch a gui.  This launching
can lead to errors in the test.
Fixes #3308
> t/t2205-hwloc-basic: only use lstopo-no-graphics

- t/t2310-resource-module.t
- t/t2315-resource-system.t
As described in #3312, fix the core idsets in a couple resource module tests.
This is required to run `make check` on systems with >37 cores. (e.g. ppc64le builder in buildfarm)
> testsuite: fix core idsets in resource module tests

- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/job-manager.c
If the scheduler disconnects, it is not handled by the disconnect
callback.  Teardown the scheduler if the scheduler has gone down.
Fixes #3030
> job-manager: handle scheduler disconnect

- src/cmd/flux-resource.py
- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/common/librlist/test/rlist.c
- src/modules/resource/drain.c
- src/modules/resource/exclude.c
- src/modules/resource/inventory.c
- src/modules/resource/inventory.h
- src/modules/resource/resource.c
- src/modules/resource/topo.c
- t/t2310-resource-module.t
- t/t2311-resource-drain.t
- t/t2312-resource-exclude.t
- t/t2313-resource-acquire.t
- t/t2315-resource-system.t
This PR adds simple support for specification of hostlists in addition to idsets in both `flux resource drain/undrain` and the `resource.exclude` configuration keyword. It is a WIP in case the approach here is not acceptable.
The approach here is to change the "idset" in the drain protocol and exclude value to a more generic "targets" list, which can be either an idset or a RFC29 hostlist. When a "targets" string is decoded to a set of ranks, the resource module will first attempt to use `idset_decode()`, and if that fails, it will try to decode "targets" as a hostlist and turn that into a set of ranks using a new function in librlist `rlist_hosts_to_ranks()`. The code proceeds as before once the "targets" are converted to a `struct idset`.
The same was done to the resource.exclude …
> resource: support hostnames for drain and exclude

- doc/man1/flux-jobs.rst
- doc/test/spell.en.pws
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/job/list.py
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/common/librlist/rlist.c
- src/modules/job-info/Makefile.am
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/job_util.c
- src/modules/job-info/list.c
- src/modules/sched-simple/Makefile.am
- t/t2230-job-info-list.t
- t/t2800-jobs-cmd.t
Per #3313 and #3323, convert `job-info` to use `librlist`, then add `nodelist` as a listable attribute in `job-info`.  Added fix for #3322 in here as well.
Most of the changes in this PR aren't earth shattering, pretty basic.  But two things to note for possible discussion:
- I changed the default output of `flux-jobs` to list `NODELIST` instead of `RANKS`, b/c I figure that's what most users probably want by default.  I doubt this change is controversial.  Unless someone thinks we should list both `RANKS` and `NODELIST`?
- I think the `NNODES` attribute is a bit ambiguous now w/ `NODELIST` output available.  We could have a situation where multiple brokers exist on a node, so the number of ranks might be > 1, but the number of nodes is a different number.  Here's a simple example:
``` …
```
> job-info / flux-jobs: Support listing nodelist 

- src/bindings/python/flux/job/submit.py
- src/cmd/flux-job.c
- src/common/libjob/job.h
- src/modules/job-info/job_state.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job.c
- src/modules/job-manager/priority.c
- src/modules/job-manager/test/job.c
- src/modules/sched-simple/sched.c
- t/ingest/submitbench.c
- t/t2202-job-manager.t
Per RFC21 changes, the priority event has been renamed admin-priority.
Update in job-info, job-manager, and tests appropriately.  Update
several function names for consistency.
Fixes #3328
> job-info, job-manager: rename priority event

- t/resource/waitup.py
Problem: A resource.monitor-waitup test was regularly failing
when running on busier systems.  It is believed the 5s timeout
in the test script was too short.
Solution: Increase the timeout from 5s to 30s.
Fixes #3329
> testsuite: increase resource.monitor-waitup timeout

- .github/workflows/main.yml
- mypy.ini
- src/bindings/python/_flux/Makefile.am
- src/bindings/python/_flux/_core_build.py
- src/bindings/python/_flux/_hostlist_build.py
- src/bindings/python/_flux/_idset_build.py
- src/bindings/python/_flux/_security_build.py
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/hostlist.py
- src/bindings/python/flux/idset.py
- t/Makefile.am
- t/python/t0020-hostlist.py
- t/python/t0021-idset.py
This PR is pretty straightforward. It adds basic `IDset` and `Hostlist` Python classes which wrap libflux-idset.so and libflux-hostlist.so.
I was also going to make automated bindings for librlist to make an Rv1 class, however I decided to stop here and make the Rv1 class a separate PR.
> python: add bindings for libflux-idset,hostlist

- src/modules/job-exec/exec.c
- t/Makefile.am
- t/job-exec/imp.sh
- t/t2404-job-exec-multiuser.t
This PR has one critical and one minor fix for the job-exec module when in multi-user mode.
These were discovered  on fluke.
* critical: input to the IMP truncated for signed jobspec > ~8K (mysteriously the stdin buffer was specifically set to 8K)
* minor: set the working directory of the IMP to `/` for better security and to avoid `"cannot change to "dir", going to /tmp instead"` errors for every multiuser job
> job-exec: fixes for multiuser mode

- src/common/libjob/sign_none.c
- src/common/libjob/test/sign_none.c
flux-core signs jobs with an internal "none" signer when configured without flux-security.  As noted in #3354, it seems the format of the envelopes now differ between flux-security and flux-core.  This PR fixes the issue and adds tests to ensure that sign/verify works both ways.
> libjob: repair interoperability with flux-security

- README.md
- configure.ac
- src/cmd/Makefile.am
- src/common/Makefile.am
- t/Makefile.am
This PR contains just a few trivial fixes/improvements for the build system.
> build: allow Lua 5.4, drop -lutil, and improve sphinx warning

- configure.ac
- src/common/libsubprocess/Makefile.am
- src/test/docker/docker-run-checks.sh
- src/test/docker/poison-libflux.sh.in
- src/test/travis_run.sh
This PR adds a script to build and install "poison" `libflux-*.so` into the system path of docker images before `configure`, `make` and `make check`. Presumably this will help us catch cases where the system flux-core components "leak" into the testsuite.
To disable the poison libs, a new `docker-run-checks.sh` option `--no-poison` is introduced.
Also fixed one link order issue that was hitting the poison system libs during testing.
> docker: install poison flux-core libs and executables before build and test

- t/Makefile.am
- t/scripts/dmesg-grep.py
- t/t2300-sched-simple.t
This PR requires #3366 
Add a testsuite utility that follows `log.dmesg` output searching for a pattern. If a line matches the script exits with success, o/w it waits until a timeout elapses and exits with an error.
This is meant to be used in place of `flux dmesg | grep PATTERN` when that construct may be racy due to log message generation from asynchronous events, or if the log message is not generated on rank 0.
Replace the one known racy test which currently loops over `flux dmesg | grep` with the new script.
> testsuite: replace loop in t2300-sched-simple.t with dmesg-grep.py helper

- doc/index.rst
Problem: when referencing the flux-core docs via intersphinx, it uses
the top section title of `index.rst` "Welcome to flux-core's
documentation".  For the meta flux-docs RTD project, we want a link that
says "Flux-core Man Pages".
Solution: Rename the subsection to "Flux-core Man Pages" and give it an
explicit link so that we can reference it with intersphinx from flux-docs.
Related to https://github.com/flux-framework/flux-docs/issues/67
> docs: add explicit link to man pages section

- src/shell/gpubind.c
- t/t2604-job-shell-affinity.t
Problem: GPU bind uses IDSET for the CUDA_VISIBLE_DEVICES environment
variable. However, hwloc doesn't support this format and this
precludes a nested flux instance from correctly auto-detecting its
allocated GPUs.
Use comma separated list format for this env variable.
Adjust the two test cases that assume the IDSET format.
> affinity: use comma separated list format for CUDA_VISIBLE_DEVICES

- src/test/generate-matrix.py
Problem: A missing --tag=NAME argument to docker-run-checks.sh
caused the push of new docker images on main branch and tags to
fail.
Ensure the --tag argument is supplied when branch is "master" or
we are building a tag, and docker_tag=True.
> github: fix missing docker tag in matrix builds

- config/x_ac_jansson.m4
- src/broker/broker.c
- src/cmd/flux-job.c
- src/modules/resource/inventory.c
This PR two minor bugs:
- resource module memory leak on `flux module reload` (my bad!)
- rewords a misleading `flux job` error message when debugging
Also, refuse to build on Super Nintendo.  I'm sure there will be disappointment.
> small fixes: resource memory leak, improve error messages, check size of int

- src/shell/Makefile.am
- src/shell/lua.d/tmpdir.lua
- t/t2602-job-shell.t
Add a default Lua plugin that ensures TMPDIR exists for all jobs.
Any error from `mkdir` will be logged, but the actual output of the command will go to the exec system and `flux dmesg` output. This will be fixed in a future PR which sends output from job shell to a special exec system per-job logfile. (TBD)
> shell: ensure TMPDIR exists for all jobs

- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/restart.c
- src/modules/job-manager/test/job.c
- t/t2212-job-manager-jobspec.t
Problem: recent changes to cache jobspec in job manager
neglected to restore jobspec when job manager is restarted.
Look up jobspec in parallel with eventlog when replaying
job eventlogs during job manager startup.
> job-manager: get jobspec from KVS on restart

- src/cmd/flux-job.c
- src/modules/job-info/job_state.c
- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/restart.c
- t/t2202-job-manager.t
- t/t2230-job-info-list.t
- t/t2232-job-info-eventlog-watch.t
- t/t2800-jobs-cmd.t
Support the flux-restart event, generating it in job-manager, parsing it in restarts in job-manager, and handling it in job-info.
For testing purposes, I also add support of a `--count` option in `flux job wait-event`.
Per #3345 (which is really a split off from #3327)
> Support flux-restart event to prepare for fair share priority plugin

- src/cmd/flux-job.c
- src/common/Makefile.am
- src/common/libeventlog/Makefile.am
- src/common/libeventlog/eventlogger.c
- src/common/libeventlog/eventlogger.h
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/testexec.c
- src/shell/Makefile.am
- src/shell/events.c
- src/shell/evlog.c
- src/shell/output.c
- src/test/checks-annotate.sh
- t/t2400-job-exec-test.t
- t/t2402-job-exec-dummy.t
- t/t2404-job-exec-multiuser.t
This PR updates job-exec to log early shell/IMP standard output to a new `log` event type in the `guest.exec.eventlog`, instead of just logging with `flux_log()`.
This makes early shell and IMP errors available for display to the user instead of lost in the `flux dmesg` logs. (i.e. the dreaded 
```
flux-job: task(s) exited with exit code 1
flux-job: No job output found
```
error)
As an example, I commonly run the shell under valgrind with a wrapper script, and now we no longer need to process `flux dmesg` output to get the output from `valgrind`:
```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ cat shell.sh 
#!/bin/sh
libtool e valgrind --leak-check=full /home/grondo/git/f.git/src/shell/flux-shell "$@"
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux module reload job-exec …
```
> job-exec: log early shell/imp errors

- src/modules/job-exec/job-exec.c
- src/modules/job-manager/start.c
As with `sched.alloc`, the job manager can now forward the cached jobspec in `exec.start`, so that the job-exec module doesn't have to fetch the full jobspec from the KVS for each job.
> job-manager: add redacted jobspec to exec.start request

- src/broker/broker.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/common/libflux/message.c
- src/common/libflux/message.h
- src/modules/resource/monitor.c
This PR addresses the problem noted in #3235, where an instance can become stuck during teardown.  I think it also has been happening in the centos7 builder and is responsible for spurious CI failures.  (I was usually able to reproduce in the Centos 7 docker image by running back to back `flux start -s32 /bin/true` after 7-10 iterations).
The problem seems to be with zeromq 4.1.4, which is the version we are stuck with on Centos 7/TOSS 3.  The ROUTER socket, which communicates with downstream TBON children, is not supposed to be able to block, but on that release it occasionally does when a peer is in the process of disconnecting.  This PR works around it by sending to that socket (only) in a non-blocking mode and logging any errors.  This enables the broker to avoid getting stuck.  Logs …
> broker: fix intermittent hang during instance tear-down on Centos7/TOSS3

- mypy.ini
- src/bindings/python/_flux/Makefile.am
- src/bindings/python/_flux/_rlist_build.py
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/resource/ResourceSet.py
- src/bindings/python/flux/resource/ResourceSetImplementation.py
- src/bindings/python/flux/resource/Rlist.py
- src/bindings/python/flux/resource/__init__.py
- src/cmd/flux-R.c
- src/cmd/flux-resource.py
- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- t/Makefile.am
- t/python/t0022-resource-set.py
- t/t2350-resource-list.t
This PR adds a python `ResourceSet` class -- a generic interface for parsing and using _R_.
In this first cut, `ResourceSet` is built from an underlying _implementation_, which for _R_ version 1 is a new binding for the C `librlist` API.
Each implementation must be a member of a `ResourceSetImplementation` abstract base class, which provides the minimum interface necessary for the generic `ResourceSet` class to implement its API.
I kept the API fairly simple for now. The hope is that when we have an Rv2 implementation, it can be plugged in as the version 2 implementation of `ResourceSet`, and zero users of `ResourceSet` will need to be updated. 
Finally, the hand-coded `Rv1` and `IDset` implementations in `flux-resource.py` are dropped and the script is updated to use `ResourceSet` for …
> python: add ResourceSet class

- Makefile.am
- src/bindings/python/flux/security.py
- src/cmd/flux-jobspec.py
- src/test/checks_run.sh
- src/test/docker/docker-run-checks.sh
- src/test/generate-matrix.py
- t/Makefile.am
- t/job-archive/query.py
- t/jobspec/summarize-minimal-jobspec.py
- t/jobspec/validate.py
- t/prove-under-flux.sh
- t/python/sideflux.py
- t/python/subflux.py
- t/python/t0001-handle.py
- t/python/t0002-wrapper.py
- t/python/t0003-barrier.py
- t/python/t0004-event.py
- t/python/t0005-kvs.py
- t/python/t0006-request.py
- t/python/t0007-watchers.py
- t/python/t0009-security.py
- t/python/t0010-job.py
- t/python/t0012-futures.py
- t/python/t0020-hostlist.py
- t/python/t0021-idset.py
- t/python/t0022-resource-set.py
- t/python/t1000-service-add-remove.py
- t/t0021-flux-jobspec.t
- t/t2604-job-shell-affinity.t
- t/t2606-job-shell-output-redirection.t
Problem: Many Flux tests in the testsuite fail when run as Flux jobs.
Most of the issues were utf-8 encoding problems in various Python libraries and scripts. This is triggered in a Flux job because `FLUX_JOB_ID` in the environment is encoded with F58 by default, but sharness resets `LANG=C` for all tests. When various python bits try to encode/decode the environment in jobspec, etc, then encoding exceptions are thrown.
This PR fixes a bunch of spots that were experiencing these exceptions by adding `errors="surrogateescape"` where necessary (though in one spot, stdin had to be reopened and forced to utf-8).
There were other little fixes along the way, including a small kludge to allow python tests in `t/python/t*.py` to be run by hand, which then allowed these scripts to be run as a Flux …
> testsuite: support level N inception of flux testsuite

- src/common/libjob/job.h
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/test/job.c
- src/modules/job-manager/urgency.c
- t/t2202-job-manager.t
- t/t2230-job-info-list.t
- t/t2234-job-info-list-update.t
- t/t2800-jobs-cmd.t
per #3345.
Nothing too remarkable with this change, except the first commit, where I had a logic error with the `flux-restart` state revert-ing.
> Sync priority changes from job-manager to job-info

- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/annotate.c
- src/modules/job-manager/annotate.h
- src/modules/job-manager/event.c
- src/modules/job-manager/urgency.c
- t/Makefile.am
- t/t2209-job-manager-job-urgency-change.t
- t/t2234-job-info-list-update.t
I'll just repeat what @garlick wrote in #3333 here:
> In single mode, the job-manager may have at most one alloc request outstanding with the scheduler. The first job in the alloc queue is the one that is sent. If a new job is submitted that has a higher priority than that one, or an existing job is re-prioritized so that it has a higher priority, the outstanding alloc should be canceled so that the job at the top of the alloc queue can take its place.
> job-manager: in mode=single, schedule higher priority jobs due to urgency change

- src/modules/job-manager/annotate.c
- t/Makefile.am
- t/t2209-job-manager-job-urgency-change-single.t
didn't want to push on #2895 too quickly for the 0.22.0 release, so I punted that issue to 0.23.0.
But figure this simple testsuite cleanup (with #3417 in mind in the future) & minor job-manager bug could be put in for 0.22.0.
> job-manager: Fix annotation clear corner case

- src/bindings/lua/jansson-lua.c
- t/Makefile.am
- t/issues/t3415-job-shell-segfault-on-null.sh
- t/t4000-issues-test-driver.t
As described in #3415, the job shell currently segfaults if there is a JSON null in the jobspec.
This occurs when the shalls packs up the jobspec to a Lua table for the shell.info table.
The fix is to not ignore `JSON_NULL` and emit a Lua `nil` instead.
> Fix job shell segfault when jobspec contains JSON null

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/job/stats.py
- src/cmd/flux-jobs.py
- src/common/libjob/job.h
- src/modules/job-info/Makefile.am
- src/modules/job-info/job-info.c
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-info/stats.c
- src/modules/job-info/stats.h
- t/python/t0010-job.py
- t/t2800-jobs-cmd.t
This PR adds a few more meta-statistics to the `job-info.job-stats` RPC, adds a python `JobStats` class for fetching these statistics (and computing other convenient stats), and uses `JobStats` in newly introduced `flux jobs --stats,--stats-only` options.
This is just meant as the minimum solution for #3386, and to get the enhanced `job-info.job-stats` RPC into mainline for possible use in other work. Therefore, nothing too elaborate was done in `flux jobs` so it would be easy to change or undo in the future if we go another route.
One thing that might be controversial in this PR: I made `flux jobs --stats-only` exit with non-zero status by default when there are no more active jobs. This makes a possibly common use case really straightforward:
```
$ while flux jobs --stats-only; do sleep …
```
> Expand available job statistics and add flux-jobs --stats,--stats-only options

- doc/conf.py
Problem: sphinx fails to auto-generate API documentation for the
`flux.job.*` submodules due to an error when importing `yaml`.
Mock the import of `yaml` using Sphinx's built-in mocking capabilities,
re-enabling the autogeneration of all the python APIs
Closes #3424
> doc: mock import for `yaml` dependency

- .github/workflows/asan.yml
- .github/workflows/main.yml
This PR fixes a couple GitHub action failures that were only seen when pushing a tag.
Since the actions are edited, this PR might need someone to push the merge button manually. (assuming actions pass)
> fix github actions on tag push

- mypy.ini
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/core/watchers.py
- src/bindings/python/flux/future.py
- src/bindings/python/flux/message.py
- src/bindings/python/flux/rpc.py
- src/bindings/python/flux/util.py
- t/Makefile.am
- t/issues/t3432-python-sigint.sh
- t/python/t0007-watchers.py
- t/python/t0012-futures.py
This PR fixes the signal handling problems described in #3432.
As described in that issue, a new global, per-thread state variable is introduced to determine if the current thread is executing under the Flux reactor, and disables the `@interrupt` decorator if so. This fixes many instances where Ctrl-C bafflingly could not interrupt a python program which had called into the reactor.
Additionally, `@interruptible` was mistakenly placed on `RPC.get()` which calls `RPC.get_str()` which was already using the `@interruptible` decorator, so that likely caused some issues as well.
I've also fixed the handling of exceptions in Future and Watcher callbacks in this PR. If an uncaught exception is detected from one of these callbacks, it is saved in global state and the reactor is terminated with an …
> python: fix ctrl-c handling and re-throw unhandled exceptions in reactor_run()

- src/bindings/python/flux/util.py
- t/Makefile.am
- t/issues/t3429-python-future-ref.py
Fix the issue described in #3429. The check_future_error decorator uses `sys.exc_info()` which can cause  a circular reference that is sometimes not cleaned up before re-entering the C reactor. This can result in a "hang" if the reactor is supposed to exit because the consumed future was the last "active" watcher on the reactor.
> python: fix circular reference in check_future_error decorator

- src/modules/job-manager/list.c
- src/modules/job-manager/test/list.c
- t/Makefile.am
- t/job-manager/job-conv.py
- t/job-manager/list-jobs.c
- t/job-manager/sched-helper.sh
- t/t2202-job-manager.t
- t/t2203-job-manager-dummysched-single.t
- t/t2204-job-manager-dummysched-unlimited.t
- t/t2205-job-manager-annotate.t
- t/t2207-job-manager-wait.t
- t/t2209-job-manager-job-urgency-change-single.t
- t/t2230-job-info-list.t
- t/t2800-jobs-cmd.t
Per discussion in #3433 and peeling off from #3428.
- fixed up several tests that were incorrectly testing urgency instead of priority, necessitating adding `priority` to the `list-jobs` output
- have the `t/job-manager/list-jobs` tool output full json output instead of its specific formatting.  
- by doing the above, remove `awk` and `cut` to retrieve fields to  `jq`, so now tests should be a little bit more clear on what they are testing and are more robust if the `list-jobs` RPC returns more fields in the future.
for example:
```
-test_expect_success 'job-manager: queue is sorted in priority order' '
+test_expect_success HAVE_JQ 'job-manager: queue is sorted in priority order' '
cat >list3_priority.exp <<-EOT &&
31
16
0
EOT
-       cut -f5 <list3.out >list3_priority.out &&
+       $jq …
```
> testsuite: fix invalid tests, cleanup list-jobs, remove hardcoded states/results

- .github/workflows/asan.yml
- .github/workflows/main.yml
- README.md
- src/test/checks_run.sh
- src/test/docker/docker-run-checks.sh
This PR was the result of updating flux-sched to Github Actions.
The docker-run-checks.sh script got a slight rewrite, allowing it to be copied to flux-sched with only trivial modifications. This will allow us to move improvements to the script between the projects more easily (and perhaps allow the script to be used in other flux-framework projects in the future)
The pr-validator action is now skipped except for pull requests (it doesn't make sense to run it otherwise)
And finally, the two workflows are given names `ci` and `asan` for easier reference (otherwise github refers to them  by full path in the repo)
> ci: better script portability and other small updates

- doc/man1/flux-jobs.rst
- doc/test/spell.en.pws
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/job/list.py
- src/bindings/python/flux/job/stats.py
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/cmd/flux-kvs.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-info/job_state.c
- src/modules/job-info/list.c
- src/modules/job-info/stats.c
- src/modules/job-info/stats.h
- src/modules/kvs-watch/kvs-watch.c
- t/t2205-job-manager-annotate.t
- t/t2230-job-info-list.t
- t/t2234-job-info-list-update.t
- t/t2800-jobs-cmd.t
Problem: The spelling of "canceled" is inconsistently
used in flux.  Sometimes the British spelling "cancelled" is
used and othertimes the American spelling "canceled" is used.
Solution: Change all spellings of "cancelled" to "canceled".
Fixes #3439
> Globally standardize spelling of "canceled"

- src/shell/shell.c
- t/t2608-job-shell-log.t
As described in #3444, if a shell plugin tries to write data to stdout, some or all of that output may be dropped since stdout is buffered, and the buffer is lost at `exec(2)`.
This PR simply sets `stdout` to unbuffered during `task.exec` to avoid the problem and the confusion it might cause.
> shell: fix dropped stdout from shell plugins in task.exec callback

- src/cmd/flux-job.c
- src/common/libjob/job.h
- src/common/libschedutil/alloc.c
- src/common/libschedutil/hello.c
- src/modules/job-info/job_state.c
- src/modules/job-info/job_state.h
- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job.h
- src/modules/job-manager/list.c
- src/modules/job-manager/urgency.c
- t/Makefile.am
- t/job-manager/sched-dummy.c
- t/t2202-job-manager.t
- t/t2210-job-manager-bugs.t
- t/t2213-job-manager-hold-single.t
- t/t2214-job-manager-hold-unlimited.t
- t/t2230-job-info-list.t
- t/t2234-job-info-list-update.t
- t/t2800-jobs-cmd.t
Per #2895 and #3324, support the idea of a job hold and job expedite.  A hold is urgency=0, in which a job will not be sent to the scheduler (note that #3334 still exists, so if the job has already been sent to the scheduler in unlimited mode, no way to change it yet).  Expedite is urgency=31, which automatically leads to the job priority being set to the max (2^32-1).
Supporting this in `flux job urgency`, the special args of `hold`, `expedite`, and `default` are now supported, making it easier for a
user to set a hold/expediate/default job priority on a job without knowing what values those map too.
Per discussion in #2895 it would be nice to inform a caller what the prior urgency was after changing it.  So I modified the `job-manager.urgency` RPC to return the old urgency to the …
> job-manager: support job hold and expedite

- doc/conf.py
- src/bindings/python/flux/job/Jobspec.py
- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/job/kill.py
A couple of minor things that I noticed while I playing around with the python bindings.
The largest change is pulling in intersphinx and then referencing RFC21 in the `event_watch`/`event_wait` docstrings.
> python: miscellaneous fixes to docstrings and argument names in bindings

- src/common/libschedutil/init.c
- src/common/libschedutil/init.h
- src/modules/job-manager/urgency.c
- src/modules/sched-simple/sched.c
- t/Makefile.am
- t/job-manager/sched-dummy.c
- t/t2210-job-manager-bugs.t
- t/t2215-job-manager-priority-order-unlimited.t
- t/t2300-sched-simple.t
Built on top of #3428.
Per #3334 and RFC27 updates, support updates of job priorities for jobs that have been sent to the scheduler (are "pending" in the job-manager) via the `sched.prioritize` RPC.
Per discussion in #3441, in order to not break ABI for the time being, `sched.prioritize` is supported in the `sched-simple` and
`sched-dummy` (testsuite) schedulers by "manually" setting up the callback and parsing messages rather than through the `libschedutil` interface.  Once `libschedutil` is refactored per #3441, we can update to use those interfaces instead.
> job-manager: send updated priorities to schedulers

- src/test/checks_run.sh
Problem: the existing `test` errors out with `too many arguments`. The
issue is that an extra call to `test` snuck into the conditional.
Solution: remove the extra call to `test` and rely on the `-a` logical
and for the conditional check.
Closes #3460
> test: fix test for installing poison libflux

- src/common/libutil/test/ipaddr.c
- t/t3000-mpi-basic.t
This PR adds the suggested `errstr` output to `libutil/test_ipaddr.t` in order to diagnose the errors described in #3466.
Also, as discussed in #3463, the MPI test timeout is extended as a workaround for an issue that seems to only be reproducible in GH actions.
> testsuite: add debug and workarounds for failures in github actions

- configure.ac
- src/bindings/python/Makefile.am
Problem: Build errors occur when using the Julia packaging tool
Yggdrasil to build Flux and package libflux.so as part of a Julia
package. These errors occur due to python versioning and the python
package dependencies.
Solution: Add a configure flag that disables the python
dependencies. This obviously produces an otherwise broken Flux build (no
working front-end utilities or validator), but it is useful for
producing a libflux.so.
Closes #3420
> configure: add switch to allow flux to be built without python

- src/common/libschedutil/alloc.c
- src/common/libschedutil/alloc.h
- src/common/libschedutil/free.c
- src/common/libschedutil/free.h
- src/common/libschedutil/hello.c
- src/common/libschedutil/hello.h
- src/common/libschedutil/init.c
- src/common/libschedutil/init.h
- src/common/libschedutil/ops.c
- src/common/libschedutil/ops.h
- src/common/libschedutil/schedutil_private.h
- src/modules/job-manager/alloc.c
- src/modules/sched-simple/libjj.c
- src/modules/sched-simple/libjj.h
- src/modules/sched-simple/sched.c
- t/t2300-sched-simple.t
Per #3441, any new callbacks added in the `schedutil_create()` function will break ABI.  To ensure future changes don't break ABI, set all callbacks in a struct of callback pointers, so new callbacks can be added to the end of the struct in the future.
I merely ripped two commits from @garlick's tree here:
https://github.com/garlick/flux-core/tree/schedutil_async
updating them for the current master.  I did not include any of the feature changes @garlick worked on in that tree.
Note that I did the minimum for solve #3441.  If there are other ABI breaking changes we'd like in `libschedutil` (either now or in the near future) we can discuss if this should be delayed.
> libschedutil: refactor API to use struct w/ callback pointers, fix priority type, add prioritize callback, add flags

- src/bindings/python/flux/core/handle.py
- t/Makefile.am
- t/issues/t3470-multithread-reactor-run.py
As described in #3470, use of `reactor_run` in multiple Python threads currently causes a libev assertion. This is because libev only allows a signal watcher for a given signal to be handled in one reactor per process for obvious reasons. However, the `SIGINT` watcher in `Flux.reactor_run()` that attempts to ensure the reactor is interruptible is currently installed on every call.
To fix the problem, this PR only performs the special `SIGINT` handling in the main Python thread. This should be fine, because whether the main thread is or is not in the C reactor, the main thread will still handle `SIGINT` and allow the process as a whole to be interrupted.
Along the way, I also found that the `threading.local()` setup wasn't working right for multiple threads either, and this is fixed here …
> python: fix use of Flux.reactor_run() from multiple threads

- doc/man1/flux-mini.rst
- doc/test/spell.en.pws
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/core/watchers.py
- src/bindings/python/flux/progress.py
- src/cmd/flux-mini.py
- t/Makefile.am
- t/t2700-mini-cmd.t
- t/t2703-mini-bulksubmit.t
In the context of testing and exercising Flux interfaces, I've found it handy to have a tool that can submit a bunch of jobs rapidly, but our standard tools are definitely lacking in this department. I have a `bulksubmit.py` script which works, but it requires a directory full of jobspec files, which is not convenient.
As an experiment I made a small change to `flux-mini.py` to allow asynchronous submission of jobspec, and using that interface, added an option that allows bulk submission of the same job  rapidly. I'm putting up this experimental PR to get feedback before I move on to any testing.
This PR enhances the job submission used in `flux-mini.py` to use `submit_async()`, which opens the door to submitting multiple jobs per invocation (without performing them back to back).
Then, a …
> flux-mini: add bulk job submission capabilities

- src/connectors/ssh/ssh.c
- t/t1105-proxy.t
Problem: ssh and rsh do not forward environment variables, thus
LD_LIBRARY_PATH is not guaranteed to be set on the remote node where the
flux command is run.  If the flux command is linked against libraries
that can only be found when LD_LIBRARY_PATH is set, then the flux
command will fail to run over ssh.
Solution: Grab the client-side LD_LIBRARY_PATH so that we can manually
forward it.  Then forward it by prepending it to the flux relay
command (e.g., `ssh hostname LD_LIBRARY_PATH=/foo flux relay`).
Closes #3457
> connectors/ssh: forward LD_LIBRARY_PATH over ssh when set

- doc/man1/flux-mini.rst
- doc/test/spell.en.pws
- src/cmd/flux-mini.py
- t/t2703-mini-bulksubmit.t
This fix for `flux mini bulksubmit` was split off #3464 as it seems like a simple, well contained fix.
The `flux mini bulksubmit` command splits file input on whitespace only, which is inconvenient if you want to submit a job per line in a file, and each line could contain whitespace. This is also different from the default behavior of GNU parallel, from which bulksubmit is inspired.
Change the default separator for file input to newline, and add a new `--sep=STRING` option to change the default. To get the previous behavior, use `--sep=none`, which splits on consecutive whitespace. As a side benefit, `flux mini bulksubmit` can now work with `find -print0` via `--sep='\0'`.
> flux-mini: bulksubmit: fix file input separator and add --sep option

- .github/workflows/asan.yml
- src/test/checks_run.sh
- src/test/docker/docker-run-checks.sh
For some reason the address sanitizer build has been hanging lately and timing out on almost every run. I was going to blame something in #3464, but then it is happening in #3478 as well, so I don't think it is related to any of the pending PRs.
Pending investigation of the hangs, this PR adds a new docker-run-checks option `--unit-test-only` which limits `make check` to run under `src/` only (only unit tests), and then uses that option on the asan build. This should remove the chance for hangs from the address sanitizer build, while still provided some benefit.
Since this PR touches the github workflow config, it will need to be manually merged.
> ci: limit asan build to unit tests only

- NEWS.md
We should be tagging 0.23.0 by monday 1/25 to make the TOSS 3 packaging deadline on Tues 1/26.   I updated the 0.23.0 milestone to reflect this and created a 0.24.0 one to push some things onto.
@chu11 I pushed the `mode=limited`  work you are doing over to 0.24.0 per our earlier discussion, but I'm open to pulling it back in if it can make it.  It sounds like you're now rebased on top of the jobtap PR so maybe?
Here's release notes for stuff merged so far.  As usual feel free to push directly to this PR.
> NEWS.md: prep for 0.23.0 tag

- src/cmd/flux-resource.py
- src/modules/resource/resource.c
- t/t2310-resource-module.t
- t/t2311-resource-drain.t
This ties up a couple of loose ends in the `flux resource` command.  `status`, `drain`, and `undrain` didn't work, and were not being tested on, ranks other than zero.
> flux resource: allow drain, undrain, and status to work on any rank

- doc/Makefile.am
- doc/conf.py
- doc/man3/flux_jobtap_get_flux.rst
- doc/man7/flux-jobtap-plugins.rst
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/jobtap-internal.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- src/modules/job-manager/submit.c
- src/modules/job-manager/submit.h
- src/modules/job-manager/test/submit.c
- t/Makefile.am
- t/ingest/job-manager-dummy.c
- t/job-manager/plugins/test.c
- t/job-manager/plugins/validate.c
- t/t2200-job-ingest.t
- t/t2216-job-manager-plugins.t
This PR changes the `job-manager.submit` protocol that job-ingest uses to submit batches of submitted jobs to the job manager. As described in #3472, job-ingest currently sends jobs in batches to the job manager in an all-or-nothing  approach, either the whole batch succeeds or it fails.
This PR extends that protocol to allow the job-manager to fail individual jobs. The response to `job-manager.submit` now may contain an optional `errors` key which is a list of `[jobid, errmsg]` tuples, each of which indicates that the given `jobid` failed. This allows one or more of a batch of jobs to be failed, each with a different error message.
Finally, a new jobtap hook `job.validate` is added which is called before a job is added to the job manager active jobs hash. A plugin can reject a job from …
> job-manager: allow jobtap plugins to reject jobs

- src/broker/boot_pmi.c
- src/broker/broker.c
- src/broker/overlay.c
- src/common/libutil/ipaddr.c
- src/common/libutil/ipaddr.h
- src/common/libutil/test/ipaddr.c
When the broker bootstraps with PMI, it calls an internal function `ipaddr_getprimary()` that guesses the IP address it sould bind to for downstream TBON peers.  `ipaddr_getprimary()` currently returns the first IP address assigned to the hostname.  On systems like Ubuntu that assign the hostname a local-only address in `/etc/hosts`, a Flux system instance spanning multiple nodes creates batch jobs that cannot wire up.  In addition, IPv6 addresses could be returned, but zeromq is not configured to allow them to work.
This PR changes the heuristic in `ipaddr_getprimary()` to first look up the interface associated with the default route, and use its address if available.  If there is no default route, then fall back to the hostname method.
Zeromq handling of IPv6 addresses is enabled, and …
> broker: improve IP address heuristic in PMI bootstrap

- .github/workflows/asan.yml
- .mergify.yml
- src/cmd/flux-cron
- src/test/docker/README.md
- src/test/docker/checks/Dockerfile
- src/test/docker/fedora33/Dockerfile
- src/test/docker/fedora33/config.site
- src/test/generate-matrix.py
This PR adds a docker image for fedora33 and adds it to our CI matrix. This gets us tests using GCC 10.x.
The asan build is also updated to use fedora33 to get the newer sanitizers in gcc-10.
> ci: add fedora33 docker image for testing

- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/job/__init__.py
- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/job/executor.py
- t/Makefile.am
- t/python/t0023-executor.py
Both Themis and Parsl use Flux in basically the same way. Both have a stream of jobs, and want to stream jobs through Flux. The stream of jobs may be produced dynamically (i.e. as a job runs it produces N new jobs) or the stream may be fixed and static but simply so large that it doesn't make sense to submit all the jobs all at once. For that reason, a mechanism to submit and monitor jobs in bulk (as discussed in #3454 and #2653) isn't quite the right solution, although I think it would be really useful in other circumstances. 
What I think would be really useful to Themis and Parsl, and perhaps to Radical Pilot as well (I'll ask Andre for feedback later), is a [concurrent.futures.Executor](https://docs.python.org/3/library/concurrent.futures.html) type of thing, which is what this PR …
> python: add concurrent.futures executor

- doc/man1/flux-mini.rst
- src/cmd/flux-mini.py
- t/t2203-job-manager-single.t
- t/t2204-job-manager-limited.t
- t/t2205-job-manager-unlimited.t
- t/t2206-job-manager-annotate.t
- t/t2213-job-manager-hold-single.t
- t/t2214-job-manager-hold-limited.t
- t/t2215-job-manager-hold-unlimited.t
- t/t2216-job-manager-priority-order-single.t
- t/t2217-job-manager-priority-order-limited.t
- t/t2218-job-manager-priority-order-unlimited.t
- t/t2703-mini-bulksubmit.t
This PR adds support for `--log=FILE` and `--log-stderr=FILE` options in `flux-mini submit` and `bulksubmit`. These options allow  the `flux-mini` output to be sent to files instead of the terminal. If `FILE` contains substitution strings, then a single `flux-mini` invocation may save output to multiple files.
As a side-effect, `{cc}` may now be used as a substitution in both `submit` and `bulksubmit`. With `bulksubmit`, the substitution of `{cc}` is done in a second pass, since any argument to `--cc` may be substituted in the first pass.
The use case being addressed here is to save jobids from bulksubmit and submit with `--cc` to separate files. This can be accomplished as:
```
$ flux mini submit --cc=1-4 --log=job{cc}.id hostname
```
which will save the jobids to `job1.id` `job2.id` …
> flux-mini: add --log and --log-stderr options

- configure.ac
- src/bindings/lua/flux-lua.c
- src/bindings/lua/jansson-lua.c
- src/bindings/python/_flux/_core_build.py
- src/cmd/flux-R.c
- src/cmd/flux-job.c
- src/cmd/flux-terminus.c
- src/common/libjob/job.h
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-manager/prioritize.c
- src/modules/job-manager/test/submit.c
- src/shell/batch.c
- src/shell/mpir/ptrace.c
- t/Makefile.am
- t/ingest/job-manager-dummy.c
- t/job-manager/print-constants.c
- t/t2208-job-manager-wait.t
This fixes some minor things that prevent compilation on a 32-bit system.
Still need to run down the following in the python bindings.  Dinner time so thought I'd post a checkpoint in case anyone has a hint on this one
```
make[1]: Entering directory '/home/garlick/proj/flux-core/src/bindings/python/_flux'
/usr/bin/python3 _core_build.py 
generating _core.c
Traceback (most recent call last):
File "_core_build.py", line 39, in <module>
ffi.emit_c_code("_core.c")
File "/usr/lib/python3/dist-packages/cffi/api.py", line 692, in emit_c_code
c_file=filename, call_c_compiler=False, **kwds)
File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 1509, in recompile
verbose=compiler_verbose)
File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 1414, in make_c_source
verbose)
File …
```
> fix 32-bit portability issues

- .github/workflows/main.yml
- .mergify.yml
- src/test/docker/docker-run-checks.sh
- src/test/generate-matrix.py
This PR adds another builder to the flux-core GitHub ci workflow that compiles and run tests in a 32 bit environment.
A new `linux/386` image has been pushed up to `fluxrm/testenv:bionic` (bionic is one of the few older distros that support a 32 bit docker base image), and `docker-run-checks.sh` has a new `--platform` option which (if docker supports it), can be used to run under this architecture.
This cross-platform docker support requires the experimental [Docker buildx](https://docs.docker.com/buildx/working-with-buildx/) frontend, which is automatically pulled into the builder if necessary. With buildx, if qemu and binfmt_misc are present, then the docker image may run under qemu, allowing foreign architecture docker containers to run on x86, (e.g. ppc64le arm64, etc). However, this …
> Add a 32 bit build to github ci checks

- src/cmd/flux-mini.py
- src/modules/job-exec/job-exec.c
- t/t2703-mini-bulksubmit.t
This is a set of fixes for `flux mini submit --progress --wait` which were discovered while developing the test for #3505.
Some incorrect assumptions and bugs in the counters displayed in the progress bar caused duplicate or negative counts when jobs had exceptions during intialization.
Also included is a fix for many of the tests in `t2703-mini-bulksubmit.t` which we've seen fail recently. (Bad assumption that all jobs would get submitted before the first job ran)
> flux-mini: fix --progress counters with job exceptions

- src/common/librouter/Makefile.am
- src/common/librouter/test/usock_emfile.c
- src/common/librouter/usock.c
- src/modules/job-exec/exec.c
- t/Makefile.am
- t/issues/t3503-nofiles-limit.sh
This PR fixes the segv reported in issue #3505 and adds the reproducer described in that issue.
I have this marked as WIP because another issue remains. Every 10-20 times I run the reproducer, instead of failing immediately, the failed jobs appear to hang for an indeterminate amount of time, and the flux-broker process spins at 100% CPU. It is a challenge figuring out exactly what is happening during that time though, and after many seconds, the problem resolves itself.
I hope to find at fix that issue in this PR, but I don't get anywhere soon we may want to merge this one as is.
> fix segfault and slowdown when broker exceeds max number of open files

- src/broker/broker.c
- src/broker/modservice.c
- src/broker/module.c
- src/cmd/flux-module.c
- src/common/libflux/module.h
This PR removes the prep/check based module keepalive messages completely. Now those messages are only sent to the broker in order to transition modules out of INIT state to RUNNING (which now only means the module is not initializing) and finalizing/exited.
Since there is no longer a case for FLUX_MODSTATE_SLEEPING, that module is removed (already updated RFC 5).
> module: reduce keepalive message traffic

- doc/man3/flux_future_get.rst
- src/common/libflux/future.c
- src/common/libflux/reactor.c
- src/common/libflux/reactor.h
- src/common/libflux/test/future.c
This was peeled off of PR #3512.  It changes `flux_future_reset()` to restart any timeout that was specified in the call to `flux_future_then()`.   This change has no effect when the future is used non-reactively.
In addition, a more efficient mechanism of managing the recurring reactor timeout is used, as documented in the libev manual.  This method required `ev_timer_again()` to be used, so it is exposed in our API as `flux_timer_watcher_again()`.
There's a bit of cleanup in the surrounding code here as well.
> libflux: restart continuation timeout in flux_future_reset()

- src/cmd/flux-job.c
- src/cmd/flux-kvs.c
- t/kvs/transactionmerge.c
Problem: Sometimes flux_future_then() is called after
flux_future_reset() to reset the continuation timeout.
These calls are no longer necessary due to update of
flux_future_reset() in PR 3518 / commit
dca95688b24459b1e67492d7d4302abfdfb10476
Solution: Remove unnecessary flux_future_then() calls.  Cleanup
code accordingly.
> remove unnecessary flux_future_then calls

- doc/man1/flux-content.rst
- doc/man1/flux-module.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- src/broker/content-cache.c
- src/broker/module.c
- src/broker/module.h
- src/broker/overlay.c
- src/broker/overlay.h
- src/modules/kvs/cache.c
- src/modules/kvs/cache.h
- src/modules/kvs/kvs.c
- src/modules/kvs/kvsroot.h
- src/modules/kvs/kvssync.c
- src/modules/kvs/kvstxn.c
- src/modules/kvs/kvstxn.h
- src/modules/kvs/lookup.c
- src/modules/kvs/lookup.h
- src/modules/kvs/test/cache.c
- src/modules/kvs/test/kvsroot.c
- src/modules/kvs/test/kvssync.c
- src/modules/kvs/test/kvstxn.c
- src/modules/kvs/test/lookup.c
- src/modules/kvs/treq.c
- src/modules/kvs/waitqueue.c
This was peeled off of PR #3512.
In several places including the KVS cache, content-cache, and broker overlay network, objects are aged by counting the number of elapsed heartbeat messages.  This is prone to inaccuracy because those messages can be delayed and "bunch up" due to overlay network congestion, head of line blocking, etc..
This PR uses elapsed time, as reported by `flux_reactor_now()` to age those objects, instead of the heartbeat epoch.  The heartbeat messages only drive the periodic checks, so it's still possible to be late timing something out, but that's less likely to be a source of problems than timing something out early.  For example, early timeout of TBON peers could cause responsive nodes to be drained (once we implement #3448).  Tardiness of heartbeat callbacks will …
> use reactor time instead of heartbeats for internal time management

- t/lua/t1001-timeouts.t
- t/t2604-job-shell-affinity.t
Update usage of `hwloc-calc`, as additional output in newer versions is messing up some scripting.
Also fix up a typo I found.
> testsuite: update hwloc-calc usage

- src/cmd/flux-kvs.c
- t/t0001-basic.t
Problem: Sometimes --help will not output help output if the
user is not running in a flux instance.
Solution: flux-kvs would flux_open() before all options were
parsed in subcommands.  Instead every subcommand should call
flux_open().  Each subcommand knows when it has completed all
option parsing.
Fixes #3491
> flux-kvs: output --help if not in an instance

- .github/workflows/main.yml
Problem: When a tag is pushed, GitHub Actions does not appear to
properly checkout the tag such that `git describe` returns a SHA
suffix version instead of the version being tagged.
When creating a release, add a step after git clone that explicitly
checks out the tag ref to hopefully work around this problem.
> github: explicitly checkout tag if creating a release

- doc/test/spell.en.pws
- src/broker/Makefile.am
A couple of trivial items were missed in PR #3512. Without this fix, `./autogen.sh` complains:
```
autoreconf: running: automake --add-missing --copy --no-force
src/broker/Makefile.am:101: warning: variable 'test_heartbeat_t_SOURCES' is defined but no program or
src/broker/Makefile.am:101: library has 'test_heartbeat_t' as canonical name (possible typo)
src/broker/Makefile.am:103: warning: variable 'test_heartbeat_t_LDADD' is defined but no program or
src/broker/Makefile.am:103: library has 'test_heartbeat_t' as canonical name (possible typo)
src/broker/Makefile.am:104: warning: variable 'test_heartbeat_t_LDFLAGS' is defined but no program or
src/broker/Makefile.am:104: library has 'test_heartbeat_t' as canonical name (possible typo)
autoreconf: Leaving directory `.'
Now run ./configure. …
```
> build/test: remove stale heartbeat references

- README.md
- config/tap-driver.py
- configure.ac
- src/bindings/python/_flux/make_clean_header.py
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/job/Jobspec.py
- src/bindings/python/flux/kvs.py
- src/bindings/python/flux/message.py
- src/bindings/python/flux/security.py
- src/bindings/python/flux/util.py
- src/bindings/python/flux/wrapper.py
- src/cmd/flux-jobspec.py
- src/modules/job-ingest/validators/validate-jobspec.py
- src/modules/job-ingest/validators/validate-schema.py
- t/jobspec/summarize-minimal-jobspec.py
- t/python/sideflux.py
- t/python/subflux.py
- t/python/t0001-handle.py
- t/python/t0002-wrapper.py
- t/python/t0003-barrier.py
- t/python/t0004-event.py
- t/python/t0005-kvs.py
- t/python/t0009-security.py
- t/python/t0010-job.py
- t/python/t0012-futures.py
- t/python/t0013-job-list-inactive.py
Two pretty trivial changes. The first commit fixes a problem I introduced in #3019. When you set a jobspec's stdout/err property to ``None``, the job will hit an exception:
```
JobWaitResult(jobid=22162702336, success=False, errstr=b'Fatal exception type=exec shell_init: No such file or directory')
```
The error message actually confused me for a little while, and it's such an easy fix, that I think it's worth it.
(Edit: it's especially confusing because the properties default to ``None``, which works fine, but if you explicitly set them to ``None`` the job will fail.)
The second commit removes references to the ``six`` module. I noticed them while I was working on the first commit and so I just went ahead and replaced the ``six`` aliases with their Python 3 names.
I would be happy to …
> Python: fix "no such file or directory" job exception resulting from bad jobspec

- src/common/libjob/job.c
- src/modules/job-info/guest_watch.c
- src/modules/job-info/guest_watch.h
- src/modules/job-info/job-info.c
- src/modules/job-info/watch.c
- t/t2231-job-info-eventlog-watch.t
Problem: Two RPC targets handle watching of job eventlogs, the "job-info.eventlog-watch" target and the "job-info.guest-eventlog-watch" target (in addition to the "cancel" equivalents).  This can be confusing to anyone who wish to call these targets directly, as the path of the job eventlog will determine which should be called.
Solution: Consolidate these two targets into the single "job-info.eventlog-watch" target.  Internally, `job-info` will determine if the standard 'watch' or special 'guest watch' code path should be used.
Update `libjob` accordingly.
Remove now non-applicable tests.
Fixes #2330
> job-info: consolidate watch RPC targets

- t/t2601-job-shell-standalone.t
- t/t2611-debug-emulate.t
- t/t4000-issues-test-driver.t
- t/valgrind/valgrind.supp
This PR extends some testsuite timeouts and adds the known libhwloc leak discovered by @chu11 to valgrind suppressions in order to make the testsuite reliably pass on TOSS4 systems. The timeout increases are required because there is some uncharacterized performance degradation affecting Flux on these systems.
On this branch `make -j 16 check` reliably passes on fluke, where without it that command fails every time.
Fixes #3522
> enhance testsuite reliability on RHEL8/TOSS4

- .github/stale.yml
This PR adds configuration for [probot/stale](https://probot.github.io/apps/stale/) which will start commenting on stale issues (currently configured for 84 days of inactivity) and PRs. The bot will autoclose issues and PRs if there isn't activity within 7 days of the issue being marked stale (using the `wontfix` label).
The bot is configured to only perform 2 actions (per hour I think?) so that we don't get inundated with comments. Over a couple weeks or so, the bot should help us clean up a lot of stale issues.
> github: add a stale issues and PR bot for flux-core

- src/broker/broker.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/overlay.c
This PR moves some code for manipulating message routes and zeromq sockets into overlay.c, to reduce the complexity of broker.c a little.  Two overlay receive callbacks become one, and three overlay send functions become one.  It's just cleanup.  There should be no functional changes here.
The overlay unit test is bolstered with some new tests, although I imagine this area of code is pretty well covered by sharness tests anyway.
> broker: refactor overlay network send/receive interfaces

- doc/man7/flux-broker-attributes.rst
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/cmd/flux-start.c
- src/shell/lua.d/openmpi.lua
- src/shell/lua.d/spectrum.lua
- src/shell/pmi/pmi.c
- t/t0001-basic.t
- t/t2601-job-shell-standalone.t
- t/t2602-job-shell.t
- t/t3000-mpi-basic.t
- t/t3002-pmi.t
As noted in #3551, the current strategy of setting `OMPI_MCA_orte_tmpdir_base` for OpenMPI to the broker run directory probably won't work for a multi-user instance, when the instance owner != the job owner.  It also covers up an actual problem, which is an inaccuracy in our `PMI_process_mapping` generation.
The inaccuracy is that each shell is considered a separate "clique", but when multiple brokers are launched per node, those cliques are really on the same node, which breaks assumptions in OpenMPI and causes segfaults.
So get `PMI_process_mapping` when the broker bootstraps and store that in an attribute.  Then in the shell, fetch the broker's mapping and determine whether it is safe to treat each shell as a clique, or whether the job's mapping should be for one big clique (standalone …
> fix PMI_process_mapping when Flux is launched with multiple brokers per node

- config/x_ac_pmix.m4
- configure.ac
- src/broker/Makefile.am
- src/broker/boot_pmi.c
- src/broker/pmiutil.c
- src/broker/pmiutil.h
- src/broker/runat.c
- src/broker/test/pmiutil.c
- src/cmd/Makefile.am
- src/cmd/builtin/version.c
- src/test/docker/bionic/Dockerfile
- src/test/generate-matrix.py
- t/Makefile.am
- t/t2009-pmix-bootstrap.t
PMIx support for bootstrapping flux is added by running
configure --with-pmix[=PATH]
When specified, PATH must contain the pmix.h header file.
PMIx is used at bootstrap by running
flux start --bootstrap=pmix
Limitations:
- configure does *not* check PATH contains the pmix.h header file
- libpmix.so currently has to be in the LD_LIBRARY_PATH
> broker: add support for PMIx bootstrap

- doc/man7/flux-broker-attributes.rst
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/broker.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/overlay.c
- src/cmd/flux-start.c
- src/modules/connector-local/local.c
- t/t0001-basic.t
This is based on top of #3553.
With `PMI_process_mapping` available in the broker, use it rather than an explicit broker command line option from `flux start` to determine when `ipc://` can be used in place of `tcp://` for the overlay network.
In addition, perform the following cleanup that falls out from these changes:
* Don't allow `tbon.endpoint` to be set on the command line.  We don't need this anymore now that we can bootstrap from config files, and `flux-start` doesn't need to set it tell the broker to use `ipc://`
* Eliminate `broker.rundir`, the ranked subdirectory of `rundir`.  Instead append the rank to `ipc://` paths when used, and to the local URI, in case `rundir` happens to be shared by multiple brokers (e.g. standalone `flux start`).
* Eliminate the callback triggered by …
> broker: drop broker.rundir and select ipc vs tcp using broker.mapping

- src/modules/job-info/Makefile.am
- src/modules/job-info/allow.c
- src/modules/job-info/allow.h
- src/modules/job-info/guest_watch.c
- src/modules/job-info/guest_watch.h
- src/modules/job-info/job-info.c
- src/modules/job-info/job-info.h
- src/modules/job-info/lookup.c
- src/modules/job-info/lookup.h
- src/modules/job-info/watch.c
per discussion in #3521 
consideration: should I drop the commit for the "always-lookup-job-owner" option?  It's very specific to testing this LRU support, and isn't something I even bothered to add a test into sharness for.  It really can't be used for anything else.  I'm leaning towards removing that commit, but thought I'd leave in for the time being.
> job-info: support LRU cache mapping job id -> owner

- src/common/libflux/plugin.c
- src/common/libflux/plugin.h
- src/common/libflux/test/plugin.c
- src/common/libutil/aux.c
- src/common/libutil/aux.h
- src/common/libutil/test/aux.c
Per discussion in #3561, make `aux_delete()` available in the aux base that lets an anonymous item be removed by value.  Its destructor is called, if defined.
Add corresponding method to the `flux_plugin` class.
> libflux: add flux_plugin_aux_delete()

- src/broker/test/boot_config.c
- src/common/libflux/test/module.c
- src/common/libflux/test/rpc.c
- src/common/libhostlist/test/hostrange.c
- src/common/libioencode/test/ioencode.c
- src/common/libjob/job.c
- src/common/libkvs/test/kvs_dir.c
- src/common/libkvs/test/kvs_txn_compact.c
- src/common/librouter/test/router.c
- src/common/librouter/test/usock.c
- src/common/libsubprocess/test/cmd.c
- src/modules/content-files/test/filedb.c
- src/modules/job-manager/test/annotate.c
- src/modules/kvs/test/lookup.c
So due to a ASAN failure in #3548, I tried to run ASAN on TOSS4 and hit all of these other ASAN discovered memleaks when trying to debug my PR's issue (i.e. `make check` was constantly failing all over the place, never getting to the unit test failure I hit in CI).
I thought these were new ASAN discoveries in TOSS4 over TOSS3, but @grondo reminded me that we turn off leak detection in the CI b/c there are too many and many can't be fixed.   But by this point I had already gone down the path of fixing a bunch of these leaks.
I saw no reason to waste these fixes, so here they are and some extras as I continued the exercise.  I did find one actual memleak in `libjob`, so the exercise wasn't a complete waste of time.
> Fix various memleaks discovered by ASAN

- src/modules/kvs/cache.h
- src/modules/kvs/kvs.c
- src/modules/kvs/kvstxn.c
Per discussion in #3549, this fixes an assert due to a missing cache entry that expires when the KVS is heavily loaded.
There is some discussion in #3549 about some additional cleanup, but in the interest of getting this into the 0.25.0 milestone, I decided to work on the cleanup after this specific fix.  I'll send (future) cleanups in a separate PR.
Side note: the core patch has been cleaned up compared to what I put in the 0.19.0 side branch.
https://github.com/chu11/flux-core/tree/issue3549_v0190_kvs_assert
> kvs: fix assert due to busy KVS

- etc/flux.service.in
Problem: the flux system instance by default uses munge to
sign/verify job requests, but declares no dependency in its
systemd unit file.
Add a 'Wants: munge-service' to the flux systemd unit file.
This ensures that the munged service is automatically started
if available, but does not prevent flux from starting if not.
See also:
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Wants=
Fixes #3571
> systemd: configure weak dependency on munge

- README.md
Thanks to @jameshcorbett, flux-core no longer requires the python `six` package, but this package still appears in the cut-n-paste RH and Ubuntu package install commands.
This PR simply removes the `python3-six` package from these lines of the `README.md`
> README.md: remove python3-six dependency

- src/common/libutil/aux.c
The aux container used to implement `_aux_get()` and `_aux_set()` in several Flux API classes was implicated in a performance issue described in #3583.  This PR implements two optimizations affecting the linear search of `aux_get()`: 1) allocate the aux item key with the item struct, to reduce cache overhead, and 2) store anonymous entries at the end of the list and stop searching once the first anonymous entry is encountered.
The first change may or may not have an effect but it seems like good citizenry to to collapse two mallocs into one anyway.  The second change seemed obvious after seeing @chu11's fix in #3585, where a large number of anonymous entries in a `flux_t` handle were slowing down access to keyed items.
> libutil: add minor optimizations to aux container

- doc/man3/flux_aux_set.rst
- src/common/libflux/handle.h
- src/common/libflux/test/msg_handler.c
- src/common/libkvs/kvs_copy.c
Per discussion in #3583.
Problem: In `flux_kvs_copy()` and `flux_kvs_move()` some auxiliary data was stored in the flux handle, with a destructor set for when the handle is destroyed.  However, the flux handle is a long lived object, typically staying alive for the length of a flux instance.  Therefore, the memory is basically never freed during the existence of the instance.
This continual memory allocation led to a very large auxiliary list in the underlying implementation and poor performance for long running instances with many jobs.
Solution: Move the auxiliary data from the flux handle to the futures used within `flux_kvs_copy()` and `flux_kvs_move()`.  These futures are short lived, therefore auxiliary memory will be cleaned up more regularly.
Also add some extra documentation to …
> libkvs: save aux data in future instead of handle

- src/broker/broker.c
- src/broker/content-cache.c
- src/broker/content-cache.h
- src/common/libflux/msglist.c
- src/common/libflux/test/msglist.c
- src/common/libutil/aux.c
On the off chance that the content-cache's use of `zhash_t`, with its lack of growth management, has an impact on our job throughput slowdown documented in #3583, here's a quick conversion to `zhashx_t` and some other minor cleanup.
I haven't had a chance to test if this has any impact on performance - just posting it before breaking for dinner.
> use zhashx_t for content-cache

- src/common/libflux/handle.c
Problem: flux_matchtag_free() scans the handle "backlog" of
received messages for responses containing the matchtag that
is proposed to be freed, and removes any matches, but the RPC
code knows not to call flux_matchtag_free() if the matchtag
cannot be safely retired.
Drop this code, which adds overhead for little benefit.
> libflux/handle: drop paranoid matchtag free code

- doc/man1/flux-jobs.rst
- doc/man7/flux-jobtap-plugins.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/job/list.py
- src/cmd/flux-job.c
- src/cmd/flux-jobs.py
- src/common/libutil/Makefile.am
- src/common/libutil/grudgeset.c
- src/common/libutil/grudgeset.h
- src/common/libutil/test/grudgeset.c
- src/modules/job-list/job_state.c
- src/modules/job-list/job_state.h
- src/modules/job-list/job_util.c
- src/modules/job-list/list.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- src/modules/job-manager/list.c
- t/Makefile.am
- t/job-manager/plugins/dependency-test.c
- t/job-manager/plugins/test.c
- t/t2212-job-manager-plugins.t
- t/t2270-job-dependencies.t
This is WIP that adds support for `dependency-add`/`dependency-remove` events in the job manager, with hooks for jobtap plugins to generate these events.
This is not too useful yet since only one jobtap plugin can be loaded simultaneously. However it can be used to develop proof-of-concept job dependency plugins, which could then be used once jobtap supports a suite of plugins.
Still todo here is to add discovery of dependencies to `job-list` so outstanding dependencies can be listed, and doc updates.
Example: The following is a plugin that sets a delay if a job has `attributes.system.delay-start` set:
```c
#include <stdio.h>
#include <jansson.h>
#include <czmq.h>
#include <flux/core.h>
#include <flux/jobtap.h>
static flux_future_t *flux_future_timer (flux_reactor_t *r,
double timeout, …
```
> job-manager: enable job dependency management

- doc/man1/flux-content.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- src/broker/content-cache.c
- src/broker/content-cache.h
This replaces the intensive scanning of the content-cache on every heartbeat to find candidates for purge with a simple LRU, patterned after @grondo's LRU implementation in `src/common/libutil/lru_cache.c`.  This is integrated with the internal data structures of the content cache for efficiency, and so does not use that implementation directly.
I thought I'd park this and take a more in-depth peek at its performance impact after #3591 is addressed.
There is some other quasi-related cleanup here as well.
> use LRU to purge content-cache

- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/wrapper.py
- src/common/libflux/rpc.c
- src/modules/job-manager/alloc.c
Problem: errno values not pre-defined in the `errno.errorcode[]` dictionary cause our python API wrappers to throw a second exception within exception-throwing code.  This can actually occur since 0MQ functions called by Flux functions can set errno to 0MQ-specific values.
Protect against accessing an undefined dictionary entry:  when the errno value is unknown, use "ErrnoN" (N=errno) instead.
Plus some other errno related fixes are thrown in.
Edit: dropped the addition of EFLUXED generic failure code.
> python: avoid throwing 2nd exception on unknown errno

- Makefile.am
Add libczmqcontainers to the code coverage exclusion list since
it is a copy of an external library.
> build: ignore code coverage on libczmqcontainers

- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/state_machine.c
- src/broker/test/overlay.c
- t/t0001-basic.t
This adds a handshake, when a broker connects to its TBON parent, to verify that they are running compatible versions of flux-core (exact match required for now), and checking that the connecting rank is really a peer.
This solves two potential real world system instance cases
1) Out of sync bootstrap config file resulting in improper TBON wire-up
2) A flux package upgrade that misses some nodes
If either of these error conditions is detected, the (child) broker emits a human readable error to stderr and exits with a nonzero exit code.  In the system instance case, the error would be captured in the systemd journal, and systemd would not automatically restart the failing broker.  In the non system-instance case, the enclosing instance (or `flux-start`) would capture stderr and, depending …
> add overlay network version/config check

- src/broker/attr.c
- src/broker/broker.c
- src/broker/broker.h
- src/broker/module.c
- src/broker/module.h
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/ping.c
- src/broker/test/overlay.c
- src/common/libflux/message.c
Problem: a broker sends an RPC, but gets rebooted before receiving all the responses.  The in-flight response messages, routed by source address to the broker identity, currently its rank, might reference a matchtag that the broker has forgotten it allocated, and may have allocated to another RPC.  The resulting mix-up is likely to be difficult to debug.
Solution: use a UUID instead of the rank for the broker identity.  Regenerate the UUID at broker startup, so that old responses are dropped rather than routed to a restarted broker.
This PR also contains some cleanup in related code.
This is currently based on top of #3597.
> broker: use UUID instead of rank for response routing

- src/broker/boot_pmi.c
Here's a fix for the mvapich "invalid tag" error from `MPI_Init()` @jameshcorbett  reported in #3592.
This error occurs when flux is started by `flux start`, without `--size` or `--bootstrap=selfpmi` options, outside of a job.  When run that way, the broker uses its "singleton" PMI bootstrap mode.  The singleton mode does not find a `PMI_process_mapping` to stuff into the `broker.mapping` attribute for the shell to find later, and the pmi shell plugin thus thinks it cannot generate `PMI_process_mapping` for its jobs.  This makes mvapich sad, apparently.
Since the process mapping of a singleton is always `(vector,(0,1,1))`,  the fix is to just set the `broker.mapping` attribute to that when the instance size is 1.  See [RFC 13](https://flux-framework.readthedocs.io/projects/flux-rfc/en/late …
> avoid mvapich segfault under flux start singleton

- doc/man1/flux-start.rst
- src/broker/doc/README.md
- src/cmd/flux-start.c
- t/README.md
- t/fluxometer.lua
- t/python/sideflux.py
- t/python/subflux.py
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t1001-kvs-internals.t
As suggested in #3599, this renames some confusing `flux start` options.
The `--size=N` option is renamed to `--test-size=N` (retaining `-s` short option).
The `--bootstrap={pmi|selfpmi}` option is dropped.  The `--test-size` option now implies "selfpmi".
There will need to be a small sharness patch applies to `flux-sched` after this is merged.
> flux-start: rename --size to --test-size, drop --bootstrap

- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/future.py
- t/issues/t3186-python-future-get-sigint.sh
- t/python/t0012-futures.py
- t/python/t1000-service-add-remove.py
Problem: the service (un)register functions are currently not manually
wrapped and leverage the auto-generated bindings.  The auto-generated
bindings do not automatically wrap the returned `flux_future_t` in a
python `Future` object.  Thus registering a service currently requires
the following code:
```python
future = f.service_register(name)
f.future_get(future, ffi.NULL)
```
Solution: manually wrap the service (un)register functions so that a
`Future` object is returned automatically.  This simplifies the code to:
`f.service_register(name).get()`
> python: add explicit service_(un)register method

- doc/man3/flux_future_and_then.rst
- src/bindings/python/flux/job/__init__.py
- src/bindings/python/flux/job/wait.py
- src/cmd/flux-job.c
- src/common/libflux/composite_future.c
- src/common/libflux/future.h
- src/common/libflux/test/composite_future.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- t/python/t0010-job.py
- t/t2501-job-status.t
This is an offshoot of an idea proposed by @jameshcorbett in #3575.
The code for `flux job status` is abstracted into a new API function: `flux_job_wait_status(3)`. This function returns a future that is fulfilled when the job eventlog reaches the end condition, and the future result contains some convenient information for getting a processed exit code, detecting if the job started or hit an exception, etc.
`flux job status` is then switched to this new interface.
Not too happy about the name of the function nor the requirement for a new structure added to the interface, but this is just an early demonstration for now.
A next step would be to develop a Python binding using this interface that meets @jameshcorbett's use case.
Fixes #3575
> libjob: add flux_job_result(3)

- src/cmd/flux-jobtap.py
- src/common/libflux/msg_handler.c
- src/common/libflux/test/dispatch.c
- src/modules/job-manager/jobtap.c
- t/t2212-job-manager-plugins.t
As described in #3476, there is a problem when a duplicate non-glob msg handler is added to the dispatcher. The duplicate handler replaces the current handler in the internal "method handlers" hash, and then when either the old or new handler is destroyed, the hash entry is purged leaving an active but non-function msg handler.
This PR changes the single msg_handler entry in the `dispatch->handlers_method` hash into a stack of handlers. Handlers are pushed onto this stack as they are added, and the only the top handler is currently "active" (even if it is not currently started). The internal list is only created when a second matching request handler is added to a  handle.
Since the underlying issue is fixed, the workaround in the jobtap code is removed. Now when the load of a plugin …
> libflux: msg_handler: capture duplicate non-glob request handlers in a stack

- .mergify.yml
- src/test/checks_run.sh
- src/test/throughput.py
- t/test-inception.sh
This is a tiny set of unrelated changes to the testsuite and ci:
- Switch from `prove` to `flux mini bulksubmit` for the "inception" tests. We now get better reporting if a test fails when run as a Flux job.
- Add the `throughput.py` test to `src/test/throughput.py` (I thought about adding it as non-installed subcommand `src/cmd/flux-througput.py` so one could run `flux throughput ...` from builddir of Flux, but didn't go there)
- Add a config to mergify to dismiss all approving reviews when a PR from a non-maintainer is updated.
Since the mergify config is updated, this PR will have to be manually merged.
> ci/test: switch to bulksubmit for inception tests, add throughput test, dismiss reviews after PR updates

- src/common/libflux/barrier.c
- src/shell/output.c
Here are a couple of optimizations peeled off of the withdrawn PR #3567 (`flux job exec`).  My comment about these from that PR was:
> One is to turn a barrier with nprocs=1 into a no-op (avoiding an RPC). This affects all barriers, but in particular I was thinking of the one in the shell, to make the case of a single node job with one shell a little faster.
>
> The other is to shunt task output in the rank 0 (leader) shell directly to buffers rather than have rank 0 send an RPC to itself just for a slight code readability benefit. Thus, a one node job would not use any RPCs to collect output from the tasks, though nothing changes after that point (e.g. shell still commits output to KVS).
>
> The 100x serial /bin/true test didn't seem to be affected, and neither did 100x serial …
> flux-shell: add minor optimizations for single node jobs

- src/common/libutil/log.c
Problem: libutil's log library calls zmq_strerror(), which creates
a libflux-core.so dependency on libzmq.so, but 0MQ only defines a
handful of error numbers.
Call strerror() instead.  If strerror() encounters an unknown
error code, it is printed numerically.
Fixes #3620
> libutil: avoid zmq_strerror()

- src/broker/content-cache.c
The "content cache" stores blobs keyed by their hash value for the KVS.   The cache is hierarchical, with a backing store at broker rank 0, and memory caches on all broker ranks.  The memory cache is "built in" to the broker, e.g. it shares the broker thread.
On the heartbeat, if the memory cache size is above a configured threshold (16MB default), then blobs are purged in LRU order until usage falls below the threshold.  The LRU scan is aborted early if an entry is reached that is younger than a configured age (10s by default).  Along the way, any entries that are dirty (not yet written upstream/to backing store) or invalid (not yet filled from upstream/backing store) are not eligible for purge and are skipped over.
While thinking about @dongahn's performance issue in #3630, I became …
> content-cache: make LRU purge more effective

- src/common/libflux/disconnect.c
- src/common/libflux/disconnect.h
- src/common/libflux/message.h
- src/modules/job-info/guest_watch.c
- src/modules/job-info/guest_watch.h
- src/modules/job-info/job-info.c
- src/modules/job-info/watch.c
- src/modules/job-info/watch.h
- src/modules/kvs-watch/kvs-watch.c
- src/modules/kvs/kvs.c
Since the fixes for #3526, #3528, #3529 are similar and all related, I've put them all in this PR, although we could split them out.
1) Add a new function `flux_msg_match_cred()` to handle the common case check of ensuring a message came from an instance owner or the userid of the sender matches another message's userid.
2) Clean up some cancel/disconnect code that manually matched message senders and instead use `flux_msg_match_route_first()`
3) Add a call to `flux_msg_match_cred()` to also check for a guest user credentials.
I didn't add any tests as I'm confident that existing tests already cover this (since its cancel paths) or we've generally never covered (disconnect).
> job-info, kvs-watch: support guest disconnect & credential checks

- src/cmd/flux-kvs.c
- src/modules/kvs/kvs.c
Per #3637, make a KVS namespace create failure a little clearer with an error msg attached to the error if a namespace is in the process of being removed.
I went back and forth on keeping the errno EEXIST vs EAGAIN, eventually settling on EAGAIN.  But it could be EEXIST instead.
> kvs: add errmsg on namespace create failure

- src/cmd/flux-start.c
- t/t0001-basic.t
- t/t0013-config-file.t
- t/t2310-resource-module.t
- t/t3200-instance-restart.t
- t/valgrind/valgrind.supp
This fixes/works around some test issues that popped up over the weekend when I started using a freshly installed Ubuntu 20.04 LTS system with an nvidia GPU.
Continuing in the "test enhancements" vein, this adds a new `flux start --test-hosts=HOSTLIST` option to enable a config file bootstrapped flux instance to be started in test.  That cleaned up some fragile "manual start" scripting in `t0013-config-file.t` .  It also prepares for  future tests that will restart brokers (since PMI bootstrap is not restartable).
> testsuite: handle hwloc issues and improve config file bootstrap test

- doc/man1/flux-proxy.rst
- src/broker/broker.c
- src/cmd/builtin/proxy.c
- t/t1105-proxy.t
As suggested in #1816, a `flux-proxy` connection to a different Flux version can result in hard to debug problems.
This PR adds a version check.  If the version is mismatched, it is treated as a fatality unless a `--force` option is used.  Later when version interoperability is more important, we can relax the check if needed.
Note: only the major, minor, patch version _numbers_ are checked.  Any git suffix on the patch is ignored.
> flux-proxy: add flux-core version check

- src/cmd/flux-start.c
- src/common/libflux/event.h
- src/common/libflux/message.h
- src/common/librouter/Makefile.am
- src/common/librouter/test/usock_service.c
- src/common/librouter/usock_service.c
- src/common/librouter/usock_service.h
- t/Makefile.am
- t/scripts/startctl.py
- t/t0001-basic.t
This adds a convenience function for setting up an embedded server that listens on a `local://` socket and routes messages between connected clients and a server side `flux_t` handle.  It's a bit of an abomination if you think about it too hard, but it does let arbitrary programs offer "services" in the usual way by registering message handlers, and clients to connect to it and use RPCs the way they would do with flux, so pretty convenient.
Maybe this will come in handy if the shell needs to offer a standalone service to applications, especially if that application is flux?
A server is then embedded in `flux-start` for the purpose of enabling system tests that restart brokers.  In this PR, the only service method just lists broker pids.  I thought maybe getting this much in with tests was …
> flux-start: add embedded server

- src/modules/kvs/Makefile.am
- src/modules/kvs/kvs.c
- src/modules/kvs/kvsroot.c
- src/modules/kvs/kvsroot.h
- src/modules/kvs/kvstxn.h
Per discussion in #3633.
I went back and forth on implementation eventually settling on a `zlist` "work_queue".  I dislike the fact I have a "on_work_queue" flag placed in the `struct kvsroot` structure.  It sort of breaks abstraction of that struct.  I could ...
1) just search the list instead of maintaining a flag, but that's a lot of iteration and we don't want to do that.
2) use a `zhash_t` instead, but a `zhash` foreach iterates through all hash buckets, and we're trying to limit iteration
3) use a `zhash_t` along w/ a `zlist_t`, using the `zhash_t` just for "is it on the list" management.  Seems like a lot of effort for just the flag.
Using @grondo's namespace benchmark.
Before
```
0.19s: Benchmark on 256 namespaces complete: 1382.4 namespace/s
0.35s: Benchmark on 512 namespaces …
```
> kvs: improve performance of transaction prep/check

- t/t3200-instance-restart.t
Problem: In previous commit
commit bb9e4faac34df8b6ae31c9c0b2430841226b4678
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Tue May 11 18:41:06 2021 -0700
testsuite: make jobid capture ignore stderr gunk
the jobid is assumed to be the last output. However, in some environments
there may be extraneous output before and after the jobid is output.  Leading
to test failures in those environments.
Solution: Go back to the jobid parsing logic from
commit 77ef3e822ae24a71b352573db3f64ae078488e22
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Fri Mar 13 09:35:56 2020 -0700
testsuite: cover jobid order across restart
but add an additional "grep" call to limit jobid parsing
to only lines with the "jobid:" prefix.
This should also deal with the issues fixed by:
commit …
> testsuite: modify jobid capture logic

- doc/man1/flux-mini.rst
- src/cmd/flux-mini.py
- t/t2700-mini-cmd.t
- t/t2703-mini-bulksubmit.t
This small PR fixes a couple of annoyances when working with `flux-mini --setattr`.
1. Currently, substitution of `{cc}` is attempted with `flux mini submit` even if `--cc` or `--bcc` wasn't used. This means that even the simplest objects cannot be specified as values with `flux mini submit --setattr=`. Avoid doing the "input" substitution in `flux mini submit` when no `--cc` or `--bcc` argument was used, since it isn't necessary anyway.
2. More moderately complex jobspec attributes get really unwieldy to specify with `--setattr`, since the quoting gets painful quite quickly. Also, they can't be specified at all with `bulksubmit` due to 1. above. Add an option to read the attribute value from a JSON file when the attribute key starts with `^`. (I realized after the fact that another …
> flux-mini: avoid substitution without --cc/bcc, allow --setattr value to be read from file

- src/modules/kvs-watch/kvs-watch.c
- src/modules/kvs/kvstxn.c
- src/modules/kvs/test/kvstxn.c
As discussed in #3615, there is some bottlenecking at larger scales in the KVS `normalize_and_append_unique()` function.  In the function, a json array is regularly searched to determine if any keys are duplicates of each other.  This is is an O(N^2) search with a not so friendly `strcmp()` in the middle.
As an experiment I modified the "array search" to use a json object as a "hash lookup".  Effectively replacing a `json_array_foreach` & `strcmp` with a single call to `json_object_get()`.
The results using the nsbench benchmark.
Before
```
0.17s: Benchmark on 256 namespaces complete: 1468.3 namespace/s
0.35s: Benchmark on 512 namespaces complete: 1469.0 namespace/s
0.70s: Benchmark on 1024 namespaces complete: 1461.4 namespace/s
1.35s: Benchmark on 2048 namespaces complete: 1519.2 …
```
> kvs: use json object to find duplicate keys

- doc/man7/flux-jobtap-plugins.rst
- src/cmd/flux-mini.py
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap-internal.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/submit.c
- t/job-manager/plugins/dependency-test.c
- t/t2212-job-manager-plugins.t
- t/t2270-job-dependencies.t
This PR adds support for the `job.dependency.<scheme>` jobtap callback topic as proposed in #3651.
These callbacks are issued just after the `job.validate` callback so that jobs with invalid dependency spec or an unsupported dependency `scheme` can be rejected before they are fully submitted.
This first required queueing dependency-add/remove events in the `struct job *` structure, for later posting in the DEPEND state (since events can't be posted to a job that is not yet active). (Pulled in @garlick's commit to add aux list to `struct job` for this purpose)
For simplicity, redundant add/remove events are queued and then ignored when they are later posted to the eventlog. This could be "fixed" if anyone feels that was a poor design choice.
Finally, a `flux mini` `--dependency` option is …
> jobtap: support for job.dependency.* callbacks

- src/modules/kvs/cache.c
- src/modules/kvs/test/waitqueue.c
- src/modules/kvs/waitqueue.c
- src/modules/kvs/waitqueue.h
Per discussion in #3615, there is a small bottleneck in the KVS's disconnect path.  Using @grondo's throughput benchmark.
`>perf record -g --call-graph=dwarf -F 1000 src/cmd/flux start ./throughput_issue3615.sh 1024 1`
```
- 9.16% flux_reactor_run
- ev_run
- 8.85% ev_invoke_pending
- 5.57% handle_cb
- 4.40% dispatch_message (inlined)
- 4.38% call_handler
- 3.13% disconnect_request_cb
- 3.11% cache_wait_destroy_msg
- 2.08% wait_destroy_msg
1.71% fzlist_first
0.63% fzhashx_next
```
At ~3% of samplings, `disconnect_request_cb()`'s impact is not huge but not nothing.  It regularly showed up amongst many profiling benchmarks.  Here is the core of `cache_wait_destroy_msg()`.
```
FOREACH_ZHASHX (cache->zhx, key, entry) {
if (entry->waitlist_valid) {
if ((n = wait_destroy_msg …
```
> kvs: remove client disconnect bottleneck

- doc/man1/flux-content.rst
- doc/man1/flux-start.rst
- doc/test/spell.en.pws
- src/cmd/flux-start.c
- t/python/sideflux.py
- t/t0001-basic.t
This was peeled off of #3661.
The main user-visible change is to rename the `--scratchdir` option to `--rundir` to more accurately reflect its purpose, which is to set the broker rundir.  Then there's a bit of cleanup.
I dropped the `flux-start` changes in #3661 but didn't want to lose this cleanup.
> flux-start: rename --scratchdir to --rundir

- src/modules/kvs/kvstxn.c
while working on one more performance fix for #3615, fixed up these along the way.  The main fix I decided wasn't worthwhile, but these minor cleanups / changes should be fine.
The third commit does make a few assumptions about treeobj validity.  I think they are ok.
> kvs: misc cleanup

- src/shell/lua.d/openmpi.lua
- t/t3000-mpi-basic.t
Problem: shared memory segment naming for the "vader" BTL may collide
when running multiple jobs per node.
This is because the path is constructed from
/dev/shm/vader_segment.hostname.uid.jobid.rank
and the flux pmix plugin in openmpi always sets the jobid to 0
because FLUX_JOB_ID in f58 format is converted to a 32-bit integer
using strtol().  This is a bug in the plugin, but a proper fix may
be elusive given the integer size mismatch of IDs.
Work around the plugin bug by changing
OMPI_MCA_btl_vader_backing_directory
from default of /dev/shm to $FLUX_JOB_TMPDIR, which the shell tmpdir
plugin will have set to a job-unique directory.
Fixes #3649
This is based on top of #3661 (FLUX_JOB_TMPDIR), which should be merged first.
> openmpi: ensure that shmem segments for co-located jobs don't conflict

- src/shell/pmi/pmi.c
Problem: mvapich2 fails when PMI_process_mapping is not provided by the PMI KVS.
The shell pmi plugin defaults to "none" if the process (broker) mapping of the Flux instance cannot be determined.  This may happen, for example, if run by (slurm) srun `--mpi=none`.
The default of "none" was chosen because it prevented openmpi shared memory paths from colliding when there were multiple brokers/shells per node, as it seems openmpi assumes it owns the node if there is no clique. Now that the openmpi.lua shell plugin sets the shared memory path to be within FLUX_JOB_TMPDIR, this is no longer a problem.
Change the default mapping to "pershell" to appease mvapich2.
Fixes #3592.
This is based on top of #3672 which should be merged first.
> shell/pmi: always populate PMI_process_mapping to avoid mvapich2 MPI_Init invalid tag error

- src/common/libflux/module.c
- src/common/libflux/test/module.c
Problem: flux_modname(3) returns a dlerror() based error message
in any provided error callback when dlsym ("mod_name") fails, but
this extra error is probably unecessary in most, if not all,
situations. It also generates a lot of noise when flux_modfind(3)
recurses through directories with a lot of non-module .so files.
Simplify flux_modname(3) to return EINVAL when a "mod_name" symbol
is not found in the DSO. This will quiet unnecessary errors from
flux_modfind() and `flux module load` etc, effectively ignoring
DSOs without a `mod_name` symbol.
> libflux: flux_modfind: ignore DSOs with no mod_name symbol

- src/common/libpmi/simple_client.c
- src/common/libpmi/simple_server.c
- src/shell/pmi/pmi.c
- src/test/docker/focal/Dockerfile
- t/Makefile.am
- t/mpi/abort.c
- t/mpi/hello.c
- t/mpi/mpich_basic/GetOpt.c
- t/mpi/mpich_basic/GetOpt.h
- t/mpi/mpich_basic/adapt.c
- t/mpi/mpich_basic/netmpi.c
- t/mpi/mpich_basic/patterns.c
- t/mpi/mpich_basic/self.c
- t/mpi/mpich_basic/sendrecv.c
- t/mpi/mpich_basic/simple.c
- t/mpi/mpich_basic/srtest.c
- t/mpi/version.c
- t/t3000-mpi-basic.t
- t/t3003-mpi-abort.t
Our in-tree MPI testing is pretty minimal, basically just covering `MPI_Init()`, `MPI_Barrier()`, and `MPI_Finalize()`. This PR cleans up what we have, then adds `MPI_Abort()` coverage, and some basic comms tests pulled in from the MPICH source tree.
> testsuite: improve in-tree MPI testing

- doc/man7/flux-jobtap-plugins.rst
- src/common/libflux/plugin.c
- src/common/libflux/plugin.h
- src/common/libflux/test/plugin.c
- src/modules/job-manager/jobtap.c
- src/shell/log.c
- src/shell/test/plugstack.c
- t/job-manager/plugins/test.c
Fixes #3683
This was pretty straightforward, but @SteVwonder and @cmoussa1 should sign off since I think they are developing plugins external to flux-core.
This PR removes `FLUX_PLUGIN_ARG_UPDATE` and makes its behavior the default. The new flag `FLUX_PLUGIN_ARG_REPLACE` can be used to get the old default behavior. Therefore existing out-of-tree plugins may get compile-time errors if they use `FLUX_PLUGIN_ARG_UPDATE`
> libflux: plugin: make FLUX_PLUGIN_ARG_UPDATE the default for set/pack

- src/test/docker/centos8/Dockerfile
- t/t3003-mpi-abort.t
This builds the latest mvapich2 in the centos8 image for CI.  With this in, we'll be doing basic MPI testing on mpich, openmpi, and mvapich.
> testsuite: add mvapich2 to centos8 CI image

- doc/man1/flux-shell.rst
- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/doom.c
- t/Makefile.am
- t/t2614-job-shell-doom.t
I thought this was going to be a throw-away demo of a plugin that detects the first task exit and logs an exec eventlog entry, but after adding a timeout that throws a fatal job exception 30s after that, it seems like it might actually be sufficient to check off that feature for now.
So posting this as a WIP to get design feedback.
Possibly the throw-away name should be changed, as `doom` was chosen becuase it had morbid connotations and was short :-)
Is it OK for the shell to log the event directly to the eventlog or should it be notifying the `job-exec` service?
I sure am liking the ability we have to implement stuff like this as plugins.
> shell: add plugin to detect first task exit

- src/common/librlist/rhwloc.c
Problem: The hwloc 'gl' plugin emits warnings to stderr if
it cannot connect to the X server.
Avoid loading this plugin for now.
Fixes #3640
Also: add missing vi modeline.
> librlist: skip loading hwloc 'gl' plugin

- src/common/libflux/Makefile.am
- src/common/libflux/test/plugin.c
- src/test/generate-matrix.py
This PR fixes a unit test failure of `src/common/libflux/test_plugin.t` under `rpmbuild` on RHEL8.
The problem was only discovered under `rpmbuild` since rpm adds `'-Wl,-z,relro -Wl,-z,now'` to `LDFLAGS`, causing a test plugin to fail to `dlopen` due to missing symbols that were ignored during normal circumstances.
Addition of `libccan.la` to `test_ldflags` fixes the underlying problem. The test was also enhanced to better report this particular failure (rather than going on to segfault). Finally, the `LDFLAGS` mentioned above are added to the `centos8` build to catch problems like this a little earlier.
> libflux: test: fix segfault of test_plugin.t under rpmbuild

- doc/man1/flux-shell.rst
- src/shell/doom.c
- t/mpi/version.c
- t/t2614-job-shell-doom.t
- t/t3000-mpi-basic.t
- t/t3003-mpi-abort.t
This PR adds a shell option `exit-on-error` (to the `doom` plugin), which implements the behavior suggested in #3691.
It also allows the MPI abort tests to work on all the MPIs we are testing in CI, so that test is changed to eliminate the skip logic and set this new shell option.
> shell: add exit-on-error option

- src/cmd/flux-mini.py
- src/modules/job-manager/event.c
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- t/Makefile.am
- t/job-manager/plugins/jobtap_api.c
- t/t2212-job-manager-plugins.t
- t/t2270-job-dependencies.t
This PR is pulled from #3696, it felt better to split these more generic jobtap fixes and enhancements from the addition of the `dependency-after` jobtap plugin itself.
This PR includes the following:
* change `--dependency=scheme:value` in `flux-mini` to always encode `value` as a string per RFC 26
* fix reentrancy of jobtap->current_job
* capture job->end_event for all jobs, not just waitable
* add `flux_jobtap_get_job_result()`
* add `flux_jobtap_lookup_job()`
Along with corresponding testsuite updates.
> jobtap: fixes and api enhancements to support dependency plugins

- .github/workflows/main.yml
- src/test/generate-matrix.py
This PR includes a couple minor fixes for coverage testing in GH actions
* ensure `--with-flux-security` is used in the coverage builder
* switch to the official codecov github action instead of manual run of the bash uploader
Since this modifies GitHub workflow yaml, it will likely need to be manually merged.
> ci: minor coverage testing fixes

- doc/man1/flux-mini.rst
- doc/test/spell.en.pws
- src/cmd/flux-mini.py
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/dependency-after.c
- t/Makefile.am
- t/t2271-job-dependency-after.t
This is  WIP PR which adds support for simple `after{,any,ok,notok}` dependency schemes.
The implementation roughly mimics that of Slurm's `--dependency=after*:JOBID` feature. I'm not sure Slurm's interface is the greatest, but it didn't seem like a good idea to arbitrarily change it, at least at first.
This is posted as WIP before it is fully complete (mostly need testing) to ensure that the approach and design of the feature are on the right track (before spending a bunch of time testing). Especially @SteVwonder and @ryanday36 may want to give their approval of the interface.
One difference between this and Slurm's `--dependency=after*` feature is that, in the current implementation, jobs for which a dependency could never be satisfied, e.g. `afterok` is used and the requisite job …
> job-manager: support simple "after*" job dependencies

- src/common/liboptparse/optparse.c
- src/common/liboptparse/optparse.h
- src/common/liboptparse/test/optparse.c
As discussed in #3700, it is a bummer that `.has_arg = 2` (optional_argument) doesn't work well for `--verbose`. Then you can't use the idiom of `-vvv` for verbosity level 3.  But if you don't allow an argument, users that want to use long options have to use `--verbose --verbose --verbose`.
It is rare that optional arguments are useful with short options, so this PR makes optional args apply to long options only by default. The result is that `-vvv` works as does `--verbose=3`. A flag is added to restore the old behavior.
As part of this work it seemed useful to have `optparse_get_int()` return the number of times an option was used on the command line instead of a fatal error if it is called on an option with no argument, so that change was made here as well.
> optparse: make optional_argument apply to long options only

- doc/man1/flux-start.rst
- src/cmd/flux-start.c
- src/common/libsubprocess/remote.c
- src/modules/resource/resource.c
- t/Makefile.am
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t2310-resource-module.t
- t/t3301-system-latestart.t
This PR adds a `flux start --test-start-mode` option that can start the instance with only the leader broker running.  The `system` sharness test personality is modified so that this can be configured from a test script.  Finally, a test script is added that checks a few basics with a late joining broker such as:
* `flux exec` to down broker doesn't hang
* down broker is not drained
* down broker is still part of the resource set used to evaluate jobspec satisfiability
* once the broker is brought up, jobs run that were stuck before
A few minor nits were fixed while working on the test.
> testsuite: add tests for late joining broker

- src/broker/broker.c
- src/broker/broker.h
- src/broker/state_machine.c
- t/Makefile.am
- t/sharness.d/flux-sharness.sh
- t/t3302-system-offline.t
Problem: if a user submits a job on a login node, but the broker upstream of that node is not yet online, the request may hang leaving the user wondering what's going on.
Send an EAGAIN response to user requests (route count >= 2) received before the broker enters INIT state
```
$ flux mini run hostname
flux-mini: ERROR: [Errno 11] Upstream Flux broker is not yet online. Try again later.
```
A sharness test is added that re-creates this situation.
This is based on top of #3709 (this PR is just the last 3 commits).
> broker: send offline responses while broker is initializing

- .github/workflows/main.yml
Problem: The "fetch annotated tag" step of Github fails on master
because the command  `git fetch -f origin master:master` reports
```
fatal: Refusing to fetch into current branch refs/heads/master
of non-bare repository
```
which in turn causes the CI overall to fail.
Skip this step on the master branch.
This may fix "Missing base commit" in Codecov for PRs.
> github: fix ci builds on master

- .github/workflows/main.yml
Problem: The fix for builds on master didn't work, since GITHUB_BRANCH
was not set in the _environment_ of the annotated tags step (it was set
as an output).
Fall back to using github.ref, and skip the annotated tags checkout
when `github.ref == 'refs/heads/master'`.
Add a line of debugging in case this step starts to fail again in the
future.
This time I actually tested by pushing to the main branch of my own repo.
> github: fix the fix for ci builds on master

- src/cmd/builtin/python.c
- t/t0001-basic.t
Problem: when a virtualenv is created, it symlinks the system python
into the virtualenv directory.  The full path to this symlink is then
compiled into the `flux-python` subcommand as the first argument to
`execve`, but the first value in the argument list (`execve`'s second
arg), is just `python`.  This leads to an "escape" of the virtualenv
and a return to the system python environment:
```
PATH=/usr/bin/:$PATH strace -e process -f flux python -c 'import sys; print(sys.executable)'
execve("/usr/bin/flux", ["flux", "python", "-c", "import sys; print(sys.executable"...], 0x7fffd6b27020 /* 18 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7f849efccb00) = 0
execve("/ve_exaworks/bin/python3", ["python", "-c", "import sys; print(sys.executable"...], 0x20e73f0 /* 26 vars */) = 0 …
```
> flux-python: fix use of virtualenv python

- src/common/libjob/Makefile.am
- src/common/libjob/jobspec1.c
- src/common/libjob/jobspec1.h
- src/common/libjob/specutil.c
- src/common/libjob/specutil.h
- src/common/libjob/test/jobspec1.c
- src/common/libjob/test/specutil.c
This PR proposes an interface for constructing V1 jobspecs in C to satisfy some of @ardangelo 's needs for CTI support, specifically job launch (#3290). The interface provides helper functions for a subset of ``flux mini submit`` options, including:
- Setting the CWD
- Redirecting stdio to files
- Setting duration
- Setting environment variables
- Setting tasks, cores_per_task, gpus_per_task, and nodes
The other ``mini run`` options are not supported, at least not with helper functions. However, it's possible to set arbitrary attributes on the jobspec. For instance, to launch a job with a startup barrier like @ardangelo requested:
```C
json_t *trueval = json_true();
json_t *jobspec = flux_specutil_jobspecV1_from_command (...);
flux_specutil_jobspecV1_attr_set (jobspec, …
```
> libjob: add a library for constructing V1 jobspecs

- doc/man1/flux-mini.rst
- doc/test/spell.en.pws
- src/cmd/flux-mini.py
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/begin-time.c
- t/Makefile.am
- t/t2272-job-begin-time.t
This small WIP PR adds a minimum begin-time (or start-after time) via a new `begin-time` dependency scheme.
For this scheme, the `value` is interpreted as floating-point seconds since epoch after which the dependency shall be removed. The plugin uses the convenient flux "periodic" watcher, which watches system time instead of relative time, so it should "just work". If the time for which the dependency is set has already lapsed then the dependency is satisfied immediately.
The next step is to add a `flux-mini` option equivalent to Slurm's `--begin` option, (perhaps named `--begin-time` or `--start-after` to be more explicit), with support for parsing a slew of user friendly datetimes and datetime offsets, e.g.
* `--begin-time=+FSD`
* `--begin-time=Tuesday`
* `--begin-time=2021-06-15`
etc. …
> job-manager: add builtin begin-time dependency plugin

- src/common/libflux/plugin.c
- src/common/libflux/plugin.h
Problem: The topic string in `struct flux_plugin_handler` is not
const, which causes compilation errors when using static initializers
to define a table of handlers on compilers where static strings
are const (e.g. C++11).
Make the topic string const. The only reason it wasn't const was as a
convenience when destroying copied flux_plugin_handler structs. Just
cast the topic back to non-const when freeing the copy.
Fixes #3719
> libflux: make flux_plugin_handler topic member const

- t/issues/t3470-multithread-reactor-run.py
- t/t0004-event.t
- t/t1106-ssh-connector.t
Here are a couple of minor test improvements.   One commit fixes a test that occasionally fails for me (#3723) and the other speeds up two tests by loading the heartbeat module with a very fast heartrate, and not loading unnecessary modules.
> testsuite: fix intermittent test, speed up others

- src/bindings/python/flux/job/Jobspec.py
- src/modules/job-ingest/schemas/jobspec.jsonschema
- src/modules/job-ingest/schemas/jobspec_v1.jsonschema
- t/jobspec/invalid/dependencies_not_array.yaml
- t/jobspec/invalid/dependency_invalid.yaml
- t/jobspec/validate.py
- t/t2270-job-dependencies.t
- t/t2271-job-dependency-after.t
This PR adds missing functionality to the `Jobspec` class to validate that the `dependencies` system attribute, if it exists, conforms to RFC 14 and RFC 26.
> python: validate dependencies in Jobspec constructor

- src/modules/cron/cron.c
- src/modules/cron/task.c
- t/t2270-job-dependencies.t
For whatever reason I was getting reproducible failures in  `t0015-cron.t`:  `not ok 2 - flux-cron can set timeout on tasks` (a failure I've seen intermittently, but never reproducible). It turns out this was not due to a race in the test, but a race in the cron module itself. The timeout timer was being started when the cron task was started, not when it was actually running. If the timer fired before the task was running, then the attempt to kill it will fail.
There are other problems in the cron module, but we'll not tackle those now. This PR just fixes the race by starting the timer when the task is Running instead of Starting.
> cron: fix race in task timeouts

- t/sharness.d/flux-sharness.sh
- t/t0005-exec.t
- t/t2601-job-shell-standalone.t
- t/t2608-job-shell-log.t
- t/t2900-job-timelimits.t
I was getting several reproducible testsuite failures with a build directory configured with `--enable-code-coverage` while running `make -j 16 check` on a system with 4 cores.
This PR fixes all of the frequently failing tests in this environment.
> testsuite: fix several tests on slower systems

- src/modules/job-list/job_state.c
- src/modules/job-list/job_util.c
- src/modules/job-list/job_util.h
- src/modules/job-list/list.c
- src/modules/job-list/stats.h
- t/t2260-job-list.t
- t/t2261-job-list-update.t
- t/t2800-jobs-cmd.t
Peeled this off of #3688 since there's a medium big cleanup commit per @grondo comments in #3688.  I'll just let my commit message do the talking:
```
testsuite: modernize job list tests
Modernize job list tests in t2260-job-list.t, t2261-job-list-update.t,
and t2800-jobs-cmd.t by replacing `flux job submit` with `flux mini submit`
as much as possible.  This leads to the removal of generated jobspecs
in most cases.
As a consequence, the `--wait` option can be used instead of using
`flux job wait-event` to wait for a job to complete.
In addition make code consistent between these test files.  This includes
using the "fj_wait_event()" function and just generally using the
same test style throughout all three files.  In some cases, slightly
faster code using jobspecs was eliminated in favor …
```
> job-list: cleanup & testsuite modernization & consistency updates

- doc/man1/flux-start.rst
- src/broker/boot_config.c
- src/cmd/flux-start.c
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
This is a fix for the problem @dongahn encountered when building flux-core in a long directory, reported in #3736.
The fix is to use a directory in /tmp for the broker "rundir" in the system test personality, and put the sockets there instead of using the test trash directory, which is relative to the build tree.  To get the directory cleaned up properly, I added a new option to `flux-start`.  That seemed a bit easier than getting sharness to do it (at least, I was having a hard time getting that to work).  This approach is fine IMHO.
> testsuite: avoid long ipc:// paths in system test personality

- src/test/checks_run.sh
- src/test/docker/docker-run-checks.sh
- src/test/generate-matrix.py
This PR adds a `--workdir` option to `docker-run-checks.sh` to create a builddir other than `/usr/src`.
It turns out some testsuite (and perhaps other) bugs only appear in lengthy builddirs, so add a really long workdir to the bionic builder to find these issues before they are merged.
This PR will fail ci until #3736 is fixed.
> ci: use long path for builddir in test build

- t/valgrind/valgrind.supp
I found the valgrind suppressions added for #3640 no longer worked after a system update.
This PR generalizes library versions and paths using wildcards, and consolidates two suppressions that were identical except for one line.
Sorry, should have done better on the first attempt.
> testsuite: generalize valgrind suppressions

- src/common/libflux/Makefile.am
- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/test/message.c
Per discussion in #3617, this is part 1 to remove the `libczmq` dependency on `libflux-core`.  In this code we rework the `flux_msg_t` internals to store data in its own native data structure rather than using `zmsg_t`.
Just wanted to get some initial thoughts.
Should we consider this a mergable PR?  Or would we want to complete more of #3617 in one PR?  It is a lot of code changes.
The only places that `zmsg_t` and `zframe_t` remain are in `flux_msg_encode_size()`, `flux_msg_encode()`, `flux_msg_decode()`, `flux_msg_sendzsock()`, and `flux_msg_recvzsock()`.  We have some `msg_to_zmsg()` and `zmsg_to_msg()` internal functions to handle the transition for the time being.  These functions will eventually be migrated out of `libflux-core`.  To `librouter`?  Or a helper lib?  This is perhaps …
> libflux: store fully decoded message in flux_msg_t

- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- src/modules/job-manager/plugins/alloc-bypass.c
- t/Makefile.am
- t/job-manager/plugins/jobtap_api.c
- t/t2212-job-manager-plugins.t
- t/t2273-job-alloc-bypass.t
This is a proof-of-concept implementation of the idea discussed in #3737. This will probably need a bit more work before it could be a merge candidate, but I thought it might be useful to push here for now in order to continue the discussion around a concrete implementation.
The current approach is pretty straightforward:
* Add a new `alloc_bypass` flag to the job manager's `struct job`. If this flag is set then alloc/free requests are not sent to the loaded scheduler
* Allow a jobtap plugin to return an `R` in the `job.state.sched` callback, which, if the job was submitted by the instance owner, enables "alloc bypass" mode, writes the `R` to the appropriate KVS path, and finally generates an `alloc` event directly
* Add an `alloc-bypass.so` loadable jobtap plugin which returns an `R` in …
> allow jobs to bypass scheduler with alloc-bypass jobtap plugin

- src/common/libflux/message.c
- src/common/libflux/test/message.c
Per discussion in #3701.  With the removal of `zmsg` internally within the `flux_msg_t` data structure, we are no longer beholden to follow the output format defined by `zframe_fprint()`.  The hex output can be somewhat confusing and not the most helpful for debugging at times.  Also, we can get rid of a call to `msg_proto_setup()`, which we really don't need in `flux_msg_copy()` anymore.
I had no strong feelings on what to update the output to, so I just picked this:
```
>[routes] |id1|
>[topic] foo.bar
>[payload] size=8 ...
>[proto header] type=request flags=0xB userid=4294967295 rolemask=0x0
>[proto aux] nodeid=4294967295 matchtag=0
```
We could remove the `prefix` notation (i.e. `>` vs `<` for request/reply), but I like it and left it in there.  I don't know if using the brackets …
> libflux: make flux_msg_fprint() output clearer

- src/common/libflux/message.c
Problem: flux_msg_clear_route() did not reset routes_len back to
zero after all routes were destroyed.
Solution: Reset the length back to zero before returning to the user.
> libflux/message: reset routes length on clear

- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job.h
- src/modules/job-manager/submit.c
This PR was mainly prep work for a prototype solution for #3746, however, it may be considered good cleanup and minor improvements. Notably, this PR:
- ensures spurious "free" event (e.g. as posted by a jobtap plugin) is caught as an error
- adds a flag to ensure a "depend" event can't be posted more than once
- refactors `event_job_post*` functions so that `submit_post_event()` can use this shared code
- removes need for one-off timestamp capture in `event_job_post_pack()`
> job-manager: minor cleanup and improvements for event handling

- src/common/libflux/handle.h
- src/common/libjob/job.c
- src/common/librouter/test/usock.c
- src/common/librouter/test/usock_echo.c
- src/common/librouter/usock.c
- src/common/librouter/usock.h
- src/common/libtestutil/util.h
- src/connectors/local/local.c
- t/Makefile.am
- t/t1108-local-opt.t
- t/util/handle.c
This is proposed solution for #3760, in which the `t3302-system-offline.t` test fails when flux is built `--with-flux-security` and the munge daemon is not running.  Use of the `security.owner` broker attribute is replaced with a connector method based on SO_PEERCRED.    The existing `flux_opt_get()` interface is leveraged.
I tested this using @grondo's method from the issue to reproduce the failure and it works.
As a bonus, the first job submitted no longer has to make the extra synchronous RPC to the broker.
> libjob: improve method for determining instance owner

- src/common/libflux/handle.c
- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/test/message.c
- t/t0002-request.t
Problem: message traces obtained by setting `FLUX_HANDLE_TRACE=1` do not contain timestamps, thus are not as helpful as they could be for performance investigations.
This adds timestamps that look like this (they are in seconds):
```
$ FLUX_HANDLE_TRACE=1 flux getattr size
--------------------------------------
> 0.00000
> attr.get
> flags=topic,payload,route userid=unknown rolemask=none nodeid=any matchtag=1
> {"name":"size"}
--------------------------------------
< 0.00024
< attr.get
< flags=topic,payload,route userid=5588 rolemask=owner errnum=0 matchtag=1
< {"value":"1","flags":1}
1
```
So this RPC took 240 microseconds.
> libflux: add time stamp to message trace

- src/bindings/python/flux/job/submit.py
- src/cmd/flux-job.c
- src/cmd/flux-mini.py
- src/common/libjob/job.h
- src/modules/job-ingest/job-ingest.c
- t/t2100-job-ingest.t
- t/t2700-mini-cmd.t
This adds a FLUX_JOB_NOVALIDATE flag that can be passed by the instance owner to the `job-ingest` module to bypass jobspec validation on a per-job basis, as opposed to reloading the `job-ingest` module with the `disable-validator` module option and disabling the validator for all jobs.
I originally added this as part of the `flux job exec` work to improve turnaround time for short lived jobs.  I broke it out for separate consideration here, since it's not really all _that_ helpful for the case it was written for, as the cost of validation is low once the python co-process is up and running.
Can we imagine this being useful for other things?  I'm fine if we prefer to dump it.
> add flag to bypass jobspec validation

- src/bindings/lua/zmsg-lua.h
- src/cmd/builtin/proxy.c
- src/common/libflux/ev_flux.c
- src/modules/job-manager/plugins/dependency-after.c
Problem: czmq.h and/or zmq.h was included in a number of locations
that was unnecessary.
Solution: Remove the unnecessary includes.  In some cases, replace with
include of czmq_containers.h or other appropriate headers that czmq/zmq
happened to include.
Fixes #3624
> Globally drop unnecessary 0MQ includes

- src/bindings/python/flux/job/validator/plugins/jobspec.py
- src/cmd/flux-job-validator.py
- t/t2100-job-ingest.t
- t/t2110-job-ingest-validator.t
This PR addresses issue #3772 -- the `jobspec` `flux job-validator` plugin was supposed to be validating V1 jobspec only by default (and with `--require-version=1`), but unfortunately was completely ignoring this option.
This PR fixes the bug in the plugin, and also adds support for `--require-version=any` for disabling the jobspec version check (which is currently the default)
Some tests needed to updated now that V1 is the default requirement.
> python: fix version requirement in jobspec validator plugin

- src/common/libccan/Makefile.am
- src/common/libccan/ccan/base64/LICENSE
- src/common/libccan/ccan/base64/_info
- src/common/libccan/ccan/base64/base64.c
- src/common/libccan/ccan/base64/base64.h
- src/common/libccan/ccan/base64/test/moretap.h
- src/common/libccan/ccan/base64/test/run.c
- src/common/libeventlog/eventlog.c
- src/common/libioencode/ioencode.c
- src/common/libioencode/test/ioencode.c
- t/Makefile.am
- t/issues/t3775-binary-io.sh
As described in #3775, if a job input or output stream contains data that cannot be encoded in utf8, `ioencode()` and `iodecode()` currently fail.
Along with a minor adjustment in RFC 24 (flux-framework/rfc#296), this PR falls back to encoding I/O eventlog data events with base64 if `json_pack()` fails on the original data. The new encoding is added to the context object so that the decoder knows that the data is in base64.
Instead of using the libsodium base64 routines, a base64 implementation is added from CCAN, since we want to get away from using libsodium at this point. Other base64 users in the codebase were not updated, that is left for a future exercise.
This is a WIP for now since it uses an as-yet unapproved change to RFC 24.
Fixes #3775
> Allow io encode/decode of binary data

- README.md
- configure.ac
- src/broker/Makefile.am
- src/broker/publisher.c
- src/common/Makefile.am
- src/common/libflux/Makefile.am
- src/common/libflux/event.c
- src/common/libioencode/ioencode.c
- src/common/libjob/Makefile.am
- src/common/libjob/sign_none.c
- src/common/libjob/test/sign_none.c
- src/common/libkvs/Makefile.am
- src/common/libkvs/treeobj.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libutil/macros.h
- src/modules/job-archive/job-archive.c
- src/modules/kvs/Makefile.am
- src/modules/kvs/kvstxn.c
- t/lua/t0003-events.t
Per #3787 and some other discussions, replace base64 use in flux-core with the ccan library over the libsodium library.
As a result, we can eliminate the linking of libsodium throughout flux-core.
Note, that I left `libsodium` in the DockerFiles for the time being, as its still needed for `flux-security`.  I think this is the right thing to do?
> Use CCAN base64 library over libsodium base64 library

- src/common/libflux/message.c
- t/t3100-flux-in-flux.t
Per discussion in #3617, this PR converts `libflux/message` to use `struct iovec` like arrays for sending/receiving messages instead of using `zmsg_t` and `zframe_t`.  This serves several purposes:
A) it continues the #3617 path to reduce dependence on `czmq`.  With this change, czmq dependence is now isolated to just `flux_msg_sendzsock()` and `flux_msg_recvzsock()`.  This will make it easy to migrate those functions over to `librouter`.
I have some experimental branches that in fact moved those functions over to `librouter` and the `message_private.h` file that is eventually created is quite small.  I have elected to not include those changes here and do that in another PR in the future.
B) Using `zmsg_t` and `zframe_t` made sense when `flux_msg_t` internally stored data via `zmsg_t`. …
> libflux: use iovec-like array over zmsg

- t/valgrind/valgrind.supp
Problem: valgrind test reports a new invalid read error
on system with OpenCL installed.
Add a valgrind suppression.
Fixes #3793
> testsuite: add valgrind suppression for opencl

- src/common/libkvs/kvs_txn_compact.c
I noticed this will doing some looking at issue #1804 awhile back.  Forgot that I had this sitting on a branch.  It's just a simple / dumb fix.
```
Problem: The txn_compact() function would attempt to compact
transactions if there are > 0 operations.  But it is impossible to
compact just 1 operation, you need atleast 2 operations to conceivably
compact.
Solution: Check for > 1 instead of > 0 operations.
```
> libkvs: compact only if ops len > 1

- t/valgrind/valgrind.supp
Problem: a new valgrind test failure was encountered on aarch64,
Ubuntu 20.04.2 LTS and also the official Jetson Ubuntu 18.04:
==1705645== Syscall param epoll_ctl(event) points to uninitialised byte(s)
==1705645==    at 0x4BDFE38: epoll_ctl (syscall-template.S:78)
==1705645==    by 0x48B37EF: epoll_modify (ev_epoll.c:96)
==1705645==    by 0x48B4F57: fd_reify (ev.c:2166)
==1705645==    by 0x48B4F57: ev_run (ev.c:3677)
==1705645==    by 0x48B4F57: ev_run (ev.c:3623)
==1705645==    by 0x48824FF: flux_reactor_run (reactor.c:126)
==1705645==    by 0x1113BF: main (broker.c:449)
==1705645==  Address 0x1ffefff22c is on thread 1's stack
==1705645==  in frame #1, created by epoll_modify (ev_epoll.c:72)
Since this is apparently internal to libev, add a suppression.
Fixes #3808
> testsuite: add valgrind suppression for libev on aarch64

- src/common/librlist/rnode.c
- src/common/librlist/test/rnode.c
- t/t0026-flux-R.t
This fixes the problem described in #3813.
The problem was an embarrassing error in `rnode_cmp()`, which compares two resources nodes to determine if they have identical child resources. The function iterates each child resource type in the first node and compares idsets with the same resource type in the second node. However, if the 2nd node has extra resources, like gpus, then the node is considered equal and is collapsed into the first node and the gpus are lost.
The fix is to first compare the number of resource types and ensure they are equal before continuing on to further comparison.
> rlist: fix erroneous collapse of nodes with different resource children when emitting R

- src/broker/doc/README.md
- src/broker/doc/resiliency.md
- src/broker/overlay.c
- src/broker/overlay.h
- src/cmd/Makefile.am
- src/cmd/builtin/overlay.c
- src/common/libhostlist/hostlist.h
- t/Makefile.am
- t/t3300-system-basic.t
- t/t3301-system-latestart.t
- t/t3303-system-healthcheck.t
This PR adds a prototype `flux healthcheck` tool, and modifies the broker overlay code to track "subtree health".  The design is documented in a markdown document added in this PR so I won't go into detail here.
The tool is then exercised by the "t33xx-system-*.t" sharness scripts.
This is what it looks like on a healthy system:
```
ƒ(s=16,d=0,builddir) $ flux healthcheck
full
ƒ(s=16,d=0,builddir) $ flux healthcheck -vvv --times --pretty
0: full  (0.275 ms)
└1: full  (0.415 ms)
└3: full  (0.517 ms)
└7: full  (0.590 ms)
└15: full  (0.691 ms)
└8: full  (0.594 ms)
└4: full  (0.447 ms)
└9: full  (0.633 ms)
└10: full  (0.569 ms)
└2: full  (0.331 ms)
└5: full  (0.519 ms)
└11: full  (0.570 ms)
└12: full  (0.564 ms)
└6: full  (0.498 ms)
└13: full  (0.548 ms)
└14: full  (0.515 ms) …
```
> system instance: add flux overlay status command

- doc/man5/flux-config-bootstrap.rst
- doc/test/spell.en.pws
- src/broker/boot_config.c
- src/broker/boot_config.h
- src/broker/boot_pmi.c
- src/broker/broker.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/boot_config.c
Problem: as noted in #3824, the current default of enabling ipv6 for all zeromq sockets prevents the flux system instance from binding to an interface that only has ipv4 addresses.  We just hit this on fluke, and in fact this bug is a blocker for getting the system instance updated on fluke.
This PR disables ipv6 for config bootstrap only, and adds a config setting for overriding the default, should that be necessary:
```toml  
[bootstrap]
enable_ipv6 = true
``` 
Fixes #3824
> add bootstrap.ipv6_enable = true config option

- src/broker/content-cache.c
- src/common/libflux/Makefile.am
- src/common/libflux/flux.h
- src/common/libflux/fripp.c
- src/common/libflux/fripp.h
- src/common/libflux/stats.c
- src/common/libflux/stats.h
- t/Makefile.am
- t/scripts/stats-listen.py
- t/stats/stats-basic.c
- t/stats/stats-immediate.c
- t/t1200-stats-basic.t
This adds a simple metric collection & sender api to `libflux` as suggested in issue #3517. The public api in `src/common/libflux/stats.h` defines the functions for storing metrics and changing the internal flush interval (which is `1s` by default). There are three types of supported metrics: `counters`, `gauges`, and `timers`. `Counters` send integers values which are aggregated in Brubeck over its flush interval. `Gauges` take an arbitrary integer value and maintain that value until next set, like a snapshot at a certain point. `Timers` take an amount of time in miliseconds. 
Right now there are no CI tests (something I need some suggestions on), but to test locally first set up Brubeck and Graphite which I have some instructions on setting up in my …
> add stats api for internal metric collection

- .github/workflows/main.yml
Problem: Over time, the addition of tests to the testsuite has
increased the minimum runtime of the GitHub workflow builds. The
coverage build is especially impacted, presumably due to extra IO
induced by gcov output, and is now often timing out.
Increase the build timeout to 40 minutes to avoid spurious CI timeouts
in the coverage builder.
This will need to be merged manually since it touches the workflow
config under `.github`.
> github: increase ci timeout to 40 minutes

- src/broker/overlay.c
- src/common/librouter/Makefile.am
- src/common/librouter/msg_hash.c
- src/common/librouter/msg_hash.h
- src/common/librouter/rpc_track.c
- src/common/librouter/rpc_track.h
- src/common/librouter/test/msg_hash.c
- src/common/librouter/test/rpc_track.c
- t/Makefile.am
- t/t3300-system-basic.t
- t/t3303-system-healthcheck.t
- t/t3304-system-rpctrack.t
This creates a generic RPC tracking class in librouter, and uses it on TBON children in the broker, as described briefly in #3800 and in more detail [here](https://github.com/flux-framework/flux-core/blob/master/src/broker/doc/resiliency.md).
Each broker tracks the state of all RPC requests passing through it to its children.  In a multi-hop RPC, each hop in that direction creates state.  If a broker goes down, only that broker's TBON parent generates the error response, which then causes the state in other brokers to be freed like it would have been had the intended destination responded.
The overhead is:
- a zhashx entry for each sent request, containnig a reference on sent `flux_msg_t`, valid while the RPC is in flight
- zhashx lookup for each received response (key=uuid+matchtag)
- …
> broker: fail pending RPCs when TBON child goes down

- src/bindings/python/flux/job/executor.py
- t/python/t0023-executor.py
Problem: when a nonexistent jobid is passed to FluxExecutor.attach(), the executor should catch a `FileNotFoundException` and error out the future. However, along that line of control flow a variable is undefined (`UnboundLocalError`), causing the executor to crash. Fix: a single-line change to define the variable. Add tests to catch the problem.
For an example of the bug see https://github.com/flux-framework/flux-core/pull/3835#issuecomment-904735399
> python: fix bug in FluxExecutor.attach method

- configure.ac
- src/broker/broker.c
- src/broker/module.c
- src/broker/overlay.c
- src/broker/state_machine.c
- src/cmd/builtin/overlay.c
- src/common/libflux/handle.c
- src/common/libflux/tagpool.c
- src/common/librouter/rpc_track.c
- src/common/librouter/test/rpc_track.c
- src/connectors/shmem/shmem.c
- t/Makefile.am
- t/t3303-system-healthcheck.t
- t/t3305-system-disconnect.t
This implements broker RPC tracking in the upstream direction, analogous to the downstream tracking added in #3822.  The `rpc_track` class added in that PR was reused. 
With this component completed, we now have the machinery in place to avoid RPC hangs resulting from lost broker connections.  The next piece is to activate the machinery when we detect an uncommunicative broker or other unrecoverable broker failure mode.
A `flux overlay disconnect RANK` command was added that allows a sys admin to force disconnect a broker,  as proposed in #3805.   Tests for this PR are built upon this tool.
Code was added as part of `flux overlay disconnect` to determine the parent of the target rank by querying the topology from rank 0 and searching it.  To make this easier to test, a subcommand was …
> broker: fail pending RPCs when TBON parent goes down

- src/broker/overlay.c
- src/broker/test/overlay.c
- src/cmd/builtin/version.c
- src/common/libzmqutil/Makefile.am
- src/common/libzmqutil/monitor.c
- src/common/libzmqutil/monitor.h
- src/common/libzmqutil/test/monitor.c
- src/common/libzmqutil/zap.c
0MQ does things like connect and authentication in its I/O thread without exposing it in its API, which is convenient, though sometimes when not working, you wish you knew what was going on in there. 
0MQ does offer [zmq_socket_monitor(3)](http://api.zeromq.org/master:zmq-socket-monitor) which we've employed in the past for counting peers, but it has a bad bug in the version of libzmq that is still packaged on centos7, and has a few other caveats that you have to be very careful with, such as the ability to deadlock the 0MQ I/O thread if the monitor socket is not properly managed.  So we stopped using it.
This PR brings back socket monitoring for the broker overlay network, but only for logging purposes, and only for modern 0MQ versions.  The sorts of messages that might appear can be …
> broker: improve logging of 0MQ socket events

- src/broker/overlay.c
- t/Makefile.am
- t/python/t0010-job.py
- t/t3300-system-basic.t
- t/t3301-system-latestart.t
- t/t3302-system-offline.t
- t/t3303-system-healthcheck.t
- t/t3304-system-rpctrack-down.t
- t/t3305-system-disconnect.t
- t/t3305-system-rpctrack-up.t
- t/t3306-system-routercrash.t
- t/t3307-system-leafcrash.t
This adds code to handle the case described in #3608, where a broker might be forever cut off from the flux instance if its TBON parent restarts without informing it (for example a kill -9 or a node crash).  With this change, the parent detects the child trying to communicate without first executing the hello handshake to register its uuid, and sends a KEEPALIVE_DISCONNECT message to ensure it stops.  Systemd would then be able to restart it.
Also fixed a problem with the crashed broker properly rejoining _its_ parent, discovered during testing.
There is also some minor overlay cleanup here.
This is built on top of pr #3843.  Once that is merged, this can be rebased.
> broker: ensure subtree restart upon loss of router node

- src/test/docker/docker-run-checks.sh
This PR updates the default flux-security version in docker images created by `docker-run-checks.sh` to the latest: v0.5.0. This means all published `fluxrm/flux-core` images will include the newer flux-security.
> update flux-security version to v0.5.0 in docker images

- NEWS.md
First draft of release notes for flux-core v0.29.0.
Feel free to directly push any changes here. I've added #3845 to the NEWS file already assuming it will be merged before we tag.
> NEWS.md: add release notes for flux-core v0.29.0

- src/common/libflux/rpc.c
- src/common/libflux/test/rpc.c
- src/common/libsubprocess/remote.c
- t/python/t0012-futures.py
This PR fixes the issue described in #3852, a problem first described in flux-framework/FluxRM.jl#17.
In general, the problem is that RPCs do not drop their active references on an event loop until the future is _destroyed_, instead of dropping them when future is _fulfilled_. This means an RPC future can't be used outside of an event loop since `flux_reactor_run(3)` will not return until all RPC futures are destroyed.
This PR just stops the internal RPC msg_handler once the final expected response is received. In the case of a normal RPC, this is when the future is first fulfilled, but for streaming RPCs this is at the first error.
A couple spots were missing the FLUX_RPC_STREAMING flag (as evidenced by hangs). These were fixed here.
The libsubprocess protocol still doesn't send an error …
> libflux: deactivate RPC message handlers after final response

- .github/workflows/asan.yml
- .mergify.yml
- src/common/libccan/ccan/base64/base64.c
- src/common/libccan/ccan/base64/base64.h
- src/common/librouter/test/rpc_track.c
- src/test/docker/README.md
- src/test/docker/fedora34/Dockerfile
- src/test/docker/fedora34/config.site
- src/test/generate-matrix.py
- t/mpi/mpich_basic/netmpi.c
This PR adds Fedora Core 34 to our CI. The compiler in this version, gcc 11.2, found some new errors, so those are fixed.
The address sanitizer build is also switched to fedora 34 on the assumption that the newer GCC will have better sanitizers.
Eventually we'll switch away from fedora 33, but for now the fedora33 ci build needs to stay since dependent projects (e.g. flux-sched) still need the fedora33 docker image produced as a result of the ci build.
> ci: add fedora 34 build and fix compiler errors from gcc 11.2

- NEWS.md
I just noticed that the release notes for flux-core v0.29.0 reference v0.28.0. Sorry!
This PR fixes that blunder.
> NEWS.md: Fix typo for v0.29.0

- src/shell/Makefile.am
- src/shell/lua.d/00-lib.lua
- src/shell/lua.d/spectrum.lua
- t/t3001-mpi-personalities.t
As described in #3855, it would be helpful if there was a way to abstract commonly useful functionality for the MPI personality plugins in the shell (and other Lua-plugins). This PR creates and installs a `00-lib.lua` "plugin", and collects some new and existing common functions that will be available in all other shell Lua plugins (assuming that `00-lib.lua` is sourced before other lua.d files)
A new `shell.getopt_with_version (name)` function is introduced, which automatically splits a top-level shell option `name` into a `value` and `version` parts, separated by `@` (assuming that is the separator of choice).
E.g. if `-o mpi=spectrum@10.4` then
```lua
local mpi, version = shell.getopt_with_version ("mpi")
```
would return `"spectrum", "10.4"`. The `spectrum.lua` plugin could then take …
> shell: add library of Lua convenience functions for use in plugins 

- src/common/libflux/future.c
`<=` should be `<`, otherwise it'd be the `==` case listed below.
> libflux/future: fix comment typo

- src/shell/lua.d/openmpi.lua
- t/t3001-mpi-personalities.t
Problem: upstream openmpi nixed our flux plugins in the v5 series, as mentioned in #3586, but our `openmpi.lua` plugin sets the environment to require those plugins, unconditionally.  This prevents flux from bootstrapping openmpi-v5, even with a pmix shell plugin.
Use the new mpi personality version support to change the logic if `-ompi=openmpi@5` is supplied by the user.  Otherwise, behavior does not change.
> mpi: add -ompi=openmpi@5 support

- src/cmd/Makefile.am
- src/cmd/flux-job-exec-override.py
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/testexec.c
- t/t2400-job-exec-test.t
Testing of future work that uses internal job events of the `RUN` state for synchronization may require better control of how the `start` and `finish` events are emitted for test jobs. 
This PR extends the job-exec module's `testexec` implementation to add an `override` option. When this option is enabled via `attributes.system.exec.test.override=1` in jobspec, the module does not immediately issue the `start` response to the job manager, but instead waits for a manual request from the job owner via a new `job-exec.override` service. If the job does not have a `duration` or `attributes.system.exec.test.run_duration` set (or they are `0.`) then the job will continue to "run" until a manual `finish` event is requested, or a job exception raised.
A new plumbing command `flux …
> job-exec: enable manual override option for mock execution jobs

- src/shell/initrc.lua
- t/t2603-job-shell-initrc.t
This is an attempt at a simple solution for #3866.
The default `initrc.lua` for the job shell loads all `*.lua` rc scripts from `${rcpath}/lua.d/*`, where `rcpath` is the directory in which `initrc.lua` was found. On a normal system, the default shell initialization can be influenced by dropping another Lua rc script in this directory. (This is how the mpi 'personality' plugins work).
However, in systems like spack, where every package has its own root, add-on packages like mpibind can't just drop a new file into the shell `rcpath`, since that path is in the flux-core package's root. This PR adds support for a new environment variable `FLUX_SHELL_RC_PATH` which, when set in a job's environment, will extend the search path for `*.lua` files to automatically load at runtime.
Therefore, in …
> allow default shell rc path to be extended via FLUX_SHELL_RC_PATH

- src/test/docker/centos8/Dockerfile
- src/test/docker/docker-run-checks.sh
A couple of small docker/test updates here.
In flux-pmix we needed a `--build-arg` option to `docker-run-checks.sh`, so pull that back up here.
For systemd-based job shell execution @chu11 needs `systemd-devel` in the centos8 image, so add that.
I've already pushed the new `fluxrm/testenv:centos8` image to docker hub.
> docker: add --build-arg to docker-run-checks, systemd-devel to centos8

- doc/man7/flux-jobtap-plugins.rst
- src/modules/job-manager/event.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap-internal.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- src/modules/job-manager/restart.c
- src/modules/job-manager/test/job.c
- t/Makefile.am
- t/job-manager/plugins/args.c
- t/job-manager/plugins/subscribe.c
- t/t2212-job-manager-plugins.t
This work was done in anticipation of future requirements for some jobtap plugins to get callbacks on job events and not just job state transitions (and priority/urgency events). This could probably be implemented by separately watching the job eventlog, but this has high development cost and is wasteful, since all events go through the job manager anyway.
Issuing a callback for all loaded plugins on every job event would probably be high cost, therefore this approach requires plugins that want these extra  callbacks to "subscribe" to events for the job. This means that in the common case, this change should add no overhead, and only plugins which are interested in all job events will have `job.event.*` callbacks called.
Unfortunately the resulting code was a little more complicated than …
> allow jobtap plugins to subscribe to job events

- doc/man3/flux_shell_get_info.rst
- src/shell/shell.c
- src/shell/shell.h
- t/shell/initrc/tests/0001-shell-info.lua
As described in #3820, a couple shell plugins have needed to gather the list of taskids assigned to shell ranks in a job. Currently, plugins can assume "block" allocation of task ids and recreate the mapping themselves, but not only is this cumbersome, it will be wrong if the shell ever chooses a different mapping for task ids across shell ranks.
This PR adds a new member of the `flux_shell_get_rank_info(3)` payload - a `taskids` entry which is an RFC 22 idset string of task ids the shell has assigned to the target shell rank.
> shell: add taskids idset to flux_shell_get_rank_info(3)

- src/common/libccan/ccan/base64/base64.c
- t/t0001-basic.t
This PR fixes a couple issues that popped up when building on a ppc64le TOSS system with clang 11.0.x.
The first issue is a build problem discussed in #3874.
The second issue isn't ppc64le/clang specific, but fixes a test error when the Python interpreter used by `flux python` is a symlink.
> Fix a couple build and test issues found on ppc64le with clang 6.0+

- src/modules/resource/inventory.c
- t/t3301-system-latestart.t
Problem: if R is missing augmented graph information, fluxion
might block forever on resource.get-xml request for resource
discovery results.
Resource discovery is the natural fallback if resources not
not configured.  But fluxion cannot tell the difference between
R that lacks configured JGF augmentation because it was misconfigured,
and R allocated by a scheduler that doesn't support it.
If discovered hwloc results are not immediately available at the time
of the request, fail the request if the broker.quorum attribute is
less than the full instance, as this indicates that the instance
should begin operation with some ranks offline, and R should contain
all needed information.
Tack a test onto t3301-system-latestart.t
Fixes #3884.
> resource: fail get-xml request on quorum subset

- t/test-terminal.perl
Problem: The test-terminal.perl script fails with
`Can't locate object method "follower" via package "IO::Pty"`.
As noted in chriscool/sharness#105, this is because IO::Pty only has a
slave method and not a follower method.
Solution: Revert the changes in 5f2fb21 until IO::Pty changes their
terminology.
Closes #3887
> t: fix incorrect method call in test-terminal.perl

- src/modules/job-manager/plugins/alloc-bypass.c
- t/python/t1000-service-add-remove.py
Some small mistakes were found in the `alloc-bypass` plugin during a review of flux-framework/flux-k8s#14.
Since early on it may be common practice to start from one of the existing jobtap plugins by copying an example, we should fix the issues discovered so they aren't copied again. This work was done quickly so an extra set of eyes will be valued.
Additionally during that review it was discovered that the Python tests have no coverage of `flux_respond_error()` (which would also be a good example usage for someone to copy), so that is tacked on here even though it is not relevant.
> job-manager: small fixes for the alloc-bypass plugin

- src/broker/liblist.c
Problem: Some installations of flux-core do not have ldconfig(1)
present in PATH, and this results in a senseless warning
sh: ldconfig: command not found
Adjust the shell command used with popen(3) to first check for ldconfig
in PATH before trying to run it, thus silently ignoring the missing
command.
> broker: ignore missing ldconfig when searching for libpmi.so

- doc/man7/flux-jobtap-plugins.rst
- src/modules/job-exec/job-exec.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- src/shell/evlog.c
- t/Makefile.am
- t/job-manager/plugins/jobtap_api.c
- t/job-manager/plugins/perilog-test.c
- t/t2212-job-manager-plugins.t
This PR adds support for `prolog-*` and `epilog-*` events for jobs and the corresponding jobtap interface functions `flux_jobtap_prolog_start()`, `flux_jobtap_prolog_finish()`, `flux_jobtap_epilog_start()` and `flux_jobtap_epilog_finish()`.
If a plugin needs to perform some asynchronous actions after a job has been allocated resources, but before the `start` request is sent to the execution system, then it can use the `prolog` events, and if a plugin needs to perform similar actions after all job shells have finished, but before resources are returned to the scheduler, then it can use the `epilog` events.
@jameshcorbett, I think you had a use case for the `prolog-start`, `prolog-finish` events. If so, can you give this PR a quick review to ensure it meets your requirements?
> job-manager: add prolog/epilog support for jobtap plugins

- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- t/t0001-basic.t
Problem: if `local-uri` or TBON unix domain sockets exceed the max allowed path length, the instance fails with obscure errors.  This may occur if
- TMPDIR is set to a long path name
- rundir is set on the command line with -Srundir=path
- local-uri is set on the command line with -Slocal-uri=uri
Add some checks to catch this early and print reasonable errors.  Also update flux-broker-attributes(7) to discourage the use of `rundir` and warn about the AF_UNIX path limit, which is quite small and may surprise some.
> broker: fail gracefully when rundir or local-uri exceed AF_UNIX path limits

- t/issues/t3920-running-underflow.sh
Problem: The t3920-running-underflow test failed under non
bourne shell shells.
Solution: Set SHELL to /bin/sh in test to ensure proper
execution.
Fixes #3936
> testsuite: fix non-bourne shell test failure

- etc/Makefile.am
- etc/flux.service.in
- etc/rc1.d/02-cron
- t/Makefile.am
- t/t3201-crontabs.t
cron: load crontabs from directory
Problem: sys admins need a way to set up cron jobs for the system instance only, that persist across an instance reboot.
Set a `cron.directory`  attribute in the systemd unit file.
In rc1, on rank 0 only, if the cron.directory attribute is set, iterate over files in the directory, loading each into the cron service with `flux cron tab <$file`.
> cron: load crontabs from directory if cron.directory attribute is set

- doc/man1/flux-exec.rst
- src/cmd/Makefile.am
- src/cmd/flux-exec.c
- src/cmd/flux-perilog-run.py
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/perilog.c
- t/Makefile.am
- t/sharness.d/flux-sharness.sh
- t/t2274-manager-perilog.t
This PR is a WIP implementation of a jobtap plugin and a new command which together support running traditional job prolog/epilogs when the plugin is loaded and configured.
Tests still need to be added, but before that I wanted to ensure the general approach is acceptable.
This PR adds a new `perilog.so` plugin (for lack of a better name) which, when loaded and configured, supports running a configurable command on rank 0 as prolog and/or epilog actions. 
The PR also adds a new helper script `flux-perilog-run.py` which when configured as the prolog or epilog command, supports running a set of scripts from a directory (default `/etc/flux/system/prolog.d` and `/etc/flux/system/epilog.d/`) and optionally executing a command across all ranks of the starting/completing job. This last feature …
> support job prolog/epilog commands

- etc/rc1
- etc/rc3
- t/issues/t3503-nofiles-limit.sh
Problem: although job-archive does nothing if not configured, it is not loaded in rc1/rc3, so a custom rc script is required if iti s needed in production.
Just load it in rc1/rc3 and it can be enabled with config.
(flux-accounting depends on it)
Fixes #3940
> rc: load job-archive

- doc/man1/flux-kvs.rst
- doc/man3/flux_kvs_namespace_create.rst
- src/cmd/flux-kvs.c
- src/common/libkvs/kvs.c
- src/common/libkvs/kvs.h
- src/common/libkvs/test/kvs.c
- src/modules/kvs/kvs.c
- t/t1000-kvs.t
- t/t1004-kvs-namespace.t
While playing around with #3811 I realized it was impossible to initialize a namespace to a specific root reference.  So "checkpointing" was sort of impossible.
This updates the KVS namespace create RPC to allow specification of a root reference to initialize the namespace to.
Edit: Note that I did break ABI on `libkvs` to allow user to pass a `const char *rootref`.  To my knowledge, no flux-framework callers outside of `flux-core`.
> kvs: optionally initialize namespace to a root reference

- NEWS.md
Placeholder for v0.31.0 release notes.  Edit at will.
> NEWS: update for v0.31.0

- doc/man3/tsync.c
- src/broker/groups.c
- src/broker/overlay.c
- src/cmd/builtin/overlay.c
- src/common/libutil/ipaddr.h
- t/t2009-pmix-bootstrap.t
- t/t3303-system-healthcheck.t
Suppress a couple of concerning but actually benign error messages @grondo noticed when he was testing flux on a node that was running out of memory.
Plus some other minor quasi-related stuff I had queued up, the most substantial of which is changing an RPC that is used by `flux overlay status` to be more useful for other things TBD.  (This commit came from an earlier monitoring branch so the use case is not there anymore, but I think this is probably a better way to structure the RPC before expanding it to include idle time).
> broker/overlay: misc cleanup

- src/cmd/flux-mini.py
- t/t2703-mini-bulksubmit.t
This improves the broken `flux-mini bulksubmit --dry-run` output when the `--cc` option is used.
Instead of just dropping the option in output, this simple change includes `--cc` in the output if the option was used.
```console
$ flux mini bulksubmit --dry-run --cc=1-2 echo {} ::: 1 2 3
flux-mini: submit --cc=1-2 echo 1
flux-mini: submit --cc=1-2 echo 2
flux-mini: submit --cc=1-2 echo 3
```
> cmd: improve flux-mini bulksubmit --dry-run output with --cc

- src/broker/groups.c
- src/modules/resource/topo.c
- t/t2310-resource-module.t
- t/valgrind/workload.d/job-info
This addresses a fatal resource module error discovered by @grondo in #3946.  The error handling code in the `resource.topo-reduce` request handler was not quite correct with respect to handling (expected) duplicate requests.
Also, an earlier commit 66d55f32dfa7e7c132a9b57dfa2056d20415e1e4 was supposed to suppress ENOSYS errors from the `groups.get` RPC, but it handled  `groups.leave` only.  Fix that too.
> resource: improve topo-reduce error handling

- src/common/libpmi/simple_server.c
- src/common/libpmi/test/simple.c
Problem: since slurm installs its libpmi2.so in the main libdir, it's
easy for applications to pick it up unintentionally in an rpath.
When Flux tries to launch the app, PMI tracing shows:
TRACE: 0: C: cmd=init pmi_version=2 pmi_subversion=0
TRACE: 0: S: cmd=response_to_init rc=0 pmi_version=1 pmi_subversion=1
followed by application hang.
Send back a failure code if the major version is not 1 to turn
the hang into a hard failure.
Add unit test coverage.
Fixes #3909
> libpmi/server: don't allow PMI2 to connect

- doc/Makefile.am
- doc/conf.py
- doc/man3/flux_rpc.rst
- src/common/libflux/rpc.c
- src/common/libflux/rpc.h
- src/common/libflux/test/rpc.c
- src/common/libsubprocess/remote.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/bulk-exec.h
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- t/Makefile.am
- t/issues/t3906-job-exec-exception.sh
- t/issues/t3960-job-exec-ehostunreach.sh
- t/t4000-issues-test-driver.t
As discussed in #3960, the remote execution and kill errors from the job-exec module do not include any rank information, which is unhelpful in diagnosing problems from logs alone.
This PR adds a `flux_rpc_get_nodeid(3)` API call to make it convenient to print the target rank in rpc errors, and uses this to add rank information to many remote subprocess and job-exec error messages.
I didn't go as far as caching the entire request for every RPC, since I didn't have a use case for anything other than the `nodeid` at this time, and was worried about the extra memory required when many, many RPCs are in flight in a client or module. For now, a `nodeid` field is added to the `struct flux_rpc` which simply caches the `nodeid` argument to `flux_rpc(3)`, making it conveniently available during …
> job-exec: improve errors and job exception message on broker disconnect

- doc/man7/flux-broker-attributes.rst
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/test/boot_config.c
- src/cmd/builtin/overlay.c
- src/modules/resource/inventory.c
- t/t0013-config-file.t
- t/t3300-system-basic.t
- t/t3303-system-healthcheck.t
Problem: a single-user flux instance boostrapped from flux or a foreign launcher does not have a hostlist, which would be useful for logging as suggested in #3961.
This renames  the `config.hostlist` broker attribute to `hostlist` and removes an assumption in the resource module that a configured _R_ must be re-ranked if the attribute is present (really it should only be re-ranked if the `[bootstrap]` config table exists).
Then the `hostlist` attribute is set during PMI bootstrap by adding the hostname to each node's business card and reading all the business cards on each rank.
In this attempt, the hostlist is guaranteed to be set after the broker exists bootstrap, regardless of the bootstrap method, which makes it useful for logging during wire-up.
This is a revamp of PR #3963.
Labeled …
> broker: set hostlist attribute when Flux is boostrapped from PMI

- t/sharness.d/flux-sharness.sh
- t/t2607-job-shell-input.t
Just a couple small testsuite fixes in one PR.
This PR unsets `FLUX_RC_EXTRA` and `FLUX_SHELL_RC_PATH` for all sharness tests since these variables from the environment could interfere with test reproducibility.
Also improve a couple flaky tests in `t2607-job-shell-input.t`. The main improvement is more efficient submission of duplicate jobs and addition of a timeout, which _should_ turn the hangs we sometimes see in CI into hard failures (at which point we could investigate further)
> testsuite: sanitize environment and fix hang in t2607-job-shell-input.t

- src/broker/attr.c
- src/broker/attr.h
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/broker.c
- src/broker/module.c
- src/broker/module.h
- src/broker/overlay.c
- src/broker/test/overlay.c
- src/cmd/builtin/overlay.c
- src/common/libflux/attr.c
- src/common/libflux/attr.h
- src/common/libflux/test/attr.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/exec.c
- t/issues/t3906-job-exec-exception.sh
- t/t0001-basic.t
- t/t3303-system-healthcheck.t
Now that the broker `hostlist` attribute is always set, add a function for translating a broker rank to hostname, and use it to make a few log messages more useful.
This also makes a small change to the broker so that "immutable" broker attributes like `hostlist` are automatically cached in the broker flux_t handle and in all the module flux_t handles.   In other contexts, `flux_get_hostbyrank()` might make an RPC on the first call to fetch the hostlist attribute.
> add flux_get_hostbyrank() and improve caching of broker attributes

- src/cmd/builtin/overlay.c
- t/t3300-system-basic.t
- t/t3301-system-latestart.t
- t/t3303-system-healthcheck.t
- t/t3305-system-rpctrack-up.t
- t/t3306-system-routercrash.t
Problem:  flux -overlay requires a bunch of options to get the most useful output.
The inadequacy of the current default output was brought home to me in our discussion with the AHA moles team.  I suggested the command, and Jeff ran it on the call and said "it just prints full".   If you're running the tool you probably want the detail.  If you don't want the detail, then you can learn the options to dial it down.
So, rework the options so that one doesn't have to specify `-vvv --ghost --pretty --color` to get the "best" output.  Now the default includes all the brokers with full gaudiness, which can be dialed down with `--no-pretty --no-color` if desired.  Add two options `--summary` (the former default - terse one word summary of subtree status), and `--down`, which only shows …
> flux-overlay status: rework options

- etc/rc1
- src/common/libkvs/kvs_getroot.h
- src/modules/job-exec/Makefile.am
- src/modules/job-exec/checkpoint.c
- src/modules/job-exec/checkpoint.h
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/testexec.c
- src/modules/job-manager/job.h
- src/modules/job-manager/restart.c
- src/modules/job-manager/start.c
- t/Makefile.am
- t/t3202-instance-restart-testexec.t
Thought I'd throw up this WIP if there are any high level thoughts / comments.  This is an prototype set of changes for checkpointing KVS namespaces when a broker goes down and "re-attaching" to an already running job.  What this PR does is:
A) upon unloading the job-exec module, checkpoint the rootref of the KVS namespaces of still running jobs
B) upon re-load, if the job is believed to still be running, send `job-exec` a "re-attach" flag from `job-manager`
C) upon re-load, have `job-exec` re-build KVS namespace with checkpointed rootref
D) upon "re-attach", `testexec` will simulate remaining runtime of the job based on the starttime of the job (i.e. perhaps `testexec` thinks the job has run 90 seconds out of 100 seconds, simulate a run for just 10 more seconds)
This currently works with …
> job-manager / job-exec: checkpoint and restore guest KVS namespaces

- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/core/watchers.py
- src/bindings/python/flux/message.py
- t/python/t0007-watchers.py
This PR is an attempt at a general fix for #3973.
The problem of `Watcher` objects being subject to early GC is solved by adding them automatically to an active watchers set in the `Flux` handle from which they are created. To avoid a circular reference, the internally stored `flux_handle` in `Watcher` objects becomes a `weakref.ref()`. At `destroy()` time, a best effort is made to remove the `Watcher` from the `flux_handle` watcher set.
Unfortunately, I was getting an `AttributeError` with this approach at interpreter exit for `TimerWatcher has no attribute "get_flux"`, which is baffling, so I wrapped the call to get the `Watcher` flux handle in a `try/except` block. It probably means I've done something subtly wrong, but I couldn't find it.
> python: avoid early garbage collection of Watcher objects

- README.md
- configure.ac
- src/cmd/Makefile.am
- src/cmd/top/joblist_pane.c
- src/cmd/top/keys.c
- src/cmd/top/summary_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
- src/cmd/top/ucache.c
- src/common/libutil/fsd.c
- src/common/libutil/fsd.h
- src/common/libutil/test/fsd.c
- src/test/docker/bionic/Dockerfile
- src/test/docker/centos7/Dockerfile
- src/test/docker/centos8/Dockerfile
- src/test/docker/checks/Dockerfile
- src/test/docker/fedora33/Dockerfile
- src/test/docker/fedora34/Dockerfile
- src/test/docker/focal/Dockerfile
- t/Makefile.am
- t/t2801-top-cmd.t
This adds a first cut at a `flux top` command.  Usage is `flux top [jobid]`.
There is quite a bit of explanation in the commit that adds the command so I won't duplicate that here.  Instead here are a couple of screen shots.  The first example is of monitoring a batch job running the throughput test:
```
ƒ(s=8,d=0,builddir) $ cat foo.sh
#!/bin/bash
/home/garlick/proj/flux-core/src/test/throughput.py -x -n 10000
ƒ(s=8,d=0,builddir) $ flux mini batch -n16 -t 10m foo.sh
ƒ3BBeCNddq
ƒ(s=8,d=0,builddir) $ flux top ƒ3BBeCNddq
```
The two turtles on the left indicate that this job has an instance depth of 1 (hierarchy of 2).  The hourglass on the right shows the time left in the instance, because it was submitted with a time limit.
The second example shows fluke, with some nodes down graphed in …
> add flux top command

- src/common/libflux/message.c
- src/common/libflux/test/message.c
This PR extends the NULL safety check in many `flux_msg_*()` functions to include checking that the message reference count is nonzero.  I verified that the reproducer for #3982 no longer sends a misdirected response to the broker groups service (it just hangs now).  Hopefully these checks will make message refcounting bugs more straigtforward to track down.
There's also a bit of gratuitous cleanup in here (couldn't resist).
> libflux: improve safety against refcounting bugs in low-level message functions

- etc/flux.service.in
- src/broker/state_machine.c
- t/t0025-broker-state-machine.t
This is an attempt to improve logging somewhat when faced with the problem described in #3959, where flux gets stuck starting up because of a bad node, and doesn't provide any clues as to which node is the bad one.  A timer is added to the state machine which is started on rank 0 upon entering QUORUM state, and fires every 60s, logging the brokers that haven't checked in yet, until rank 0 exits the QUORUM state.  Here's an example with the timeout cranked down to 1s:
```
$ flux start -s8 -o,-Sbroker.quorum-timeout=1s
2021-11-28T00:09:52.631500Z broker.err[0]: quorum delayed: waiting for system76-pc (rank 7)
2021-11-28T00:09:52.680774Z broker.err[0]: quorum reached
ƒ(s=8,d=0,builddir) $
```
Unfortunately, if the bad node is a router on the overlay network, any of its children will likely …
> broker: log slow nodes during startup

- etc/flux.service.in
Problem: Some future flux services may wish to run processes
under systemd. This would require a flux user service to be
setup under systemd.
Solution: Update flux service file to setup flux user service
when the broker is started.  Add appropriate environment
variables for user service to environment before launching flux broker.
> systemd: start flux systemd user service

- src/bindings/python/flux/message.py
- t/Makefile.am
- t/issues/t3982-python-message-ref.py
This appears to fix the issue described in #3982.
The `Message` class was probably written before `flux_msg_incref()`, and it tried to be smart about whether or not to "destruct" the underlying `flux_msg_t` on `Message` garbage collection. This led to possible use-after-free of `flux_msg_t` if a message is stashed from a msg_handler in Python for later use.
With the availablity of `flux_msg_incref()`, the handling of `Message` objects becomes more sane. We always call `flux_msg_decref()` when a `Message` is GC'd, and call `flux_msg_incref()` always, unless the `Message` constructor itself creates the underlying `flux_msg_t`.
> python: fix reference counting for Python Message objects

- README.md
The flux-core README.md contains some outdated information.  Make a few edits to bring it up to date.
> bring README.md up to date

- .mergify.yml
- README.md
- src/test/docker/README.md
- src/test/docker/bionic/Dockerfile
- src/test/docker/checks/Dockerfile
- src/test/generate-matrix.py
- t/t2700-mini-cmd.t
During rebuild of docker images for #3989 wonderful `pip` in the bionic image pulled in latest `jsonschema`, which broke the build since `configure` can't detect the version for that module after 4.0 since they removed the `__version__` attribute on the module. Additionally, the newest cffi module no longer built with python3.7 because it now appears to require `libffi-dev`.
Additionally, I noticed that `src/test/docker/README.md` hadn't been updated with instructions for how to build the multiarch `bionic` image, which requires `docker buildx`.
This PR includes the fix for #3989. It seems like that commit can also fit in this PR to speed up the merge of these fixes.
> docker: fix and update ci dockerfiles

- etc/flux.service.in
Problem: A rebase error left a line in etc/flux.service.in without
a necessary continuation character, causing systemd to fail to start
flux.
Add the missing line continuation character to etc/flux.service.in.
Fixes #3995
> systemd: fix typo in flux.service unit file

- doc/Makefile.am
- doc/conf.py
- doc/domainrefs.py
- doc/man1/flux-uri.rst
- doc/man1/index.rst
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/importer.py
- src/bindings/python/flux/job/validator/validator.py
- src/bindings/python/flux/uri/__init__.py
- src/bindings/python/flux/uri/resolvers/jobid.py
- src/bindings/python/flux/uri/resolvers/pid.py
- src/bindings/python/flux/uri/resolvers/slurm.py
- src/bindings/python/flux/uri/uri.py
- src/cmd/Makefile.am
- src/cmd/flux-uri.py
- t/Makefile.am
- t/python/t0025-uri.py
- t/t2802-uri-cmd.t
This PR introduces a `FluxURIResolver` Python class which can resolve target URIs to Flux job URIs. Support for resolving URIs in different contexts is provided by resolver "plugins" which are loaded based on the target URI _scheme_, though if no _scheme_ is provided, then a scheme of `jobid` is assumed.
A new `flux-uri(1)` utility is provided to access this Python class from the commandline.
The PR includes three resolver plugins:
* `jobid`: resolve job URIs for a Flux jobid in the current instance. This resolver works recursively if a "path" of jobids is provided, e.g. `jobid:f1234/f3456` will attempt to resolve the URI for jobid `f3456` running as  child job of `f1234`. Since `jobid` is the default URI resolver scheme, `f1234/f3456` would also work. e.g.
```console
$ flux uri ƒR3S77XQb …
```
> add FluxURIResolver Python class and flux-uri command for job URI discovery

- doc/man1/flux-proxy.rst
- doc/man1/flux-uri.rst
- src/bindings/python/flux/uri/resolvers/jobid.py
- src/cmd/builtin/proxy.c
- src/cmd/top/top.c
- src/common/libutil/Makefile.am
- src/common/libutil/uri.c
- src/common/libutil/uri.h
- t/t1105-proxy.t
- t/t2801-top-cmd.t
- t/t2802-uri-cmd.t
This PR adds a C function `flux_uri_resolve()` to libutil which calls out to `flux-uri(1)` to resolve a high-level URI "target" to a native Flux URI.
Then, support for high-level URIs is added to both `flux top` and `flux proxy` by calling `flux_uri_resolve()` to resolve the command argument, if provided.
This allows these commands to connect to jobs using any resolvable URI argument supported by `flux-uri(1)`, including plain jobids, nested jobids, e.g.:
```
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux jobs
JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
ƒQ6Nz6NkP grondo   flux        R      4      1   43.22s asp
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux proxy ƒQ6Nz6NkP?local flux jobs
JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST …
```
> cmd: support high-level URIs and JOBID arguments in flux-top and flux-proxy
