- src/cmd/builtin/proxy.c
- src/common/libflux/reactor.c
- src/common/libflux/test/reactor.c
I happened to notice that `flux proxy` is calling `flux_reactor_create (SIGCHLD)`  but the flag should be `FLUX_REACTOR_SIGCHLD`.
Fix that, and add flag validation to `flux_reactor_create()` and `flux_reactor_run()`.
> libflux: check reactor flags

- src/common/libutil/uri.c
- t/t1105-proxy.t
This PR fixes an embarrassing error in the `uri_resolve()` implementation which causes `flux proxy /JOBID` to segfault. :facepalm:
For a minute, I thought it would be cool if `/` resolved to the depth=0 instance (root) in the current hierarchy, and if we also supported `..` as "look in parent", but I'm pretty sure we don't want to go there, so `/JOBID` is treated the same as `JOBID`.
> fix segfault in uri_resolve() when argument has "/" prefix

- doc/man1/flux-jobs.rst
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
Per #3993 
- make `-A` option be a convenience for `--user=all` and nothing else.  This allows `-A` to be used alongside `--filter`.
- re-word documentation that `-a` lists jobs in all states.  The documentation that it lists all jobs for the current user is redundant b/c the current user is always the default.  It is basically now a shortcut for `--filter=pending,running,inactive`
- as a result, `flux jobs -a -A` may be commonly used as a shortcut for listing all jobs, in all states, for all users
> cmd/flux-jobs: re-work -A option and clarify -a option

- src/cmd/flux-uri.py
- src/cmd/top/joblist_pane.c
- src/cmd/top/keys.c
- src/cmd/top/summary_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
- src/common/libutil/uri.c
- t/scripts/runpty.py
- t/t2801-top-cmd.t
This started as an experiment but turned out to be useful, so posting it as a PR to get comments.
Now that instance URIs are available in job listing, add the `annotations` attribute to the `flux top` `job-list` query and have jobs that are instances colored blue (or made bold if there's no color support).
Introduce the idea of a current or "selected" job. The selection is made by traversing the `flux top` job listing with the `j` and `k` or arrow keys. The currently selected job is highlighted. On the "enter" key, `flux top` recursively calls itself on the currently selected job, if that job is an instance (nothing happens for a normal job).
Since the new function `top_run()` is called recursively, hitting the `q` key in the nested `top` call pops you back up to the previous job, while …
> flux-top: allow top to recursively call itself

- .github/workflows/main.yml
- src/cmd/flux-cron
- src/shell/svc.c
- src/shell/svc.h
- src/test/checks-lib.sh
- src/test/checks_run.sh
- src/test/docker/centos8/Dockerfile
- src/test/docker/docker-run-checks.sh
- src/test/docker/docker-run-systest.sh
- src/test/docker/fluxorama/Dockerfile
- src/test/docker/fluxorama/entrypoint.sh
- src/test/generate-matrix.py
- t/Makefile.am
- t/scripts/run_timeout.py
- t/scripts/stats-listen.py
- t/system/0001-basic.t
- t/t0016-cron-faketime.t
- t/t1200-stats-basic.t
- t/t9000-system.t
This PR adds a tweak to the fluxorama docker image along with a simple script to make iterative development and test easier within this systemd based docker container.
Currently, the script only launches an interactive shell within the container after launching it. In the future, though, the script could be extended to run a suite of multi-user specific tests.
I'm posting this a little early since @chu11 may find the script useful in his current work.
The script first optionally rebuilds the `fluxrm/flux-core:centos8` image from the current build directory (only if `--rebuild` option is used). It then builds the `systest` stage of the `fluxorama` image (an image without ttyd enabled) and starts the container in the background. An interactive shell is started in the container as the …
> ci: add ability to run tests under system instance

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/uri/resolvers/jobid.py
- src/bindings/python/flux/uri/uri.py
- src/cmd/flux-jobs.py
- t/Makefile.am
- t/t2800-jobs-recursive.t
This PR adds a very simple `-R, --recursive` option to `flux-jobs` which lists child jobs recursively.
Similar to `ls -R`, when listing recursive jobs, each child instance of Flux is prefixed with its "path", which also happens to be a suitable jobid URI for use with `flux-uri` (and thus `flux-proxy(1)` and `flux-top(1)`).
If `--stats` is given, then the jobid path is also accompanied by that job's statistics.
A `-L, --level=N` option can be used to stop the recursion at a defined depth.
As part of this work, a convenience `uri` property was introduced for `JobInfo` objects, along with support for listing `{uri}` and `{uri.local}` attributes in `flux-jobs`.
Finally, in keeping with the visual cue introduced recently in `flux-top(1)` running jobs which are also instances of Flux are now …
> flux-jobs: add --recursive option

- doc/Makefile.am
- doc/conf.py
- doc/man1/flux-broker.rst
- doc/man1/flux-content.rst
- doc/man1/flux-event.rst
- doc/man1/flux-getattr.rst
- doc/man1/flux-hwloc.rst
- doc/man1/flux-keygen.rst
- doc/man1/flux-logger.rst
- doc/man1/flux-module.rst
- doc/man1/flux-resource.rst
- doc/man1/flux.rst
- doc/man1/index.rst
- doc/requirements.txt
- src/cmd/flux.c
As discussed in #4000, `flux help` prints some commands that are probably not going to be very popular.  Drop those from the output, and add a reference to our [readthedocs documentation](https://flux-framework.readthedocs.io).  Also add a missing `flux-resource(1)` man page.  There are others but that one seemed egregious. 
After these changes, output is:
```
$ flux help
Usage: flux [OPTIONS] COMMAND ARGS
-v, --verbose          Be verbose about environment and command search
-V, --version          Display command and component versions
-p, --parent           Set environment of parent instead of current instance
Common commands from flux-core:
cron               Schedule tasks on timers and events
dmesg              manipulate broker log ring …
```
> doc: add flux-resource(1),  clean up help output

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/resource/__init__.py
- src/bindings/python/flux/resource/list.py
- src/cmd/flux-jobs.py
- src/cmd/flux-resource.py
- t/Makefile.am
- t/t2800-jobs-instance-info.t
This PR adds a small set of `instance.` fields to the `JobInfo` class, and therefore also to `flux-jobs` output
By default, the extra information is not fetched for `JobInfo` objects. Instead a new class method `.get_instance_info()` is added which can optionally be run to fetch Flux instance data if the job is indeed an instance, and if the job is currently running.
The instance-specific data is encapsulated in a new `InstanceInfo` class, which currently contains `JobStats` and `SchedResourceList` objects at the time the data was fetched. The class also provides some possibly useful high-level attributes including:
* `instance.utilization`: the number of cores used divided by the total number of cores in the instance
* `instance.gpu_utilization`: same as above but for GPU resources, if …
> flux-jobs: support instance-specific fields in output

- doc/man1/flux-jobs.rst
- src/cmd/flux-jobs.py
- t/t2800-jobs-recursive.t
This PR makes some improvements to recursive job listing by
* only attempting to recurse into current user's jobs by default, unless `--recurse-all` is used.
* connect and fetch all child job info in parallel using a ThreadPoolExecutor. A new `--threads` option is added to optionally adjust the `max_workers` value for this recursive jobs as well as instance-info gathering ThreadPools.
This is based on top of #4022
> flux-jobs: improve recursive job listing

- src/broker/state_machine.c
Problem: spurious 'quorum delayed' log messages are emitted on rank 0
of a system instance.
The timer is armed even if the timeout value is set to -1, as it the
case for the system instance, where the systemd unit file sets th
quorum.timeout attribute to "none".
Don't arm the timer unless the timeout is greater than zero.
Fixes #4017
Co-authored-by: Mark A. Grondona <mark.grondona@gmail.com>
> broker: avoid inappropriate quorum.timeout

- src/test/docker/fluxorama/Dockerfile
Add a few conveniences to the `fluxorama` image:
- allow primary user to sudo to root or the `flux` user.  Since we launch the broker under `flux`, can be useful for debugging
- setup common systemd environment vars for `flux` user in their `.bashrc`, so that they are already setup when `su`-ing or `sudo`-ing to the `flux` user.
> fluxorama: allow user to sudo to flux user, add common systemd environment vars to flux user's bashrc

- t/t2800-jobs-recursive.t
Problem: The FLUX_SECURITY prereq is missing on some tests that
require it, causing t2800-jobs-recursive.t to fail on flux-core
that isn't built --with-flux-security.
Add the necessary prereq to sharness tests that require flux-security.
Fixes #4029
> t2800-jobs-recursive.t: add missing FLUX_SECURITY prereq to tests

- doc/Makefile.am
- doc/conf.py
- doc/man1/flux-jobs.rst
- doc/man1/flux-pstree.rst
- doc/man1/index.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/util.py
- src/cmd/Makefile.am
- src/cmd/flux-pstree.py
- t/Makefile.am
- t/python/t0026-tree.py
- t/t2800-jobs-instance-info.t
- t/t2803-flux-pstree.t
This PR adds a `flux-pstree(1)` command which offers [`pstree(1)`](https://man7.org/linux/man-pages/man1/pstree.1.html)  like output for Flux job hierarchies. 
This is still a WIP because there isn't yet any documentation or tests. It seemed a good idea to get some early feedback before taking a pass at either, in case the interface needs to be changed. It is built on top of the two pending PRs #4024 and #4022.
Currently this command only targets jobs for the calling user, as it didn't seem too useful to attempt to list other user's jobs at this time. Perhaps in the future a `-A, --user=all` option could be added if necessary.
The commit that adds the command has a good overview, so I won't repeat that here. Mainly I'll just show some examples:
```console
$ flux jobs
JOBID USER     NAME …
```
> add flux-pstree command

- etc/flux.service.in
Problem: Systemd user services can be stopped after the last
user session for that user has exited.  This can become a problem
during development / testing / debugging if someone runs something
under the flux user (e.g. 'sudo -u flux ...`) or su's to the flux
user and then exits.
Solution: Set linger on the flux user to ensure systemd user
services will not be stopped.
Fixes #4030
> systemd: set linger on flux user

- src/modules/job-list/job_state.c
Problem: An error is emitted from job-list for every job:
```
job-list: job_update_eventlog_seq: job X duplicate event (last = N, latest = N)
```
The problem is the else clause in `journal_process_event()`, which
always calls `job_update_eventlog_seq()`, even though this function is
already called at the top of the function. This causes the function
to be called twice for events that are not handled explicitly, such
as the "start" event.
Remove the `else` clause. `job_update_eventlog_seq()` will never need
to be called here since it is always already called at the top of
the function when `job` is found in the hash, or the function exits
early if `job` is not found.
Fixes #4041
> job-list: fix "duplicate event" errors

- src/bindings/python/flux/resource/ResourceSet.py
- src/bindings/python/flux/resource/Rlist.py
Problem: On Python 3.10, the import of Mapping from collections
gets
"ImportError: cannot import name 'Mapping' from 'collections'"
It turns out that Mapping should be imported from 'collections.abc'
not just 'collections'. Fix the import.
> python: fix ImportError for collections.abc.Mapping

- doc/Makefile.am
- src/bindings/lua/Makefile.am
- src/common/libioencode/Makefile.am
- src/common/librouter/Makefile.am
- src/common/libsubprocess/Makefile.am
- src/common/libterminus/Makefile.am
- src/modules/content-files/Makefile.am
- src/modules/job-exec/Makefile.am
- src/modules/job-manager/Makefile.am
- src/modules/kvs/Makefile.am
- src/modules/resource/Makefile.am
- src/test/checks_run.sh
- src/test/docker/poison-libflux.sh.in
- t/Makefile.am
- t/sharness.d/01-setup.sh
- t/t2802-uri-cmd.t
- t/t9000-system.t
This PR fixes the use of the `poison-libflux.sh` script during `docker-run-checks.sh`. It turns out the script wasn't actually being used because it needs to be run under `sudo`.
Once that was fixed, it turns out many tests were being linked with system `libflux-*.so` libraries under some distros. This required some further fixes and experimental workarounds to the build system.
Finally, some poisoned `flux-*` commands are added to a fake `FLUX_EXEC_PATH` to ensure we never call out to commands in the system or previously registered `FLUX_EXEC_PATH` during the testsuite (as was seen with #4038)
Along the way a couple other minor testsuite issues were fixed.
> ci: fix use of poison-libflux.sh and add poison fllux-* commands

- doc/man7/flux-broker-attributes.rst
- src/broker/groups.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/state_machine.c
- src/broker/test/overlay.c
- src/modules/resource/drain.c
- t/Makefile.am
- t/t3308-system-torpid.t
Here is a first cut at changes to drain nodes that are "torpid" (unresponsive).
A broker group `broker.torpid` is set up to track torpid nodes based on the existing code for logging them.  Then the resource module watches that group.  Any broker ranks (er execution targets) entering the group are drained with the message `broker was unresponsive` and will remain drained until someone manually runs `flux resource undrain target`.
The parameters affecting this behavior can be set via config file or broker attribute.  The broker attribute can be set on the fly.  In case it becomes annoying during a DAT or something, it can be disabled with `flux exec flux setattr tbon.torpid_max 0`.
I just realized while writing this that I didn't update man pages so adding WIP and will take care of that …
> resource: drain torpid nodes

- doc/Makefile.am
- doc/conf.py
- doc/man5/flux-config-access.rst
- doc/man5/flux-config-archive.rst
- doc/man5/flux-config-bootstrap.rst
- doc/man5/flux-config-exec.rst
- doc/man5/flux-config-job-manager.rst
- doc/man5/flux-config-resource.rst
- doc/man5/flux-config-tbon.rst
- doc/man5/flux-config.rst
- doc/man5/index.rst
- doc/man7/flux-jobtap-plugins.rst
This PR fills in some missing man pages in section 5.  For a start it adds `flux-config(5)` which is an overview of config files, and pages for a couple of additional tables, including for `tbon` so we can document the new "torpid" knobs.  I wanted to see if this pattern looks OK before adding more (hence WIP).  I was thinking we could have a man page for each top level table, named with the pattern `flux-config-NAME.5` where NAME is the table name.  That seem reasonable?
Then we can reference these pages from the configuration section of the [Administrator's Guide](https://flux-framework.readthedocs.io/en/latest/adminguide.html).
> doc: add man pages for config files

- doc/man1/flux-proxy.rst
- src/cmd/builtin/proxy.c
- t/t1105-proxy.t
This PR contains a few fixes (already described in #2139) to improve the experience of `flux proxy` users when the proxied Flux instance terminates.
Currently, `flux proxy` exits, leaving the child process (usually an interactive shell) to be reparented to PID 1 and lose its terminal. This typically causes the user's tty to get into a bad state. Sometimes I've even had myself logged out of my connection to the host from which I originally ran `flux proxy`.
This PR adds a couple mitigations for these problems:
* Attempt to restore terminal when `flux proxy` gets an error. This seems to help me in most cases, though nothing is guaranteed. The code makes a best-effort attempt to do the restore.
* Attempt to keep `flux proxy` running until the child process exits. This makes it so that the …
> flux-proxy: improve experience when proxied Flux instance terminates

- src/cmd/flux-ping.c
- t/t0007-ping.t
Problem: The default help output says "flux-ping [OPTIONS] ..."
which is not clear.
Solution: Update output to "flux-ping [OPTIONS] \<target\>".
Fixes #3892
> cmd/flux-ping: make help output clearer

- doc/man1/flux-content.rst
- doc/man1/flux-kvs.rst
- doc/man1/flux-resource.rst
- doc/man3/flux_attr_get.rst
- doc/man3/flux_content_load.rst
- doc/man3/flux_get_rank.rst
- doc/man3/flux_kvs_lookup.rst
- doc/man3/flux_kvs_txn_create.rst
- doc/man3/flux_respond.rst
- doc/man3/flux_rpc.rst
- doc/man3/idset_add.rst
- doc/man3/idset_create.rst
- doc/man3/idset_encode.rst
- doc/man5/flux-config-archive.rst
- doc/man5/flux-config-bootstrap.rst
- doc/man5/flux-config-exec.rst
- doc/man5/flux-config-resource.rst
- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
Problem: man page RESOURCES often point to RFCs at github rather than readthedocs.
Update references.
Add a couple missing ones.
Fix some RFC references to include a space between RFC and the number.
Drop some man page references that were inappropriate.
> doc: fix cross-references

- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
Initially spawned by issue #3964, ending up fixing many minor things.
- some lines > 80 chars
- some invalid error messages
- do not log common EHOSTUNREACH errors
- remove duplicate logging
- fix potential errno clobbering error
- (and then finally) when error is returned to the user, do not log to LOG_ERR, log to LOG_DEBUG to avoid likely redundant error logs
> libsubprocess: fix excess logging and logging corner cases

- src/bindings/python/flux/job/JobID.py
- src/cmd/flux-pstree.py
- t/t2800-jobs-cmd.t
- t/t2803-flux-pstree.t
Problem: When the user inputs an illegal job id the error
message is a very generic:
flux-jobs: ERROR: [Errno 22] EINVAL: Invalid argument
which can be confusing and unclear what was done wrong.
Solution: Improve error message to:
flux-jobs: error: argument JOBID: illegal JobID <invalid arg>
Add a test case.
Fixes #3882
> improve error message from flux-proxy and flux-jobs for invalid and unknown jobids

- doc/conf.py
- doc/man3/flux_stat_watcher_create.rst
- doc/man5/flux-config-bootstrap.rst
The documentation in flux-config-bootstrap(5) is really minimal and probably not all that useful.  This PR expounds a bit and adds a simpler example.
> improve flux-config-bootstrap(5)

- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- src/broker/broker.h
- src/cmd/flux-pstree.py
- src/cmd/top/summary_pane.c
- src/cmd/top/top.h
- src/common/libflux/attr.c
- src/common/libflux/attr.h
- src/common/libflux/test/attr.c
This adds a `broker.starttime` attribute as discussed in #4033, and a convenience function for fetching it from rank 0 so it can be used to calculate instance uptime.  Then the uptime is displayed in `flux-top`.
There are a couple of small cleanups tacked on also.
> add broker.starttime; add uptime to flux-top, flux-pstree

- doc/man1/flux-shell.rst
- src/cmd/flux-mini.py
- src/common/libterminus/pty.c
- src/common/libterminus/pty.h
- src/common/libterminus/terminus.c
- src/common/libterminus/test/pty.c
- src/shell/Makefile.am
- src/shell/output.c
- src/shell/pty.c
- t/t2500-job-attach.t
- t/t2612-job-shell-pty.t
- t/test-inception.sh
This is something I had sitting around for a bit and thought I'd throw up here for now as a WIP for comments.
The job shell pty support is currently pretty limited. It only allows allocating a pty to rank 0, and only supports "interactive" use, where the pty is interactively attached immediately after start. All data sent from the task running under a pty is lost, meaning it is not logged anywhere.
The above is fine for the `flux mini alloc` use case, however there is currently no way to allocate a pty for tasks when run non-interactively or to allocate a pty to all tasks. This may be useful when running asynchronous jobs that expect a pty, e.g. a testsuite that wants to emit color output.
This PR modifies the job shell's `pty` option to be a JSON object with multiple, optional keys, …
> shell: enhance pty support

- doc/man1/flux-mini.rst
- scripts/.pylintrc
- src/bindings/python/flux/future.py
- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/progress.py
- src/cmd/flux-mini.py
- t/python/t0010-job.py
- t/t2703-mini-bulksubmit.t
Had this one sitting around and there's been a few times it would have be useful for testing, so I thought I'd go ahead and propose a PR.
This PR adds a `--wait-event=NAME` option to `flux mini submit` and `flux mini bulksubmit`. The current `--wait` option thus becomes equivalent to `--wait-event=clean`. This option reduces the need for constructs like 
```shell
id=$(flux mini submit ...)
flux job wait-event ${id} start
```
which can be replaced with simply
```
id=$(flux mini submit --wait-event=start ...)
```
and allows waiting for _all_ submitted jobs to receive the indicated event when used with `bulksubmit` or `flux mini submit --cc`.
(It does not, however, provide a timeout option like `flux job wait-event`, so if a timeout is desired `wait-event` should be used.)
The `--wait-event` …
> flux-mini: add --wait-event option to submit/bulksubmit

- doc/man3/flux_shell_log.rst
- src/shell/evlog.c
- src/shell/log.c
- src/shell/shell.h
- t/shell/plugins/log.c
Error messages from the job shell are currently duplicated to the `evlog` plugin and `stderr`, and since job-exec copies `stderr` to the output eventlog, these errors are also duplicated in the output of `flux job attach`, which makes for a bit more output than is strictly necessary, e.g.:
```
ƒ(s=1,d=0) grondo@fluke108:~$ flux mini run badprog
0.060s: flux-shell[0]: FATAL: task 0: start failed: badprog: No such file or directory
0.060s: flux-shell[0]: stderr: flux-shell: FATAL: task 0: start failed: badprog: No such file or directory
0.061s: job.exception type=exec severity=0 task 0: start failed: badprog: No such file or directory
flux-job: task(s) exited with exit code 127
```
This PR adds a way to suppress all `stderr` log messages once the `evlog` plugin is initialized. It is …
> shell: fix duplicate logging after evlog plugin is initialized

- doc/man1/flux-resource.rst
- src/cmd/flux-resource.py
- src/modules/resource/resource.c
- t/t2311-resource-drain.t
This PR ensures that `flux resource drain` (no args) can be used on any rank to list drained nodes, not just rank 0.
Also, allow guests to access the `resource.status` RPC, thus allowing them to use the above command plus `flux resource status`.  This eliminates an unnecessary sudo for sys admins, and also may be useful to users debugging a problem with their jobs.  There is no reason to restrict access that I can think of.
Update tests and man page.
> flux resource: allow limited guest access

- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog.t
This fixes the issue described in #4089, where the job-manager perilog plugin will segfault on a job-exception raised for a job which completed a prolog/epilog.
> Fix broker segfault when an exception is raised on a job after completed prolog

- etc/flux.service.in
Problem: when an upstream broker fails, downstream brokers need to
be manually restarted.
This is sort of as designed but it's a pain.
Switch to Restart=always mode so the broker always tries again,
and sys admins won't have to mop up when something bad happens.
Fixes #3818
> systemd: set restart=always

- src/common/libterminus/client.c
- src/common/libterminus/pty.c
- src/common/libterminus/terminus.c
This was split off from work on #4077. Still don't have the fix working, but these fixes for memory leaks seemed like they should go in sooner rather than later.
> libterminus: fix memory leaks in pty code

- src/shell/svc.c
The system instance owner is by design an unprivileged user which should not have access to guest user services provided by the job shell, but currently most shell services allow FLUX_ROLE_OWNER.
Lock down access to shell-provided services to the job owner only.
> shell: do not allow instance owner to use guest shell services

- doc/conf.py
- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- doc/test/spell.en.pws
- src/broker/overlay.c
- t/t0013-config-file.t
Enable TCP keepalives so Flux can disconnect from nodes that have been turned off.
> broker: use TCP level keepalives

- src/common/libterminus/pty.c
- src/common/libterminus/pty.h
- src/common/libterminus/terminus.c
- src/common/libterminus/test/pty.c
- src/shell/pty.c
- t/t2612-job-shell-pty.t
This PR reworks the pty code to close a race condition when attaching to a short-lived process which has been allocated a pty.
The major visible change here is that, when running a job with `-o pty.interactive`, the shell will keep the rank 0 pty available until at least one client attaches, even if the task has exited. If no client attaches the shell `doom` plugin will terminate the job after 30s by default. This can be disabled via `-o exit-timeout=-1`, in which case the shell could hang until the job times out waiting for a client to attach.
> shell: fix race in attach to interactive job pty

- doc/man1/flux-ping.rst
- src/cmd/flux-ping.c
- src/common/libflux/attr.c
- src/common/libflux/attr.h
- src/common/libflux/test/attr.c
- t/t0007-ping.t
This changes `flux-ping` to accept a hostname as part of the TARGET instead of a rank, e.g.
```
$ ./flux ping system76-pc
0!broker.ping pad=0 seq=0 time=0.200 ms (1c36d225!b4330dc7!b6026d87)
0!broker.ping pad=0 seq=1 time=0.198 ms (1c36d225!b4330dc7!b6026d87)
^C
```
or
```
$ ./flux ping 'system76-pc!kvs'
0!kvs.ping pad=0 seq=0 time=0.232 ms (85d88d89!b4330dc7!b6026d87!e92cbac2)
0!kvs.ping pad=0 seq=1 time=0.363 ms (85d88d89!b4330dc7!b6026d87!e92cbac2)
^C
```
It also adds a general function for resolving hosts to ranks:
```c
/* Find the lowest numbered broker rank running on 'host', by consulting
* the "hostlist" attribute.
* Returns rank on success, -1 on failure with errno set.
*/
int flux_get_rankbyhost (flux_t *h, const char *host);
```
> flux-ping: support hostnames in TARGET

- NEWS.md
This is a rough draft of release notes for v0.35.0.
This assumes a couple pending PRs will go in. I added a short blurb about "better handling of situations where is broker is unresponsive but not disconnected", but I'm assuming @garlick will edit that for correctness and clarity.
Feel free to push any edits or additions directly.
> NEWS.md: add release notes for v0.35.0

- src/broker/broker.c
- src/broker/modservice.c
- src/broker/module.c
- src/common/libflux/module.c
- t/t0003-module.t
Problem: the broker and its modules communicate status using
special control messages, but this communication would be more
clear if regular RPCs were used, with no disadvantage.
Replace low level message code with regular RPCs.  Register
a broker service named `broker.module-status` instead of hard-wiring
module status updates in the broker's low level message callback.
In addition, update `flux_module_set_running()` to use the RPC.
Update tests.
> broker: use RPC not broker module sync/status

- t/t2410-exec-systemd.t
Problem: t2410-exec-systemd.t fails with dash 0.5.10
Replace ">& filename" idiom with ">filename 2>&1".
Fixes #4114
> testsuite: remove unportable cshism

- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- src/broker/modservice.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/common/libflux/Makefile.am
- src/common/libflux/control.c
- src/common/libflux/control.h
- src/common/libflux/flux.h
- src/common/libflux/handle.c
- src/common/libflux/handle.h
- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/message_iovec.c
- src/common/libflux/message_private.h
- src/common/libflux/message_proto.h
- src/common/libflux/module.c
- src/common/libflux/test/message.c
- src/common/librouter/test/rpc_track.c
- src/common/libtestutil/util.c
- t/t0003-module.t
This changes all references to application level keepalives and the Flux keepalive message type to "control messages" per the proposed change to RFC 3 in flux-framework/flux-core#312.
This should avoid some confusion between TCP keepalives, which we now support, and these control messages, now only used between brokers after #4110.
> rename keepalive messages to control messages

- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- doc/test/spell.en.pws
This adds missing broker attributes to flux-broker-attributes(7) and reorganizes its sections.
Also there's a fix for an error in flux-config-tbon(5).
> doc: update flux-broker-attributes(7)

- doc/man1/flux-resource.rst
- src/cmd/flux-perilog-run.py
- src/cmd/flux-resource.py
- src/modules/resource/drain.c
- src/modules/resource/topo.c
- t/t2311-resource-drain.t
This PR introduces some changes in behavior for the `resource.drain` RPC, reflected in a change in the default behavior of `flux resource drain` along with some additional options:
* By default, a `resource.drain` RPC now fails if any targets are already drained. This matches the behavior of `flux resource undrain` and also avoids overwriting existing drain `reasons` without positive verification that you really mean it.
* An optional `mode` member of the RPC request is introduced to change the default drain mode to either:
- mode=`update`: The RPC does not fail if one or more targets are already drained, and does not overwrite existing `reason` for any drained target (it will, however, update a `reason` that is not set)
- mode=`overwrite`: The RPC does not fail if one or more targets are …
> resource: enhance resource.drain RPC with "update" and "overwrite" modes

- doc/man5/flux-config-tbon.rst
- src/broker/overlay.c
- t/t0013-config-file.t
This fixes a bug in the way the `tbon.zmqdebug` attribute setting was interpreted, and adds support for configuring it via the TOML config file.
> broker: allow tbon.zmqdebug to be set in config file and make sure it's really off if set to 0

- src/shell/output.c
- t/t2606-job-shell-output-redirection.t
This PR is a stopgap fix for #4117. 
When an output or error file is specified, re-route log messages to the same output file as stderr, instead of sending them to the output eventlog.
Since the output files aren't opened until after the shell has connected to Flux and initialized, some log messages and errors still end up in the output eventlog, e.g. if something goes wrong before shell.init, but at least there isn't likely to be an _empty_ output file when a job fails after it gets that far, so the spirit of the issue is resolved.
Eventually, perhaps a better fix would be to have the exec system read the output and error options from the jobspec and, if the output type is `file`, pass this along in new `--output` and `--error` options to the job shell. This would allow the job shell to …
> shell: capture job shell error messages in designated output file

- src/broker/module.c
- src/cmd/flux-R.c
- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/common/librlist/test/rlist.c
- src/modules/resource/inventory.c
This PR adds an `rlist_error_t` parameter to `rlist_rerank()` which offers a more specific error when the rerank operation fails.
The parameter is then used in the `resource` module to print a specific error along with the general `error reranking R`.
Finally, to avoid the confusing error message when the `resource` module exits due to `rlist_rerank`'s use of `errno` like `ENOSPC` and `EOVERFLOW`, reset `errno` to `EINVAL` when `rlist_rerank()` fails.
> resource: emit a more specific error when rlist_rerank() fails

- README.md
Problem: It has been shown that when libc6-dev is missing on a
host system, the build fails in a confusing way:
./ccan/endian/endian.h:112:2: error: #error "Unknown endian"
112 | #error "Unknown endian"
|  ^~~~~
Explicitly list that glibc development packages are requirements
to build flux-core to avoid this (and probably other) errors.
Fixes #4002
> README: add libc development packages in requirements

- src/bindings/python/flux/job/submit.py
- src/cmd/flux-mini.py
- src/test/throughput.py
As described in #3614, it would be much more convenient to return a `JobID` instead of `int` from `flux.job.submit` and `flux.job.SubmitFuture.get_id`, with no discernable drawbacks.
This PR updates these Python calls to return a `JobID` object. This should not break any existing code, since `JobID()` on an instance of `JobID` should work fine.
Once the calls are converted, unnecessary use of `JobID()` is removed in `flux-mini.py` and `throughput.py`.
> python: return `JobID` from flux.job.submit, not `int`

- src/modules/kvs/kvs.c
- t/Makefile.am
- t/kvs/change-checkpoint.py
- t/t2010-kvs-snapshot-restore.t
Thought I'd tackle this old issue.  I did a relatively simple thing for the check pointing, writing out a serialized json object storing the rootref + timestamp instead of just the rootref.
Multiple other possibilities, but thought this was the simplest / reasonable (i.e. no need to change content store implementation).  Other options include writing two keys out instead of one.
Note that I intentionally did not support backwards compatibility.  Figured use of this was rare at the moment.
```
Problem: It'd be convenient if we knew the date when the kvs
primary checkpoint was checkpointed.
Solution: When checkpointing the primary KVS, store a json
object with both the rootref and timestamp, instead of just
the rootref string.  On retrieval, parse appropriately and
retrieve timestamp for …
```
> kvs: add date to kvs-primary checkpoint

- .github/workflows/main.yml
- codecov.yml
This PR has a couple tweaks to codecov configuration and uploader which may help with some of the strange coverage reports we've seen since adding the "system" coverage builder.
1. Update the codecov GH action to v2. The system coverage builder uses the newest uploader, so perhaps there is some inconsistency in the two uploads which is causing differences.
2. Delay the codecov PR comment until both coverage reports are uploaded by setting `after_n_builds: 2`. This may give codecov a change to merge reports before commenting.
It is unclear if either of these will help with the report of ~3% coverage drop due to the system coverage builder, but they both seem like a good idea for now.
> codecov: minor improvements for coverage reporting

- doc/Makefile.am
- doc/man1/flux-uptime.rst
- doc/man1/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/broker/groups.c
- src/cmd/Makefile.am
- src/cmd/builtin/uptime.c
- src/modules/job-manager/alloc.c
- src/modules/job-manager/submit.c
- t/Makefile.am
- t/t2240-queue-cmd.t
- t/t2804-uptime-cmd.t
OK here's a crack at a `flux-uptime` command per discussion in #4146.  Here's some example output on a single user instance:
```
$ flux uptime
17:29:27 up 3.7s, owner garlick, depth 0, size 4
```
Here's some output on a system instance, that happens to have a drained node, some offline nodes, and both scheduling and job submission disabled
```
$ flux uptime
17:31:46 up 46m, owner flux, depth 0, size 8, drained 1, offline 5, submit disabled, sched disabled
```
It gets a little long if everything is showing, but most of the time that won't be the case.
> add flux-uptime command

- doc/Makefile.am
- doc/man1/flux-startlog.rst
- doc/man1/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- etc/rc1
- etc/rc3
- src/cmd/Makefile.am
- src/cmd/builtin/startlog.c
- src/cmd/builtin/uptime.c
- t/Makefile.am
- t/t2805-startlog-cmd.t
- t/t3200-instance-restart.t
- t/t3202-instance-restart-testexec.t
This adds a  `flux-startlog` utility that operates on `admin.eventlog`.
The rc1 adds a `start` event to the eventlog, and rc3 adds a `finish` event.  If the last two events are both starts, then flux is restarting after a crash, since it means rc3 didn't execute.   In that case, run `flux queue stop` and `flux queue disable` (later in rc1) to avoid further damage.
The command provides a history of flux restarts similar to last(1):
```
$ sudo flux startlog
2022-02-23 19:08 - running (58s)
$ sudo systemctl restart flux
$ sudo flux startlog
2022-02-23 19:08 - 2022-02-23 19:10 (1.3m)
2022-02-23 19:10 - running (2.6s)
$ sudo kill -9 89249  # kill the broker
$ sudo systemctl start flux
$ sudo flux startlog
2022-02-23 19:08 - 2022-02-23 19:10 (1.3m)
2022-02-23 19:10 - crashed
2022-02-23 19:10 - …
```
> add flux-startlog and enter safe mode after crash

- src/common/libflux/future.c
- src/common/libflux/test/future.c
Problem: When a negative timeout is passed to flux_future_wait_for()
and a future is not properly initialized to be tied to a localized
'now' reactor, flux_future_wait_for() can return -1 without setting
an errno.
Set errno of EINVAL when the above corner case occurs.  Add unit
test.
Fixes #4160
> libflux/future: set missing errno in flux_future_wait_for() 

- doc/man5/flux-config-archive.rst
Problem: the [archive] configuration example uses integer seconds where FSD is required.
Update example.
Fixes #4163
> flux-config-archive(5): fix TOML example

- src/cmd/builtin/overlay.c
- src/common/libflux/attr.c
- src/common/libflux/attr.h
- src/common/libflux/test/attr.c
This PR abstracts the functionality provided by `flux overlay lookup` into a function `flux_hostmap_lookup(3)` exported from libflux-core for convenience.
The function can take either a set of ranks in Idset form or a set of hostnames in Hostlist form and will return the reverse as an allocated string.
I didn't add docs since there presently any for `flux_get_hostbyrank(3)` and `flux_get_rankbyhost(3)`, but I could if that is desired. (I'm guessing `flux_hostmap_lookup(3)` will be slightly less useful than the other two, but there is one use case in #4155, so it made sense to avoid the code duplication)
> libflux: add flux_hostmap_lookup(3)

- src/shell/output.c
Commit 1d08bf76fd773fedb4a1956a500760254ca27fdf modified how the shell output plugin detects completion, but it introduced a performance issue for single rank jobs, which now wait at least `output.batch-timeout` seconds before the output plugin flushes pending events and exits the reactor.
This PR fixes that issue by having the rank 0 shell add a reference count per task - so that once all tasks are complete the output eventlogger can be flushed and exit immediately.
Without this fix single rank jobs have a minimum runtime of ~500 ms, which affects single node job throughput.
> shell: fix delay in completion of jobs with a single shell rank

- doc/Makefile.am
- doc/man1/flux-config.rst
- doc/man1/flux-uptime.rst
- doc/man1/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/broker/brokercfg.c
- src/cmd/builtin/config.c
- src/cmd/builtin/content.c
- src/cmd/builtin/dmesg.c
- src/cmd/builtin/env.c
- src/cmd/builtin/heaptrace.c
- src/cmd/builtin/help.c
- src/cmd/builtin/hwloc.c
- src/cmd/builtin/python.c
- t/Makefile.am
- t/t2806-config-cmd.t
Here's a new command and corresponding RPC:
```
$ flux config get -h
Usage: flux config get [--type=TYPE] [--quiet] [PATH]
Query broker configuration values
-t, --type=TYPE        Set expected type (any, string, int, real, boolean,
object, array, fsd, fsd-int, fsd-real)
-q, --quiet            Suppress printing of "[key] is not set" errors.
```
Parking this as a WIP until I have a chance to write tests and man page.  Meanwhile, how's the usage look?  I was mainly intending to support usage from shell scripts like rc1.
> add flux-config get

- src/modules/job-exec/Makefile.am
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/exec.c
- src/shell/internal.h
- src/shell/shell.c
- t/Makefile.am
- t/job-exec/dummy.sh
- t/job-exec/imp-fail.sh
- t/t2404-job-exec-multiuser.t
- t/t2602-job-shell.t
This PR fixes an issue in job launch where an early exit of the IMP/shell (before the shell has connected to Flux) causes a job hang. The problem occurs because the exec system doesn't presently have any knowledge of the state of job launch, and it is not considered an exceptional condition if a shell exits with nonzero status (since this could just mean one or more tasks exited with the same). Therefore, no job exception is raised when this condition occurs.
This PR adds a new `FLUX_EXEC_PROTOCOL_FD` channel to the job-exec's execution of the IMP/shell. The channel is then used to replace the `flux_barrier(3)` used by the shell. This allows the exec system to know when the job shell has executed at least one barrier, and it can raise an exception if any job shell (or IMP for mulituser …
> job-exec: fix job hang after early IMP/shell exit

- doc/man1/flux-uptime.rst
- src/broker/broker.c
- src/broker/state_machine.c
- src/cmd/builtin/uptime.c
- t/t3302-system-offline.t
Problem: my system instance was taking a long time to get through `rc1`, but some tools fail in that state and others hang on rank 0.  I thought it might be useful for `flux-uptime` to report how long the broker has been in the current state if it's not in _run_ state.  Here's an example:
```
garlick@picl0:~/proj/flux-conf$ flux uptime
13:03:07 init 6.2s,  owner flux,  depth 0,  size 8
```
Meanwhile, a compute node reports:
```
garlick@picl2:~$ flux jobs
flux-jobs: ERROR: [Errno 11] Upstream Flux broker is offline. Try again later.
garlick@picl2:~$ flux uptime
12:53:51 join 21m,  owner flux,  depth 0,  size 8
```
After rank 0 finally gets to run state, it looks like before, except it says _run_ instead of _up_:
```
garlick@picl0:~/proj/flux-conf$ flux uptime
13:06:21 run 3.3m,  owner …
```
> flux-uptime: provide useful output for slow/stuck broker state

- t/t0005-rexec.t
Problem: Several potential races exist in t0005-rexec.  In one
case, processes launched in the background may have not yet started when
`rexec_ps` is run to see the process listing.  In the second case,
`rexec_ps` may still list killed processes because internal flux
watchers have not yet noticed the killed processes / updated process listings.
Solution: Run `rexec_ps` in a loop to wait for the process listing to
reach the count we are expecting.  Timeout after 30 seconds if the
process listing is not working.
Fixes https://github.com/flux-framework/flux-core/issues/4097
> testsuite: fix racy tests in t0005-rexec

- src/broker/attr.c
- src/broker/boot_config.c
- src/broker/broker.c
- src/broker/test/boot_config.c
Problem: rank, size, and hostlist are required to be in the `flux_t` handle attribute cache in the broker with the IMMUTABLE flag set, or deadlock could result in strange corners of the broker.
Add some assertions that will make this fail fast rather than hang, and a better comment.  Also, while puzzling about broker attributes, I found and fixed a couple of unchecked mallocs.
Thanks to @grondo for triggering this subtle footgun and wondering aloud about it, although I'm sure he enjoyed it so much that thanks will not be necessary.
> add assertions that rank, size, hostlist broker attributes are cacheable

- src/broker/boot_pmi.c
- src/modules/resource/inventory.c
- t/Makefile.am
- t/issues/t4182-resource-rerank.sh
- t/kvs/issue1876.c
- t/t0001-basic.t
As discussed in #4182, the job shell may not assign ranks in an order that follows the parent instance rank ordering. This occurs when there is a heterogeneous allocation of cores (i.e. different numbers of cores per execution target). This behavior is a hold over from a different time, and there is probably an argument that the shell should not do this, but there is a slightly better argument that the `hostlist` attribute is the canonical mapping of hosts to ranks for an instance, and R should follow this mapping not its own. (also, providing this solution is much easier than changing the shell behavior for now).
This PR adds support for re-ranking R in the resource module when R is provided by the parent, as it already does when R is provided by a bootstrap configuration. The re-ranking …
> resource: assign ranks in R provided by job-info based on hostlist attribute

- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/common/librlist/rnode.c
- src/common/librlist/rnode.h
- src/common/librlist/test/rnode.c
- src/modules/resource/topo.c
- t/t2315-resource-system.t
As a stopgap solution for #4181, drop the verification of "gpu" resources (actually any resource except "core") by the flux-core `resource` module in all cases. The `rlist_verify()` used by the resource module will still verify that rank:hostname mapping is correct.
This should allow explicit configuration of GPUs by sysadmins without additionally requiring the `resource.noverify` option, for which we do not have a good plan for propagation to child instances.
Additionally, verification of cores and hostnames has proven valuable lately in the detection of incorrect rank ordering, so it would be nice to keep that part of it for now.
If at some point in the future the system-installed default libhwloc can detect GPUs reliably, then GPU devices can be added back into the verification step. …
> resource: restrict resource verification to cores/hostnames only

- src/common/librlist/rlist.c
- src/common/librlist/test/rlist.c
- t/Makefile.am
- t/issues/t4184-sched-simple-restart.sh
This fixes a counting bug in librlist where cores allocated from ranks that are down caused an underflow in count of available cores. This caused sched-simple to think there were less than zero cores available after a restart with running jobs, so no further jobs could be scheduled.
> sched-simple: fix counting bug that can cause scheduler to fail after a restart

- src/modules/job-exec/exec.c
- src/shell/shell.c
- t/job-exec/dummy.sh
- t/t2402-job-exec-dummy.t
As described in #4195 early exec failures _after_ the initial shell barrier may still cause job hangs since shells could block stuck at a barrier if for some reason an exception can't be raised, or even if signals can't be delivered due to a IMP bug or other issue.
Since the exec system knows that shells have exited during or before a barrier, we might as well have the module abort the barrier at the time, rather than waiting for "something else" to clean up the shells. This will result in a more timely job exit when everything is working correctly, and will also result in a proper cleanup when things are not working well (as was the case in #4195).
> job-exec: fix more potential hangs after early shell failure

- src/common/librlist/rhwloc.c
- t/Makefile.am
- t/hwloc-data/corona/0.xml
- t/t0026-flux-R.t
Similar to flux-framework/flux-sched#918, expand the detection of GPU devices from librlist to include AMD GPUs which are detected by hwloc "RSMI" backend.
Before:
```console 
$ FLUXION_QMANAGER_RC1_NOOP=t FLUXION_ESOURCE_RC_NOOP=t flux start flux resource list -v
STATE NNODES   NCORES    NGPUS LIST
free      1       48        0 rank0/core[0-47]
allocated      0        0        0 
down      0        0        0 
```
After:
```console
$ FLUXION_QMANAGER_RC1_NOOP=t FLUXION_ESOURCE_RC_NOOP=t src/cmd/flux start flux resource list -v
STATE NNODES   NCORES    NGPUS LIST
free      1       48        8 rank0/core[0-47],gpu[0-7]
allocated      0        0        0 
down      0        0        0 
```
> librlist: support hwloc discovery of AMD RSMI GPUs

- etc/flux.service.in
Problem: Flux is started under "/bin/bash -c", leading to journal / log
entries being listed under the program "bash".  Example:
Feb 01 04:30:06 fluxorama bash[51]: broker.info[0]: start: none->join 0.0084658>
Feb 01 04:30:06 fluxorama bash[51]: broker.info[0]: parent-none: join->init 5.2>
Solution: Set the SyslogIdentifier to "flux-broker" so journal / log
entries are more obviously associated with the flux-broker.  Example
after the change:
Mar 10 05:02:52 fluxorama flux-broker[62]: broker.info[0]: start: none->join 0.>
Mar 10 05:02:52 fluxorama flux-broker[62]: broker.info[0]: parent-none: join->i>
Fixes #4084
> systemd: set SyslogIdentifier to flux

- src/bindings/python/flux/idset.py
- t/python/t0021-idset.py
This PR was split off from some work on #4205.
The Python `IDset` class was implemented before the C libidset API exposed important set operations directly, and so the class converted IDsets to Python `set` objects and used that class for set operations. While we don't use Python because it is fast, it turns out that the libidset equivalent set operations (added since the original `IDset` class implementation, I think) are much faster (~11x faster).
This PR converts many of the `IDset` class methods to use the underlying C implementation. Also, a missing `difference` method is added, and some Python operators are overloaded to match the Python `set` conventions (`|/+` for union, `-` for difference, `&` for intersect).
Finally, the `IDset()` constructor is improved to allow more types …
> python: add missing methods and improve efficiency of IDset class

- src/shell/internal.h
- src/shell/shell.c
- t/python/t0010-job.py
- t/t2608-job-shell-log.t
This PR adds the hostname to the log message (and exception note) when a task fails to start (e.g. due to missing executable), or when the shell is unable to `chdir()` to the indicated `cwd` in jobspec.
It will be helpful to have hostnames associated with these errors readily available in the logs or exception note when only a subset of job shells encounter them. We don't go as far as adding the hostname to every error or log message, however, as the rank to hostname mapping is available after the fact for other, more rare errors.
We could eventually _optionally_ display hostnames instead of shell ranks from `flux job attach` by having the command fetch _R_ and use that to lookup the mapping when displaying log messages. That wasn't done for now since it doesn't seem like a critical …
> shell: add hostname to a couple key log messages

- src/broker/broker.c
- t/sharness.d/flux-sharness.sh
It turns out the root of the problem in #4183 is that the broker doesn't currently block `SIGPIPE`, and thus if the broker or any broker module writes to a closed fd, the broker is killed (with signal 13).
The actual problem of writing to a closed pipe was probably introduced via the exec system's use of `FLUX_EXEC_PROTOCOL_FD` with the shell. This doesn't seem to be a problem with the real job shell, but the dummy shell used in `t2402-job-exec-dummy.t` seems to exit quickly in some error case used in the tests, and likely causes SIGPIPE somewhere down in libsubprocess.
In any event, we probably want to be getting `EPIPE` errors locally and not `SIGPIPE` in the broker, so the fix here is to just block `SIGPIPE`. This seems to resolve the intermittent failures in `t2402-job-exec-dummy.t` …
> broker: block SIGPIPE

- src/bindings/python/flux/util.py
- t/fluxometer.lua
- t/issues/t3906-job-exec-exception.sh
- t/issues/t3960-job-exec-ehostunreach.sh
- t/job-archive/query.py
- t/kvs/change-checkpoint.py
- t/python/subflux.py
- t/sharness.d/flux-sharness.sh
- t/t0000-sharness.t
- t/t0013-config-file.t
- t/t2110-job-ingest-validator.t
- t/t2212-job-manager-plugins.t
- t/t2273-job-alloc-bypass.t
- t/t2800-jobs-instance-info.t
- t/t2800-jobs-recursive.t
- t/t2801-top-cmd.t
- t/t2803-flux-pstree.t
- t/test-inception.sh
A good stress test for the testsuite is to run multiple copies of every test across a flux instance via
```
$ flux mini bulksubmit --quiet --shuffle --watch --progress -o pty --cc=1-4  --job-name={./%} \
sh -c './{} -d -v --root=$FLUX_JOB_TMPDIR' ::: t*.t python/t*.py lua/t*.t
```
This command submits 4 copies of every test in the testsuite as a job to the current instance, watching progress and output as the tests progress.
However, when attempting this on fluke, I ran into several issues, including:
- Because the testsuite runs with `LANG=C` and `FLUX_JOB_TMPDIR` contains the jobid in f58 encoding, a few test scripts and one core flux Python module broke due to Unicode errors.
- at least one test broke when `FLUX_JOB_CC` was set in the current environment
- a couple tests used static …
> testsuite: ensure tests can run concurrently with --root=$FLUX_JOB_TMPDIR 

- doc/man1/flux-resource.rst
- src/cmd/flux-resource.py
- t/flux-resource/status/drain.expected
- t/flux-resource/status/example.expected
- t/t2311-resource-drain.t
- t/t2351-resource-status-input.t
As described in #4185, `flux resource drain` and `flux resource status` do not differentiate between ranks that are drained and still have jobs allocated, vs ranks that are "idle" (and thus ready to be taken down for service).
This PR enhances `flux-resource` to fetch  the `sched.resource-status` RPC in addition to `resource.status` and uses the result to create an idset of "draining" ranks by taking the intersection of `drain` ranks with those the scheduler has allocated.
> flux-resource: differentiate drained vs draining ranks

- src/modules/content-sqlite/content-sqlite.c
- t/t0012-content-sqlite.t
Problem: when restarting Flux with an existing content.sqlite
file, sqlite does not raise an error if the db is open read-write
but the file is not writable.  Instead, it fails store RPCs one
by one.
Add an access(2) call before opening the database with the sqlite3 API.
Fixes #4210
> content-sqlite: check that file has rw permission

- configure.ac
- doc/Makefile.am
- doc/man1/flux-dump.rst
- doc/man1/flux-restore.rst
- doc/man1/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/cmd/Makefile.am
- src/cmd/builtin/dump.c
- src/cmd/builtin/restore.c
- src/cmd/builtin/startlog.c
- src/common/libkvs/kvs_checkpoint.c
- src/common/libkvs/kvs_checkpoint.h
- src/common/libkvs/test/kvs_checkpoint.c
- src/modules/content-sqlite/content-sqlite.c
- src/modules/job-exec/job-exec.c
- src/modules/kvs/kvs.c
- src/test/docker/bionic/Dockerfile
- src/test/docker/el7/Dockerfile
- src/test/docker/el8/Dockerfile
- src/test/docker/fedora33/Dockerfile
- src/test/docker/fedora34/Dockerfile
- src/test/docker/focal/Dockerfile
- t/Makefile.am
- t/scripts/sqlite-query.py
- t/t2250-job-archive.t
- t/t2807-dump-cmd.t
As proposed in #4202, here are dump/restore utilities that walk KVS metadata using the content interface so they can be used when the KVS is not loaded.  They use [libarchive](https://www.libarchive.org/) to support various portable archive formats.
Still playing with these and plan to add tests and man pages but wanted to get this checkpointed.
> add flux-dump and flux-restore

- src/modules/job-manager/Makefile.am
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/validate-duration.c
- t/Makefile.am
- t/t2275-job-duration-validator.t
There are several ways to validate that the requested time limit of a job (as set in the `duration` key of jobspec) will not exceed the current instance lifetime (as set in `R.execution.expiration`). The approach used here is to add  a builtin jobtap plugin which fetches `resource.R` and rejects jobs where the submitted `duration` would exceed any instance `expiration` as set in _R_.
Another possible approach would be to do the validation in the scheduler "feasibility" RPC. But the feasibility RPC is only optionally enabled, and enabling it by default causes lots of tests to break. Also the feasibility plugin is only able to reject jobs when the scheduler is loaded, leaving a gap when the scheduler is unloaded or being reloaded for some reason.
A job validator plugin could also be …
> job-manager: add builtin job duration validator plugin

- src/cmd/builtin/restore.c
- src/modules/kvs/kvs.c
- t/Makefile.am
- t/issues/t4222-kvs-assume-empty-dir.sh
- t/t2807-dump-cmd.t
Problem: The kvs has always assumed an empty directory treeobj
has been stored in the content store, because that is how the first
kvs root was originally initialized.  The introduction of kvs dump / restore
can prune non-referenced objects in the content store, such as the
empty directory treeobj.  This can lead to errors.
Solution: Always store an empty directory object into the content
store when loading the kvs module.
Fixes https://github.com/flux-framework/flux-core/issues/4222
> kvs: always store empty directory object to content store

- src/bindings/python/flux/job/info.py
- src/cmd/top/joblist_pane.c
- src/common/libjob/Makefile.am
- src/common/libjob/job.h
- src/common/libjob/result.c
- src/common/libjob/state.c
- src/common/libjob/strtab.c
- src/common/libjob/strtab.h
- src/common/libjob/test/job.c
- src/modules/job-list/stats.c
- src/modules/job-manager/event.c
- t/job-manager/job-conv.py
- t/stats/stats-immediate.c
This is a small "upgrade" to the interfaces for converting job states to strings that fell out of some other work I was doing.
```c
/* Convert state to string.  'fmt' may be:
* "s" - lower case short name
* "S" - upper case short name
* "l" - lower case long name
* "L" - upper case long name
* This function always returns a valid string, though it may
* be something like "(unknown)".
*/
const char *flux_job_statetostr (flux_job_state_t state, const char *fmt);
```
Identical change here, just to keep interfaces similar
```c
const char *flux_job_resulttostr (flux_job_result_t result, const char *fmt);
```
> libjob: improve flux_job_statetostr(), flux_job_resulttostr() interface

- doc/man1/flux-dmesg.rst
- src/broker/log.c
- src/cmd/builtin/dmesg.c
- src/common/libflux/msg_handler.c
- src/modules/job-manager/alloc.c
- src/modules/job-manager/submit.c
- t/t0009-dmesg.t
- t/t0017-security.t
- t/t2240-queue-cmd.t
Problem: `flux-dmesg(1)` (and associated RPC service) can "follow" broker log messages, but always requires the entire ring buffer to be dumped first.
This PR adds a flag to the RPC to skip dumping the ring buffer, and then adds the `--new` option to `flux-dmesg(1)`:
```
Usage: flux dmesg [OPTIONS...]
Print or control log ring buffer
-C, --clear            Clear the ring buffer
-c, --read-clear       Clear the ring buffer contents after printing
-f, --follow           Track new entries as are logged
-n, --new              Show only new log messages
```
I actually needed this capability in the RPC for work on a `flux-shutdown(1)` command as discussed in #3895, where I thought it would be useful to have an option to show log messages as the …
> flux-dmesg: add --new option, plus logging cleanup

- doc/man1/flux-mini.rst
- src/bindings/python/flux/job/Jobspec.py
- src/bindings/python/flux/resource/ResourceSet.py
- src/bindings/python/flux/resource/Rlist.py
- src/cmd/flux-R.c
- src/cmd/flux-mini.py
- src/common/libjob/jobspec1.c
- src/common/librlist/Makefile.am
- src/common/librlist/match.c
- src/common/librlist/match.h
- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/common/librlist/rnode.c
- src/common/librlist/rnode.h
- src/common/librlist/test/match.c
- src/common/librlist/test/rlist.c
- src/common/librlist/test/rnode.c
- src/modules/job-ingest/schemas/jobspec.jsonschema
- src/modules/job-ingest/schemas/jobspec_v1.jsonschema
- src/modules/sched-simple/sched.c
- t/Makefile.am
- t/jobspec/invalid/constraints_not_object.yaml
- t/python/t0022-resource-set.py
- t/t0026-flux-R.t
- t/t2276-job-requires.t
This PR adds support for resource properties as specified in [RFC 20](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_20.html), along with basic support for [RFC 31](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_31.html) constraints.
Thus far, most of the groundwork has been completed, so I thought I'd post now to allow @dongahn an early comment and synchronization period. Still TODO is to add support for constructing RFC 31 constraints in jobspec from the `flux mini` command line tools (tentative support for selecting resources based on constraints is in sched-simple already), along with associated testing.
In summary, this PR contains the following enhancements:
- support for RFC 20 `properties` key on encode and decode of Rv1 objects
- …
> add support for resource properties

- src/broker/state_machine.c
- t/t0025-broker-state-machine.t
Problem: broker immediately posts "children-none" on entry to STATE_SHUTDOWN, even if it has TBON children.
`state_machine->child_count` is always set to zero on entry to STATE_SHUTDOWN because it hasn't been updated since it was
initialized, when no peers were  online.  There is actually no reason to be saving this value - just call the `overlay_get_child_peer_count()` accessor when the count is needed instead of caching it.
Add a failing test to the broker state machine sharness test script.
This bug means that leaves-to-root rc3 execution has been running without synchronization.  The rc3's effectively all start at the same time across the instance, and upstream could complete before downstream, which violates a primary invariant of our distributed service design.  Most likely what has …
> broker: don't leave shutdown state prematurely

- src/test/checks_run.sh
- src/test/docker/docker-run-checks.sh
Problem: At some point the docker 32bit builder (platform = linux/i386)
stopped setting the i386 personality(2), so uname -m reports x86_64
instead of i686, and thus configure detects an x86_64 target.
Check for a platform of linux/i386 in checks_run.sh and re-invoke the
script under `setarch i386` to force the "correct" uname.
Fixes #4226
> ci: run 32bit build under linux32 personality

- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/job/validator/plugins/require-instance.py
- t/t2110-job-ingest-validator.t
This PR adds a validator plugin which attempts to require that all submitted jobs will result in a new instance of Flux. The idea is that we may not want to allow regular parallel jobs (as submitted by `flux mini run` and `flux mini submit` for example) in a system instance, since this results in potential extra burden on the system instance TBON and KVS.
At first it was thought that admins could just drop a validator plugin into the correct path if this was required, but in the end it seemed like offering a native solution (which also serves as another validator plugin example) was probably wise.
> add 'require-instance' job validator plugin

- doc/Makefile.am
- doc/man5/flux-config-ingest.rst
- doc/man5/flux-config.rst
- doc/man5/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/modules/job-ingest/job-ingest.c
- src/modules/job-ingest/validate.c
- src/modules/job-ingest/validate.h
- src/modules/job-ingest/worker.c
- src/modules/job-ingest/worker.h
- t/Makefile.am
- t/t2111-job-ingest-config.t
This PR adds a TOML config for `job-ingest` module in order to make configuration of validator plugins in the system possible using config files.
`flux config reload` is supported for `ingest.validator.plugins` and `ingest.validator.args`, but it would have been a little too much development to allow disabling the validator on reload, so that is not supported now (and this can be done by reloading the job-ingest module anyway).
> job-ingest: add TOML config 

- etc/rc3
Problem: failures in the rc3 script are not reflected in the instance exit code, so shutdown-related failures could be missed
in test.
The rc3 script previously ran with "#!/bin/bash -e" so any error caused the script to immediately exit, but the "-e" was dropped to address concerns that a premature exit due to a trivial error could prevent the KVS data from being dumped out to stable storage.
Add some logic so that the script runs to completion but any errors that occur are reflected in the script exit code.
> rc3: ensure exit code reflects any errors

- etc/flux.service.in
Problem: the flux service unit file currently creates, chowns,
and chmods `${localstatedir}/lib/flux` for the content.sqlite file
on startup using ExecStartPre, but systemd provides support for
standardized creation of a directory for persistent state.
One notable change is that the old directory was relative to
flux's --prefix and the new one is relative to systemd's.
This will have no effect on system-packaged flux which is the
main use case for execution under systemd.
Also of note: the directory may not be a symbolic link.
If content.sqlite needs to be redirected to a different file
system, a bind mount on `/var/lib/flux `may be used for now;
in the future, we could let this path be configured via TOML.
Since `${STATE_DIRECTORY}` was introduced in systemd v240 and
RHEL 8 is currently …
> flux.service: use StateDirectory for content.sqlite

- doc/man7/flux-broker-attributes.rst
- etc/flux.service.in
- src/broker/state_machine.c
- t/t0025-broker-state-machine.t
Problem:  if rc1 fails, for example, due to a misconfiguration, systemd will restart the broker over and over, filling up logs with useless noise until someone notices and fixes the problem.
If rc1 fails, most likely it is going to fail again on restart.   It seems more appropriate to not restart in this case.
This PR configures a special "don't restart" exit code using  `RestartPreventExitStatus`, and then uses it in place of the rc1 script exit code when rc1 fails, but only when run from systemd.
This was peeled off of work on #3895 - it seemed like it should stand alone for the release notes.
> broker: prevent systemd restart if rc1 fails

- t/t0007-ping.t
- t/t2900-job-timelimits.t
This PR fixes a couple minor test failures:
* ping tests assume short hostname
* timelimit test might fail due to inconsistent Python rounding
> testsuite: fix a couple intermittent test failures

- doc/man1/flux-mini.rst
- src/bindings/python/flux/job/Jobspec.py
- src/bindings/python/flux/resource/Rlist.py
- src/cmd/flux-mini.py
- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/common/librlist/test/rlist.c
- src/modules/sched-simple/libjj.c
- src/modules/sched-simple/libjj.h
- src/modules/sched-simple/sched.c
- t/sched-simple/jj-reader.c
- t/t0022-jj-reader.t
- t/t2110-job-ingest-validator.t
- t/t2700-mini-cmd.t
- t/t2701-mini-batch.t
- t/t2702-mini-alloc.t
This PR adds an `--exclusive` flag in the `flux-mini` set of commands, which only works when `-N, --nodes` is also specified, and sets the `exclusive` key to `true` on the node vertex in jobspec. Support for node exclusive requests is added to sched-simple (mainly for testing), and finally the number of tasks/slots in `flux mini` commands is defaulted to the number of nodes, and the `exclusive` flag enabled, when number of tasks is not otherwise specified on the command line (fixes #4228).
As noted above, the new `--exclusive` flag only works if `-N, --nodes` is also specified. I was having trouble deciding if Jobspec V1 could even support setting the exclusive flag on nodes without also specifying the number of required nodes, though I admittedly didn't spend too much time on it. The …
> support node exclusive allocations

- src/broker/broker.c
- t/scripts/runpty.py
- t/t0014-runlevel.t
- t/t2212-job-manager-plugins.t
While going through some old issues I found one that seemed easy and valuable to fix
* #2032
This PR has the broker check for a tty on stdin when invoking an interactive shell. If there is no tty the broker exits with an error:
```console
$ flux mini run flux start                                                                              
lt-flux-broker: stdin is not a tty - can't run interactive shell               
flux-job: task(s) exited with exit code 1                                      
```
This prevents wasting time when you think an interactive job is taking a long time to start, but really you've forgotten `-o pty`/`-o pty.interactive` or the `--pty` option with `srun`.
There was a little test fallout from this one, and most of my time was actually spent trying to fix …
> broker: emit error when running interactive shell without tty

- src/bindings/python/flux/resource/ResourceSet.py
- src/bindings/python/flux/resource/ResourceSetImplementation.py
- src/bindings/python/flux/resource/Rlist.py
- src/cmd/flux-resource.py
- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/common/librlist/test/rlist.c
- t/flux-resource/list/fluxion.expected
- t/flux-resource/list/missing.expected
- t/flux-resource/list/normal-input.expected
- t/flux-resource/list/null.expected
- t/t2350-resource-list.t
It occurred to me that while we added support for execution target properties in #4236, there was no way to actually query what properties were available from the current instance.
This PR adds some missing calls to the librlist API to make this possible, adds similar methods to the Python `ResourceSet` class, and and finally makes a `{properties}` field available from `flux resource list`. This field is now displayed by default if any properties exist in the current instance:
```console
$ flux resource list
STATE PROPERTIES NNODES   NCORES    NGPUS NODELIST
free                 1        4        0 asp
free xx              1        4        0 asp
free foo,xx          1        3        0 asp
free foo             1        4        0 asp
allocated foo,xx          1        1        0 asp
down …
```
> flux-resource: support properties when listing resources

- src/broker/runat.c
- src/broker/state_machine.c
- src/modules/sched-simple/sched.c
Some logs look more silly now that we're displaying them in the output of `flux-shutdown(1)`.  This PR cleans up a few.
Before:
```
$ sudo flux shutdown
broker.info[0]: cleanup.0: /bin/bash -c flux queue stop --quiet Exited (rc=0) 0.0s
broker.info[0]: cleanup.1: /bin/bash -c flux job cancelall --user=all --quiet -f --states RUN Exited (rc=0) 0.0s
broker.info[0]: cleanup.2: /bin/bash -c flux queue idle --quiet Exited (rc=0) 0.0s
broker.info[0]: cleanup-success: cleanup->shutdown 0.199253s
broker.info[0]: quorum-full: ignored in shutdown
broker.info[0]: quorum-full: ignored in shutdown
broker.info[0]: quorum-full: ignored in shutdown
sched-simple.info[0]: resource update: {"down":"3,5,7"}
broker.info[0]: quorum-full: ignored in shutdown
sched-simple.info[0]: resource update: {"down":"6"} …
```
> broker: clean up shutdown logs

- src/bindings/python/flux/job/Jobspec.py
- src/common/libjob/jobspec1.c
- src/modules/job-ingest/schemas/jobspec.jsonschema
- src/modules/job-ingest/schemas/jobspec_v1.jsonschema
- t/jobspec/invalid/resource_slot_with_zero.yaml
- t/jobspec/invalid_v1/core_count_invalid.yaml
- t/jobspec/invalid_v1/gpu_count_invalid.yaml
- t/jobspec/valid_v1/gpu_count_zero.yaml
When going through old issues I noticed #3275, which seemed like a reasonable and easy fix.
This change allows a count of 0 for core and gpu resources (not sure if core is all that useful, but this addresses the main point of the issue)
> python: allow resource count of 0 in Jobspec v1

- src/broker/exec.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/overlay.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- t/t0005-exec.t
This PR addresses #3202. A simple approach is taken for now: rather than offering configuration, remote subprocess exec requests to rank 0 are always rejected.
It is unlikely that use of `flux exec` or `flux_rexec()` to rank 0 from another broker is a current use case, so this approach was considered the most safe for now.
> broker: reject remote exec requests on rank 0

- doc/man5/flux-config-archive.rst
- etc/rc1
- src/modules/content-files/content-files.c
- src/modules/content-sqlite/content-sqlite.c
- src/modules/job-archive/job-archive.c
- t/t2250-job-archive.t
Per discussion in #4251.
- make `period` required in `job-archive` to make it do its thing
- if `dbpath` is not set, assume a path in `statedir` for job-archive, otherwise error
- in `rc1`, don't load `job-archive` module unless we're rank 0 & `archive.period` has been set
i have one commit below that is purely anal retentive, it can be dropped :-)
> job-archive: use statedir path if dbpath is not set

- src/modules/content-sqlite/content-sqlite.c
Fix an obviously wrong error path.  Embarassing!
> content-sqlite: ensure that module load fails if initialization fails

- NEWS.md
flux-core v0.38.0 is scheduled to be tagged on April 4. This adds release notes to `NEWS.md`.
As usually, feel free to directly push here with any changes or updates.
The changes here assume some pending PRs will be merged before or on Monday.
> NEWS.md: add release notes for flux-core v0.38.0

- src/broker/exec.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/server.h
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
Problem: The flux_subprocess_server_start() function takes
a prefix for setting up server targets.  However the flux_rexec()
function is not configurable on what target should be used to
launch a remote subprocess.  This inconsistency is likely due
to a forgotten design decision / hope from long ago.
Solution: Remove the prefix for server setup and always internally
assume the prefix is "broker".
Fixes #4176
> libsubprocess: remove prefix on server setup

- src/cmd/flux-resource.py
Problem: The `flux resource status` output includes ranks *and* hostnames
in default output, but this just clutters the output, especially when the
ranks idset overflows its column.
Remove the ranks column from default output for a cleaner result.
Fixes #4269
Before:
```
STATUS NNODES RANKS           NODELIST
avail     89 4-13,15-20,22-53,55,57,59-62,64-75,77-88,90-100 fluke[7-16,18-23,25-56,58,60,62-65,67-78,80-91,93-103]
offline      8 14,21,54,56,58,63,76,89 fluke[17,24,57,59,61,66,79,92]
exclude      3 0-2             fluke[1,3,108]
drained      9 3,14,21,54,56,58,63,76,89 fluke[6,17,24,57,59,61,66,79,92]
```
After:
```
STATUS NNODES NODELIST
avail     89 fluke[7-16,18-23,25-56,58,60,62-65,67-78,80-91,93-103]
offline      8 fluke[17,24,57,59,61,66,79,92]
exclude      3 fluke[1,3,108] …
```
> flux-resource: remove ranks from default status output

- doc/man1/flux-resource.rst
- src/cmd/flux-resource.py
- t/flux-resource/list/fluxion-info.expected
- t/flux-resource/list/missing-info.expected
- t/flux-resource/list/normal-input-info.expected
- t/flux-resource/list/null-info.expected
- t/flux-resource/list/properties-info.expected
- t/t2350-resource-list.t
This PR adds a `flux resource info` subcommand as described in #4266.
e.g.
```
grondo@fluke108:~/git/flux-core.git$ src/cmd/flux resource info
101 Nodes, 404 Cores, 0 GPUs
grondo@fluke108:~/git/flux-core.git$ src/cmd/flux resource info -s up
89 Nodes, 356 Cores, 0 GPUs
grondo@fluke108:~/git/flux-core.git$ src/cmd/flux resource info -s down
12 Nodes, 48 Cores, 0 GPUs
```
The implementation is just a thin wrapper around `flux resource list`, i.e. the `sched.resource-status` RPC. I thought at first it would be more appropriate to use the `resource.status` RPC but due to the structure of the code it was much easier to use the scheduler-based call. Therefore, this command won't work if a scheduler is not loaded.
> add flux-resource info subcommand

- t/t2701-mini-batch.t
- t/t2801-top-cmd.t
I was regularly hitting two failures when I did `make -j16 check`.  Here are suggested fixes.
Note, that I sort of "jumped" big on my timeouts / input times.  Could be tweaked lower if people want them to be lower.
> testsuite: fix failing tests on parallel testsuite runs

- src/test/docker/docker-run-checks.sh
This was peeled off of @chu11's PR #4070. It would be convenient to have flux-security v0.6.0 in the official `fluxrm/flux-core` docker images, so figured this would be nice to get in first.
> docker: update default flux-security version to v0.6.0

- src/common/libflux/msg_handler.c
- src/modules/resource/inventory.c
- src/modules/resource/inventory.h
- src/modules/resource/topo.c
- t/t2310-resource-module.t
- t/t3301-system-latestart.t
Now that fluxion has the Rv1 reader (flux-framework/flux-sched#921), it no longer requires the `resource.get-xml` RPC to fetch aggregated hwloc XML for the instance.   This PR removes that RPC and leaves the hwloc XML out of the R<sub>local</sub> :arrow_right: reduction, greatly reducing the amount of data that needs to be moved before the scheduler can be started when resources are dynamically discovered (e.g. under slurm).
This PR is based on top of #4262 (remove `flux-hwloc`)
> resource: stop collecting/reducing hwloc XML 

- src/broker/boot_config.c
- src/broker/brokercfg.c
- src/broker/overlay.c
- src/broker/test/boot_config.c
- src/common/libflux/conf.c
- src/common/libflux/conf.h
- src/common/libflux/conf_private.h
- src/common/libflux/test/conf.c
- src/modules/connector-local/local.c
- src/modules/content-s3/content-s3.c
- src/modules/job-archive/job-archive.c
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/journal.c
- src/modules/job-manager/plugins/perilog.c
- src/modules/resource/resource.c
- t/t0013-config-file.t
Problem: #4165 introduced a common type for returning human readable errors from Flux API calls, but `flux_conf_unpack()` and related functions were not converted.  Furthermore, the file and line structure members in `flux_conf_error_t` are pretty useless after the initial parsing of TOML files since most of the time these functions access the JSON config object and any unpack error would not generate a useful file and line.
Drop the `flux_conf_error_t` type from the API and convert the `flux_conf_*()` functions to use `flux_error_t`.
Update tests and users.
I did not find any users in `flux-sched`, `flux-accounting`, `flux-coral2`, or `flux-pmix` so at least nothing breaks in those projects as a result of this change.
> libflux: convert flux_conf_error_t to flux_error_t

- src/common/libev/LICENSE
- src/common/libev/Makefile.am
- src/common/libev/ev.c
- src/common/libev/ev.h
- src/common/libev/ev_epoll.c
- src/common/libev/ev_iouring.c
- src/common/libev/ev_kqueue.c
- src/common/libev/ev_linuxaio.c
- src/common/libev/ev_poll.c
- src/common/libev/ev_port.c
- src/common/libev/ev_select.c
- src/common/libev/ev_vars.h
- src/common/libev/ev_wrap.h
- src/common/libev/libev.m4
- t/t0016-cron-faketime.t
Problem: libev has undergone some development and bugfixes since the last time we updated our embedded copy.
Update from 4.27 to 4.33.
Changes are:
4.33 Wed Mar 18 13:22:29 CET 2020
- no changes w.r.t. 4.32.
4.32 (EV only)
- the 4.31 timerfd code wrongly changed the priority of the signal
fd watcher, which is usually harmless unless signal fds are
also used (found via cpan tester service).
- the documentation wrongly claimed that user may modify fd and events
members in io watchers when the watcher was stopped
(found by b_jonas).
- new ev_io_modify mutator which changes only the events member,
which can be faster. also added ev::io::set (int events) method
to ev++.h.
- officially allow a zero events mask for io watchers. this should
work with older libev versions as well but was not …
> libev: update to version 4.33

- doc/man5/flux-config-job-manager.rst
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/conf.c
- src/modules/job-manager/conf.h
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/journal.c
- t/t2210-job-manager-events-journal.t
Problem: the job manager has multiple subsystems that consume the TOML configuration object from the broker, but there is no mechanism for them to receive a callback when the configuration changes (e.g. sys admin calls `flux config reload` or `systemctl reload flux`).
To prepare to support a dynamically configurable purge policy in a future PR, this PR introduces a way for job manager subsystems to register a callback for configuration handling:
```c
/* Return value:
*   0=success, one-shot
*  -1=falure (set 'error' but not errno)
*   1=success, continue to invoke callback on config updates
*/
typedef int (*conf_update_f)(const flux_conf_t *conf,
flux_error_t *error,
void *arg);
/* Immediately call 'cb' on current config object, and then on config updates
* as indicated by initial …
```
> job-manager: introduce config callback

- src/cmd/flux-job.c
- src/common/libterminus/client.c
- src/common/libterminus/pty.h
- src/common/libterminus/test/pty.c
- t/t2612-job-shell-pty.t
This PR fixes an issue that can cause `flux job attach` to hang when attaching to an interactive pty and the job gets an exception before the pty client is fully "attached". This occurs specifically when a non-existent command is supplied, for example:
```console
$ flux mini run -o pty.interactive foo
<hang>
```
This PR reworks the `attach_pty()` code so that the attach can be performed asynchronously, and adds an accessor so that the client can query if it is attached yet. When a job exception occurs while the pty is not yet attached, we can avoid the hang by destroying the pty client.
Now the command above no longer hangs:
```console
$ flux mini run -o pty.interactive foo
0.079s: flux-shell[0]: FATAL: task 0 (host eel): start failed: foo: No such file or directory
0.083s: job.exception …
```
> fix hang when job with an interactive pty fails early

- src/bindings/python/flux/util.py
- src/common/libutil/fsd.c
- src/common/libutil/test/fsd.c
- t/python/t0024-util.py
This PR adds support for the `ms` suffix in `fsd_parse_duration(3)` and `fsd_format_duration(3)` now that the changes to [RFC 23](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_23.html) allowing that suffix have been merged. Mainly this is useful when small durations are printed, e.g. in logs:
before
```
parent-none: join->init 3.312e-05s
```
after
```
parent-none: join->init 0.169518ms
```
(Note these were from real examples, so the numbers are not meant to match)
The `ms` suffix may be useful in other situations as well, so it seemed prudent to go ahead and add support for it.
> libutil: support "ms" suffix for Flux Standard Duration

- src/bindings/python/flux/importer.py
- t/t2110-job-ingest-validator.t
Problem: When flux.importer.import_plugins() does not find any
plugins to import, it returns an empty list, but the function should
always return a dict.
Return an empty dict when no plugins are found in import_plugins().
As discovered by @wkharold in #4285
> python: fix return from flux.importer.import_plugins() when no plugins found

- doc/man1/flux-job.rst
- doc/man5/flux-config-job-manager.rst
- doc/test/spell.en.pws
- src/cmd/flux-job.c
- src/modules/job-list/job-list.c
- src/modules/job-list/stats.c
- src/modules/job-list/stats.h
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/job-manager/annotate.c
- src/modules/job-manager/event.c
- src/modules/job-manager/getattr.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/kill.c
- src/modules/job-manager/purge.c
- src/modules/job-manager/purge.h
- src/modules/job-manager/raise.c
- src/modules/job-manager/urgency.c
- t/Makefile.am
- t/t2201-job-cmd.t
- t/t2280-job-memo.t
- t/t2809-job-purge.t
This adds two methods of purging inactive jobs:
One can purge interactively, e.g.
```
$ flux job purge --num-limit=10
purged 90 inactive jobs, 10 remaining
```
or one can configure automatic purging via TOML
```toml
[job-manager]
inactive-age-limit = "7d"
inactive-num-limit = 10000
```
The job manager retains inactive jobs in a hash and places them in a list ordered by the time they became inactive.  When jobs are purged, the entry in the hash is removed along with the corresponding KVS directory.
> job-manager: add inactive job purge capability

- doc/man1/flux-dmesg.rst
- src/cmd/Makefile.am
- src/cmd/builtin/dmesg.c
- t/t0009-dmesg.t
This is a little side branch I've been working on, so I thought I'd go ahead and get it to the point of usefulness today and post it as a PR for comments.
There are times I've wanted to check `flux dmesg` output and compare the time between events, but the default output isn't entirely conducive to that. The timestamps are in ISO 8601 UTC with sub-second precision, and while these can be compared it requires a little bit of mental effort.
In contrast, the Linux `dmesg` command has a nice `-H, --human` mode which displays a human-readable timestamp for every new minute (e.g. `Apr18 12:30`), then a delta for each new message. I've borrowed that approach here (with a slight tweak by default) for `flux-dmesg(1)`.
`flux dmesg -H` displays a date-time timestamp at every new minute, then each …
> flux-dmesg: colorize output and add -H, --human option

- src/broker/state_machine.c
Problem: When a response to the groups.get request for the
broker.online group reports no members, the broker prints a confusing
log message:
```
[  +0.002432] broker[0]: online:  (ranks )
```
Suppress this log message if the groups.get response contains an
empty set for members. This also avoids creating and destroying an
empty hosts string.
> broker: suppress online message with no members

- src/broker/content-cache.c
- src/modules/content-sqlite/content-sqlite.c
- t/t0012-content-sqlite.t
Problem: content.sqlite sets journal_mode=OFF, synchronous=OFF for performance, but we do occasionally see database corruption in the system instance, as noted in #4152.
This PR changes the content-sqlite pragmas to journal_mode=WAL, synchronous=NORMAL which is safer at the expense of some performance.  It also adds metrics to content-sqlite so we can get a window into the performance.   Below is a comparison of performance in both modes while running the throughput test with 32768 jobs.  Job throughput decreased by 23%.  This is likely an acceptable trade-off for the system instance, but perhaps not for single user instances.
Marking as a WIP for now.
**TL;DR**
Snippets from https://www.sqlite.org/pragma.html 
**journal_mode=OFF, synchronous=OFF**
> If the application crashes in the …
> select safer content.sqlite consistency pragmas

- src/broker/content-cache.c
- src/cmd/builtin/content.c
- src/cmd/builtin/dump.c
- src/cmd/builtin/restore.c
- src/common/libcontent/content.c
- src/common/libcontent/content.h
- src/common/libutil/blobref.c
- src/common/libutil/blobref.h
- src/common/libutil/test/blobref.c
- src/modules/content-files/content-files.c
- src/modules/content-s3/content-s3.c
- src/modules/content-sqlite/content-sqlite.c
- src/modules/kvs/kvs.c
- t/kvs/content-spam.c
- t/t0012-content-sqlite.t
- t/t0018-content-files.t
- t/t0024-content-s3.t
- t/t2008-althash.t
This implements the protocol change proposed in flux-framework/rfc#330, in which blobref strings are replaced with the raw hash in content load/store RPCs.  The broker content-cache also now uses hashes instead of blobrefs as the zhashx key.
The RPC wrappers in libcontent were updated, so their users including `flux-content`, `flux-dump`, `flux-restore`, and the KVS module did not really have to change, although some of the libcontent functions were renamed.
One thing that superficially worked before but no longer works at all after this change is modifying the hash algorithm across an instance restart.  If we want to enable a system instance to migrate from sha1 to sha256, a dump/restore will be required and the content back ends will need to treat an attempt to restart under a different …
> content: track RFC 10 protocol changes

- src/modules/job-archive/job-archive.c
- t/t2250-job-archive.t
Following up PR #4294 where `content-sqlite` used safer pragmas, this updates `job-archive` to do the same.
I wasn't entirely sure of the best way to test performance with `job-archive`.  Because it "polls" `job-list` data, there's a non trivial amount of wall clock time dependent on that polling.
So I ended up instrumenting `job-archive` with the following:
```
+    if (clock_gettime (CLOCK_MONOTONIC, &tp_start) < 0)
+        flux_log_error (ctx->h, "clock_gettime start");
while (sqlite3_step (ctx->store_stmt) != SQLITE_DONE) {
/* due to rounding errors in sqlite, duplicate entries could be
* written out on occassion leading to a SQLITE_CONSTRAINT error.
@@ -381,6 +387,10 @@ void job_info_lookup_continuation (flux_future_t *f, void *arg)
goto out;
}
}
+    ctx->total += monotime_since …
```
> job-archive: use safer pragmas

- etc/Makefile.am
- etc/flux.conf
- etc/flux.service.in
- etc/rc1
- etc/rc3
- src/cmd/builtin/shutdown.c
- src/modules/content-files/content-files.c
- src/modules/content-s3/content-s3.c
- src/modules/content-sqlite/content-sqlite.c
- t/Makefile.am
- t/sharness.d/flux-sharness.sh
- t/t0012-content-sqlite.t
- t/t0018-content-files.t
- t/t0024-content-s3.t
- t/t2808-shutdown-cmd.t
- t/t2810-kvs-garbage-collect.t
This adds some logic to rc1 and rc3 to enable offline garbage collection of a system instance using `flux-dump(1)` and `flux-restore(1)`.  If requested by `flux shutdown --gc`, a dump is produced in ${statedir} during shutdown with a RESTORE symlink pointed to it.  On startup, if RESTORE exists, the current backing store is truncated and content is restored from the archive file.  Then the RESTORE symlink is removed.
For example on my test system:
```
$ sudo flux shutdown --gc
flux-shutdown: shutdown will dump KVS (this may take some time)
broker.info[0]: cleanup.0: flux queue stop --quiet Exited (rc=0) 0.0s
broker.info[0]: cleanup.1: flux job cancelall --user=all --quiet -f --states RUN Exited (rc=0) 0.0s
broker.info[0]: cleanup.2: flux queue idle --quiet Exited (rc=0) 0.0s …
```
> flux-shutdown: add --gc garbage collection option

- src/modules/content-sqlite/content-sqlite.c
- t/t2008-althash.t
This PR modifies the schema of the content-sqlite database to use BLOB instead of CHAR(20) as the type for the hash key in the objects table, as discussed in #2795.
Although this is a schema change, it shouldn't cause problems for system instances on upgrade.  The change only affects the command used to create the objects table if does not already exist.  So if the database already has an objects table, it will continue to use CHAR(20).  The next time the database is recreated (for example after `flux shutdown --gc`) the new column type will be used.
There is also some minor test cleanup here.
> use correct type in content-sqlite, misc. content test cleanup

- src/cmd/flux-job.c
Problem: purge usage string uses the wrong name for the
--num-usage option.
Fix usage string.
Fixes #4317
> flux-job: fix purge usage message

- src/bindings/python/flux/uri/resolvers/pid.py
Problem: The fallback PID URI resolver was failing intermittently
during testing due to what was presumed whitespace in the command
string found in /proc/[pid]/stat. Since the /proc/[pid]/stat contents
were split into fields on whitespace, the incorrect field was passed
to int() and an exception thrown, resulting in the inscrutable error:
flux-uri: ERROR: invalid literal for int() with base 10: 'S'
To fix, use a regex instead of simply splitting the contents on
whitespace. This allows whitespace to possibly occur in the command
name, since we now consume everything between parentheses as the
command name.
Fixes #4168
> python: uri: fix intermittent failure of fallback pid resolver

- t/t2607-job-shell-input.t
While testing the patch in #4320, I did hit:
`FAIL: t2607-job-shell-input.t 7 - flux-shell: multiple jobs, each want stdin`
once or twice.  Assuming it was a timeout issue.  Increase the job timeout in this test.
> testsuite: increase test timeout

- README.md
Problem: README does not list libarchive build prerequisite.
Add libarchive to prerequiste table and os-specific package lists.
> README: add libarchive prerequisite

- src/cmd/builtin/overlay.c
- t/t3303-system-healthcheck.t
- t/t3305-system-rpctrack-up.t
While I was working on something recently, I wanted an option like the [pstree(1)](https://linux.die.net/man/1/pstree) `--highlight` option for `flux overlay status` to highlight one or more ranks and their ancestors in the overlay. For example, for the new distributed job-exec module, it would be nice to easily know which ranks handled messages for a job after knowing the job's assigned idset or hostlist.
This PR adds a new `-H, --highlight=TARGETS` to `flux overlay status` which will highlight the given ranks and their ancestors (i.e. the subtree involving TARGETS) in color if color is enabled or via the special characters `<< >>` if not (useful for testing, and also _almost_ as visible as color).
This PR also replaces the `--no-color` option with the more standard `--color=WHEN` option …
> flux-overlay: replace --no-color with --color=WHEN option, add -H, --highlight=TARGETS

- src/bindings/python/flux/job/list.py
- src/cmd/flux-job.c
- src/cmd/flux-pstree.py
- src/modules/job-list/job-list.c
- src/modules/job-list/job-list.h
- src/modules/job-list/job_util.c
- src/modules/job-list/list.c
- t/python/t0010-job.py
- t/t2260-job-list.t
Per discussion in #4313, support a new "all" attribute to get all job-list attrs from a job.
- its much easier than listing / maintaining like 25+ keywords
- has potential benefits when we want to archive all data in 1 big blob
- flexibility for future new attributes and need to update less stuff
side notes:
- i didn't support this in `flux-jobs` as I felt it wasn't necessary
- i pondered ways to make it so we didn't need to maintain a list of attrs in `t/python/t0010-job.py`.  Like hypothetically stick all attrs in a text file and have a script that generates C code / python list.  But I'll leave that for another day. (#3572)
> job-list: support new "all" attribute to get all job attributes

- src/shell/tmpdir.c
- t/t2602-job-shell.t
This PR fixes a couple `TMPDIR` issues discovered recently by @bhatiaharsh, specifically:
* If `TMPDIR` is set to `FLUX_JOB_TMPDIR`, as may be the case when a job is submitted from another job, clear `TMPDIR` instead of trying to reuse and/or create it.
* If `TMPDIR` can't be created, e.g. the parent directory does not exist, do not raise a fatal error. Instead fall back to `/tmp` with a warning.
> shell: improve handling of TMPDIR

- src/modules/job-manager/journal.c
- t/Makefile.am
- t/issues/t4222-kvs-assume-empty-dir.sh
- t/issues/t4331-job-manager-purged-events.sh
Problem: If a job has been purged from the job-manager, events in the journal may still exist for those purged jobs.  They can be sent to journal requestors.
Solution: When a new request is made for the journal, check that the events in the journal are still valid before sending them.
Fixes #4331
> job-manager: do not send purged events

- src/bindings/python/flux/job/info.py
- src/modules/job-list/job_state.c
- src/modules/job-list/job_util.c
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
Problem: The job-list module was inconsistent in its return of
job data to the user.  In some cases, "defaults" were returned
when data was never initialized.  In other cases, the data is
simply not returned to the user.
Solution: Consistently do not return data to the user when it
is not available / not set.  The attributes adjusted are:
name
ntasks
nnodes
ranks
nodelist
expiration
Adjust tests accordingly.
In the Python JobInfo class, set display defaults for name and ntasks.
> job-list: consistently return job attributes

- src/modules/content-sqlite/content-sqlite.c
- t/t0012-content-sqlite.t
Problem: if the content-sqlite database is corrupted, this is typically discovered at runtime when the KVS attempts to load/store a blob, which causes secondary fallout.  It would be better to catch that condition early.
Add the [quick_check](https://www.sqlite.org/pragma.html#pragma_quick_check) sqlite pragma.  Since pragmas are executed before the module enters the reactor, if this check fails, the module load fails, and rc1 aborts before the higher level services are loaded.
This addresses #4338
> content-sqlite: verify database integrity during module load

- doc/man1/flux-keygen.rst
- src/cmd/flux-keygen.c
- src/common/libzmqutil/zap.c
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t3300-system-basic.t
This works on the problem described in #4341, where logs that look like this:
```
2022-05-24T22:40:04.389347Z broker.info[0]: overlay auth picl0 OK
```
are potentially misleading, since `picl0` is the hostname where the cert was generated not the peer that is authenticating.
We change the log slightly so it at least indicates what that name is:
```
2022-05-24T22:40:04.389347Z broker.info[0]: overlay auth cert-name=picl0 OK
```
and then add a `flux keygen --name=NAME` option that lets the certificate name be set to something other than the local hostname.  I was thinking we would recommend the cluster name in the admin guide.
> improve logging of overlay peer authentication

- doc/man3/flux_future_get.rst
- doc/test/spell.en.pws
- src/common/libflux/future.c
- src/common/libflux/test/future.c
- src/common/libkvs/test/kvs_checkpoint.c
Problem: In flux_future_wait_for() the errno EINVAL is returned
when a flux future is not initialized properly.  This errno is
generic and confusing.
Solution: Return EDEADLOCK instead.  Update comments to give
more details on how a hang / deadlock may occur.  Update unit
tests accordingly.
Fixes #4343
> libflux: return better errno in future wait path

- doc/man5/flux-config-exec.rst
- etc/rc1
- src/modules/job-exec/Makefile.am
- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/exec_config.h
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/sdexec.c
- src/shell/shell.c
- t/Makefile.am
- t/system/0002-job-exec-sdexec-basic.t
- t/system/0003-instance-restart.t
- t/t2405-job-exec-sdexec.t
- t/valgrind/valgrind.supp
- t/valgrind/workload.d/job-sdexec
Built on top of #3864.  Hope is that we can add @grondo's `job-shell` reconnect on top of this, then hopefully add a simple test that will allow flux to restart and the job to be "re-attached".
> job-exec: support new sdexec job launch plugin 

- src/common/libeventlog/eventlog.c
- src/common/libeventlog/eventlog.h
- src/common/libeventlog/test/eventlog.c
- src/shell/builtins.c
- src/shell/builtins.h
- src/shell/events.c
- src/shell/events.h
- src/shell/evlog.c
- src/shell/output.c
- src/shell/shell.c
- t/system/0003-instance-restart.t
- t/t9000-system.t
Per discussion in #4070, this fixes a hang in the shell due to reconnects occurring at the wrong time and shell "completion references" never getting cleared.
Note that I created a new callback for when we reconnect, called `reconnect_init()`.  This is presently unused.  I only added it because adding only a `reconnect_cleanup()` callback seemed "unbalanced".  Can nix if people think it should be nixed.  There are things that could be done with a `reconnect_init()` though.  Perhaps we want to re-try writing to an eventlog by caching unconfirmed eventlog writes?  That's just an idea and not for this PR.
This is built on top of #4070.  Note that this is independent of #4255, does not have to go in before / after it.
Note I don't have an issue created for this, b/c it seems weird to create …
> shell: fix reconnect hang

- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/submit.c
- src/modules/job-manager/test/submit.c
- t/t2100-job-ingest.t
Problem: job-ingest posts the submit event, but every other job
event is posted by the job manager. This results in some special
cases in the job manager that can be confusing.
Since job-ingest now waits for the job manager to "approve" each
job before responding to the user, this division of labor is no
longer required.
Have the job manager post the submit event.  Maintain the invariant
that the user does not receive the job ID until the submit event
has been committed to the KVS by deferring the response to job-ingest
until the KVS batch completes.
Impact on submit latency:  latency is increased because job-ingest does
not send its request to the job manager until the jobspec is committed
to the KVS, and now the job manager does not respond until the submit
event is committed to the …
> job-manager: post submit event, instead of job-ingest

- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/test/subprocess.c
Problem: flux_local_exec() did not check if the user supplied
any arguments for execution.  This was not consistent to the
checks supplied by flux_rexec() and can lead to a segfault
internally.
Solution: Add a argument count check identical to the check done
in flux_rexec().  Add a unit test.
Fixes #4347
> libsubprocess: avoid segfault on empty argv

- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/submit.c
- t/t2212-job-manager-plugins.t
- t/t2240-queue-cmd.t
Here are a few job manager/test cleanup commits split off from #4351.    They are  independent of that PR so I thought maybe it's better to submit them separately.
> job-manager: misc cleanup

- doc/man1/flux-mini.rst
- doc/man1/flux-shell.rst
- doc/test/spell.en.pws
- src/common/libsubprocess/local.c
- src/shell/internal.h
- src/shell/shell.c
- src/shell/task.c
- src/shell/task.h
- t/t2602-job-shell.t
This PR makes a slight change in the way the job shell launches tasks so that each task is in its own process group. This allows the shell to use `killpg(2)` (via libsubprocess) when forwarding signals to a job, so that even children of job tasks are delivered a signal. This should result in better cleanup when job tasks call `fork()`, though note that this may affect an existing use case: #3445.
IMO, it makes sense that the job shell would treat tasks similar to the real shell and use process groups to manage sets of tasks. However, since this could break existing users, maybe we need a shell option to disable it?
I'll work on that next since it should be fairly trivial to implement. Then we'll need some tests. I'm thinking `-o nosetpgrp` but if someone has a better idea please let me …
> shell: execute job tasks in their own process group

- t/t2201-job-cmd.t
Problem: Before the test "f58 can use multibyte prefix", the test
script attempts to find a valid utf8 locale using locale -a piped
to grep.  However, if multiple locales match the pattern, then the
UTF8_LOCALE variable used to set LC_ALL is invalid since it will
contain newlines.  This breaks the test on machines with many locales.
Use head(1) to ensure UTF8_LOCALE only contains a single line.
Add a line of debug output to the test in case there are further
problems in the future.
Fixes #4359
> t2201-job-cmd.t: fix bug in UTF-8 test

- doc/man1/flux-mini.rst
- src/cmd/flux-job.c
- src/cmd/flux-mini.py
- t/t2274-manager-perilog.t
- t/t2500-job-attach.t
This PR changes `flux job attach` (and thus `flux mini run`) to wait only for the job `finish` event instead of `clean` to avoid unnecessarily waiting in these interactive commands when there is a slow job epilog or some other  delay between the finish and clean events.
A new `--wait-event` option is added to `flux job attach` and exposed in `flux mini run`. `flux mini run --wait-event=clean ...` will restore the current behavior for example.
> wait for 'finish' instead of 'clean' event in flux-mini run and flux-job attach

- doc/man1/flux-kvs.rst
- src/cmd/flux-kvs.c
- src/common/libkvs/kvs_commit.c
- src/common/libkvs/kvs_commit.h
- src/common/libkvs/test/kvs_commit.c
- t/kvs/fence_api.c
- t/t1000-kvs.t
split off from #4348.  A minor helper function and subsequent helper option in kvs commands.  The fact this was missing before seems to be an oversight / we just didn't have the random use case for it and just didn't do it.
> libkvs: add flux_kvs_commit_get_rootref() 

- doc/Makefile.am
- doc/man3/flux_shell_get_hwloc_xml.rst
- doc/man3/index.rst
- doc/manpages.py
- src/modules/resource/topo.c
- src/shell/Makefile.am
- src/shell/affinity.c
- src/shell/info.c
- src/shell/info.h
- src/shell/shell.c
- src/shell/shell.h
- t/shell/plugins/invalid-args.c
Putting up this WIP PR before I head out of town (feel free to add early comments). This is a WIP because it still needs some tests added.
This change significantly speeds up throughput of many simultaneous jobs on systems with many cores like corona. Loading hwloc topology directly appears to be essentially serialized on these systems, so we go from a throughput of 6-8 job/s to 40-50 job/s by avoiding the redundant reload of topology via hwloc.
Loading hwloc topology is also very slow on corona (on the order of 1s), so it should help speed up short-lived jobs as well.
> shell: obtain hwloc XML from enclosing instance

- src/modules/kvs/kvs.c
Problem: When a namespace is not available (ENOTSUP) the kvs
module logs an error.  However, a namespace not available
error can be quite common, such as when the job-info module
transitions reading from a guest namespace to a primary namespace.
These log messages can be excessive in the logs.
Solution: Remove log messages when ENOTSUP is returned to
callers.  Let callers decide if ENOTSUP should be logged or not.
Fixes #4369
> kvs: remove excess logging of ENOTSUP

- src/broker/content-cache.c
- t/Makefile.am
- t/issues/t4378-content-flush-force.sh
- t/issues/t4379-dirty-cache-entries-flush.sh
Fixes for #4378 and #4379.  Decided to try and fix both in one PR b/c they are very tightly integrated with each other.  One requires the other for a regression test, the other sort of doesn't appear without the other.
> broker: content cache corner case corrections

- src/broker/content-cache.c
- t/Makefile.am
- t/issues/t4375-content-flush-hang.sh
Problem: The content.flush target will never respond to a request if a backing store is never loaded.
Solution: Return error with ENOSYS if content.flush cannot be completed.  In addition, return ENOSYS if a content.flush is in progress when the backing store is unregistered.  Add regression test.
Fixes https://github.com/flux-framework/flux-core/issues/4375
> broker: return error in content.flush if no backing store exists 

- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog.t
I noticed this while doing some testing. If only a `[job-manager.epilog]` is configured, without also configuring a `[job-manager.prolog]`, then the epilog does not get initiated by the job manager `perilog.so` plugin.
The problem is that the plugin only subscribes to job events during the prolog handler. So, if a prolog is not configured, this subscription doesn't happen and the `job.event.finish` callback isn't received by the plugin.
The fix is to always subscribe to events in the `job.state.run` callback if either a prolog or epilog action is configured.
> job-manager: fix case where a job manager epilog can't be configured without a prolog

- doc/man1/flux-kvs.rst
- src/cmd/builtin/startlog.c
- src/cmd/flux-kvs.c
- src/common/libkvs/kvs_checkpoint.h
- src/common/libkvs/kvs_commit.h
- src/modules/kvs/kvs.c
- src/modules/kvs/kvstxn.c
- src/modules/kvs/kvstxn.h
- src/modules/kvs/test/kvstxn.c
- t/Makefile.am
- t/kvs/fence_api.c
- t/t1010-kvs-commit-sync.t
Per discussion in #4308.
Thought I'd park this to get any initial thoughts.  I have some very simple tests but could use more, perhaps after I see how coverage is after this PR starts.
- Basically added several states to the "kvs transaction" state machine to do the `content.flush`  and `checkpoint`.  I don't think the code change is shocking.  Perhaps the most interesting refactoring was to change the state machine's "switch" statement into a loop, b/c doing a "fallthrough" between states no longer makes sense with the new states.  Right now it sort of looks weird that the primary state machine is a `while (1)` loop and exits are all based on `break`, `goto`, and `return`.
- Only works with primary namespace, but could work with another namespaces.  We'd just have to come up with a …
> kvs: support FLUX_KVS_SYNC

- src/modules/job-manager/event.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/test/job.c
- t/job-manager/plugins/jobtap_api.c
- t/t2212-job-manager-plugins.t
- t/t2270-job-dependencies.t
Problem: when a job event is posted to a job in the job manager, the "action" for the event might post more events.  Since each event is processed immediately, this can lead to re-entry to the event posting code, and myriad corner cases.
This PR does not switch to a full asynchronous event posting model like the broker's state machine, where events are posted to a queue and always processed in another reactor handler. I went there first and found there was quite a bit of code that assumed that the effects of posting an event are immediate.  Instead this takes a more conservative step: an event queue is added to each job.  Any events that are posted while another event is in progress are added to the queue.  Then when the event is finished, the queue is processed in order.  The queue is …
> job-manager: unwind job event posting recursion

- doc/man1/flux-mini.rst
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- src/modules/job-manager/plugins/dependency-after.c
- t/t2271-job-dependency-after.t
This PR allows jobtap plugins to lookup inactive jobs (where that makes sense). This in turn allows the dependency-after plugin to utilize jobs that are inactive as the antecedent for the various `after*` dependency schemes.
> job-manager: allow dependencies on inactive jobs

- src/modules/content-sqlite/content-sqlite.c
Problem: json objects are packed into a response message without taking a reference and then freed.
Take a reference in the pack call (change o to O).
Fixes #4390
> content-sqlite: fix double free

- doc/man7/flux-jobtap-plugins.rst
- src/modules/job-manager/event.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap-internal.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/alloc-bypass.c
- src/modules/job-manager/plugins/begin-time.c
- src/modules/job-manager/plugins/perilog.c
- src/modules/job-manager/plugins/submit-hold.c
- src/modules/job-manager/plugins/validate-duration.c
- src/modules/job-manager/restart.c
- src/modules/job-manager/submit.c
- t/Makefile.am
- t/job-manager/plugins/args.c
- t/job-manager/plugins/cleanup-event.c
- t/job-manager/plugins/create-event.c
- t/job-manager/plugins/create-reject.c
- t/job-manager/plugins/dependency-test.c
- t/job-manager/plugins/job_aux.c
- t/job-manager/plugins/jobtap_api.c
- t/job-manager/plugins/perilog-test.c
- t/job-manager/plugins/priority-invert.c
- t/job-manager/plugins/priority-wait.c
- t/job-manager/plugins/subscribe.c
- t/job-manager/plugins/test.c
- t/job-manager/plugins/validate.c
- t/t2212-job-manager-plugins.t
This was split off from #4386.
It just adds the job.create, job.destroy jobtap callbacks and related stuff as discussed in #4368.
> jobtap: add job.create, job.destroy callbacks

- src/common/libflux/plugin.c
- src/common/libflux/plugin.h
- src/common/libflux/test/plugin.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap.c
- t/job-manager/plugins/job_aux.c
- t/t2212-job-manager-plugins.t
This PR addresses two problems:
- If a jobtap plugin stores an aux item with a destructor, and the plugin is unloaded before the job is destroyed, the destructor might no longer be resident, leading to a segfault
- now that jobs are kept in memory after transition to inactive, any job aux items are not automatically cleaned up (#4296)
This addresses the first problem by leaking the items if the module that registered them is no longer loaded  (see commit message for further details).  The "solution" presumes that it's unlikely that jobtap plugins are going to be loaded and unloaded on a live system except in test or rare debug siutations where a little leakage is no big deal.
The second problem is addressed by destroying the aux container upon transition to inactive, as suggested by …
> job-manager: ensure job aux items are destroyed safely

- .github/workflows/main.yml
- src/test/create-kvs-dumpfile.sh
This PR adds a script like the one proposed in #4401 to the GitHub workflow. This runs a small workload in the most recent tag and saves the dumpfile to `t/job-manager/dumps/valid` which will cause the dumpfile to get testing during `make check`.
This should, in theory, automatically catch PRs proposed that can't restart the previous tagged version KVS.
The workload here is very minimal, but could be easily extended if needed.
> ci: create kvs dumpfile from previous tag for testing

- src/cmd/flux-exec.c
- src/common/libsubprocess/Makefile.am
- src/common/libsubprocess/command.c
- src/common/libsubprocess/fork.c
- src/common/libsubprocess/fork.h
- src/common/libsubprocess/local.c
- src/common/libsubprocess/posix_spawn.c
- src/common/libsubprocess/posix_spawn.h
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/subprocess.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/exec.c
- src/modules/job-ingest/worker.c
- src/shell/shell.c
- t/job-exec/dummy.sh
- t/t0001-basic.t
- t/t0005-exec.t
This PR started as an experiment to verify a theoretical cause of slow job throughput on systems with many cores. The effect of switching to `posix_spawnp(3)` on even my small home system was significant, so I thought I'd submit more polished changes as a PR.
The changes here introduce an alternate mechanism for launching local subprocesses in libsubprocess. Whenever possible, a this new implementation, which uses `posix_spawn(3)`, is preferred over the existing mechanism. However, libsubprocess will still fall back to fork/exec in cases where `posix_spawn()` will not work, e.g. if the subprocess uses a pre_exec hook or sets a working directory.
The requirement that all subprocesses have a current working directory is then relaxed, so that the cwd can be removed in job-exec and other …
> Add a posix_spawn() implementation to libsubprocess and use it to launch job shells

- .github/workflows/main.yml
- .mergify.yml
- src/modules/job-manager/event.c
- t/job-manager/plugins/dependency-test.c
- t/t2212-job-manager-plugins.t
As noted in #4405, recent changes to how posted events are handled by the job manager broke the addition of dependencies in the `job.state.depend` callback. This PR fixes that issue by avoiding post of the `depend` event if there is a `dependency-add` event queued.
A test is also added, since that was clearly missing coverage. (All the tests apparently used `job.dependency.*` callbacks instead)
Finally, to avoid merging PRs which break flux-accounting, a CI check similar to the existing flux-sched check is added for flux-accounting.
Since this modifies mergify config it will likely need a manual merge.
> job-manager: fix dependency-add from job.state.depend callback

- src/broker/brokercfg.c
- src/modules/connector-local/local.c
- src/modules/content-s3/content-s3.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-manager/getattr.c
- src/modules/job-manager/wait.c
- src/modules/resource/drain.c
- src/modules/resource/exclude.c
- src/modules/resource/exclude.h
- src/modules/resource/inventory.c
- src/modules/resource/inventory.h
- src/modules/resource/resource.c
- src/modules/resource/rutil.c
- src/modules/resource/rutil.h
- src/modules/resource/test/rutil.c
While working on #4383, review comments noted that I did not use `flux_error_t` and `errprintf()` for writing out error messages in the `kvs` module.  It ended up I had copied the style of usage from the `resource` module.
I noticed that style was still used in a number of places, so updated its usage in lots of places.  Hopefully I did not go too overboard and update more than I should have :-|  This was not a super deep audit.
Note that in a few locations the char buf size was larger than the 160 bytes of `flux_error_t` (like 256).  We could make `flux_error_t` larger?  But I suspect the 256 bytes was arbitrarily chosen and unlikely to matter.
> Use flux_error_t and errprintf() over char buf and snprintf()

- doc/man7/flux-jobtap-plugins.rst
- src/common/libutil/errprintf.c
- src/common/libutil/errprintf.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- t/Makefile.am
- t/job-manager/plugins/config.c
- t/t2212-job-manager-plugins.t
Problem: jobtap plugins have no simple way to be notified when TOML configuration changes. 
This adds a `conf.update` callback topic.  It is called 
- when the plugin is initially loaded
- each time `flux config reload` is run
The "proposed" config object is found in the callback input arguments under `conf`.  The plugin may reject the configuration by returning  `flux_jobtap_error()` with a human readable error (preferably calling out the offending TOML section).  If the config is rejected at plugin load time, the plugin load fails, e.g.
```
$ flux jobtap load config.so
flux-jobtap: ERROR: [Errno 22] Error parsing [testconfig]: Object item not found: testconfig
```
or if rejected at config reload time, `flux config reload` fails, e.g.
```
$ flux config reload
flux-config: reload: …
```
> jobtap: add conf.update callback

- src/modules/job-manager/Makefile.am
- src/modules/job-manager/event.c
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/jobspec-default.c
- t/Makefile.am
- t/t2220-job-manager-jobspec-default.t
I wanted to get this posted for early feedback.  It's a new builtin jobtap plugin called `jobspec-default` that parses the policy table described in RFC 33 and can set configured defaults for jobs where they are missing.
For example one could configure
```toml
[policy.jobspec.defaults.system]
queue = "batch"
duration = 3600
```
and if either of those are missing from a job, the defaults are set by posting a `jobspec-update` event.
(Note that a duration of 0 in the submitted jobspec is considered the same as "missing", a quirk of RFC 14).
The `jobspec-update` event is posted from a `job.create` jobtap callback as described in #4368.   The event must be posted early so that `job.validate` can access it, for example to check the correct queue limits if no queue was specified by the user.  If …
> allow configurable defaults for jobspec system attributes

- src/modules/job-manager/event.c
- src/modules/job-manager/event.h
- src/modules/job-manager/job.h
- src/modules/job-manager/submit.c
- t/t2209-job-manager-bugs.t
As described in #4409, this PR fixes the race between eventlog creation in the job manager and job startup by adding a flag which queues events until the initial submit event in the eventlog is committed to the KVS.
Additionally, the event batch timeout is made tunable at runtime via a new `job-manager.set-event-timeout` RPC (much easier to use than a module option), and that is used in a reproducer in the tesuite using @chu11's trick of extending the timeout to 1s.
> job-manager: fix race in job eventlog commit and job shell start

- src/cmd/builtin/dump.c
- t/t2807-dump-cmd.t
This fixes the issue described in #4414 by switching `flux-dump` to use `flux_response_decode_raw()` instead of `flux_msg_get_payload()`, the former of which handles responses with an "empty" payload in the expected way.
An attempt to add the precipitating condition to the tests in `t2807-dump-cmd.t`was also made, though I stumbled around a bit trying to figure out the correct blob counts and description of what is happening in the KVS under the covers for the empty, then appended, key. Please forgive and correct any mistakes therein.
> flux-dump: fix handling of empty blobref value

- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/uri/resolvers/lsf.py
- t/t2802-uri-cmd.t
Though I've gotten this to run for `lalloc` sessions I started with Flux, I'm marking this as work-in-progress until I can test more multi-node allocations and edge cases for error handling.
What I'm most concerned about here is the string parsing logic associated with getting the compute node hostname (see L#54-58). This won't work if Flux doesn't span the entire allocation of a user's compute resources, and may not necessarily resolve broker-0 in the allocation (not sure about this, still working on checking multi-node allocations). If anyone has a better way of doing this that'd be excellent, but we tried `bjobs -json` and several variations of that to no success.
In spite of these limitations, I hope this provides something useful to users that we don't currently have.
> python: add LSF URI resolver plugin

- src/modules/job-info/allow.c
- src/modules/job-info/lookup.c
- t/Makefile.am
- t/issues/t4413-empty-eventlog.sh
- t/t2232-job-info-security.t
Per discussion in #4413, there was a corner case where ENOMEM was returned to a caller when an eventlog was empty.  The ENOMEM came from assumptions that an eventlog can never be empty (RFC18 says that an empty eventlog should be impossible).  Handle several corner cases around this fact.
I decided that since an empty eventlog should be impossible, instead of returning EINVAL, I returned EPROTO.  Right choice?
As a fallout, I updated other code to also return EPROTO if the eventlog was in error.
> job-info: handle invalid eventlog entry errors more carefully

- src/common/librlist/match.c
- t/t2276-job-requires.t
This PR fixes #4424. As suspected, when copying the internal sched-simple rlist for constraint matching, the up/down state of nodes was not preserved. This PR fixes that issue, and adds the unfortunately missing tests that ensure down nodes are not scheduled to jobs that include a constraint.
> sched-simple: fix allocation of down nodes when using constraints

- doc/Makefile.am
- doc/man5/flux-config-kvs.rst
- doc/man5/flux-config.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/modules/kvs/Makefile.am
- src/modules/kvs/kvs.c
- src/modules/kvs/kvs_checkpoint.c
- src/modules/kvs/kvs_checkpoint.h
- src/modules/kvs/kvsroot.h
- src/modules/kvs/kvstxn.c
- src/modules/kvs/kvstxn.h
- src/modules/kvs/test/kvsroot.c
- src/modules/kvs/test/kvstxn.c
- t/Makefile.am
- t/t1011-kvs-checkpoint-period.t
Per discussion in #4301, add a `sync = <time>` option to the KVS, so that the primary kvs namespace can be checkpointed on a regular basis.
> kvs: add defensive checkpoint via sync configuration option

- doc/Makefile.am
- doc/man1/flux-queue.rst
- doc/man1/index.rst
- doc/manpages.py
Problem: flux-queue(1) man page is missing, but this is a useful administrator command.
Add a simple page.
> flux-queue(1): add man page

- doc/man3/flux_respond.rst
- src/common/libflux/response.c
- src/common/libflux/response.h
- src/common/libflux/test/response.c
Problem: if `flux_respond_error()` is called with errnum of 0, no response is sent, which can cause hard to diagnose problems.
Use EINVAL if errnum is zero.
Fixes #3036
> libflux: handle flux_respond_error (errnum=0)

- doc/Makefile.am
- doc/man5/flux-config-policy.rst
- doc/man5/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/common/libjob/Makefile.am
- src/common/libjob/jj.c
- src/common/libjob/jj.h
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/jobspec-default.c
- src/modules/job-manager/plugins/limit-duration.c
- src/modules/job-manager/plugins/limit-job-size.c
- src/modules/sched-simple/Makefile.am
- src/modules/sched-simple/sched.c
- t/Makefile.am
- t/sched-simple/jj-reader.c
- t/t0022-jj-reader.t
- t/t2221-job-manager-limit-duration.t
- t/t2222-job-manager-limit-job-size.t
This adds a plugin that implements general and per-queue limits as described in RFC 33, based on just checking the jobspec against the TOML config.
As I was looking for an issue to reference when posting this, I came across #4309 and realized I dove into this today without remembering the idea of using a dependency like scheme to add/remove limits.  Which was a good idea!  Tomorrow I'll pause this and spend some considering that approach instead.
> job-manager: add limits plugins for duration and job size

- src/modules/job-manager/job-manager.c
- src/modules/job-manager/purge.c
- src/modules/job-manager/restart.c
- src/modules/job-manager/restart.h
- t/t2219-job-manager-restart.t
Problem:  as noted in #4300, the job-manager only writes out the max job ID to the KVS when it is unloading, so despite best efforts to preserve KVS content (e.g. with defensive checkpoints added in #4383) when there is a crash or a failed shutdown, we are in danger of starting from an old max ID value and issuing duplicate job IDs.
This just uses the greater of the checkpoint value or the maximum job ID replayed from the KVS to improve robustness.
Also, since purging can eliminate all jobs in the KVS, we add code to update the checkpoint value in the KVS if  the job matching the current max job ID happens to be purged, as suggested by @grondo.
> job-manager: improve robustness of max job id recovery on restart

- src/broker/broker.c
- src/broker/state_machine.c
- src/cmd/builtin/config.c
- src/cmd/flux-start.c
- src/common/libccan/Makefile.am
- src/common/libccan/ccan/array_size/LICENSE
- src/common/libccan/ccan/array_size/_info
- src/common/libccan/ccan/array_size/array_size.h
- src/common/libccan/ccan/array_size/test/compile_fail-function-param.c
- src/common/libccan/ccan/array_size/test/compile_fail.c
- src/common/libccan/ccan/array_size/test/run.c
- src/common/libflux/message.c
- src/common/libflux/test/reactor.c
- src/common/libidset/Makefile.am
- src/common/libidset/test/idset.c
- src/common/libjob/Makefile.am
- src/common/libjob/result.c
- src/common/libjob/state.c
- src/common/libjob/test/jobspec1.c
- src/common/liboptparse/Makefile.am
- src/common/liboptparse/test/optparse.c
- src/common/libpmi/Makefile.am
- src/common/libpmi/pmi_strerror.c
- src/common/librouter/test/rpc_track.c
- src/common/libsubprocess/Makefile.am
- src/common/libsubprocess/test/cmd.c
- src/common/libutil/test/jpath.c
- src/common/libzmqutil/monitor.c
- t/Makefile.am
- t/request/treq.c
Use of this handy ccan macro seems justified.
It converts expressions like `sizeof (a) / sizeof (a[0])` to `ARRAY_SIZE(a)` and adds some saftey against using the macro on a function parameter or pointer.
Find all the places that idiom is used and use the macro instead.
> use ccan ARRAY_SIZE() macro

- doc/man1/flux-top.rst
- src/cmd/top/keys.c
- src/cmd/top/summary_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
@woodard had requested splitting the flux-top(1) inactive job stats into successful vs failed for easier monitoring of a test workload.
I already had this lying around, so I thought I'd propose it. I think @garlick had something similar but in a different form? We could use that instead, but I could not find it.
This version keeps the default display unless you are connecting to the instance as the owner, then details are displayed by default. In either case, the display can be toggled with the `d` key. The end result is fairly simple:
> flux-top: support split of inactive jobs into completed and failed

- doc/Makefile.am
- doc/man3/flux_open.rst
- doc/manpages.py
- src/bindings/python/flux/core/handle.py
- src/common/libflux/connector.h
- src/common/libflux/handle.c
- src/common/libflux/handle.h
- src/common/libflux/test/handle.c
- src/common/libutil/Makefile.am
- src/common/libutil/errprintf.h
- src/common/libutil/popen2.c
- src/common/libutil/popen2.h
- src/common/libutil/strstrip.c
- src/common/libutil/strstrip.h
- src/common/libutil/test/errprintf.c
- src/common/libutil/test/popen2.c
- src/common/libutil/test/strstrip.c
- src/common/libutil/uri.c
- src/connectors/local/local.c
- src/connectors/loop/loop.c
- src/connectors/shmem/shmem.c
- src/connectors/ssh/ssh.c
- t/t1106-ssh-connector.t
This stack of changes is prereq for some other, much simpler, work, but the addition of `flux_open_ex(3)` seemed like a good place to stop to ensure this new function gets documented in release notes.
Currently, `flux_open(3)` may emit errors to stderr, especially when using the ssh connector, since all errors from `ssh` will go to the current terminal's `stderr`. This can be inconvenient for some users of libflux, since libraries typically aren't expected to write directly to `stderr`.
This PR first augments `popen2()` to allow capture of `stderr` (along with other minor cleanup), adds some other helper functions, then adds a new `flux_open_ex(3)` interface to libflux which takes an optional `flux_error_t` parameter in which errors can be returned to the caller. Then, the `ssh` connector …
> add flux_open_ex(3)

- src/cmd/builtin/proxy.c
- src/cmd/builtin/shutdown.c
- src/cmd/top/joblist_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
- src/common/libutil/uri.c
- src/common/libutil/uri.h
- t/t2801-top-cmd.t
Problem: When recursive top_create() fails due to a `flux_open()` error, e.g. the user cannot access the job's URI, top exits with an error when the intention is just to fall back to the current top instance.
This PR removes some calls to `fatal()` in `top_create()` and instead passes errors back via a `flux_error_t`. On error, a popup dialog is displayed instead of raising a fatal error. The dialog is dismissed after 4s or if any key is pressed.
This PR makes use of `flux_open_ex(3)`, so is based on top of #4450. In addition, the internal `uri_resolve()` function is augmented similarly to `flux_open_ex(3)` so that errors to `stderr` from `popen2()` of `flux uri` are captured.
Example of error popup:
> flux-top: avoid premature exit on recursive top error

- src/cmd/builtin/relay.c
When the ssh connector fails to connect to a remote uri, but the ssh was successfully able to execute `flux-relay`, an error such as the following is displayed
```
flux-relay: local:///tmp/flux-xoZRkf/local-0: Permission denied
```
The `flux-relay` prefix probably isn't all that helpful for users, and may be confusing, since `flux-relay` was only indirectly run as part of the `ssh` connector. Instead it may be more useful to use the hostname as the command prefix. This way, the user is made aware of the host on which the local connection failed e.g
```
fluke89: local:///tmp/flux-xoZRkf/local-0: Permission denied
```
> flux-relay: initialize log prefix to hostname when possible

- src/modules/content-files/content-files.c
- src/modules/content-s3/content-s3.c
- src/modules/content-sqlite/content-sqlite.c
- t/issues/t4379-dirty-cache-entries-flush.sh
Problem: In the content-sqlite, content-files, and content-s3 modules,
the backing module is registered before setup of module services is
complete.  This can cause problems if the broker's content-cache
wants to make calls into the module during registration time.
Solution: Ensure that all setup is complete before registering the
backing module.
Update regression test which would fail with this change.
Fixes https://github.com/flux-framework/flux-core/issues/4456
> content-sqlite,files,s3: register backing module after setup is complete

- doc/Makefile.am
- doc/man1/flux-overlay.rst
- doc/man1/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/broker/overlay.c
- src/cmd/builtin/overlay.c
- src/common/libflux/disconnect.h
Problem: `flux overlay status` is restricted to guests for no particular reason, requiring sys admins to run under sudo.
Make the necessary RPCs available to guest users.
Also, add missing man page, and fix a bug in the `flux overlay disconnect` output (still restricted to instance owner).
> flux-overlay: add man page, open to guest users

- NEWS.md
Here are some provisional release notes for 0.42.0 coming out next week, a bit early, but I was going through the release notes to audit an admin guide pr, and thought may as well!
Push directly here as needed.
> NEWS: prep for 0.42 release

- .github/workflows/main.yml
Unfortunately the dumpfile check in ci didn't work when run against a tag.
This check isn't necessary on a tag anyway, since the tag represents no changes. Let's just skip it.
I'm going to delete the current tag and retag after this is merged.
> ci: skip dumpfile check on release

- src/test/create-kvs-dumpfile.sh
Problem: The create-kvs-dumpfile.sh script doesn't work when the
current commit is a tag because no docker image will exist for
that tag yet.
Do nothing if run on a tag by default.
> create-kvs-dumpfile.sh: do nothing if run on a tag

- .github/workflows/main.yml
This PR (now) fixes a couple issues found when pushing the last flux-core tag:
- There was still one remaining issue with the dumpfile creation step when run on a tag
- The auto-deploy steps seem to trigger when pushing a tag to a fork, not just the flux-framework/flux-core repo
> github: fixes for issues found when pushing a tag

- src/modules/job-list/job_state.c
- t/Makefile.am
- t/issues/t4465-job-list-use-after-free.sh
@grondo and I ran this fix to #4465, which crashed the rank 0 broker on fluke twice this morning.
I'll see if I can come up with a test.  It's a use-after-free so the test may not be a reliable reproducer unless run under valgrind.  That's still probably useful I guess.
Edit: I did confirm that the valgrind test described in the issue (which involves restart from fluke's kvs dump) no longer produces errors with this fix.
> job-list: avoid segfault after job purge

- src/broker/content-cache.c
- src/cmd/builtin/restore.c
- src/common/libkvs/kvs_checkpoint.c
- src/modules/content-files/content-files.c
- src/modules/content-s3/content-s3.c
- src/modules/content-sqlite/content-sqlite.c
- t/t0012-content-sqlite.t
- t/t0018-content-files.t
- t/t0024-content-s3.t
- t/t1010-kvs-commit-sync.t
- t/t1011-kvs-checkpoint-period.t
- t/t2807-dump-cmd.t
As per-requisite support for issue #4267, we will need to route checkpoints through the broker into the content backing modules.
There is a nice chunk of cleanup to do before this can happen, mostly surrounding topic names.  So this is a bit of a pre-requisite PR I'm splitting off from the main PR since it doesn't really do much but touches a lot of lines of code.
Note that in the last commit, there is some code that is "common" and would look like I should add a common function.  But they will be modified shortly so I left them separate.  I could clean that up if desired.
> content-{sqlite,files,s3}: route checkpoint-get and checkpoint-put through broker

- src/cmd/builtin/restore.c
- src/common/libkvs/kvs.h
- src/common/libkvs/kvs_checkpoint.c
- src/common/libkvs/kvs_checkpoint.h
- src/common/libkvs/test/kvs_checkpoint.c
- src/modules/content-sqlite/content-sqlite.c
- src/modules/kvs/kvs.c
- src/modules/kvs/kvstxn.c
- src/modules/kvs/kvstxn.h
- src/modules/kvs/test/kvstxn.c
- t/t2010-kvs-snapshot-restore.t
Problem: The KVS root sequence number isn't persisted across
restarts.  It restarts at zero everytime the KVS module is loaded.
Solution: Add the root sequence number to the checkpoint object, read
it in and initialize the KVS primary namespace to that sequence
number.
Fixes #4446
> kvs: add root sequence number to checkpoint object

- doc/man7/flux-broker-attributes.rst
- etc/flux.service.in
- src/broker/Makefile.am
- src/broker/attr.c
- src/broker/attr.h
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/broker.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/overlay.c
- src/broker/test/topology.c
- src/broker/topology.c
- src/broker/topology.h
- t/t0001-basic.t
Problem: the broker overlay network code assumes a "complete" k-ary tree topology.
This PR prepares the broker to support a custom configured tree topology as discussed in #3799 by removing assumptions about the topology from the overlay code and pushing the details into a new class.   Later, we can add support to that class for setting up trees that are wired any way we like, for example with all interior nodes (overlay message routers) mapped to cluster service nodes that are less likely to be destabilized by running resource intensive user applications.
The most user-visible change here is that the `tbon.fanout` broker attribute has changed:
- it now may be set to a value of 0 on the command line to select a flat topology, regardless of instance size
- it is reset after the topology is …
> refactor broker overlay for topology flexibility

- src/cmd/top/summary_pane.c
Problem: The summary pane detailed breakdown of failed vs complete
jobs computes the failed job count as the sum of failed + cancelled +
timeout jobs, but the failed count reported by the job-list module
already includes timeout and cancelled jobs.
Fix the reporting of the failed job count in flux-top.
Fixes #4478
> top: fix detailed report in summary pane

- t/issues/t4465-job-list-use-after-free.sh
- t/t5000-valgrind.t
This cleans up the test I added for #4465 to respect FLUX_ENABLE_VALGRIND_TEST and load the valgrind suppressions.  The latter is required for the test to pass on aarch64.
I also removed an obsolete environment variable from the mian valgrind test.
> testsuite: misc valgrind cleanup

- doc/man1/flux-mini.rst
- src/cmd/flux-mini.py
- t/t2110-job-ingest-validator.t
- t/t2700-mini-cmd.t
This PR attempts to simplify the `flux-mini` `--setattr` interface by placing keys in `attributes.system` by default (unless the key starts with `system.`, `user.` or `.`), since almost all use cases for `--setattr` are targeting `attributes.system.` anyway.
Also, similar to `--setopt`, if a value is not provided, have it default to `1`. This allows, for example, `attributes.system.prolog.clear-ssd = 1` to be set simply with `flux mini batch --setattr=prolog.clear-ssd` instead of the more cumbersome `flux mini batch --setattr=system.prolog.clear-ssd=1`.
> flux-mini: --setattr: place keys in `attributes.system` by default with and default values to 1

- src/broker/content-cache.c
- src/cmd/builtin/dump.c
- src/cmd/builtin/restore.c
- src/common/libkvs/kvs_checkpoint.c
- src/common/libkvs/kvs_checkpoint.h
- src/common/libkvs/test/kvs_checkpoint.c
- src/modules/kvs/kvs.c
- src/modules/kvs/kvstxn.c
Problem: The kvs_checkpoint functions checkpoint data to the backing
store through the broker's content-cache.  There is no way to
bypass the cache, similar to libcontent's CONTENT_FLAG_CACHE_BYPASS
flag.
Solution: Support a new KVS_CHECKPOINT_FLAG_CACHE_BYPASS, that will
get/put directly to the backing store.  The flag is very similar to
libcontent's CONTENT_FLAG_CACHE_BYPASS flag.
Fixes https://github.com/flux-framework/flux-core/issues/4476
> libkvs: Support KVS_CHECKPOINT_FLAG_CACHE_BYPASS flag

- src/broker/content-cache.c
- t/Makefile.am
- t/issues/t4482-flush-list-corruption.sh
Problem: A dirty cache entry has to potential to be added onto the flush list twice.  This double addition can lead to list corruption.
The observed side effect was a list that was shortened and no longer accurate with respects to the `acct_dirty` counter.  This could lead to hangs with content flush, missed flushes to the backing store, and segfault/memory corruption in the worst case.
Solution: Check if the cache entry is already on the flush list before adding it.
Fixes https://github.com/flux-framework/flux-core/issues/4482
> broker: fix content-cache flush list corruption

- .github/workflows/build-container.yaml
There is a typo in the path to the Dockerfile we missed.
> docker: typo in path to Dockerfile

- doc/man1/flux-jobs.rst
Problem: flux-jobs was missing information about TIMEOUT being
a valid result / status.
Solution: Update documentation accordingly.
Fixes #4498
> doc: add TIMEOUT result to flux-jobs(1)

- src/cmd/flux-job.c
- t/t2260-job-list.t
Problem: flux job list is too easy to confuse with flux-jobs(1),
but the former is a test tool that emits JSON.
Omit the list, list-inactive, and list-ids subcommands from help output.
If output is a tty, assume a human is trying to ingest JSON (blech!)
and throw a fatal error that instructs them to try flux-jobs(1).
Fixes #4497
> flux-job: point users to flux-jobs(1)

- .github/stale.yml
Problem: The stale bot configuration limits the number of actions per
hour to 2, which just draws out the initial pain of marking many old
issues stale.
Update the number of actions per hour to 20.
Also, exempt issues that are part of a Project board.
> github: modify stale-bot config

- t/job-list/job-list-helper.sh
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
So I'm admittedly not sure if the pros outweigh the cons on this.  This was initially going to be just comments to point readers to the tests in `t2900-job-limits`, but as I was skimming things I realized "oh this isn't covered ... and this isn't covered ... and ..." and I slowly started adding things.
The addition of the timed out job to the job list tests is probably racy, which we can add things to try and limit that.
I maybe added too many permutations to the job list filtering tests, which can be whittled down.
Do the pros outweigh the cons?
> testsuite: add timeout job tests

- src/bindings/python/flux/job/list.py
- t/t2800-jobs-cmd.t
Problem: When an invalid username is provided to flux-jobs,
the error message is:
flux-jobs: ERROR: invalid literal for int() with base 10: 'fasdfsdafd'
which is not helpful.
Solution: Improve error message to:
flux-jobs: ERROR: Invalid user fasdfsdafd specified
Update test to check for correct error output message.
> flux-jobs: improve bad username error message

- doc/man1/flux-jobtap.rst
- doc/man7/flux-jobtap-plugins.rst
- src/cmd/flux-jobtap.py
- src/common/libflux/plugin.c
- src/common/libflux/plugin.h
- src/common/libflux/test/plugin.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/jobtap-internal.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/dependency-after.c
- t/t2212-job-manager-plugins.t
- t/t2271-job-dependency-after.t
As described in #4506, this PR adds support for a new `flux jobtap query` subcommand which can fetch extended data about jobtap plugins (currently `name` and `path` by default). Optionally, plugins can register for a `plugin.query` callback topic and add arbitrary data to the response payload. This gives plugins a generic way to export internal state for debugging or other purposes.
As an example implementation, the `dependency-after` plugin is extended to support this interface and adds a `dependencies` key the query response which includes all active dependencies, e.g.:
```
$ flux jobtap query .dependency-after | jq
{
"name": ".dependency-after",
"path": "builtin",
"dependencies": [
{
"id": 500699234304,
"depid": 505581404160,
"type": "after-success",
"description": …
```
> add flux jobtap query subcommand

- t/valgrind/workload.d/job-list
Problem: In commit
ad5cd8bf1d2c2a3e4226d7318683bc08fdae505b
the "flux job list" command will give a warning / error to the user
to use "flux jobs" when the output is a tty.  The valgrind workload
still uses "flux job list", which can lead to errors when running the
valgrind unit tests by hand on the command line.
Solution: Use "flux jobs" instead of "flux job list" in the valgrind
workload.
> testsuite: use flux jobs in valgrind workload

- doc/man1/flux-jobs.rst
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
Now that `job-list.list` supports the `since` and `name` parameters, this PR adds support to `flux-jobs` for these options.
The `--name` option restricts returned jobs to those matching a supplied name, and the `--since=WHEN` option restricts jobs to jobs that became inactive after WHEN. If no other filtering options are supplied, then `--since` implies `-a` (because obviously pending and running jobs will become inactive after any supplied time).
The argument to `--since` supports raw timestamp, (negative) offset in FSD, or anything handled by the `flux.util.parse_datetime()` function (e.g. `yesterday`, `an hour ago`, `last monday`).
Using `flux jobs --since` we can now easily determine which jobs were pending or running since yesterday
```console
$ flux jobs --since=8am,yesterday
``` …
> flux-jobs: add --since=WHEN and --name=NAME options

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- t/t2800-jobs-cmd.t
Problem: Currently the job status outputs "PENDING"
when the job is in the DEPEND or SCHED state and "RUNNING" when the
job is in the RUN or CLEANUP states.  This abstraction of job states
in the job status doesn't give enough detail about what is going
on with a job.
Solution: Update the job status to output the job state when a job
is not inactive.  Output the job result when it is inactive.  In
other words, the list of outputs for the job status is now:
DEPEND, SCHED, RUN, CLEANUP, COMPLETED, FAILED, CANCELED, or TIMEOUT
Update tests for new output accordingly.
Update documentation accordingly.
Fixes #4495
> cmd/flux-jobs: include job state in status output

- src/broker/Makefile.am
- src/broker/content-cache.c
- src/broker/content-cache.h
- src/broker/content-checkpoint.c
- src/broker/content-checkpoint.h
- t/Makefile.am
- t/content/content-helper.sh
- t/t0012-content-sqlite.t
- t/t0018-content-files.t
- t/t0024-content-s3.t
Per a discussion in #4492, there was a mistake in PR #4463 were non-rank 0 brokers did not forward checkpoint RPCs to rank 0.  Instead, they were forwarded to rank 0's backing module.  It has little effect / meaning before the work in #4492, but felt it wise to split it out into its own PR as it solves a specific thing.  I also put some of the work from #4492 into this PR, since it made sense.  Most notably, the movement of the content-checkpoint code out of `content-cache` and into its own `content-checkpoint` files.  
Also added a helper lib for the content tests, b/c I was getting irritated constantly modifying all three content tests all of the time.
> broker: forward content.checkpoint-{get,put} RPCs to rank 0

- src/cmd/Makefile.am
- src/cmd/flux-job.c
- src/common/libjob/Makefile.am
- src/common/libjob/test/unwrap.c
- src/common/libjob/unwrap.c
- src/common/libjob/unwrap.h
- src/shell/Makefile.am
- src/shell/info.c
- t/job-exec/dummy.sh
- t/job-exec/imp.sh
- t/t2230-job-info-lookup.t
- t/t2404-job-exec-multiuser.t
- t/t2602-job-shell.t
This PR is prepares some consumers of jobspec for the possibility that Flux instance may store redacted and/or modified jobspec in the "jobspec" KVS key.
First, a new `flux job info --original` option is added which, when used with the `jobspec` key, fetches and "unwraps" J into jobspec. If the jobspec in the KVS is redacted, this will be the only way to get the originally submitted jobspec.
Similarly, the job shell is modified to fetch and verify J instead of the jobspec from the job-info service.
In order to support decoding J into a jobspec string in two places, a new function `unwrap_string()` is added (to libjob since there didn't seem to be a better place) to avoid cut and pasting the code to unwrap signed data into a NUL terminated string (when built with or without flux-security). …
> fetch J instead of jobspec in the job shell, support flux job info --original jobspec

- etc/rc1
- etc/rc3
- src/broker/content-cache.c
- src/broker/content-checkpoint.c
- src/broker/content-checkpoint.h
- t/Makefile.am
- t/content/content-helper.sh
- t/t0012-content-sqlite.t
- t/t0018-content-files.t
- t/t0024-content-s3.t
- t/t0028-content-backing-none.t
- t/t2807-dump-cmd.t
Per discussion in #4267, always loading the backing module content-sqlite can lead to performance issues, especially for shorter lived single user instances.   Default to not loading a backing module.
- to enable this, cache checkpoint put/get in the broker even when a backing module does not exist.  This allows a number of checkpoint operations to still work even if a backing module isn't loaded.
- update rc1/rc3 to not load the checkpoint module by default
- update systemd service file to default configure loading `content-sqlite`
- update tests that require content-sqlite to specifically configure for it
one possible remaining gotcha is that if the user doesn't set a backing module, they are still allowed to load one and that becomes the backing module.  Dunno if we'd like to support a …
> etc: support content.backing-module=none

- src/broker/content-cache.c
Problem: In the event of content store errors, such as ENOSPC
if the disk is full, error messages are logged to LOG_ERR.  This
does not properly signify the severity of the error, as something
like ENOSPC would mean no data is being backed up to disk.
Solution: Log to LOG_CRIT, to signify the importance of this
issue and the need for it to be resolved.
> broker: log content store errors to LOG_CRIT

- doc/man1/flux-shutdown.rst
- doc/man5/flux-config-kvs.rst
- src/cmd/builtin/shutdown.c
- t/t2808-shutdown-cmd.t
Problem: KVS garbage collection is only done when an administrator runs flux-shutdown and chooses to garbage collect via the --dump or --gc options.
Solution: Support a kvs gc-threshold configuration option.  This configuration will take an integer count of KVS changes (the KVS version number or sequence number).  Once the threshold has been crossed, flux-shutdown will ask the user if they wish to garbage collect.  This offers an easy way for administrators to be reminded of garbage collection on a regular basis.
Fixes https://github.com/flux-framework/flux-core/issues/4311
> kvs: support gc-threshold config 

- doc/man1/flux-mini.rst
- doc/test/spell.en.pws
- src/cmd/flux-mini.py
- t/t2702-mini-alloc.t
This PR adds a new `--bg` option to `flux mini alloc` which causes the program to print a jobid on stdout and exit once the new instance is ready, instead of interactively attaching. This should fix the use case described in #4522 (chose a slightly shorter option name).
With `-v`, the command will log what it is waiting on to stderr:
```console
$ flux mini alloc --bg -n1 -v 
ƒkdmkPjqR:  0.000s: waiting for resources
ƒkdmkPjqR:  0.026s: resources allocated
ƒkdmkPjqR:  0.094s: waiting for instance
ƒkdmkPjqR:  1.255s: ready
ƒkdmkPjqR
```
> flux-mini: add --bg option to flux-mini alloc

- src/connectors/ssh/ssh.c
- t/scripts/tssh
- t/t1106-ssh-connector.t
This is a proposed fix for #3731. I still have to ensure it works for a user with `csh` or `tcsh` and find some way to add a regression test. However, I'm posting as an early WIP to get any feedback.
> fix ssh connector with csh/tcsh shells

- src/cmd/flux-mini.py
Problem: 'flux mini bulksubmit' does not describe itself
accurately when passed the '--help' option.
Fix the help message to more accurately describe usage.
> flux-mini: fix bulksubmit help message

- src/shell/affinity.c
Problem: The job shell uses hwloc_distrib() incorrectly to distribute
cores to tasks when cpu-affinity=per-task is specified, resulting in
strange, uneven distribution of cores to tasks.
Using the source for hwloc-distrib(1) as a reference, distribute cores
to tasks by creating a separate hwloc_obj_t "root" per core in the
current topology, then calling hwloc_distrib() explicitly with those
roots. This seems to force the even distribution of cores to tasks
that is expected.
Fixes #4525
> shell: fix cpu-affinity=per-task

- src/modules/job-list/job_state.c
- src/modules/job-list/job_util.c
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
Problem: job-list does not return nnodes until a job is running.
When a job specifically requests a number of nodes, it may be
useful for job-list to return nnodes so it can be listed in
job listing tools such as flux-jobs.
Solution: If the jobspec specifically lists nodes as a requested
resource, have job-list return nnodes even before it is running.
Fixes https://github.com/flux-framework/flux-core/issues/4530
> job-list: return nnodes if jobspec specifies nodes

- src/shell/shell.c
- t/t2602-job-shell.t
As noted in #4540, setting `FLUX_F58_FORCE_ASCII=1` for a job does not change the encoding of a job output file with `{{id}}` in it. This is because the job shell isn't using the job environment, but the environment of the broker or the that created by the IMP (in multi-user mode).
This PR sets up the job shell to inherit a static list of environment variables from the job environment, starting with `FLUX_F58_FORCE_ASCII`.
Note that this can be fixed in current Flux versions by an addition to the shell `initrc.lua` or `lua.d` (see #4540 for the example). However, it seemed like some environment variables should always be inherited by the shell, so thus this PR.
Fixes #4540
> shell: inherit FLUX_F58_FORCE_ASCII from job environment

- doc/man1/flux-mini.rst
- src/bindings/python/flux/job/Jobspec.py
- src/cmd/flux-mini.py
- t/t2700-mini-cmd.t
This is a request for comments PR (and a WIP) since I'm not sure if this will be an acceptable way to solve #4533. I first made an attempt to add `--tasks-per-node` support to the base `flux mini run,submit` commands and `JobspecV1.from_command()`, but I fear "that way madness lies" and I eventually gave up. Trying to get consistent and expected behavior when trying to mix the existing `--ntasks`, `--nodes`, `--cores-per-task` and new `--tasks-per-node` and `--cores` options was too much for me.
Instead, the approach taken here is to add a new `JobspecV1.per_node()` constructor:
```python
def per_node(
cls,
command,
ncores=None,
nnodes=None,
tasks_per_node=None,
tasks_per_core=None,
gpus_per_node=None,
exclusive=False,
):
"""
Factory function that builds a v1 jobspec from an explicit …
```
> cmd: add "per-resource" allocation options to flux-mini run and submit

- NEWS.md
This is a first cut of release notes for v0.43.0. It assumes #4541 will go in.
As always, feel free to push directly here for corrections and additions.
> NEWS.md: add entry for v0.43.0

- doc/man1/flux-jobs.rst
Problem: The output format of {id.dec} was not documented in flux-jobs(1).
Add it to the list of id output formats.
> doc: document {id.dec} in flux-jobs(1)

- doc/man1/flux-mini.rst
- src/bindings/python/flux/job/Jobspec.py
- t/t2700-mini-cmd.t
This addresses the issues discovered in #4547 
* unhelpful error message when neither `--cores` or `--nodes` are used with other per-resource options in `flux mini`
* unhelpful documentation of `--tasks-per-core`
> flux-mini: improve an error message and documentation for per-resource options

- t/t2315-resource-system.t
This PR fixes an invalid failure in the resource `norestrict` test due to some versions of `hwloc-calc` logging extra lines of data to stdout. Also, support `FLUX_TESTS_LOGFILE` in `t2315-resource-system.t` to make future debugging a little easier.
> testsuite: fix spurious resource norestrict test failures on some version of hwloc

- .github/workflows/build-container.yaml
- etc/docker/Dockerfile.base
spack is still borked w.r.t view copying so I want to try disabling it for now. We will not be able to do multi-stage builds, but having builds will be better than nothing! I added a test here on PR so we can verify it builds before merge, and I can remove that if/when it does! If It still doesn't build, oh spack, why do you anguish me so! :laughing: :sob: 
> Container base: remove view copy

- src/broker/overlay.c
- src/broker/state_machine.c
Problem: there is a lot of garbage to sift through when trying to do a post-mortem on a flux problem by looking at `journalctl -u flux` on the rank 0 node.
Eliminate, rate-limit, and reduce severity of several offending messages.
> improve signal/noise ratio in systemd journal logs

- src/bindings/python/flux/uri/resolvers/lsf.py
Problem: The lsf URI resolver plugin executes `ssh flux uri resolve..` on a compute host during URI resolution, but this may not work if the remote host has a different version of Flux installed as the system instance.
Assume a shared filesystem by default and replace `flux` with the path to the local flux executable by using `shutil.which("flux")`. As with the ssh connector, allow this to be overridden with `FLUX_SSH_RCMD`.
Fixes #4558
> python: uri: use path to current flux executable in lsf resovler

- doc/man1/flux-mini.rst
- src/cmd/flux-mini.py
- t/t2212-job-manager-plugins.t
- t/t2220-job-manager-jobspec-default.t
- t/t2260-job-list.t
- t/t2607-job-shell-input.t
- t/t2700-mini-cmd.t
- t/t2900-job-timelimits.t
As proposed in #4552, this PR changes `flux-mini` so it now refuses to accept a `--time-limit` of less than 300s unless units are explicitly specified. A hopefully helpful error message is displayed instead:
```console
$ flux mini run -t 30 myapp
flux-mini: ERROR: time limit is 30 seconds. Are you sure? Force with "30s".
```
> flux-mini: change default unit for --time-limit to minutes

- doc/man5/flux-config-resource.rst
- src/cmd/flux-R.c
- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/common/librlist/rnode.c
- src/common/librlist/rnode.h
- src/common/librlist/test/rlist.c
- src/modules/resource/inventory.c
- src/modules/resource/resource.c
- t/t0026-flux-R.t
- t/t2315-resource-system.t
After lamenting that configuration of resources via a hand edited _R_ or via use of `flux R encode` was confusing and error prone, @garlick and I had the idea that a simple configuration of resources in the `[resource]` TOML table might be a huge improvement.
This PR introduces support for a `resource.config` array which can be used to configure resources instead of `resource.path` pointing to the system _R_. The format of each entry in `resource.config` is a required `hosts` key pointing to a hostlist of node names to which the entry applies, then optional `cores`, `gpus` (in idset form), and `properties` (an array of properties to assign to `hosts`). It is not an error to specify a hostname more than once - in that case the host is updated not overwritten. E.g.:
```toml …
```
> resource: support configuration of resources in TOML config

- configure.ac
- src/bindings/python/Makefile.am
The `--without-python` flag does not make sense if Flux cannot build without it. This PR tests removing the flag (and if checks) for building the bindings. Discussion in https://github.com/flux-framework/flux-core/pull/4577#issuecomment-1250493250. It could be that we want to keep the flag, but have it only control building the Python wrappers (and not the core logic for getting python working for generating commands, etc.) I'm happy to try both - let me know.
> configure: remove --without-python

- configure.ac
This fixes a quoting error in configure.ac that was missed before #4577 was merged.
> configure.ac: fix error message when running autogen.sh

- src/modules/job-list/Makefile.am
- src/modules/job-list/job-list.c
- src/modules/job-list/job_data.c
- src/modules/job-list/job_data.h
- src/modules/job-list/job_state.c
- src/modules/job-list/job_state.h
- src/modules/job-list/job_util.c
- src/modules/job-list/job_util.h
- src/modules/job-list/list.c
- src/modules/job-list/stats.c
- src/modules/job-list/stats.h
This is a general refactoring PR.                                                                                                           
I actually did some similar refactoring in #4336
I did some similar refactoring in a (now tabled) PR for #4404
@garlick commented on some potential refactoring in #4555                                                                                   
So thus this refactoring, and why I put it in a separate PR.
I could add some unit tests to capture some worst offending failure cases (e.g. like jobspec that is just a curly brace), but didn't given its limited coverage increase.  Some of this is already handled in sharness tests.
> job-list: split out job information into new files                                                                                          

- doc/Makefile.am
- doc/man5/flux-config-policy.rst
- doc/man5/flux-config-queues.rst
- doc/man5/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/job/frobnicator/plugins/constraints.py
- src/broker/brokercfg.c
- t/t2112-job-ingest-frobnicator.t
- t/t2241-policy-config.t
This adds an ingest "frobnicator" plugin (thanks @grondo) that works with the RFC 33 `queues.NAME.requires` spec proposed in flux-framework/rfc#342. The broker policy/queue config validator is also modified to allow `queues.NAME.requires`.
This was sufficient to get my test system queues working again with this config
```toml
[ingest.validator]
plugins = ["feasibility", "jobspec" ]
[ingest.frobnicator]
plugins = [ "defaults", "constraints" ]
[[resource.config]]
hosts = "picl[0-7]"
cores = "0-3"
[[resource.config]]
hosts = "picl[1-5]"
properties = ["batch"]
[[resource.config]]
hosts = "picl[6-7]"
properties = ["debug"]
[queues.debug]
requires = [ "debug" ]
[queues.batch]
requires = [ "batch" ]
[policy.jobspec.defaults.system]
queue = "debug"
```
Marked as WIP pending
> ingest: set configured queue constraints

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
This PR adds a way to have format fields in flux-jobs that are optionally completely removed when they render as an empty string for all jobs. So-called "collapsible" fields are indicated in a format  by prepending `?:` before the format, e.g. `?:{name}`. The main use case here is so that we can optionally list jobs queues in the system instance in the default format, but not have this empty, useless field present for all single user instances which are most likely using anonymous queues. E.g.:
```console
$ flux jobs -ao '{id.f58:>12} ?:{exception.type:>16} {nodelist}'
JOBID   EXCEPTION-TYPE NODELIST
ƒEiwyRCb             exec asp
ƒC5m5dL3          timeout asp
ƒ4H3iwEo                  asp
ƒ3uw9ATy                  asp
$ flux jobs -f completed -ao '{id.f58:>12} ?:{exception.type:>16} …
```
> flux-jobs: support collapsible format fields

- doc/man1/flux-mini.rst
- src/cmd/flux-mini.py
- t/issues/t4465-job-list-use-after-free.sh
- t/t2112-job-ingest-frobnicator.t
- t/t2212-job-manager-plugins.t
- t/t2221-job-manager-limit-duration.t
- t/t2222-job-manager-limit-job-size.t
- t/t2260-job-list.t
- t/t2700-mini-cmd.t
- t/t2800-jobs-cmd.t
- t/test-inception.sh
The title says it all. This is just shorthand for `--setattr=queue=NAME`.
Fixes #4437
> flux-mini: add `-q, --queue=NAME` option

- doc/man1/flux-jobs.rst
- doc/test/spell.en.pws
- mypy.ini
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/util.py
- src/bindings/python/flux/utils/README.md
- src/bindings/python/flux/utils/tomli/LICENSE
- src/bindings/python/flux/utils/tomli/__init__.py
- src/bindings/python/flux/utils/tomli/_parser.py
- src/bindings/python/flux/utils/tomli/_re.py
- src/bindings/python/flux/utils/tomli/_types.py
- src/bindings/python/flux/utils/tomli/py.typed
- src/cmd/flux-jobs.py
- t/Makefile.am
- t/sharness.d/flux-sharness.sh
- t/t2800-jobs-config.t
It turns out it wasn't so difficult to reject overrides of internal default formats in the `flux jobs` configuration support.
Unfortunately, I can't re-open #4571, so we'll have to start over here.
This updates #4571 such that any internally defined formats for `flux-jobs` can't be overridden by system or user configuration.
```conf
$ flux jobs 
flux-jobs: ERROR: /home/grondo/.config/flux/flux-jobs.toml: override of builtin format 'default' not permitted
```
It also tentatively adds support for `--format=get-config=NAME` as requested:
```console
$ flux jobs -o get-config=default
[formats.default]
description = "Default flux-jobs format string"
format = "{id.f58:>12} {username:<8.8} {name:<10.10} {status_abbrev:>2.2} {ntasks:>6} {nnodes:>6h} {runtime!F:>8} {nodelist:h}"
```
This feature is …
> flux-jobs: add configurable named formats

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/util.py
- t/t2800-jobs-cmd.t
The `flux-jobs` `!d` conversion specifier converts job timestamps to Python `datetime` objects so that `strftime(3)` format specifiers can be used to generate flexible representations of time. However, a drawback of this is that the `datetime` class' `__format__` method does not support width and alignment specifiers (i.e. `:>20`), which makes it impossible to use with other fields because the placement of the field (and the header) can't be controlled.
This PR introduces a `JobDatetime` class which subclasses `datetime` and replaces the `__format__` method with a version that allows the Python format spec to occur after any time format separated by `::`. The `!d` conversion specifier is then updated to convert to `JobDatetime` instead of `datetime`.
Now this works:
```console
$ flux jobs …
```
> flux-jobs: support width and alignment with `!d` conversion specifier

- doc/man1/flux-jobs.rst
- src/cmd/flux-jobs.py
This PR adds `?:{queue}` to the builtin `default` and `deps` format strings so that a QUEUE column is displayed when job queues are configured.
> flux-jobs: add queue to builtin format strings

- src/cmd/top/joblist_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
- t/t2801-top-cmd.t
This PR simply adds a QUEUE column to `flux-top` when any jobs in the job list have a queue defined.
I thought about adding a `--queue=NAME` option to filter jobs by queue, but this needs more thought since the resource list and job statistics will still apply the entire instance so this may cause more confusion than insight. 
(I'll open a new issue on this so that the original issue tied to our milestone can be closed)
> flux-top: add minimal support for job queues

- doc/man5/flux-config-ingest.rst
- doc/man5/flux-config-queues.rst
- doc/test/spell.en.pws
- src/bindings/python/flux/job/frobnicator/frobnicator.py
- src/bindings/python/flux/job/frobnicator/plugins/defaults.py
- src/modules/job-ingest/pipeline.c
- t/t2112-job-ingest-frobnicator.t
- t/t2221-job-manager-limit-duration.t
- t/t2222-job-manager-limit-job-size.t
Problem: the configuration of queues and jobspec defaults is made more error prone by the need to configure the ingest frobnicator.
Since we know the frobnicator is needed when those other things are configured, just enable if implicitly when those configs are present.  Also, to simplify this, implement a default plugin list that includes `defaults` and `constraints`.
A small bug fix to the defaults plugin is included, and a little bit of test cleanup.
> ingest: enable frobnicator when needed by [queues] or [policy]

- t/t2800-jobs-cmd.t
Problem: An debugging test_done call was left in t2800-jobs-cmd.t, therefore not running any tests after the call.
Remove the errant call.
> testsuite: remove errant test_done call

- src/bindings/python/flux/job/frobnicator/plugins/defaults.py
- t/t2112-job-ingest-frobnicator.t
- t/t2221-job-manager-limit-duration.t
- t/t2222-job-manager-limit-job-size.t
Problem: if queues are configured, but no default queue is configured, and a job is submitted without a queue, the job is ingested and allowed to fail later.
Modify the 'defaults' frobnicator plugin to reject such a job at ingest.
> ingest: require job queue if [queues] are configured

- src/modules/job-info/watch.c
- t/Makefile.am
- t/issues/t4612-eventlog-overwrite-crash.sh
Problem: If an eventlog is illegally overwritten, it can result in the appearance of a "zero length" append.  If a user is watching
this eventlog, this "zero length" append can result in a segfault in the job-info module.
Solution: If a "zero length" append occurs in an eventlog being watched, consider the eventlog malformed and return an error.
Issue https://github.com/flux-framework/flux-core/issues/4612
Side notes: 
EINVAL the best error to return?  I considered EPROTO as well, but that didn't seem quite right.  Open to suggestions.
> job-info: return error on invalid eventlog append

- doc/man5/flux-config-tbon.rst
- src/broker/overlay.c
- t/t0013-config-file.t
Problem: a batch job takes around 20m to notice that a peer has been turned off.
The `tbon.tcp_user_timeout` can be used to tune this value in the system instance, and we encourage that.  But batch jobs get the system default.
Since the system default is probably not suitable for flux _ever_, set our own default.  Let's try 20s.
> broker: reduce tbon.tcp_user_timeout

- src/modules/job-manager/queue.c
- src/modules/job-manager/queue.h
- src/modules/job-manager/restart.c
- t/t2219-job-manager-restart.t
This adds the queue enable/disable state to the job manager KVS checkpoint so that it persists across an instance restat.
This PR is currently based on #4440 (only the most recent 2 commits are part of this PR).
> make queue state persist across instance restart

- doc/man1/flux-start.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/overlay.c
- src/broker/test/topology.c
- src/broker/topology.c
- src/broker/topology.h
- src/cmd/flux-start.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/rset.c
- src/modules/job-exec/rset.h
- src/modules/job-exec/test/rset.c
- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/exception.c
- src/shell/output.c
- src/shell/svc.c
- t/Makefile.am
- t/issues/t4583-free-range-test.sh
- t/t0001-basic.t
- t/t2400-job-exec-test.t
- t/t2701-mini-batch.t
This is a WIP, more of an experiment or proof-of-concept really, to address #4417 and #4573. (So no need for code review just yet, but looking for comments on the general approach.)
I was able to run down what was causing instances started with the experimental `exec.ignore-lost-ranks` to hang around after the rank 0 broker exits. It turns out the Flux instance was exiting normally, but the `output` plugin in the rank 0 job shell was not releasing its "completion reference" because it was still waiting for EOF from the lost shell rank.
This PR adds support for notifying the rank 0 job shell that a shell has been lost (actually through a couple different methods), along with an experimental `shell.lost` plugin callback, which the `output` plugin uses to decrement its internal refcount …
> make child instances resilient to non-critical node failures

- src/modules/job-list/idsync.c
- src/modules/job-list/idsync.h
- src/modules/job-list/job-list.c
- src/modules/job-list/job-list.h
- src/modules/job-list/job_data.c
- src/modules/job-list/job_data.h
- src/modules/job-list/job_state.c
- src/modules/job-list/job_state.h
- src/modules/job-list/list.c
- src/modules/job-list/stats.h
some kruft developed over time, and some circular header / struct dependencies were the most notable.  Bunch of cleanup and resolution to that kruft.  Should make future changes (#4604, #4592) easier.  Note, some future refactoring perhaps coming, but thought this was a good stopping point.
> job-list: remove circular header dependencies

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
This PR follows up the `contextual_info` with a `contextual_time` field. As discussed in #4613, it might be useful to display the job duration when available for pending jobs in the default `flux jobs` output. To allow that feature easily, a new contextual jobinfo property is introduced, `contextual_time`, which displays runtime for jobs that hit the RUN state, but job duration (if set) otherwise. The heading is simply `TIME` as proposed in that issue.
> python: add contextual_time jobinfo field

- t/README.md
I can never remember what to set, so document it in the testsuite README.  Note that in the sharness script it appears setting it to non-empty is fine, but I just documented to set to "t" since that's we seem to do the most in the issues.
> testsuite: document FLUX_TEST_VALGRIND

- src/cmd/flux-jobs.py
This simple PR adds a `flux jobs --format=long` as described in #2627.
Built on top of #4641 since it uses the `contextual_time` field.
Fixes #2627.
> flux-jobs: add --format=long

- doc/man1/flux-mini.rst
Problem: A common use case is for a user to submit a new batch script to the parent instance from within a batch job, but the flux-mini(1) man page doesn't mention how to do this.
Add a note to the flux-mini(1) man page about the flux(1) `--parent` option, which can be used to target the parent instance for any flux command, but is useful here to submit a new batch job from a batch script.
> doc: add note about flux --parent option in flux-mini(1)

- src/modules/job-list/job_data.c
- t/t2260-job-list.t
Problem: Sometimes tasks are listed as a "total" count in the
jobspec.  This case is not parsed by libjj and subsequently
an invalid number of tasks can be returned by job-list.
Add additional parsing to parse this specific case.
Fixes https://github.com/flux-framework/flux-core/issues/4646
Also noticed invalid testing errors in t2260, fixed those up here as well.
> job-list: parse tasks with total count in jobspec

- src/modules/job-manager/jobtap.c
- t/t2212-job-manager-plugins.t
This PR fixes #4645. A `< 0` was inadvertently used to test for failure from a function that returns a pointer. :facepalm: 
I also added @garlick's enhancement to the testsuite.
> job-manager: do not ignore failure to load configured plugins

- NEWS.md
This adds release notes for flux-core v0.44.0, assuming a couple pending, approved PRs will get in.
I tried to add a summary of notable changes at the top, but it may not be quite right. Feel free to force push any and all changes!
> NEWS.md: add release notes for v0.44.0

- src/broker/runat.c
Problem: When the broker launches a non-interactive shell via runat, e.g. when running a script as part of a batch job, and that script is later canceled, the signal is delivered only to the shell which may leave other processes running. This can cause batch jobs to hang after a `flux shutdown` if the batch script is running a command in the foreground. The shell will be terminated, but the command keeps running keeping the stdio file descriptors open so the job shell can't exit.
When the runat subsystem is spawning a shell command, add the subprocess flag FLUX_SUBPROCESS_FLAGS_SETPGRP, so that the shell is run in a new process group. This then causes flux_subprocess_kill(3) to call killpg(2) instead of only signaling the spawned shell.
Note: I believe this fixes hangs in …
> broker: launch non-interactive shells in a new process group

- src/broker/broker.c
- src/broker/runat.c
- src/broker/runat.h
- src/broker/test/runat.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
Problem: On older glibc versions, the setting of the child process group via POSIX_SPAWN_SETPGROUP can be racy.  A call to killpg() immediately after a spawned process is launched may not kill a child process.  In one runat test, this can give the appearance of a hang as a 3600 second sleep call is being waited on.
- support a new flag in libsubprocess to force the use of FORK/EXEC
- refactor runat code to take flags instead of bool for log_stdio
- have runat flags take a flag for forced use for FORK/EXEC
- have test use FORK/EXEC if using older versions of glibc
Fixes https://github.com/flux-framework/flux-core/issues/4657
> broker/test: Fix runat race on older glibc versions

- src/modules/job-ingest/test/job.c
Problem: The job-ingest test_job.t unit test fails if the build environment is not able to sign jobspec -- e.g. if sign-type=munge is configured but the munge daemon is not running. But the purpose of this unit test is not to test flux-security but to test job-ingest interfaces, so forcing failure due to misconfigured environment is not necessary.
Just skip the "guest" tests when the default sign-type is not functional.
(This PR fixes a failure in toss buildfarm, where the munge daemon is not running)
> test: job-ingest: skip guest tests when default sign-type fails

- src/broker/overlay.c
Quick pr for annoying logs seen on fluke during flux-core 0.44.0 upgrade.
> broker: don't log failed CONTROL_DISCONNECT

- src/modules/job-list/idsync.c
- src/modules/job-list/idsync.h
- src/modules/job-list/job_state.c
- src/modules/job-list/list.c
refactor round two, abstract the "idsync" logic better, instead of the logic being spread around and throughout all the code.
> job-list: refactor to abstract "idsync" logic better

- configure.ac
- etc/Makefile.am
- etc/completions/flux.pre
This PR reimplements the existing bash completion script to be much more fully featured. Not _all_ commands have completions after the first level `flux <TAB>` completion, but many of the most common commands have been added (see the file for details). Additionally, some experimental support for completing jobids and queues was added. Also notably, this fixes the problem we had before where the completion was disabling bash filename completion under any command that started with `flux`.
It is difficult to test bash completions except by hand, so these should be considered experimental and there could be lingering issues.
> etc: add functional bash completions

- etc/rc1
Problem: although flux shutdown stops the rank 0 broker in a system instance, the other ranks are immediately restarted by systemd. This means that altering the configuration while flux is "down" may be too late for the brokers that have already restarted but have not yet rejoined the instance.
To avoid confusing people, run flux config reload in rc1 on rank > 0 to ensure it starts with the latest configuration.
Fixes #4663
> rc1: reload configuration on rank > 0

- configure.ac
Problem: commit ee47ced changed the installation path for the flux bash completion file to the result of
pkg-config --variable=completionsdir bash-completion
ignoring `--prefix`. However, this will break `make install` to side install locations, temporary installs, and possibly spack builds since the system bash-completion path is always used.
Set `bashcompdir=${sysconfdir}/etc/bash_completion.d` by default and add a new option `--with-system-bash-completion-dir` for users that want to force installation of the completion file to the system-defined bash-completion path.
Fixes #4666
> build: fix use of system bash-completion dir

- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
This PR moves some code around in `flux.util` and `flux.job.info` to enhance reusability (required for some follow up PRs), including some other cleanup.
In summary:
* The `JobFormatter` and `HeaderFormat` class are embedded in the `JobInfoFormat`class, but these classes are not job specific. Move `JobFormatter` to `flux.util.UtilFormatter` and embed `HeaderFormat` in the more general `OutputFormat` class.
*  Move `JobDatetime`, which is also not really job-specific, to `flux.util.UtilDatetime`, and the `fsd()` function from `flux.job.info` into `flux.util`.
* Move `filter_empty()` to `OutputFormat` and modify its return type to be a new format string instance of an instance of the `OutputFormat` class for reusability.
* Fix a bug in `OutputFormat` constructor when a format string that …
> python: move and rename some classes for reusability

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
Problem: it is hard to develop flux-core locally.
Solution: This addition will allow VSCode users to quickly run (and work in) a development container, defined under .devcontainer in the root, which contains a devcontainer.json file and a Dockerfile that uses the fluxrm/testenv:focal base to quickly pull and
spin up the container. We need the Dockerfile to support a post start command to fix a git security issue, and also add developer tools like formatters, linters, etc. This is a vanilla install, meaning it just will allow for build of the core flux, and as other developers try this out we can easily add other extensions that make the development experience better!
The one sticky bit was with git permissions - if you sign you can't commit from inside the container (no keys) and then …
> Add devcontainer environment for vscode

- src/broker/broker.c
Problem: A broker that supports sending its critical ranks to the parent via the job-exec.critical-ranks RPC can't be launched under an older Flux instance that doesn't support this RPC.
Ignore ENOSYS errors from the job-exec.critical-ranks RPC. It should not be a fatal error if this RPC fails.
Fixes #4679
> broker: ignore ENOSYS from parent job-exec.critical-ranks RPC

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
- src/cmd/flux-resource.py
- t/t2350-resource-list.t
- t/t2800-jobs-cmd.t
This PR (built on #4669) adds a way to request that truncation be indicated in output format strings, and adds that flag to the job `{name}` field for `flux jobs` builtin format strings, and the `{properties}` list for `flux resource list`.
This is a WIP since I haven't yet added any testing since I wanted to make sure the approach was acceptable.
> python: indicate truncation for some fields in flux-jobs and flux-resource

- README.md
Just noticed the flux help output was out of date.
I didn't remove the readthedocs pointer in the helper output to keep it 100% identical, but maybe should remove?
> README: update flux help output

- .github/workflows/main.yml
nodejs 12 actions are being deprecated, so we should update the setup-python action to be latest (v4) that will have the newest version of nodeJS. This will close #4692 
> ci: update setup-python/buildx actions to v4/v2

- doc/man1/flux-config.rst
- src/broker/brokercfg.c
- src/cmd/builtin/config.c
- t/t2113-job-ingest-pipeline.t
- t/t2221-job-manager-limit-duration.t
- t/t2222-job-manager-limit-job-size.t
- t/t2240-queue-cmd.t
- t/t2241-policy-config.t
- t/t2801-top-cmd.t
- t/t2806-config-cmd.t
- t/t2809-job-purge.t
As discussed in #4678, this adds a new `flux config load` subcommand that takes a configuration object on stdin (JSON or TOML) and directly updates the broker.   E.g. you can do stuff like this:
```sh
flux config load <<EOF
tbon.tcp_user_timeout = "2s"
EOF
```
or
```sh
flux config get | jq '.tbon.tcp_user_timeout = "3s"' | flux config load
```
In this PR, the entire config object is replaced with each invocation of `flux config load`, which seems like the safest way to use this in test, since it makes it clear that no config lingers from earlier tests.   A simple extension (perhaps for a future PR?) would be to add an `--update` option to let changes be applied incrementally, e.g.  [json_object_update()](https://jansson.readthedocs.io/en/latest/apiref.html#c.json_object_update) style, …
> flux config: add load subcommand

- doc/man5/flux-config-bootstrap.rst
- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- doc/test/spell.en.pws
- src/bindings/lua/flux-lua.c
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/overlay.c
- src/broker/test/boot_config.c
- src/broker/test/overlay.c
- src/broker/test/topology.c
- src/broker/topology.c
- src/broker/topology.h
- src/connectors/loop/loop.c
- t/issues/t3906-job-exec-exception.sh
- t/issues/t3960-job-exec-ehostunreach.sh
- t/issues/t4583-free-range-test.sh
- t/lua/t0002-rpc.t
- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
- t/t0013-config-file.t
- t/t3302-system-offline.t
- t/t3303-system-healthcheck.t
- t/t3304-system-rpctrack-down.t
- t/t3305-system-rpctrack-up.t
- t/t3306-system-routercrash.t
As discussed in #3799, this adds an optional "parent" key to `[bootstrap]` hosts array entries so that a custom topology can be expressed.  Here's an example from a tiny test cluster:
```toml
hosts = [
{ host = "picl0" },
{ host = "picl[1-2]", parent = "picl0" },
{ host = "picl[3-5]", parent = "picl1" },
{ host = "picl[6-7]", parent = "picl2" },
]
```
```
garlick@picl0:~$ flux overlay status
0 picl0: full
├─ 1 picl1: full
│  ├─ 3 picl3: full
│  ├─ 4 picl4: full
│  └─ 5 picl5: full
└─ 2 picl2: full
├─ 6 picl6: full
└─ 7 picl7: full
```
A larger cluster that preserves the mapping of ranks to hostname suffixes while using non consecutive nodes as routers as might be done in a system with scalable units:
```toml
[[bootstrap.hosts]]
host = "test[0-127]"
[[bootstrap.hosts]]
host = "test[1,64]" …
```
> broker: allow custom topology to be configured

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
Problem: flux lacks a certain cuteness factor.  This limits its potential to be liked by younger HPC users.
Solution: Support the {state_emoji}, {result_emoji}, and {status_emoji} fields, which will output the emojis representing job states
or results respectively.
Fixes #4681
Note, while this was originally brought up as a joke in a discussion, this isn't actually that un-useful.  When listing a bunch of jobs, it may be easier to visually scan for a poop instead of printed text like FAIL.  So I selected emojis based on some visual "scan-ability".
Emoji alignment is difficult, but largely ignored it as it's going to be font and terminal specific.
Let the bike-shedding of emoji choices begin!
> flux-jobs: support emoji output formats

- src/bindings/python/flux/resource/ResourceSet.py
- src/bindings/python/flux/resource/ResourceSetImplementation.py
- src/bindings/python/flux/resource/Rlist.py
- src/cmd/flux-resource.py
- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/common/librlist/test/rlist.c
- t/python/t0022-resource-set.py
- t/t2350-resource-list.t
This PR fixes an embarrassing scaling issue with `flux resource list`. The most severe issue is that `flux-resource`  uses the `ResourceSet.union` method to build up resource sets with matching lines of output. Since the `union` method returns a new resource set on each iteration, this causes an exponential slowdown as the program iterates over all ranks in the returned resource set.
This PR adds an `add` method to librlist and `ResourceSet`, which is like `union` but modifies the target resource set instead of returning a copy. This solves 90% of the issue since NRANKS copy and destroys are now avoided.
The other issue is that lookups by rank in `librlist` is a linear search and this is done frequently in `flux resource` since it iterates over all ranks at least once. To address this …
> flux-resource: fix scalability issues with large sets of resources

- src/cmd/builtin/proxy.c
- t/system/0001-basic.t
Problem: if proxy user is a guest in the Flux instance, `flux_job_submit()` can get confused about job request signing requirements.
For now just don't allow flux-proxy to connect as a guest to an instance, unless `--force` is specified.
Fixes #4648
> flux-proxy: require owner == proxy user

- doc/man1/flux-mini.rst
- src/cmd/flux-mini.py
Not much to see here, this PR just adds a `-x` short option equivalent for `--exclusive` as suggested in #4668
> flux-mini: add -x short option for --exclusive

- src/bindings/lua/flux/shell.lua
- src/bindings/python/flux/job/Jobspec.py
- src/shell/lua.d/mvapich.lua
- src/shell/lua.d/openmpi.lua
- t/t2701-mini-batch.t
- t/t2702-mini-alloc.t
This PR makes a couple changes to support the `mpi=none` job shell option to disable existing MPI shell plugins.
Then, this is made the default for `flux mini alloc` and `flux mini batch`. This prevents unnecessary MPI environment variables from being set in the initial program of subinstances created by these `flux-mini` subcommands. 
Fixes #4671
> support mpi=none shell option and make it the default for `flux mini batch` and `flux mini alloc`

- doc/man7/flux-broker-attributes.rst
- src/broker/test/topology.c
- src/broker/topology.c
- t/t0001-basic.t
I think @trws  suggested we try a binomial tree overlay topology.  This adds an option to play with:
```
$ ./flux start -s16 -o,-Stbon.topo=binomial flux overlay status
0 system76-pc: full
├─ 1 system76-pc: full
├─ 2 system76-pc: full
│  └─ 3 system76-pc: full
├─ 4 system76-pc: full
│  ├─ 5 system76-pc: full
│  └─ 6 system76-pc: full
│     └─ 7 system76-pc: full
└─ 8 system76-pc: full
├─ 9 system76-pc: full
├─ 10 system76-pc: full
│  └─ 11 system76-pc: full
└─ 12 system76-pc: full
├─ 13 system76-pc: full
└─ 14 system76-pc: full
└─ 15 system76-pc: full
```
> broker: support binomial tree topology

- doc/man1/flux-resource.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
- src/cmd/flux-resource.py
- t/Makefile.am
- t/t2311-resource-drain.t
- t/t2350-resource-list.t
- t/t2351-resource-status-input.t
- t/t2352-resource-cmd-config.t
This PR updates `flux resource list`, `status`, and `drain` commands to unify the output format options (all subcommands now take the `-n, --no-header` and `-o, --format=FORMAT` options), adds support for `flux-resource.{toml,yaml,json}` config files as with `flux-jobs(1)`, and makes some other minor improvements.
To get there required a lot of refactoring of some Python classes in `flux.util` for better reusability of `UtilConfig` and `UtilFormat` classes etc. Perhaps that work should be split out into a separate PR, but since it was all in support of the changes to `flux-resource` I've left everything in one big PR for now for the sake of 
Also in this PR, the default output format used by `flux resource drain` with no arguments was improved to be more readable and compact. The old …
> flux-resource: unify output format options, support config files and named formats

- t/system/0001-basic.t
Problem: there is a typo in the flux-proxy test added to t/system/0001-basic.t.
Fix typo.
> testsuite: fix broken proxy system test

- .devcontainer/devcontainer.json
Problem: if we are using the devcontainer to develop Python scripts that use Flux, we cannot take advantage of autocomplete without the Python plugin installed (must be installed in the container) along with having the custom Flux paths included to be seen. This fix will ensure the Python extension is installed, and that all search paths are provided where the module could be (pre and post compile, with preference for installed locations if flux is ultimately built)
Examples (this is newly starting the dev container):
> add devcontainer autocomplete

- doc/man1/flux-job.rst
- src/cmd/flux-job.c
- t/t2201-job-cmd.t
- t/t2202-job-manager.t
- t/t2260-job-list.t
- t/t2261-job-list-update.t
- t/t2800-jobs-cmd.t
I thought I'd throw this implementation up in a PR for comments since it seems to be working.
This PR allows the `flux job cancel`, `flux job raise`, and `flux job kill` subcommands to target multiple jobids per invocation. The ability to set an option message in the free arguments is preserved by stopping the processing of jobids at the first argument that doesn't look like a FLUID, or when the string `--` is encountered. This heuristic could get easily confused if the first word of the message could be interpreted as a jobid, e.g. if it starts with the letter `f` or is a number. The result would be that the command would error on that one jobid, and the message set in the exception note would be missing one or more words. Therefore, it will probably be best practice to use `--` to …
> flux-job: support multiple jobids for `cancel`, `raise`, and `kill`

- .github/workflows/asan.yml
- .github/workflows/build-containers.yaml
- .github/workflows/main.yml
GitHub actions is deprecating the set-output, and it looks like there are a few extra mentions in some of the workflows here! In addition, this fix:
- uses the [action updater](https://github.com/vsoch/action-updater) to bump some of the major actions to their latest versions.
- Also saves the yaml so serves as a spacing / formatting tool too.
The way the updater works is to use major versions for "trusted" actions (e.g., docker/login, checkout) and for all others chooses a release, and a specific commit (and comments with the tag).
> fix action syntax for output and yaml formatting

- src/modules/job-list/job-list.c
- t/Makefile.am
- t/issues/t4711-job-list-purge-inactive.sh
Problem: The handler for the job-purge-inactive event does not check if the requested job ids are inactive.  Purging a non-inactive job id can lead to various issues such as stats miscalculations and (worst case) an assertion could be triggered.
Add check to ensure job is inactive before doing purge.
Fixes #4711
> job-list: ensure purged jobs are inactive

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/stats.py
- src/cmd/flux-jobs.py
- src/modules/job-list/idsync.h
- src/modules/job-list/job-list.c
- src/modules/job-list/job-list.h
- src/modules/job-list/job_state.c
- src/modules/job-list/job_state.h
- src/modules/job-list/stats.c
- src/modules/job-list/stats.h
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
per #4604, get queue specific job stats.  in `flux-jobs`, the `--queue` option can now also select which queue `--stats` outputs.
> job-list: support queue specific stats

- etc/completions/flux.pre
Some options were changed and removed recently without corresponding updates in our bash completion functions. This PR addresses that issue. It also adds tab completion for named formats with `-o, --format=` with `flux resource` and `flux jobs`.
Additionally, some strange behavior with long options was found with an older bash version. The bash-completion initialization function seems to help with that (along with some `COMP_WORDBREAKS` machinations), but we don't yet require bash-completion so only call that project's `_init_completion()` function when it is available.
> etc: update bash completion functions

- src/bindings/python/flux/job/stats.py
- src/modules/job-list/stats.c
- src/modules/job-list/stats.h
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
built on top of #4684 
we had failed, timeout, and canceled counters, but not "successful" for some reason.  Probably some random "what is our current need" decision from long ago.
> job-list: add successful job count stat

- doc/man1/flux-mini.rst
- doc/man1/flux-shell.rst
- doc/test/spell.en.pws
- etc/completions/flux.pre
- src/cmd/flux-mini.py
- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/rlimit.c
- t/Makefile.am
- t/t2603-job-shell-initrc.t
- t/t2615-job-shell-rlimit.t
- t/t2700-mini-cmd.t
Ok, here's a proposed solution to #4743. This PR adds a new `rlimit` shell plugin and corresponding `rlimit` shell option where process soft rlimits and the values to propagate can be set in jobspec. Then, `flux-mini` commands are all extended to add a set of default rlimits to propagate.
A new `--rlimit=RULE` option is added which works similarly to the existing `--env=RULE` option, i.e. if `RULE` starts with a `-` then that name is explicitly excluded from rlimit propagation, otherwise the name is explicitly included, or with `name=value` an value is set. For example, `--rlimit=-*` propagates nothing, `--rlimit=core=1024` sets `RLIMIT_CORE` to `1024` and `--rlimit=-*,core` propagates only the current core rlimit.
I wasn't sure if the `rlimit` key should be directly in …
> propagate process resource limits to jobs

- src/modules/job-list/idsync.c
- src/modules/job-list/job-list.c
- src/modules/job-list/job_data.c
- src/modules/job-list/job_state.c
- src/modules/job-list/list.c
- src/modules/job-list/stats.c
Problem: A number of error logging functions assumed zhashx and zlistx functions set errno and thus flux_log_error() was called to log an error.  However it is not a safe assumption to assume they set errno on error.
Solution: Replace flux_log_error() calls with flux_log() calls after zhashx or zlistx errors.  When necessary, set errno = ENOMOM or remove setting of errno = ENOMEM when it is not necessary to set.
Fixes #4741
> job-list: cleanup error logging, remove excess logging

- NEWS.md
I accidentally merged NEWS.md before updating it to include #4744 which has merge-when-passing set right now.  Whoops!  This tacks on that entry.
> NEWS.md: add one more entry for 0.45.0

- src/shell/rlimit.c
- t/t2615-job-shell-rlimit.t
Problem: The job shell rlimit plugin issues a possibly confusing message when the requested soft limit exceeds the hard limit. Also, the limit is left alone instead of raising the limit as much as possible, which may be more helpful.
Check to see if the requested soft limit exceeds the hard limit and issue an explicit warning that the shell cannot set the requested value and instead will raise the soft limit to the hard limit.
Update a test in the testsuite with new expected error message.
> shell: rlimit: improve handling of limits over hard limit

- .github/workflows/main.yml
This fixes the github workflow that does our auto-release on tags. There was an incorrect key used in the yaml, and also step that wasn't necessary anymore. Also, "upgrades" the softprops/action-gh-release action which was inadvertently downgraded by a recent commit.
Fixes #4751  (though we really won't know until the next tag)
> github: fix automated tag release action

- src/bindings/python/flux/job/stats.py
- src/cmd/flux-jobs.py
- src/modules/job-list/stats.c
- src/modules/job-list/stats.h
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
Following up #4753 for issue #4719, instead of adding a purge timestamp to the job stats, add a count of jobs purged.  Definitely like this approach better.
pro:
- can do purge counts per queue as well as total
- cleaner, not as much refactoring needed to be done in job-list
con:
- modifies default flux-jobs stats output
but overall, I like this better than the prior attempt that I went ahead and added tests thinking this a worthwhile candidate for merging.
> job-list: add inactive purge count to job-list stats

- doc/man1/flux-config.rst
- src/broker/brokercfg.c
- t/t2806-config-cmd.t
broker: allow guests to use config.get RPC
Problem: Flux command line utilities may require access to [policy]
and [queues] TOML config for proper display of limits and queue
resources.
Open the config.get RPC to guests.
> allow guests to access flux configuration

- doc/man1/flux-content.rst
- doc/test/spell.en.pws
- src/broker/content-cache.c
- src/broker/content-checkpoint.c
- src/broker/content-checkpoint.h
- src/cmd/builtin/content.c
- t/t0011-content-cache.t
- t/t0017-security.t
This splits off some broker content service cleanup from #4546, and also adds support to flux-content(1) for "split content" which will be used in tests to be written for #4546 and shouldn't break any existing uses of the command.
> content: cleanup and minor tooling updates

- src/bindings/python/flux/job/list.py
- src/common/libjob/job.h
- src/common/libjob/list.c
- t/Makefile.am
- t/python/t0013-job-list.py
Following up #4757, all of the python list functions return all attributes by default, instead of no entries.  This is the more obvious / expected behavior users should expect.
> python: by default return all attrs in job listing functions

- src/cmd/flux-queue.c
- src/modules/job-manager/queue.c
- t/t2240-queue-cmd.t
- t/t2260-job-list.t
- t/t2302-sched-simple-up-down.t
While working on #4629 found a memory corruption bug that somehow has never caused us any grief :-) (Edit: So far ... )
threw in a whole bunch of other cleanups / minor fixes that I had in my branch too.
> job-manager: fix memory corruption due to json reference counting bug

- doc/python/job_submission.rst
- src/bindings/python/flux/job/__init__.py
- src/bindings/python/flux/job/list.py
- t/python/t0010-job.py
Problem: most users of the Python API (or any API in general) ideally want an intuitive user interface. An early likely interaction is to do a flux.job.submit, and then (for many use cases) the next desire is to get more information about the job. As currently implemented, the user needs to stumble on flux.job.job_list_id and decide to try it, and then further to look at the rpc object returned and figure out they can do get_str and json loads that, OR a less intuitive "get" to do the same. OR they could figure out some interaction with a JobInfo object, which to be frank, I do not see how they would know to go there because it is located in a totally separate place, and requires knowing how to instantiate (and is not just calling an easy function). I think the most ideal solution here, …
> python: add flux.job.get_job

- src/cmd/builtin/uptime.c
- src/cmd/flux-queue.c
- src/modules/job-manager/alloc.c
- t/t2240-queue-cmd.t
- t/t2804-uptime-cmd.t
Problem: The terms enable/disable and start/stop are used interchangeably when referencing if a scheduler can allocate resources or not.
Consistently use the terms start/stop when referring to scheduler allocations being "allowed" vs "not-allowed".  This includes changes to variables, comments, rpc parameters, tool output, and tests.
>  job-manager: use allocation terms consistently

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
- .vscode/c_cpp_properties.json
- .vscode/extensions.json
- .vscode/settings.json
- .vscode/tasks.json
- README.md
- scripts/generate_compile_commands
- src/bindings/lua/Test/More.lua
- src/bindings/python/.style.yapf
- src/test/docker/focal/Dockerfile
New setup for vscode and similar.  The commits and messages provide much more detail, but this builds on the devcontainer setup so we get a pretty full featured semi-IDE with all of flux's paths and idioms working and correctly identifying things.
If and when we get the python linting PR in, it would be good to refactor a bit of this, like to have the dockerfile use the requirements from the top level, and to better integrate the settings that has for flake8 and mypy (they are on in here but not well configured since I didn't want to duplicate all that good work).
> Vscode setup

- src/broker/broker.c
- t/t2701-mini-batch.t
This PR fixes an issue introduced by #4615: When the `broker.mapping` attribute isn't set, the broker can't calculate the instance critical ranks and this is treated as a fatal error when it should not be. This can occur when `-o pmi.clique=none` is used or if `PMI_process_mapping` overflows the PMI max value length.
This PR simply makes an error sending the critical ranks to the upstream job-exec service a non-fatal error.
> broker: fix startup failure when broker.mapping is not set

- configure.ac
- etc/Makefile.am
- etc/flux-taskmap.pc.in
Problem: The pkg-config file for libflux-taskmap is missing.
Add the missing flux-taskmap.pc file.
> add missing taskmap pkg-config file

- src/shell/pmi/pmi.c
- t/t2601-job-shell-standalone.t
- t/t2602-job-shell.t
- t/t2701-mini-batch.t
- t/t3002-pmi.t
As described in #4780, the `pmi.clique=single` shell option doesn't really have any use cases, and since `pmi.clique=pershell` is the default, the only useful `pmi.clique` option is `none`. This PR drops the shell `pmi.clique` option and replaces `pmi.clique=none` with a new, simpler `pmi.nomap` option.
> shell: remove `pmi.clique` option, add `pmi.nomap`

- doc/man1/flux-start.rst
- doc/test/spell.en.pws
- src/broker/boot_config.c
- src/broker/runat.c
- src/broker/runat.h
- src/broker/state_machine.c
- src/cmd/flux-start.c
- src/modules/resource/inventory.c
- src/modules/resource/inventory.h
- src/modules/resource/monitor.c
- src/modules/resource/monitor.h
- src/modules/resource/resource.c
- t/Makefile.am
- t/system/0004-recovery.t
- t/t2315-resource-system.t
- t/t3203-instance-recovery.t
Problem: when a system instance won't start, debugging is a chore.
This adds a `flux start --recovery` mode that _should_ let rank 0 of a system instance be started interactively when something goes wrong with systemd startup, e.g.
```console
$ sudo -u flux ./flux start --recovery
flux@picl0:/nfshome/garlick/proj/flux-core/src/cmd$ 
```
It only works for the system instance right now, since it hardwires the system instance configuration path and doesn't work with PMI bootstrap.
Thought I'd post it to see what people thought before digging in deeper.  It seems like it's happened several times that we try to start Flux after a configuration update or new release, and the first problem we encounter is that the instance won't start.  If there's something in the KVS (like the …
> add flux start --recovery

- .github/workflows/main.yml
Problem: The python linting job fails on ubuntu-latest because python 3.6 is no longer supported.
Use runs-on: ubuntu-20.04 in the python-lint job so that python 3.6 can still be used.
See https://github.com/actions/setup-python/issues/355#issuecomment-1335042510
> ci: revert to ubuntu-20.04 for workflow jobs that fail on ubuntu-latest

- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog.t
This PR is a probable fix for the crash described in #4790. I am not 100% certain of the root cause, since I don't see how the subprocess kill future callback could get called after the subprocess handle is destroyed (the subprocess and kill future are destroyed together when the subprocess or job completes), but ensuring the future is only called once on timeout would have prevented this particular crash (and not destroying the future in this case was definitely a bug)
> broker: fix potential crash after sending SIGKILL to job-manager prolog

- src/broker/broker.c
- src/broker/runat.c
- src/broker/runat.h
- src/broker/test/runat.c
- src/cmd/flux-start.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
- src/modules/job-ingest/worker.c
- t/Makefile.am
- t/issues/t4771-flux-start-bash.sh
This PR nominally solves #4771 while at the same time  avoiding most hangs when the broker fails to detect that an initial program is supposed to be interactive.
The root of the problem is that the broker runs non-interactive initial programs in a separate process group to aid cleanup, but if the child tries to read from the tty it gets SIGTTIN and ends up stopped in what is effectively an uninterruptible state (requires SIGKILL to be terminated). Since the broker currently only treats lack of an argument as an "interactive" shell, `flux start bash` or `flux start <any shell>` causes this behavior.
To fix this issue the broker has to have a good idea of what arguments might specify an interactive shell. So, instead of just checking for `argz == NULL` to detect an interactive shell, the …
> broker: improve detection of interactive shells

- src/broker/boot_pmi.c
- src/common/libpmi/pmi2.h
- src/common/libpmi/simple_client.c
- src/common/libpmi/simple_server.h
- src/common/libpmi/test/pmi_info.c
- src/shell/pmi/pmi.c
- t/t3002-pmi.t
This PR adds the RFC 34 taskmap to the PMI kvs as `flux.taskmap` and changes libpmi to check for this value first before falling back to `PMI_process_mapping` as suggested in #4796. This allows clique size and ranks to be calculated by libpmi even if `PMI_process_mapping` would overflow the 1K maximum value length, as is the case with 128 tasks per node across more than a single node.
> add flux.taskmap to PMI kvs for better cyclic task distribution scalability

- src/common/libhostlist/hostlist.c
- src/common/libhostlist/hostrange.c
- src/common/libhostlist/hostrange.h
- src/common/libhostlist/test/hostlist.c
- src/common/libhostlist/test/hostrange.c
This PR fixes an artificial 8K limit on the return value from `hostlist_encode()` by replacing an internal statically sized buffer with the use of a POSIX memstream to dynamically allocate memory for the encoded result.
Additionally, some unused code is removed.
> libhostlist: fix 8K limit on encoded hostlists

- src/common/librlist/rnode.c
- src/common/librlist/test/rnode.c
- src/common/libutil/xzmalloc.c
- src/common/libutil/xzmalloc.h
I ran code coverage without any unit tests to find libutil and other functions that are used only by their own unit tests.
I thought I'd find a bit more, but it was only a couple functions after all.
> cleanup: remove some unused functions

- README.md
- doc/Makefile.am
- doc/man1/flux-filemap.rst
- doc/man1/flux-mini.rst
- doc/man1/flux-shell.rst
- doc/man1/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/broker/Makefile.am
- src/broker/content-cache.c
- src/broker/content-mmap.c
- src/broker/content-mmap.h
- src/cmd/Makefile.am
- src/cmd/builtin/filemap.c
- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/test/message.c
- src/common/libutil/Makefile.am
- src/common/libutil/fileref.c
- src/common/libutil/fileref.h
- src/common/libutil/hola.c
- src/common/libutil/hola.h
- src/common/libutil/test/fileref.c
- src/common/libutil/test/hola.c
- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/stage-in.c
- t/Makefile.am
- t/t0029-filemap-cmd.t
- t/t2617-job-shell-stage-in.t
This is a redo of #4546 with some proposed better tooling.
To review, the idea was that we could mmap(2) a (possibly large) file into the rank 0 broker, then use the hierarchical scalability properties of the content cache to _pull_ the file to local storage on each node of a job.  The basic functionality is to create the mapping and emit an object that includes some file metadata and an array of blobrefs.  The blobrefs refer to regions of the actual external file - this data does not land in the backing store.   The object can be transferred to a "client" who can then use it to recreate the file through the content cache.
That PR only supported mapping individual files.  I was thinking of a use case like transferring a large file system image.   That worked well, but the tooling was …
> add file broadcast toolset

- src/cmd/flux-job.c
Problem: The finish_mpir_interface() function is not necessary and may cause problems in some paralllel debuggers (verified with TotalView).
Remove this function. Just let flux-job exit at the end of a job to notify the debugger that the job is complete.
Fixes #4797
> flux-job: remove finish_mpir_interface()

- doc/man1/flux-mini.rst
- etc/completions/flux.pre
- src/cmd/flux-mini.py
- t/t2700-mini-cmd.t
Problem: setting the working directory is a common operation, but it is not clear how to do it on the command line.
Add a --cwd option to the flux-mini commands for setting it.
Fixes #4774.
> flux-mini: add --cwd option

- src/cmd/Makefile.am
- src/cmd/builtin/pmi.c
- t/t3002-pmi.t
Problem: when debugging MPI or other parallel launch problems, it is sometimes useful to be able to run a stripped down  PMI client  to verify that at least that level of functionality is working in the failing environment.
I've found myself building the clunky pmi test programs in libpmi for this purpose, when really I wanted something like `mpi_hello` but at the pmi level.  I can imagine it would be useful to be able to suggest that someone try this without requiring them to have a built source tree.
This adds a built-in command that can be run as a parallel job to verify PMI, e.g.
```
$ flux mini run -n32 flux pmi barrier
ƒ4mC1JWT: completed pmi barrier on 32 tasks in 0.001s.
$ flux mini run flux pmi get flux.taskmap
{"version":1,"map":[[0,5,6,1],[5,1,2,1]]}
```
> flux-pmi: add installed PMI test tool

- doc/man1/flux-shell.rst
- doc/test/spell.en.pws
- src/shell/stage-in.c
- t/t2617-job-shell-stage-in.t
Problem: the stage-in plugin cannot specify a global file system as the destination, since the copy always occurs on all shells of the job.
Rename the `stage-in.destdir` option to `stage-in.destination` and allow an optional scope prefix of `global:` (denoting a global file system) or `local:` (denoting a local file system).   If the scope is _global_, the copy is only performed on the first shell.
> shell/stage-in: allow destination scope to be specified

- doc/man1/flux-shell.rst
- doc/test/spell.en.pws
- src/shell/affinity.c
- t/t2604-job-shell-affinity.t
This PR adds a new mode for shell's `cpu-affinity` option which allows users to map specific cpus to tasks using a semicolon separated list. List members can be any of hwloc's supported bitmap formats, including list (like an idset), bitmap (hwloc specific bitmap format) or taskset (taskset hex bitmask format). If less entries exist in the list than tasks on the node, then entries are reused, e.g.:
```console
$ flux mini run -n3 -o cpu-affinity=map:'0-3;0xf,0x0;0xffff000000000' -N1 --exclusive sh -c 'taskset -cp $$'
1: pid 1621419's current affinity list: 32-35
0: pid 1621418's current affinity list: 0-3
2: pid 1621420's current affinity list: 36-51
```
> shell: allow users to map specific cpus to tasks with `map` cpu-affinity option

- NEWS.md
First rough draft of release notes for v0.46.0. I think I've already noted #4776. Feel free to push directly to this branch for any updates or fixes.
I wonder if we want an introductory blurb on this one to at least describe the file broadcast toolset.
> NEWS.md: add release notes for v0.46.0

- src/common/libccan/Makefile.am
- src/common/libccan/ccan/pushpull/LICENSE
- src/common/libccan/ccan/pushpull/_info
- src/common/libccan/ccan/pushpull/pull.c
- src/common/libccan/ccan/pushpull/pull.h
- src/common/libccan/ccan/pushpull/push.c
- src/common/libccan/ccan/pushpull/push.h
- src/common/libccan/ccan/pushpull/pushpull.h
- src/common/libccan/ccan/pushpull/test/run.c
- src/common/libflux/message.c
- src/common/libflux/message_iovec.c
- src/common/libflux/message_private.h
- src/common/libflux/message_proto.c
- src/common/libflux/message_proto.h
- src/common/libflux/message_route.c
Problem: the Flux message PROTO frame (described in [RFC 3](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_3.html)) codec is not self contained.
I came across the CCAN "pushpull" class and it seemed like a good way to clean up the PROTO codec.  Now it just looks like this:
```c
int proto_encode (const struct proto *proto, void *buf, size_t size)
{
char *cp = buf;
size_t len = 0;
fixed_size = size;
push_set_realloc (proto_realloc);
if (!push_u8 (&cp, &len, PROTO_MAGIC)
|| !push_u8 (&cp, &len, PROTO_VERSION)
|| !push_u8 (&cp, &len, proto->type)
|| !push_u8 (&cp, &len, proto->flags)
|| !push_u32 (&cp, &len, proto->userid)
|| !push_u32 (&cp, &len, proto->rolemask)
|| !push_u32 (&cp, &len, proto->aux1)
|| !push_u32 (&cp, &len, proto->aux2)
|| len < size) {
errno = …
```
> libflux/message: cleanup with macros and CCAN pushpull class

- src/common/Makefile.am
Problem: Commit 90d4af5fdd357d180dafa7ed101e8b99896a0962 attempted to fix a race condition during `make install` that could cause relinking of libpmi*.so to fail when used with `make -j`, but the fix wasn't implemented properly and instead the PMI libraries were not installed at all.
The problem with the original fix appears to be that it registers a duplicate rule:
install-fluxlibLTLIBRARIES: $(install-libLTLIBRARIES)
which prevents the _real_ install rule from appearing in Makefile.in. Instead, this fix uses what appears to be proposed in the suggested workaround here:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=7328
which I don't completely understand, but first assigns the rule name to a variable, then uses the variable to make the new rule with a dependency on …
> build: fix installation of libpmi*.so

- t/t2616-job-shell-taskmap.t
Problem: In t2616-job-shell-taskmap.t an expected hostname is compared to `hostname -s` which breaks the test on systems with a fully-qualified hostname.
Drop the `-s` argument to hostname to make the test more reliable.
> testsuite: fix failure on a system with fully-qualified hostname

- NEWS.md
Because of the issue fixed by #4824 (libpmi*.so not installed with `make install`), we need to release a 0.46.1. This PR adds release notes for that version.
> NEWS.md: Add release notes for v0.46.1

- src/common/libtaskmap/taskmap.c
- src/common/libtaskmap/taskmap.h
- src/common/libtaskmap/test/taskmap.c
Problem: flux-pmix needs the taskmap in raw form, without the idset ranges.
Add a flag to trivially generate the raw taskmaps without ranges.   
This will allow some [code](https://github.com/flux-framework/flux-pmix/blob/main/src/shell/plugins/maps.c#L51) over there to just fetch the taskmap directly and encode it without the extra machinations.
> libtaskmap: add TASKMAP_ENCODE_RAW_DERANGED

- doc/man1/flux-mini.rst
- doc/man1/flux-shell.rst
- doc/test/spell.en.pws
- src/shell/pmi/pmi.c
- t/t3002-pmi.t
Problem: there is no way to disable the flux-shell's PMI-1 server, but this may be useful when testing other process manager interfaces like pmix.
Add `-opmi=off` and improve the robustness of the pmi shell plugin option parsing.
> flux-shell: add -opmi=off option

- src/cmd/top/joblist_pane.c
- src/cmd/top/summary_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
- src/modules/sched-simple/sched.c
- t/t2801-top-cmd.t
in preparation for queue support in `flux-top` I would need some extra testing ability.  Wanted to add testing coverage under non-queue circumstances first, but hit some snags, thus this PR resulting in some cleanup, fixes to allow easier / more testing, add more tests.
I think the only iffy commit here may be the `test-exit after summary output refreshed` commit.  I admittedly took a very lazy approach to dealing with this.  I felt adding some type of "completion_ref" count system like done in the shell would have been overkill.
> flux-top: add extra test coverage

- src/cmd/top/summary_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
- t/t2801-top-cmd.t
Problem: flux-top does not honor the FLUX_F58_FORCE_ASCII environment variable and outputs ƒ ("fancy-f") all the time.
Output "f" instead of ƒ when FLUX_F58_FORCE_ASCII is set.
Fixes https://github.com/flux-framework/flux-core/issues/4837
Note, I added one dumb test for coverage, borderline maybe isn't even necessary.  Ultimately grepping for ƒ from the `flux-top` was hard given whatever format curses + runpty ultimately put things in.  Grepping for normal-f seemed pointless given there's going to be a bunch of `f` anyways via normal hex output.
> flux-top: honor FLUX_F58_FORCE_ASCII 

- doc/man1/flux-jobs.rst
- doc/man1/flux-top.rst
- src/cmd/flux-jobs.py
- src/cmd/top/top.c
- t/t2800-jobs-cmd.t
- t/t2801-top-cmd.t
per a user request.  Also tweaked the `--color` option to ensure it matched the `--color` option in `flux-dmesg` a bit more.
Note that `-L` option in `flux-dmesg` is already used by `flux-jobs`'s `--level` option, so we're going with `--color` should be allowed, but only `-L` in `flux-dmesg`.
> flux-top: Support --color option

- doc/Makefile.am
- doc/man1/flux-job.rst
- doc/man3/flux_job_timeleft.rst
- doc/man3/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/job/__init__.py
- src/bindings/python/flux/job/timeleft.py
- src/cmd/flux-job.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- t/python/t0010-job.py
- t/t2201-job-cmd.t
This WIP PR proposes a new `flux_job_timeleft(3)` function which fetches the remaining time for the current process, abstracting the implementation from callers because (as we've seen) the determination of _how_ to get the current time left is not exactly straightforward in all situations.
This function doesn't take a jobid but is still placed in libjob with the `flux_job` prefix since only jobs have a duration/expiration, so it doesn't seem to really belong under libflux.
Opening early as a WIP to get feedback (nothing about the interface is set in stone) and to allow @garlick to attempt addition of a `flux timeleft` utility, which can also act as a test vehicle for the function.
> add tools for querying job remaining time: `flux_job_timeleft(3)`, python `flux.job.timeleft()` and `flux-job timeleft`

- src/modules/job-list/job_data.h
- src/modules/job-list/job_state.c
- src/modules/job-list/job_util.c
- t/Makefile.am
- t/issues/t4852-t_submit-legacy.sh
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
Problem: Prior to the introduction of the validate event in
https://github.com/flux-framework/flux-core/commit/9f7aa094e3533cb49c6bbd02c8535e7209aef31e
the t_submit and t_depend timestamps returned by job-list were
identical because the 'submit' timestamp lead to the DEPEND
state transition.  Both attribute names were supported for
convenience.
However, after the introduction of the 'validate' event, these two
values should be different.  t_submit should be associated with the
'submit' event.  t_depend should be associated with the 'validate'
event and transition to the DEPEND state.
This lack of a split between the two values resulted in data
errors for older jobs without a 'validate' event.  Without the
'validate' event job-list would never process that a t_submit/t_depend
timestamp …
>  job-list: separate t_submit / t_depend  calculation

- doc/man1/flux-resource.rst
- doc/test/spell.en.pws
- src/cmd/flux-resource.py
- t/t2315-resource-system.t
- t/t2350-resource-list.t
Per #4765
Just throwing this up here to see if there's any initial feedback.
This is a little tricky to support because:
A) "queue" is not returned from a `sched.resource-status` response ... thus
B) "queue" is not in the ResourceSet that is ultimately constructed from said response and fed into output code
I decided to create a new class currently called "ResourceSetPlusQueue", which just adds a "queue" property on top of "ResourceSet".  You initialize it with the flux configuration, and some logic is done to find queue(s) that meet the property requirements of the resources.
maybe some corner cases still as I haven't written any tests, but thought I'd just throw this up here if there's any initial thoughts on if this approach is sensible.  And maybe I'll come up with a better class name …
> flux-resource: support QUEUE output in resource list

- doc/Makefile.am
- doc/man1/flux-pgrep.rst
- doc/man1/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/cmd/Makefile.am
- src/cmd/flux-pgrep.py
- t/Makefile.am
- t/t2811-flux-pgrep.t
This PR adds a minimal version of `flux-pgrep`/`flux-pkill`. This allows matching and canceling jobs by name and/or jobid range without the more advanced match/constraint syntax proposed in #4849. Once RFC 35 in flux-framework/rfc#360 is approved, then we can extend pgrep to support the more advanced syntax once again.
This version of `flux-pgrep` supports matching a pattern  to job names by default. Due to user request, a jobid range is also supported if the match expression appears as `ID1..ID2`. Since that is also a valid pattern, a name regex can be forced via `name:<pattern>`.
> Add flux-pgrep and flux-pkill 

- doc/man1/flux-queue.rst
- src/modules/job-manager/queue.c
- t/t2219-job-manager-restart.t
- t/t2240-queue-cmd.t
Per #4804, the number of checkpoints to the KVS seems a bit excessive, as it occurs on every change.
Instead, do it only when the user asks to via a `sync` flag.  So that users can say "hey preserve this specific change just in case of catastrophic failure", as well as to help with testing.
I made one additional change that I think is important, when checkpointing in the `job-manager`, make sure that the FLUX_KVS_SYNC flag is set, to ensure the data is on the backing store as well.  Would have slowed things down before, but now that syncs are optional, I think it more than offsets it.
> job-manager: do not checkpoint on every queue state change

- doc/man1/flux-getattr.rst
- doc/man7/flux-broker-attributes.rst
- etc/completions/flux.pre
- src/broker/attr.c
- src/broker/attr.h
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/broker.c
- src/broker/brokercfg.c
- src/broker/content-cache.c
- src/broker/hostname.c
- src/broker/log.c
- src/broker/overlay.c
- src/broker/state_machine.c
- src/broker/test/attr.c
- src/broker/test/boot_config.c
- src/cmd/builtin/attr.c
- src/common/libflux/attr.c
- src/common/libflux/test/attr.c
- t/t0008-attr.t
- t/t0009-dmesg.t
Problem: the broker attribute design is outdated and contains bits that we no longer use.
Cull the broker attribute internal design back a bit so it is perhaps more comprehensible to newcomers.
> clean up little used broker attribute functionality

- src/common/libpmi/upmi.c
- src/common/libpmi/upmi_libpmi.c
- t/t0001-basic.t
Problem: t0001-basic.t "broker.boot-method=single" test fails if a libpmi.so is found that falls through to singleton mode.
Drop the test.  It wasn't doing much.
Fixes issue #4873
> testsuite: drop fragile broker.boot-method test

- src/shell/log.c
- t/shell/plugins/log.c
- t/t2608-job-shell-log.t
Problem: potentially useful shell log messages are lost if the static log buffer size is exceeded.
If the message is too long, truncate it, add a '+', and continue on. Don't treat this as an error.
Fixes #4860
> flux-shell: truncate long log messages

- doc/man1/flux-mini.rst
Problem: The --job-name option is not documented in flux-mini(1)
Document it.
Fixes #4866
> doc: document --job-name in flux-mini(1)

- src/test/docker/bionic/Dockerfile
- src/test/docker/focal/Dockerfile
Problem: On debian based docker containers (bionic, focal), the flux python module is not found by default because
/usr/lib/python3.x/site-packages
is not in the default search path. This is because debian based distributions only search 'dist-packages' instead of 'site-packages'. However, `make install` puts our Flux modules in 'site-packages' because this is the module install directory understood by autotools.
To work around this issue, place a 'site-packages.pth' file in 'dist-packages' to get Python to read site-packages as well as dist-packages.
Fixes #4877
> docker: add site-packages to default python3 path

- doc/man1/flux-keygen.rst
- src/cmd/flux-keygen.c
- t/t0001-basic.t
This adds an option to flux-keygen to set arbitrary metadata in certificates at generation, and override default metadata.
Also it renames some built-in metadata keys with a "keygen." prefix to hopefully make their purpose more clear.
Finally, the versions of flux-core, czmq, zmq, and sodium are added to the certificate.  These might be useful when asking questions like "was this certificate generated by software with a known bug that affects the robustness of the cert?"
> add flux-keygen --meta KEY=VAL option

- doc/man1/flux-top.rst
- src/cmd/top/joblist_pane.c
- src/cmd/top/summary_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
- t/t2801-top-cmd.t
per #4606.  I'm really glad I added that testing in #4833, caught a couple of issues :P
- i assume `--queue` doesn't recursively goto into sub-instances.  Possibly sub-instances may have same queue names setup, but it's not what i think is desired by the `--queue` option.
- right now `flux-top` determines if the "QUEUE" column should be displayed if any jobs have been submitted to any queue.  Maybe this should be changed to just determining if any queues have been configured, i.e. if `queue.*` actually is configured?  While what is implemented is perhaps more "correct", its heavier weight and not sure its really needed except outside of testing scenarios (i.e. queue configuration changed between job submissions).  But for the time being I left it in.
- will probably have to add support in …
> flux-top: limit jobs and summary to specific queue

- t/t2201-job-cmd.t
Problem: CI recently failed due to a "flux job wait-event" timeout in a test in t2201-job-cmd.t.
Increase the timeout from 5 seconds to 30 seconds globally in the file.
Fixes #4887
> testsuite: increase flux job wait-event timeout

- src/common/libschedutil/hello.c
- src/modules/job-manager/event.c
- src/modules/sched-simple/sched.c
- t/Makefile.am
- t/t2303-sched-hello.t
Here's a workaround for the problem's we have with fluxion refusing to start when running jobs are in the KVS, described in #4862.
In this one, a failure of the scheduler's `hello` callback causes a fatal `scheduler-restart` job exception to be posted rather than a scheduler tear-down.  When that particular exception is raised, the job manager clears the flag that indicates that resources are allocated, so the `sched.free` RPC is skipped when the job enters cleanup.
This is a WIP pending writing tests.
> work around fluxion inbability to recover running jobs

- README.md
- scripts/requirements-dev.txt
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/constraint/parser.py
- src/test/docker/bionic/Dockerfile
- t/Makefile.am
- t/python/t0027-constraint-parser.py
- t/t0031-constraint-parser.t
This PR adds a `ConstraintParser` class to the Flux Python bindings which can parse the generic query syntax being proposed for RFC 35 in flux-framework/rfc#360. I'm posting the implementation early since it may help reviewers of the RFC PR to experiment with the syntax and give feedback in either PR.
The `flux.constraint.parser` module supports a `__main__` function, so you can run the parser like this for testing:
```console
$ src/cmd/flux python -m flux.constraint.parser --default-op=name 'a|b|c'
{"or": [{"name": ["a"]}, {"name": ["b"]}, {"name": ["c"]}]}
```
> python: add flux.constraint.parser for RFC 35 Constraint Query Syntax

- doc/Makefile.am
- doc/man1/CONSTRAINTS.rst
- doc/man1/flux-mini.rst
- src/bindings/python/flux/job/frobnicator/plugins/constraints.py
- src/cmd/flux-mini.py
- t/t2112-job-ingest-frobnicator.t
- t/t2276-job-requires.t
This PR builds on #4871 and #4895 to add full RFC 35 constraint syntax support to the `flux mini --requires` option. This is the final step to fix #4535.
After this PR is merged, hosts can be included by hostlist with `flux mini --requires=host:fluke[1-10]` and excluded with `--requires=-host:fluke10`, and jobs can similarly include/exclude resource by broker rank with `rank:IDSET` or `-rank:IDSET`. Additionally, any valid RFC 35 constraint query string is now supported, allowing complex boolean expressions if necessary.
The frobnicator is also updated here to use logical AND to join job constraints with queue constraints.
Once this is merged, end-to-end tests could be added to https://github.com/flux-framework/flux-sched/pull/997, though in principal these PRs could be merged in any …
> Support RFC 35 constraint syntax in `flux mini --requires`

- src/bindings/python/flux/constraint/parser.py
There's an issue with ply's automated generation of `parsetab.py` for `flux.constraint.parser.ConstraintParser`. This file is currently generated during `make` and then installed alongside `parser.py` as part of `make install` which should avoid any need for ply to regenerate the file since the grammar will not change.
However, it turns out that when the parser is used by another file, e.g. within flux-mini.py, ply attempts to write `parsetab.py` out in the same directory of the script instead of alongside `flux/constraint/parser.py`. This could be because flux-mini subclasses `ConstraintParser`, I'm not sure.
However, a good workaround seems to be to default `write_tables=False` in `yacc.yacc()` and only use `write_tables=True` in the one case where we do want to write out a …
> python: avoid unecessary parsetab.py generation in ConstraintParser

- doc/man1/flux-startlog.rst
- etc/rc1
- t/t3200-instance-restart.t
Problem: safe mode is confusing as noted in #4861, and more so now that we have multiple queues with state that persists across a reboot.
All an admin can really do after an improper shutdown is re-enable the queues and hope for the best.  This PR changes the behavior after an improper shutdown is detected.  Instead of stopping/disabling all queues, it just logs the improper shutdown and continues.  If there are troubles, this will be useful information to have in the logs.
> eliminate "safe mode" after improper shutdown

- src/modules/job-manager/plugins/alloc-bypass.c
- t/t2273-job-alloc-bypass.t
This fixes the issue with the `alloc-bypass` plugin described in #4900 and fixes the test to catch this error or errors like this in the future.
> job-manager: fix alloc-bypass plugin

- doc/man1/flux-jobs.rst
- doc/man1/flux-pgrep.rst
- etc/completions/flux.pre
- src/cmd/flux-jobs.py
- src/cmd/flux-pgrep.py
- t/t2800-jobs-cmd.t
- t/t2809-job-purge.t
- t/t3200-instance-restart.t
Per #4899, make the `--suppress-header` / `--no-header` consistent between tools.  Chose to common-ify on `--no-header`.  
Note that I legacy support `--suppress-header` in `flux-jobs` but not in `flux-pgrep`, b/c the latter has not officially been released yet, so I assumed no users of it yet.
> flux-jobs/flux-pgrep: rename --suppress-header to --no-header

- src/cmd/flux-resource.py
Problem: Unlike other tools such as flux-queue and flux-jobs, it is possible for multiple queues to be listed with the "flux resource list" "queue" field.  The default output width is 8 characters, which is a little short for multiple queues.
Increase from 8 characters to 10 characters.
Fixes #4904
---
We can debate the number of chars, I just didn't want to go too big b/c the common case is of course 1 queue.
Also, I elected not to make the heading "QUEUES" (plural).  The field name is "queue" and I figure one queue is still the common case.
Edit: or we could go with QUEUE(S)?
> flux-resource: increase width of queue field

- src/modules/job-list/job_state.c
- src/modules/job-list/job_util.c
- t/t2260-job-list.t
Per discussion in #4906
I only added a regression test, no additional wider coverage tests yet per discussion in #4906.
Hopefully will have those wider extra coverage tests in soon.  But just in case that extra wider coverage can't be completed in a timely manner, just wanted to make sure we atleast get this fix in before the next release, we can always add the extra tests later.
> job-list: do not assume alloc event context always contains annotations

- doc/man1/flux-mini.rst
- doc/test/spell.en.pws
- src/cmd/flux-mini.py
- src/shell/batch.c
- src/shell/internal.h
- src/shell/output.c
- src/shell/shell.c
- src/shell/shell.h
- t/t2601-job-shell-standalone.t
- t/t2701-mini-batch.t
- t/t2702-mini-alloc.t
In #4868, it was suggested (er by me) that an option to dump kvs contents when a batch job instance exits might be useful.
This extends the `content.dump=auto` code in rc3 to use the job ID and produce `flux-<jobid>-kvs.tgz` if requested when a `statedir` is not defined.
I started looking at `flux-mini.py` to see about adding a shorthand option for this and realized it might be better if such an option worked like `--output` and supported mustache templates.  So maybe this is the wrong approach and support for this should be added to the shell `batch` plugin instead.  Parking this pending some time to think more about it.  Meanwhile, input welcome!
> support flux mini batch,alloc --dump[=FILE]

- doc/man1/flux-resource.rst
- src/cmd/flux-resource.py
- t/flux-resource/status/example.expected
Proposing this a bit early so that @garlick can test on his system and give feedback.
This is the simplest solution to #4909, so we can sneak it into the next release.
Problem: It is difficult to tell which drained nodes are offline vs not in the output of flux-resource drain and status.
Take a simple step at first and flag offline drained nodes with an asterisk, i.e. `drained*`, in flux-resource `status` and `drain` output.
Update the expected output in one test.
Fixes #4909
> flux-resource: mark drained+offline nodes with asterisk

- src/bindings/python/flux/constraint/parser.py
- src/bindings/python/flux/job/Jobspec.py
- src/cmd/flux-mini.py
- t/python/t0027-constraint-parser.py
- t/t0031-constraint-parser.t
- t/t2276-job-requires.t
This PR fixes some issues discovered with end-to-end job constraint support upon further testing and review by @garlick.
- Add missing validation of operator characters in the constraint parser
- fix outdated usage output for `--requires` in `flux mini --help`
- detect invalid operator and hostlist,ranks in the jobspec validator
Fixes #4917
> improve invalid RFC 35/RFC 31 constraint detection and documentation

- src/cmd/flux-job.c
- t/t2201-job-cmd.t
- t/t2500-job-attach.t
There have been several instances of users frustrated by a lack of feeback from `flux mini run` and `flux mini alloc` when jobs are pending. It is impossible to tell if the job is waiting for resources, is starting, or has started is hanging etc.
This PR adds a simple job status line to `flux job attach` which is automatically enabled if the job has been pending for more than 2s. This makes it so that jobs which start quickly continue to have no extraneous output, but jobs blocked in `PRIORITY`, `DEPEND` and `SCHED` states will get some feedback automatically when stdin is a tty. The statusline can be forced with `--show-status` (mainly for testing).
Example:
> automatically provide job status for pending interactive jobs

- src/cmd/flux-resource.py
- t/t2311-resource-drain.t
This PR simply adds a note to try `--force` in `flux resource drain` when the target is already drained, in case the user wants to update the drain reason.
> suggest use of --force with `flux resource drain` when target is already drained

- src/cmd/flux-mini.py
The flux-mini RFC 35 constraint parser inadvertently added `hostlist` and `ranks` operators to the `combinded_terms` set in the  parser, which means that `ranks:1 and ranks:2`is joined to `ranks:1-2`. But `ranks:1-2` means the rank can be in the set `1-2`, which means they are joined by OR not AND.
Remove `hostlist` and `ranks` from the `combined_terms` set to avoid this incorrect behavior.
> flux-mini: do not combine hostlist/ranks terms joined by AND

- src/bindings/python/flux/Makefile.am
Problem: The Python ply module is smart enought to avoid regenerating parsetab.py when its tables have not changed (via checksum), but make will always try to regenerate parsetab.py if it is older than constraint/parser.py. This generates unnecessary work for make on every run when parser.py is updated, but the parsing has not changed.
Touch constraint/parser.py after running constraint/parser.py to indicate to make that this file is up to date whether it was rewritten or not.
> build: avoid continuous regeneration of constraint/parsetab.py

- etc/completions/flux.pre
Problem: Some new commands and subcommands were added without updates to the completions file.
Add support for completion of `flux job timeleft`, `flux pgrep` and `flux pkill`.
> etc: update bash completions

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/util.py
- src/cmd/flux-queue.py
- t/t2241-queue-cmd-list.t
Problem: The current default outputs of node, core, and gpu values
and ranges in flux queue list is not considered very user friendly.
Solution: If the value of nnodes, ncores, or ngpus is not configured,
instead of always returning "inf", return "inf" only if it is the max.
Return 0 if it is the min.  As a result, the default output from the
range values of nodes, cores, and gpus becomes 0-inf.
Fixes #4927
> flux-queue: adjust default output of min/max/range

- src/cmd/flux-job.c
- src/common/libutil/Makefile.am
- src/common/libutil/hola.c
- src/common/libutil/hola.h
- src/common/libutil/slice.c
- src/common/libutil/slice.h
- src/common/libutil/test/hola.c
- src/common/libutil/test/slice.c
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- src/modules/job-manager/plugins/history.c
- t/Makefile.am
- t/t2812-flux-job-last.t
I thought these trivial commands would be useful.  `flux-job last` prints the job ID of the most recently submitted job.  `flux job history` prints the job ID and "name" for the most recently submitted 10 jobs.
```
$ flux job last
flux-job: job history is empty
$ flux mini submit -N1 true
ƒ7bbUqDZZ
$ flux job last
ƒ7bbUqDZZ
$ flux job history
ƒ7bbUqDZZ	true
ƒ4a15vsCs	hostname
ƒ4Zj7Lc5M	hostname
ƒ4ZXi88PZ	hostname
ƒ3HPLDNQ7	hostname
ƒoFzsGdV	sleep
ƒhtPAE7h	hostname
```
I couldn't figure out how to get a submission-ordered list of jobs (including all states) out of `job-list` so I added a little jobtap plugin that tracks the last 10 job ids for each user and registers a service that returns the list for the asking user.
I don't know if others will find this useful, so before I did any real …
> add `flux job last`

- NEWS.md
This PR updates NEWS.md with release notes for v0.47.0. Pending PRs tagged with the v0.47.0 milestone are already incorporated into the release notes.
Feel free to push directly here for corrections and updates.
> NEWS.md: add release notes for flux-core v0.47.0

- doc/man7/flux-jobtap-plugins.rst
- src/common/libutil/hola.c
- src/common/libutil/hola.h
- src/common/libutil/test/hola.c
- src/modules/job-manager/event.c
- src/modules/job-manager/plugins/history.c
- src/modules/job-manager/purge.c
- src/modules/job-manager/restart.c
- t/t2212-job-manager-plugins.t
- t/t2812-flux-job-last.t
This fixes #4930 and #4931 by adding  `job.inactive-add` and `job.inactive-remove` jobtap callbacks, as discussed in #4930.
I marked it WIP pending
> job-manager/history: track inactive jobs over purge/restart

- src/modules/job-manager/prioritize.c
- t/t2213-job-manager-hold-single.t
- t/t2214-job-manager-hold-limited.t
- t/t2215-job-manager-hold-unlimited.t
This PR fixes the issue described in #4940, and adds some tests to the `hold` suite of sharness tests to set urgency to hold already held jobs to ensure we don't see this particular issue again.
> job-manager: fix for job priority not reset after a duplicate urgency update

- doc/man1/flux-job.rst
Problem: "flux job attach" is not documented in flux-job(1).
Add documentation on the subcommand and relevant options for users.
---
note: i only document `--label-io` b/c every other option appears to be internal plumbing specific.  agreed or is there another borderline one to document?
```
>flux job attach --help
Usage: flux-job attach [OPTIONS] id
Interactively attach to job
-E, --show-events      Show job events on stderr
-X, --show-exec        Show exec events on stderr
--show-status      Show job status line while pending
-w, --wait-event=NAME  Wait for event NAME before detaching from eventlog
(default=finish)
-l, --label-io         Label output by rank
-v, --verbose          Increase verbosity
-q, --quiet            Suppress warnings …
```
> doc: document attach in flux-job(1)

- doc/man1/flux-jobs.rst
Problem: The exclamation point used in flux-jobs(1) conversion flags is interpreted by some shells, such as csh/tcsh.  It leads to the following error:
$ flux jobs -A -o "{contextual_time!H}"
H: Event not found.
Solution: Add a note in flux-jobs(1) reminding some users that some shells will interpret the exclamation point and it needs to be escaped.
Fixes #4938
> doc: add shell help on flux-jobs(1) formatting

- doc/man1/flux-broker.rst
- doc/man5/flux-config.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- src/cmd/builtin/config.c
- src/common/libflux/conf.c
- src/common/libflux/conf.h
- src/common/libflux/test/conf.c
- t/t0013-config-file.t
Currently, the broker can only read configuration as a set of `*.toml` files from a configuration directory. This is because the underlying `flux_conf_parse(3)` call always appends `/*.toml` to its argument and reads all matching files.
This PR extends `flux_conf_parse(3)` to detect if its path argument is a directory, and if not, attempts to read the file directly. Additionally, if the file has the extension `.json`, parse the config as JSON instead of TOML.
If the path argument is a directory, `flux_conf_parse(3)` still only reads TOML from that directory, to avoid inadvertently parsing some JSON files that wer ignored before.
Thi ability to parse a  file allows more convenient use of simple config files for the broker (you don't have to put your config file in an otherwise empty …
> broker: allow a file argument to `-c, --config-path` in TOML or JSON

- src/bindings/python/flux/util.py
- src/connectors/local/local.c
This PR is a stab at improving the error message from most utilities when `flux_open()` fails. Specifically, when the local connector socket is not found, an error more descriptive than "No such file or directory" is set in the `flux_error_t` of `flux_open_ex(3)` as suggested by @garlick, e.g.:
```
flux-jobs: ERROR: Unable to connect to Flux: broker socket /run/flux/local was not found
```
In other cases, `strerror()` is still used, e.g.
```console
$ FLUX_URI=local:///tmp src/cmd/flux jobs
flux-jobs: ERROR: Unable to connect to Flux: Connection refused
```
which seems about as clear as you can get.
This only works for Python utilities since many C based commands have not switched to `flux_open_ex(3)`.
In addition, error messages from most Python utilities are simplified by attempting to …
> improve error message in Python frontend utilities when broker is not running

- src/common/libsubprocess/Makefile.am
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/server.h
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/rcmdsrv.c
- src/common/libsubprocess/test/rcmdsrv.h
- src/common/libsubprocess/test/remote.c
- src/modules/job-ingest/worker.c
Problem: we noticed that flux stopped accepting job requests on one of the production login nodes after some "channel" errors on the validator subprocess (#4920)
This fixes issue #4920 and improves the error handling and logging around subprocess channel overflow errors.  Now when this occurs you get
```
broker.err[0]: Error writing 4707 bytes to subprocess pid 4077290 stdin: No space left on device
job-ingest.err[0]: job-validator[0]: Failed: No space left on device
```
and the ingest worker is restarted.
> job-ingest: handle worker channel overflow

- src/broker/runat.c
- src/cmd/flux-exec.c
- src/cmd/flux-start.c
- src/common/libsubprocess/Makefile.am
- src/common/libsubprocess/fork.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/fdcopy.c
- src/common/libsubprocess/test/iochan.c
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/remote.c
- src/common/libsubprocess/test/subprocess.c
- src/modules/cron/task.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-ingest/worker.c
- src/modules/job-manager/plugins/perilog.c
- t/rexec/rexec.c
- t/t0005-rexec.t
Problem: the FLUX_SUBPROCESS_EXEC_FAILED state is not needed
This state is a terminal state that indicates that a remote `flux_exec()` call failed before a PID could be returned.  Other remote failures, before and after a PID is returned, are covered by FLUX_SUBPROCESS_FAILED, so the extra state seems to serve no purpose.
Drop the state and update users.
Also, fix logic surrounding a last-ditch SIGTERM sent to subprocesses on failure and improve unit testing on remote subprocess channels.
> libsubprocess: drop FLUX_SUBPROCESS_EXEC_FAILED state

- src/bindings/python/flux/job/Jobspec.py
- src/shell/batch.c
- src/shell/shell.c
- src/shell/tmpdir.c
- t/batch/jobspec/v0.47.json
- t/t2605-job-shell-output-redirection-standalone.t
- t/t2613-job-shell-batch.t
The shell `batch` plugin needs to rewrite the job arguments because the batch script is written to a random filename in TMPDIR. This unforutunately requires different handling of "nested" jobspec (i.e. jobspec that creates a subinstance) between `flux mini alloc` and `flux mini batch`.
Now that there is a `FLUX_JOB_TMPDIR`, write the job script there as `$FLUX_JOB_TMPDIR/script` so the batch script is always in a well known location.
Extend the shell mustache rendere to allow plugins to fulfill templates by subscribing to the callback topic `mustache.render.<name>`. Extend the `tmpdir` plugin to substitute `{{tmpdir}}` with `FLUX_JOB_TMPDIR`.
Finally, refactor the Jobspec `from_batch_command()` method to use `from_nest_command()`, a batch jobspec is now just a special case of a `flux mini …
> Support {{tmpdir}} in shell mustache templates and simplify batch jobspec construction

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/util.py
- src/cmd/flux-resource.py
This PR extends the `?:` prefix in the `OutputFormat` class to suppress columns in which all lines have a representation of zero in addition to suppressing all empty lines. This then allows use of `?:` in the `ngpus` column of `flux resource list`. Displaying an NGPUS column on systems without GPUs was identified as an important issue by at least one user.
> flux-resource: suppress NGPUS on systems without GPUs

- src/broker/broker.c
- src/common/libflux/flog.c
- src/common/libflux/flog.h
- src/common/libsubprocess/Makefile.am
- src/common/libsubprocess/fork.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/iochan.c
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/rcmdsrv.c
- src/common/libsubprocess/test/rcmdsrv.h
- src/common/libsubprocess/test/remote.c
- src/modules/cron/cron.c
- src/modules/job-exec/job-exec.c
- src/modules/job-ingest/pipeline.c
- src/modules/job-manager/job-manager.c
This eliminates the calls to `flux_log()` inside libsubprocess, which is not appropriate in all cases.  It is replaced with an llog function callback, which has been used in the shell.
Since some log messages occur right when the subprocess is created, it would not work to have a "setter" on the subprocess object to set up the logging - that would be too late.  So rather than add logger parameters to `flux_rexec()` and friends, I added a single function `flux_set_default_subprocess_log()` that sets a log function and argument in the `flux_t` handle aux container.  Then when a subprocess or the subprocess server is created, it uses that if it was set.
A llog-compatible callback that logs to the broker is provided, and that is used in the broker-resident subprocess users for now.
The …
> libsubprocess: rework internal logging

- .devcontainer/Dockerfile
- README.md
Problem: writing files in the DevContainer is done as root. 
Solution: have the default user be uid 1000, gid 1000, and they are written as the same user on the host.
To demonstrate this working, here I am making lasagna in the container:
And the same file viewed from the host - it's still owned by me!
> .devcontainer permissions fix

- Makefile.am
- README.md
- scripts/install-deps-deb.sh
- scripts/install-deps-rpm.sh
- vscode.md
Problem: now that we have extensive docs on the readthedocs site, the info in the README is prone to getting stale.
Prune it a bit and reorganize.
> README: trim it down now that we have readthedocs

- doc/man1/flux-alloc.rst
- doc/man1/flux-batch.rst
- doc/test/spell.en.pws
Problem: now that flux-batch(1) and flux-alloc(1) have their own man pages, there is an opportunity to provide a focused command introduction.
This is a stab at improving the docs for those two commands.   I'm not attached to these descriptions at all so suggestions are welcome!
> flux-batch(1) and flux-alloc(1): improve DESCRIPTION section

- configure.ac
- doc/man1/flux-job.rst
- src/cmd/builtin/version.c
- src/cmd/top/top.c
- src/common/libjob/test/job.c
- src/common/libutil/fluid.c
- src/common/libutil/test/fluid.c
- src/test/generate-matrix.py
- t/python/t0010-job.py
- t/t2201-job-cmd.t
This PR adds a new option to flux-core configure: `--enable-broken-locale-mode`, which when used causes flux-core to avoid using the non-ascii `ƒ` character as a FLUID prefix (and in `flux top` etc). It is offered as more fool-proof way to disable the "fancy" character for install where locales or terminals are known to be misconfigured such that `ƒ` does not display correctly.
In these environments, RPMs can be built with this option and the question of when/how to set `FLUX_F58_FORCE_ASCII` can be avoided.
Set as a WIP in case others have better ideas, and because I'm considering if we need a CI builder with this option enabled.
> allow flux-core to be configured in ascii-only mode

- src/common/libjob/test/job.c
- t/python/t0010-job.py
Problem: The FLUX_F58_FORCE_ASCII environment variable is sanitized in all sharness tests, but not in unit and python tests.
Remove the FLUX_F58_FORCE_ASCII environment variable as needed in tests where it breaks expected output or results.
> testsuite: unset FLUX_F58_FORCE_ASCII in some tests

- doc/man1/flux-filemap.rst
- src/broker/content-mmap.c
- src/cmd/builtin/filemap.c
- src/common/libutil/fileref.c
- src/common/libutil/fileref.h
- src/common/libutil/test/fileref.c
- src/shell/stage-in.c
- t/t0029-filemap-cmd.t
Problem: the JSON file objects used by flux-filemap, the broker, and the shell stage-in plugin are out of date now that RFC 37 has been published.
Use the new object format.
WIP pending a bit more testing.
> flux-filemap: update to RFC 37 internally

- src/cmd/flux-mini.py
Problem: the deprecation warning added to flux-mini in #4961 is not working.
This fixes it.  Does this seem appropriate/ok?
```
$  flux mini 
flux-mini: WARNING: ⚠️ flux-mini is deprecated, use flux-batch, flux-run, etc.⚠️
usage: flux-mini [-h] {run,submit,bulksubmit,batch,alloc} ...
flux-mini: error: the following arguments are required: subcommand
```
I was wondering about the non-ascii glyphs but they do get your attention and it's not like people are going to whine too much about a command they should be migrating away from :-)
> flux-mini: emit deprecation warning

- src/shell/doom.c
Problem: The incorrect JSON object is decref'd in doom_post() in the doom shell plugin, resulting in a leak of the outer `entry` object.
Call json_decref() on the correct object.
> shell: fix memory leak in doom plugin

- doc/man1/common/submit-standard-io.rst
- doc/man1/flux-job.rst
- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/cli/run.py
- src/cmd/flux-job.c
- src/shell/input.c
- t/Makefile.am
- t/scripts/pipe.py
- t/t2500-job-attach.t
- t/t2710-python-cli-submit.t
- t/t2711-python-cli-run.t
This PR adds support for directing standard input of `flux run` to a subset of task ranks.
This is a stopgap for #4956 until we can get better support for input redirection directly in the job shell.
This PR works by adding a new `--stdin-ranks=RANKS` option to `flux job attach`. Then, the `--input` option (in `flux run` only) is extended so that it a supplied idset is passed along to `flux job attach` instead of setting a filename in jobspec.
In addition, there's some minor cleanup in the job shell to detect if a writer attempts to write to closed tasks.
In a future PR, a new scheme will be proposed to allow more generic redirection of standard input, but `--input=RANKS` should still work in this case, so that we won't be changing behavior.
> flux-run: allow stdin to be directed to a subset of tasks

- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/test/remote.c
Problem: a remote subprocess that receives SIGSTOP is killed for entering an "illegal state" (#4947)
Handle the STOPPED state properly for remote processes.
> libsubprocess:  don't abort remote processes that receive SIGSTOP

- src/cmd/top/top.c
Problem: The initial draw of the summary pane shows "(null)" instead of "ƒ" or "f" because the top->f_char is not initialized until *after* the panes are created.
Move the initial draw of top summary and job panes to after the f_char member is initialized.
> flux-top: initialize f character before drawing panes

- doc/man1/flux-pgrep.rst
- doc/man3/flux_event_decode.rst
- doc/man3/flux_request_decode.rst
- doc/man3/flux_response_decode.rst
- src/bindings/python/flux/cli/fortune.py
- src/bindings/python/flux/util.py
- src/common/libsubprocess/test/subprocess.c
- t/t0014-runlevel.t
Problem: "sub-instance" should not be hyphenated
Fix spelling.
There's more misuse in `flux-docs`, but saw there was one dumb one here :P  The remaining ones were in NEWS.md, but didn't touch those.
> Fix minor documentation errors and typos

- etc/completions/flux.pre
It seems gauche to offer tab completion for `flux mini` when that command is deprecated, so this PR removes it from the bash tab completion config distributed with flux.
I found some other minor missing things and added those here as well.
> completions: remove flux-mini and other updates

- NEWS.md
Some proposed release notes for 0.48.0.
Assumes "shell: fix memory leak in doom plugin (#4979)" is merged.
Edit: oops, and also "flux-run: allow stdin to be directed to a subset of tasks (#4977)"
> NEWS: add release notes for 0.48.0 release

- src/cmd/flux-mini.py
Problem: The warning that flux-mini is deprecated is not as clear as it could be.
Atttempt to instruct users the exact command they are looking for when possible, e.g. `flux mini run` warns:
flux-mini: WARNING: ⚠️ flux-mini is deprecated, use flux run ⚠️
Otherwise, replace 'flux-run`, 'flux-submit' with "flux run" and "flux submit" so that users do not try to use literally "flux-run".
Fixes #4988
> flux-mini: improve deprecation warning

- src/bindings/python/flux/hostlist.py
- src/cmd/flux-resource.py
- t/python/t0020-hostlist.py
This simple PR improves the indexing of `Hostlist` objects by
* returning a new `Hostlist` when more than one host is indexed, e.g. by slice (before, a `list` of hosts was returned)
* allowing any iterable to be used with a Hostlist index, most notably a tuple, e.g. `hl[1,3,5]` and an idset `hl[ids]`.
> python: improve Hostlist class indexing

- doc/man1/flux-resource.rst
- src/cmd/flux-resource.py
- src/modules/resource/drain.c
- t/t2311-resource-drain.t
This PR adds a `force-overwrite` "mode" to the job-manager drain RPC which overwrites the drain reason _and_ timestamp.
Use of `--force` twice in `flux resource drain` then sets this mode, such that `flux resource drain -ff TARGETS REASON` will update both timestamp and reason, instead of just the drain reason.
> flux-resource: support overwrite of drain timestamp with `--force --force`

- doc/man1/flux-resource.rst
- doc/test/spell.en.pws
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/resource/__init__.py
- src/bindings/python/flux/resource/status.py
- src/bindings/python/flux/util.py
- src/cmd/flux-resource.py
- t/flux-resource/status/drain.expected
- t/flux-resource/status/example.expected
- t/flux-resource/status/exclude.expected
- t/flux-resource/status/offline.expected
- t/flux-resource/status/simple.expected
- t/t2351-resource-status-input.t
This PR is a WIP. Still need to write a few more tests and documentation. However, since this makes some fundamental changes to the `flux resource status` command, it would be good to get feedback before finishing up those items.
This is pretty much a full rewrite of `flux resource status`. It is broken up into a few parts, but the final rewrite is one big change, I wasn't sure how else to accomplish that.
* First some groundwork is laid to make a reusable `flux.util.Deduplicator` class, which combines items that would format to the same string given an output formatter, a list of fields that should be excluded from duplicate detection, and  a method to combine similar items.
* Then, some reusable code for fetching status from both the resource and scheduler module is added to …
> rewrite flux-resource status

- src/cmd/flux-mini.py
Problem: the deprecation warning for flux-mini tells the user about the underlying command, which is not actually what they would execute!
Solution: Fix the warning to reference "flux mini" and "flux (submit|batch|run) etc. so it makes sense.
I was doing some testing of flux with merlin tonight and was (very happy) to see this warning, but I think we could improve it slightly by showing the user the command they would actually run, and not the underlying actual filename.
> fix: warning message to user should be actual command

- src/broker/exec.c
- src/common/libsubprocess/Makefile.am
- src/common/libsubprocess/client.c
- src/common/libsubprocess/client.h
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/remote.h
- src/common/libsubprocess/server.c
- src/common/libsubprocess/server.h
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/iochan.c
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/rcmdsrv.c
- src/common/libsubprocess/test/rcmdsrv.h
- src/common/libsubprocess/test/remote.c
- src/common/libsubprocess/test/subprocess.c
This PR modifies the subprocess server so a service name (currently `rexec`) can be specified when the server is instantiated and then adds  `flux_rexec_ex()`, a variant of `flux_rexec()` with an additional service name parameter.
Internally, the "remote" portion of libsubprocess is cleaned up so that the RPC protocol is handled exclusively in client.c and server.c
This is prep work for
- embedding the subprocess server in the shell (needed once shells are launched in a limited cgroups environment)
-  #5004
- allowing subprocess clients to communicate with a new compatible server that starts processes using systemd
> cleanup: allow subprocess service name to be configured

- src/broker/broker.c
- src/broker/exec.c
- src/broker/runat.c
- src/cmd/builtin/proxy.c
- src/cmd/flux-start.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/server.h
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/iochan.c
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/rcmdsrv.c
- src/common/libsubprocess/test/remote.c
- src/common/libsubprocess/test/subprocess.c
- src/common/libterminus/terminus.c
- src/modules/cron/cron.c
- src/modules/cron/task.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/sdexec.c
- src/modules/job-ingest/pipeline.c
- src/modules/job-ingest/worker.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/plugins/perilog.c
- src/shell/task.c
Problem: it was probably a misstep to add `flux_set_default_subprocess_log()` instead of adding logger parameters directly to the subprocess functions.
Add `flux_local_exec_ex()` that takes an `llog` function.
Drop the `hooks` argument from `flux_local_exec()` since it is not widely used (leave it in the `_ex()` version)
Drop `flux_exec()` since the only difference from `flux_local_exec()` was taking a `flux_t *` instead of a reactor, so that it could call `flux_log()` internally, which it no longer does.
Add the logger parameters to `subprocess_server_create()`, and have subprocesses inherit the logger from the server.
> cleanup: improve interface for subprocess logging

- src/common/librlist/rhwloc.c
Problem: The librlist rhwloc_local_topology_xml() function passes the HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V1 flag when exporting the topology to XML under hwloc 2.x, thus forcing the XML for all users of this function to the hwloc v1 format. This includes the XML stored in the resource module and available via resource.topo-get.
Now that hwloc 2.x is more ubiquitous and the XML gathered by the flux resource module has less users, it may be possible to drop this flag.
In fact, we now have external users like mpibind which assume hwloc 2.x and the V1 flag may be detrimental to those integrations.
Drop the HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V1 flag when generating XML from a v2 topology so that v2 XML is available.
Fixes #5005
> librlist: drop V1 flag from hwloc XML generation

- src/modules/job-manager/event.c
- t/job-manager/plugins/perilog-test.c
- t/t2212-job-manager-plugins.t
@jameshcorbett reported an issue where an `epilog-start` event was emitted for a job in CLEANUP, but the `free` and `clean` events were still emitted before `epilog-finish`. This only seems to occur if a job enters CLEANUP without ever having started, e.g. when a job exception occurs during the job prolog.
The problem occurs because the `epilog-start` event is still pending in the job manager event queue when the action for CLEANUP runs. Since the job didn't start, and `perilog_active` is still 0, the `free` event is emitted immediately instead of waiting for `epilog-finish`.
This PR simply adds a check for a pending `epilog-finish` event that is enqueued.
A new test is added to replicate the failing case.
> job-manager: ensure epilog-start event prevents resource release for job that never started

- src/broker/broker.c
- t/issues/t4612-eventlog-overwrite-crash.sh
Problem: The broker posts a job memo containing the instance remote uri too early during startup. This creates a race condition where the job uri is available in the eventlog before the local connector has created the socket, resulting in a rare failure to connect using tools such as `flux alloc --bg`.
Move the function that notifies any parent instance of subinstance particulars (including instance uri) to after the connector is loaded.
> fix rare `Unable to connect to JOBID` error from `flux alloc --bg`

- t/t4000-issues-test-driver.t
Problem: The t4000-issues-test-driver.t runs individual tests serially, and now that there are many issues tests to run, the time to run the test is getting very long - exceeding the 5 minute CI time limit in some cases.
Alter the design of the t4000-issues-test-driver.t test to run each issue reproducer script as a job. Since some scripts themselves run jobs, execute each script under a single-core Flux instance.
Adjust one test that only works with multiple cores to cancel a running job before submitting a new one.
> testsuite: speed up t4000-issues-test-driver.t

- src/broker/broker.c
- src/broker/overlay.c
- t/t3302-system-offline.t
Problem: if a broker cannot connect to its upstream peer, `flux dmesg` doesn't work, and if the problem is a misconfigured hostname, nothing is logged anyway.
Add dmesg to the list of services that are available "early" (before upstream connect).
Add a small check on the upstream URI before handing it over to zmq_connect().
If I comment out the upstream peer in /etc/hosts on my test cluster, now I can do this:
```
$ sudo flux dmesg
2023-03-24T22:52:26.438913Z broker.err[7]: getaddrinfo picl2: No address associated with hostname
2023-03-24T22:52:26.459197Z broker.debug[7]: insmod connector-local
2023-03-24T22:52:26.459352Z broker.info[7]: start: none->join 18.249ms
2023-03-24T22:52:26.460967Z connector-local.debug[7]: allow-guest-user=true
2023-03-24T22:52:26.460997Z …
```
> improve broker debugging on overlay connect failure

- src/common/libflux/flog.c
Problem: An internal buffer added +1 to the buffer, but didn't use it in any meaningful way.
Remove the extra +1 that isn't needed.
Fixes #3880
> libflux: remove extraneous +1s used in buffers

- doc/man1/common/submit-other-options.rst
- src/bindings/python/flux/cli/base.py
As suggested by @v and @ryanday36, the documentation of the `--begin-time` option doesn't make it clear that the argument can be either a relative offset or an absolute time. This PR adjusts both the help output and manual page to hopefully make that more clear.
> cli: adjust description of `--begin-time` submission option

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/util.py
Problem: The "h" output presentation type will output a hyphen (-) if a timestamp field is equal to the epoch of 1970-01-01T00:00:00. However, this does not account for any local timezone offsets that may occur when outputting the epoch time.
Solution: In addition to checking 1970-01-01T00:00:00, get the local epoch time and add it to the list of potential "zero" things that
can be converted to a hyphen.
> python: recognize local timezone epoch adjustment

- doc/man1/flux-uri.rst
Problem: The environment FLUX_URI_RESOLVE_LOCAL is not documented.
Add info about it in flux-uri(1).
----
I couldn't remember the environment variable and had to dig to find it.  So decided we should stick it in `flux-uri(1)`.
> doc: document FLUX_URI_RESOLVE_LOCAL

- doc/Makefile.am
- doc/man1/common/submit-job-environment-variables.rst
- doc/man1/flux-run.rst
- doc/man1/flux-submit.rst
Problem: The environment variables that Flux creates when a job is run is not documented.
Add documentation into flux-run(1) and flux-submit(1).
Fixes #4568
----
I largely cut and pasted the text that @grondo had written up in the issue.  Only debate might be where I put this in the manpages.  Could be higher/lower than where I put it?
> doc: document job environment variables

- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-manager/kill.c
- t/Makefile.am
- t/t2402-job-exec-dummy.t
- t/t2406-job-exec-cleanup.t
This PR should fix #4987. It is WIP for now while I consider how to add a test.
Currently, the job shell is always terminated with SIGKILL after the configurable kill timeout in the job-exec module. This PR modifies the exec system to instead _request_ that the job shell send SIGKILL to the job tasks. This should result in many less orphan processes in the common case. Tasks can still be missed if they escape the process group set for them by the shell, but they will eventually be caught by future improvements to run first-level system jobs in a container.
The SIGKILL is sent open loop (since it is based on an event anyway), so I wonder if the exec system should keep trying as long as the job is still around. :thinking:
> prevent orphaned job processes when terminating jobs due to exception

- t/t2701-mini-batch.t
- t/t2702-mini-alloc.t
- t/t2714-python-cli-batch.t
- t/t2715-python-cli-cancel.t
- t/t2802-uri-cmd.t
Not sure what happened in the last month but nice chunk of tests were failing / timing out for me when doing big parallel `make -j16 check` runs.
I'm sure it has nothing to do with the tests I updated here specifically, but its whatever other tests are running in parallel and eating up tons of CPU.  Perhaps some new tests are really CPU heavy and thus hitting these specifically.  The timeout of 180 was picked somewhat randomly based on surrounding tests.
If this is approved, I'll actually wait a few days to hit MWP.  See if any more pop up.
Edit: maybe the t4000 tests now running in parallel is causing this?  It launches up a flux instance of two nodes within it, and each node can have many CPUs, thus running many t4000 tests in parallel?
> testsuite: increase test timeouts

- doc/man1/flux-jobs.rst
- doc/man1/flux-pgrep.rst
- doc/man1/flux-queue.rst
- doc/man1/flux-resource.rst
- src/bindings/python/flux/util.py
- src/cmd/flux-pgrep.py
- t/sharness.d/01-setup.sh
- t/t2241-queue-cmd-list.t
- t/t2311-resource-drain.t
- t/t2350-resource-list.t
- t/t2351-resource-status-input.t
- t/t2800-jobs-cmd.t
- t/t2811-flux-pgrep.t
Per #4839.  Several pros and cons to approach, but I think a relatively safe "net win".
> Support environment variable to override default output formats

- src/cmd/flux-pgrep.py
The `sre_constants` module has been depreacated in latter Python versions. Turns out we didn't need it anyway.
> flux-pgrep: fix warning about sre_constants on Python 3.11+

- doc/man1/flux-resource.rst
- doc/man5/flux-config-resource.rst
- src/modules/resource/drain.c
- src/modules/resource/drain.h
- src/modules/resource/exclude.c
- src/modules/resource/resource.c
- t/t2311-resource-drain.t
This PR attempts to prevent excluded ranks from being drained since `flux resource status` now assumes a node/rank is only in one of the states avail, exclude, drained, or draining.
Ensuring this required changes in multiple places - I'm not sure if there was a cleaner way to handle this:
* exclude idset is now checked in the drain request handler and an error generated if any target is excluded
* if a node is excluded on replay, any drain events for that rank are ignored
* if a node is excluded at runtime, any drain state for that rank is cleared
Since drain initialization now requires access to the exclude idset, the resource module initialization had to be reordered a bit. It was actually a bit difficult to determine the dependencies between the resource module bits, so I tried to add …
> resource: do not allow ranks to be both drained and excluded

- src/common/libpmi/upmi.c
- src/common/libpmi/upmi_libpmi.c
Problem: when debugging flux launch failure with FLUX_PMI_DEBUG=1, trace output does not include the final dlopened library, if any.
This adds a way for the plugin to return a generic note on successful initialization, which is included in the trace output.  The libpmi plugin sets its note to "using .../libpmi.so".  Here's an example when launching under slurm on a cray system (using libpmi2 which isn't merged yet but you get the idea):
```
rzvernal11 /g/g0/garlick/proj/flux-core > FLUX_PMI_DEBUG=1 srun -N2 -n2 src/cmd/flux start /bin/true
boot_pmi: flux-pmi-client: trying 'simple'
boot_pmi: simple: PMI_FD not found in environ
boot_pmi: flux-pmi-client: trying 'libpmi2'
boot_pmi: flux-pmi-client: trying 'simple'
boot_pmi: simple: PMI_FD not found in environ
boot_pmi: flux-pmi-client: …
```
> libpmi: improve tracing of dlopened PMI libraries

- src/broker/boot_pmi.c
- src/cmd/builtin/pmi.c
- src/common/libpmi/Makefile.am
- src/common/libpmi/upmi.c
- src/common/libpmi/upmi.h
- src/common/libpmi/upmi_libpmi.c
- src/common/libpmi/upmi_libpmi2.c
- t/t0001-basic.t
- t/t3002-pmi.t
This works through the problems identified in #5040.  I've been able to test this on rzvernal, where the cray PMI libraries were added to LD_LIBRARY_PATH and seems ok.
```
$ srun -N2 -n4 src/cmd/flux start flux getattr broker.mapping
[[0,2,2,1]]
$ src/cmd/flux start flux getattr broker.mapping
(snip big warning from libhwloc)
[[0,1,1,1]]
```
> libpmi: enable flux to bootstrap with cray libpmi2.so

- doc/man1/flux-job.rst
- src/cmd/flux-job.c
- t/t2208-job-manager-wait.t
As discussed in #5033, it is hard to differentiate between a job not being waitable / no more jobs are waitable vs a waitable job had an error.  Because in both circumstances `flux job wait` exits with 1.
This PR has `flux job wait` exit with 100 when either a jobid is non-waitable (invalid, not waitable, etc.) or there are no more waitable jobs.  So we can more easily write a script like this:
```
while jobid=`flux job wait 2> /dev/null`; ec=$?; test $ec -ne 100
do
echo "$jobid finished"
if [ $ec -eq 0 ]
then
echo "job successful"
else
echo "job failed"
fi
done
echo "no more jobs to wait on"
```
I picked the exit code 100 somewhat arbitrarily.  It's common to use exit code of 2, 3, 4, ... for other purposes.  I just wanted to make it clear this wasn't an exit code from the job.  Maybe …
> flux-job: add special exit code to flux job wait when not waitable

- src/common/libjob/jj.c
- src/common/libjob/jobspec1.c
- src/common/libjob/result.c
- src/common/libjob/sign_none.c
- src/common/libjob/strtab.c
- src/common/libjob/test/job.c
- src/common/libjob/test/jobspec1.c
- src/common/libjob/test/sign_none.c
- src/modules/job-list/job_state.c
- src/modules/job-list/job_util.c
- src/modules/job-list/stats.c
- src/modules/job-list/test/job_data.c
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
technically is `job-list` and things related to `job-list`
> job-list: minor code consistency cleanup

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/job/list.py
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
- t/t2800-jobs-recursive.t
This PR adds a `--json` option to flux-jobs(1) to dump job data as JSON instead of formatted output.
As discussed in #4994, by default the keys in the JSON objects for jobs are filtered of empty/unset values.
Fixes #4994
> flux-jobs: add --json option

- src/cmd/top/joblist_pane.c
- t/t2801-top-cmd.t
Per #5021, the listing of jobs when filtered by specific queue did not display correctly because job indexing was not done correctly.
> flux-top: fix queue specific output display

- src/common/libpmi/upmi_libpmi.c
- src/common/libpmi/upmi_libpmi2.c
Problem: a flux standalone singleton no longer works on slurm systems, as reported in #5057
The libpmi2.so from slurm (which is installed in a public libdir) does not "emulate" singleton when called outside of a slurm job, unlike the libpmi.so from slurm which does emulate singleton.
Now that we're searching for libpmi2 ahead of libpmi because of the cray situation, we're hitting this.
Change the libpmi2 (and libpmi) plugins so that they ensure the library is going to work before selecting it.  This lets the pmi client try the next method.
WIP pending some manual testing.
> PMI: ensure fallthrough when PMI library fails to initialize

- doc/man1/flux-shell.rst
- doc/test/spell.en.pws
- src/shell/pmi/pmi.c
- src/shell/pmi/pmi_exchange.c
- t/t2701-mini-batch.t
- t/t2714-python-cli-batch.t
- t/t3002-pmi.t
This implements the idea presented in #5063 of interpreting `flux run -o pmi=VALUE` values as a list of PMI implementations to load.   It preserves the meaning of `-o pmi=off` and the behavior of loading the simple server by default, but now if `-opmi` is specified and it doesn't include `simple`, the simple server is not loaded.
This PR also renames the little used simple pmi tunables to be under an implementation specific key.  `-o pmi.kvs=native` becomes `-o pmi-simple.kvs=native`.
This gives users more control over which PMIs are active among `simple`, `pmix`, and `cray-pals`.  It will require those plugins to be modified as well to disable themselves if they are not in the list.
> shell: support -o pmi=LIST

- src/shell/lua.d/openmpi.lua
Problem: we may want to bootstrap pre-v5 versions of openmpi using the flux-pmix plugin, but the always-loaded openpmi plugin tries to force the flux MCA plugins to load.
Drop that part of the plugin.  It shouldn't really be necessary anyway, since the whole purpose of the ompi "schizo" layer is to determine which bootstrap method to use.  It should find Flux OK unless it's configured wrong.
> openmpi: don't force flux MCA plugins

- etc/flux.service.in
Problem: when flux-shutdown(1) is used to stop flux, the systemd unit state is set to failed.
Set SuccessExitStatus=42 so the magic "norestart" exit code is considered success, in addition to 0.
Fixes #5076
> systemd: avoid leaving unit in failed state after flux-shutdown(1)

- etc/flux.service.in
- src/broker/Makefile.am
- src/broker/broker.c
- src/broker/broker.h
- src/broker/runat.c
- src/broker/runat.h
- src/broker/state_machine.c
- src/broker/test/runat.c
Systemd's [sd_notify(3)](https://www.freedesktop.org/software/systemd/man/sd_notify.html) provides a mechanism to improve systemd integration for the flux system instance brokers.
This PR contains the following improvements
1) notify systemd of the broker's status during startup/shutdown
2) delay the rank 0 unit transition to "active" by switching to `Type=notify` and sending a notification on rank 0 only once the broker has reached run state (e.g. it's ready to run stuff)
Here's a snapshot of `systemctl status flux` output during startup.  Note the new "Status:" line showing that the broker is running rc1.  Also note that the Active: line shows "activating (start)".  Later it will change to "active (running)".
```
● flux.service - Flux message broker
Loaded: loaded …
```
> broker: improve systemd integration with sd_notify(3)

- src/cmd/flux-job.c
- src/modules/job-exec/exec.c
- t/t2400-job-exec-test.t
This PR modifies the error raised by the job-exec module when the job-shell or IMP failed to execute, which is currently a bit confusing, e.g.:
```
job shell exec error on broker pi3 (rank 0): No such file or directory
```
The new error just adds the path to the failing command, which should make it obvious what went wrong in this case.
When testing, I noticed that `flux job attach` would hang in this scenario (ctr-c works to terminate it though) because of a stray timer that was left on in the reactor, so that is fixed here as well.
For some reason, the test does not work in CentOS 7. Instead of getting an error from exec(2), execution of the job shell from a bad path returns success on this distro, then later exits with exit code 127. I didn't want to spend all day trying to get to the …
> job-exec: improve error message when job shell/imp execution fails

- src/common/libsubprocess/subprocess.c
I noted in #5080 how there were some warnings/errors due to `assert(0)` usage in `libsubprocess`.  In general, shouldn't use `assert(0)`.  Should assert to check for validity of expected things vs doing a `assert(0)` to "error out" on unexpected things.  In one case it was in an user facing API function, which is bad.
Due to my recently created issue #5083 also added a note about how one function doesn't necessarily do the expected thing at the moment.
> libsubprocess: remove use of assert(0)

- t/t2400-job-exec-test.t
Problem: A test in t2400-job-exec-test.t fails on RHEL7.  It is skipped on CENTOS7 and should be skipped on RHEL7 as well.
Skip the test on both RHEL7 and CENTOS7.
Fixes #5089
----
Tested on a RHEL7 and RHEL8 box, hopefully there isn't a corner case in there (that won't be picked up via CI).
> testsuite: skip failing test on RHEL7

- src/broker/state_machine.c
- src/cmd/builtin/proxy.c
- src/common/libeventlog/Makefile.am
- src/common/libsubprocess/server.c
- src/common/libterminus/pty.c
- src/shell/Makefile.am
- t/sharness.d/01-setup.sh
- t/t0001-basic.t
- t/t9000-system.t
This PR includes a set of fixes that were necessary under `conda`, excluding the `fwrite` changes required from `attribute_unused` in the CentOS 6 sysroot.
I figured most of these will work around future problems we may hit on other one-off platforms.
> build: applicable build and test fixes for conda

- src/common/libsubprocess/remote.c
Problem: libsubprocess can trigger a segfault if a remote subprocess object is destroyed before the remote protocol is complete.
The remote's future should be held by subprocess->f but in the code cleanup of 8bb3e74fad8c2178a8900121cf7aa1ef69869766, this was dropped and it now has an independent life cycle from the subprocess.
Assign the future to subprocess->f and don't destroy it separately on completion in the continuation.
Fixes #5094
> libsubprocess: avoid segfault on error path

- src/modules/job-manager/job-manager.c
- src/modules/job-manager/jobtap.c
This PR slightly improves the errors when a jobtap plugin fails to load.
Fixes #5098
> job-manager: improve errors from jobtap initialization

- doc/man1/flux-job.rst
- src/cmd/flux-job.c
- src/modules/job-manager/purge.c
- t/t2809-job-purge.t
Per #4801.  I decided to add a new `purge-id` subcommand instead of having `purge` take optional ID arguments.  That way its similar to `list` vs `list-id`.
> flux-job: support job ids to purge

- t/t9000-system.t
Problem: In t9000-system.t the FLUX_TEST_INSTALLED_PATH variable is setup if 'debug' is set.  However, the check for 'debug' is done before sharness is sourced, so the `-d` option when running the tests doesn't matter.  This lead to the t9000-system.t tests failing when running make check in a docker container.
Solution: Instead of checking for 'debug' to set FLUX_TEST_INSTALLED_PATH, check for FLUX_ENABLE_SYSTEM_TESTS instead.
> testsuite: fix setup error in system tests

- t/t1000-kvs.t
Problem: A test in t1000-kvs.t assumes the environment variable COLUMNS is not set before running the test.  If the environment variable is set, it can mess up the expected output.
Run part of the test in a subshell with COLUMNS unset just in case.
---
It's just not my day for running the sharness test suite ;-)
I accidentally ssh-ed to a cluster from a local docker container on my laptop, and for whatever reason, that lead to `COLUMNS=140` to be set in my session, messing up this test.  
I could unset the variable for the whole test as well, dunno if there's a strong preference from the group.
> testsuite: fix column width output corner case

- src/cmd/flux-ping.c
- src/common/libfluxutil/method.c
- t/t0007-ping.t
Per discussion in #4106, output a header before the main ping output.  This is useful because there are so many input possibilities, as well defaults, that the header can make it clear what is being pinged.  In addition, when a hostname is input on the command line, the rank can be specified too.
As discussed, the output of the ping output is now also the same regardless of the input mechanism.  Before you might get `0!broker`, `broker`, or `upstream!broker` depending on the input on the command line.  Now you always get `0!broker` if the ping comes from rank 0.
Biggest complaint might be my static inline `ASPRINTF()` function.  I was just annoyed enough about passing buffers around that I wanted to use `asprintf` instead, and it was just annoying enough to have to do `log_err_exit("out …
> flux-ping: output header before output of main ping output

- t/t0001-basic.t
- t/t2405-job-exec-sdexec.t
- t/t2613-job-shell-batch.t
This PR fixes a few spurious errors in the testsuite caused when running the nix package manager. These are mostly fixes that would have popped up elsewhere anyway.
This does not go as far as replacing every use of absolute paths to commands (`/bin/sh`, `/bin/bash`) yet, but this allows most tests to pass under the flake shared by @trws in #4998.
Some systemd tests still fail for unknown reasons. It is best to disable the tests that use systemd when running under nix by unsetting `XDG_RUNTIME_DIR` during the testsuite, e.g.
```
XDG_RUNTIME_DIR= make -j 12 check
```
> testsuite: fix test issues under nix

- doc/man1/flux-top.rst
- src/cmd/Makefile.am
- src/cmd/top/joblist_pane.c
- src/cmd/top/keys.c
- src/cmd/top/queues.c
- src/cmd/top/summary_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
- t/t2712-python-cli-alloc.t
- t/t2801-top-cmd.t
It is inconvenient to have to restart flux-top to filter jobs by a different queue.
Support using the left/right arrow keys or h/l to "rotate" through all of the possible queues, including "all" queues.
Only minor thing is it's a little annoying that you don't know what queue (or "all" queues) you are currently rotating through if no jobs are in that queue.  So I added the queue name along with the fancy f in the upper left.  Could be somewhere else?  Originally I was going to add something right above the "QUEUE" header, until I realized the instance depth is already output there when you recurse down in `flux-top`.  We could also remove this, it's not super important.
This PR is built on top of #5032
> flux-top: support ability to flip through queues via left/right arrow keys

- .github/workflows/main.yml
- .typos.toml
Problem: The current typos workflow check only checks a select number of files because there are so many false positives in flux-core.
Solution: Add a _typos.toml configuration file to eliminate false positives so we can run the typo check on all of flux-core.  The config file either skips files with lots of false positives or lists common false positives we wish to ignore.
----
This works when I run by hand in my build dir, we'll see if this works in CI :shrug: 
Note, this will probably fail typo checking until #5019 is merged
Edit:
yup, seems to work.  These are the ones I have in a fix in #5019
> Add false positives typos config

- src/common/libschedutil/ops.c
- src/modules/sched-simple/sched.c
- t/t2300-sched-simple.t
This implements @grondo's fix proposed in #5108, and removes unnecessary service de-registration code from libschedutil that was adding to the log noise when this problem was encountered.
> sched-simple: avoid assertion failure when trying to load scheduler twice

- configure.ac
- etc/rc1
- etc/rc3
- src/modules/Makefile.am
- src/modules/sdbus/Makefile.am
- src/modules/sdbus/README.md
- src/modules/sdbus/connect.c
- src/modules/sdbus/connect.h
- src/modules/sdbus/interface.c
- src/modules/sdbus/interface.h
- src/modules/sdbus/main.c
- src/modules/sdbus/message.c
- src/modules/sdbus/message.h
- src/modules/sdbus/objpath.c
- src/modules/sdbus/objpath.h
- src/modules/sdbus/sdbus.c
- src/modules/sdbus/sdbus.h
- src/modules/sdbus/subscribe.c
- src/modules/sdbus/subscribe.h
- src/modules/sdbus/test/message.c
- src/modules/sdbus/test/objpath.c
- src/modules/sdbus/watcher.c
- src/modules/sdbus/watcher.h
- t/Makefile.am
- t/issues/t3503-nofiles-limit.sh
- t/t2407-sdbus.t
- t/t2408-sdbus-recovery.t
Edit: after some iteration, this PR now only contains the `sdbus` module and its tests.  The `sdexec` portion will be submitted separately.
This is a rework/reimagining of @chu11's libsdprocess work from 2021 with the goal of getting  `job-exec` to launch shells as systemd transient units for the following short term benefits:
- clean up of orphaned processes when flux comes back online
- systemd cgroups containment (especially memory) on job shells
and of course to prepare groundwork for the eventual recovery of running jobs.
Two broker modules are added that enable libsubprocess to work with systemd transient units.  The modules are only loaded in an instance configured with
```toml
[systemd]
enable = true
```
One module is a D-Bus gateway module that translates Flux RPCs into D-Bus …
> sdbus: enable flux to communicate with a systemd user instance

- .mergify.yml
- src/modules/sdbus/connect.h
- src/modules/sdbus/interface.c
- src/modules/sdbus/message.h
- src/modules/sdbus/sdbus.c
Despite https://github.com/flux-framework/flux-core/pull/5070 failing the typo/spelling check, it was merged by mergify.  Ends up we forgot to add spelling to the mergify check.
Do that and add the fixed typos.
> mergify: add spelling check to required checks

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/stats.py
- src/cmd/top/summary_pane.c
- src/modules/job-list/stats.c
- t/t2260-job-list.t
Problem: The way that job-list stats counts failures is that all non-successful jobs are failures.  This can be a bit confusing b/c job results return jobs as "failed", "canceled", or "timeout".  So the total job failures via "job results" is different than the job failures via job-list stats.
Problem: Make the job-list stat counts consistent to job results.  Update tests and users of job-list stats in flux-top, flux-jobs, and t2260-job-list.t.
This PR is built on top of #5031
> job-list: make job stats consistent to job results

- Makefile.am
- src/common/libccan/Makefile.am
- src/common/libtomlc99/Makefile.am
@jan-janssen noticed that the flux-core `LICENSE` file was missing from our distribution tarball.
This PR adds that and some other missing licenses and informational files to `EXTRA_DIST` where appropriate so those files are included in the distribution.
> ensure license and other informational files appear in distribution tarball

- src/common/libutil/fileref.c
- src/common/libutil/test/fileref.c
Problem: The libutil/fileref code fails to compile on systems without SEEK_DATA and SEEK_HOLE defined. This occurs for example on conda-forge which uses a CentOS 6 based sysroot.
Wrap optional code in #ifdef SEEK_DATA and #ifdef SEEK_HOLE so that the code compiles without sparse file support.
(This will allow us to eventually drop this patch from the conda-forge recipe).
> fileref: fix compile on systems without SEEK_DATA/SEEK_HOLE

- src/shell/mpir/nodelist.c
- src/shell/mpir/proctable.c
- src/shell/mpir/proctable.h
- src/shell/mpir/rangelist.c
- src/shell/mpir/test/nodelist.c
- src/shell/mpir/test/proctable.c
This PR fixes a bug in the encoding of MPIR data by the job shell when hostnames have leading zeros in the numeric suffix. The suffix is converted to an integer when encoded to the "rangelist" representation, so the leading zeros are dropped.
Also, I noticed the encoding(s) used to compress the MPIR proctable were not documented anywhere. I've added a brief description of each in the source code for future reference.
> shell: fix improper encoding of some hostnames in MPIR proctable

- src/bindings/python/flux/job/directives.py
- t/batch/directives/valid/011-quoted-punctuation.sh
- t/batch/directives/valid/expected/011-quoted-punctuation.expected
A user noticed that some batch directives unexpectedly required quoting, e.g.
```console
$ cat test.sh
#!/bin/sh
#flux: --output=test.{{id}}.out
flux run -n8 hostname
$ flux python -m flux.job.directives  test.sh
SETARGS(['--output=test.', '{', '{', 'id', '}', '}', '.out'])
```
On further reading of the `shlex` python documentation, the `whitespace_split` attribute should be set to `True` for "the best shell lexing compatibility", This seems to fix the problem:
```console
$ src/cmd/flux python -m flux.job.directives test.sh
SETARGS(['--output=test.{{id}}.out'])
```
This PR makes that change and adds missing tests that exercise the issue.
> python: fix parsing of special characters in submission directives

- src/bindings/python/flux/importer.py
- t/t2110-job-ingest-validator.t
This PR fixes an issue where `flux job-validator` reports that no plugins are available when importing any one plugin failed with an `ImportError`. This occurred because a `ModuleNotFoundError` exception was handled at the wrong spot and treated as an empty plugins directory.
Now, any import failure on a plugin will result in an exception being raised to the caller with a sensible error message.
e.g.: in the case reported in #5116 we see this
```console
$ flux job-validator --list-plugins
Available plugins:
```
Now we'll get this:
```console
$ src/cmd/flux job-validator --list-plugins
flux-job-validator: ERROR: failed to import schema plugin: No module named 'jsonschema'
```
> job-validator: fix empty plugins list when one plugin fails to import

- doc/man1/common/submit-standard-io.rst
- src/shell/shell.c
- t/t2606-job-shell-output-redirection.t
This PR adds support for rendering a `{{name}}` tag in file output templates that expands to the job name or command.
> shell: support {{name}} tag in output file templates

- src/bindings/python/_flux/Makefile.am
- src/cmd/flux-job.c
- src/common/libflux/types.h
- src/common/libjob/Makefile.am
- src/common/libjob/job.h
- src/modules/job-archive/job-archive.c
- src/modules/job-list/list.c
- t/t2260-job-list.t
Per #4514 
I gave this issue another go around late last week.  The major gotcha is the auto-generation of python bindings to deprecated C functions, which we probably don't want to do.
Going back and forth with several options, I decided on the following approach.  Set
```
#ifndef FLUX_DEPRECATED
...
#endif
```
around deprecated C functions, so that the python scripts wouldn't generate those functions.
The big pro was that it was relatively easy, not a lot of changes, no major script updates to python bindings stuff.
The con is, well, that this is all it is.  Using the python `deprecated` decorator appears more for non-auto-generated stuff and would probably require a non-trivial amount of scripting hacks to add that in, especially for auto generated stuff.
Considered a special …
> libjob: deprecate flux_job_list() and flux_job_list_inactive()

- src/broker/log.c
- src/cmd/builtin/dmesg.c
- src/common/libutil/Makefile.am
- src/common/libutil/test/timestamp.c
- src/common/libutil/timestamp.c
- src/common/libutil/timestamp.h
This PR is a stab at fixing #5081. The timestamp parsing code is moved from `src/cmd/builtin/dmesg.c` to libutil (including some tests), then the broker uses that to reformat timestamps in a more readable format and in localtime.
This only changes the timestamps emitted on stderr, timestamps are still encoded as ISO 8601 in UTC in the internal dmesg buffer.
I guess the drawback to doing it this way is more processing required when the broker is logging with timestamps to stderr, but that is pretty rare (the system instance logs to systemd without timestamps).
Fixes #5081
> broker: use human readable timestamp in local time when logging to stderr

- src/common/libtomlc99/Makefile.am
- src/modules/sdbus/sdbus.c
- t/t2407-sdbus.t
- t/t2408-sdbus-recovery.t
Problem: sdbus users can't tell the difference between recoverable and non-recoverable errors
Return EAGAIN on recoverable error (sdbus is reconnecting to D-Bus) and ENOSYS when the module is unloading.
There's also a small correction to the EXTRA_DIST additions in #5113
> sdbus: return useful errno values to requests on error

- doc/man3/flux_shell_getenv.rst
- src/common/libflux/plugin.c
- src/common/libflux/test/plugin.c
- src/common/libflux/test/plugin_foo.c
- src/shell/shell.c
- t/shell/plugins/invalid-args.c
This PR improves poor handling of errors from plugins discovered by @jameshcorbett in https://github.com/flux-framework/flux-coral2/pull/68.
Specific changes are documented in the included commits.
> improve error on plugin load if flux_plugin_init() returns an error

- src/broker/runat.c
- src/cmd/builtin/proxy.c
- src/cmd/flux-exec.c
- src/common/libflux/attr.c
- src/common/libflux/test/attr.c
- src/common/libsubprocess/server.c
- src/common/libutil/uri.c
- src/common/libutil/uri.h
- src/shell/task.c
- t/t1105-proxy.t
This is a WIP fix for #5132. Posting before tests are fully complete (though testing will be trivial) because I'm not sure the implementation will be acceptable.
This PR adds special handling of `parent-uri` directly to `attr_get()`. If there is a request for the `parent-uri` attribute and an environment variable `FLUX_PROXY_REMOTE` is currently set, then the local `parent-uri` is transparently transformed to a remote URI using the remote "authority" in `FLUX_PROXY_REMOTE` and is cached locally as `parent-remote-uri`.
When `flux-proxy(1)` uses a remote URI to connect to an instance, it then sets `FLUX_PROXY_REMOTE` appropriately in the environment of the spawned subprocess. Then, care is taken to unset this environment variable if other subprocesses are started, e.g. as part of a job or …
> convert parent-uri attribute to remote under flux-proxy(1)

- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/overlay.c
- t/t0013-config-file.t
Problem: there is no way to tune the ZMQ_CONNECT_TIMEOUT socket option.
Allow the connect timeout to be set either in the config:
```toml
[tbon]
connect_timeout = "10s"
```
or on the broker command line: `-Stbon.connect_timeout=10s`.
The broker command line takes precedence.
Set a default of 30s instead of the system default of "a long time" per [zmq_setsockopt(3)](http://api.zeromq.org/4-2:zmq-setsockopt).
Fixes #5134
> broker: make tbon.connect_timeout configurable

- src/bindings/python/flux/job/info.py
Problem: We currently cannot package rlist.h with the install (at least without more work) and since this is a required import for flux.job.info, without it the Python bindings (installed via pip) will error.
Solution: the flux.resource module is not technically required, so we can fallback to catching the ImportError instead and using the same empty (dummy) class to handle self.resources
I am going to test this with the Python bindings, and would like to get that working first before we finalize it here! Note that I'm going to be taking a break for a few minutes but I'll be back after. I'll update the issue after I have done some testing with this branch!
> make SchedResourceList optional in flux.job.info

- src/cmd/flux.c
- src/common/libutil/Makefile.am
- src/common/libutil/environment.c
- src/common/libutil/environment.h
- src/common/libutil/test/environment.c
- t/t1102-cmddriver.t
This is an experimental WIP to address #5016.
Instead of prepending to `PATH`, have flux(1) command driver _insert_ its path into `PATH` as far back as possible, i.e. such that the current `flux` executable is still the first `flux` that will be found.
This has two useful effects. First, if the current `flux` is already the first `flux` in `PATH`, then `PATH` is not changed. Second, if a common path like `/usr/bin` does need to be moved up, it will only be moved up enough to make `/usr/bin/flux` take precedence over any other `flux`. This will likely avoid the issue we have now -- that calling `/usr/bin/flux` promotes `/usr/bin` in front of other directories users purposefully placed before `/usr/bin` or other system paths.
Fixes #5016
> flux(1): avoid prepending to PATH when unnecessary

- doc/requirements.txt
- src/broker/state_machine.c
Problem: the rank 0 broker currently calls sd_notify(0, "READY=1") when it reaches RUN state, but this puts an upper bound (default 90s) on the time to execute rc1, which can be too little when there are many jobs in the KVS.
Notify systemd when the broker enters JOIN state for all ranks.
Fixes #5151
> broker: signal readiness to systemd in JOIN state

- doc/man1/flux-start.rst
- doc/man1/flux-uptime.rst
- doc/man7/flux-broker-attributes.rst
- etc/flux.service.in
- src/broker/state_machine.c
- src/cmd/flux-start.c
- t/sharness.d/flux-sharness.sh
- t/t0025-broker-state-machine.t
- t/t3203-instance-recovery.t
- t/t3301-system-latestart.t
- t/t3302-system-offline.t
Problem: broker.quorum as an idset is less useful than if it were a size threshold.
Redefine broker.quorum as a size.
Fixes #5145
WIP pending some manual testing...
> broker: redefine broker.quorum as a size

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/list.py
- src/cmd/flux-job.c
- src/modules/job-list/list.c
- src/modules/job-list/list.h
- t/t2250-job-archive.t
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
This is some misc cleanup / doc updates peeled off from another branch.  It also include cleanup in `flux-job`, testsuite, and `flux-jobs(1)`.
> job-list: misc cleanup

- src/bindings/python/flux/util.py
Problem: The Python 3.11 tomllib implementation requires that toml files be opened in binary mode, but the UtilConfig class opens files in normal read mode, resulting in a TypError
File must be opened in binary mode, e.g. use `open('foo.toml', 'rb')`
Open all UtilConfig config files with mode 'rb'. This doesn't seem to cause an issue with other config file types.
Fixes #5154
> python: open UtilConfig files as binary

- src/common/libioencode/ioencode.c
- src/common/libioencode/ioencode.h
- src/common/libioencode/test/ioencode.c
- src/shell/output.c
- t/t2606-job-shell-output-redirection.t
This is a WIP pending tests and is meant as a stopgap workaround for #5148.
This PR simply sets a static threshold for KVS output and stops writing to the output eventlog after the threshold is reached.
A warning is issued at the time output is truncated as well as at the end of the job.
Figured I'd post early to get feedback.
E.g.:
```console
$ flux run lptest 79 140000 | wc -c
4.842s: flux-shell[0]:  WARN: output: stdout will be truncated, 10MB limit exceeded
5.240s: flux-shell[0]:  WARN: output: stdout: 714240 of 11200000 bytes truncated
10485760
```
> shell: truncate output to KVS after 10MB

- src/test/docker/README.md
- src/test/docker/docker-run-checks.sh
- src/test/docker/fedora38/Dockerfile
- src/test/docker/fedora38/config.site
- src/test/generate-matrix.py
This PR adds a builder for Fedora 38, since this distro has GCC 13 and Python 3.11, a combo we're not yet testing.
The caliper version we've pinned won't build in fedora38, and the newest version isn't compatible with the current code that calls it in flux-core, so I've just disabled Caliper here. Honestly, I'm wondering if we should just remove the caliper support? Eh, not too much of a headache yet, so we can save that decision for another day.
> ci: add fedora38 builder, update flux-security default to 0.8.0

- src/shell/output.c
- src/shell/shell.c
- src/shell/shell.h
- t/shell/plugins/invalid-args.c
The `shell_mustache_render(3)` function declared in `shell.h` is missing the `flux_` prefix. Since the shell is built to only export `flux_*` symbols, this means that this function is not available to dynamically loaded shell plugins.
Rename the function `flux_shell_mustache_render(3)`, add protection against a `NULL` `shell` parameter, and add a couple simple tests for invalid arguments to the testsuite.
> shell: add missing `flux_` prefix to `shell_mustache_render(3)`

- src/common/libioencode/ioencode.c
- src/common/libioencode/ioencode.h
Problem: There are several memory leaks in error paths in libioencode.
Make sure to free memory on error paths.
Fixes https://github.com/flux-framework/flux-core/issues/5158
Also, cleanup some unnecessary goto statements.
> libioencode: fix memleaks on error paths

- src/broker/broker.c
- src/broker/exec.c
- src/broker/module.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/overlay.c
- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/test/message.c
- src/connectors/local/local.c
- src/modules/connector-local/local.c
- src/modules/sdbus/sdbus.c
- t/t0017-security.t
- t/t2407-sdbus.t
The flux broker exec service on rank 0 does not allow any user, even the instance owner, to start processes remotely, so that flux cannot be used to attack (albeit only as the unprivileged flux user) a locked down management node from a compromised compute/login node.
Problem: the recently added `sdbus` module (not loaded by default) provides the ability to launch processes as the flux user, but has no restrictions.  Furthermore, the mechanism used to restrict the broker exec service only works within the broker proper and cannot be used in `sdexec`, which is a broker module.
This PR  replaces the broker-only method with a new method (proposed in #5136) that works anywhere, then adds the rank 0 restriction to the `sdbus` module.
> restrict remote access to sdbus on rank 0

- t/sharness.d/flux-sharness.sh
- t/t1000-kvs.t
- t/t2803-flux-pstree.t
On some systems, likely those with bash >= 5, tests that make use of a `COLUMNS` environment variable to override the detected terminal width were failing when the test was run with `-d -v`. It isn't obvious why the failures only occur with the
debug and verbose sharness flags, but the cause seems to be invocation of the `flux` libtool wrapper script (which uses `#!/bin/bash`), which then causes the `COLUMNS` variable to be reset.
There isn't a clear workaround for this issue, so instead set a prereq if `COLUMNS` does propagate through a call to `flux`, and use that prereq to skip a couple tests when that isn't true.
> testsuite: skip tests that expect COLUMNS to be inherited across calls to flux(1) when that isn't true

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/util.py
- t/python/t0024-util.py
- t/t2800-jobs-cmd.t
This PR fixes a few annoyances when using the `!d` conversion specifier in output formats as discussed over in #5055 
- A `!d` converted timestamp now renders as an empty string for a timestamp of `0.0`
- The `h` suffix can now be used with `!d` to replace the empty timestamp with a hyphen `-`
- Currently `!d` used without a format returns an empty string, this PR adds a default format so that a ISO 8601 string is returned instead.
I've also added a set of unit tests for the affected `UtilDatetime` class to ensure the above is working.
> python: improve handling of `!d` conversion specifier in output formats

- .pre-commit-config.yaml
- src/bindings/python/flux/util.py
In #5055 some code that was only supported in Python 3.11 did not get caught by the vermin check, which surprised me.  It ended up it was caught in a newer version of vermin.
So lets increase the version and add a `novermin` comment for one place that needs it.  Also add a comment to the place that needs the novermin override.
> pre-commit: increase vermin version

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/compat36.py
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
- t/Makefile.am
- t/python/t0028-compat36.py
- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
- t/t3203-instance-recovery.t
Per discussion in #4946.  This adds a new field `{inactive_reason}` to get why a job is inactive and a new named format in `flux-jobs` to help the user get the reason why their job is inactive.
After some trial and error, came up with the following defined format for `flux-jobs`, which I call "endreason".  Open to suggestions for an alternate name.  Its the best I could come up with :-)
```
+                "{id.f58:>12} ?:{queue:<8.8} {username:<8.8} {name:<10.10+} "
+                "{status_abbrev:>2.2} {t_inactive!D:>19h} {inactive_reason}"
```
example
```
JOBID USER     NAME       ST          T_INACTIVE INACTIVE-REASON
ƒCWZ9cgX chu11    sleep       R                   - 
ƒBwTFejy chu11    sleep       R                   - 
ƒJw1KBu1 chu11    nosuchcom+  F 2023-03-31T12:45:43 command …
```
> flux-jobs: support new "inactive_reason" output field and "endreason" format

- src/common/liboptparse/optparse.c
- src/common/liboptparse/test/optparse.c
Problem: When a required argument is missing, liboptparse returns the error "unrecognized option", which is confusing.
Solution: Check for a missing argument and return a more appropriate "missing argument" error message.  Output the long option name when name is available.  Add some unit test coverage.
Fixes #5178
> liboptparse: correct message on missing argument

- src/cmd/flux-job.c
This is a possible workaround for #5175 since the cause of that issue isn't really understood. Instead of aborting `flux job attach` when there is an EINVAL error creating the buffered stdin watcher, just log a warning that stdin will be ignored.
> flux-job: ignore stdin instead of aborting when unable to create stdin watcher

- src/cmd/flux-job.c
- t/t2201-job-cmd.t
- t/t2404-job-exec-multiuser.t
This is a small change required for some other work, but which seemed more appropriate as its own PR.
The main goal is to simply strip leading and trailing whitespace from J when submitted with `flux job submit --flags=signed`, however there was some other very minor cleanup along the way.
> flux-job: submit: strip unnecessary whitespace from pre-signed jobspec

- src/cmd/Makefile.am
- src/cmd/flux-imp-exec-helper
- src/common/libflux/Makefile.am
- src/common/libflux/conf.c
- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/exec_config.h
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/sdexec.c
- src/shell/internal.h
- src/shell/shell.c
- src/test/docker/docker-run-checks.sh
- t/job-exec/dummy.sh
- t/job-exec/imp.sh
- t/t2402-job-exec-dummy.t
- t/t2602-job-shell.t
- t/valgrind/valgrind.supp
This PR adds an IMP exec helper utility that lets the IMP fetch its input from the enclosing instance instead of requiring the input on stdin. This becomes the default behavior if flux-security >= 0.9.0 is detected (the version in which support for an IMP helper was introduced). 
This should improve scalability of mulituser job launch somewhat, but the main purpose is to free up stdin/out of the job shell to be used to implement the exec barrier protocol instead of a separate socketpair. This will be necessary to support launching multi-node jobs under systemd, under which we can't provide a separate set of fds for the protocol.
Thus, when the IMP helper is used, use stdin/out fds for the exec protocol.
Closes #4220
> job-exec: provide IMP exec helper when possible and use stdin/out for shell exec protocol

- doc/python/job_submission.rst
Problem: A job submission Python example in the docs has an error, so it won't run, making it a poor example. It also prints the raw JobInfo object, which isn't very demonstrative.
Update the example to fix the error and print something useful from the returned JobInfo result object.
Fixes #5190
> doc: fix python example

- src/broker/broker.c
- src/broker/runat.c
- t/Makefile.am
- t/issues/t5105-signal-propagation.sh
This PR changes the behavior of the broker when handling nonfatal symbols `SIGUSR1`, `SIGUSR2`.
Currently, the broker ignores `SIGUSR1` and `SIGUSR2`, so a user attempting to signal a batch job with `SIGUSR1` to achieve some effect will be disappointed - the signal is ignored.
This PR changes the handling of these signals so that they are forwarded to all active jobs. If there is an error forwarding signals (e.g. the job-manager module is not loaded), then the broker falls back to calling `state_machine_kill()`.
This allows the `SIGUSR` and `SIGUSR2` signals to be propagated to jobs -- i.e. the expected behavior. If one or more jobs are subinstances, then the signal is forwarded to the jobs in that instance, and so on. The test added here ensures that a `SIGUSR1` delivered to a batch job …
> broker: foward nonfatal signals to all running jobs

- src/bindings/python/flux/kvs.py
- t/python/t0005-kvs.py
Problem: The KVS python interface writes all data to the KVS in JSON and reads all data back assuming it is formatted in JSON.  This appears to be legacy implementation from the days that all data in the KVS was required to be formatted in JSON.
There are still some benefits to doing this, for example Python lists/dicts can be written/read back easily.  However, there are clear
problems with this, most notably data written in non-JSON format cannot be read from the KVS via the Python interface at all.
Solution: With the goal of not breaking current code, support the following compromise.  If data that is read back is not in JSON format, return it as a string if all the data is UTF-8 valid.  If it is not UTF-8 valid, return it in a Python bytes object.  If data cannot be written in JSON, …
> python: support non-JSON formatted data in KVS

- doc/man1/flux-resource.rst
- src/bindings/python/flux/hostlist.py
- src/bindings/python/flux/resource/status.py
- src/cmd/flux-resource.py
- src/common/libhostlist/hostlist.c
- src/common/libhostlist/hostlist.h
- t/python/t0020-hostlist.py
- t/t2311-resource-drain.t
- t/t2351-resource-status-input.t
This PR adds a `-i, --include` option for both `flux resource status` and `flux resource drain` as requested in #5143. The option allows filtering output to a select set of hosts or ranks by using a new `filter()` method for `ResourceStatus` objects (which are returned from `flux.resource.resource_status()`).
It is not an error to provide ranks or hosts that do not exist. Instead, only the hosts that do match are retained. This not only seemed most correct given that the option is a filter, but also makes it easier to implement and match behavior between hostnames in a hostlist and ranks in an idset.
e.g.
```console
$ src/cmd/flux resource status
STATE UP NNODES NODELIST
avail  ✔      5 pi[3,0-2,4]
$ src/cmd/flux resource status -i 0-1
STATE UP NNODES NODELIST
avail  ✔      2 pi[3,0]
$ …
```
> flux-resource: add `-i, --include` option to filter hosts for `status` and `drain` commands

- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- t/t0005-rexec.t
Problem: when `rexec.kill` cannot look up a pid, it fails with ENOENT (No such file or directory).
Fail with ESRCH (No such process) instead.
Also, don't set the SUBPROCESS_REXEC_CHANNEL flag for a remote subprocess if an `on_channel_out` callback is registered, but no channels are configured.
This was peeled off of #5197.
> libsubprocess: fail with ESRCH when pid cannot be found

- t/issues/t4184-sched-simple-restart.sh
- t/issues/t4227-test.sh
- t/issues/t4331-job-manager-purged-events.sh
- t/issues/t4583-free-range-test.sh
- t/issues/t4612-eventlog-overwrite-crash.sh
- t/issues/t5105-signal-propagation.sh
- t/t0025-broker-state-machine.t
- t/t3100-flux-in-flux.t
- t/t4000-issues-test-driver.t
Problem: The regression tests in t/issues are now run in parallel, which can increase the chance of test timeouts / failures when a large parallel run of the test suite is done.
Increase the timelimit of each issue to 10m from 2m.  For extra good measure, increase the timeouts of several waits / etc. in several tests under t/issues.
> testsuite: increase test expiration

- src/cmd/flux-job.c
- src/modules/job-list/idsync.c
- src/modules/job-list/idsync.h
- src/modules/job-list/job_state.c
- src/modules/job-list/list.c
- t/job-list/job-list-helper.sh
- t/python/t0005-kvs.py
- t/t2260-job-list.t
- t/t2261-job-list-update.t
- t/t2800-jobs-cmd.t
- t/t2801-top-cmd.t
Problem: It'd be convenient if the `job-list.list-id` service not only waited for a job id to be legal but to also waited for the job to pass
a certain job state.  Then it can also be used to "wait on" `job-list` for a number of eventual consistency checks in the testsuite.
Fixes #2864                                                                                                                                 
Also stuck on a testsuite coverage for a prior PR that I just forgot to do.
> job-list: allow list-id to wait for job state                                                                                               

- t/t2260-job-list.t
- t/t2261-job-list-update.t
- t/t2800-jobs-cmd.t
Problem: flux job list-ids will error out when output is to stdout instead of a file.  Recent testsuite cleanup did not consider this fact when tests are run in debug mode.
Solution: When using flux job list-ids always redirect to a file. Fix offending cases in t2260-job-list.t, t2261-job-list-update.t, and t2800-jobs-cmd.t by redirecting to /dev/null.
Fixes #5230
> testsuite: fix tests when run in debug mode

- src/cmd/top/top.c
- t/t2801-top-cmd.t
Problem: The flux-top command can redraw output when a heartbeat
is received.  On a slow system, such as during a large parallel
run of the testsuite, its possible the heartbeat could arrive before
a test completes, resulting in unexpected output and a failing test.
Solution: In t2801-top-cmd.t, reload the heartbeat module with a much
longer heartbeat period.
Fixes https://github.com/flux-framework/flux-core/issues/5223
> testsuite: fix potential flux-top race

- src/broker/groups.c
- src/broker/runat.c
- src/broker/service.c
- src/cmd/flux-exec.c
- src/common/libflux/composite_future.c
- src/common/libkvs/kvs_txn_compact.c
- src/common/librlist/rlist.c
- src/common/librouter/disconnect.c
- src/common/libsubprocess/command.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/modules/job-exec/job-exec.c
- src/modules/job-list/idsync.c
- src/modules/job-list/job_state.c
- src/modules/job-list/stats.c
- src/modules/job-manager/event.c
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/limit-duration.c
- src/modules/job-manager/plugins/limit-job-size.c
- src/modules/job-manager/plugins/perilog.c
- src/modules/job-manager/queue.c
- src/modules/kvs-watch/kvs-watch.c
- src/modules/kvs/kvsroot.c
- src/shell/output.c
Problem: zhash_insert() and zhashx_insert() return -1 when a duplicate entry exists, NOT when the process is out of memory.  However, a number of locations assume it returns when out of memory and set errno = ENOMEM as a result.
Do not assume zhash_insert()/zhashx_insert() fail on memory allocation errors.  Always ssume duplicate entry.  When necessary set/return errno = EEXIST instead of ENOMEM.
Fixes https://github.com/flux-framework/flux-core/issues/5216
Notes:
My initial reason for doing this was just to make things consistent b/c there was inconsistency in `flux-core`.   Don't know how necessary this is ... Maybe this was just a pointless excercise ... but since I did it, here's the PR :P
There were obviously borderline cases.  Maybe another approach would be to set errno = ENOMEM …
> zhash_insert()/zhashx_insert() return EEXIST 

- doc/man1/common/submit-other-options.rst
- doc/man1/flux-jobs.rst
- doc/test/spell.en.pws
- src/bindings/python/flux/cli/alloc.py
- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/cli/batch.py
- src/bindings/python/flux/job/Jobspec.py
- src/bindings/python/flux/util.py
- t/Makefile.am
- t/t2716-python-cli-batch-conf.t
This PR adds a `--conf` option to `flux-alloc` and `flux-batch` which allows users to iteratively build a JSON config file in the jobspec file archive (i.e. `.attributes.system.files["conf.json"].data`). If this option is used once, then `-c{{tmpdir}}/conf.json` is appended to the broker options so that the config becomes the child instance config. The `--conf=ARG` option takes several possible types of arguments:
* If `ARG` contains a newline, then it is assume to be a multiline configuration and is parsed as JSON or TOML. This allows config to be embedded directly in a batch directive
* O/w, if `ARG` contains a `=`, the argument is assumed to be `key=value` where `key` can be dotted to set hierarchical values, and value is parsed as JSON -- e.g. `--conf=resource.noverify=true`
* O/w, if …
> add `--conf` option for registering instance config in `flux-batch` and `flux-alloc`

- src/broker/runat.c
- src/common/libsubprocess/command.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/cmd.c
- t/t0014-runlevel.t
Problem: SLURM_ prefixed environment variables that leak through slurm -> flux -> MPI can cause hard to diagnose problems.
Clear all SLURM_ prefixed variables in the environment of the rc scripts spawned by the broker (where rc2 == initial program).
> broker: unset SLURM_* in initial program environment

- doc/man1/common/submit-other-options.rst
Problem: It may be tempting for users to use the --add-file=PATH job submission cli option to broadcast large files to their job, a use which would be inappropriate.
Add a note to this option explaining when --add-file should be used vs the shell stage-in plugin.
> doc: add usage note for --add-file submission cli option

- doc/man1/flux-resource.rst
- src/bindings/python/flux/resource/ResourceSet.py
- src/bindings/python/flux/resource/Rlist.py
- src/bindings/python/flux/resource/list.py
- src/cmd/flux-resource.py
- t/flux-resource/list/normal-new-info.expected
- t/flux-resource/list/normal-new.expected
- t/flux-resource/list/normal-new.json
- t/t2350-resource-list.t
Recently, a `-i, --include=TARGETS` option was added to `flux resource drain` and `flux resource status`, but not to `flux resource list`. It turns out this would be useful, and it is simple, so add it.
> flux-resource: add `-i, --include=TARGETS` option to `list`  and `info` subcommands

- src/cmd/flux-job.c
Problem: flux-job.c is missing a necessary include of signal.h.
Add the missing include.
> flux-job: add missing include of signal.h

- src/common/libjob/test/unwrap.c
- src/common/libjob/unwrap.c
While diagnosing a local issue with libflux-security, I noticed that `sign_unwrap()` was suppressing the error from `flux_security_configure(3)` and also had a potential leak.
Fix the leak and grab the `flux_security_last_error()` so that errors are easier to diagnosis.
Add one extra test to the unit tests so that when these tests fail the user has some idea of the actual error.
> libjob: fix leak in sign_unwrap()

- doc/man1/flux-resource.rst
- etc/completions/flux.pre
- src/cmd/flux-resource.py
- t/flux-resource/list/fluxion.R
- t/flux-resource/list/missing.R
- t/flux-resource/list/normal-input.R
- t/flux-resource/list/normal-new.R
- t/flux-resource/list/null.R
- t/t2350-resource-list.t
It seems like a gap that there's no way for a user to access the underlying resource set being used by the scheduler. In fact, in a system instance, users can't access any kind of instance wide R since access to `resource.R` in the KVS is limited to the instance owner.
This PR adds a simple `flux resource R` command that fetches the scheduler resource set and emits Rv1. By default, the R for all resources is emitted, but there are options to get R for any state supported by `flux resource list`.
> flux-resource: add `R` subcommand

- src/common/libjob/unwrap.c
Problem: if the Flux security context cannot be allocated, `unwrap_string()` falls through to `flux_security_configure()` instead of returning.
Add missing return.
> libjob: return on error in unwrap_string()

- doc/man5/flux-config-bootstrap.rst
Problem: two of the examples in flux-config-bootstrap(5) split inline tables across lines, but TOML 1.0.0 forbids newlines bewteen the curly braces unless they are valid within a value.
Inline tables are described here:
https://toml.io/en/v1.0.0#inline-table
Change the formatting of the examples to be valid TOML 1.0.0.
Note that the last example demonstrates using the "arrays of tables" syntax which may be more readable when inline tables become too long. Arrays of tables are described here:
https://toml.io/en/v1.0.0#array-of-tables
All the bootstrap examples were successfully run through https://www.toml-lint.com/.
Fixes #5249
> flux-config-bootstrap(5): fix TOML error

- doc/man1/flux-restore.rst
- etc/rc1
- src/cmd/builtin/restore.c
- t/t2807-dump-cmd.t
Problem: flux could not be restarted on a system after `flux shutdown --gc` due to EFBIG errors from `flux-restore(1)`.
This was more fallout from the earlier lack of any limit on the amount of stdio a job can write to the KVS.   Some large stdio keys were apparently still around and were added to the dump file when flux was shut down.  When flux was brought back, up the  keys could not be restored because they exceed the maximum content cache blob size and manual recovery was necessary.
As discussed in #5245, this adds a new option `--ignore-store-error=LIST` to flux-restore(1) that allows certain store errors to be treated as warnings rather than fatal.  rc1 is modified to call `flux restore --ignore-store-error=EFBIG`.
> Ignore errors when starting flux from a restart dump containing giant blobs

- src/shell/shell.c
- src/shell/task.c
- src/shell/task.h
- t/t2602-job-shell.t
This PR fixes #5258 by overwriting HOSTNAME in the job environment when it is set.
> shell: set correct HOSTNAME in job environment if necessary

- src/bindings/python/flux/job/JobID.py
- src/bindings/python/flux/job/list.py
- t/python/t0010-job.py
While working on #5176 I noticed a corner case in the `JobList` class.  It assumes that all ids passed in are of type `JobID`, so that later on `jobid.orig` can be output in an error message.  But a jobid could just be an integer.
There are multiple ways to handle this.  I elected to go for a simple:
```
-                    msg = f"JobID {child.jobid.orig} unknown"
+                    id = JobID(child.jobid)
+                    msg = f"JobID {id.orig} unknown"
```
solution.  This also requires the `JobID` class to take a `JobID` as input.  There of course other ways to skin this cat of course.
> python: allow JobID to take a JobID

- src/modules/sdbus/sdbus.c
- t/t2407-sdbus.t
- t/t2408-sdbus-recovery.t
Problem: sdbus is prolific in its output to the flux circular log buffer.
Disable debug logging by default, and allow it to be enabled by config:
```toml
[systemd]
sdbus-debug = true
````
(This was peeled off of #5197)
> sdbus: make debug logging configurable

- src/bindings/python/flux/resource/ResourceSet.py
- src/bindings/python/flux/resource/list.py
- t/python/t0022-resource-set.py
- t/t2350-resource-list.t
This PR fixes the issue described #5266, when hosts are excluded by configuration, they do not appear in the `SchedResourceList` "all" resource set, and so an erroneous assumption that the index into the `nodelist` attribute is the node rank causes the wrong hosts to be included.
> flux-resource: fix `-i, --include=HOSTS` in `list` command when some hosts are excluded

- configure.ac
Problem: job-exec includes code to run the pre-0.9.0 IMP.
Require 0.9.0 so we can drop that code.
This was split from #5267 for improved release notes.
Also: since 0.9.0 is only now starting to roll out in LC (and may be delayed for some time on some platforms), we could elect to delay merging this until deployments catch up a bit, if not being able to build flux-core `--with-flux-security` on those platforms would be inconvenient.  Quickly checking some systems:
- corona: flux-security 0.8.0
- fluke, tioga, rzvernal: flux-security 0.9.0
> build: require flux-security >= 0.9.0

- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/exec_config.h
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/sdexec.c
Problem: testing with the (future) "sdexec" remote subprocess exec service is complicated by the fact that stdio is only used for the exec barrier when the IMP is invoked.
Use stdio by default, falling back to a subprocess channel only if the IMP is too old.
A couple of very minor fixes are also included.
Peeled off of #5197
> job-exec: always use stdio for exec barrier

- src/broker/boot_config.c
- src/broker/overlay.c
- t/t0013-config-file.t
Problem: the broker complains of being unable to resolve its upstream peer when bootstrapped via PMI, but the peer uri is valid.
```  
Warning: unable to resolve upstream peer [: Name or service not known
```
The URI is generated by 0mq after concretizing a wildcard bind address.  When ipv6 is enabled, 0mq puts the address in a form that cannot be parsed by yuarel, nor can it be looked up by getaddrinfo(3), e.g.
```
tcp://[::ffff:134.9.50.69]:49155
```   
Move the check into boot_config.c so that it is only performed when the URIs come from a config file.
Fixes #5273
> broker: avoid spurious overlay peer warning

- doc/man1/flux-filemap.rst
- doc/man1/flux-ping.rst
- doc/man1/flux-restore.rst
- etc/rc1
- src/cmd/builtin/filemap.c
- src/cmd/builtin/restore.c
- src/cmd/flux-ping.c
- src/common/Makefile.am
- src/common/liboptparse/optparse.c
- src/common/liboptparse/optparse.h
- src/common/liboptparse/test/optparse.c
- src/common/libutil/parse_size.c
- src/common/libutil/parse_size.h
- src/common/libutil/test/parse_size.c
- t/t0007-ping.t
Ok, attempt 3 here. I think we now know what this all about.
Differences in this version:
- as suggested, add a `optparse_get_size_int()` helper function that calls the optparse fatal error function if the supplied argument overflows `MAX_INT`.
- add an `encode_size()` function (with unit tests) to `parse_size.c` that creates a human readable string from a `size` argument using the same suffixes supported by `parse_size()`. This is only used to encode `MAX_INT` for help output for now, but could be useful in the future.
- Use `optparse_get_size_int()` in the affected flux utilities.
- Simplify documentation
> support `[kKMG]` suffixes in command options that take a bytes argument

- src/broker/broker.c
- src/broker/modservice.c
- src/modules/content-files/content-files.c
- src/modules/content-sqlite/content-sqlite.c
- src/modules/job-archive/job-archive.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-list/job-list.c
- src/modules/job-manager/job-manager.c
- src/modules/kvs-watch/kvs-watch.c
- src/modules/kvs/kvs.c
- t/t0012-content-sqlite.t
- t/t0017-security.t
- t/t0018-content-files.t
- t/t1005-kvs-security.t
- t/t2100-job-ingest.t
- t/t2202-job-manager.t
- t/t2250-job-archive.t
- t/t2260-job-list.t
Problem: the  `flux module list` and `flux module stats` sub-commands are unnecessarily restricted to instance owner.
Open them to guests.
Fixes #5244
> allow guests to use flux module list, flux module stats

- src/cmd/flux-job.c
- src/shell/pty.c
- t/t2712-python-cli-alloc.t
Currently `flux job attach` skips watching the output eventlog when attaching to an interactive pty because all job output is presumed to go through the pty. However, this means error messages posted as `log` events to the eventlog are ignored, which can result in confusing behavior as described in #5272. It would also be valuable to see regular output from tasks, since brokers in a flux-alloc instance may also issue errors or warnings that would otherwise be suppressed.
This PR changes `flux job attach` so it always watches the output eventlog. Special handling for the pty case is required:
- add missing `\r` for output and log messages since the terminal is assumed to be in raw mode
- skip output for rank 0 when the pty is being captured to avoid duplication
Otherwise, the code is …
> do not suppress job shell and broker errors with `flux alloc`

- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/job/__init__.py
- src/bindings/python/flux/job/kvslookup.py
- src/modules/job-info/lookup.c
- t/Makefile.am
- t/python/t0010-job.py
- t/python/t0014-job-kvslookup.py
- t/t2230-job-info-lookup.t
Per #5176, it'd be nice to have a convenience API for `job-info.lookup` as doing the rpcs and parsing out the results can be inconvenient, especially when you want to do multiple lookups.
On the command line this is `flux job info` b/c of the `job-info` module, but we created the "JobInfo" class for the data coming back from `job-list` module in the Python bindings.  In hindsight perhaps an unfortunate naming.
So ... I eventually settled on calling this getting "job metadata".  The naming of this can be debated of course.  I think it's a good name for things like "jobspec", "eventlog", "R".  It's sort of a meh name for "guest.input/output".  But presumably we'll someday have the solution for https://github.com/flux-framework/flux-core/issues/4854, so maybe it doesn't matter as much on …
> python: support convenience API for `job-info.lookup` RPC / "flux job info"

- t/t0014-runlevel.t
- t/t3203-instance-recovery.t
Problem: flux-start will kill all brokers after the first broker exits.  By default the timeout to kill all the other brokers
is 20s.  A broker in a test in t3203-instance-recovery.t would sometimes be killed due to a slow running rc3 cleanup.  This would
lead to a invalid test error.
Solution: Increase the kill timeout to 300s with the--test-exit-timeout option.
Fixes https://github.com/flux-framework/flux-core/issues/5290
Also increase the timeout in one other test that timed out.
> testsuite: fix occasional broker kill error

- src/cmd/flux-exec.c
- src/common/libsubprocess/fork.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/subprocess.c
- t/t0005-exec.t
Problem: When a subprocess fails the "failed_errno" value is set and can be returned in `flux_subprocess_fail_errno()`.  It would
be convenient if there was an error message to describe the error in more detail.
Solution: Internally support a new "failed_error" field which can store a text message describing the error in more detail.  Generally speaking, always fill this with a text message when "failed_errno" is also set.
Set user friendly error string in many cases throughout libsubprocess.
Support a new `flux_subprocess_fail_error()` to retrieve this error message.
Add corner case unit tests.
Fixes https://github.com/flux-framework/flux-core/issues/5233
----
Extra notes:
I think the biggest review question in this PR will be my choice of "error message" throughout.  And if I should add …
> libsubprocess: support user friendly error string 

- src/bindings/python/flux/job/JobID.py
- src/common/libjob/id.c
- src/common/libjob/job.h
- src/common/libutil/fluid.c
- src/common/libutil/fluid.h
- src/common/libutil/test/fluid.c
- src/modules/job-exec/job-exec.c
- src/shell/svc.c
Problem: an f58 job encoding that does not change depending on locale configuration is potentially useful and a solution to the problem discussed in #5257.
This PR introduces `f58plain` encoding and uses it in the shell job service name.
> add f58plain job encoding

- src/shell/log.c
- src/shell/signals.c
Per discussion in #5210, but I'm not 100% sure this completely fixes #5210, but it is a fix nonetheless.
Problem: If a trapped signal (SIGTERM, SIGINT, SIGALRM) is caught before all shell tasks have been launched, unexpected behavior could happen.  For example, some tasks could be run without being sent the signal.  The signal can also interrupt initial setup and cause other problems.
Solution: In this unlikely situation, kill current tasks via SIGKILL and exit.  If this situation is hit outside of testing conditions, it is assumed the job was messed up and we want to just kill it.
> shell: document signal race

- src/modules/job-manager/Makefile.am
- src/modules/job-manager/plugins/alloc-check.c
- t/Makefile.am
- t/t2304-sched-simple-alloc-check.t
This adds a jobtap plugin called `alloc-check` that raises an exception on a job when it is allocated resources by the scheduler that were allocated to another job and have not yet been freed.  I thought this would be useful while chasing flux-framework/flux-sched#1043.
Example - reproducing the above issue:
```toml
[job-manager]
plugins = [
{ load = "perilog.so" },
{ load = "alloc-check.so" },
]
epilog.command = [ "flux", "perilog-run", "epilog", "-e", "sleep,2" ]
```
```console
$ flux start -o,--config-path=test.toml
ƒ(s=1,d=0) $ flux module remove sched-simple
ƒ(s=1,d=0) $ flux module load sched-fluxion-resource
ƒ(s=1,d=0) $ flux module load sched-fluxion-qmanager
ƒ(s=1,d=0) $ for i in $(seq 2); do flux run -N1 -x -t1s sleep inf; done
1.045s: job.exception type=timeout severity=0 …
```
> job-manager: add alloc-check plugin

- src/bindings/python/flux/job/kvslookup.py
- t/python/t0014-job-kvslookup.py
Support something similar to the `--original` option in `flux job info`
There are multiple approaches and I went with the approach of make the `libjob` `unwrap_string()` function public.  Hopefully not a unpopular decision.
There were several reasons:
0) `libjob`'s `unwrap_string()` function easily handles the `flux-core` built w/ and w/o `flux-security` case.
1) while possible to implement the `unwrap_string()`'s `flux-security` code in python via the security module, in `libjob` there is an implementation of the function `sign_none_unwrap()` for the "no flux security" case, which would probably be hard to re-do in python (and minimally annoying to re-do).
2) I realized `unwrap_string()` is used in the job shell, it made me think there may be users of `unwrap_string()` in the future …
> python: support "original" option in job kvslookup module

- src/modules/job-manager/alloc.c
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/raise.c
- src/modules/job-manager/raise.h
Problem: the job manager publishes a job-exception event message when an exception is raised via the job-manager.raise RPC, but not when a jobtap plugin calls flux_jobtap_raise_exception().
Publish the job-exception event when a jobtap plugin calls flux_jobtap_raise_exception().
Fixes #5306
> job-manager: publish event on jobtap exception

- src/cmd/flux-job.c
- t/job-manager/plugins/perilog-test.c
- t/t2500-job-attach.t
This PR fixes the issue described in #5313. Instead of printing `starting` after the first `prolog-finish` event, a counter is kept so that the attach status prints `waiting for prolog` until the last expected `prolog-finish` event.
> flux-job: fix attach notification with multiple prolog-start events

- NEWS.md
Replease notes for 0.52. Change as needed!
This assumes the PRs added to the 0.52 milestone are going to be merged first.
> NEWS.md: add release notes for v0.52.0

- src/modules/job-info/lookup.c
- t/t2230-job-info-lookup.t
Per #5303.  Multiple approaches on fixing this, I elected to ignore duplicates.  The main reason is because the lookup result is a json object.  So duplicate keys sort of make no sense on a return (i.e. in a json object you can't put the same key in the object twice).
Could have done a "are there duplicates?" check instead and return EINVAL, but figured it's a costly check for a (hopefully) rare corner case.
Note, issue #5305 is highly related to this, but a little different.  Going to solve that in follow up PR.
>  job-info: ignore duplicate lookup keys

- src/cmd/flux-job.c
- t/t2260-job-list.t
- t/t2501-job-status.t
I noticed that `flux job status` treats all job exceptions as fatal. This is incorrect behavior since a job can get an exception with severity > 0 and still be "successful" i.e. exit with a 0 status.
This PR fixes the behavior and adds a simple test.
> flux-job: fix `flux job status` handling of nonfatal exceptions

- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog.t
This PR fixes a couple issues in the handling of exceptions in the `perilog` plugin:
- Only kill the prolog when an exception is received and the prolog is running. Ignore exceptions during the epilog.
- Only kill the prolog for fatal job exceptions, i.e. ignore all job exceptions with severity > 0.
This will require flux-framework/flux-sched#1047 to be merged so that the flux-sched checks won't fail.
> job-manager: fix prolog/epilog exception handling

- src/cmd/flux-job.c
- t/t2230-job-info-lookup.t
Problem: In flux job info and the --original option, it is assumed that every response of "J" is meant to be "jobspec".  However, that
is not a safe assumption, as the user may have input both "J" and "jobspec".
Solution: When outputting the results from a flux job info lookup, output results based on the keys input by the user, not by the keys used during lookup.
Fixes https://github.com/flux-framework/flux-core/issues/5305
Built on top of #5317
> flux-job: fix invalid --original info output

- src/bindings/python/flux/job/kvs.py
- src/bindings/python/flux/kvs.py
- t/Makefile.am
- t/issues/t5308-kvsdir-initial-path.py
- t/python/t0005-kvs.py
Per #5308.  Fix and add testing coverage that was missing before.
Nothing too extravagant about this fix.  It seems it was an  oversight since the initial implementation.  But as I note in #5308, this has the potential to break any code that was using it in the "buggy" way prior.  i.e.
```
dir = KVSDir(handle, path="foo.bar")
dir["foo.bar.a"] = 1
dir.commit()
```
before this created "foo.bar.a" and if we change it'll create "foo.bar.foo.bar.a".  Same with any other functions that underneath the covers write to the KVS via KVSDir (e.g. `fill()` object function) or anything that gets a KVSDir, such as `job_kvs()` or `kvs.get_dir()`.
I think it's low probability that this will cause a lot of breakage out there, but any breakage would be quite severe for said users.  Not sure if we want to …
> python: fix writes in KVSDir with initial paths

- src/bindings/python/flux/kvs.py
- t/python/t0005-kvs.py
Problem: KVSDir can be passed an initial path when initialized.  This
path is utilized as a contextual path for reads and writes.  However,
it was not used for the exists() class function.
Solution: Use the initial path when checking a key in exists().
---
Notes: this was simply missed in #5322 b/c it wasn't a "write" thingie.  Looked through all the KVSDir functions and I think everything else works as intended.
> python: fix exists in KVSDir with initial paths

- src/bindings/python/flux/kvs.py
- t/python/t0005-kvs.py
- t/python/t0013-job-list.py
- t/python/t0014-job-kvslookup.py
The first 4 commits here at coverage / cleanups I noticed while working on the prior python kvs module doc PR.
The final two commits were things I noticed and I believe are wrong.  Probably very early "how should we integrate this all in together" mistakes from 2018 in f4c9e2d6d9bf1da1af0f4a333f81bd436cd7f082
Whether we should do them is a different question, i.e. breaking behavior.  I think very low odds this change matters and would break users.  Also, since we did break some behavior via https://github.com/flux-framework/flux-core/pull/5322, I figure what the heck.
> python: do not return int status in kvs functions     

- src/bindings/python/flux/kvs.py
- src/common/libkvs/kvs.h
- t/python/t0005-kvs.py
Added a bit more in there.  Didn't add it for everything, sorta picked and choosed, notably not adding docs for the direct access to C-bindings stuffs b/c that stuff is mostly just used by `KVSDir`.  The readthedocs shouldn't be quite so bare now.
> python: add extra documentation to kvs.py module

- src/bindings/python/flux/kvs.py
- t/python/t0005-kvs.py
Problem: When a commit error happens on a KVS transaction, an error is raised.  This means that the internal KVS transaction (created via calls to put(), put_mkdir(), etc.) does not get cleared.  Therefore a subsequent call the commit() would redo the the transaction.  If the transaction is the cause of the commit failure, no subsequent commits can ever work.
Solution: If an exeption is raised during the commit, clear the internal transactions before returning the exception to the user.
Fixes #5333
> python: clear KVS txns on commit error

- src/modules/resource/inventory.c
- t/t2312-resource-exclude.t
Problem: when _R_ is acquired dynamically, the resource module refuses to process exclusions.
`inventory_targets_to_ranks()` fails if _R_ is not set, but _R_ is only used if the input fails to parse as an idset.
Move the check for NULL R into the hostnames to ranks mapping block where it is used.  This allows an exclusion set specified as an idset  to be decoded when R is dynamically discovered.
Fixes #5337
> resource: fix problem with exclusions when R is dynamically discovered

- doc/man1/flux-broker.rst
- doc/man5/flux-config-resource.rst
- src/modules/resource/acquire.c
- src/modules/resource/exclude.c
- src/modules/resource/exclude.h
- src/modules/resource/resource.c
- t/t2303-sched-hello.t
- t/t2311-resource-drain.t
- t/t2312-resource-exclude.t
- t/t2313-resource-acquire.t
Problem: the resource module contains code to process live changes to the configured exclude set, but as discussed in flux-framework/rfc#383, there is no longer much of a use case now that flux-batch(1) et al have a `--conf` option that can configure exclusions on the command line for subinstances.
The extra code includes posting `exclude`/`unexclude` events to the KVS resource.eventlog _synchronously_ by calling the internal function `reslog_sync()`.  This makes the resource module unresponsive while the KVS commit completes.
This extra complexity is no longer justified.  Remove.
Update tests.
There are also a couple of incidental man page updates here which could be split off to a separate pr if desired.
> resource: ignore live resource.exclude changes

- src/bindings/python/_flux/callbacks.h
- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/future.py
- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/job/wait.py
- src/bindings/python/flux/rpc.py
- src/common/libflux/composite_future.c
- t/python/t0012-futures.py
Problem: There is no current support for easily building extensible Future objects in the Python API, e.g. to return a Future that may be composed of a series of multiple RPCs or other actions with a single result.
Add a `FutureExt` class, which is derived from `Future`, but takes an initialization callback like `flux_future_t` which can be used to initiate the composite series of actions that should result in fulfillment of the returned `Future`. The `FutureExt` class also support fulfilling a Future with any Python object that is JSON serializable, and the `FutureExt.get()` method is overloaded to return the fulfilled value. This makes it simple to return a result from Python to Python using `FutureExt`.
A simple example is used in testing and copied here for demonstration purposes: a …
> python: add FutureExt class for extensible futures from python

- src/bindings/python/flux/future.py
This PR fixes a frustrating issue I was hitting while working on #5332 which uses the `FutureExt` class.
The crux of the issue is that a Python `Future` ffi handle for the `then_cb` (`future.cb_handle`) can be garbage collected before the `Future` itself is. If the C `flux_future_t` can be fufilled multiple times, or if the future was not reset, then the reactor may try to invoke the Python `continuation_callback()` again, and Python throws a little fit and aborts since the ffi handle is no longer valid.
Thanks to help from @trws, the problem was narrowed down to the `finally` block in `continuation_callback()`:
https://github.com/flux-framework/flux-core/blob/837104c07ee7400bb2f3413c9bd0b04b971143bd/src/bindings/python/flux/future.py#L46-L52
Since `py_future.cb_handle` is set to `None`, …
> python: fix potential gc of Future ffi handle before Future destruction

- src/bindings/python/flux/job/event.py
- src/cmd/flux-job.c
- src/common/libjob/result.c
- src/modules/job-list/job_state.c
- src/modules/job-manager/raise.c
- src/modules/job-manager/start.c
- src/modules/job-manager/wait.c
- t/python/t0023-executor.py
- t/t2260-job-list.t
Per #5314, the job-manager would output an empty string "note" for an exception when a note is not specified.  But RFC21 says that the note is optional.  So do not output this empty string "note".
Two test fallouts from this.  The job result code in `libjob` always assumed a note would be there.  And some job-list tests would sometimes assume a note would be empty string instead of "null".
Doing an audit on the code, I think there is one more place where there could be a problem but it wasn't covered in tests.  It's in the Python cli base code.
Also some misc cleanup in `libjob` when I was looking at the code and trying to figure why it failed the way it did.
> job-manager: make exception note a requirement

- src/common/libsdexec/parse.c
- src/modules/sdexec/sdexec.c
- t/t5000-valgrind.t
- t/valgrind/workload.d/job-sdexec
This mops up some memory errors found by manually running sdexec and sdbus tests under valgrind and revives @chu11's valgrind "workload" script that runs jobs under sdexec.
> sdexec: fix memory leaks

- doc/man1/flux-job.rst
- doc/test/spell.en.pws
- src/cmd/flux-job.c
- t/t2500-job-attach.t
This PR makes it a little more likely that the `flux job attach` status line will be suppressed if its output is not desirable.
Since we really only want to display the status line if `flux job attach` is actually being run interactively, only enable it if all of `stdout`, `stderr`, and `stdin` are attached to a tty. Also add a `FLUX_ATTACH_NONINTERACTIVE` environment variable that always suppresses the status line for environments like ATS where a pty is used to run jobs but the output is logged. In this case the status line generates a lot of output since theres a timer updated every second.
> flux-job: suppress the `attach` status line in more situations

- src/bindings/python/flux/cli/base.py
- src/cmd/flux-job.c
- src/modules/job-list/job_state.c
- t/t2304-sched-simple-alloc-check.t
As pointed out in #5307, `flux job attach` and `flux jobs` ignore fatal job exceptions if the job has a `finish` event with exit status `0`. This doesn't agree with `flux job wait` and `flux job status`, which exit with failure for any fatal job exception.
Given that a fatal exception by definition probably indicates that the job has failed in some way regardless if the job tasks finished successfully, update the behavior of these commands (as well as `flux submit` and `flux bulksubmit`) to exit with failure for any fatal job exception. Additionally, `flux jobs` now only reports a successful job if the job finished with `status=0` _and_ there were no fatal job exceptions.
Because the "alloc check" tests already generated the failing case here (job with fatal job exception but all tasks …
> ensure flux utilities agree that a job with a fatal exception has failed

- src/modules/job-manager/event.c
- t/t2212-job-manager-plugins.t
This PR fixes #5345, where a job that is canceled before an `alloc` event could become inactive (have a `clean` event posted) even while an epilog action was in progress (outstanding `epilog-start` event).
This PR simply checks for an enqueued `epilog-start` event or `perilog_active` count before allowing the `clean` event to be emitted. Also adds a test that reproduces the original issue.
> job-manager: prevent jobs with outstanding epilog-start events from becoming inactive

- doc/man1/flux-shell.rst
- doc/test/spell.en.pws
- src/shell/Makefile.am
- src/shell/affinity.c
- src/shell/affinity.h
- src/shell/gpubind.c
- t/t2604-job-shell-affinity.t
This PR adds support for `gpu-affinity=map:LIST`. This can come in handy for benchmarking, testing, etc. Also, since `-o cpu-affinity` supports `map:`, it seemed like GPUs should be able to assigned in this way.
As a side effect of the approach, #5352 was also fixed.
> shell: support `-o gpu-affinity=map:LIST`

- .readthedocs.yaml
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/job/__init__.py
- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/job/output.py
- t/Makefile.am
- t/python/t0010-job.py
- t/python/t0012-futures.py
- t/python/t0015-job-output.py
This PR adds a new set of interfaces to the Python API for watching and fetching job output.
The `FutureExt` class is used here, so this is based on #5330.
The new functions are all documented in the code, but summarized here for convenience. All functions can be called on active or inactive jobs. If the job is inactive or starting, the functions will wait until the output eventlog is available to start watching it. (except for `job_output(nowait=True)` in which case a `FileNotFoundError` exception is raised (since output eventlog does not exist).
* `job_output(flux_handle, jobid, tasks="*", labelio=False, nowait=False, log_stderr_level=LOG_TRACE)`: simple function for fetching job output synchronously in one call. Returns a `JobOutput` tuple with members `stdout`, `stderr`, and `log`, in …
> python: add API for job output

- etc/completions/flux.pre
- src/cmd/flux-job.c
- src/common/libjob/info.c
- src/common/libjob/job.h
- src/modules/job-info/guest_watch.c
- src/modules/job-info/watch.c
- t/t1007-kvs-lookup-watch.t
- t/t2231-job-info-eventlog-watch.t
- t/t2607-job-shell-input.t
- t/t2800-jobs-cmd.t
Per #5301
Some comments:
- pondered if this should be the default or if a flag / option was best.  Eventually settled on the latter as there may be scenarios we do not want to "waitcreate"
- the "style" in which tests are written in t2231-job-info-eventlog-watch.t is pretty ancient.  It could be cleaned up.  But for this PR, kept the style as is.   Figured cleanup / update can be for a follow up PR.
>  job-info: support WAITCREATE on eventlog watch 

- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/job/__init__.py
- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/job/watcher.py
- src/bindings/python/flux/progress.py
- t/python/t0010-job.py
- t/t2710-python-cli-submit.t
This PR abstracts the `SubmitBulkCmd` "watch" functionality into a `JobWatcher` class, which uses the `flux.job.output` functionality for the output watching, and then uses this new class to support `submit` and `bulksubmit` `--watch` and `--wait` functionality.
This class can then be used for other utilities in the future, e.g. something like a `flux watch`.
There's no extra tests of the `JobWatcher` class at this point. Instead the existing bulksubmit and submit tests are used to test operation of the class.
> python: add JobWatcher class and use for `submit` and `bulksubmit` `--watch` functionality

- doc/Makefile.am
- doc/man1/flux-watch.rst
- doc/manpages.py
- etc/completions/flux.pre
- src/bindings/python/flux/progress.py
- src/bindings/python/flux/util.py
- src/cmd/Makefile.am
- src/cmd/flux-jobs.py
- src/cmd/flux-pgrep.py
- src/cmd/flux-pstree.py
- src/cmd/flux-watch.py
- t/Makefile.am
- t/t2813-flux-watch.t
Putting this up as a WIP, in case others have suggestions or comments on this added command.
This PR adds a new command, `flux watch` for lack of a better name (I asked ChatGPT and one of its suggestions was `flux gazemancer` but that was just a bit too outlandish). This command basically does the same thing as `flux submit --watch` but can monitor all running jobs, all inactive jobs, or a specific set of jobs. (It has a similar set of options as `flux jobs`, `flux pstree` etc.).
This allows users to submit many jobs then watch then with `flux watch`, e.g. at the end of a batch script, or if you need to run multiple `submit` or `bulksubmit` commands to submit a set of jobs and then want to monitor them all, e.g. `flux watch --all --progress`...
I still need to think more about the set of …
> cmd: add flux-watch(1)

- doc/man5/flux-config-exec.rst
- doc/test/spell.en.pws
- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/exec_config.h
- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/oom.c
- t/Makefile.am
- t/shell/plugins/setopt.c
- t/t2410-sdexec-memlimit.t
- t/t2411-sdexec-job.t
This adds some configuration that allows cgroups MemoryMax to be set for jobs.  For example, on my test system I am setting
```toml
[systemd]
enable = true
[exec]
imp = "/usr/lib/aarch64-linux-gnu/flux/flux-imp"
service = "sdexec"
[exec.sdexec-properties]
MemoryMax = "80%"
```
When I run a  sleep job on a 2g node, systemd neatly displays
```
garlick@picl1:~$ fsystemctl status imp-shell-1-fUdKSFCzEes.service
● imp-shell-1-fUdKSFCzEes.service - User workload
Loaded: loaded (/run/user/500/systemd/transient/imp-shell-1-fUdKSFCzEes.se>
Transient: yes
Active: active (running) since Fri 2023-07-28 14:01:23 PDT; 14s ago
Main PID: 407340 (flux-imp)
Tasks: 3 (limit: 1599)
Memory: 2.2M (max: 1.4G)
CPU: 127ms
CGroup: /user.slice/user-500.slice/user@500.service/app.slice/imp-shell-1->
├─407340 …
```
> job-exec: allow job memory limits to be set

- src/bindings/python/flux/kvs.py
- t/Makefile.am
- t/issues/t5368-kvs-commit-clear.py
Problem: The internal KVS transaction is only cleared when commit()
causes an error.  It should be cleared after every call to commit().
Clear the internal KVS transaction after every call to commit().
Also fixed up a corner case I saw, I think the future needs to be destroyed too.
> python: clear kvs txn after all commits

- src/bindings/python/flux/kvs.py
- t/python/t0005-kvs.py
while working on other stuff, noticed that `flux.kvs.isdir()` in the python kvs module returns ENOENT if a key is missing.  I believe this is inconsistent to how one normally thinks of these kinds of functions.  If the key does not exist, I think the function should just return False.
At the same time I noticed this, it ends up there was no `isdir()` coverage in the python tests, so adding some.
If folks think the logic should not be changed, I can still add the tests (although tweaked a bit).
> python: have kvs.isdir() return False if key missing

- .mergify.yml
- src/test/docker-deploy.sh
Apparently had a mistake in there.  On merge to master, the new default bookworm containers all went up, but the 386 version got tagged latest rather than the amd64 version.  This should fix that.
> docker-deploy: only push latest when arch is 64-bit

- .github/workflows/main.yml
Add the marge_group trigger in case we want to test out the github native merge queue functionality.  Just add that in, has no effect until and unless we enable the merge queue branch protection.
> actions: add merge_group trigger

- t/t0005-exec.t
Problem: If the signal in the signal forwarding test in t0005-exec.t is delivered after the "hi" sentinel is printed but before sleep(1) is executed, then bash ignores the signal and the test will timeout and fail.
To prevent the race use awk instead of a bash script, so that there is no point where the delivered signal will not be handled.  The awk script prints the sentinel then reads from a fifo in order to block indefinitely (stdin in sharness may be closed), so there are no extra subprocesses involved.
Fixes #5382
> testsuite: fix race in t0005-exec.t signal test

- src/bindings/python/flux/kvs.py
- t/python/t0005-kvs.py
GAH, another "initial path" bug in KVSDir.  I missed this one in the `__delitem__` item accessor.
I stole some cleanup from PR #5373 to put at the beginning of this PR since it would make the test numbering update easier.  This one now comes first in the chain of PRs.
> python: fix __delitem__ in KVSDir with initial paths

- src/broker/Makefile.am
- src/broker/broker.c
- src/broker/broker.h
- src/broker/brokercfg.c
- src/broker/brokercfg.h
- src/broker/modhash.c
- src/broker/modhash.h
- src/broker/module.c
- src/broker/module.h
- src/broker/publisher.c
- src/common/libflux/attr.c
- src/common/libflux/attr.h
- src/common/libflux/test/attr.c
- t/module/testmod.c
- t/t0003-module.t
- t/t2500-job-attach.t
This was some broker cleanup that was the beginning of  work to create a "module loader" standalone helper executable that could be used to optionally load broker modules in a separate address space.
I didn't get that done, but this cleanup is progress on its own.
> broker: refactor broker module loading code and fix minor bugs

- t/t2412-sdexec-perilog.t
Problem: the t2412-sdexec-perilog.t test script expects exactly one space between output columns but this fails in some environments.
The failing environment is a Ubuntu 22.04 LTS system running systemd 249.11-0ubuntu3.9.
Allow any number of spaces between the columns.
> testsuite: relax systemctl output parsing

- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- t/Makefile.am
- t/job-manager/plugins/jobspec-update.c
- t/t2212-job-manager-plugins.t
This PR adds a convenience function for jobtap plugins that want to post a `jobspec-update` event.
The benefit of this function over using `flux_jobtap_event_post_pack(3)` directly is two-fold:
- The `jobspec-update` event is delayed until after the callback for the current plugin returns, avoiding an update of the jobspec while the callback may be holding some pointers to it as a result of `flux_plugin_arg_unpack()`.
- It allows some validation of the keys being updated (e.g. RFC 21 specifies they must start with `attributes.`)
The addition of a basic test here also exercises the processing of the `jobspec-update` event in the job manager, which doesn't seem to be tested at all presently.
> job-manager: add flux_jobtap_jobspec_update_pack(3)

- .github/workflows/main.yml
- src/test/generate-matrix.py
This is a step-1 to supporting arm64 a bit better in CI.  If this is
fast enough, maybe we can get some occasional smoke tests on top of it
or something but it should make getting dev containers going easier at
the least.
> matrix: add arm64 install-only builder

- t/t2260-job-list.t
- t/t2800-jobs-cmd.t
Problem: In commit
c851ecbb34d7a741030c25fd12a38e0c11f84b4c
a job signal race was worked around in t2800-jobs-cmd.t.  The same fix should have been applied to t2260-job-list.t but was not.
Solution: Carry over the same fixes to t2260-job-list.t.  Also add a small comment in t2800-jobs-cmd.t for why the signal race workaround isn't needed in one location.
Fixes #5399
> testsuite: handle job signal race in more tests

- .github/workflows/main.yml
It got really, really close, but didn't quite finish in time on the master build.  Give it a bit more of a buffer before canceling.
> extend ci-checks timeout for arm64 build

- src/modules/job-manager/plugins/limit-duration.c
- t/t2221-job-manager-limit-duration.t
This PR fixes an outdated design in the `limit-duration` job manager plugin which explicitly allows jobs with unlimited duration through, even if there is an applicable queue or general limit. This was probably the case so that a default could later be applied to the job, but since default are now applied in the job frobnicator at ingest time, this is no longer necessary and allows jobs with unlimited duration to submitted if there is a limit but no duration default.
> job-manager: fix duration limit check for jobs with unset/unlimited duration

- src/modules/job-manager/event.c
- src/modules/job-manager/job.c
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- t/job-manager/plugins/jobspec-update.c
- t/t2212-job-manager-plugins.t
Almost all jobspec updates don't make any sense after the job has been allocated resources and the job starts running, but as noted by @chu11, there is currently nothing the job manager that prevents a `jobspec-update` event in job state from modifying the redacted jobspec.
This PR makes it an error if a `jobspec-update` event occurs in `RUN`, `CLEANUP` or `INACTIVE` states (actually, any event is prevented if the job is inactive now by checking the `eventlog_inactive` flag)
There is also one commit that adds missing support for bumping a job in `SCHED` back to `PRIORITY` on a `jobspec-update` event so that the priority can be recalculated and the `alloc` request restarted, but now I'm wondering if that commit belongs here or in a future PR that adds support for a job manager update …
> job-manager: prevent jobspec-update events after a job has resources

- src/modules/job-list/job_data.c
- src/modules/job-list/job_data.h
- src/modules/job-list/job_state.c
- src/modules/job-list/stats.c
- src/modules/job-list/stats.h
- src/modules/job-list/test/job_data.c
- t/Makefile.am
- t/job-manager/plugins/jobspec-update-job-list.c
- t/t2260-job-list.t
Per #4404, built on top of #5407
There were some tricky parts that took me awhile to refactor through, but overall, the commit series shouldn't look too strange.
I didn't list this as WIP as I think this could go in as is.  But perhaps we want to wait until work on #4844 is further along so we can test in tandem??
> job-list: support jobspec-update event

- .github/workflows/main.yml
- .typos.toml
- NEWS.md
- src/broker/test/topology.c
- src/cmd/flux-job.c
- src/common/libflux/fripp.h
- src/common/libflux/stats.h
- src/common/libutil/test/dirwalk.c
- src/modules/content-s3/s3.c
- src/modules/kvs-watch/kvs-watch.c
- src/modules/kvs/lookup.h
- src/modules/kvs/test/kvsroot.c
nothing fancy here, except I chose to add the british "requestor" to the false positives list, instead of change to use the american "requester".  Could fix of course ... we did away with the british "cancelled" awhile back.
Update: FWIW
```
>git grep -i "requestor" | wc -l
13
>git grep -i "requester" | wc -l
2
```
Edit:
Ok, googling more, I guess in computer programming circles "requestor" is liked more.  But I guess it doesn't really matter.
> actions: update typo checker version

- src/modules/job-manager/job.c
- src/modules/job-manager/test/job.c
Problem: An update to RFC21 allows all jobspec fields to be updated by a jobspec-update event.  However not all fields are allowed to be updated via the validate_jobspec_updates() function.
Solution: Allow all fields in current legal jobspecs to be updated.
-- 
A split off from #5418
> job-manager: support jobspec update to all fields

- src/modules/job-list/job_data.c
- src/modules/job-list/job_data.h
- src/modules/job-list/test/job_data.c
- t/job-manager/plugins/jobspec-update-job-list.c
- t/t2260-job-list.t
Per a recent update to RFC21, all fields in a jobspec can now be updated via a jobspec-update event.
> job-list: allow updates to all of jobspec

- src/common/libpmi/simple_server.c
- src/common/libpmi/simple_server.h
- src/common/libpmi/test/server_thread.c
- src/shell/pmi/pmi.c
Problem: on a slurm system, it's easy to trip over the libpmi2.so that they install in libdir.
To get around that library's quirk of ignoring version negotiation, we already disabled PMI version negotiation in our server.   This converts a hang into a hard failure.  However, we didn't have a way for the protocol engine to warn the user what we suspect may be the cause.
Add a new callback so that the shell pmi plugin can call `shell_warn()` when the protocol engine encounters this situation:
```
$ flux run  -N2 flux pmi --method=libpmi2
flux-pmi: /lib/x86_64-linux-gnu/libpmi2.so: pmi error 14
flux-pmi: /lib/x86_64-linux-gnu/libpmi2.so: pmi error 14
0.047s: flux-shell[0]:  WARN: pmi-simple: is application unintentionally using slurm libpmi2.so?
flux-job: task(s) exited with exit code 1
``` …
> shell/pmi: warn if application might be using slurm's libpmi2.so

- doc/man1/flux-exec.rst
- src/cmd/flux-exec.c
- src/cmd/flux-perilog-run.py
- t/Makefile.am
- t/system/0002-exec-with-imp.t
- t/t0005-exec.t
As suggested offline by @garlick, add a `--with-imp` convenience option to both `flux exec` and `flux perilog-run` that prepends `/path/to/flux-imp run` (fetched from instance configuration) to the command to be executed. Note this requires that the command be configured in the IMP `run` config. At this time this is mostly for `prolog` and `epilog` scripts.
In `flux-exec(1)`, when the `--with-imp` option is used or if `flux-imp` is the first argument of the command, `flux-imp kill` will be used to forward signals to remote processes instead of `flux_subprocess_kill()`. This allows the signals to actually be delivered to the processes spawned by `flux exec` since they are likely running with privilege.
Tests for this feature are added to the "system" ci tests since the IMP is required for …
> cmd: add --with-imp options to flux-exec(1) and flux-perilog-run(1)

- src/cmd/flux-job.c
- src/cmd/flux-perilog-run.py
- src/modules/job-manager/plugins/perilog.c
- t/system/0002-exec-with-imp.t
- t/t2274-manager-perilog.t
This PR switches the `flux-perilog-run.py` script to run local and "per rank" prolog and epilog processes under a timeout. By default the timeout is 30m (maybe should be 1h or unlimited by default?), but a `-t, --timeout=FSD` option is added for timeout customization.
In order to more easily support execution of multiple processes under a timeout in this script, it has pretty much been rewritten to use `asyncio`. This has the added benefit that now all local and per-rank executions are done in parallel. There was a bit of other work necessary to make the signaling of timed out processes more reliable, etc.
> flux-perilog-run: support prolog and epilog timeouts (default 30m)

- src/cmd/flux-perilog-run.py
- t/t2274-manager-perilog.t
This PR updates the `flux perilog-run` script to avoid running the prolog or epilog on offline ranks, which is guaranteed to fail anyway. When this occurs, a message is logged and the command exits with nonzero status (as if the prolog/epilog failed on the offline ranks), but by default offline ranks are not drained (or have their drain reason updated). A new `-D, --drain-offline` option is provided which causes the command to update/add a drain reason of, .e.g. `offline for JOBID epilog`.
> cmd: flux-perilog-run: avoid running prolog/epilog on offline ranks

- src/modules/job-list/job-list.c
- src/modules/job-list/stats.c
- src/modules/job-list/stats.h
- t/Makefile.am
- t/t2262-job-list-stats.t
As discussed in #5400, a streaming version of `job-list.job-stats` would be useful and could let us deprecate the `job-stats` events, reducing job manager complexity and background noise on the overlay network.
This modifies `job-list.job-stats` so if the FLUX_RPC_STREAMING flag is used, responses are sent whenever job stats change (but no more frequently than every 200ms), and switches `flux-top(1)` to use the streaming responses to detect job activity in place of subscribing to `job-stats` events.
Marked as WIP pending the addition of tests and any initial feedback.
> job-list: support streaming job-stats RPC

- src/cmd/top/summary_pane.c
- src/cmd/top/top.c
- src/cmd/top/top.h
Problem: flux-top(1) subscribes to job-state events to detect job activity and trigger other queries, but now that the `job-stats` RPC is streamable, there is no need.
Drop the job-state subscription and instead drive queries with streaming `job-stats` responses.
> flux-top: use streaming job-stats RPC

- doc/man7/flux-jobtap-plugins.rst
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/update.c
- t/t2290-job-update.t
This PR is some minor cleanup for the job-manager update service.
Also, add missing documentation in `flux-jobtap-plugins(7)`.
> job-manager: update: cleanup, small fixes, and documentation

- t/t2602-job-shell.t
Problem: Every once in awhile t2602-job-shell.t fails with:
FAIL: t2602-job-shell.t 22 - job-shell: test shell kill event handling: numeric signal
On a busy system.
The test checks for a non-zero status but the logs show
1694098677.862467 finish status=0
The suspicion is that the job, which is only 60 seconds long, may actually run to completion before the signal is sent / received on a busy system.
Solution: Increase the job from 60 seconds to 300 seconds.
> testsuite: increase sleep time in tests

- src/bindings/python/flux/job/kvslookup.py
- src/cmd/flux-job.c
- src/cmd/flux-update.py
- t/python/t0014-job-kvslookup.py
- t/t2230-job-info-lookup.t
The jobspec returned by `flux job info` is the one stored in the KVS, which may differ from what is internally "viewed" by flux components due to `jobspec-update` events.  Notably, the jobspec returned may not be consistent to what is returned via `flux jobs`.
This PR will make `flux job info` return an updated jobspec by default.
Added a `--noupdate` option to get the version stored in the KVS.  I'm not super in love with this option name.  I considered `--kvs`, but that was confusing give Python binding function names like ("job_kvs_lookup()").  `--stored` seemed dumb too.  Ehhh ... any better ideas?  I didn't want the option to be `--update` b/c I wanted the default to be the updated one.
Also added support in the Python bindings.
Update `flux-update`, as it no longer needs to apply …
> flux-job: get updated version of jobspec

- src/modules/content-files/content-files.c
- src/modules/content-s3/content-s3.c
- src/modules/content-sqlite/content-sqlite.c
- src/modules/cron/cron.c
- src/modules/kvs/kvs.c
- src/modules/sched-simple/sched.c
- t/t0015-cron.t
- t/t1000-kvs.t
Per #5440, noticed there was inconsistency where some modules returned error on invalid module args, while others ignored invalid args.
Also noticed a few modules did not set errno = EINVAL when an invalid arg was specified.
> modules: consistently return error on invalid module arguments

- debian/control
- src/cmd/flux-keygen.c
Problem: libsodium is required by flux-keygen but it is not checked in configure.ac.
All we do with libsodium at this point is add its version to certicate metadata.  This was just "provenance", never actually used for anything, and not worth the extra dependency.  Rather than fix configure.ac, drop the libsodium version from flux-keygen(1) certificates.
Fixes #5445
> flux-keygen: drop libsodium requirement

- etc/rc1
- etc/rc3
- t/t0001-basic.t
Problem: If BASH_ENV is set to a script that is not "-e clean", flux's rc1 script exits immediately.
Drop -e from the shebang and add a "set -e" afterwards.
Fixes #5447
> rc: avoid startup problems when BASH_ENV is set

- config/am_check_pymod.m4
- config/ax_python_devel.m4
- configure.ac
This is an attempted fix for #5455. It switches to `packaging.version.Version` instead of `StrictVersion` in our custom `AM_CHECK_PYMOD` macro, and updates the autoconf-archive `ax_python_devel.m4` to the latest available, which _appears_ to have a fix for use of the deprecated `distutils` module.
> configure: avoid use of deprecated python distutils module

- config/am_check_pymod.m4
Problem: The Python packaging module is not standard, but configure uses it to compare versions, leading to an implicit new dependency.
Since distutils is not removed until Python 3.12, try distutils first then fall back to the packaging package. This will allow configure to continue to work on existing systems while also not breaking on Python 3.12.
Note: this is a proposed workaround for #5457. It will keep our current systems working without a new dependency, but will require Python 3.12 users to install the `packaging` module. :shrug:
> configure: use distutils if available to avoid extra python module dependency

- doc/man1/flux-update.rst
- doc/man7/flux-jobtap-plugins.rst
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/jobtap-internal.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/prioritize.c
- src/modules/job-manager/queue.c
- src/modules/job-manager/update.c
- t/Makefile.am
- t/t2291-job-update-queue.t
This is an experimental WIP that allows users to move a pending job to a new queue.
The list of valid queues and their current status (enabled/disabled) is currently private to `job-manager/queue.c`, so it isn't straightforward to add an `update-queue` plugin. The plugin would have to send an RPC back to the job-manager itself to query the list of queues and their states (and there's currently no way to do asynchronous work in one of these plugins), or a `jobtap` API call to "unpack" the queues or otherwise query them would be required.
Instead, this PR proposes a way for job manager components to register builtins directly from within their initialization routines, and pass some opaque data along that can be passed to all jobtap callbacks. This seems a little backwards, since it exposes …
> support update of job queue

- src/broker/broker.c
- src/broker/modhash.c
- src/broker/module.c
- src/broker/module.h
- src/broker/overlay.c
- src/broker/test/overlay.c
- src/common/libtestutil/Makefile.am
- src/common/libtestutil/util.c
- src/common/libzmqutil/Makefile.am
- src/common/libzmqutil/ev_zmq.c
- src/common/libzmqutil/monitor.c
- src/common/libzmqutil/monitor.h
- src/common/libzmqutil/mpart.c
- src/common/libzmqutil/mpart.h
- src/common/libzmqutil/msg_zsock.c
- src/common/libzmqutil/reactor.c
- src/common/libzmqutil/sockopt.c
- src/common/libzmqutil/sockopt.h
- src/common/libzmqutil/test/ev.c
- src/common/libzmqutil/test/mpart.c
- src/common/libzmqutil/test/msg_zsock.c
- src/common/libzmqutil/test/reactor.c
- src/common/libzmqutil/zap.c
- src/common/libzmqutil/zap.h
- src/connectors/shmem/shmem.c
Problem: libczmq is handy for prototyping 0MQ code in C but Flux is beyond prototyping now and we've outgrown it.  It is cleaner for us to use the libzmq API directly, since it is better documented and its error handling is more aligned with flux's (sets `errno` for example).
This PR migrates flux-core off of czmq classes, except for the `zcert`  (CURVE certificate handling) which will be handled in another PR.  Once that's in, we can drop the external czmq dependency.
> use zeromq interfaces directly where possible instead of via czmq

- src/common/librlist/rhwloc.c
- t/Makefile.am
- t/README.md
- t/python/t0015-job-output.py
- t/t0001-basic.t
- t/t2201-job-cmd.t
- t/t2800-jobs-instance-info.t
Running `make -j N check` where `N` is large can cause random and numerous test failures on systems with a lot of cores due to parallel hwloc topology discovery across many tests, each invoking many brokers. Presumably, some kind of kernel locks in sysfs slow down parallel hwloc discovery so much that tests time out and fail in unexpected ways. It is also disappointing that `make -j 32 check` runs slower on a 64 core system than an 8 core system.
Based on an idea by @wihobbs, I found that hwloc supports a `HWLOC_XMLFILE` environment variable that forces `hwloc_topology_load(3)` to use a file instead of reading the real system topology from scratch. However, in practice this environment variable does not seem reliable, and it is pretty easy to create our own similar environment variable. …
> allow hwloc topology to be loaded from a file with FLUX_HWLOC_XMLFILE

- configure.ac
- debian/control
- scripts/install-deps-deb.sh
- scripts/install-deps-rpm.sh
- src/test/docker/bookworm/Dockerfile
- src/test/docker/el7/Dockerfile
- src/test/docker/el8/Dockerfile
- src/test/docker/fedora33/Dockerfile
- src/test/docker/fedora34/Dockerfile
- src/test/docker/fedora35/Dockerfile
- src/test/docker/fedora38/Dockerfile
- src/test/docker/focal/Dockerfile
- src/test/docker/jammy/Dockerfile
Problem: libczmq is no longer used by flux-core but it's still required.
Drop it from` configure`, `make deb`, and `Dockerfile`s.
> drop libzcmq dependency

- src/bindings/python/flux/job/info.py
- t/t2272-job-begin-time.t
This proposes a fix for #5465 (the easy way). This adds special case handling of the `begin-time` dependencies in the `JobInfo` class. Other special cases could be added in the future, perhaps with a way to register plugins so that out-of-tree dependency modules could register their own post-processing of raw dependencies (though honestly I doubt this would ever be necessary)
Edit: Oh, I guess it would help to describe the method used here: `begin-time=<timestamp>` is replaced with `begin@<datetime>` where `datetime` is 
- The time if `datetime` is today
- The datetime as MMMDD-HH:MM (e.g. `Sep26-17:00`) if `datetime` is tomorrow or later
- Seconds are only displayed if they are nonzero.
> improve begin-time representation in `flux-jobs(1)` output

- .github/workflows/main.yml
This pulls over the fix from the matching flux-sched nosuid issue in case we run into it here at some point.
Problem: flux-sched side ran into issues with setuid binaries in some cases under aarch64 emulation building containers.  It seems to depend on which workers pick up the job, so seems best to bring the solution over.
Solution: Run the docker container with the setup script directly with the appropriate option to handle setuid credentials.
> switch qemu-user-static setup to fix setuid

- src/common/libzmqutil/cert.c
- src/common/libzmqutil/test/cert.c
Problem: the cert class uses some newer 0MQ functionality that isn't available in libzmq-4.1.5, which is the packaged version on the lassen (IBM coral) system.
Simple fixes.
> libzmqutil: fix portability to libzmq-4.1.5

- NEWS.md
First cut of release notes for flux-core v0.55.0.
As usual, feel free to directly push to this branch with fixups and additions.
> NEWS.md: add release notes for v0.55.0

- .github/workflows/codeql.yml
- .github/workflows/main.yml
- codecov.yml
- doc/requirements.txt
- src/test/docker/docker-run-checks.sh
This PR adds the flux-pmix and flux-pam builds to CI to ensure PRs do not break the build/test of these projects.
flux-pam is probably less useful, but it is so quick to build I threw it in there.
This also fixes the `after_n_builds` support for codecov which might hopefully reduce the extra reporting we get for coverage.
> ci: add flux-pmix, flux-pam builds to CI

- src/bindings/python/flux/job/info.py
- t/python/t0010-job.py
This PR fixes #5491, however it does it in two ways
- fix handling of the `t_remaining` `JobInfo` attribute when `expiration` and/or `status` attrs are missing
- skip attributes that raise an exception in `to_dict()`
This allows `to_dict()` to work with `JobInfo` objects returned from `flux.job.result()`.
> python: fix handling of JobInfo properties and `to_dict()` method with missing attributes

- src/common/libflux/test/disconnect.c
- t/t2290-job-update.t
This PR contains a couple trivial fixes for the tests. There wasn't really anywhere else to put these, thus this PR.
- Avoid use of `round` with `jq` (not supported on `jq` 1.5 which is the version on bionic)
- Fix a silly leak in a unit test.
> testsuite: trivial test fixes

- doc/Makefile.am
- doc/man3/flux_send.rst
- doc/manpages.py
- src/broker/module.c
- src/common/libflux/connector.h
- src/common/libflux/connector_interthread.c
- src/common/libflux/flog.c
- src/common/libflux/handle.c
- src/common/libflux/handle.h
- src/common/libflux/response.c
- src/common/libflux/response.h
- src/common/libflux/rpc.c
- src/common/libflux/rpc.h
- src/common/libflux/test/handle.c
Problem: it's a common pattern to create a message, send it with with `flux_send()`, then destroy it; however, there is no interface to allow the message ownership to be transferred rather than copied.
Add `flux_send_new()` which accepts a non-const `flux_msg_t **` and implement it in the interthread connector.  Now messages can pass from one end to the other without costly duplication.
Use this function in the common `flux_rpc()` and `flux_respond()` family of functions.
This is marked WIP for now while I consider whether it's possible to use this in the broker along the message path.  It would be neat if rpcs between broker modules could transit the broker without copying!
Even just this change does seem to have a positive impact on job throughput.
> libflux: add flux_send_new()

- src/common/libflux/Makefile.am
- src/common/libflux/connector_local.c
- src/common/libflux/handle.c
- src/connectors/Makefile.am
Problem: it's not very efficient to have to separately dlopen the local connector when we could just build it in.
Build it in.
> libflux: make local connector built-in
