flux-framework/flux-core

- src/bindings/python/flux/util.py
- t/python/t0024-util.py
This PR fixes #5501 by adding a special case for `parse_datetime("now")`. Instead of parsing `"now"` with the `parsedatetime` module, just use `datetime.now()` which internally uses `gettimeofday(2)` and thus has sub-second precision, unlike `parsedatetime` `Calendar.parse()` which returns only second precision by default.
> python: return more precise result from `flux.util.parse_datetime("now")`

- src/common/libflux/connector.h
Problem: when connector operations are added, ABI compatibility between flux versions is broken.
Move the new `op->send_new()` to the end of the struct so that old libflux can operate with new connectors.
Add padding so in the future, new ops can replace padding and new libflux can operate wtih old connectors.
> connectors: avoid future ABI issues with _pad[]

- src/common/libflux/Makefile.am
- src/common/libflux/connector_interthread.c
- src/common/libflux/connector_loop.c
- src/common/libflux/handle.c
- src/common/libflux/message.c
- src/common/libflux/message_private.h
- src/common/libflux/msg_deque.c
- src/common/libflux/msg_deque.h
- src/common/libflux/test/handle.c
- src/common/libflux/test/interthread.c
- src/common/libflux/test/msg_deque.c
Problem: the `flux_msglist` class is used in connector implementations as a message queue, but it's not a great fit for that:
- it isn't thread safe
- its operations are slightly awkward for a queue (enqueue is "append", dequeue is "pop")
- it manipulates message references, making it awkward for no-copy interfaces
- it uses a zlistx internally, so insertions require a memory allocation and connectors are on critical performance path
This PR creates a new internal container class called "mpipe" which
- it is thread safe, with a MPIPE_SINGLE_THREAD option to relax this
- it has only enqeuue, dequeue, and requeue (enqueue to the other end) operations
- it uses a CCAN list internally for low overhead insertion
- it implements the pollfd/pollevents interface for reactor loop integration
Then …
> libflux: refactor internal message queues

- configure.ac
- src/bindings/lua/Makefile.am
- src/bindings/python/_flux/Makefile.am
- src/common/Makefile.am
- src/connectors/Makefile.am
New try at #5514 - this just adds the `--gc-sections` linker options in places where we build DSOs.
Overall, this reduces the size of DSO text and bss sections by about 50%.  It seems the debuginfo sections are not removed though, so the `.so` size is not reduced that much  :shrug:
Anyway, this makes the linker work the way I thought it was supposed to(!) so that's progress IMHO.
> build: reduce junk content in DSOs

- src/modules/Makefile.am
- src/modules/job-info/guest_watch.c
- src/modules/job-info/guest_watch.h
- src/modules/job-info/job-info.c
- src/modules/job-info/job-info.h
- src/modules/job-info/update.c
- src/modules/job-info/update.h
- src/modules/job-info/util.c
- src/modules/job-info/util.h
- src/modules/job-info/watch.c
- src/modules/job-info/watch.h
- t/Makefile.am
- t/job-info/update_lookup.c
- t/job-info/update_watch_stream.c
- t/t2231-job-info-eventlog-watch.t
- t/t2233-job-info-update.t
per discussion in #5451
Problem: In the future, several services will need to know a job's resources and know the updates that would apply to them.
This would currently require users to read R, watch the eventlog, and then apply `resource-update` events as they happen.  It would be nice if a service did this as there will be multiple users.
Solution: Support a new job-info.update-watch streaming service.  It currently supports only the key "R", but can be extended to other keys in the future.
The service will read R and the eventlog for a job and apply all resource-update changes as needed.  This initial "R" will sent back to the caller.  If the job has completed, the RPC streaming service ends.  If not, the eventlog will be watched for future resource-update events.  On each new …
> job-info: support new update-lookup and update-watch service

- src/common/libschedutil/alloc.c
- src/common/libschedutil/alloc.h
- src/common/libschedutil/hello.c
- src/common/libschedutil/ops.c
- src/common/libschedutil/ready.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/rset.c
- src/modules/job-exec/rset.h
- src/modules/job-manager/alloc.c
- src/modules/job-manager/getattr.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/alloc-bypass.c
- src/modules/job-manager/restart.c
- src/modules/job-manager/start.c
- src/modules/job-manager/test/job.c
- t/Makefile.am
- t/t2220-job-manager-R.t
- t/t2400-job-exec-test.t
Problem: jobtap plugins might need convenient access to R per #5471 
Per discussion, this prototypes keeping a copy of R in the job manager so that it could potentially be offered to jobtap plugins.  Some notes/caveats:
- R is not deleted after the job becomes inactive, which could be a potential optimization to conserve memory on JGF systems
- jobtap interfaces are unchanged (I thought @grondo might already have a good idea of how he wants to do that)
- if this is acceptable, RFC 27 will need updates to `sched.alloc` and  `job-manager.sched-hello` responses.
- this is set up so that job manager restart could replay `resource-update` events on top of the original _R_ loaded from the KVS
- R could be passed to `job-exec.start` to save a lookup (would require an update to RFC 32).  (Edit: …
> cache R in the job manager

- src/bindings/python/flux/job/kvslookup.py
- src/cmd/flux-job.c
- t/Makefile.am
- t/job-manager/plugins/resource-update-expiration.c
- t/python/t0014-job-kvslookup.py
- t/t2230-job-info-lookup.t
- t/t2232-job-info-security.t
similar to https://github.com/flux-framework/flux-core/pull/5428 this supports `resource-update` events in `flux job info` and the equivalent python bindings to look up the "viewed" R and not the "base" one stored in the KVS.
Just like #5463, the commits with new tests do not work and have XXX tagged to be filled in later when an actual way to update the R of a job exists.
I should also note that this does not use any solution from #5451 as A) I implemented this first :P, B) copied the implementation from the jobspec side, and C) I wanted to keep this processing out of broker.  We could of course change the approach.
> flux-job: get updated version of R

- src/modules/job-list/job_data.c
- src/modules/job-list/job_data.h
- src/modules/job-list/job_state.c
- src/modules/job-list/test/job_data.c
- t/t2260-job-list.t
This is an early implementation for `resource-update` support in `job-list` for when the `resource-update` event is actually implemented within `job-manager`.  So at the moment this does not do anything.
Note that the last commit has some "XXX" tags for what needs to be done to finish the code, mostly updating tests b/c how to actually update a job's expiration has not yet been determined.
> job-list: support resource-update event

- doc/man1/flux-job.rst
- doc/test/spell.en.pws
- src/cmd/flux-job.c
- t/t2230-job-info-lookup.t
- t/t2232-job-info-security.t
- t/valgrind/workload.d/job-info
Following up on #5464, this tries to simplify`flux job info`.  For a start, it uses `job-info.update-lookup` to fetch the current R instead of replaying the eventlog on the original R.  It also cleans up the `flux-job(1)` man page and adds an entry for `flux job info` with descriptions of each available key.
> flux job info: drop multiple key support, clean up code, add man page entry

- src/cmd/builtin/proxy.c
Problem: flux-proxy core dumps when It loses its connection to Flux.
`ctx.remote_uri_authority` is `free()`ed twice when `flux_reactor_run(`) returns < 0, as it does when the connection is lost.
Pull that `free()` out of `proxy_command_destroy_usock_and_router()` which is called twice and is otherwise idempotent and place it after the second call.
Fixes #5528
> flux-proxy: fix double-free on lost connection

- doc/man1/flux-update.rst
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/rset.c
- src/modules/job-exec/rset.h
- src/modules/job-exec/test/rset.c
- src/modules/job-list/job_data.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
- src/modules/job-manager/plugins/update-duration.c
- src/modules/job-manager/start.c
- src/modules/job-manager/start.h
- src/modules/job-manager/test/job.c
- src/modules/job-manager/update.c
- src/modules/resource/acquire.c
- src/modules/resource/inventory.c
- src/modules/resource/reslog.c
- src/modules/resource/reslog.h
- src/modules/sched-simple/sched.c
- src/shell/info.c
- src/shell/info.h
- src/shell/signal.c
- t/Makefile.am
- t/t2230-job-info-lookup.t
- t/t2233-job-info-update.t
- t/t2290-job-update.t
- t/t2292-job-update-running.t
This PR adds full support for updating the duration/expiration of running jobs.
Updates to duration of running jobs are permitted by the update-duration plugin when made by the instance owner only. Running job duration updates are then handled as a special case in the job-manager update service. The update service sends the RFC 27 `sched.expiration` RPC and defers posting of `jobspec-update` and `duration-update` events until the RPC returns successfully.
The job execution system (which handles signaling jobs at their expiration) and the job shell (which uses the expiration for support of the `--signal` option) are updated to watch R instead of fetching it once at the beginning of the job. On updates, the expiration 
Additionally, the resource module is switched from `job-info.lookup` to …
> support duration update for running jobs

- doc/Makefile.am
- doc/man1/common/submit-environment.rst
- doc/man1/common/submit-job-environment-variables.rst
- doc/man1/common/submit-other-options.rst
- doc/man1/common/submit-shell-options.rst
- doc/man1/flux-config.rst
- doc/man1/flux-filemap.rst
- doc/man1/flux-job.rst
- doc/man1/flux-jobs.rst
- doc/man1/flux-kvs.rst
- doc/man1/flux-pgrep.rst
- doc/man1/flux-proxy.rst
- doc/man1/flux-queue.rst
- doc/man1/flux-resource.rst
- doc/man1/flux-shell.rst
- doc/man1/flux-start.rst
- doc/man1/flux-uri.rst
- doc/man1/flux-version.rst
- doc/man1/flux.rst
- doc/man3/flux_kvs_lookup.rst
- doc/man3/flux_open.rst
- doc/man5/flux-config.rst
- doc/man7/flux-broker-attributes.rst
- doc/man7/flux-environment.rst
- doc/man7/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
This adds flux-environment(7), an attempt at "one stop shopping" for the environment variables that flux sets or that influence flux.  The environment variable references scattered throughout other pages are then formatted with the `:envvar:` markup that creates a cross-reference to the new entries in the HTML.  Some content in other pages like flux(1) and flux-run(1) was reduced to a summary table with references.
I spent some time researching each variable so I think the descriptions are of a fairly high quality but it would be good to check them over to be sure.
> flux-environment(7): add new man page

- src/modules/job-exec/bulk-exec.c
Problem: When the job-exec module handles an error from the wait-all composite future created from exec_kill(), it makes an assumption that all child futures are also fulfilled, and calls flux_future_get() on each individual future in bulk_exec_kill_log_error() to print a specific error. However, if bulk kill operation times out, then one or more of the child futures may not be fulfilled, and the module could block forever.
Check that each child future is ready in bulk_exec_kill_log_error() before calling flux_future_get() to avoid the hang.
Fixes #5523
Note: The fact that a wait-all future could be fulfilled with an error without all child futures also being fulfilled seems like a big foot-gun, but when I tried to fix the issue that way, I ran into some testing issues. Since this is a …
> job-exec: fix potential hang after exec kill error

- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- src/cmd/flux.c
We have some broker environment variables that have a "conf." prefix making them at least a little bit confusingly named since they have nothing to do with the toml configuration, but some also do not seem to have a strong reason for existing.  I whacked the following in this PR:
- `conf.module_path` mirrors broker's environment setting for FLUX_MODULE_PATH.  `flux --parent` uses it to fetch the parent's module path and prepend it in the subcommand environment, but now that the broker does its own search for modules rather than the `flux-module` command, this has no effect that I can see.
- `conf.connector_path` has no users
- `conf.exec_path` is used like `conf.module_path` to push parent's FLUX_EXEC_PATH in front of the local path.  This seems iffy to me as built-in commands will be the …
> drop broker conf.module_path, conf.connector_path, conf.exec_path attributes

- src/modules/job-manager/jobtap.c
- t/t2212-job-manager-plugins.t
Currently, when an attempt to load a duplicate jobtap plugin is made, the error message incorrectly reports "plugin not found".
This is due to a failure to set an appropriate errno when the plugin is already loaded. This PR fixes that issue along with some other minor cleanup.
> job-manager: fix error message on duplicate plugin load

- src/bindings/python/flux/cli/base.py
- t/t2710-python-cli-submit.t
This PR fixes substitution of `{cc}` in `flux submit --cc/--bcc` when `cc=0`. (Issue #5539)
> flux-submit: fix substiution of `{cc}` when cc=0

- config/x_ac_jansson.m4
- doc/man3/common/json_pack.rst
- doc/man3/common/json_unpack.rst
- doc/man3/flux_shell_get_hwloc_xml.rst
- doc/man3/flux_shell_get_info.rst
- doc/man3/flux_shell_get_jobspec_info.rst
Problem: the version of jansson shipped with SLES, reportedly jansson 2.9 on frontier at ORNL and same on sles15-sp5, is too old to build Flux.
It seems that 2.9 is just as good as the current minimum of 2.10 for Flux so reduce the minimum version to 2.9.
Fixes #5544
> build: reduce minimum jansson version to 2.9

- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
- t/rexec/rexec.c
- t/rexec/rexec_getline.c
This was pulled off some other work.
Currently, `flux_subprocess_write()` writes any bytes it can to the destination buffer, which could result in a short write (return code < `len`). However, a check for a short write is not done is most places (a check for `rc < 0` seems to be the common case), and where it is checked it is immediately promoted to a fatal error. In some cases (such as the job-ingest pipeline) a short write can be dangerous since it isn't recovered and writing only part of a line "hangs" the protocol.
In the interest of simplicity, add a check for the available buffer space in `flux_subprocess_write()` and return immediately with return code `-1` and `errno` set to `ENOSPC` if there is not enough space for all the data. Update any callers that attempt to handle a short …
> libsubprocess: do not allow short writes with `flux_subprocess_write()`

- src/modules/job-ingest/worker.c
This PR is another piece of the workaround for #5518.
If the buffer for a subprocess on the _server_ side becomes full and therefore a write fails, libsubprocess currently treats this as fatal error, kills the subprocess and returns `FLUX_SUBPROCESS_FAILED` as subprocess state.
If this occurs for a job-ingest worker, then any futures still in the queue will never be fulfilled and job submissions will appear to hang.
This PR just adds a call to `worker_unexpected_exit()` for failed worker subprocesses so that any pending futures are fulfilled with error.
> job-ingest: fix cleanup when a pipeline worker process fails

- doc/man5/flux-config-ingest.rst
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/util.c
- src/modules/job-ingest/job-ingest.c
- src/modules/job-ingest/pipeline.c
- src/modules/job-ingest/pipeline.h
- src/modules/job-ingest/workcrew.c
- src/modules/job-ingest/workcrew.h
- src/modules/job-ingest/worker.c
- src/modules/job-ingest/worker.h
- t/Makefile.am
- t/issues/t5518-job-validator-hang.sh
- t/t2111-job-ingest-config.t
This is the final piece of the workaround for #5518.
This PR makes the job-ingest worker input buffer configurable and increases the default size to 10MB.
A reproducer for #5518 is then added to the testsuite using the configurable buffer size to reduce the buffer.
This requires #5549 so is built on top of that.
Fixes #5518.
> job-ingest: make worker input buffer configurable with a default of 10MB

- doc/man1/flux-config.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
Problem: after #5536 was merged, the broker code for initializing "attributes from the environment" looks over-engineered.
Trim it down.
Also fix some man page typos that were adjacent to the work in #5536.
> broker: cleanup up attribute initialization code

- doc/man1/flux-start.rst
- doc/test/spell.en.pws
This reworks the flux-start(1) man page to hopefully offer more explanation and troubleshooting tips for problems that repeatedly come up.
> flux-start(1): add more description and troubleshooting info

- doc/Makefile.am
- doc/man1/flux-pmi.rst
- doc/man7/flux-environment.rst
- doc/manpages.py
- doc/test/spell.en.pws
Problem: there is no man page for flux-pmi, although one is referenced from flux-start(1).
Add one.
Also add a missing detail about PMI clients to flux-environment(7).
> flux-pmi(1): add new manual page

- doc/man1/common/job-shell-options.rst
- doc/man1/flux-alloc.rst
- doc/man1/flux-batch.rst
- doc/man1/flux-bulksubmit.rst
- doc/man1/flux-run.rst
- doc/man1/flux-shell.rst
- doc/man1/flux-submit.rst
- doc/test/spell.en.pws
Problem: the job submission commands duplicate shell plugin information in `flux-shell(1)`.
Improve the way options are formatted for HTML presentation in `flux-shell(1)`, adding x-ref capability and reworking some dense/terse descriptions.  Then change the duplicate option descriptions in the submission commands into a short table that cross-references commonly needed options to `flux-shell(1)`.
Improve the descriptions of pmi and affinity options as they were a bit terse IMHO.
> flux-shell(1): improve option descriptions and x-ref

- doc/man7/flux-environment.rst
- doc/test/spell.en.pws
- src/cmd/Makefile.am
- src/cmd/flux.c
- src/cmd/py-runner.py
- src/common/libflux/conf.c
- t/t2110-job-ingest-validator.t
This is stab at fixing #5547 with a new module `fixsyspath` which can be imported first in all Python utilities to move the standard and Flux Python module paths back to the front of `sys.path`.  This works around possible changes to `PYTHONPATH` that put incompatible Python modules before the system modules.
Still need to add some automated tests here, but I did verify this works around the specific case documented in the issue:
On current master:
```console
$ module load omniperf
$ flux alloc -n1 flux run hostname
flux-run: ERROR: Unrecoverable error: worker unexpectedly exited
Nov 10 16:58:58.347767 broker.err[0]: rc2.0: flux run hostname Exited (rc=1) 0.4s
Nov 10 16:58:58.348470 job-ingest.err[0]: job-validator[0]: exited with rc=1
[detached: session exiting]
```
On this branch: …
> make flux Python commands more resilient to changes in PYTHONPATH

- src/broker/broker.c
- src/common/libeventlog/eventlog.c
- src/common/libflux/connector_interthread.c
- src/common/libflux/connector_loop.c
- src/common/libflux/module.c
- src/common/libflux/msg_deque.c
- src/common/libflux/test/interthread.c
- src/common/libflux/test/msg_deque.c
- src/common/libflux/test/msglist.c
- src/common/liboptparse/getopt.c
- src/common/libsubprocess/fork.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/util.c
- src/common/libtestutil/util.c
- src/common/libutil/timestamp.h
- src/modules/job-exec/job-exec.c
Problem: a few non-standard headers are included in place of the standard ones, impacting portability.  Other headers are included for no reason, likely left over from cut and paste or previous versions of the code.  Cleanup is in order.
Use the standard headers and drop some needless includes.
This was peeled off of #5564.
> fix improper include directives in source files impacting portability

- doc/man1/common/job-other-options.rst
Problem: the `--urgency` option is not described very thoroughly.
Expand the description and re-format for readability.
I was cleaning up some old branches and found this commit that was somehow not included in previous improvements to the submission command docs
> doc: improve --urgency option description in job submission commands

- t/Makefile.am
- t/job-info/info_lookup.c
- t/t2230-job-info-lookup.t
Problem: In PR #5520 "multiple key" "flux job info" tests were removed due to a feature change in "flux job info".  This removed some coverage of corner cases in job-info.lookup.
Add a new "job-info.lookup" RPC target helper tool and re-add a number of the previously removed "multiple key" tests.
> testsuite: add multiple key job-info lookup tests

- src/broker/broker.c
- src/broker/broker.h
- src/broker/modhash.c
- src/broker/modhash.h
- src/broker/module.c
- src/broker/module.h
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/service.c
- src/broker/service.h
- src/broker/test/overlay.c
- src/broker/test/service.c
Problem: the broker copies messages when it doesn't have to.
This PR eliminates some places in the broker where messages are needlessly copied.  I had hoped that by making the local paths between ingest -> kvs, ingest -> job manager, kvs -> content cache effectively zero copy, there would be a measurable effect on the job throughput test.  Well, not really.
I'll mark this WIP for now and revisit tomorrow to make sure I'm not missing something.
The other thing here is I replaced the strange half-constructed connector with back-to-back interthread handles.  It should make the broker code a little easier to understand.
> broker: eliminate some message copies

- src/modules/job-info/guest_watch.c
- src/modules/job-info/update.c
- src/modules/job-info/util.c
- src/modules/job-info/util.h
- src/modules/job-info/watch.c
Misc cleanup, mostly coming from comments in #5467
Note that I just saw #5585 got submitted, dunno if there are conflicts ...
> job-info: misc cleanup

- doc/man1/flux-kvs.rst
- doc/test/spell.en.pws
Problem: flux-kvs(1) is hard to use as a reference.
Improve the synopsis, description, and break out sub-commands into sub-sections with properly declared options.
> flux-kvs(1): improve man page formatting

- src/bindings/python/flux/cli/alloc.py
- src/bindings/python/flux/cli/run.py
Problem: If PATH is not set in the environment of the flux-run(1) and flux-alloc(1) job submission commands, they raise an unhelpful KeyError and fail to invoke `flux job attach`, leaving the job running without the interactive attach.
Do not assume PATH is set in these commands when prepending FLUX_EXEC_PATH.
Fixes #5562
> cli: avoid KeyError when PATH isn't set in environment

- doc/man1/flux-job.rst
- src/cmd/flux-job.c
- t/t1105-proxy.t
- t/t2201-job-cmd.t
- t/t2292-job-update-running.t
- t/t2402-job-exec-dummy.t
- t/t2813-flux-watch.t
Problem: flux job cancel still is documented but we want people to use `flux-cancel(1)` now.
Hide the `cancel` and `cancelall` sub-commands of `flux-job(1)`  and print a deprecation warning if they are used.
Drop those sub-commands from the `flux-job(1)` man page and make various improvements to the page, including documenting some user-facing commands that were not listed such as `flux job urgency` and `flux job last`.
> deprecate flux job cancel and improve flux-job(1) documentation

- t/t2292-job-update-running.t
Problem: Several tests in t2292-job-update-running.t were failing due to "fancy f" vs "normal f" grepping inconsistencies.
Solution: Set FLUX_F58_FORCE_ASCII to true to get consistent testing.
> testsuite: fix fancy f grep inconsistency

- t/t2201-job-cmd.t
- t/t2402-job-exec-dummy.t
This PR fixes a couple race conditions that popped up in job signal/cancel tests. I'm unsure why these races seem to have become more likely to be hit lately. Perhaps after the improvements in broker message handling? Anyway, the workarounds presented here seem to improve things in CI and my test environment.
> testsuite: improve reliability of a couple job signal/cancel tests

- src/bindings/python/flux/kvs.py
- src/common/libkvs/kvs_txn.c
- src/common/libkvs/kvs_txn.h
- src/common/libkvs/test/kvs_txn.c
- t/python/t0005-kvs.py
Built on top of the prior #5373.  Unlike the namespace support, this ones a little ehhh ... 
Support a new "KVSTxn" class that semi-mirrors the "kvs transactions" we do in `libkvs`.  This allows users to do:
```
with KVSTxn(handle, "basedir", namespace="foobar") as txn:
txn.put("a", 1)
```
and, most notably, not all changes to the KVS are placed into a single transaction.  For example, under the old code something like:
```
dir1 = get_dir("mydir")
dir1["a"] = 1
dir2 = get_dir("mydir")
dir2["a"] = 2
dir1.commit()
```
Would not give you the effect one would expect.
Notes:
- All of the "put*()" functions don't need a `flux_handle`, just a transaction object.  But because of the old "aux_txn" and backwards compatibility, we have to leave it there.  Unless we decide to just break things.
- I …
> python: add KVSTxn class to KVS module

- doc/man1/flux-kvs.rst
- src/cmd/builtin/dmesg.c
- src/cmd/flux-job.c
- src/cmd/flux-kvs.c
- src/common/libeventlog/Makefile.am
- src/common/libeventlog/formatter.c
- src/common/libeventlog/formatter.h
- src/common/libeventlog/test/formatter.c
- src/common/libutil/test/timestamp.c
- src/common/libutil/timestamp.c
- src/common/libutil/timestamp.h
- t/t1008-kvs-eventlog.t
- t/t2100-job-ingest.t
- t/t2230-job-info-lookup.t
Many times I've wished for output from `flux job eventlog` that matches the output from `flux dmesg -H`, which in turn was taken from the output of `dmesg -H`:
```
[Nov28 17:33] broker[0]: insmod connector-local
[  +0.000085] broker[0]: start: none->join 3.31617ms
[  +0.000117] broker[0]: overlay auth cert-name=1 OK
[  +0.000157] broker[0]: parent-none: join->init 0.06508ms
```
This format is nice because it presents not only relative timestamps of events, but also gives an absolute timestamp every minute, so you can place the events in time as well as tell how far apart they are occurring. With the current eventlog commands, you can choose either an "offset", "raw" floating-point timestamps, or "iso" ISO 8601 timestamps, none of which have the properties of the above format.
This PR adds …
> support colorized, human-readable output from eventlog commands

- src/cmd/flux-terminus.c
- src/common/libterminus/terminus.c
- src/common/libterminus/terminus.h
Looking into why `t0020-terminus.t` has been hanging (#5595) revealed a potential race in the flux-terminus server. When the server shuts down, it relies on the disconnect handler to unregister the service with the broker. This leaves a small race between when the server leaves the flux reactor and when the service is unregistered where a client request could be left without a response. This could cause a client hang and thus the hangs in `t0020-terminus.t`.
I did observe the hang several times in the alpine docker container while attempting to debug this, and no hangs after 100s of runs on this branch. So while there's no definitive proof that this issue was the cause of the hang, I'm hopeful this will fix it.
> flux-terminus: fix potential hang in terminus client commands

- configure.ac
- src/broker/Makefile.am
- src/broker/broker.c
- src/common/libmissing/Makefile.am
- src/common/libmissing/strlcat.c
- src/common/libmissing/strlcat.h
- src/connectors/ssh/ssh.c
- t/t1105-proxy.t
- t/t1106-ssh-connector.t
Problem: the ssh connector tries to remotely execute `flux-relay` using a path derived from the local flux installation.  This tends not to work well when the remote flux is installed to a different path, as was encountered in #5582.
This  PR improves the odds of getting it right with the following changes:
1. the broker places a symlink to its bindir in `rundir/bin`
2. the ssh connector derives `rundir` from the `ssh://` URI and places `rundir/bin` first in the remote PATH
The local directory that contains `flux(1)` is appended to the remote PATH, so that there should be no change in behavior when using `flux proxy` to an older version of flux that doesn't have this feature.  `/usr/bin:/bin` is also appended so `flux(1)` can be a libtool wrapper (the wrapper scripts need to run some …
> improve ssh connector reliability with different installation paths

- src/bindings/python/flux/uri/resolvers/lsf.py
- t/python/t0015-job-output.py
- t/t0005-exec.t
- t/t1102-cmddriver.t
- t/t2201-job-cmd.t
- t/t2233-job-info-update.t
- t/t2260-job-list.t
- t/t2500-job-attach.t
- t/t2607-job-shell-input.t
- t/t2712-python-cli-alloc.t
- t/t2801-top-cmd.t
- t/t3307-system-leafcrash.t
Many tests in the testsuite seem to have become a bit more unreliable lately. I disabled the `make recheck` step on a branch, at which point 2 or 3 builds failed every time. I then worked through the failing tests, trying to fix some and adding more debug info for others where there was nothing apparent in the logs for the cause of the failure.
This doesn't fix everything, but it should make CI at least slightly more reliable.
> testsuite: fix some test races and improve debugging

- src/modules/kvs/kvs.c
- t/kvs/fence_api.c
- t/t1005-kvs-security.t
This limits the operations that can be performed in a guest-owned private KVS namespace.
> kvs: limit the content of guest commits

- t/t2233-job-info-update.t
Problem: A quoting issue in one of the tests in t2233-job-info-update.t causes the test to fail when run with -d -v or debug=t.
Fix the quoting issue.
This was caught by gitlab-ci. Not sure why it doesn't surface in our normal CI.
> testsuite: fix t2233-job-info-update.t with debug=t

- src/common/libkvs/kvs.c
- src/common/libkvs/kvs.h
- src/common/libkvs/kvs_checkpoint.c
- src/common/libkvs/kvs_commit.c
- src/common/libkvs/kvs_commit.h
- src/common/libkvs/kvs_dir.c
- src/common/libkvs/kvs_dir.h
- src/common/libkvs/kvs_dir_private.h
- src/common/libkvs/kvs_getroot.c
- src/common/libkvs/kvs_lookup.c
- src/common/libkvs/kvs_lookup.h
- src/common/libkvs/kvs_txn.c
- src/common/libkvs/kvs_txn.h
- src/common/libkvs/test/kvs_txn.c
- src/common/libkvs/treeobj.c
- src/common/libkvs/treeobj.h
This fixes a bad parameter that was caught in RHEL 8 aarch64 CI.  I also tacked on some libkvs whitespace cleanup.
> libkvs: fix test failure in aarch64 CI

- t/t2260-job-list.t
- t/test-inception.sh
Another test had some bad `test_debug` statements that caused the test to fail when run with `-d -v`. This PR fixes that and adds these args to the sharness tests in the inception builder to hopefully catch these silly errors in CI.
> testsuite: fix t2260-job-list.t with `-d -v` and run inception tests with these args to prevent future similar errors

- t/t2233-job-info-update.t
- t/t2500-job-attach.t
This PR includes a few more fixes for unreliable tests in ci. There are still more flaky tests, but they are now somewhat rare instead of annoyingly common.
> testsuite: more reliability improvements in tests

- src/modules/job-list/list.c
Problem: In the check_id_valid path, there is a potential a mem-leak of a json object.  The path is for a rare race, so it likely has not been hit in production.
Solution: Remove the json object when it is no longer used.
> job-list: fix json object mem-leak

- t/t2716-python-cli-batch-conf.t
Problem: A test in t2716-python-cli-batch-conf.t can fail if some errant stderr ends up in the json output file.
Solution: Redirect stderr to a separate file.
> testsuite: fix test corner case on stderr

- doc/man1/flux-alloc.rst
- doc/man1/flux-batch.rst
- doc/man1/flux-bulksubmit.rst
- doc/man1/flux-run.rst
- doc/man1/flux-submit.rst
- doc/man7/flux-environment.rst
This PR adds a few more references to the useful `flux-environment(7)` man page in the job submission cli manual pages.
> doc: reference flux-environment(7) in job submission cli man pages

- src/bindings/python/flux/kvs.py
- t/python/t0005-kvs.py
Problem: There may be circumstances that a non-synchronous kvs
commit is desired, but there is no way to do that at the moment.
Solution: Add a kvs.commit_async() function to the kvs module.
Also add equivalent commit_async() functions to KVSTxn and KVSDir.
Fixes #5606
--- 
Note will re-work #5389 to use this
> python: Add kvs.commit_async()

- src/common/libflux/message.c
- src/common/libflux/message_iovec.c
- src/common/libflux/message_iovec.h
- src/common/libflux/message_private.h
- src/common/libflux/test/message.c
- src/common/libzmqutil/msg_zsock.c
- src/common/libzmqutil/test/msg_zsock.c
Problem: `flux_msg_create()` accepts FLUX_MSGTYPE_ANY as a type argument, but this is confusing and is not required by users.
Factor out a `msg_create()` internal constructor that can be used by internal functions instead.
Update libflux and libzmqutil users.
Update unit tests.
This was split off of #5630
> libflux: don't accept FLUX_MSGTYPE_ANY  in flux_msg_create()

- src/common/libflux/message.c
- src/common/libflux/message.h
- src/common/libflux/message_iovec.c
- src/common/libflux/message_private.h
- src/common/libflux/test/message.c
Problem: `flux_msg_frames()` has no practical use outside of message encoding/decoding implementations but it is in the public API.
Convert this to a private function, msg_frames().
Update internal users and unit tests.
> libflux: drop flux_msg_frames()

- doc/guide/glossary.rst
- doc/test/spell.en.pws
Problem: the Glossary section of the flux-core docs is pretty thin.
Define some Flux/resource management terms.
(dredged this up from earlier docs work and made an editing pass)
> doc: expand glossary

- doc/test/spell.en.pws
- t/README.md
Problem: Lassen doesn't like the words login, workflow, or infeasible, and it causes our CI spellcheck tests to break on that machine.
Add those words to the exempt word list in the docs.
Looking at previous issues, I thought that #3071 might be at play since `LC_ALL=C` is set on Lassen but not on TOSS 4 machines. Changing that to `LC_ALL=""` didn't solve the issue. 
I also tried using `SHARNESS_SKIP_TESTS=spellcheck` command [listed in the testsuite readme](https://github.com/flux-framework/flux-core/tree/master/t#skipping-tests), but it still ran the test. Do we support that command? When I git grep'd for it in core I couldn't find anywhere in our shell scripts it's used. I did find [`SKIP_TESTS` in `t/sharness.sh`](https://github.com/flux-framework/flux-core/blob/f8558d01cc1b853007a8283 …
> testsuite: fixes for Lassen

- src/common/librlist/rhwloc.c
- src/common/librlist/rhwloc.h
- src/common/librlist/rlist.c
- src/modules/resource/inventory.c
- src/modules/resource/resource.c
- src/modules/resource/resource.h
- src/modules/resource/topo.c
- t/t0001-basic.t
- t/t2712-python-cli-alloc.t
This PR adds the ability for the resource module to grab the local hwloc from its parent instance when possible, instead of always using `hwloc_topology_load(3)`. This should speed up this stage of the module's initialization greatly, as well as keeping a consistent topology available throughout a hierarchy as noted in #5611.
If there is no parent instance or the `resource.topo-get` RPC fails , then we fall back to `hwloc_topology_load(3)`.
This is a WIP for now to get feedback and until I figure out how to add some testing.
> resource: get local hwloc XML from parent when possible

- src/common/libflux/message.h
While debugging an issue in DYAD, @hariharan-devarajan and I found something odd stemming from `message.h` in `libflux`. When we used `flux_log` or `flux_log_error` in DYAD, everything worked fine. However, when we commented out the code using those functions, DYAD failed to build because `ssize_t` wasn't defined when the compiler was handling code from `message.h`.
We can work around this in DYAD by making sure we include `sys/types.h` (i.e., the header where `ssize_t` is defined) before including `flux/core.h`, but it would be better long term if that include happened in `message.h`. This PR simply adds that include.
> libflux: add include for ssize_t to message.h

- src/modules/resource/inventory.c
- t/t3100-flux-in-flux.t
I noticed while running some tests on corona that launching multiple brokers per node wasn't working.
The issue was introduced by 093509813cfe7fbafc4c84614069be82b17ea703. In the fallback code, `inventory_put()` is always attempted, even if the conversion of R failed and thus `R == NULL`. This causes `inventory_put()` to fail and in turn the load of the `resource` module.
The call to `inventory_put()` should only be made if `R != NULL` (as it is in the non-fallback case).
Also, add some tests that were clearly missing here (though this one's a bit of a corner case)
> resource: fix initialization of multiple brokers per node when fallback to job-info.lookup is used

- t/t3306-system-routercrash.t
Problem: In t3306-system-routercrash.t SIGSEGV is intentionally sent to a broker to test a broker crash, but this could leave a mysterious corefile in the test directory if the core file ulimit and system configuration allow it.
Call `ulimit -c 0` before test_under_flux() to avoid the core file.
> testsuite: avoid artificial corefile in test

- src/common/libutil/test/fileref.c
Problem: the fileref unit test fails on tmpfs in debian 11, kernel 6.1.0-rpi7-rpi-2712.
Although tmpfs supports sparse files, in some cases the test's efforts to create sparse test files are unsuccessful.
Skip tests when the test file must be sparse and is not.
Fixes #5642
> testsuite: fix fileref unit test failure on tmpfs

- doc/man1/common/job-other-batch.rst
- doc/man1/common/job-other-run.rst
- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/cli/batch.py
- t/t2716-python-cli-batch-conf.t
This PR enables the `--quiet` option on `flux-batch`.
Fixes #5644
> flux-batch: support `--quiet` option

- doc/man1/common/job-standard-io.rst
- doc/man1/flux-batch.rst
Problem: Documentation of standard io options is not included in flux-batch(1).
Add a STANDARD I/O section to flux-batch(1) and include the missing common/job-standard-io.rst text. Since flux-batch(1) now has its own manual, remove the generic statement about flux-batch(1) from the common file and put a similar statement directly in flux-batch(1).
> doc: add missing standard-io options to flux-batch(1)

- src/common/libflux/msg_handler.c
Problem: the message dispatcher does not respond with EPERM to unauthorized requests (per the message handler's rolemask) unless the message has a valid matchtag, but that should not be required.
Only suppress the response if FLUX_MSGFLAG_NORESPONSE is set.
FIxes #5651
> libflux: respond to denied, matchtagless requests

- src/bindings/python/flux/message.py
- t/Makefile.am
- t/python/subflux.py
- t/python/t0008-message.py
Python `Message` objects currently offer some basic property getter and setters, but there is no convenient way to call the underlying `decode` API function for these messages. Notably, this makes it impossible to tell if a response contains an error.
This PR adds a `decode` method to the `Message` class which calls the underlying decode C API, raising an `OSError` exception if the decode fails, since this is an idiomatic way to detect an error in the case of requests.
Additionally, there were no unit tests of the `Message` class, so a set of tests is added.
> python: add `decode` method to Flux `Message` class

- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/message.py
- t/python/t0007-watchers.py
- t/python/t1000-service-add-remove.py
This PR fixes #5013 by adding an optional `rolemask` parameter to the `MessageWatcher` class initializer as well as `msg_handler_create()` which calls it.
> python: add rolemask parameter to msg_handler_create()

- NEWS.md
This adds some release notes for v0.58.0. Feel free to edit or amend.
The current version assumes #5650 and #5653 will be merged before tagging.
> NEWS: add release notes for v0.58.0

- doc/man3/flux_requeue.rst
Problem: FLUX_RQ_TAIL is listed twice in flux_requeue(3).  One of them should be FLUX_RQ_HEAD.
Fix the typo.
Fixes #5659
> doc: correct typo in flux_requeue(3)

- src/modules/kvs/kvs.c
- t/Makefile.am
- t/issues/t5657-kvs-getroot-namespace.sh
Per discussion in #5657
To solve, I added a "namespace" field in the getroot response.  Obviously could have done an "aux" thing instead.  But felt this was the most reasonable / potentially useful in other ways solution.
I did not add "get" functions for the namespace in `libkvs/kvs_getroot`.  Maybe should / could?  I initially did, but then it seemed silly to add it into `flux kvs getroot` (i.e `flux kvs getroot --namespace foo-namespace` would output `foo-namespace`).
> kvs: store correct namespace after getroot lookup

- doc/man1/flux-filemap.rst
- src/cmd/builtin/filemap.c
- src/common/libfilemap/filemap.c
- src/common/libfilemap/filemap.h
- src/common/libutil/fileref.c
- src/shell/files.c
- src/shell/stage-in.c
- t/t0029-filemap-cmd.t
Problem: as discussed in #5655, `flux filemap get` can too easily ovewrite the source file causing mahem in a file broadcast operation.
This changes the default behavior to fail the `get` operation if a destination file exists, and adds a `--overwrite` option that can be used to get the old behavior.
> add flux filemap get --overwrite and change the default overwrite behavior

- doc/man1/common/job-param-batch.rst
- src/bindings/python/flux/cli/base.py
- t/t2714-python-cli-batch.t
- t/t3100-flux-in-flux.t
Problem: for some reason, the `--exclusive` option in `flux-alloc` and `flux-batch` is not paired with a short `-x` option like it is in the other submission commands.
Add the short option.
> add -x option to flux-alloc and flux-batch

- doc/man7/flux-broker-attributes.rst
- src/broker/broker.c
- t/t3100-flux-in-flux.t
This ensures that the `parent-uri` broker attribute is only set when Flux was lauched as a Flux job, as discussed in #5622.
> broker: only set parent-uri when instance is a job

- src/modules/job-manager/event.c
- src/modules/job-manager/jobtap.c
- t/job-manager/plugins/jobspec-update.c
- t/t2212-job-manager-plugins.t
As described in #5671, plugins that modify jobspec may end up having duplicate `jobspec-update` events posted. This is wasteful.
The problem occurs because `jobtap_post_jobspec_updates()`, which is called _after_ all plugin callbacks and posts any pending jobspec updates to avoid modifying jobspec while the plugin is still active,  may be called reentrantly as a result of the jobspec updates. The function does not clear `jobtap->jobspec_update` before posting the event, so the 2nd (or more?) calls will post the duplicate.
This PR fixes that issue by ensureing `jobtap_post_jobspec_updates()` is reentrant, and adds a reproducer for this issue to the testsuite.
> job-manager: fix duplicate posting of jobspec-update event from plugins

- src/common/libpmi/Makefile.am
Problem: the libpmi Makefile.am does not check for JANSSON_CFLAGS, which is required to find the jansson header file.
Add the check. Closes #5670
This solution is [courtesy of](https://github.com/flux-framework/flux-core/issues/2892#issuecomment-1883973494) @garlick in #2892. :-)
> libpmi: add `JANSSON_CFLAGS` to Makefile.am

- src/broker/exec.c
- t/t0005-exec.t
- t/t0005-rexec.t
Problem: remote rexec to rank 0 is not permitted, but it would be useful to allow shell plugins to run things on rank 0 in order to utilize leader-only services like 'flux filemap map'.
Remote rexec is restricted in order to prevent the flux user from remotely executing arbitrary programs on a restricted management node. This is not a concern for other Flux instances such as batch jobs.
Change the rexec authorization callback to allow remote access on rank 0 if the 'access.allow-guest-user' TOML key is unset or false.
Update tests.
> broker: allow single-user rexec to rank 0

- src/broker/broker.c
- src/common/libflux/attr.c
- t/t1105-proxy.t
This applies the changes discussed in #5679 to fix `flux start` hangs under `flux proxy`.
> fix broker hang under `flux proxy`

- src/common/librlist/rhwloc.c
- src/common/librlist/rlist.c
This PR fixes an issue reported in the conda-forge environment with hwloc-2.9.3 reported [here](https://github.com/conda-forge/flux-core-feedstock/pull/35). The newer hwloc in that environment doesn't like including the terminating `NUL` with `hwloc_topology_set_xmlbuffer()` (I was unable to reproduce just using that version of hwloc outside of conda-forge. Maybe the change is actually in an underlying xml library). It doesn't seem to be a problem to exclude the `NUL` on other hwloc versions, so this PR just adjusts the size to the result of `strlen()`.
This failure also uncovered an actual bug: Passing `NULL` to `hwloc_topology_destroy(3)` causes a segfault, so also protect against that to avoid segfaults in the future.
> librlist: fix segfault when initializing topology from XML in later hwloc versions

- src/common/librlist/rhwloc.c
Problem: With some versions of libxml, the XML load function does not tolerate a buffer length that includes the trailing NUL character. In hwloc 2.10.0, hwloc_topology_set_xmlbuffer() was changed to decrement the length before passing to the underlying XML call, so this effectively means that hwloc now *requires* the NUL character be included in length, but current librlist code does not include it to workaround the problem in v2.10.
Since there is no way to determine if NUL should or should not be included in hwloc_topology_set_xmlbuffer(), include the NUL by default, but retry without it if the first call fails.
Fixes #5689
> librlist: workaround xml buffer size issue in some hwloc versions

- src/common/librouter/test/sendfd.c
- src/shell/rlimit.c
- t/t2260-job-list.t
- t/t2710-python-cli-submit.t
- t/t2711-python-cli-run.t
- t/t2714-python-cli-batch.t
This PR contains some fixes required for `make check` to pass in the conda-forge build environment.
This includes a workaround for missing `F_GETPIPE_SZ` as well as some real test bugs found because `jq` v1.7 uncovered some missing inputs to `jq` in the testsuite.
Fixes #5684
> testsuite: fix testsuite errors discovered in conda-forge build environment

- src/common/libterminus/client.c
- src/common/libterminus/pty.c
- src/common/libterminus/pty.h
- src/common/libterminus/test/pty.c
- t/t2712-python-cli-alloc.t
This PR addresses a couple issues reported in #5696.
First, evidently some pty data fails to encode using the jansson API. This PR adds support for falling back to base64 when that (very rare) event occurs. 
Second, the `flux alloc vi` test is currently dependent on the filename showing in the vi statusline, which doesn't always seem to be the case. Make the test more reliable by just looking for the file data before quitting `vi`.
Fixes #5696
> enable encode of pty data as base64 and make `flux alloc vi` test more reliable

- src/test/docker/docker-run-checks.sh
- src/test/generate-matrix.py
This PR simply adds a fedora 39 builder with Python 3.12 to CI.
> ci: add fedora39 build

- src/bindings/python/flux/job/output.py
- src/bindings/python/flux/job/watcher.py
- t/t2813-flux-watch.t
This PR fixes binary output with `flux-watch(1)` as discussed in #5702. A test is also added.
> python: fix `flux-watch: TypeError: Object of type 'bytes' is not JSON serializable`

- doc/man7/flux-environment.rst
- src/broker/boot_pmi.c
- src/common/libutil/ipaddr.c
- src/common/libutil/ipaddr.h
- t/t0001-basic.t
Problem: during scale testing, it was observed that Flux was using an unstable network fabric, but there is no way to tell it to use another one.
Add the FLUX_IPADDR_INTERFACE environment variable.   It can be set to an interface name in the broker's environment, and then PMI bootstrap will select an address associated with that interface.
> broker: add FLUX_IPADDR_INTERFACE to select broker network interface

- src/test/docker/fedora39/Dockerfile
- src/test/docker/fedora39/config.site
Problem: When support for ci builds on Fedora 39 was added, the Dockerfile was never included.
Add a Dockerfile for Fedora 39.
Thanks @chu11 for catching this!
> docker: add Dockerfile for fedora39

- src/bindings/python/flux/kvs.py
- src/modules/job-list/job-list.c
- src/modules/job-list/job_state.c
- src/modules/job-list/job_state.h
- src/modules/job-list/stats.c
- src/modules/job-list/stats.h
- t/t2260-job-list.t
Problem: Job queue stats are generated in job-list when a job is submitted into it.  If a job queue never has a job submitted to it, no job stats exist for the queue.  This isn't what users would expect, they should expect queue stats to be 0 for the queue.
Solution: Read the flux config and initialize queue stats to 0 for any queues that have been configured.
Fixes #5688
----
Uhhh I clearly messed up my branch with rebasing somehow ... will fix
I'm not sure why a CodeQL warning showed up in this PR.  I figured the "not a warning" in original PR was enough, but I guess not??  Or maybe b/c it was due to my messed up rebasing earlier.  Anyways, I just added a tiny fix to fix it.
Oh yeah, side note.  Implementation may look a little weird.  Why have config_reload() call down into stats.[ch], …
> job-list: initialize queue stats

- .github/workflows/asan.yml
- .github/workflows/codeql.yml
- .github/workflows/main.yml
Problem: Github warns that
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/checkout@v3.
Update to checkout@v4 to silence the warnings.
> github: update checkout action to v4 to silence warnings

- src/shell/pmi/pmi.c
- t/t3001-mpi-personalities.t
- t/t3002-pmi.t
Problem: Flux installs its `libpmi.so` and `libpmi2.so` in a directory that is not searched by `ld.so` by default, which creates problems such as #5714 
When simple PMI is active (a requirement for Flux pmi libs to be functional), prepend this directory to LD_LIBRARY_PATH.
This will break the coral2 `cray-pals` plugin.  Or rather, it will prevent Cray MPICH from finding cray `libpmi2.so`, which will render `cray-pals` ineffectual.  So flux-framework/flux-coral2#122 should go in first.
> pmi: prepend Flux PMI directory to LD_LIBRARY_PATH

- doc/man1/flux-shell.rst
- src/shell/shell.c
This simple PR just adds a new shell plugin callback topic: `shell.post-init`. This will be convenient for plugins that want to run after all other plugin `shell.init` callbacks have run, but before the first `task.init` callback (which is supposed to be task-specific).
It will be used in the solution for #5718.
> shell: add `shell.post-init` plugin calllback topic between `shell.init` and first `task.init`

- doc/man1/common/job-shell-options.rst
- doc/man1/flux-shell.rst
- doc/test/spell.en.pws
- src/shell/Makefile.am
- src/shell/batch.c
- src/shell/builtins.c
- src/shell/builtins.h
- src/shell/hwloc.c
- t/Makefile.am
- t/t2619-job-shell-hwloc.t
This PR adds a new `hwloc` shell builtin plugin which export the shell hwloc XML to a file and sets `HWLOC_XMLFILE` if `-o hwloc.xmlfile` is used.
An hwloc object is used instead of `-o hwloc=xmlfile` to allow other keys to be open for future use, though I can't think of any other hwloc options we might want to use in the job shell at the moment.
The `hwloc.xmlfile` value is checked in `shell.post-init`, which means other plugins may request this behavior from `shell.init` or earlier by using `flux_shell_setopt_pack(3)`.
This is a WIP while I develop some simple tests. However, I wanted folks to get a chance for early comments on the general approach.
Fixes #5718
> shell: write hwloc XML to a file with `HWLOC_XMLFILE` set with `-o hwloc.xmlfile`

- doc/man1/common/job-shell-options.rst
- doc/man1/flux-shell.rst
- doc/man3/flux_shell_get_info.rst
- src/shell/internal.h
- src/shell/output.c
- src/shell/shell.c
- src/shell/shell.h
- t/system/0001-basic.t
- t/t2606-job-shell-output-redirection.t
- t/t9000-system.t
This PR adds support for a new `output.limit` job shell option which overrides the default KVS output limit.
The limit remains `10M` for multiuser instance jobs (when broker userid != job shell userid), but the limit is removed for single-user jobs (broker userid == shell userid).
This should resolve some of the issues users have hit with the KVS output limit inside batch jobs, where it is most convenient to have jobs output folded in with that of the batch output file.
> shell: make kvs output limit configurable and default single-user jobs to unlimited

- doc/man1/flux-job.rst
- src/common/libtaskmap/taskmap.c
- src/common/libtaskmap/taskmap.h
- src/common/libtaskmap/test/taskmap.c
Specification of a manual host to task rank mapping requires the `--taskmap=manual:ARG` scheme, where `ARG` is processed by libtaskmap `taskmap_decode(3)`, and thus supports either PMI_process_mapping style vector, or an [RFC 34 Task Map](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_34.html). These mappings are somewhat compact, but they aren't exactly user-friendly.
The 'raw' taskmap used in RFC 34 is simple to understand, and in fact users are encouraged to use `flux job taskmap --to=raw TASKMAP` to aid in creation and understanding of the taskmap format. However, it would be even more convenient if `flux job taskmap` could take a raw taskmap as input and emit an RFC 34 compatible taskmap.
This PR enables this practice by supporting raw taskmaps in …
> libtaskmap: support decode of raw (semicolon-delimited) taskmaps

- src/shell/shell.c
- t/t2616-job-shell-taskmap.t
This simple PR fixes #5723: If a user inadvertently specifies `--taskmap=block:arg` when they meant `--taskmap=other_scheme:arg`, the shell currently silently ignores `arg` and silently continues with the `block` scheme. Since an argument is not expected or allowed with the `block` taskmap scheme, the shell should generate an error in this case. 
Fixes #5723
> shell: generate fatal error if `block` taskmap scheme has an argument

- src/cmd/flux-perilog-run.py
- t/t2274-manager-perilog.t
This PR fixes #5734 and adds a test for the issue to the testsuite.
> do not drain ranks when job is canceled during prolog

- doc/Makefile.am
- doc/man1/flux-hostlist.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/bindings/python/flux/util.py
- src/cmd/Makefile.am
- src/cmd/flux-hostlist.py
- t/Makefile.am
- t/t2814-hostlist-cmd.t
As described in #3344, this PR adds an implementation of a `flux hostlist` command.
This implementation takes a set of hostlist "sources" on the command line, appending multiple sources by default, and returns the result on stdout. Several options are provided to manipulate, modify, or query the result before it is emitted:
```
usage: flux-hostlist [-h] [-e] [-d S] [-c] [-n N] [-L N] [-S] [-x HOSTS]
[-u | -i | -m | -X] [-f] [-q]
[SOURCES ...]
positional arguments:
SOURCES              (optional) One or more hostlist sources
options:
-h, --help           show this help message and exit
-e, --expand         Expand hostlist using defined output delimiter
-d, --delimiter=S    Set output delimiter for expanded hostlist
(default=',')
-c, --count          Print the total number of hosts
-n, …
```
> add flux-hostlist(1)

- src/cmd/flux-job.c
- src/common/libjob/job.h
- src/modules/job-info/job-info.c
- src/modules/job-info/job-info.h
- src/modules/job-info/lookup.c
- src/modules/job-info/lookup.h
- src/modules/job-info/update.c
- src/modules/job-info/update.h
- src/modules/job-info/util.c
- src/modules/job-info/util.h
- t/job-info/info_lookup.c
- t/job-info/update_lookup.c
- t/kvs/lookup_invalid.c
- t/t2230-job-info-lookup.t
- t/t2233-job-info-update.t
This PR could be split up a bit more, but for now it's one PR.
This adds several new lookup flags, and with their addition, the `job-info.update-lookup` RPC target can be deprecated.
The one "tricky" part was how to grab cached data from current `update-watch`es being done.  Perhaps the lookup of that "cached" info could just be dropped as it probably has minimal use.
I decided to not support `job-info.update-watch` within the original `job-info.lookup` RPC for several reasons.  Most notably because `lookup` can take multiple keys as input and `job-info.update-watch` takes only one key.  I could make it so a WATCH flag only works with one key.  Or we could have a "re-direct to this RPC" like we do with KVS watch.  But I didn't delve too much into this design yet.
~~I then updated PR #5592 …
> job-info: add JSON_DECODE & CURRENT flags, deprecate job-info.update-lookup

- src/bindings/python/flux/job/kvslookup.py
- src/cmd/flux-job.c
- src/common/libjob/job.h
- src/modules/job-info/lookup.c
- src/modules/job-info/update.c
- src/modules/job-info/util.c
- src/modules/job-info/util.h
- t/python/t0014-job-kvslookup.py
- t/t2233-job-info-update.t
Problem: It is inconvenient that lookup w/ updates and update-watch support reading/watching an updated R but not an updated jobspec.
Support returning an updated jobspec.
Then remove the manually updated jobspec/R code in `flux-job` and the Python `kvslookup` library.  
Built on top of #5633.
Could potentially be split into two PRs ....
> job-info: support lookup of updated jobspec, remove manual construction of updated R / jobspec

- src/cmd/job/eventlog.c
- t/t2201-job-cmd.t
- t/t2230-job-info-lookup.t
- t/t2231-job-info-eventlog-watch.t
- t/t2232-job-info-security.t
- t/t2402-job-exec-dummy.t
- t/t2404-job-exec-multiuser.t
- t/t2500-job-attach.t
- t/t2501-job-status.t
- t/t2602-job-shell.t
- t/t2607-job-shell-input.t
- t/t2609-job-shell-events.t
- t/t2610-job-shell-mpir.t
- t/t2612-job-shell-pty.t
- t/t2614-job-shell-doom.t
- t/t2616-job-shell-taskmap.t
This PR is a simple update to add some shorthand names for well-known eventlogs wih `flux job wait-event` and `flux job eventlog`. It is a bit cumbersome to always be typing `flux job eventlog -p guest.exec.eventlog`, and after this PR you can just do `flux job eventlog -p exec ...`.
> flux-job: add shorthand paths for `flux job eventlog` and `wait-event`

- t/t0021-archive-cmd.t
Problem: the randbytes() function in t0021-archive-cmd.t uses /dev/random to create files of size 128 and 2048 bytes, respectively. However, /dev/random can be truncated at <128 bytes and, when it is, the file created by dd will be as well. This causes a size mismatch in the kvs, which causes tests 13, 14, and 18 to fail. This first showed up in GitLab CI on TOSS 4.
We can instead utilize the /dev/urandom file, which is not truncated, and thus guaranteed to create files of the proper sizes. Also, some cleanup of t0021-archive-cmd.t is baked into this PR.
When merged, closes issue #5750.
> testsuite: fix random-generation of kvs archive files in t0021

- t/t2617-job-shell-stage-in.t
Oops. Yesterday, when we were fixing the `/dev/random` file creations, we missed one. That's my bad.
I ran a `git grep "/dev/random"` to make sure we got them all. Should be good after this.
> testsuite: fix t2617 to utilize /dev/urandom

- src/shell/shell.c
- t/t2603-job-shell-initrc.t
Embarrassingly, the values returned for non-local shell ranks from `flux_shell_get_rank_info(3)` and associated calls has been wrong. The local values are always returned even if the "info" for a different shell rank is requested.
This PR fixes the object constructed for this and associated calls to return the correct information, and includes what was obviously a missing test.
> shell: fix incorrect values returned from `flux_shell_get_rank_info(3)`

- src/broker/groups.c
- t/scripts/groups.py
- t/t0027-broker-groups.t
Problem: `groups.join` and `groups.leave` RPCs do not behave as designed when used remotely, but this is allowed by the RPC handlers.
Respond with an error if the join/leave request is not of local origin.
> broker: catch an improper use of groups and handle it gracefully

- doc/man1/flux-job.rst
- doc/test/spell.en.pws
- etc/completions/flux.pre
- src/cmd/Makefile.am
- src/cmd/job/attach.c
- src/cmd/job/hostpids.c
- src/cmd/job/main.c
- src/cmd/job/mpir.c
- src/cmd/job/mpir.h
- src/shell/mpir/rangelist.c
- src/shell/mpir/test/rangelist.c
- t/t2201-job-cmd.t
This PR adds a `flux job hostpids` command which uses the job shell's `proctable` RPC to emit the `host:PID` pairs for all tasks in a job.
This is useful for tools that take this information on the command line and do not support Flux natively.
> add `flux job hostpids` command

- src/cmd/job/mpir.c
- src/shell/mpir/mpir.c
- src/shell/mpir/proctable.c
- src/shell/mpir/proctable.h
- src/shell/mpir/test/proctable.c
- t/Makefile.am
- t/shell/mpir.c
- t/t2610-job-shell-mpir.t
This PR adds the minimum support for the MPIR tool daemon launch extensions documented in [The MPIR Process Acquisition Interface Version 1.1 ](https://www.mpi-forum.org/docs/mpir-specification-03-01-2018.pdf), Section 7.1. It also splits the MPIR code in `src/cmd/job/attach.c` into its own source file so that the implementation can be tested with the "shell" mpir test utility in `t/shell/mpir.c`.
Currently the tool specified in `MPIR_executable_path` and `MPIR_server_arguments` is launched with libsubprocess. We depend on the disconnect handler to clean up stray tool processes if `flux job attach` is terminated or otherwise exits early.
This is currently a WIP because it adds a list of task/broker rank pairs to the shell `proctable` response since this was the simplest approach for now, …
> flux-job: attach: support MPIR tool launch extension

- doc/man1/common/job-shell-options.rst
- doc/man1/flux-shell.rst
- src/shell/output.c
- t/t2606-job-shell-output-redirection.t
This PR adds a new job shell output option `output.mode`. The valid values are "truncate" (the default) and "append", which opens any output files with `O_APPEND` instead of `O_TRUNC`.
> shell: support opening output files with `-o output.mode=append`

- .github/workflows/codeql.yml
- .github/workflows/main.yml
- src/test/generate-matrix.py
This PR fixes warnings about `Node.js 16 actions are deprecated.` 
Also, now that 4 cores are available to Github actions builders increase coverage build parallelism to `-j4`.
> github: update deprecated actions

- .github/workflows/main.yml
- .typos.toml
- NEWS.md
- src/broker/boot_pmi.c
- src/cmd/builtin/relay.c
- src/cmd/flux-module.c
- src/modules/resource/reslog.h
- src/modules/resource/topo.c
- t/t0005-exec.t
- t/t2110-job-ingest-validator.t
The obligatory typo fix PR.  Feel free to push here.
> fix various typos

- doc/guide/admin.rst
- doc/test/spell.en.pws
- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog.t
On large systems, the `flux-perilog-run` script is generating hundreds of lines of useless output from an asyncio issue (see #5752). Additionally, there could be lots of other output or errors from the prolog/epilog that should be suppressed.
This PR introduces a new configuration list `job-manager.perilog.log-ignore` that contains a list of regexes to suppress from the logs for the prolog and epilog.
> job-manager: support suppression of prolog/epilog output with `perilog.log-ignore` pattern list

- NEWS.md
Problem: There's no release notes for flux-core v0.60.0.
Add release notes for this version.
This assumes the MPIR and typos PRs will be merged in time for this release.
> NEWS: add release notes for v0.60.0

- src/modules/content/cache.c
Problem: sometimes brokers hit an assertion when the content module is unloaded during shutdown.
The assertion is that there are no pending load/store operations waiting on a cache entry when it is destroyed.  This is certainly possible, depending on the behavior of users of the load/store RPCs.  In the case of unload in rc3, dependent modules would have already been unloaded, so it seems safe to simply destroy any pending RPCs without responding to them.
Destroy them, if present.
Fixes #5706
> modules/content: drop incorrect assertion

- src/bindings/python/flux/job/watcher.py
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/bulk-exec.h
- src/modules/job-exec/exec.c
- src/shell/doom.c
- src/shell/exception.c
- src/shell/output.c
- t/Makefile.am
- t/issues/t2492-shell-lost.sh
- t/t2614-job-shell-doom.t
Currently, job shells are detected as "lost" during a job only if a whole node or broker disappears. If a job shell abnormally terminates for some other reason, the rest of the job is not aware which can lead to hangs at exit as noted in #2492.
Also, tasks managed by lost shells are not considered exited, so the exit-timeout and exit-on-error parameters do not have an effect in this case, which could lead a broken job to run until its timeout.
This PR attempts to partially address this situation by having the job execution system report to the leader shell when any other job shell terminates due to a signal. Other abnormal exit conditions are not captured because this is expected behavior, and the hope is that the shell was able to complete its normal shutdown activities in this case, …
> improve handling of lost job shells

- src/common/libschedutil/init.h
- src/common/libschedutil/ops.c
- src/common/libschedutil/ops.h
- src/modules/job-manager/alloc.c
- src/modules/sched-simple/sched.c
- t/t2300-sched-simple.t
Problem: R has to be looked up from the KVS in the `sched.free` request handler, but now that the job manager caches R, this is an unnecessary extra step.
Add R to the `sched.free` request payload.
Note that the `R.scheduling` key is not included.  The current design of Fluxion in which `R.scheduling` may contain a voluminous JGF object made caching this part of R impractical.
Change libschedutil so that
- the `sched.free` message handler never looks up R in the kvs
- the free callback always sets its `R` argument to NULL
- the SCHEDUTIL_FREE_NOLOOKUP flag is a no-op
Update sched-simple's free callback to unpack R from the message instead of decoding the `R` arugment.
Note that Fluxion sets SCHEDUTIL_FREE_NOLOOKUP so it already expects the free callback's R argument to be NULL.  Although …
> job-manager: include R in sched.free request

- src/cmd/flux-queue.py
- src/common/libschedutil/free.c
- src/common/libschedutil/free.h
- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job.h
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/test/job.c
- src/modules/sched-simple/sched.c
- t/t2223-job-manager-queue-priority-order-limited.t
- t/t2224-job-manager-queue-priority-order-unlimited.t
- t/t2240-queue-cmd.t
- t/t2300-sched-simple.t
Problem: the `sched.free` RPC requires a response but the response is unnecessary for correct job management.
Moreover, the coupling between the RPC response and the job state machine makes some anticipated changes harder to design.
Make `sched.free` a "fire and forget" RPC.  Simply post the `free` event immediately instead of deferring it until the response is received..
Update `flux queue status -v` output to not show pending free rpcs, since they can no longer be pending.
This change should be accompanied by an update to RFC 27.
> job-manager: drop sched.free response requirement

- t/issues/t2492-shell-lost.sh
Problem: the t2492-shell-lost.sh sends a SIGKILL to the wrong process.
This test runs a job whose two tasks on shell rank 3 try to send a SIGKILL to their parent, the shell.  One succeeds and the other, slower, task may be reparented before calling os.getppid and thus sends the signal to the wrong task.
Running two tasks per shell seems like it doesn't further the purpose of the test so just run one task per shell.
Fixes #5791
> testsuite: fix test that kills the wrong processes

- .github/workflows/asan.yml
Problem: The address sanitizer CI build started failing for unknown reason. The failure is occurring in the make program before even running any tests in 'make check.'
Take the following steps to attempt to address the issue:
- The asan build currently runs on Fedora 34, which is getting old at this point. Update the sanitizer run to use Fedora 36.
- Drop the LD_PRELOAD of the libasan library, which seems to be causing the failure in some unrelated programs not compiled with -fsanitize=address (a guess).
- Add 'verify_asan_link_order=false' to ASAN_OPTIONS to avoid libasan complaints about link order. This is only important if malloc, free, etc., are replaced by libs. In that case libasan _must_ be first in the link order. See https://github.com/google/sanitizers/wiki/AddressSanitizerFlags …
> github: run asan build on fedora36

- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
This PR fixes the crash in the job-exec module described in #5782.
As described there, the issue was a use-after-free in libsubprocess when a signal is sent to a remote subprocess before the subprocess is running.
I ran the reproducer below for 4 hours with no crashes on this branch. On master the issue reproduces within 30m reliably.
reproducer:
```
$ flux run -o cpu-affinity=off -o mpibind=off \
--env=MALLOC_CONF=junk:true,tcache:false \
--env=LD_PRELOAD=/g/g0/grondo/git/jemalloc/lib/libjemalloc.so \
-o pty.interactive -o pty.capture -n 768 -N32  \
src/cmd/flux start -o,-Stbon.topo=kary:800
$ while true; flux submit --cc=1-2048 true \
&& sleep 60 \
&& flux cancel --all \
&& sleep 30 \
&& flux cancel --all \
&& sleep 5 \
&& flux cancel --all \
&& flux queue idle; \
done
```
> job-exec: fix rare segfault at scale due to libsubprocess use-after-free

- t/t2800-jobs-recursive.t
- t/t2802-uri-cmd.t
This PR attempts to fix or workaround an issue that I keep seeing: A couple orphaned instances that stick around after `make -j N check`. A quick investigation showed that the instances all had a sleep job stuck in CLEANUP, with the scheduler unloaded, and had at least instance-level 1 (so they were batch jobs run within the test instance).
I wasn't really able to make a reproducer for this issue, but terminating the affected instances more cleanly seems to resolve the problem (at least in my testing), so it seems like a good idea to do that.
> testsuite: fix lingering processes after `make check`

- .github/workflows/main.yml
- pyproject.toml
- scripts/requirements-dev.txt
- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/util.py
- src/bindings/python/flux/wrapper.py
- src/cmd/flux-pgrep.py
- src/test/generate-matrix.py
- t/issues/t5308-kvsdir-initial-path.py
- t/job-manager/bulk-state.py
- t/jobspec/summarize-minimal-jobspec.py
- t/jobspec/y2j.py
- t/python/tap/pycotap/__init__.py
- t/scripts/strerror_symbol
Dependabot noted a potential security issue in our currently required version of `black` in #5806, but a bit more than just bumping the version was required to get the suggested `black` version working, so I've done that here. This included apply the very minor formatting changes enacted by the new version.
The changes also required an update of `mypy`, so I've bumped that to the latest version as well. There did not seem to be any fallout.
Pending PRs _may_ have to reformatted if they include python code. However, I was surprised how little changed in the formatting when updating to the new black version.
> python: update required versions of black and mypy

- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/rset.c
- src/modules/job-exec/testexec.c
- src/shell/exception.c
This PR fixes #5811 by always notifying the leader job shell of lost shells, whether they are critical or not. This then allows the leader shell to exit quickly when all its tasks terminate, rather than waiting for EOF from a lost shell during abnormal termination.
> job-exec: improve cleanup after lost shell events

- src/modules/job-exec/exec.c
- t/issues/t2492-shell-lost.sh
While working on #5813 I noticed the job execution system doesn't raise a fatal job exception and initiate cleanup when the rank 0 job shell is lost due to a signal. This could lead to a hang because the other job shells may continue running even though the job really can't continue without the leader shell.
The leader shell is currently notified if any non-rank-0 shell exits due to a signal. Expand this to raise a fatal error if the rank 0 shell exits due to a signal.
Expand the lost shell testing to test loss of rank 0 as well as rank 3 job shells.
This is based on top of #5813 to avoid conflicts.
> job-exec: raise fatal job exception if rank 0 job shell is lost due to signal

- src/modules/job-manager/jobtap.c
- t/t2212-job-manager-plugins.t
A missing `zlistx_next()` in the jobtap code that searches for a matching builtin plugin name causes an infinite loop if a builtin plugin is loaded that doesn't match the first plugin name in the list.
Also, though it isn't advisable to specify a relative plugin path to `flux jobtap load`, if this is done and the path starts with `.`, the current code assumes a builtin plugin is specified.
This PR fixes both these issues.
> job-manager: fix infinite loop when loading builtin jobtap plugin

- src/cmd/flux-resource.py
This PR improves the performance of `flux resource list` by modifying some really inefficient code:
- The `ResourceSetExtra` wrapper class unnecessarily reinitializes the `ResourceSet` argument. Just stash the `ResourceSet` instead and forward method calls to it to avoid this wasted work.
- `resources_uniq_lines()` iterates over each individual rank in each resource set to collect common lines of output together. Instead, split a resource set into all combinations of properties and iterate each of these sets. This _should_ be the minimum number of sets required to create possibly unique lines (at least at this point). This reduces the iteration count significantly.
Timing before with a very large resource set (~10K ranks):
```
time flux resource list --from-stdin < ../../large-list.json …
```
> flux-resource: improve performance of `flux resource list`

- src/bindings/python/flux/core/handle.py
- t/issues/t2492-shell-lost.sh
- t/python/t0003-barrier.py
`flux_barrier(3)` returns a `flux_future_t`, but the Python handle barrier method returns nothing.
This PR returns a Future from `handle.barrier()` as is necessary for proper functionality and updates callers.
Note: Clearly the barrier unit tests were not working, but I didn't have any good ideas how to properly test the barrier functionality, so left it alone for now besides addition of the missing `get()` calls.
> python: fix handle barrier method to return a Future

- src/common/libidset/idset.c
- src/common/librlist/rnode.c
This PR fixes some key hotspots in librlist and libidset found while profiling poor `flux resource list` performance.
This is based on #5823 just to show the cumulative performance gains.
On #5823:
```
$ time src/cmd/flux resource list --from-stdin < ../../large-list.json >/dev/null
real	0m1.790s
user	0m1.662s
sys	0m0.102s
```
On this PR branch:
```
$ time src/cmd/flux resource list --from-stdin < ../../large-list.json >/dev/null
real	0m0.826s
user	0m0.715s
sys	0m0.100s
```
> optimize key librlist functions to improve `flux resource list` performance

- doc/man1/flux-resource.rst
- doc/man7/flux-environment.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/resource/list.py
- src/cmd/top/summary_pane.c
- src/modules/Makefile.am
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/alloc.c
- src/modules/resource/Makefile.am
- src/modules/resource/acquire.c
- src/modules/resource/monitor.c
- src/modules/resource/resource.c
- src/modules/resource/resource.h
- src/modules/resource/status.c
- src/modules/resource/status.h
- t/t2350-resource-list.t
As discussed in #5776, this adds
- resource tracking in the job manager and a new RPC to request the current set of allocated resources
- expansion of the payload of `resource.status` to include the keys found in `sched.resource-status`
- update users (top, python) to call `resource.status` instead of `sched.resource-status`
Marking as a WIP pending
> add a faster way to get resource allocation status than sched.resource-status RPC

- src/bindings/python/flux/cli/base.py
- t/t2713-python-cli-bulksubmit.t
The `flux submit` and `flux bulksubmit` commands fail to preserve mustache templates in the job command.
This PR fixes that.
> fix `flux submit` and `bulksubmit` handling of mustache templates in command and args

- src/modules/job-ingest/job-ingest.c
- t/t2100-job-ingest.t
Problem: the fix for #5708 (gracefully handling FLUID ID range errors on nodes >= 16K) is incorrect. 
Fix it and add tests.
Also: reserve the top 16 generator IDs for future use as this may be hard to do later when Flux has actually been run on large systems.
> job-ingest: fix handling of size > 16K and reserve some FLUID generator IDs for future use

- src/common/libterminus/client.c
- src/common/libterminus/pty.c
- t/t2612-job-shell-pty.t
This PR fixes handling of `NUL`s in pty data handling. Jansson by default will not unpack `NUL` unless `JSON_ALLOW_NUL` is used, so the read side of the pty was just dropping them.
As part of developing a test, an issue with `echo something | flux run -o pty.interactive ...` was discovered, which is also fixed here.
Fixes #5832
> fix handling of `Ctrl-SPACE` (`NUL`) over job ptys (e.g. under `flux job attach`)

- doc/man7/flux-environment.rst
- src/bindings/python/flux/job/info.py
- src/bindings/python/flux/resource/list.py
- src/cmd/top/summary_pane.c
- t/t2350-resource-list.t
- t/t2801-top-cmd.t
This PR implements the compatibility fallback for users of the new `resource.sched-status` RPC, so that these interfaces and utilities will still work when run against older versions of Flux.
Since `flux-top(1)` was the only C user of this RPC, a fallback was added in place for the summary pane.
For Python, the `ResourceListRPC` class is reworked to implement the fallback, so that all callers benefit.
The handy existing `FLUX_RESOURCE_LIST_RPC` environment variable is then used for testing purposes. By setting the rpc to an invalid value, the fallback is forced.
> support fallback to the old `sched.resource-status` RPC for tools that use the new `resource.sched-status` RPC

- doc/man7/flux-jobtap-plugins.rst
Problem: flux-jobtap-plugins(7) does not document that a redacted R is available in plugin arguments after a job is in the RUN state, nor that an R may be returned in the plugin output arguments from job.state.sched to bypass the scheduler and provide a custom R for a job.
Update flux-jobtap-plugins(7) to document this information.
> doc: add missing R documentation to flux-jobtap-plugins(7)

- configure.ac
Problem: flux-core requires the Python ply module, but configure doesn't check for it.
Add a check for this required module in configure.
Fixes #5444
> configure: add missing check for python ply >= 3.9

- doc/man1/flux-shutdown.rst
- etc/flux.service.in
- src/cmd/Makefile.am
- src/cmd/builtin/dump.c
- src/cmd/builtin/restore.c
- src/cmd/builtin/shutdown.c
- t/system/0004-recovery.t
- t/t2808-shutdown-cmd.t
- t/t9000-system.t
This enables KVS garbage collection when flux is started with systemd, and wires `flux-dump(1)` and `flux-restore(1)` into sd_notify(3) so that systemd won't kill the dump process if it takes too long, and `systemctl status flux` will show regular updates about how many keys have been dumped/restored.
I've tested this on my home system by beefing up the content store and reducing the TimeoutStopSec=90 in the unit file to just a few seconds.  Definitely kills flux-dump without this PR, and does not with it.
I probably need to add a little more testing but thought I'd post this as is since dinner just arrived!
> make KVS garbage collection automatic

- src/cmd/job/eventlog.c
- t/t2231-job-info-eventlog-watch.t
This PR fixes context matching in `flux job wait-event -m, --match-context`, which currently returns a match if the value matches but key does not.
> flux-job: fix `wait-event -m, --match-context`

- pyproject.toml
- src/cmd/Makefile.am
- src/cmd/flux-post-job-event.py
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/post-event.c
- t/Makefile.am
- t/t2815-post-job-event.t
Jobs can end up stuck in CLEANUP state if, for example, an `epilog-start` event is posted with no corresponding `epilog-finish` event. This can occur if the rank 0 broker restarts when a job epilog is running. Currently, to clean up this state a special, one-off jobtap plugin must be loaded to manually post the missing `epilog-finish` event.
Actually, my guess is this issue will be rare if we've fixed the broker crash that's been the most common cause of this condition. However, it might be useful to have on hand a more usable utility to post custom job events for this case or any other similar problems that might arise.
To that end, this PR adds a simple builtin jobtap plugin that can accept events for jobs as an RPC, and posts them to the requested jobid. A front-end command is then …
> add utility for posting job events manually if required

- doc/Makefile.am
This is minor, but it would be useful if `doc/requirements.txt` was in the distribution tarball and it currently is not.
This simple PR adds it.
> add `doc/requirements.txt` to dist

- NEWS.md
First cut at a `NEWS.md` update for v0.61.0. (Assuming #5848 and #5846 will be merged)
Feel free to push directly here as necessary.
> NEWS.md: add release notes for 0.61.0

- src/modules/job-list/job_data.c
- src/modules/job-list/job_data.h
- src/modules/job-list/job_state.c
Problem: Older code that handled jobspec/R updates when jobspec/R were not yet read in from the KVS.  This code is no longer necessary now that jobspec/R are sent via the event journal.
Remove all traces of cached "jobspec_updates" and "R_updates" code.
> job-list: remove jobspec/R update dead code

- doc/guide/admin.rst
Problem: some code formatting is wonky in the admin guide because of whitespace issues.
Fix it.
> doc: fix whitespace issues in admin guide

- doc/Makefile.am
- doc/conf.py
I ran into an issue building the documentation while following the README, `sphinx-build` couldn't find the `manpages` module. Adding the path to `sys.path` manually or on a one-off basis is easy enough but I think adding this will be a bit more foolproof?
> doc: add path to 'manpages' to conf.py

- src/modules/job-list/job_state.c
- src/modules/job-manager/event.h
- src/modules/job-manager/journal.c
- src/modules/job-manager/prioritize.c
@chu11 and I were both looking through the job-list source to be sure all is OK before we tag, and we both spotted some incorrect source comments.  Al, feel free to add to this PR.
> minor cleanup in job-manager journal and job-list (mostly inline docs)

- src/common/librlist/rlist.c
- src/modules/resource/Makefile.am
- src/modules/resource/drain.c
- src/modules/resource/drainset.c
- src/modules/resource/drainset.h
- src/modules/resource/rutil.c
- src/modules/resource/rutil.h
- src/modules/resource/status.c
- src/modules/resource/test/drainset.c
- src/modules/resource/test/rutil.c
- t/t2312-resource-exclude.t
This PR improves the time it takes the `resource` module to assemble the `drain` key in the `resource.status` response when there are many drained targets.
The previous method of building the response piecemeal in a `json_t` object is dropped in favor of a custom class that more efficiently represents a set of drained ranks.
A sharness test that simulates a 2^14 size instance was used to simulate some worst-case performance scenarios at scale. The `resource.status` RPC was timed in the following scenarios:
- no drained ranks
- 16,000 drained ranks, but matching timestamps and reason fields
- 16,000 drained ranks, each with differing timestamp or reason fields
The timing is for just the RPC (i.e. `future.wait_for(-1)` was used instead of `future.get()` to avoid the penalty of …
> resource: improve `resource.status` response time with many drained ranks

- src/bindings/python/flux/resource/status.py
- src/cmd/flux-resource.py
This PR picks off some more performance issues in `flux resource list` and `status`.
It is built on top of #5863.
This reduces the time for `flux resource list` on a large system with queues from 5s to ~2s, and reduces the `flux resource status` time when there are 16K drained ranks from >40s to ~7s.
> fix more performance issues in `flux resource`

- src/modules/resource/drain.c
This PR rounds the drain timestamp in the resource module while building the drain object for a `resource.status` response. The idea here is that this will allow more compression in the `drain` object in the response and also result in less lines of output in `flux resource drain` (when sub-second precision in the output is used)
A kind of best case scenario is show by separately draining 16000 nodes, such that each rank has a different timestamp (but many are actually within the same second)
before
```
expecting success:
flux dmesg -c >/dev/null &&
time rpc "resource.status" >rstatus.json
flux dmesg -HL
real    0m0.766s
user    0m0.193s
sys     0m0.040s
ok 7 - time resource.status rpc
expecting success:
time flux python -m cProfile -o prof.out $flux_resource status
STATE UP NNODES …
```
> resource: round timestamp of drained ranks

- src/common/librlist/rlist.c
- src/common/librlist/test/rlist.c
This PR fixes issue #5856.
When ranks are excluded, the resource module removes them from the constructed rlist with `rlist_remove_ranks()`. However, there is a bug in `rlist_remove_ranks()` that leaves pointers to the destroyed `rnode` objects in the rnode lookup hash. This causes a subsequent `rlist_mark_down()` to crash if an excluded rank is also down.
This PR fixes that main issue and also ignores missing ranks in `rlist_mark_down()` and `rlist_mark_up()` to avoid a subsequent NULL deref.
> fix broker crash in `resource.status` RPC handling when exlcuded ranks are also down

- etc/rc1
Problem: when flux is shutting down and canceling running jobs, the epilog can greatly extend the shutdown time.
Unload the perilog plugin as part  of the cleanup tasks so that canceled jobs can complete quickly in the shutdown case.
Note: @grondo's good IMHO idea!  This was peeled off of #5860 because it seems like it might be a good candidate for a point release, whereas #5860 is too big of a change for that.
> shutdown: unload perilog plugin during shutdown

- NEWS.md
Problem: There are no release notes for v0.61.1.
Add release notes to NEWS.md for v0.61.1.
> NEWS.md: add release notes for 0.61.1

- t/t3203-instance-recovery.t
This PR fixes a couple issues discovered in `t3203-instance-recovery.t` when run under `fakeroot`.
> testsuite: fix `t3203-instance-recovery.t` under `fakeroot`

- src/broker/overlay.c
- src/cmd/builtin/proxy.c
This just ignores the PATCH number in MAJOR.MINOR.PATCH version comparisions in the broker so we can install a patch version without restarting all of flux at once.
Also, if we're going to assume PATCH versions interoperate we may as well relax the check in flux-proxy, so do that too.
> broker: allow patch versions to interoperate

- src/broker/broker.c
- src/broker/module.c
- src/broker/module.h
- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/annotate.c
- src/modules/job-manager/annotate.h
- src/modules/job-manager/event.c
- src/modules/job-manager/prioritize.c
- src/modules/job-manager/queue.c
- t/Makefile.am
- t/t0003-module.t
- t/t2305-sched-slow.t
Problem: when a job is canceled with an outstanding sched.alloc request, the job is stuck in CLEANUP until the scheduler responds.
When the scheduler is slow, this needlessly prevents the job from terminating.
When the job enters CLEANUP state with a pending sched.alloc, send the cancel request as before but immediately remove the job from the pending_jobs list and clear job->alloc_pending.  The job can then transition to INACTIVE after the other cleanup activities are completed.  Meanwhile, when a response is received to sched.alloc, handle it internally.  If the alloc was successful, immediately free the resources.  If the alloc was canceled or unsuccessful, simply ignore the response.
Fixes #5876
~Marking WIP pending figuring out how to add a test.~
> job-manager: canceled job need not wait for sched

- NEWS.md
Problem: There are no release notes for v0.61.2.
Add release notes to NEWS.md for v0.61.2.
> NEWS.md: add release notes for 0.61.2

- src/test/docker/docker-run-checks.sh
Recently, several core developers have noted that the docker-run-checks.sh script borks when command-line options that specify values do so with an equals sign rather than a space. Since this is not super intuitive, update the usage/help message for that script accordingly.
I pulled out all the = signs from the usage message and added a note, but maybe one or the other is more desirable.
> docker: add script help message for macOS

- src/cmd/job/attach.c
- src/common/libjob/job.c
- src/common/libjob/job.h
- src/common/libjob/test/job.c
- src/modules/job-manager/wait.c
- t/t2500-job-attach.t
This PR adds a new `flux_job_waitstatus_to_exitcode(3)` function to libjob which replaces some custom code in `flux job attach` and the job-manager wait implementation.
In this implementation, the error message properly reports `job shell <sigstr>` when the _shell_ exited due to a signal (i.e. `WIFSIGNALED (waitstatus)` is nonzero), and `task(s) <sigstr>` if one or more _tasks_ exited due to a signal (exitcode > 128).
The job manager wait code and `flux job attach` are then updated to use this new function, and therefore `flux job wait` and `flux job attach` now consistently report the correct error output for these conditions.
> properly report signaled tasks in `flux job wait` and `flux job attach`

- src/common/librlist/rlist.c
Problem: rlist_to_R() does not sort the internal list of nodes before generating R. This results in larger JSON output than necessary, especially for an rlist built from multiple rlist_append() operations.
Sort rnodes by rank in rlist_to_R() before generating the JSON result.
Fixes #5885
> librlist: sort rlist before generating R

- src/common/libterminus/test/terminus.c
Problem: The terminus server function in the terminus unit tests calls `setenv(3)`, but this function is run in a thread and `setenv(3)` is not thread safe. This could result in rare segfaults if reading the environment races with setting it during the test.
Move the `setenv` to main(), there's no reason to be setting the environment variable specifically in terminus_server() anyway, since this is a unit test, all invocations of the server should have `FLUX_TERMINUS_TEST_SERVER` set.
Fixes #3120
> fix potential segfault in test_terminus.t

- etc/rc1
- src/modules/job-manager/plugins/perilog.c
- t/Makefile.am
- t/issues/t5892-shutdown-no-epilog.sh
Problem: most unfortunately, a typo in rc1 rendered #5871 ineffectual.
Fix the typo and add a test this time.
> suppress epilog on jobs canceled during shutdown (try no. 2)

- src/broker/module.c
Tiny change, but handy.
problem: As it is, all threads are named `flux-broker-<num>` when identified with `info threads` in gdb, or in perf, or wherever.
solution: Since almost all threads are actually actors executing a specific module, name the thread using the module name during module setup.
Here's an example "after":
> broker/module.c: name threads

- src/modules/job-manager/plugins/alloc-check.c
- t/t2303-sched-hello.t
Problem: when a job gets a `scheduler-restart` exception due to RFC 27 hello failure with the scheduler, the `alloc-check` plugin does not properly account for resources.
Fix that by handling the exception in the jobtap plugin.
In addition, eliminate a synchronous KVS lookup of R since R is now available as a jobtap callback argument, which should reduce the overhead of loading this plugin.
> alloc-check: account for resources in scheduler hello failure

- src/cmd/builtin/dmesg.c
- src/cmd/builtin/overlay.c
- src/cmd/flux-kvs.c
- src/cmd/job/eventlog.c
- t/t0009-dmesg.t
- t/t1008-kvs-eventlog.t
- t/t2230-job-info-lookup.t
- t/t2612-job-shell-pty.t
- t/t3303-system-healthcheck.t
Problem: Several flux commands support a --color option.  However, a short option (-L) is inconsistently supported.  In addition to this inconsistency, the options to --color are optional and may not always work with the short option.
For consistency across flux tools, only support the long --color option.
Update tests that tested the -L short option.
Update manpages and remove refernce to -L short option.
Fixes #5828
> Support optional arg in -L (--color) short option

- src/cmd/job/list.c
- src/modules/job-list/job-list.c
- src/modules/job-list/job-list.h
- src/modules/job-list/list.c
- src/modules/job-list/match.c
- src/modules/job-list/match.h
- src/modules/job-list/test/match.c
- t/t2260-job-list.t
Problem: Job-list constraints are not limited in their size.  A nefarious user could cause a DoS of the job-list service by sending an extremely large constraint request.
Solution: Set a reasonable max on constraint sizes.  The maximum length a constraint array can be is 256 elements and the maximum recursive depth (via and/or/not operators) is set to 16.
Add unit tests.
Fixes #5669
----
This was something I came up with ... good idea?  bad idea?  the limit sizes ok?
> job-list: limit constraint comparisons to avoid DoS

- doc/man7/flux-environment.rst
- doc/test/spell.en.pws
- src/cmd/flux-exec.c
- t/t0005-exec.t
Problem: it is tricky to run systemd commands using flux-exec(1) on a system instance configured with exec.service=sdexec because the user systemd environment is not set up.
If not already set, set DBUS_SESSION_BUS_ADDRESS so that systemd --user commands access the dbus instance running as the flux user.
Thus commands like this can work (after sudo to root or flux):
```
flux exec -r 3 systemctl --user list-units --type=service
flux exec -r 3 systemctl --user status imp-shell-3-ftSp9MrEVNw.service
```
Fixes #5901.
> flux-exec: set up systemd environment to support sdexec debugging

- doc/man1/flux-config.rst
- doc/test/spell.en.pws
- src/cmd/builtin/config.c
- src/cmd/flux-R.c
- t/t0026-flux-R.t
- t/t2806-config-cmd.t
Problem: as noted in #5898, it may be useful for a sys admin to be able to probe the installed flux configuration before launching flux.
Add two new capabilities:
-  add  `flux config get --config-path=PATH` option (with special PATH names of `system`, `security`, and `imp`)
- enhance `flux R parse-config PATH` to follow `resource.path` if defined
> add options for offline config file parsing

- src/cmd/flux-perilog-run.py
- t/Makefile.am
- t/job-manager/plugins/offline.c
- t/t2274-manager-perilog.t
Recently, jobs were consistently failing with an exception `job prolog failed with exit code=1` without any other details in the logs or job eventlog. It turned out that the scheduler was handing out offline nodes, and the prolog fails in this case, but due to the use of an incorrect log level, the log message for this condition was suppressed. Also, users were confused by the lack of detail in the job exception.
This PR improves prolog handling of offline ranks by
- using the correct log level for the warning "prolog: rank[s] XX offline. Skipping."
- raising a non-fatal job exception with this same detail (that some broker ranks were offline) so that a user is notified in the job eventlog of the reason the prolog will fail.
`flux perilog-run` can't raise the fatal exception itself, since …
> job-manager: improve handling of offline ranks in job prolog

- src/modules/cron/cron.c
Problem: If a sync event is configured, it can lead to cron jobs being added to the deferred list.  If the sync event is later changed or disabled, it is possible jobs on the deferred list may never be executed again.
Handle this race:
- if the sync event is changed, restart the message handler if there are any jobs currently on the deferred list.
- if the sync event is disabled, run any jobs currently on the deferred list.
----
I didn't add any tests b/c this is racy and would require some instrumentation.  Or alternately, could do something nuts like have a cron interval of .1 seconds and regularly change event/disable event for a few seconds, and make sure cron job is still running afterwards?  I guess it could be a LONG_TEST.
> cron: fix race if sync event changed or disabled

- src/broker/broker.c
- src/broker/overlay.c
- src/broker/runat.c
- src/common/libeventlog/eventlog.c
- src/common/libpmi/simple_server.c
- src/common/librlist/rlist.c
- src/common/librouter/msg_hash.c
- src/common/libsubprocess/command.c
- src/modules/job-list/idsync.c
- src/modules/kvs/cache.c
- src/modules/sched-simple/sched.c
- src/shell/events.c
- src/shell/plugstack.c
- t/Makefile.am
This fixes assorted source hygiene issues, nothing major.
> assorted minor source cleanup

- src/modules/job-manager/plugins/perilog.c
Problem: The job-manager perilog plugin manually sets the cwd of any subprocesses run for a prolog or epilog, but this is unnecessary and furthermore forces a fallback to the fork/exec method instead of posix_spawn(3) which is more performant.
Remove the use of `flux_cmd_setcwd()` in the perilog plugin.
Fixes #5921
> job-manager: perilog: do not set working directory on subprocesses

- doc/guide/admin.rst
- doc/test/spell.en.pws
Problem: core dump note does not suggest systemd override.conf if not using coredumpctl(1).
Add an example.
> doc: enhance core dump instructions in admin guide

- src/common/libflux/composite_future.c
- src/common/libflux/test/composite_future.c
This PR fixes the problem with chained futures described in #5923: if a `next` future in a chain is destroyed before the `prev` future, then a segfault due to use-after-free could occur later if `prev` is eventually fulfilled since this references next.
The case where this is likely to occur is when `flux_future_then(3)` is called with a timeout on a `next` future, since the timeout will fulfill `next` with an error without even touching the `prev` future.
The fix is not exactly elegant. A reference to the `chained_future` object is placed in  the `next` future's `aux` list, so that when it is destroyed it can (optionally) destroy `prev`. However, this needs to be avoided in the common case where `prev` is destroyed before `next`, so an aux_item destructor is _also_ placed in `prev` to …
> fix possible use-after-free in chained future implementation

- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/overlay.c
- t/t0013-config-file.t
Problem: The default tbon.topo is kary:2, which is almost certainly not optimal for any case.
Let's try kary:32.
> change default tbon.topo to kary:32

- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/shutdown.c
- src/broker/state_machine.c
- t/t0025-broker-state-machine.t
Problem: as noted in #5881, we observe many "transitioning to LOST due to EHOSTUNREACH" log messages during shutdown of a large system with a flat TBON.
This is due to a deficiency in the shutdown handshake.  Once a tbon child completes rc3, it sends an offline status control message to the parent and immediately disconnects.  The parent processes the status message asynchronously and may attempt to send messages to the child (for example routine broadcasts) after the child has closed the connection, which triggers this log message.
Improve the shutdown handshake by adding an RPC that the child must wait for before disconnecting.
In addition, make the message a little more user friendy so if it does appear it is more clear to users what is going on.
> broker: avoid LOST due to EHOSTUNREACH messages during shutdown

- scripts/install-deps-deb.sh
- scripts/install-deps-rpm.sh
- src/test/docker/bookworm/Dockerfile
- src/test/docker/fedora39/Dockerfile
- src/test/docker/focal/Dockerfile
- src/test/docker/jammy/Dockerfile
problem: Apparently bookworm, jammy, focal, and new fedoras don't install /usr/bin/time by default.  I ran into this trying to include time output in a test.
Evidently the "time" builtin in bash is suppressed inside the scope of an eval like we use in sharness, either way this seems less annoying than having to avoid it.
solution: install it, added to each of the docker files as well as the install-deps-*.sh files.
> deps/docker: add 'time' as a dependency for tests

- src/modules/job-exec/bulk-exec.c
Problem: The exit_batch_timer is not destroyed in bulk_exec_destroy(), which could result in the timer firing on a bulk_exec structure which has already been destroyed. Testing shows that this is a rare, but reproducible condition when bulk_exec_imp_kill() is used. This is possibly because destruction of the bulk_exec structure is tied to that of the future returned from this function. This allows the caller to destroy the future and the bulk_exec object before the timer watcher is cleared, resulting in use-after-free and memory corruption.
Destroy the exit_batch_timer watcher in bulk_exec_destroy().
> job-exec: fix potential use-after-free in bulk-exec implementation

- src/test/docker/docker-run-checks.sh
problem: docker-run-checks.sh currently assumes that mounting $HOME to /home/$USER will match the outer system.  Sometimes that is not the case.  Example, my lima-managed vm uses `/home/$USER.linux` as the home directory for the vm user, which causes strange errors because of the mismatch.
solution: map $HOME to $HOME
Assuming this works here, I'll apply this to flux-sched as well.
> docker-run-checks: ensure we match user's home

- doc/man1/flux-job.rst
- src/cmd/job/taskmap.c
- t/t2616-job-shell-taskmap.t
This PR adds a `--to=hosts` option to `flux job taskmap`, which prints the hostname: tasks mapping for a job when given a jobid. E.g. for a 4 node 16 task "cyclic" job:
```
$ src/cmd/flux job taskmap --to=hosts $(flux job last)
fluke87: 0,4,8,12
fluke88: 1,5,9,13
fluke89: 2,6,10,14
fluke90: 3,7,11,15
```
> flux-job: add `flux job taskmap --to=hosts`

- .typos.toml
- src/modules/resource/Makefile.am
- src/modules/resource/drain.c
- src/modules/resource/resource.c
- src/modules/resource/upgrade.c
- src/modules/resource/upgrade.h
- t/Makefile.am
- t/resource/resource.eventlog.thing2
- t/t2311-resource-drain.t
- t/t2353-resource-eventlog.t
Problem: under-specified resource.eventlog drain/undrain events, copious online/offline events, and bloated resource-init events are allowed to remain in resource.eventlog after recent updates that address these issues for new events.
If the resource.eventlog contains a resource-init event, rewrite the eventlog in the KVS with an upgraded version:
- remove resource-init, online, offline events
- add nodelist to under-specified drain/undrain events
Fixes #5931
> resource: upgrade KVS resource.eventlog if needed

- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/exec_config.h
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/testexec.c
- src/modules/job-list/job-list.c
- t/t2403-job-exec-conf.t
- t/t2404-job-exec-multiuser.t
Per comments in #5913, did a bunch of cleanup/re-work in prep of job-exec config reload (#5900).  
- job-exec module stats that export current config values (did it in a "impl.bulk-exec.config." object).
- modernize tests in t2403-job-exec-conf.t
- update to use module stats to determine conf
- add missing coverage of other job-exec confs
> job-exec: support module stats to see current bulk-exec configuration

- src/common/librlist/rhwloc.c
As discussed in #5934, this PR removes the lines from librlist that are currently filtering out L2/L3/etc caches in the hwloc topology loaded by flux, thus making this information unavailable to components and processes that use this topology, since it is shared from parent to child instance and shell to shell plugin.
> do not filter caches when loading hwloc topology

- doc/man1/common/job-shell-options.rst
- doc/man1/flux-shell.rst
- src/shell/hwloc.c
- t/t2619-job-shell-hwloc.t
This PR adds the `hwloc.restrict` job shell option as described in #5934, along with a trivial test and docs.
> shell: add `hwloc.restrict` option to restrict `HWLOC_XMLFILE` to assigned resources

- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/test/fbuf_watcher.c
Problem: Profiling shows that a significant amount of time can be spent in the prep/check of remote subprocess output. This is even in the case when the output buffer is empty.
Enable the remote output prep/check only when the buffer is non-empty.
----
Side note, after trying and flailing on the "input" side of this, I realized that a bunch of code in `libsubprocess`'s remote code simply assumes the prep/check for input is always running.  So that work requires more thought.  Posting this so we can atleast get this in for the next release if I can't figure out the input side by then.
> libsubprocess: reduce remote output prep/check

- src/common/libsubprocess/server.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/exec.c
While testing some other things it was apparent that job-exec is a contributor to nuisance logging. Especially bad was some libsubprocess server logging when data can't be written to processes that have since disappeared due to being killed.
This PR cleans up some of that useless logging. (and fixes one place where it was already meant to be cleaned up)
> job-exec: silence some nuisance logging

- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/exec_config.h
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- src/modules/job-exec/testexec.c
- t/t2403-job-exec-conf.t
- t/t2410-sdexec-memlimit.t
Problem: job-exec requires the job-exec module to be reloaded to read changes to configuration.  This is inconvenient and can affect running jobs.
Support reading/loading configuration changes via the config-reload message callback.  If anything is configured on the command line during module load time, that configuration still override's anything in broker configuration.
----
only minor thing is I called the exec_implementation function "reload" instead of "config_reload", just b/c I didn't want one function to be much longer than any other function and muck all the pretty alignment that already exists.  "reload" could be ambiguous, like this callback is for when the module is reloaded?? 
(edit: don't have docker on system I'm on today, so some tests are not tested ... we'll see if they …
> job-exec: support config reload

- src/modules/job-exec/job-exec.c
- t/t2403-job-exec-conf.t
- t/t2404-job-exec-multiuser.t
Problem: All job-exec stats are listed under a key "impl", which is excessive.
Remove the top level key "impl".  Now the top level keys are simply the names of the exec implementations, i.e. "bulk-exec".
Update all tests accordingly.
> job-exec: remove layer of stats indirection

- src/modules/job-list/job_state.c
- src/modules/job-manager/journal.c
Problem: job-list logs "update_jobspec: job xxx received jobspec update before jobspec" when flux-accounting sets a default bank.
The job manager journal attached the jobspec to the validate event, so it is not available when jobspec-update events are sent before validate.
Send it with submit instead of validate.  Adjust job-list to handle it with the submit event.
Fixes #5951
> job-manager: journal jobspec with submit event

- src/cmd/job/mpir.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/channel.c
- src/common/libsubprocess/test/stdio.c
- src/common/libsubprocess/test/subprocess.c
- src/modules/cron/task.c
- src/shell/output.c
- src/shell/pmi/pmi.c
- t/rexec/rexec_count_stdout.c
and some comment additions and an extra test.
> libsubprocess: remove unused len parameter from flux_subprocess_read()

- src/modules/job-manager/alloc.c
- src/modules/job-manager/job.c
- src/modules/job-manager/job.h
While trying to find the cause of issue #5964, I finally got fed up and did some cleanup in alloc.c.
Nothing too risky here.
I didn't get to the bottom of the actual issue but figured this cleanup could stand alone.
> job-manager: misc cleanup in scheduler interface

- src/common/libsubprocess/subprocess.c
Problem: A recent crash showed that it is possible for a process to not be in the EXITED state when
subprocess_check_completed() is called.  See issue
Solution: To temporarily remove the possibility for broker crashes, demote the assert to an error message.
> libsubprocess: demote assert to warning

- src/cmd/job/attach.c
- t/t2500-job-attach.t
This PR just closes an old issue since the fix was simple enough.
> flux-job: improve EPERM error message

- src/broker/runat.c
- src/cmd/flux-exec.c
- src/cmd/flux-start.c
- src/cmd/job/mpir.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/channel.c
- src/common/libsubprocess/test/iochan.c
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/remote.c
- src/common/libsubprocess/test/stdio.c
- src/common/libsubprocess/test/subprocess.c
- src/modules/cron/task.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-ingest/worker.c
- src/modules/job-manager/plugins/perilog.c
- src/shell/output.c
- src/shell/pmi/pmi.c
- t/rexec/rexec_count_stdout.c
- t/rexec/rexec_getline.c
Problem: The flux_subprocess_read() family of functions return a pointer to a buffer on success and length of buffer in an
optional parameter.
This API style isn't the most intuitive as it is quite different than the read(2) system call.  Most notably when EOF
is reached on a read stream you have to check if the buffer pointer is non-NULL and the length returned from an optional parameter is 0.
Solution:  Update the read family of functions to return the length from the function and the buffer pointer in an optional parameter.
Update all callers accordingly.
---
side notes
notes, b/c so much code already used `int`s and `char *`s for these functions, I elected to keep `int` vs `ssize_t` and `char *` vs `void *`.
Relatively simple refactoring ... sorry but the review will be a little …
> libsubprocess: improve read API

- src/modules/job-manager/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/plugins/alloc-bypass.c
- t/t2273-job-alloc-bypass.t
This fixes #5797 by omitting alloc-bypass jobs from the "hello" phase of the scheduler handshake.
It looks like `set-flags` is already used to ensure `job->alloc_bypass` survives a flux restsart.
I did notice that my flux restart test hangs without FLUX_DISABLE_JOB_CLEANUP set, as the alloc-bypass job gets stuck in CLEANUP, so that needs following up.   Will open a separate issue.
> don't free alloc-bypass resources when scheduler reloads

- doc/man1/flux-jobs.rst
Problem: The flux-jobs(1) manpage did not get updated when the PRIORITY state was introduced.
Updated documentation to note the PRIORITY job state and the "P" abbreviation for it.
Fixes #5985
----
and one extra cleanup in the area
> doc: add PRIORITY state to flux-jobs(1)

- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/remote.c
- src/common/libsubprocess/test/stdio.c
- src/common/libsubprocess/test/subprocess.c
- src/common/libsubprocess/test/test_echo.c
Splicing out this collection of minor things from my bigger PR
> libsubprocess: minor cleanup

- doc/man1/flux-dump.rst
- etc/rc3
- src/cmd/builtin/dump.c
- t/t2807-dump-cmd.t
This adds an option to allow a KVS dump to continue even when there are keys referencing nonexistent blobrefs.   This would have been handy last night when el cap ran out of disk space and we had to kill the rank 0 broker.  This left some dangling keys which prevented flux from starting.  Then after we got rid of those, we found some more in less critical places that we had to run down by iteratively running `flux dump`  and removing one key until it ran clean.
This option allows all the bad keys to be found in one go.
This PR also adds the option to the dump called from rc3 so that any bad keys that find their way into the KVS are simply not included on the next restart.
> flux-dump: add --ignore-failed-read option

- src/shell/output.c
- t/t2606-job-shell-output-redirection.t
This PR fixes #5992 by moving the check for truncated data to just before the output plugin shuts down.
> shell: fix repeated output truncation warning messages

- src/broker/state_machine.c
Problem: many "quorum-full: ignored in shutdown" messages were observed during shutdown of Flux on a large system with a flat TBON.
The quorum-full broker event could be posted in any state but RUN. Restrict quorum-full posting to the QUORUM state.
Fixes #5983
> broker: don't post quorum-full in non-QUORUM state

- src/broker/runat.c
- src/broker/state_machine.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/test/subprocess.c
This addresses the log messages noted in #5995, which are more confusing than helpful.
> suppress confusing log messages when broker is signaled during shutdown

- doc/man1/flux-jobs.rst
Problem: The field name for `status_emoji` is incorrect due to a cut and paste error.
Correct the field name for `status_emoji`.
Fixes #5997
> doc: fix typo in flux-jobs(1)

- src/shell/input/file.c
- src/shell/input/kvs.c
- src/shell/input/service.c
- src/shell/input/util.c
- src/shell/input/util.h
- t/t2607-job-shell-input.t
This PR modifies the shell `input.file` plugin to bypass the KVS when an input file is specified, rather than reading the file into the KVS input eventlog, i.e. this makes the behavior match documentation. If input is redirected from a file, an RFC 24 redirect event is posted in place of any data.
This also solves the problem of stdin flow control when file input is used since each task now has its input redirected from the file instead of shuttling through the KVS. (flow control is still an issue with interactive input though, so this doesn't fully solve issue #2459)
It would also be trivial now to support a mustache template for a stdin FILE, e.g. to support input per task or node, etc., however, that work is left for the future.
> bypass KVS for job stdin with `--input=FILE`

- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- doc/test/spell.en.pws
- src/broker/overlay.c
- t/t0013-config-file.t
This adds two new TOML/broker attrs:
**tbon.child_rcvhwm**
Allows the child receive buffer to be capped at some number of messages per peer.  It is currently unlimited.  This might help keep RSS growth in check on the leader broker of a big system
**tbon.zmq_io_threads**
Lets the number of I/O threads spawned by zeromq be increased from the default of 1.  Only affects the leader node.
I have only tested this on my small cluster with
```toml
[tbon]
zmq_io_threads = 2
child_rcvhwm = 5
```
I confirmed that rank 0 has started two I/O threads while other ranks started one, and that a "flood ping" (+) from rank 1 to rank 0 causes the RSS of rank 1 to grow not 0.
_______
(+) `flux ping -p 8k -i 0 -c 100000 0`
> broker: add tunable parameters for extreme fanout configurations

- src/modules/job-manager/plugins/validate-duration.c
- src/modules/job-manager/update.c
This PR fixes a couple places in the job manager where an expiration update is logged even though the expiration didn't change.
Fixes #5973
> job-manager: don't log expiration update when unnecessary

- doc/man5/flux-config-exec.rst
- src/modules/job-exec/job-exec.c
- t/t2403-job-exec-conf.t
This PR was split off #6014 and mainly adds new `kill-signal` and `term-signal` module parameters as for testing as suggested by @garlick.
Since this was a good chunk of work with its own tests, documentation updates, etc, it seemed reasonable to propose as a separate PR.
> job-exec: add `kill-signal` and `term-signal` module parameters

- src/common/libsubprocess/Makefile.am
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/remote.c
- src/common/libsubprocess/test/subprocess.c
- src/modules/job-exec/bulk-exec.c
- src/modules/job-exec/job-exec.c
Per discussion in #5919, some notes
- built on top of my cleanups in #5974
- should the use of this flag in  job-exec be a different PR?
- in job-exec subprocess flags are passed in via the API to bulk-exec, so it felt wrong to just assume that flag is always set.  So that led to adding a new `flux_subprocess_get_flags()` function and calling an appropriate "read" function depending on flags.  This could be done differently of course, perhaps the flags aren't passed in from the API and are internalized within `bulk-exec`?
- haven't tested to ensure that the performance profile changes as expected, dunno if we have a simple reproducer laying around? Edit: I did now, see notes in #5919
> libsubprocess: support FLUX_SUBPROCESS_FLAGS_LOCAL_UNBUF

- src/modules/job-exec/job-exec.c
- t/t2403-job-exec-conf.t
Problem: cmdline options to the job-exec module should always override configuration settings, but this is not the case for kill-timeout, term-signal, and kill-signal when the configuration is reloaded.
Ensure that cmdline options for kill-timeout, term-signal, and kill-signal always override configuration settings.
----
This was an oversight from commit in #5975
> job-exec: cmdline options for signals should override config settings

- src/common/libsdexec/channel.c
- t/t2410-sdexec-memlimit.t
Problem: sdexec sends two EOF notifications for each channel, which causes libsubprocess to get confused and not signal subprocess completion in UNBUF mode.
The sdexec channel class stops its own watcher after sending EOF, but the sdexec module restarts the watcher during completion to ensure it can send EOF in an error case where it was not started.  This results in two EOF notifications.
Add an `eof_delivered` flag to the channel and use it to ensure that only one eof is sent.
Also, adjust the output of `t2410-sdexec-memlimit.t` (which was hanging) to give more of an indication of what is going on, since it is pretty terse otherwise.
> sdexec: avoid double EOF notification

- src/common/libsubprocess/remote.c
Problem: A recent fix in the sdexec module corrected a double EOF, which caused the client side to hang when the LOCAL_UNBUF flag was used. The client side hang was due to incorrect counting of closed channels.
Solution: Properly flag that an EOF has been sent to the caller when the LOCAL_UNBUF flag is used, so that multiple EOFs are not reported to users.
> libsubprocess: protect against double EOF

- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- t/t2406-job-exec-cleanup.t
Currently, the job-exec module only attempts to signal job tasks (via `flux_job_kill(3)`) once, waits for a timeout (default 25s), then attempts to signal the job shell itself once (via `flux_subprocess_kill(3)`). On a large system, we've seen jobs stuck permanently in CLEANUP after termination because one or more job shells are still running after the signal is sent to the job shell.
This PR adds retries of both `flux_job_kill(3)` (during the initial timeout) and `flux_subprocess_kill(3)` while any job shells are still running. This should cleanup those cases where the initial attempts may fail due to the possible raciness inherent in these interfaces.
The retry is added to the `flux_job_kill(3)` because we do want to avoid just killing the job shell if possible, since this could leave …
> job-exec: retry kill of job tasks and job shell during job termination

- src/broker/log.c
Problem: The timezone designation is not included with broker log messages, making determination of when an error message in a logfile occurred slightly ambiguous.
Add the timezone abbreviation to the timestamp.
Fixes #6015
> broker: add timezone abbrev to log message timestamps

- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/remote.c
- t/t2409-sdexec.t
Problem: Profiling shows that a significant amount of time can be spent in the prep/check of remote subprocess input. This is even in the case when the input buffer is empty.
Enable the remote input prep/check only when the buffer is non-empty.
> libsubprocess: reduce remote input prep/check

- src/common/librlist/rlist.c
- t/t0026-flux-R.t
There's an oversight in librlist parsing of `resource.config` entries, and a non-array `properties` value is silently ignored.
Validate that any `properties` entry is a JSON array and generate an error if not.
> librlist: ensure `properties` is an array when parsing `resource.config` entries

- src/cmd/builtin/overlay.c
- t/t3303-system-healthcheck.t
Problem: `flux overlay status` makes some unnecessary RPCs that slow things way down on el cap.  Specifically, the `overlay.health` RPC is made to leaf nodes despite the fact that the parent already knows the status of its children.
Eliminating that gets us about a 4x speedup on el cap.
before
```
[garlick@elcap1:cmd]$ time /usr/bin/flux overlay status >/dev/null
real	1m28.377s
user	0m56.726s
sys	0m0.905s
```
After
```
[garlick@elcap1:cmd]$ time ./flux overlay status >/dev/null
real	0m19.892s
user	0m18.275s
sys	0m0.209s
```
> speed up flux overlay status on a big system

- src/broker/overlay.c
- src/broker/state_machine.c
- src/broker/topology.h
- src/modules/job-exec/exec.c
- t/issues/t3906-job-exec-exception.sh
Problem: as noted in  #6021, the log messages like this one are confusing to users:
```
broker[0]: picl2 (rank 2) has disconnected unexpectedly. Marking it LOST.
```
Moreover, when the TBON is not flat, only the subtree root is called out.  The other nodes in the subtree are also lost but not called out.
For your consideration: this PR
- demotes the LOST messages to LOG_DEBUG
-  adds a new LOG_ERR message that tracks brokers leaving the `broker.online` group during broker RUN and CLEANUP states. 
Example, if I kill -9 rank 1 of a kary:2 8 node instance, I get the following on stderr:
```
$ flux start -s8 -o,-Stbon.topo=kary:2
Jun 04 09:21:45.016921 PDT broker.err[0]: dead to Flux: system76-pc,system76-pc,system76-pc,system76-pc (rank 1,3-4,7)
```
In a system instance, if I power off rank …
> improve broker messages when nodes die

- src/broker/overlay.c
Problem: when the upstream broker is offline, it takes 60s for systemctl stop flux to complete.
The `overlay.goodbye` RPC has a 60s timeout.  Just skip it if the broker never made contact with its parent.
Fixes #5991
This seems to resolve the issue on my test system.
> broker: avoid 60s delay on follower shutdown

- src/common/libsdexec/channel.c
- src/common/libsdexec/test/channel.c
Problem: the sdexec module can segfault when a subprocess unit is destroyed as a result of an output channel closing.
The channel output callback destroys the channel, then the channel code continues referencing it after the callback.  Add a reference count that is held over the callback and the duration of the function to prevent the segfault.
Fixes #6036
> sdexec: fix use after free during teardown

- src/common/libsubprocess/client.c
- src/common/libsubprocess/client.h
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/iostress.c
- src/modules/sdexec/sdexec.c
This is an attempt to implement the subprocess protocol change proposed in flux-framework/rfc#416, which allows a write request to be sent to a remote subprocess before the pid is received.
Unfortunately what seemed like a straightforward change broke a bunch of tests and I've yet to figure out why!
Wanted to post what I had so far and continue discussing this with @chu11
> libsubprocess: use matchtag instead of pid for flux_subprocess_write()

- src/modules/job-list/job_data.c
- src/modules/job-list/job_data.h
- src/modules/job-list/match.c
- src/modules/job-list/match.h
- src/modules/job-list/state_match.c
- src/modules/job-list/test/match.c
- src/modules/job-list/test/state_match.c
- t/t2260-job-list.t
TSIA.
Maybe the only interesting side note is that until we solve #5367 (which should probably follow this one up) we don't yet have a friendly user interface for this.  The tests send constraints objects straight to the `job-list` module.
> job-list: support "hostlist" constraint to allow jobs to be filtered by nodes

- .github/workflows/main.yml
- src/test/docker/docker-run-systest.sh
- t/t2410-sdexec-memlimit.t
Running our `system` test container under `docker` is now failing in GitHub actions on the 20.04 actions runner. We already knew that `docker` could no longer run the `system` container (which has to have the ability to start `systemd` as PID 1) on ubuntu 22.04, so it was probably inevitable that at some point this was going to break.
As an experiment, I updated the `system` container to run via `podman` in the `docker-run-systest.sh` script, because `podman` officially supports systemd via a `--systemd` option, and it seems to work. Since ubuntu 22.04 has the correct version of `podman`, this PR adds those changes and updates the github runners for the main workflow to `ubuntu-latest`.
Some other fallout was fixed along the way (notes in specific commit messages and comments.)
> ci: convert `system` test container to run under `podman` for better `systemd` support

- src/cmd/Makefile.am
- src/cmd/flux-python
problem: using `flux python` on minimal systems, say alpine or other minimal systems that do not provide an `env -S`, is currently non-trivial. Since the shebang only supports a single argument after the command, there's no way to search the path for flux to run flux python
solution: add a `flux-python` script, which is installed to the same bin path as `flux` itself, so that `#!/usr/bin/env flux-python` can be used as a shebang
ping @tgamblin
> flux-python: add posix-compatible shebang wrapper

- src/common/libidset/idset.c
Problem: idset_intersect(3) and idset_has_intersection(3) always iterate one idset fully to determine the result, but the code doesn't check to ensure it is iterating the smaller of the two provided idsets. This could lead to wasted cycles, especially when the idset being iterated has many more entries than the other argument.
If both idsets do not have the IDSET_FLAG_COUNT_LAZY flag set, then swap arguments in both idset_intersect(3) and idset_has_intersection(3) such that the idset with the smaller number of entries is iterated.
Before this change, to intersect the idsets 1-10000 and 1-100 took an average of 4.5ms, with this change, that drops to .02 ms.
> libidset: improve efficiency of idset intersection

- src/modules/job-list/job_data.c
- src/modules/job-list/job_data.h
- src/modules/job-list/match.c
- src/modules/job-list/state_match.c
- src/modules/job-list/test/match.c
- t/t2260-job-list.t
This PR adds a `ranks` constraint operator to job-list to allow restricting output to jobs that were assigned one of a set of ranks. This is useful in testing or to eventually make queries not dependent on hostname.
There's already a pending PR to update RFC 43.
Fixes #6046
> job-list: add support for `ranks` constraint

- doc/Makefile.am
- doc/man3/flux_shell_get_hostlist.rst
- doc/manpages.py
- src/shell/doom.c
- src/shell/info.h
- src/shell/shell.c
- src/shell/shell.h
- src/shell/taskmap/hostfile.c
This PR augments the error messages, and thus exception notes, from the shell `doom` plugin to include the affected hostname. This prevents users and admins from having to go through several steps to match a prematurely exiting task rank back to a hostname on which it ran.
> shell: enhance exit-timeout and exit-on-error exceptions with hostname

- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/job/Jobspec.py
- t/python/t0010-job.py
Problem: By default the Jobspec setattr() function sets keys to attributes.key.  The default --setattr option in command line options like flux-submit default to set keys to attributes.system.key.  This inconsistency can be confusing.
Default Jobspec setattr() to set keys to "attributes.system.key". Adjust command line --setattr option accordingly for tweak.
Fixes #6042
----
Just throwing up this WIP in case there are any initial objections
- TODO - unit tests
- TODO - update callers to specify "foo" instead of "system.foo"?  maybe unnecessary to do this, will think about it
> python: Update default Jobspec setattr() path

- src/modules/job-exec/exec.c
- t/valgrind/workload.d/job-multinode
Problem: The job-exec barrier protocol does a streq() string comparison on the data returned from a subprocess's stdout.  When subprocesses began to use the new UNBUF flag, this data became non-NUL terminated.  The streq() therefore became unsafe to use.
Update code to check data length and use strncmp() instead of streq().
Fixes #6057
> job-exec: do not streq() an unbuffered string

- etc/completions/flux.pre
Problem: The bash tab completions are currently missing a couple things:
- the flux-queue(1) completions are missing the --queue option for a couple subcommands
- the flux-python(1) command doesn't have any completions, so you can't complete the path of a script to pass to `flux python` with tab.
Fix these issues.
> etc: add some missing functionality to bash completions

- src/modules/job-manager/prioritize.c
I think this might take the cake for me for heisenbug of the week.  Somehow all of this worked correctly until after I fixed the ordering and async issues in qmanager.  My guess is there's a race condition, maybe it worked because in other cases job-manager received the update event and thus updated it sooner? Not sure, I have yet to find where it actually updates the job structure.  Either way, this is what caused the catastrophic CI failure after I fixed the reconsider spinning issue over in flux-framework/flux-sched#1227. Also no clue how this passed all the tests before, the `sched.prioritize` messages consistently carry the wrong value. 🤷‍♂️ 
problem: On receiving a message from `flux job urgency` the job-manager prioritize code updates the value of job->priority after sending the …
> job-manager/prioritize: update priority before sending

- t/valgrind/valgrind.supp
Problem: hwloc 2.10 has some memleaks that show up in valgrind tests.
Add a valgrind suppression for this memleak.
Fixes #5705
> t: suppress hwloc 2.10 memleaks

- src/common/libsubprocess/bulk-exec.c
- src/common/libsubprocess/bulk-exec.h
- src/modules/job-exec/exec.c
This PR fixes the `active_shells` count in the job-exec per-job module stats and also adds an `active_ranks` member with an idset of ranks on which job shells are still active. This can aid in finding an unkillable shell in large jobs.
> job-exec: add `active_ranks` and fix `active_shells` count in per-job stats

- src/common/libsdexec/channel.c
- src/common/libsdexec/channel.h
- src/modules/sdexec/sdexec.c
- t/t2409-sdexec.t
Problem: sdexec internal state is opaque
Add support for the `sdexec.stats-get` RPC so 'flux module stats sdexec' returns something useful when debugging stuck jobs.
Example output with one job running:
```json
{
"procs": {
"imp-shell-0-f5XkPPeaUuu.service": {
"state": "active.running",
"pid": 922759,
"in": {
"local_fd": 139,
"remote_fd": -1
},
"out": {
"local_fd": 141,
"remote_fd": -1,
"buf_used": 0,
"buf_free": 4194304,
"eof": false
},
"err": {
"local_fd": 26,
"remote_fd": -1,
"buf_used": 0,
"buf_free": 4194304,
"eof": false
}
}
}
}
```
> sdexec: add stats-get RPC handler

- src/cmd/job/attach.c
Problem: The `flux job attach` status line reference counting for prolog-start events doesn't work because job_event_notify_string(), which is where the refcount is done, is only called when the status line is active -- that is after 2s by default. The first prolog-start events could have been posted during this time, and the increment of the prolog-finish refcount is missed.
Always call job_event_notify_string() in attach_notify() to ensure the refcounting is correct.
> flux-job: fix prolog refcount in attach status message

- doc/man7/flux-environment.rst
- doc/test/spell.en.pws
- src/broker/module.c
- src/common/libflux/Makefile.am
- src/common/libflux/handle.c
- src/common/libflux/plugin.c
- src/common/libflux/plugin_private.h
Add an environment variable to control whether we actually apply the RTLD_DEEPBIND flag when calling dlopen.  More details in the commit message, but this makes it possible to run flux with an alternate allocator using LD_PRELOAD or certain other things that make heap tracing and certain other debugging and tracing tasks much easier.
> add environment variable to avoid `RTLD_DEEPBIND` when loading modules

- src/modules/job-manager/alloc.c
- t/t2204-job-manager-limited.t
- t/t2205-job-manager-unlimited.t
Problem: we observed underflow in the `flux queue status -v` pending alloc count in #6059 with fluxion.
I was unable to reproduce the underflow.  This PR adds tests since there were none for the alloc/pending counts, and simplifies the code.
TL;DR In limited mode, the job manager places pending alloc requests in a priority queue so that it can reorder them and cancel/resubmit if priorities change.  In unlimited mode, the list was eschewed for a counter.  It's the counter that went wrong here (somehow).   The cleanup is to always use the priority queue so that we only have one code path to worry about and since list removal is idempotent, the underflow case should be gone.
I can't imagine the priority queue presents a performance issue.  I did run a quick check, running `flux module reload …
> job-manager: improve sched.alloc request tracking

- NEWS.md
This is the start of the v0.64 release notes. As usual, feel free to push updates here as needed.
> NEWS.md: add release notes for v0.64.0

- src/broker/boot_pmi.c
- src/common/libpmi/keyval.c
- src/common/libpmi/test/keyval.c
Problem: mpiexec.hydra from mpich v4.2.0 and reportedly v4.1.1 can no longer launch Flux.
The mpich PMI-1 wire protocol used by hydra started appending `found=TRUE` to values returned by kvs get around v4.1.1. With tentative confirmation from mpich developers that this is likely a bug introduced during pmi refactoring, add a workaround to ignore that protocol element if present.
Fixes #6072
I manually confirmed this fixes the problem with mpich 4.2.0 and included a unit test.
> broker: work around problem with launch by some versions of mpiexec.hydra

- configure.ac
- etc/Makefile.am
- etc/flux-epilog@.service.in
- etc/flux-prolog@.service.in
- src/cmd/Makefile.am
- src/cmd/flux-run-epilog.in
- src/cmd/flux-run-prolog.in
Problem: future housekeeping scripts should be run in a systemd cgroup for reliable termination, logging to the local systemd journal, and debugging using well known systemd tools.
Add a systemd "oneshot" service unit for housekeeping.  The service unit runs a user-provided `housekeeping` script. It is configured so that `systemctl start housekeeping` blocks until the the run is complete and its exit code reflects the exit code of the housekeeping script.
Add a helper script that can be configured as an IMP run command. It runs `systemctl start housekeeping` and traps SIGTERM, which can be sent to enforce a timeout.  Upon receipt of SIGTERM, it stops the unit and exits with a nonzero code.
To enable environment variables such as the FLUX_JOB_ID to be passed into the user-provided …
> systemd: add prolog/epilog service units

- src/bindings/python/flux/util.py
- t/t2350-resource-list.t
This fixes an issue in `flux resource` and other utilities where a line consisting of only whitespace is not skipped, only completely empty lines.
> flux-resource: suppress empty lines in output

- doc/man1/flux-shell.rst
Problem: there's inconsistency in the flux-shell(1) page, where some lua syntax is used and other places use pseudo- code.
Make it consistent by updating "+" to ".." (Lua).
> doc: update flux-shell(1) manpage

- t/python/t0015-job-output.py
Problem: The python/t0015-job-output.py test has an empty environment by default.  This can lead to problems on some distributions.
Set an environment equivalent to the current one to avoid this problem.
Fixes #6088
> t: add job environment to tests

- src/cmd/job/eventlog.c
- t/t2230-job-info-lookup.t
This is a simple one I had laying around for a bit. 
Sometimes it is convenient to "follow" a job eventlog, which can be done with `flux job eventlog -v JOBID clean`, but that isn't quite as user friendly and obvious as a `--follow` option for `flux job eventlog`. This PR makes `flux job eventlog --follow` a synonym for `flux job wait-event -v JOBID clean` via some refactoring. 
Unfortunately, `-f ` is already taken by `--format`, so the short option for follow becomes `-F`.
> flux-job: add `-F, --follow` option to `flux job eventlog`

- src/common/libsubprocess/bulk-exec.h
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- t/t2406-job-exec-cleanup.t
This PR modifies the job-exec module to add a max number of retries when signaling the job shell. When this count is exceeded, the remaining active ranks are drained and the tasks are forced to complete so that the job can proceed to CLEANUP.
Fixes #6097
> drain nodes with unkillable tasks after configurable retries

- src/cmd/flux-start.c
- t/t3203-instance-recovery.t
Problem: `flux-start` ignores `--recovery` if `--test-size` is present.
Handle the two options together.
> flux-start: accept --recovery with --test-size

- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/modules/resource/acquire.c
- src/modules/resource/reslog.c
- src/modules/resource/reslog.h
- src/modules/resource/status.c
- t/Makefile.am
- t/valgrind/workload.d/resource
Problem: on a large system, frequent use of `flux resource list` or `flux resource status` triggers significant broker CPU consumption.  Commands like `flux top` or `watch flux resource list` are not unreasonable things to do, yet they are costly.
As noted in #6009, we repeatedly calculate the same resource sets, even when they don't change.
Add a simple cache.
> resource: cache resource status information to reduce broker load

- src/modules/job-manager/housekeeping.c
Problem: housekeeping start/stop debug logs are quite chatty, and unnecessary now that we have 'flux housekeeping list'.
Eliminate those logs.  We still log if something goes wrong.
Fixes #6110
> job-manager: silence housekeeping debug logs

- src/broker/modhash.c
- src/broker/module.c
- src/broker/module.h
- src/cmd/flux-module.c
- src/common/libflux/connector_interthread.c
- src/common/libflux/handle.h
- src/common/libflux/msg_deque.c
- src/common/libflux/msg_deque.h
- src/common/libflux/test/interthread.c
- src/common/libflux/test/msg_deque.c
This just adds a count of the number of messages queued for each module to `flux module list` output.  `Send` is the number of messages sent by the broker but not yet read by the module.  `Recv` is the number of messages sent by the module and not yet read by the broker.  So this is from the broker's point of view.
Here I added a check watcher to `barrier.so` to have it continually send KVS lookups to `kvs.so` and immediately discard the future:
```
$ flux module list
Module                   Idle  S Send Recv Service
cron                       15  R    0    0 
resource                    8  R    0    0 
job-exec                    8  R    0    0 
job-list                   12  R    0    0 
sched-simple                8  R    0    0 sched
heartbeat                   0  R    0    0 …
```
> add message queue counts to flux module list

- src/common/libschedutil/alloc.c
- src/modules/job-manager/event.c
- src/modules/job-manager/job-manager.c
- src/modules/job-manager/journal.c
- src/modules/job-manager/journal.h
- t/t2260-job-list.t
Progress towards making flux core more robust in situations like #6114.  Marking WIP because there's still some unexplained RSS growth with "annotation spam" to run down.
> address RSS growth when there are excessive annotation events

- doc/man1/flux-overlay.rst
- src/broker/overlay.c
- src/cmd/builtin/overlay.c
- t/t3303-system-healthcheck.t
- t/t3305-system-rpctrack-up.t
Problem: as discussed in #6109, spelunking logs to find out why a node is offline is tedious, and repeated messages about mismatched versions decrease the log signal to noise ratio.
This adds an error message to `flux overlay status` for each offline node, if available, and eliminates the mismatched version log message.
Example:
```
$ flux overlay disconnect 39
flux-overlay: asking system76-pc (rank 1) to disconnect child system76-pc (rank 39)
$ flux overlay status --down -vvv
0 system76-pc: degraded for 8.38533s (0.377 ms)
├─ 1 system76-pc: degraded for 8.386s (0.328 ms)
│  └─ 39 system76-pc: lost for 8.386s administrative disconnect
```
Marking WIP to get feedback on this approach before proceeding to address test issues.
> add error text to down nodes in flux overlay status

- src/common/libsubprocess/bulk-exec.c
- t/t2406-job-exec-cleanup.t
`bulk_exec_active_ranks()` is supposed to report the ids of ranks on which bulk-exec subprocesses are still active, but it doesn't account for those that have exited. This causes the `active_ranks` key of `flux module stats job-exec` per-job stats to be incorrect (it always reports all ranks).
Fix `bulk_exec_active_ranks()` and add a test.
> job-exec: fix per-job `active_ranks` module stats

- doc/man5/flux-config-exec.rst
- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/exec_config.h
- src/modules/job-exec/job-exec.c
- src/modules/job-exec/job-exec.h
- t/t2402-job-exec-dummy.t
- t/t2406-job-exec-cleanup.t
- t/t2713-python-cli-bulksubmit.t
This PR adds a timeout for the execution system "start barrier". 
All job shells participate in a barrier after initialization, which includes change of working directory, processing the initrc, etc. After this PR, a timer (default 30m) will be started after the first job shell enters the barrier. If the timer expires before the barrier fully completes, a job exception of the form:
```
exception type="exec" severity=0 userid=1001 note="start barrier timeout waiting for 1/4 nodes (rank 3)
```
will be raised, and the affected rank or ranks drained with the message:
```
job f3oxE4XH start timeout: possible node hang
```
The default barrier timeout can be overridden in jobspec (mainly for testing) via `attributes.system.exec.bulkexec.barrier-timeout`, or via config `exec.barrier-timeout`. …
> job-exec: add timeout for job start barrier

- doc/man1/flux-jobs.rst
- etc/completions/flux.pre
- src/cmd/flux-jobs.py
- src/cmd/flux-pgrep.py
Problem: Use of `-q` as a shorthand for `--queue` is standard in most flux(1) subcommands, such as `flux resource list`, `flux submit`, etc. However, `-q` is not accepted in `flux jobs`, `flux pgrep` and `flux pkill`, which is awkward for users.
Accept `-q` in these commands. Update `flux-jobs(1)` (`flux-pgrep(1)` already claimed `-q` was supported).
Fixes #6130
> cmd: accept `-q` for `--queue` in `flux-jobs`, `pgrep`, and `pkill`

- src/modules/job-exec/exec.c
Problem: A debug fprintf() was inadvertently added to the job-exec module in a recent commit.
Remove the debug fprintf().
> job-exec: remove stray debug fprintf

- .github/workflows/main.yml
- .gitignore
- config/ax_code_coverage.m4
- doc/requirements.txt
- scripts/fetch-and-build-caliper.sh
- scripts/fetch-and-build-catch.sh
- scripts/fetch-and-build-mpich.sh
- scripts/requirements-ci.txt
- scripts/requirements-doc.txt
- src/test/checks_run.sh
- src/test/docker/alpine/Dockerfile
- src/test/docker/bookworm/Dockerfile
- src/test/docker/el9/Dockerfile
- src/test/docker/el9/config.site
- src/test/docker/fedora40/Dockerfile
- src/test/docker/fedora40/config.site
- src/test/docker/jammy/Dockerfile
- src/test/docker/noble/Dockerfile
- src/test/generate-matrix.py
- t/t3000-mpi-basic.t
- t/t3003-mpi-abort.t
This ended up being more churn than I intended, but once I got into it here's where I ended up.
Effects:
* add containers for: ubuntu/noble, fedora/40, el9
* add 
* factor out caliper build into a script, fix build on fedora and noble with 1-line patch
* factor python deps into a requirements file so we don't have to keep copy/pasting it
* change ubuntu and debian dockerfiles to use a single apt update rather than many
* add catch2 all the way at the bottom, this is mainly for sched, but if we can count on it could also be used for core testing since it helps so much with things like actually printing values of unit tests that failed, and making fixtures a whole lot easier to manage, it's also not large
* add env var to fix stupid HWLOC problem where it tries to look for opengl devices by …
> Update containers: el9, fedora40, noble, add arm64 for fedora40, el9, noble

- doc/man1/flux-jobs.rst
- doc/man1/flux-pgrep.rst
- src/bindings/python/flux/job/list.py
- src/bindings/python/flux/job/stats.py
- src/cmd/flux-jobs.py
- src/cmd/flux-pgrep.py
- t/t2800-jobs-cmd.t
This PR adds support for multiple queues in the `-q, --queue=` options of `flux jobs`, `flux pgrep`, and `flux pkill`. As a prereq, the `JobList` and `JobStats` classes are also extended to take multiple queues.
Fixes #6141
> cmd: support multiple queues in `flux jobs`, `pgrep`, and `pkill` `-q, --queue` option

- doc/guide/broker.rst
- doc/index.rst
- doc/man5/flux-config.rst
Updates path to reflect current URL - https://flux-framework.readthedocs.io/projects/flux-core/en/latest/guide/admin.html
> doc: update flux admin guide URL

- src/cmd/builtin/startlog.c
Problem: The enum POST_FLAG_FLUSH was not initialized, therefore it defaults to 0.  This means when a user passes a flag of "0", it ends up being equal to POST_FLAG_FLUSH, leading to undesired behavior.
Initialize POST_FLAG_FLUSH to 1.
> cmd/startlog: initialize enum to non zero

- src/modules/kvs/Makefile.am
- src/modules/kvs/kvs.c
- t/t1000-kvs.t
- t/t1001-kvs-internals.t
- t/t1003-kvs-stress.t
- t/t1004-kvs-namespace.t
- t/t1005-kvs-security.t
- t/t1007-kvs-lookup-watch.t
- t/t1008-kvs-eventlog.t
- t/t1009-kvs-copy.t
- t/t1010-kvs-commit-sync.t
- t/t1011-kvs-checkpoint-period.t
Problem: When the KVS module is unloaded, any unfinished requests (get, put, wait-version, etc.) should get an ENOSYS response.  That is presently not handled.
Solution: Track all requests sent to the kvs module that will not be returned immediately.  Upon module exit, respond to all unfinished requests with ENOSYS.
Fixes #5979
----
note, I noted in #5979 that some other modules might need this fix as well.  Could tack onto this PR as well, but thought we'd deal with just this one first since it specifically has been hit.
> kvs: return ENOSYS on unfinished requests

- .github/workflows/main.yml
- src/test/generate-matrix.py
problem: the no-args fedora40 and version with just prefix arguments are identical for all intents and purposes
solution: remove the no-args version in favor of the one that generates a docker tag
@grondo, sorry for the churn here, but I only realized this was essentially a duplicate when I went to port the changes to sched.  Should be a quick cleanup if you agree.  Sadly will require updating the branch protections again.
Also found that the explicit platform we had on bookworm needs to be on all the multi-arch images, so that's in here now.  Finally dropped the non-ascii el8 builder in favor of bringing the base bookworm/jammy builders back since they were not intentionally dropped.
> matrix: fix matrix generation for arm64 and remove redundant fedora

- src/cmd/flux-resource.py
- t/t2350-resource-list.t
This PR fixes #6166 by appending an empty resource set for each configured or requested queue, instead of a pure empty resource set, which can have no queue. Thus, when node nodes are in a given state, `{queue}` will not be blank, instead there will be a line in output for each queue.
> flux-resource: fix missing queue in `flux resource list` output for states with no nodes

- .github/workflows/main.yml
problem: some of the arm builders, especially the gcc-14 ones, run right up to the timeout of 90 minutes when succeeding, giving spurious failures to update all the container manifests
solution: increase the timeout to 120 minutes
> actions: increase ci timeout from 90 to 120 minutes

- src/modules/resource/exclude.c
- t/t2312-resource-exclude.t
- t/t2315-resource-system.t
While looking at #6136 I noticed that `flux_log_error()` was used unnecessarily for the exclude idset error message.
This PR fixes that.
Also, thought I'd add a test for the specific issue of excluding a hostname that isn't in configuration.
> resource: error message cleanup, add test for invalid exclude

- doc/man1/flux-queue.rst
- etc/completions/flux.pre
- src/bindings/python/flux/util.py
- src/cmd/flux-queue.py
- src/cmd/flux-resource.py
- t/t2241-queue-cmd-list.t
As noted in #6145, it is confusing to users why there are separate `flux-queue(1)` `status` and `list` subcommands.
This PR enhances `flux queue list` to fetch queue status in addition to configuration, and uses this data to support the following new output fields:
* `{submission}` - text representation of submission status: `enabled` or `disabled`
* `{scheduling}` - text representation of scheduling status: `started` or `stopped`
* `{enabled}` - single character boolean for enabled/disabled status (`✔/y` or `✗/n`)
* `{started}` - single character boolean for started/stopped status  (`✔/y` or `✗/n`)
The default output format is now:
```
"?:{queuem:<8.8} "
"{color_enabled}{enabled:>2}{color_off} "
"{color_started}{started:>2}{color_off} "
"{defaults.timelimit!F:>8} " …
```
> enhance `flux queue list` with `-q, --queue=` option and abillity to report queue enabled/started status

- Makefile.am
- src/test/checks_run.sh
- src/test/docker/alpine/Dockerfile
- src/test/generate-matrix.py
problem: we seem to get spurious branch merge mismatch errors in CI, and
ensuring atomicity has not helped
solution: ignore that specific class of errors with `--ignore-errors
mismatch`
> CI: ignore merge errors and increase parallelism

- .github/workflows/main.yml
- src/test/generate-matrix.py
After all the reworks, I just flat can't get flux to build on fedora40 under arm64 emulation in a reasonable amount of time.  No clue why, noble should have the same issue (or worse) and it's done in only a bit over half the time.  So for now I'm throwing in the towel. Will revisit when GHA supports arm runners for OSS.
> docker: Demote fedora40 to x86_64 only

- doc/man1/flux-overlay.rst
- src/broker/overlay.c
- src/cmd/builtin/dmesg.c
- src/cmd/builtin/overlay.c
- src/common/libeventlog/formatter.c
- src/common/libutil/Makefile.am
- src/common/libutil/ansi_color.h
- t/Makefile.am
- t/t3400-overlay-trace.t
Problem: there is no way to observe the message the broker is sending and receving on the overlay network.
Solution: the broker implements a streaming RPC that sends a one line summary of each message sent/received on the overlay network to a tool, `flux overlay trace`.
The format is:
```
[tx|rx] peer-rank message-type topic-string [size]
```
where e=event, >=request, <=response, c=control
I thought I'd post this and ask for feedback on the output format before proceeding (hence WIP).
Here's an example of an instance that running a couple of jobs then shutting down.
```
$ flux overlay trace
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e kvs.namespace-primary-setroot [209]
tx 1 e kvs.namespace-primary-setroot [177]
tx 1 e …
```
> add flux overlay trace

- src/test/generate-matrix.py
The good news: Everything we request be built now builds.
The bad news: Nothing gets tagged because I accidentally triggered a re-use bug in generate-matrix.
problem: re-using the env argument revealed we were not copying the dict but modifying the argument in place, causing multiarch builds to only tag amd64, and matrix generation to fail
solution: copy the env dict in add_build
> matrix: avoid overwriting env elements

- src/test/docker/docker-run-checks.sh
- src/test/docker/docker-run-systest.sh
- t/Makefile.am
- t/t0090-content-enospc.t
This is just a "starting point" for future ENOSPC work.  
- have docker containers create a 1m tmpfs space for testing
- make sure that flux in general can run even if the tmpfs is full
as you see in the comments, the tests disable rc3.  I think the first initial work will be to somehow get rc3 to not hang.
> t: add initial ENOSPC tests

- config/x_ac_zeromq.m4
- configure.ac
- src/broker/overlay.c
Problem:  as noted in #6151, the error handling of `cert_create()` is wrong, and we lack a configure time test that zeromq was built with curve support.
This addresses both of those issues.
Leaving this a WIP for now since this purports to "fix" #6151 but we have not confirmed that this is the whole problem there.
> add configure time check for zeromq crypto and improve broker error handling at cert creation

- src/modules/job-ingest/job-ingest.c
- t/t2201-job-cmd.t
- t/t2812-flux-job-last.t
This PR addresses #6144 by rejecting jobs directly in job-ingest if they are submitted as userid 0 when the instance owner is not also 0.
The reasoning behind handling this directly in job-ingest is simplicity. Also, it does seem like this check should always be in place, since there is not currently a way a root job could execute successfully due to limits/guardrails in the flux-security behavior. Therefore, a validator plugin doesn't really make sense. (IMO)
> reject jobs submitted as user root in a multi-user instance

- .github/workflows/main.yml
- src/test/generate-matrix.py
problem: we have widely varying timouts based on the target and the
usage, and only one timeout value
solution: add timeout-minutes to the matrix and expand it on the
docker-run-checks step.  The downside is that this will not time out if
another step stalls, but which other step would stall?
For now I'm setting the default timeout_minutes to 60, arm64 to 90, and adding back fedora40 at four hours.
> matrix/actions: add per-target timeout-minutes 

- doc/man1/common/job-param-additional.rst
- etc/completions/flux.pre
- src/bindings/python/flux/cli/base.py
- t/t2710-python-cli-submit.t
Now that `bank` and `project` have been [proposed](https://github.com/flux-framework/rfc/pull/420) as official members of canonical jobspec, and since they are supported by job-list, it seems like there are excellent arguments to at least support `-B, --bank=` options in our cli as suggested most recently by @ilumsden.
This PR starts with @ilumsden's draft PR #6157 (thanks Ian!), reworks the commit message to project standards, then adds the docs, testing, and new option to tab completions.
I didn't add `--project` here, even though it is also proposed as canonical in the rfc PR above. I like the idea of `-Sproject=NAME` for rarer cases such as this, though I'm not opposed to `--project` if people think that's a good idea.
For now, this seems like a good and simple ui improvement.
> add `-B, --bank=` option to submission commands

- src/modules/job-manager/alloc.c
- src/modules/job-manager/alloc.h
- src/modules/job-manager/housekeeping.c
- src/modules/sched-simple/sched.c
- t/t2226-housekeeping.t
This changes the RFC 27 `sched.free` payload to include a `final` flag, as proposed in flux-framework/rfc#421.
When present and true, the scheduler may assume that the last `sched.free` request has been received for a job's resource allocation, and could start an optional sanity check that no resources remain allocated to that job.  If missing, it's probably wise to not assume anything  at this point, for backwards compatibility with earlier flux core releases.
@trws is this what you were thinking?
> job-manager: add final flag to sched.free

- src/modules/job-manager/housekeeping.c
Problem: we observed disturbing loss of job state in housekeeping in #6179, where a job was apparently removed from the internal housekeeping list without releasing all resources.
This PR adds back a couple debug log messages that were helpful in discovering this but removed earlier in the current release cycle.  It also streamlines some `zlistx_t` handling that just felt a little loosey-goosey.
> improve housekeeping logging and list management

- .github/workflows/main.yml
- src/test/generate-matrix.py
problem: everything now builds, the timeouts now work as expected, but the fedora40 builder takes so long that it often gets cancelled by another PR getting merged within that four hour window, as a result no manifest gets generated for that merge
solution: remove fedora40 for arm64 again
This should be the last one for a while.  The only other thing in here is I made it so that every single add_build has to specify an image.  It's too easy to lose track of which is which in some cases (I did a couple of times working on all of this) so better to be explicit.
> matrix: remove fedora40 arm again

- doc/man1/flux-overlay.rst
- src/cmd/builtin/overlay.c
- t/t3303-system-healthcheck.t
Problem:  `flux overlay errors` does not show textual errors recorded for nodes in the "offline" state - only nodes that are "lost".  Among the errors not displayed are nodes that tried to connect with a mismatched flux version, which was the original motivator for the command!
Display any textual errors recorded for offline nodes.  This includes the version mismatch.  It also will show "administrative shutdown" as an error for nodes that are shutdown cleanly with `systemctl stop flux`.  I guess this is probably OK even though it's not an "error" per se, since it will only add one line to the compressed output and its meaning is probably obvious.
Example
```
$ flux overlay status
0 picl0: partial
├─ 1 picl1: partial
│  ├─ 3 picl3: full
│  ├─ 4 picl4: offline administrative shutdown
│  └─ …
```
> include offline nodes in flux overlay errors output

- doc/man1/flux-module.rst
- src/broker/broker.c
- src/broker/broker.h
- src/broker/modhash.c
- src/broker/modhash.h
- src/broker/module.c
- src/broker/module.h
- src/broker/state_machine.c
- src/cmd/flux-module.c
- src/common/libflux/module.c
- t/Makefile.am
- t/t0003-module.t
- t/t2305-sched-slow.t
- t/t3401-module-trace.t
After adding `flux overlay trace`, it seemed natural to add a tool for tracking messages sent/received by broker modules.
This also shovels some module related code in the main broker source file (broker.c) into modhash.c without modification.
Example: trace `resource` and `sched-simple` when a job is run:
```
$ flux module trace resource sched-simple
2024-08-08T09:57:10.250 sched-simple rx > sched.alloc [485]
2024-08-08T09:57:10.250 sched-simple tx > log.append [102]
2024-08-08T09:57:10.250 sched-simple tx > kvs.commit [330]
2024-08-08T09:57:10.250 sched-simple tx > log.append [90]
2024-08-08T09:57:10.251 sched-simple rx < kvs.commit [72]
2024-08-08T09:57:10.251 sched-simple tx < sched.alloc [283]
2024-08-08T09:57:10.267     resource rx > resource.topo-get [0]
2024-08-08T09:57:10.267 …
```
> add flux module trace

- etc/completions/flux.pre
Problem: The new `flux overlay trace` and `flux module trace` commands are missing from the bash tab completions file.
Add them.
> etc: add flux module/overlay trace to bash tab completion

- t/t2500-job-attach.t
Problem: when t2500-job-attach.t is run on a busy system, the "attach: reports job shell Killed if job shell is killed" test sometimes fails.
'flux submit --wait-event=exec.shell.start kill -9 $PPID' may fail if the shell is terminated before shell.start can be posted.
Moving the --wait-event to the 'flux job attach' command seems to address the problem.
Fixes #6211
> testsuite: fix racy flux job attach test

- src/modules/kvs/kvstxn.c
Problem: In PR #2547, a fix was added into the KVS to deal with duplicate appends to a KVS entry.  However, a corner case was left in the code. When an append is done to a KVS entry that does not exist, the append is treated like a normal insertion.  This corner case should also be counted as an "append".  Otherwise, duplicate appends could happen at the beginning of a KVS entry when it is created.
Solution: Set the append flag to true when a KVS entry does not exist and the append is treated like an insert.
Fixes #6207
----
Side note, now that all "good paths" are counted as appends, I could moved  `(*append) = true` into the end of the function before `return 0`.  But given how the error handling is done in the function, I felt leaving each of the `(*append) = true` near their "we did …
> kvs: correct code logic about what is an append

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/list.py
- src/cmd/flux-jobs.py
- t/python/t0013-job-list.py
- t/t2800-jobs-cmd.t
This PR takes a bit of the minor work from #5711 and uses it to implement a `-i, --include=HOSTS|RANKS` option for `flux jobs` as suggested in #6202.
This might be a more palatable first step that what's proposed in #5711, is useful on its own, and if the advanced `-f, --filter` "query syntax" is ever merged, the hostlist/ranks constrain can easily be combined (if used) with `and`.
The option name of `-i, --include` could be controversial here. I wouldn't have thought of it except that it was proposed by @kkier, and I like that it matches the similar options in `flux-resource(1)` for consistency. I also like that it works for both ranks and hostnames.
However, easy to change if others do not agree.
> flux-jobs: add `-i, --include=HOSTS|RANKS` option

- src/modules/content/cache.c
- t/t0011-content-cache.t
- t/t0090-content-enospc.t
This is an experimental PR, mostly to solve #6155 and #6100 (maybe I should split this PR into two later on), but also to experiment/brainstorm in general for future ENOSPC stuffs.
When ENOSPC is hit, rc3 hangs.  After #6170 was merged, the culprit is `flux content flush` which will never return.
I added a flag to the `content.flush` target that allows it to return ENOSPC if ENOSPC is hit when trying to write to the backing store.  I then support a `--nowait` option to `flux content flush` and use that option in rc3 to eliminate the hang.
A few thoughts on this approach:
A) There may be some initial belief that we should just always return ENOSPC, but per #6010 we may not want to do that.  The option gives us flexibility for the future, perhaps a "give up after X seconds" approach may be …
> content: allow content.flush to return errors

- src/modules/cron/cron.c
- src/modules/cron/datetime.c
- src/modules/cron/event.c
- src/modules/cron/interval.c
- src/modules/cron/task.c
- src/modules/cron/task.h
- src/modules/cron/types.h
This PR fixes #6104 by allowing cron tasks to have a default, unset cwd if just using the broker cwd. This allows use of the posix_spawn() default subprocess mechanism in most cases, instead of always falling back to fork().
> cron: use posix_spawn() for cron tasks when possible

- src/modules/job-manager/event.c
- src/modules/sched-simple/sched.c
- t/t2273-job-alloc-bypass.t
This is the most minimal fix for #6218 - it just completely skips housekeeping for alloc-bypass jobs.
This _seems_ like the right approach, i.e. it may be surprising to have housekeeping run, if configured, for jobs using alloc-bypass. However, prolog/epilog actions are not similarly skipped for alloc-bypass jobs (and this is probably necessary, because some of these actions may be required for job functionality), so an argument could be made to keep housekeeping support for alloc-bypass.
Anyway, this PR is WIP to ensure we have agreement first on no support for housekeeping on alloc-bypass jobs.
This PR also turns a failed free request in sched-simple from a log message into a hard error so that we can catch future failures in the testsuite and CI.
> job-manager: skip housekeeping for alloc-bypass jobs

- src/modules/content-sqlite/content-sqlite.c
- t/t0090-content-enospc.t
split out from PR #6217, this is dinky stuff
> content-sqlite: misc cleanup

- src/modules/content-sqlite/content-sqlite.c
- t/t0012-content-sqlite.t
Problem: Some module configuration varies depending on flux configuration.  In addition, future sqlite configuration may change
during operations.  There is no way to know what the current configuration is.
Output the journal_mode and synchronous settings in the module stats.
> content-sqlite: add sqlite config to module stats

- src/modules/content-sqlite/content-sqlite.c
- t/t0012-content-sqlite.t
Problem: In content-sqlite, the journal_mode and synchronous configs for sqlite can only be configured via the module command line.  This can be inconvenient, especially for testing.
Support their configuration via the flux config as well.
> content-sqlite: set sqlite pragmas with flux-config

- .mergify.yml
problem: mergify is deprecating some of the options we use, and removing them in a few weeks
solution: use the new versions
> mergify: use updated keys before deprecation bites

- src/common/libev/ev.c
- t/valgrind/valgrind.supp
problem: libev accesses one byte past the end of the stack in its custom assembly memory fence.  I have no idea why, it doesn't help, and causes valgrind to throw a warning every single time it gets invoked.
solution: Apply this patch identified for debian upstream in 2017 so it
will stop doing that: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850861
> libev: fix memory fence on i386 under valgrind

- doc/guide/admin.rst
- etc/rc1
- src/bindings/python/flux/job/validator/plugins/feasibility.py
- src/modules/job-manager/update.c
- src/modules/sched-simple/sched.c
- t/t2110-job-ingest-validator.t
This PR updates sched-simple, the feasibility validator plugin, and docs to conform with the RFC 27 specification of a `feasibility` service and `feasibility.check` RPC instead of `sched.feasibility`. This disentangles the feasibility checks from the scheduler service, and therefore allows more flexibility in how and where the feasibility service is implemented.
Before this PR passes CI, a small PR may be necessary in flux-sched to have qmanager register the `feasibility` service and add a handler for `feasibility.check` requests. (Later, a feasibility specific module in Fluxion may be supported)
> update feasibility RPCs to conform to RFC 27

- doc/man1/common/job-dependencies.rst
Problem: there is not a concrete example of using --dependency in our current documentation.
Solution: add example to man1/common/job-dependencies.rst
> doc: add dependency example

- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/cli/batch.py
- t/t2710-python-cli-submit.t
- t/t2711-python-cli-run.t
- t/t2712-python-cli-alloc.t
- t/t2714-python-cli-batch.t
Since Python `argparse` throws an error if an ambiguous `argparse` option is used after the last non-option argument (e.g. `flux run -n2 foo --n=2` throws an error, even though `argparse` should just ignore everything from `foo` onwards), there should be some way for users to work around this problem. However, the standard use of `--` doesn't work here, because Python then includes the `--` as part of `args.command` (in the case of `flux run` and `flux submit`) or `args.SCRIPT` in the case of `flux batch`.
This PR simply ignores `--` when it is the first entry of `args.command` or `args.SCRIPT` and adds some tests that verify the solution works. (i.e. `flux run -n2 -- foo --n=2` can be used to workaround the error noted above).
There may be some better way to support this with `argparse` …
> Fix handling of `--` used to separate options from command in `flux submit`, `run`, and `batch`

- doc/man1/common/job-other-options.rst
- etc/completions/flux.pre
- src/bindings/python/flux/cli/base.py
- t/t2710-python-cli-submit.t
As suggested by @garlick and @jameshcorbett, this PR adds support for `-S` as shorthand for `--setattr` in all job submission commands.
> support short option `-S` for `--setattr=` in job submission commands

- doc/man5/flux-config-job-manager.rst
- src/modules/job-manager/housekeeping.c
- t/t2226-housekeeping.t
In an offline discussion with @grondo about his pr #6235, we noted that housekeeping's `use-systemd-unit` key is misleading.  It's the IMP config that decides whether or not systemd is used to run the housekeeping script.  Really this is just selecting a comand of `imp run housekeeping`.
This changes the logic to use the above command if the housekeeping `command` key is undefined.
Note this means the housekeeping config table could be empty and still valid (housekeeping enabled).
If `use-systemd-unit` is present, it is a config error.   I could make it accept it and issue a deprecation warning if we think that's better.
> housekeeping: deprecate use-systemd-config option

- doc/man1/flux-hostlist.rst
- doc/man7/flux-environment.rst
- doc/test/spell.en.pws
- src/cmd/flux-hostlist.py
- t/t2814-hostlist-cmd.t
This PR addresse #6244 by changing `flux hostlist` with no args to read from `stdin` instead of `local` (which uses the enclosing instance or job if `FLUX_JOB_ID` is set).
This will break existing usage of `flux hostlist` where it is used, because the command will now hang instead of returning the enclosing hostlist. However, the current design choice was pretty bad and it is unlikely that this command has that much use so far, so it is probably better to just fix it now.
In order to mitigate the possibility of hangs with this change, a timeout was added to the read of `stdin` of 15s. After the timeout the command exits with a warning. Hopefully this workaround can be removed in the next release.
The existing behavior can be replicated with `flux hostlist local` or a new `flux hostlist …
> flux-hostlist: change default source from `local` to `stdin`

- doc/guide/admin.rst
- doc/man5/flux-config-job-manager.rst
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/plugins/perilog.c
- t/Makefile.am
- t/t2274-manager-perilog-per-rank.t
- t/t2274-manager-perilog.t
Posting this PR as a WIP to get early feedback and to give reviewers a head start.
This PR reimplements the perilog jobtap plugin using bulk-exec in order to support direct execution of prolog/epilog on the ranks of a job instead of using `perilog-run`, which has been shown to take several minutes to start `flux exec` for a job comprising thousands of nodes.
The plugin should continue to work the same unless a new `per-rank = true` option is set, in which case the plugin uses bulk-exec to launch the defined `command` across all ranks that are part of the starting/ending job.
Support for other `flux perilog-run` features are also moved directly into the plugin, including draining failed ranks, a `timeout` parameter, and a `use-imp` boolean which replaces `command` with `["$imp", "run", …
> perilog: support direct execution of prolog/epilog on job ranks for better performance

- src/bindings/python/flux/progress.py
problem: in some corner case the equation produces an offset of exactly len(style) rather than a valid offset
solution: when that happens, set it to -1 to access the last element
> progress: ensure we don't access outside style

- doc/man5/flux-config-resource.rst
- src/cmd/flux-R.c
- src/modules/resource/resource.c
- t/t0026-flux-R.t
- t/t2315-resource-system.t
This PR adds a new `resource.scheduling` key in the Flux config TOML that, when set,  amends the configured _R_ with an externally defined `scheduling` key. Notably, this allows use of JGF with the `resource.config` array, which currently is not possible. It also would allow storing _R_ and JGF in separate files if this is desired.
It is an error if `resource.scheduling` is set but neither `resource.path` or `resource.config` are.
Fixes #6245
> support `resource.scheduling` in config TOML to amend configured R with a scheduling key

- doc/man5/flux-config-job-manager.rst
- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog-per-rank.t
This PR addresses #6055 by triggering the job epilog when the prolog completes if it fails, e.g. due to timeout or if it is canceled due to a job exception.
Fixes #6055
> run epilog even if job prolog fails or is canceled

- doc/man1/flux-resource.rst
- src/bindings/python/flux/resource/status.py
- src/cmd/flux-resource.py
- t/Makefile.am
- t/t2354-resource-status.t
Currently the `flux resource status` command doesn't support display of `allocated` resources, even though this information is available because it is necessary to split `draining` nodes from `drained`. The addition of this state is trivial, and could be useful in situations like #6248.
Note that this PR does not put `allocated` in the list of states to show by default, so the default output won't change. However, `flux resource status -s all` will now show the set of allocated nodes, which may be helpful when admins and users are trying to see the status of all nodes at a glance.
> support display of `allocated` nodes in `flux resource status`

- NEWS.md
This PR updates `NEWS.md` for v0.66.0.
As usual, feel free to push additions/amendments directly here.
This assumes #6253 is approved and is merged today. If not, I'll remove that entry.
> add release notes for v0.66.0

- doc/guide/admin.rst
- doc/test/spell.en.pws
Problem: the admin guide does not describe how to configure the flux system instance to run the prolog and epilog scripts in systemd, but this probably should be recommended.
Add an example prolog/epilog script.
Change the IMP config instructions to point to systemd rather than the user-provided scripts.
Drop the paragraph about suppressing output in the flux log since it does not apply when set up this way.
> doc: update admin guide for systemd perilog

- doc/man1/flux-shell.rst
- src/shell/output.c
- t/t2606-job-shell-output-redirection.t
Problem: The KVS has a size limit of INT_MAX for when returning kvs values.  This limit can be exceeded by a job's standard output because it is continually appended and the total size is not yet tracked by the KVS.  When reading the output later, such as via `flux job attach`, this can lead to EOVERFLOW errors.
Solution: For a single user instance, default to a maximum standard output of 1G instead of "unlimited".  1G should provide a practical maximum for most users and encourage them to send standard output to a file if they want to save excess standard output.  If desired, the value can still be overwritten via the "output.limit" setting.
Fixes #6256
----
Any thoughts of if the limit should be higher? lower?   I picked 1G mostly b/c I disliked the limit of "2G - 1".  
I also timed …
> limit output to 1G in single user instances

- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog-per-rank.t
The documentation states that the `perilog.so` plugin prolog, if configured, has a default timeout of "30m", but this wasn't actually the case.
Fix the code to add the 30m default for the prolog, and add the missing test.
If people feel it would be better to not have defaults for either prolog/epilog I can instead fix the documentation. I could go either way.
> perilog: ensure default prolog timeout matches documentation

- src/bindings/python/flux/core/handle.py
- src/bindings/python/flux/util.py
- t/python/t0001-handle.py
As part of some other work, it seemed like it would be nice to have a convenient method to get values from current Flux configuration. This is one possible simple approach.
This PR adds a `flux.Flux.conf_get()` method:
```python
def conf_get(self, key=None, default=None, update=False):
````
On first access or if `update=True`, the current config is synchronously fetched from the broker and cached. If `key` is `None`, then the entire object is returned, otherwise `key` is a dotted string representation of a key from the config to return. If `key` does not exist, then `default` is returned.
This should make it easy for Python components to use the Flux configuration.
As I said, this is just one approach, but thought I'd throw it up as a PR for comments.
> python: add `conf_get()` convenience method to `flux.Flux` handle

- doc/man7/flux-environment.rst
Problem: There's a typo in the flux-environment(7) manual page. FLUX_IPADDR_HOSTNAME is specified where FLUX_IPADDR_INTERFACE should have been used.
Update the entry to specify the correct nvironment variable.
> doc: fix typo in `FLUX_IPADDR_INTERFACE` entry in `flux-environment(7)`

- src/common/libhostlist/hostlist.c
- src/common/libhostlist/hostlist.h
- src/common/libhostlist/hostname.c
- src/common/libhostlist/hostname.h
- src/common/libhostlist/hostrange.c
- src/common/libhostlist/hostrange.h
- src/common/libhostlist/test/hostlist.c
- src/common/libhostlist/test/hostname.c
- src/common/libhostlist/test/hostrange.c
This is an in-progress PR looking at making hostrange_find allocation-free.  It actually does that, and also keeps track of the length of all string components such that it can use comparison functions that don't have to check for a null terminator, but when I was doing tests with this a few weeks ago, it was no faster for the flux-sched case.  Maybe worth poking at to see if I did something screwy but something strange is going on.
> remove allocations in hostrange_find

- configure.ac
Problem: autoconf will accept junk at configure time as a valid version, then go off and generate an invalid version.h file. This happens frequently with shallow clones, setups in CI, or other constrained user environments. It has caused new contributors a lot of confusion in the past.
Solution: Like [flux-framework/flux-sched#1291](https://github.com/flux-framework/flux-sched/issues/1291) suggested, reject invalid versions at configure time and provide appropriate suggestions to the user to remedy this.
> configure: add check for valid version

- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- doc/man7/flux-environment.rst
- doc/test/spell.en.pws
- src/broker/boot_pmi.c
- src/broker/overlay.c
- src/common/libutil/Makefile.am
- src/common/libutil/cidr.c
- src/common/libutil/cidr.h
- src/common/libutil/ipaddr.c
- src/common/libutil/ipaddr.h
- src/common/libutil/test/cidr.c
- src/common/libutil/test/getaddr.c
- src/common/libutil/test/ipaddr.c
- t/t0001-basic.t
Problem:  starting an instance with its overlay assigned to a particular network is tricky if you network interface names are unpredictable.  And environment variables are a hacky way to influence the broker's choice.
The broker chooses a network address to bind to (and to exchange with PMI peers) using a heuristic usually based on the default route.  You can set environment variables to choose the address associated with the hostname instead, or a specific interface by name.
This adds
- the option of specifying the interface by network address (ipv4  CIDR, e.g. 10.0.2.0/24)
- a new broker attribute `tbon.interface-hint` which can have the values of `default-route` (the default), `hostname` (as described above), or name that can be either an interface name or a network address
- a TOML …
> add tbon.interface-hint broker attribute / configuration key with CIDR network support

- src/bindings/python/flux/job/validator/plugins/require-instance.py
- t/t2110-job-ingest-validator.t
@trws had suggested in a meeting that the `require-instance` validator might be more useful if it had a configurable minimum job size to which the validator would apply. For example, a cluster might be configured to allow any jobs up to 16 nodes, but above that, `flux alloc` or `flux batch` should be used.
This PR adds new options to the `require-instance` validator `--require-instance-minnodes=N` and `require-instance-mincores=N` which, if used, allow jobs smaller than these numbers to be ignored by the plugin. To avoid a case where only `--require-instance-minnodes` is used, and all jobs that only specify cores are allowed to run, a very conservative default of 16 cores per node is assumed if `--require-instance-mincores` is not set.
It would be nice if this configuration could be set …
> validator: allow configurable minimum job size in the require-instance validator plugin

- doc/man1/flux-pmi.rst
- src/broker/boot_pmi.c
- src/cmd/builtin/pmi.c
- src/cmd/flux-start.c
- src/common/libpmi/upmi.c
- src/common/libpmi/upmi.h
- src/common/libpmi/upmi_libpmi.c
- src/common/libpmi/upmi_libpmi2.c
- src/common/libpmi/upmi_simple.c
- src/common/libpmi/upmi_single.c
- src/shell/pmi/pmi.c
- t/t0001-basic.t
- t/t2602-job-shell.t
- t/t3002-pmi.t
Problem: brokers can hang if some of them enter the PMI barrier and others encounter a fatal error.
For example, #6278 demonstrates such a hang when `tbon.interface-hint` suggests an interface that doesn't exist.
With this PR, that example fails immediately like this:
```
$ flux start -s2 -o,-Stbon.prefertcp=1,-Stbon.interface-hint=192.16.1.1/24
flux-broker: could not find address associated with 192.16.1.1/24
flux-start: 0: PMI_Abort(): fatal bootstrap error
flux-start: 0 (pid 1227875) exited with rc=1
flux-start: 1 (pid 1227876) Killed
```
or
```
$ flux start -s2
ƒ(s=2,d=0,builddir) $ flux batch -N2 --broker-opts=-Stbon.interface-hint=192.16.1.1/24 --wrap true
ƒH51ZWG7
ƒ(s=2,d=0,builddir) $ flux job attach ƒH51ZWG7
0.075s: job.exception type=exec severity=0 PMI_Abort: fatal bootstrap …
```
> broker: call PMI_Abort() if something goes wrong during PMI bootstrap

- src/bindings/python/flux/job/validator/plugins/feasibility.py
- src/bindings/python/flux/job/validator/validator.py
Currently, the Python validator plugin interface provides an on-demand Flux handle via the `ValidatorJobInfo` class. However, in retrospect, this was a big mistake. Since the `ValidatorJobInfo` object is created once per job, the handle is closed and must be reopened for each job passed to a validator plugin. Also, since the job info object is passed to multiple validators running in different threads, thread-local storage needs to be used, which complicates the implementation. Finally, the `ValidatorJobInfo` object is obviously not available when the plugin is configuring itself, which makes it impossible for plugins to contact Flux to configure themselves (or they have to open a handle themselves)
This PR instead provides a new `flux` attribute in the `ValidatorPlugin` class which opens …
> python: update Flux handle location in validator plugin API

- doc/man1/flux-jobs.rst
Problem: There's a quirk in the Python argparse implementation that causes a required option argument that has a leading dash to be ignored when a space between long option and its argument is used instead of an equals. This is common with the `flux jobs --since` option because relative FSD is allowed so `-1h`, `-30m`, etc are expected option arguments. This can be very confusing to users who may not have an inkling of what's going on.
Add a note in the flux-jobs(1) man page regarding this quirk in hopes users will see and become aware of it. Suggest that `=` always be used between `--since` and its argument to avoid the problem.
> doc: add warning about Python argparse in flux-jobs(1)

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
- src/cmd/flux-pgrep.py
- src/cmd/flux-resource.py
- t/t2800-jobs-cmd.t
This PR adds two new output format "sentinels" `+:` and `?+:` to the `OutputFormat` class that allow automated adjustment of the field width to avoid truncation. `+:` only does the expansion, while `?+:` combines the functionality of `+:` and `?:` and expands the field to the maximum observed width and removes the field if all entries would result in an "empty" value.
Then `?+:` is applied to `flux resource list` default output for `queue` and `ngpus` fields. This avoids truncation of the QUEUE column, which may contain comma separated list of queues on system instances (and in the case of `ngpus` saves a couple characters of width in the common case)
> support expandable width output formats and use them in `flux resource list` to avoid truncation of queue field

- .clang-format
Problem: the .clang-format file has a duplicated line that causes clang-format to break.
Remove the duplicated line.
> format: fix clang-format file

- src/shell/oom.c
Problem: when a job exceeds the memory cgroup limit, it may not be immediately obvious what the limit is or what host it occurred on.
Include the hostname with the existing "out of memory" message. Log the value of memory.peak (the peak memory usage).
New output example
```
29.475s: flux-shell[0]: ERROR: oom: Memory cgroup out of memory: killed 1 task on picl7.
29.563s: flux-shell[0]: ERROR: oom: memory.peak = 1.4428558G
```
> shell/oom: log more detail when tasks are killed

- doc/man5/flux-config-tbon.rst
- doc/man7/flux-broker-attributes.rst
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/shell/pmi/pmi.c
- t/Makefile.am
- t/t0001-basic.t
- t/t0019-tbon-config.t
Problem: we don't have a way to configure subinstances to use a particular network, other than setting the global environment variable FLUX_IPADDR_INTERFACE.
Change the way the default `tbon.interface-hint` is set.  Instead of hard coding "default-route", use the value that is set in the enclosing instance, if any.
This would allow a system instance to configure `tbon.interface-hint` and batch/alloc jobs that it starts would use that value unless overridden.  If the value is not configured, then the attribute will have the default value which will be inherited by the child.
> broker: use enclosing instance tbon.interface-hint unless overridden

- src/bindings/python/flux/cli/base.py
Problem: The Xcmd class that implements option argument mutability in flux-bulksubmit(1) has a manual list of mutable options that is missing some useful options.
Update the list to include some missing options, like --cwd=, --signal=, --taskmap=, and --begin-time=.
Fixes #6295
> flux-bulksubmit: support `{}`  in more options like `--cwd=`, `--signal=`, `--taskmap=`, etc.

- src/common/libsubprocess/ev_fbuf_read.c
- src/common/libsubprocess/fbuf_watcher.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/stdio.c
Problem: In several cases, libsubprocess hangs/spins can occur if the internal output buffer is full.  For example, if subprocess output is line buffered and a single line exceeds the buffer size, the buffer can never be emptied because output callbacks are never called (i.e. the buffer never contains a line).
Other situations can exist if the user simply does not read data when it becomes available.
Solution: Handle full output buffers with two special cases
- if output is line buffered and the buffer is full AND no line exists, call the output callback for the user to get the current data.
flux_subprocess_read_line() and similar functions will return data that is not a full line.
- if the buffer is at capacity and the user elected to not read anything in the output callback, drop the …
> libsubprocess: do not spin on large lines

- src/bindings/python/flux/job/list.py
Problem: The JobList class documentation indicates that the default is to list jobs for all users.  This is incorrect, the default is to list jobs for the current user.
Update documentation accordingly.
Fixes #6308
---
and fixup one other thing I noticed
> python: fix JobList default documentation

- config/ax_python_devel.m4
- scripts/install-deps-deb.sh
- scripts/install-deps-rpm.sh
- src/test/docker/alpine/Dockerfile
problem: flux-core currently can't configure with python3.12 due to setuptools no longer being part of the default distribution
solution: import setuptools where necessary to keep things working in the ax_python_devel file
This worked to build a copy of flux, but I didn't get the dep install scripts updated yet because I couldn't get an image downloaded on this wifi.  Now off to dinner and the airport.
> autoconf: support python 3.12

- doc/man1/flux-job.rst
Sometimes I say "minus" and sometimes I say "dash," what's the right answer? 🤔 
Problem: the --severity option for flux job raise is missing a dash.
Add the dash.
> doc: add dash to flux-job(1) manpage

- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog-per-rank.t
This PR fixes a typo that resulted in an incorrect `FLUX_JOB_USERID` in the job epilog after a prolog is canceled. Additionally, some other minor cleanup was done along the way.
> perilog: fix `FLUX_JOB_USERID` in epilog after canceled prolog

- src/common/libsubprocess/fbuf.h
- src/common/libsubprocess/fbuf_watcher.h
- src/common/libsubprocess/local.c
- src/common/libsubprocess/subprocess.h
per comment in #6281 some extra comments could be useful.  I did find myself struggling remembering how read vs write fbuf watchers behaved too.
> libsubprocess: add extra documentation

- doc/man1/flux-resource.rst
- src/cmd/flux-resource.py
- src/modules/resource/drain.c
- t/t2311-resource-drain.t
`flux resource undrain` currently aborts the entire operation if one or more targets is not currently drained. This makes it difficult to simply ensure a set of ranks/hosts are undrained.
Add a `mode=force` option to the `resource.undrain` RPC and a corresponding `--force` option to `flux resource undrain`.
Fixes #6306
> add `--force` option to `flux resource undrain`

- src/common/libsubprocess/bulk-exec.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
When a bulk-exec launched subprocess is terminated but still has children with open stdio fds, `bulk_exec_active_ranks()` reports an empty idset, even though the subprocess should still be considered active.
Add a libsubprocess accessor to determine if a subprocess is still active, i.e. is not failed or completed, and use this in bulk-exec to properly report all "active" subprocesses.
Fixes #6321
> libsubprocess: fix bulk-exec reporting of active ranks

- src/cmd/job/info.c
- src/modules/job-info/allow.c
- src/modules/job-info/allow.h
- src/modules/job-info/job-info.c
- src/modules/job-info/lookup.c
- src/modules/job-info/lookup.h
- src/modules/job-info/update.c
- src/modules/job-info/update.h
- src/modules/job-info/util.c
- src/modules/job-info/util.h
- src/modules/job-info/watch.c
- src/modules/job-info/watch.h
- t/issues/t4413-empty-eventlog.sh
- t/t2230-job-info-lookup.t
- t/t2232-job-info-security.t
Problem: as noted in #6325, `flux job info` prints the same error message for a missing key as for an unknown job id.
Fixing this turned out to be tricky because the `job-info.lookup` service is just acting as a proxy for a KVS lookup and doesn't have a direct way to check for an invalid ID - it just knows that a KVS lookup for` job.<id>.R` (or whatever) got ENOENT.  However it does also lookup the job  eventlog for access control purposes for guests only.  The instance owner is immune from such checks.
The solution is to always look up the eventlog regardless of request credentials if _that_ fails with ENOENT then we know the job ID does not exist.
Because this code is pretty old, a fair bit of modernization was also required.   And there is more to do but I tried to keep this focused on …
> flux job info: improve error messages

- doc/man5/flux-config-job-manager.rst
- src/cmd/flux-perilog-run.py
- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog-per-rank.t
- t/t2274-manager-perilog.t
This PR modifies the perilog plugin to never send SIGKILL to the prolog/epilog. Instead, after kill-timeout has expired, nodes still actively running a perilog are drained and the finish event posted.
To avoid too eagerly draining nodes, the default kill-timeout is doubled from 5 to 10 seconds.
> perilog: never send SIGKILL to prolog/epilog, drain active nodes after kill-timeout instead

- etc/flux-housekeeping@.service.in
Problem: sometimes systemd doesn't set $EXIT_CODE or $EXIT_STATUS and nodes that fail housekeeping are drained with the message "housekeeping code= status=".
Modify the unit file to generate a message that
- includes the jobid
- drops the code/status labels and just print the values, if set
- include the $SERVICE_RESULT or "failure" if unset
Examples:
When housekeeping script exits with nonzero code: `housekeeping@f2PsCLp3gf9 exit-code: exited 1`
When flux housekeeping kill is used: `housekeeping@f2PxL1tmvUX signal: killed TERM`
If no env vars available (theoretical): `housekeeping@fuzzybunny failure`
Fixes #6176
Edit: tested the first two on debian bookworm (systemd 252).  The env vars were added in 231.  El cap runs 239.
> systemd: improve housekeeping drain message

- doc/man1/common/job-standard-io.rst
Problem: It may surprise users that --output, --error, and --input files are opened on the first node of the allocation and relative to the working directory of the job, not on the submission node.
Add a note to the common job-standard-io.rst document warning users of this potential pitfall.
Fixes #6329
> doc: add warning about stdio file paths in submission cli man pages

- src/common/libsubprocess/remote.c
Problem: If a output buffer is full, we issue an emergency call to the user's output callback to empty the buffer before more data is put in it.  This is done because we cannot control the order in which check callbacks are called.  Now that check callbacks can have priority set, we can ensure output check callbacks are called first before a check callback that may put more data in the buffer.
Set the priority of the output check watcher higher than the default.  Remove the now unnecessary emergency callback to the user's output callback.
built on top of #6316
> libsubprocess: increase output watcher priority

- src/modules/resource/drain.c
- t/t2311-resource-drain.t
By default `flux resource undrain` aborts the entire operation if any target is not drained, but it only includes the first rank in the error message which has proved confusing.
This PR updates the error message to include all not drained hostnames (and their corresponding ranks).
> include all not drained hostnames in `flux resource undrain` error message

- src/cmd/flux-resource.py
Problem: the "long" format of 'flux resource drain' doesn't show the un-truncated drain reason, but one might expect that to be the case.
Now that we have expandable field width support, use it for {reason} in the "long" format.  In addition, to conserve space, {timestamp} is changed to use same format as "default", since the longer representation wasn't particularly helpful.
```
$ flux resource drain
TIME         STATE    REASON                         NODELIST
Oct02 13:06  drained  This is a long drain message + pop-os
$ flux resource drain -o long
TIME         STATE    RANKS    REASON                                NODELIST
Oct02 13:06  drained  0        This is a long drain message isnt it? pop-os
```
Same for {reason} in the "long" format of 'flux resource status':
```
$ flux …
```
> make flux resource drain -o long reason expandable

- t/sharness.d/flux-sharness.sh
- t/t0001-basic.t
Problem: As noted in #6336, one of the tests is occasionally failing due to an unexpected signal caught by `test_must_fail_or_be_killed` but we don't know which one.
This changes that function to print the signal number so we can get a clue as to what is happening (did it segfault?)
And there is some adjacent cleanup and tests added for the function itself.
> testsuite: improve test_must_fail_or_be_killed function

- doc/guide/admin.rst
- src/cmd/flux-run-epilog.in
- src/cmd/flux-run-housekeeping.in
- src/cmd/flux-run-prolog.in
Problem: flux-run-{prolog,epilog,housekeeping} scripts do not fail if systemctl start fails.
Replace "wait" with "wait $!".
The former always returns success.
> systemd: make scripts fail if systemctl start does

- doc/man1/flux-module.rst
- doc/man1/flux-overlay.rst
- etc/completions/flux.pre
- src/broker/module.c
- src/broker/overlay.c
- src/cmd/builtin/overlay.c
- src/cmd/flux-module.c
- t/t3400-overlay-trace.t
- t/t3401-module-trace.t
Look, payloads can be displayed now in `flux overlay trace` and `flux module trace`.   Here's an example of the latter when running `flux run hostname`.
Note that non-json payloads are not displayed.  The log message at the end is a good example - we encode those in RFC 5424 format.
```
$ flux module trace --full sched-simple
2024-10-03T17:39:29.131 sched-simple rx > sched.alloc [478]
{
"id": 1098219782144,
"priority": 16,
"userid": 5588,
"t_submit": 1728002369.1095428,
"jobspec": {
"resources": [
{
"type": "slot",
"count": 1,
"with": [
{
"type": "core",
"count": 1
}
],
"label": "task"
}
],
"tasks": [
{
"command": [
"hostname"
],
"slot": "task",
"count": {
"per_slot": 1
}
}
],
"attributes": {
"system": {
"duration": 0,
"cwd": "/home/garlick/proj/flux-core",
"shell": {
"options": { …
```
> add --full option to display payloads in message tracing programs

- src/broker/runat.c
- src/cmd/builtin/proxy.c
- src/cmd/flux-start.c
- src/common/libsubprocess/fork.c
- src/common/libsubprocess/posix_spawn.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/subprocess.c
- src/shell/task.c
Problem: Remote subprocesses default to always set the SETPGRP flag.  This leads to inconsistent behavior where local subprocesses don't have the flag set but remote ones do.
We could remove this default and require remote subprocess execution to set this flag as needed.  However, it ends up that the vast majority of code in flux-core sets the SETPGRP flag anyways, leading to an excess amount of code change to make local vs remote subprocesses consistent.
Solution: Invert the SETPGRP flag logic into NO_SETPGRP.  Now, by default, have both local and remote subprocesses call setpgrp(2).  The NO_SETPGRP flag will then disable the call to setpgrp(2).  Update all callers to libsubprocess accordingly.
Note that we leave the new NO_SETPGRP flag to be for local subprocesses only.  If there comes …
> libsubprocess: invert SETPGRP flag logic

- configure.ac
- src/broker/Makefile.am
- src/broker/module.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/trace.c
- src/broker/trace.h
- src/cmd/builtin/overlay.c
- src/cmd/flux-module.c
- src/common/libmissing/Makefile.am
- src/common/libmissing/strerrorname_np.c
- src/common/libmissing/strerrorname_np.h
- t/t3400-overlay-trace.t
- t/t3401-module-trace.t
Problem: `flux module trace` and `flux overlay trace` don't show the `errnum` value for response messages, but this would be helpful when interpreting message traces.
Append  "success" or the error name associated with the `errnum` value in the one line trace output for responses.
When `--full` is specified, include human readable error message (if any) from  the payload.
Change the color of failure response messages to bright red so they stand out.
> show response result in message traces

- doc/man1/flux-jobs.rst
Problem: flux jobs --count=0 means "unlimited" but that is not documented in the man page.
Add it.
Fixes #6363
> flux-jobs(1): document unlimited --count value

- src/common/libsubprocess/server.c
- src/common/libsubprocess/test/channel.c
- src/common/libsubprocess/test/stdio.c
- src/common/libsubprocess/util.c
peeling off some independent cleanups/fixups from #6353
> libsubprocess: check bufsize is > 0

- src/modules/sched-simple/sched.c
- t/t2300-sched-simple.t
Problem: The exception raised by sched-simple when it receives a job request including GPUs can be confusing. Especially when users expect that a different scheduler is loaded, or do not know that sched-simple does not support scheduling GPUs.
Improve the exception message to say explicitly
sched-simple does not support resource type 'gpu'
to make it clear that sched-simple is loaded and does not support GPUs.
> sched-simple: improve unsupported resource type exception

- doc/index.rst
The hyper-link to the flux-accounting guide on flux-core's front page no longer works because the guide was moved from flux-docs to flux-accounting, which now has its own ReadTheDocs site.
---
This PR just updates the link to the flux-accounting guide.
> doc: update link to flux-accounting guide

- src/bindings/python/flux/util.py
- t/python/t0024-util.py
This PR fixes some issues discovered while working on something else for the `flux.util.OutputFormat` class. It also became apparent that the `OutputFormat` class is complex enough now that it could definitely use some unit testing, so that's added here as well.
> python: cleanup, fixes, and unit tests for flux.util.OutputFormat

- doc/man1/flux-housekeeping.rst
- etc/completions/flux.pre
- src/cmd/flux-housekeeping.py
- t/t2226-housekeeping.t
This PR adds a `-i, --include=TARGETS` option to `flux housekeeping list` as requested in #6375.
> flux-housekeeping: add `-i, --include=TARGETS` option to `flux housekeeping list`

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
- t/python/t0024-util.py
- t/t2800-jobs-cmd.t
This PR adds support for adding sort keys directly to format strings in the `flux.util.OutputFormat` class via a `sort:` prefix, e.g. `sort:t_run {id.f58}`. The sort is done in the `OutputFormat.print_items()` method, so all utilities that use that method get this form of sort support automatically.
Then, a `--sort` option is added to `flux jobs` to set the sort keys, overriding any existing  sort stored with the format.
Admittedly, it is a bit strange to do it this way, it isn't immediately obvious that a class ostensibly handling an output format string should support sort keys. However, I started work on another branch where I added sort directly to `flux jobs` and it ended up being more complicated because 1. the sort keys need to be included in the "fields" that `flux jobs` uses to …
> support `sort:` prefix for format strings and `--sort` option to `flux jobs`

- src/common/libsubprocess/client.c
- src/common/libsubprocess/client.h
- src/common/libsubprocess/ev_fbuf_write.c
- src/common/libsubprocess/ev_fbuf_write.h
- src/common/libsubprocess/fbuf.c
- src/common/libsubprocess/fbuf.h
- src/common/libsubprocess/fbuf_watcher.h
- src/common/libsubprocess/local.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/fbuf.c
- src/common/libsubprocess/test/fbuf_watcher.c
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/stdio.c
- t/reactor/reactorcat.c
Per https://github.com/flux-framework/rfc/pull/427 and discussion in #4572.
Some minor tweaks to the `add-credit` RPC.  I think the design in the RFC assumed multiple channels would return credits at the same time, but I think that is impractical, so it's just credits for each channel.
Haven't tested that this works by adding support in `flux-exec` yet.  Just thought I'd post this initial work.  May split off the cleanup into another PR.
> libsubprocess: support flow control on writes via credits

- src/bindings/python/flux/job/journal.py
- t/python/t0030-journal.py
@wihobbs had pointed out some usability issues with the `JournalConsumer` class yesterday after the PR was merged. This PR tackles those issues.
- Document that `poll()` must be called after `start()`.
- handle the above case better by raising a specific `RuntimeException` when the `JournalConsumer` isn't started before `poll()` is called
- allow `set_callback()` to be called before `start()` - there's no reason not to allow it.
- add tests accordingly.
> python: usability improvements for `JournalConsumer` class

- src/broker/boot_config.c
- src/broker/boot_config.h
- src/broker/boot_pmi.c
- src/broker/boot_pmi.h
- src/broker/broker.c
- src/broker/broker.h
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/boot_config.c
- src/broker/test/overlay.c
- src/cmd/flux-start.c
- src/common/libhostlist/hostlist.c
- t/issues/t4182-resource-rerank.sh
- t/t2311-resource-drain.t
Problem: as noted in #6389, a mismatched `bootstrap.hosts` config can result in two hosts ping-ponging back and forth, connecting and causing the the other to be disconnected with a misleading message.
This adds the hostname to the `overlay.hello` RPC.  The rank was already there.  If the `hostlist` broker attribute does not confirm the rank to host mapping, deny the connection.
Marking as a WIP for now  pending inspiration on how to adapt the issue test for  #4182 (resource module re-ranking).
> broker: detect mismatched bootstrap.hosts configuration

- src/test/generate-matrix.py
Problem: Recent updates to the flux-core ci workflow dropped the deployment of the  fluxrm/flux-core:el8 image, but several projects depend on this image representing the current version of flux-core.
Add a new el8 test-install builder to CI and tag the image for docker deployment.
> docker: add missing tag of flux-core el8 image

- src/common/libsdexec/start.c
- src/modules/job-exec/exec.c
- src/modules/sdexec/sdexec.c
- t/t2409-sdexec.t
Problem: For multi-user jobs spawned via SDEXEC, the systemd user instance running as the flux user does not have permission to kill guest processes, yet it does try and in the process may kill off the only process that does have permission to continue cleanup efforts, the IMP.
When the job is run by the IMP and sdexec, Set `KillMode=process` so that systemd only delivers signals to the IMP, which it should forward to the shell and/or cgroup per RFC 15.
Also set `SendSIGKILL=off` so that SIGKILL is never deployed against the IMP.
Fixes #6399
This _should_ be OK even without the forthcoming changes to job-exec and the IMP to forward signals and avoid using SIGKILL, however I still need to give this a sanity check on my test cluster as the conditional use of these properties for IMP jobs is …
> sdexec: set KillMode=process SendSIGKILL=no for multi-user jobs

- src/broker/test/overlay.c
Problem: There is a small chance of receiving EADDRINUSE from an overlay_bind() call if a prior test has not fully cleaned itself up.
Retry overlay_bind() if EADDRINUSE is hit.
Fixes #6404
>     broker/test: avoid race in zeromq cleanup

- src/cmd/flux-exec.c
- t/t0005-exec.t
built on top of #6353, splitting it off since it's a separate issue
> flux-exec: use subprocess credits to avoid overflowing stdin buffers

- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog-per-rank.t
This PR fixes an issue discovered while testing recent flux-security changes.
If the prolog times out and the resulting cancel (SIGTERM) then times out, affected ranks are drained, but no job exception is raised so the job continues to start. Not only does this result in a job starting when it isn't supposed to, but additionally the epilog may be run _twice_: once when the prolog fails and again when the `finish` event is posted.
This PR fixes the issue by adding a new flag cancel_timeout to the `perilog_proc` struct which then results in a specific exception being raised. The exception then prevents the job from starting and of course the extra `finish` event, etc.
A test that reproduced the issue is also added.
> resolve perilog plugin issue that lets a job start after prolog timeout when cancellation fails

- configure.ac
- doc/man1/flux-exec.rst
- src/cmd/flux-exec.c
- src/common/libsubprocess/bulk-exec.c
- src/common/libsubprocess/bulk-exec.h
- src/common/libsubprocess/test/bulk-exec-einval.c
- src/modules/job-exec/exec.c
- src/modules/job-exec/job-exec.c
- src/modules/job-manager/housekeeping.c
- src/modules/job-manager/plugins/perilog.c
- src/test/docker/docker-run-checks.sh
- t/job-exec/imp-fail.sh
- t/t2404-job-exec-multiuser.t
Problem: job-exec uses `flux imp kill` to deliver SIGKILL to the flux-shell when shell signaling methods fail to clean up a multi-user job, but the `flux imp kill` sub-command is being deprecated in favor of having the IMP forward signals (per RFC 15).
This changes job-exec to send SIGUSR1 (which RFC 15 defines as a proxy for SIGKILL) directly to the IMP in that case.
To make it easier to coordinate the flux-core and flux-security changes, we'll add the #6409 fix here as well.
> update multi-user signaling to track flux-security 0.13.0 IMP changes

- doc/man7/flux-broker-attributes.rst
- etc/flux.service.in
- src/broker/state_machine.c
- t/t0025-broker-state-machine.t
Problem: `systemctl stop flux` on rank 0 may hang waiting for the queue to become idle, and the broker may be killed before it can write its KVS checkpoint if the systemd `TimeoutStopSec=90s` is exceeded.
This adds a 45s timeout over all cleanup actions when the broker is started by systemd.  The timeout only applies if the broker is being shut down on a signal, which is the case for `systemctl stop flux` but not `flux shutdown`.
If cleanup gets stuck waiting for the queue to become idle after a `systemctl stop flux` it should move on to stopping the rest of the system after 45s.  It's possible we'll discover another place after cleanup where things can go wrong, but this seems like a good first step. 
By default this timeout is disabled.  It is configured on in the systemd unit file, …
> add cleanup timeout for systemctl stop flux on rank 0

- doc/man5/flux-config-bootstrap.rst
I've been trying to make different topology designs this weekend, and this was the only example I could find of a slightly interesting tree in the flux config. I spent a ton of time confused not because the tree was complex, but because I mistook a comma for a dash (meaning I was reading `test[1-128]` instead of `test[1,128]`, and didn't see it until I sat down with pen and paper to draw it out. To save others the time of also making this mistake, I'm adding a diagram to the docs here that explicitly shows the tree and describes some of the components in text.
Problem: It is really easy to miss the subtle comma (instead of a dash) for one of the bootstrap directives, resulting in a lot of confusion trying to figure out how the tree makes sense.
Solution: Provide a visual diagram of the …
> docs: rfc flux-config-bootstrap diagram

- NEWS.md
Problem: There are no release notes for flux-core v0.68.0.
Add them.
Assumes the following PRs that have merge-when-passing set will be merged:
- #6411 
- #6397
> NEWS.md: add release notes for v0.68.0

- src/modules/job-manager/plugins/history.c
Problem: Internal job history lists are sorted with larger t_submit values at the front of the list.  When new jobs are inserted (i.e. jobs with bigger t_submit values), they are inserted with a search starting at the back of the list. This is the opposite of what should be done and leads to a slowdown in job throughput over time.
Insert into the job history list starting at the front.
Fixes #6419
> job-manager/history: optimize list insertion

- doc/man1/flux-dmesg.rst
- src/cmd/builtin/dmesg.c
- src/common/libeventlog/formatter.c
- src/common/libutil/test/timestamp.c
- src/common/libutil/timestamp.c
- src/common/libutil/timestamp.h
- t/t0009-dmesg.t
- t/t2230-job-info-lookup.t
This PR changes the default timestamp display for `flux dmesg` and the "iso" time format for `flux job eventlog` `flux kvs eventlog` and `flux job wait-event`  to use local time instead of UTC. This better matches the behavior of most other system utilities and logfiles, and the old behavior can easily be restored if desired by setting `TZ=UTC`.
Fixes #6421
> convert ISO timestamp output from UTC to local time + offset in `flux dmesg` and eventlog commands

- config/x_ac_jansson.m4
- src/common/libflux/conf.c
- src/common/libflux/test/conf.c
- src/common/libmissing/Makefile.am
- src/common/libmissing/json_object_update_recursive.c
- src/common/libmissing/json_object_update_recursive.h
This PR updates the `json_object_update()` call to use `json_object_update_recursive()` when "updating" a Flux config object with another config fragment loaded from a file. This makes it so that table values in the new config object update tables in the existing config, instead of replacing tables (see #6396).
Since `json_object_update_recursive()` is not present until jansson v2.13, add a simple implementation to libmissing if necessary. Note that the upstream jansson version of this function detects cycles, whereas the libmissing version does not, but that is unlikely to be an issue for Flux.
> recursively update instead of replacing tables when loading Flux configuration

- doc/guide/admin.rst
- doc/test/spell.en.pws
Problem: the admin guide says nothing about launching jobs with systemd, but it is recommended.
Add a section on systemd+cgroup2 prerequisites and add the runes for enabling systemd job execution to the example TOML config.
Fixes #6407
> doc: launch jobs with systemd in the admin guide

- doc/guide/admin.rst
- doc/man1/flux-housekeeping.rst
- doc/man5/flux-config-job-manager.rst
- doc/test/spell.en.pws
Problem: the admin guide does not discuss housekeeping, and the flux-housekeeping(1) and flux-config-job-manager(5) man pages list housekeeping as EXPERIMENTAL.
I think we're past the EXPERIMENTAL phase at this point.  Drop that.
Add a TROUBLESHOOTING section to flux-housekeeping(1).
Rework the prolog/epilog section of the admin guide to include housekeeping and a general intro that describes the roles of the three scripts.
> doc: improve housekeeping documentation

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/job/info.py
- t/t2800-jobs-cmd.t
This PR implements @ryanday36's suggestion in #6426. It extends the `flux jobs` `{contextual_info}` field (`INFO`) to check for a priority of 0 and prints `held` if `urgency` is also zero, otherwise `priority-hold`.
> indicate held jobs in the` INFO` column of `flux jobs` output

- doc/man5/flux-config-job-manager.rst
- src/modules/job-manager/plugins/perilog.c
Problem: on a slow system, the prolog kill timeout may be exceeded due to reasons other than an intransigent prolog process.
Increase the timeout from 10s to 1m.
Fixes #6420
> increase default prolog kill-timeout from 10s to 1m

- src/bindings/python/flux/job/validator/validator.py
- src/cmd/flux-job-validator.py
Problem: The concurrent.futures ThreadPoolExecutor is not explicitly shut down when exiting flux-job-validator. This MAY be causing the program to occasionally hang at exit.
Add a stop() method to the JobValidator class which calls the shutdown() method of the executor. Call validator.stop() from flux-job-validator(1) before exit.
Fixes #6434
> python: call shutdown() on executor in job validator

- src/modules/job-ingest/workcrew.c
- src/modules/job-ingest/worker.c
- src/modules/job-ingest/worker.h
- t/t2113-job-ingest-pipeline.t
This adds a count of "trash" processes for each work crew to the `flux module stats job-ingest` output, so that there is some indication that the module is tracking subprocesses whose input has been closed, but that have not yet exited.
While in there I noticed that the cleanup code that sends SIGKILL to running workers doesn't signal workers that are lingering in the trash list.  Add code to signal those too and a test.
> job-ingest: improve cleanup and stats output

- src/modules/job-manager/job-manager.c
- src/modules/job-manager/job-manager.h
- src/modules/job-manager/queue.c
- src/modules/job-manager/queue.h
- src/modules/job-manager/restart.c
Problem: queues in the job manager are a bit strange(!) and the code is not well documented.
This is some gratuitous cleanup based on my experience revisiting the code after a long haitus.  Hopefully it makes things a little more clear for the next visitor.
> job-manager: clean up queue code

- src/cmd/job/attach.c
- t/t2500-job-attach.t
This PR is largely a rewrite of the "statusline" implementation in `flux job attach` to address multiple issues:
- the status message displayed "canceling due to exception" even for non-fatal exceptions
- the status message did not properly account for prolog-start and finish events due to the implementation
- the status message was overwritten by text when `flux job attach` logs a `job.exception` message
> fix multiple issues in the `flux job attach` statusline

- doc/man1/flux-resource.rst
@schoate had pointed out that the `flux resource list --include` option is difficult to discover because the option name itself isn't exactly obvious and the man page description of the option doesn't include the term "node' (only host and rank).
Update the `-i, --include` option documentation to include the word "node" for improved search.
> doc: improve `--include` documentation in flux-resource(1)

- src/common/libfilemap/fileref.c
Problem: 'flux archive create' segfaults when it tries to archive files with size >2G.
Change a local variable from int to size_t.
Fixes #6461
> libfileref: fix segfault for files >2G

- src/cmd/job/attach.c
- src/shell/doom.c
- t/t2304-sched-simple-alloc-check.t
- t/t2608-job-shell-log.t
Problem: Exceptions from the doom plugin do not specify what job failed.  It can be confusing to users which job failed amongst multiple in a batch job, or if the broker from a batch job itself failed.
Add the job executable name and jobid to the doom exception outputs.
Fixes #6357
---
we could obviously debate the message format, I went back and forth and just ended up at this.  Tweak suggestions welcome.
> shell: add extra info to doom exceptions

- doc/man1/flux-resource.rst
- etc/completions/flux.pre
- src/cmd/flux-resource.py
- t/t2350-resource-list.t
We didn't really come to a resolution in issue #6275 - however, it is clear that this output is surprising and wrong:
```console
$ flux resource list --include=corona171
STATE QUEUE   NNODES NCORES NGPUS NODELIST
free pdebug       1     48     8 corona171
allocated pbatch       0      0     0 
allocated pdebug       0      0     0 
allocated pnvmeof      0      0     0 
down pbatch       0      0     0 
down pdebug       0      0     0 
down pnvmeof      0      0     0 
```
This PR adds a `--skip-empty` option to `flux resource list` to skip all lines that represent empty resource sets, then makes this the default for `-i, --include` (which is probably the expected and least surprising behavior). So, instead of the above, we get:
```console
$ src/cmd/flux resource list --include=corona171 …
```
> skip "empty" lines of output in `flux resource list` with `--skip-empty` or `--include`

- doc/man1/flux-module.rst
- src/cmd/flux-module.c
- src/common/libfluxutil/method.c
- t/t0003-module.t
Problem: `getrusage(2)` accepts multiple `who` targets, but flux hard codes the non-portable RUSAGE_THREAD.
Switch the default to RUSAGE_SELF, which is portable.
Add a `who` key to the RPC and change `flux module stats --rusage` so it takes an optional argument of `self`, `children`, or `thread`.
Update docs and add a few tests.
> add flux module stats --rusage=[self|children|thread] optional argument

- doc/man1/flux-uri.rst
- doc/test/spell.en.pws
- src/bindings/python/flux/uri/resolvers/jobid.py
- src/cmd/flux-uri.py
- t/t2802-uri-cmd.t
This PR adds support for a `?wait` query parameter to the `jobid` URI resolver, and a new `--wait` option to `flux-uri` to pass that parameter down to the resolver.
This supports waiting until the URI is available for pending or starting jobs, as opposed to the resolver returning "job is not running".
If the `wait` parameter is used with a job that isn't an instance of Flux, then it waits until the `finish` event before giving up and returning "URI not found".
> support `flux uri --wait JOBID`

- doc/man1/flux-hostlist.rst
- src/cmd/flux-hostlist.py
- t/t2814-hostlist-cmd.t
This PR makes the following minor improvements to `flux hostlist`:
* `-n, --nth=IDS`: This option now takes an idset instead of a single index into the hostlist. This allows a user to get a "slice" of a hostlist while preserving current behavior, e.g. `flux hostlist -n 0-1 JOBID` to get the first two hosts of a job.
* `-x, --exclude=HOSTS|IDS`: As suggested by @vsoch, this option now takes either a hostlist or idset or indices to exclude from the hostlist. This allows a user to exclude the first host for example with `flux hostlist -x 0 local`
Fixes #6464
> flux-hostlist: allow idset argument to `--nth` and `--exclude` options

- config/x_ac_sanitize.m4
- configure.ac
- src/bindings/lua/Makefile.am
- src/bindings/python/_flux/Makefile.am
- src/common/Makefile.am
- src/common/libflux-core.map
- src/common/libflux-hostlist.map
- src/common/libflux-idset.map
- src/common/libflux-optparse.map
- src/common/libflux-schedutil.map
- src/common/libflux-taskmap.map
- src/common/libpmi.map
- src/common/libpmi/Makefile.am
- src/common/libpmi/sentinel.c
- src/common/libpmi2.map
- src/connectors/Makefile.am
- src/modules/Makefile.am
- src/shell/Makefile.am
- src/shell/flux-shell.map
- t/valgrind/valgrind.supp
More macos portability fixes.
This is based on top of #6475 and also requires flux-framework/flux-accounting#546 to be merged before CI will pass.
> fix macos portability issues (fourth batch)

- doc/man3/flux_kvs_lookup.rst
- src/cmd/job/eventlog.c
- src/common/libkvs/test/treeobj.c
- src/common/libkvs/treeobj.c
- src/common/libkvs/treeobj.h
- src/modules/kvs-watch/kvs-watch.c
- t/t1007-kvs-lookup-watch.t
Problem: The FLUX_KVS_WATCH_APPEND flag is implemented inefficiently in kvs-watch.  Everytime new data is appended, the entire contents of the watched key are retrieved and only new data calculated via an offset is sent to the watcher.  This significantly slows down performance of large appended data (such as stdio).
Solution: Instead of retrieving the entire contents of the watched key, fetch the tree object for the key from the KVS.  With access to the tree object's blobref array, we need only access the new appended blobrefs from the content store.  This significantly cuts down on the amount of data transfered during a kvs-watch.
Fixes #6414
---
side notes:
- so protocol wise
- before it was
- first RPC get all KVS data, return it all, note how long the data is
- later RPCs, get all …
> kvs-watch: only fetch new data for appends

- src/common/libflux/conf.c
- src/common/libflux/conf.h
- src/common/libflux/event.c
- src/common/libflux/event.h
- src/common/libflux/fripp.c
- src/common/libflux/future.c
- src/common/libflux/future.h
- src/common/libflux/message.c
- src/common/libflux/msg_handler.c
- src/common/libflux/plugin.c
- src/common/libflux/plugin.h
- src/common/libflux/request.c
- src/common/libflux/request.h
- src/common/libflux/service.c
- src/common/libflux/test/reactor.c
- src/common/libkvs/kvs_dir.c
- src/common/libutil/blobref.c
- src/common/libutil/blobref.h
Problem: some older code violates RFC 7 whitespace guidelines.
Break long parameter lists to one per line.
This chunk of whitespace cleanup was peeled off of #6467
> modernize code formatting

- configure.ac
- src/cmd/flux.c
- src/common/Makefile.am
- src/common/libflux/test/reactor.c
- src/common/libmissing/Makefile.am
- src/common/libmissing/pipe2.c
- src/common/libsubprocess/test/bulk-exec.c
- src/common/libsubprocess/test/fbuf_watcher.c
- src/common/libsubprocess/test/iochan.c
- src/common/libsubprocess/test/iostress.c
- src/common/libsubprocess/test/remote.c
- src/common/libutil/intree.c
- src/common/libutil/test/fdwalk.c
- src/common/libutil/test/intree.c
- src/shell/Makefile.am
- src/shell/builtins.c
- t/Makefile.am
- t/job-manager/plugins/args.c
- t/job-manager/plugins/validate.c
- t/rexec/rexec.c
- t/rexec/rexec_count_stdout.c
- t/rexec/rexec_getline.c
Last batch of macos fixes.
I _think_ this gets everything compiled, including tests but there are still unit test failures to deal with.  Anyway, this is as far as I got for now.
> fix macos portability issues (fifth batch)

- src/modules/resource/resource.c
Problem: The Rv1 scheduling key as JGF can be large and time-consuming to generate and distribute, but currently it is required on all nodes. Since the key is really only used by the scheduler on rank 0, it would be ideal resource.scheduling was only read on rank 0.
Only process the resource.scheduling config key on rank 0.
Fixes #6480
> resource: only read `resource.scheduling` config on rank 0

- configure.ac
Problem: libflux-optparse.so has unresolved jansson symbols on focal.
A recent macos portability change dropped the linker option to garbage collect unused sections, resulting in unresolved json_* symbols in libflux-optparse.so from libmissing.la on focal.
The change, introduced in flux-framework/flux-core#6476, was supposed to set a make variable $ld_gc_sections when that option is available, but the change was incomplete and the variable was never set.
Add the missing configure logic.
Confirmed:
- json_ symbols are no longer unresolved in libflux-optparse.so on focal
- macos still builds, and json_ symbols do not appear there
Fixes #6496
> build: use -Wl,--gc-sections when appropriate

- .github/workflows/main.yml
- src/common/libsdexec/test/start.c
- src/modules/job-manager/test/kill.c
- src/modules/kvs/test/cache.c
Problem: recent macos portability fixes are not being tested
Add a macos builder that just runs `make check TESTS=` to build all the code.
It doesn't run any tests because we are not there yet
- #6485
Fix a couple minor compilation issues that were missed before.
> ci: add macos builder

- src/modules/job-manager/jobtap.c
- src/modules/job-manager/jobtap.h
- t/job-manager/plugins/jobspec-update.c
- t/t2212-job-manager-plugins.t
This PR addresses #5957 by adding a function that posts a `jobspec-update` event for an arbitrary jobid.
The function assumes the target job is not in an active callback, i.e. it is being updated asynchronously, so some of the work of `flux_jobtap_josbpec_update_pack()`, like accumulating updates until the current callback is complete, can be skipped. Thus the function is really just a wrapper around `event_post_pack()`.
> jobtap: add `flux_jobtap_jobspec_update_id_pack()`

- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/conf_builtin.py
- src/common/libflux/conf.c
- t/Makefile.am
- t/python/t0031-conf-builtin.py
Currently, Python programs have no way to query libflux for compiled-in config values, but this could be useful if they want to find the current config directory. This could possibly be derived from broker attributes, but in some cases the broker attributes could be set to nothing, so this is not ideal.
Calling in to `flux_conf_builtin_get()` with `FLUX_CONF_AUTO`  using ffi doesn't work, because the "executable" for Python programs is always going to be a `python` binary installed in the system (or elsewhere), so the libflux intree detection doesn't work.
This PR introduces a wrapper for `flux_conf_builtin_get()` for Python that reimplements intree detection using the path to module itself compared to the intree python_path.
Since the motivating use case is to determine the current …
> add `flux.conf_builtin.conf_builtin_get()` to give Python access to compiled-in config values

- src/modules/job-info/guest_watch.c
- src/modules/job-info/update.c
- src/modules/job-info/watch.c
Problem: Common usage in flux-core is to not respond with an RPC error
(such as through flux_respond_error()) if a prior RPC attempt fails (such
as through flux_respond_pack()).  This pattern is violated in several
places in job-info.
Solution: If flux_respond_pack() fails, do not call flux_respond_error()
in error handling paths.
Fixes #6498
> job-info: avoid error response on failed rpc

- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/job/Jobspec.py
- t/t2710-python-cli-submit.t
This PR fixes a small bug in the submission cli `--add-file=[NAME=]DATA` option. The option is documented to allow file data on the command line if `DATA` contains a `\n`. However, any `\n` passed on the command line ends up quoted, so this doesn't actually work:
```console
$ flux submit --add-file=test='this is a test\n' hostname
flux-submit: ERROR: --add-file=test=this is a test\n: [Errno 2] No such file or directory: 'this is a test\\n'
```
This PR just unescapes in newlines in `DATA` so that newline detection works (and the newlines appear as newlines in the resulting fileref data).
> fix handling of `\n` in submission cli `--add-file=` option

- doc/man1/common/job-other-options.rst
- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/job/Jobspec.py
- t/t2710-python-cli-submit.t
This PR adds support for specifying file permissions in the `--add-file` option in Flux submission command. (Presently, all files added with content directly provided on the command like get the default permissions of 0600)
Example:
```
$ flux submit --add-file=test:700='#!/bin/sh\ntrue\n' -n1 {{tmpdir}}/test
```
> support specification of file permissions in `--add-file` submission option

- scripts/install-deps-macos.sh
Problem: macos ci builds are failing (that didn't take long!) because apparently the lua I chose was about to be deprecated, and now is.
This fixes that.
> build macos with homebrew lua that is not deprecated

- src/modules/job-exec/job-exec.c
- t/t2406-job-exec-cleanup.t
Problem: The drain message issued by the job-exec module when it gives up trying to kill user processes in the job is not clear.
Note that the unkillable job procesess were user processes to avoid confusion that epilog or housekeeping processes were at fault.
Update one test that attempts to match the old error message.
Fixes #6495
> job-exec: improve drain message for unkillable procs

- src/common/Makefile.am
- src/common/libschedutil/hello.c
- src/common/libschedutil/init.h
- src/modules/job-manager/alloc.c
- src/modules/job-manager/housekeeping.c
- src/modules/job-manager/housekeeping.h
- src/modules/sched-simple/sched.c
- t/t2226-housekeeping.t
This is a proof of concept implementation of the changes to the scheduler hello protocol proposed in flux-framework/rfc#433, in which support is added for reloading the scheduler with housekeeping running and some nodes of job(s) already released.
The scheduler indicates it supports this by calling `schedutil_create()` with the SCHEDUTIL_HELLO_PARTIAL_OK flag.  When it sets that, it agrees to parse an optional `allocated` key in each hello response.  The `allocated` key is set to an idset representing the subset of ranks of R that are actually allocated.  If missing, all ranks are assumed to be allocated.
We need to get some feedback from @milroy, @trws, et al to make sure this approach works for fluxion.  I thought working through this with sched-simple would be helpful to illustrate the …
> support partially allocated jobs across scheduler reload

- src/common/libschedutil/init.h
Problem: its laborious to test flux-core for the existence of schedutil flags because they are anonymous enums.
Convert to preprocessor symbols that can be easily checked with an #ifdef in the scheduler.
> libschedutil: use preprocessor symbols for flags

- doc/man1/flux-shell.rst
- doc/man7/flux-environment.rst
Here are a few fixes to man page deficiencies that I noticed.
> minor man page improvements

- src/shell/signal.c
Problem: The shell signal plugin doesn't work with Fluxion because it expects a float value for expiration in R and Fluxion encodes an integer.
Update the format specifier in the signal plugin's use of json_unpack on R to use `s:F` instead of `s:f` so that the plugin works with Fluxion.
Fixes #6521
> shell: fix signal plugin to work with Fluxion scheduler

- doc/man1/flux-kvs.rst
- doc/man3/flux_kvs_lookup.rst
- src/cmd/flux-kvs.c
- src/common/libkvs/kvs.h
- src/common/libkvs/kvs_lookup.c
- src/modules/kvs-watch/kvs-watch.c
- t/Makefile.am
- t/kvs/watch_stream.c
- t/t1007-kvs-lookup-watch.t
Problem: It would be convenient if there was a way to stream large data from the KVS by their individual content blobs, rather than getting a very large piece of content in one response.  Such a response can be slow and give the appearance that something is hanging.  For example, this ability would be useful for a large amount of standard output stored in the KVS.
Support a new FLUX_KVS_STREAM flag.  It will use the mechanisms built into the kvs-watch module and the FLUX_KVS_WATCH_APPEND flag to stream each content blob to the user.  Once all the content is streamed, it will return ENODATA to indicate the stream is complete.
> kvs-watch: support FLUX_KVS_STREAM flag

- src/cmd/flux-kvs.c
- t/t1008-kvs-eventlog.t
Problem: When an improperly formatted eventlog is input into eventlog commands, a non-useful error message is output.
Output a better error message.
> flux-kvs: improve eventlog error messages

- doc/Makefile.am
- doc/man1/common/job-mustache-templates.rst
- doc/man1/common/job-standard-io.rst
- doc/man1/flux-batch.rst
- doc/man1/flux-bulksubmit.rst
- doc/man1/flux-run.rst
- doc/man1/flux-shell.rst
- doc/man1/flux-submit.rst
- doc/man3/flux_shell_get_info.rst
- src/shell/mustache.c
- src/shell/mustache.h
- src/shell/shell.c
- src/shell/shell.h
- src/shell/test/mustache.c
- t/Makefile.am
- t/t2604-job-shell-affinity.t
- t/t2620-job-shell-mustache.t
This PR adds new mustache tags specific to tasks and nodes (shell rank, really), formatted as `{{task.*}}` and `{{node.*}}`, with a couple special cases. The node tags use the "rank info" object in the shell to render results, which has been updated with additional items for mustache tag use.
Since there are many more supported tags to document, a new _MUSTACHE TEMPLATES_ section is added to the job submission ccommands' manual pages, pasted here since it contains the set of supported tags:
Submission commands support a simplified version of mustache templates in select options (e.g., `--output`, `--error`, `--dump`), and job commands/arguments. These templates are replaced by job details once available. A mustache template is a tag in double braces, like `{{tag}}`.
The following is a …
> shell: support more mustache tags

- src/bindings/python/flux/util.py
- t/python/t0024-util.py
This PR fixes truncation of strings in output formats that use the `+:` sentinel, when the field width is greater than the minimum precision (e.g. `+:{field:10.10}` and the maximum width > 10)
> fix possible truncation of strings with "expandable" output fields

- src/cmd/flux-hostlist.py
- t/t2814-hostlist-cmd.t
`flux hostlist` uses the `avail` resource set int the `resource_status` response, but this resource set includes offline resources and `flux hostlist` is documented to exclude those from `flux hostlist avail`.
Subtract the `offline` resource set from `avail` when reporting the hostlist in `flux resource avail`.
> flux-hostlist: fix `available` hostlist

- src/modules/job-info/guest_watch.c
- src/modules/job-info/watch.c
Problem: If a job is inactive, all data in an eventlog will be returned
as a single response during an eventlog watch.  This is because we know for
a fact that the data should never change after the job is inactive.
If this data, such as job standard output, is very large, this lookup
can be very slow.  In some cases, the use of something like `flux job attach`
can have the apperance of a hang because the standard output response is
taking so long to lookup and return.
Solution:
When a job is inactive and the user wants to watch a job eventlog,
do not respond with all of the data in a single response.  Instead stream
the response back just as if the job were active.
Utilize the FLUX_KVS_WATCH_APPEND_ONCE to ensure the stream ends once all
data in the KVS is streamed.  Update all …
> job-info: stream events even if job is inactive

- src/modules/job-exec/exec.c
- src/shell/info.c
- src/shell/output.c
- src/shell/shell.c
- src/shell/shell.h
- src/shell/task.c
- t/job-exec/dummy.sh
- t/shell/plugins/invalid-args.c
- t/t2602-job-shell.t
The main purpose of this PR is to create the shell task list earlier in initialization so that tasks can be iterated in the `shell.init` callback. This may be convenient in some scenarios where some per-task work is being done and that work may fail. With this change, the failure would occur during `shell.init` and cleanup will be simplified since no tasks have been started yet.
Other fixes that were discovered along the way are included here.
> shell: make shell tasks available in `shell.init` callback

- doc/man1/common/job-env-rules.rst
- src/bindings/python/flux/cli/base.py
- src/shell/Makefile.am
- src/shell/builtins.c
- src/shell/env-expand.c
- t/t2620-job-shell-mustache.t
The job shell expands mustache templates for input/output filenames as well as in command arguments. It would also be useful to support this template expansion in environment variables, but currently this is not supported. It probably isn't efficient to wholesale expand mustache templates in all environment variables, since the common case would be no variables to expand. Also, some environment variables may happen to contain mustache templates which should not be expanded.
This PR introduces a new `env-expand` shell builtin plugin which applies mustache expansion to any environment variables in a new `env-expand` shell options key in jobspec.
On the cli side, the `get_filtered_environment()` function is extended to look for environment variable values specified on the command line and …
> allow mustache templates in job environment variables

- src/shell/output.c
- src/shell/pty.c
This is another standalone PR split off some other work on the job shell. This PR fixes some leaks in the shell `pty` plugin, and also makes the capture of pty output more efficient by encoding `shell.output` plugin callback args with a string `rank` member instead of integer. This allows the shell output plugin to pass the args directly along as an RFC 24 output context object, removing the need to unpack and repack a JSON object.
> shell: minor fixes for shell pty plugin

- doc/man5/flux-config-resource.rst
- src/modules/resource/inventory.c
- src/modules/resource/inventory.h
- src/modules/resource/resource.c
- src/modules/resource/resource.h
- src/modules/resource/topo.c
- src/modules/resource/topo.h
- t/Makefile.am
- t/t2316-resource-rediscover.t
This PR adds an optional `rediscover` key to  the `[resource]` config table which, when true, forces rediscovery of local resources via hwloc, rather than using the job's R and enclosing instance hwloc XML.
This could be used in combination with a prolog option to change the GPU compute partition mode so the child instance can see the newly reconfigured GPUs.
Fixes #6418.
> add `resource.rediscover` config key to force rediscovery of subinstance resources

- src/broker/shutdown.c
- src/common/libflux/flog.c
- src/common/libflux/flog.h
- src/common/libflux/test/log.c
- t/t0009-dmesg.t
This fixes #6545 by falling back to a malloc'd buffer if truncation is detected when handling log messages.
Since the internal fixed buffer size is no longer relevant, the definition of `FLUX_MAX_LOGBUF` is also removed from the public interface. However, I'm fine dropping that commit if it goes too far.
Fixes #6545.
> prevent log message truncation

- doc/man1/flux.rst
- src/cmd/flux.c
- t/t3100-flux-in-flux.t
Since `flux --parent [--parent] COMMAND ARGS...` is supported to connect to parent (grandparent, etc.), it seems neglectful that a method to connect to the top-level or _root_ instance is not also provided. Instead, users have to supply the `--parent` option at least `instance-level` times: an admittedly awkward interface.
This PR adds a `--root` option to `flux(1)` that behaves exactly as if `--parent` had been specified `instance-level` times. If `instance-level` is `0`, this option has no effect (same as `--parent`).
> add `flux --root` option

- doc/man7/flux-environment.rst
- src/broker/broker.c
- src/broker/runat.c
- src/broker/runat.h
- src/broker/test/runat.c
- t/t0014-runlevel.t
This PR adds a `FLUX_ENCLOSING_ID` environment variable as an alternative to the broker `jobid` attribute. If an instance does not have a `jobid` attribute, then `FLUX_ENCLOSING_ID` is unset.
This environment variable can be used to refer to the jobid of the enclosing batch or alloc instance from the initial program or a job within that instance (since it will be inherited by jobs).
> add `FLUX_ENCLOSING_ID` to initial program environment for instances with a `jobid` broker attribute

- t/t0019-tbon-config.t
Problem: The test `tbon.endpoint cannot be set` in t0019-tbon-config.t fails occasionally in ci because the `flux start` command reports it is terminated by SIGPIPE rather than SIGKILL/SIGTERM.
The test is just meant to detect an expected failure of the command, it does not matter how the command fails. Just use `!` to detect failure. Add a note to explain why `test_must_fail` or similar is not used here.
Fixes #6336
> testsuite: fix flaky test in t0019-tbon-config.t

- doc/man1/common/job-dependencies.rst
- src/modules/job-manager/plugins/dependency-after.c
- t/t2271-job-dependency-after.t
This PR updates the `dependency-after` plugin to only allow jobs that entered the RUN state to satisfy any of the `after*` dependencies (which really only affects the `afterany` and `afternotok` types). This changes existing behavior, since pending jobs that are canceled would currently cause `after{any,notok}` dependent jobs to be released. This probably isn't what users want though, and it fixes the use case described in #6555, so it is probably the right approach.
> ensure only jobs that entered the RUN state can satisfy `--dependency=afterany|afternotok`

- doc/man1/common/job-dependencies.rst
- doc/man7/flux-jobtap-plugins.rst
- doc/test/spell.en.pws
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/dependency-after.c
- t/t2271-job-dependency-after.t
This PR adds support for an `afterexc` dependency scheme as suggested in #6564.
This is similar to `afternotok`, but the dependency is only satisfied if a fatal job exception was the event the caused the job to transition to the CLENAUP state.
> support `afterexc` dependency scheme

- src/broker/broker.c
- t/t0001-basic.t
This PR fixes #6560 by delaying initialization of the mentioned attributes until after bootstrap. Then the `jobid` attribute instead of `FLUX_JOB_ID` is used since this more correctly indicates if the current instance is a job or not.
Fixes #6560
> broker: ensure `parent-uri` and `parent-kvs-namespace` are only set for jobs

- src/modules/kvs/kvs.c
- t/t1001-kvs-internals.t
Problem: In the future we would like to put a cap on the maximum number
of operations in a transaction.  However, we do not have any stat tracking
of operations in a transaction.
Add transaction stats for commits and fences in the kvs module.
---
This is really a "prep" for #6125.  I decided to split out the stats for commits & fences, since they are quite different.  For example, if every process in an job did a fenced KVS transaction with a single op, this scales up with the size of cluster.  So we want to count that differently than each op individually.
Note that I could have done "stats per namespace", but that wasn't really the information that we want.  We mostly want to know what is the average and what is the max.  So I did it "globally" vs per namespace.
> kvs: add transaction stats

- src/broker/log.c
Problem: Flux broker log timestamps do not contain the year. This makes it difficult for users to determine when an error or other log message occurred in historical job output files.
Add the year to log timestamps emitted by the broker.
Fixes #6569
> broker: add year to log timestamps

- doc/man3/flux_open.rst
- src/bindings/python/flux/core/handle.py
- src/common/libflux/handle.c
- t/t3100-flux-in-flux.t
This PR adds support for path-like shorthand arguments to `flux_open(3)` and `flux_open_ex(3)` to refer easily to ancestor Flux instances using a familiar filesystem idiom. The string ".." refers to the parent, "../.." its parent, and so on. "/" can be used to refer directly to the root instance, and for completeness "." indicates the current instance (and is therefore ignored as a path element). It is not an error to specify ".." at the root, so specifying more ".." elements than parents just returns a handle to the root instance.
I did my best in the documentation, but feel free to make suggestions.
> libflux: support ancestor paths as alternative to URI in `flux_open(3)` and `flux_open_ex(3)`

- doc/man1/flux-uri.rst
- src/bindings/python/flux/uri/resolvers/jobid.py
- src/bindings/python/flux/uri/uri.py
- t/python/t0025-uri.py
- t/t2802-uri-cmd.t
This PR adds support for path-like expressions in the `jobid` URI resolver. Notably, `/`  now refers to the root instance, `..` refers to the parent of the current instance, and for completeness `.` indicates the current instance. These special targets can be combined with a slash as expected, e.g. `../..` refers to the parent of the current instance's parent, and `/f1234` would refer directly to job `f1234` in the root instance, and so on.
This gives users of `flux-uri(1)`, the `FluxURIResolver` class, and the internal `uri_resolve()` function (`flux proxy`, `flux top` and `flux shutdown`) an easy way to refer to the root instance or parent instances from within a batch/alloc job.
I've made this PR a WIP because other folks may not agree with the approach. 
One other idea I had was to …
> python: support relative and absolute path-like targets in jobid URI resolver

- src/modules/job-exec/exec.c
- t/t2400-job-exec-test.t
Problem: When the job-exec module detects an exec error for a job shell it emits a confusing error message that includes either the path to the job shell or the IMP (if a multiuser job), and only the result of `strerror()` for the errno returned from libsubprocess. When using sdexec, this errno is always `ENOENT`, resulting in a confusing error message that seems to indicate that `flux-imp` was not found.
It is unhelpful to include `argv[0]` in this error message. It will always be the job shell or the IMP and we all know it. Drop this from the log message.
Also, sdexec will provide extra information in the subprocess error string available from `flux_subprocess_fail_error (p)`. Log this instead of `strerror (errno)`.
Fixes #6568
> job-exec: fix confusing "job shell exec error" log message

- src/shell/rcalc.c
- t/shell/input/out-of-order-ranks.json
- t/shell/output/out-of-order-ranks.10.expected
This PR should fix #6582. The rcalc code in the shell currently assigns shell ranks based on the order broker ranks appear in `R_lite` in the job's R. This breaks an assumption elsewhere that rcalc derived shell ranks match the order of broker ranks and the R nodelist.
This PR simply sorts the rcalc->ranks array and reassigns shell rank ids if necessary.
A test is added to ensure out of order ranks in `R_lite` still produce the expected task layout and rank assignment.
> shell: fix incorrect assignment of shell rank ids when broker ranks appear unordered in R

- src/cmd/builtin/overlay.c
This PR replaces the synchronous RPCs used in `flux overlay errors` with asynchronous. This improves responsiveness on large clusters, e.g. on elcap:
before:
```
$ time flux overlay errors >/dev/null
real	0m19.254s
user	0m0.297s
sys	0m0.335s
```
after:
```
$ time src/cmd/flux overlay errors >/dev/null
real	0m1.599s
user	0m0.158s
sys	0m0.214s
```
> improve scalability of `flux overlay errors`

- src/modules/job-manager/housekeeping.c
- t/t2226-housekeeping.t
Problem: as noted in #6596, when housekeeping is reconfigured, it retains the old value of `release-after` unless the key is explicitly set.
And the only way to disable partial release is to not set it.
This fixes the config callback so that release-after is set to the default if not mentioned.
> fix housekeeping reconfiguration problem

- src/common/libkvs/kvs_txn_compact.c
- src/modules/kvs/kvs.c
- src/modules/kvs/test/treq.c
- src/modules/kvs/treq.c
- src/modules/kvs/treq.h
With the removal of KVS fence support in #6592, a large amount of the transaction request ("treq") API is no longer needed.  Remove that code and code that uses it.
As a side note, you may notice the "treq" API is now very simple.  Here's the internal structs
```
struct treq_mgr {
zhash_t *transactions;
};
struct treq {
char *name;
const flux_msg_t *request;
int flags;
};
```
So I hope I can "squash" this into the kvsroot/kvstxn API, but that is for a follow up PR.  This PR is just for the "obvious" removal of dead code.
> kvs: remove unused internal transaction request API code

- doc/man1/flux.rst
- doc/man7/flux-environment.rst
- doc/python/basics.rst
- src/cmd/builtin.h
- src/cmd/builtin/env.c
- src/cmd/builtin/python.c
- src/cmd/flux.c
- src/cmd/py-runner.py
- t/sharness.d/01-setup.sh
- t/t1102-cmddriver.t
This PR attempts to fix #6594 while preserving a bit of backwards compatibility and ensuring that Python subcommands get a `sys.path` that will load the correct version of the Flux Python bindings. The steps taken to accomplish this were the following:
- save the current `PYTHONPATH` before executing the `py-runner.py` Python subcommand wrapper so that `PYTHONPATH` can be modified before running the wrapper. The wrapper script then reestablishes the original `PYTHONPATH` after `sys.path` is internally set up correctly. This is necessary so that `py-runner.py` imports the correct `_flux` cffi modules, from which it derives other necessary paths.
- Only modify `PYTHONPATH` in `flux env` and `flux python` (in addition to the case above). Thus, `PYTHONPATH` is no longer modified in the …
> do not export `PYTHONPATH` by default in Flux commands

- doc/man1/flux-resource.rst
- src/cmd/flux-resource.py
- src/modules/resource/monitor.c
- src/modules/resource/reslog.c
- src/modules/resource/reslog.h
- src/modules/resource/resource.c
- src/modules/resource/upgrade.c
- t/Makefile.am
- t/t2355-resource-journal.t
This adds a resource journal streaming RPC similar the one offered by the job manager.  Just a first cut at this point.
This doesn't change what's posted to the persistent `resource.eventlog` in the KVS but does add one new event called `restart` that's only for journal consumption.  It provides a baseline for mapping execution targets to hostnames in the current instance, and sets the initial `online` set after a restart.
Unlike the job manager journal, this doesn't have as much volume to deal with so no options for event filtering or skipping historical data are provided as yet.
`flux resource eventlog` can be used to dump and optionally follow this log.  This is not currently polished at all - it just dumps the events in JSON form, one per line.
For more detail on what's in this log …
> add resource journal

- src/cmd/job/eventlog.c
- t/t2230-job-info-lookup.t
While working on something else I discovered that `flux job eventlog -HL ...` wasn't forcing color on like it should. This is because `-H, --human` forces `color = auto`, overwriting the user's command line choice.
`auto` is already the default. Stop doing that.
Add a test.
> flux-job: do not override `-L, --color` when `-H, --human` is used in `eventlog` and `wait-event` subcommands

- .github/workflows/main.yml
- src/test/docker/README.md
- src/test/generate-matrix.py
- t/t0016-cron-faketime.t
This is related to flux-framework/flux-sched#1328. The problem over there started because of a single-arch push to the alpine tag, which I'm guessing was a small mistake in a buildx command.  In investigating that, I realized our documented commands don't work, so this fixes that.  Also this includes commits to fix an issue in the docker entrypoint script, and port over the arm64 runner changes developed in the above sched PR.
NOTE: the last commit in here is mainly there so we can test the arm64 runners before merging anything.  If it works well, we might want to run some of the tests on arm all the time, or at least _run the tests after the builds on merge_.  Either way, we need to resolve that before this can be considered ready to merge.
> arm64 Docker cleanup

- src/test/checks_run.sh
Problem: Unit tests are no longer being run as part of the coverage ci build after 69c1691b6a5f0f1e7ee8d66a152ef22059dc6a1a replaced `make check-prep` with `make check TESTS=`. This is because the former actually ran all unit tests while the latter does not.
Ensure unit tests are executed during the coverage build by adding
(cd src && make check)
to the set of commands run during coverage.
> ci: ensure unit tests are run during coverage

- src/modules/kvs/kvs.c
- src/modules/kvs/kvs_wait_version.c
- src/modules/kvs/kvsroot.c
- src/modules/kvs/kvstxn.c
- src/modules/kvs/lookup.c
- src/modules/kvs/test/cache.c
- src/modules/kvs/test/kvstxn.c
- src/modules/kvs/test/lookup.c
- src/modules/kvs/test/waitqueue.c
- src/modules/kvs/waitqueue.c
- src/modules/kvs/waitqueue.h
Built on top of #6604, just some misc cleanups.
> kvs: misc cleanups

- doc/man1/flux-resource.rst
- doc/test/spell.en.pws
- etc/completions/flux.pre
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/abc/__init__.py
- src/bindings/python/flux/abc/journal.py
- src/bindings/python/flux/eventlog.py
- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/job/journal.py
- src/bindings/python/flux/resource/__init__.py
- src/bindings/python/flux/resource/journal.py
- src/cmd/flux-resource.py
- t/Makefile.am
- t/python/t0032-resource-journal.py
- t/python/t0033-eventlog-formatter.py
- t/t2355-resource-journal.t
The main purpose of this PR is to add the Python `ResourceJournalConsumer` class, which mimics the existing job manager `JournalConsumer` class. In fact, most of the original `JournalConsumer` class implementation is moved to an abstract `JournalConsumerBase` class, then both the job manager `JournalConsumer` and `ResourceJournalConsumer` classes inherit from that.
In addition, the `flux resource eventlog` utility is modified to have similar options to the rest of the `eventlog` utilities in Flux (`--format`, `--time-format`, `--color`, `--human`)using a new `EventLogFormatter` class  and the newly added `ResourceJournalConsumer` class.
> add `ResourceJournalConsumer` and `EventLogFormatter` classes and use them to standardize `flux resource eventlog` 

- src/modules/kvs/kvs.c
- src/modules/kvs/kvstxn.c
- src/modules/kvs/kvstxn.h
- src/modules/kvs/test/kvstxn.c
- t/t1001-kvs-internals.t
- t/t1005-kvs-security.t
Problem: KVS stats clearing code was added very early on in KVS prototyping for testing.  It is basically not used anymore.  If we
want to test something that requires a "clean" slate for the KVS, we can just start a new instance and test with that.
Solution: Remove all KVS stats clearing code.  Remove all associated tests.
Fixes #6607
> kvs: remove stats clearing

- doc/man1/flux-kvs.rst
- etc/completions/flux.pre
- src/bindings/python/flux/kvs.py
- src/cmd/flux-kvs.c
- src/common/libkvs/kvs.c
- src/common/libkvs/kvs.h
- src/modules/kvs/kvs.c
- t/issues/t1760-kvs-use-after-free.sh
- t/kvs/issue1760.c
- t/t1000-kvs.t
- t/t1005-kvs-security.t
Problem: KVS dropcache code was added very early on in KVS prototyping for testing.  It is basically not used anymore.  If we want to test something that requires a "clean" slate for the KVS, we can just start a new instance and test with that.
Solution: Remove all KVS dropcache code.  Remove all associated tests.  Update one regression test to be accomplished through two instances rather than one to emulate an emptying of the cache.
Fixes #6608
> kvs: remove dropcache

- src/cmd/flux-resource.py
- t/t2355-resource-journal.t
This PR restores the functionality of `flux resource eventlog -F, --folow`, which was dropped as part of #6614.
> Restore `flux resource eventlog -F, --follow` functionality

- doc/man5/flux-config-exec.rst
- doc/test/spell.en.pws
This PR fixes #6606 by adding the missing config keys, defaults, and key types related to job termination. The suggested `JOB TERMINATION ` section is added as well.
> doc: expand job termination documentation in `flux-config-exec(5)`

- src/common/libsubprocess/bulk-exec.c
- src/common/libsubprocess/bulk-exec.h
- src/common/libsubprocess/test/bulk-exec.c
This tidies up some minor stuff in `bulk-exec.[ch]` and its test program.  Purely cosmetic.
> libsubprocess: cosmetic cleanup

- src/bindings/python/flux/util.py
- src/cmd/flux-resource.py
- t/python/t0024-util.py
- t/t2354-resource-status.t
This PR fixes #6625. Expandable width fields (those with the `+:` or `?+:` prefix sentinel) are passed to the `Deduplicator` class before the final maximum width is known, so comparison only occurs up to the _minimum_ width. This was causing drain reasons that differ past the 30 character minimum width to be incorrectly combined.
The fix here strips the field widths from expandable fields in the `Deduplicator` so that the entire field is compared.
> fix incorrect combination of lines in `flux resource status` for expandable fields that differ past the minimum width

- src/cmd/builtin/version.c
Problem: The hwloc version reported by `flux version` is the build time libhwloc API version, not the actual libhwloc version. This can cause confusion for users that are expecting this string to report the library version.
Hint that the HWLOC version reported is an API version by changing the string to `hwloc.api`.
Fixes #6637
> flux-version: report hwloc.api=x.y.z instead of hwloc=x.y.z

- doc/guide/glossary.rst
- doc/test/spell.en.pws
Problem: when thinking about grow and shrink, I have to keep looking
up these terms of art: fixed, moldable, malleable, evolving.
Add them to the docs glossary with a citation of the original paper in a footnote.
> doc: add job classifications to glossary

- doc/man1/flux-jobs.rst
- src/bindings/python/flux/util.py
- src/cmd/flux-jobs.py
- t/Makefile.am
- t/t2800-jobs-cmd-multiuser.t
Problem: The --include option is predominantly used for finding jobs on specific hosts.  This implies that the -A option is set (i.e.
filter on all user jobs) but it is currently not.  This can be confusing to users wondering why --include isn't finding any jobs running on specific hosts.
Solution: If the user did not specify filtering on a specific user with --user, then assume all user jobs (i.e. -A or --user=all) will be checked when --include is specified.
---- 
side note, the 1 tricky part was how to tell if the user specified `--user=X` on the command line so we didn't assume "-A" when `--include` was specified.  I setup a new filter action that sets a argparse flag "filtereduser".  There were probably other ways of doing this, but went with this approach.
> flux-jobs: filter against all users with --include

- doc/man1/flux-resource.rst
- src/cmd/flux-resource.py
- src/modules/resource/drain.c
- t/t2311-resource-drain.t
- t/t2355-resource-journal.t
This PR adds support for an undrain reason. Currently there is not a utility to display the undrain reason, it is just entered into the resource eventlog. Therefore, to make the undrain reason a bit more useful, a new `-i, --include=TARGETS` option is added to `flux resource eventlog` so admins can easily see the "history" of a node or set of nodes. (Actually, this could be moved to  a separate PR if preferred.)
Fixes #6599
> add support for undrain reason

- doc/guide/admin.rst
- doc/man7/flux-broker-attributes.rst
- etc/flux.service.in
- src/broker/state_machine.c
- t/t0025-broker-state-machine.t
Problem: The `broker.quorum-timeout` and `broker.shutdown-timeout` just control the timing of warning messages, but their names imply otherwise.  Documentation is wrong for the former and missing for the latter.
Rename these to `broker.quorum-warn` and `broker.shutdown-warn`, respectively, and update documentation and tests.
> rename broker quorum and shutdown warn period attributes

- t/t0013-config-file.t
Problem: on systems where a non-flux libpmi is loaded first, and in some of our CI systems, t0013's test of unknown tbon.topo schemes fails with SIGKILL.
Force the test to run as singletons so libpmi is not used. Fixes #6655
> testsuite: fix flaky test for handling of invalid `tbon.topo`

- src/common/libsubprocess/server.c
Problem: the subprocess server ignores failure of `cmd_set_env()`.
This was introduced by #6661 which was just merged.  Oops!
Fix error path.
> libsubprocess: fix error path bug

- configure.ac
- debian/control
- doc/man5/flux-config-exec.rst
- src/common/libsdexec/start.c
- src/common/libsdexec/start.h
- src/common/libsdexec/test/start.c
- src/modules/job-exec/exec.c
- src/modules/job-exec/exec_config.c
- src/modules/job-exec/exec_config.h
- src/modules/sdexec/sdexec.c
- src/test/docker/docker-run-checks.sh
- t/t2409-sdexec.t
Problem: in a system instance using sdexec, jobs may remain in R state when the shell exits with unkillable processes.
This is because the IMP doesn't exit until the unit cgroup is empty, and the IMP must exit for sdexec to collect the shell's exit status.
This PR, in conjunction with flux-framework/flux-security#201, arranges for the unit to enter deactivating state once the shell exits.  An sdexec timeout begins at that point.  If after a configurable period, the unit has not stopped, SIGUSR1 (IMP proxy for SIGKILL) is sent to the unit.  If after another period the unit still has not stopped, it is abandoned and the subprocess protocol is terminated so  the job can advance and release resources.
The abandoned unit remains in deactivating state indefinitely, and can be picked up by the …
> sdexec: add stop timeout to handle unkillable processes

- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog-per-rank.t
This PR adds a missing exception (non  fatal) to the job eventlog on epilog failure.
> raise non-fatal exception on epilog failure

- doc/man1/flux-hostlist.rst
- src/cmd/flux-hostlist.py
- t/t2814-hostlist-cmd.t
This simply adds a `-F, --find=HOSTS` option to `flux hostlist`, which allows getting the index of one or more hosts in the target hostlist.
> flux-hostlist: add `-F, --find=HOSTS` option

- configure.ac
- src/modules/sdexec/sdexec.c
- t/sharness.d/flux-sharness.sh
- t/t2409-sdexec.t
- t/t2410-sdexec-memlimit.t
- t/t2411-sdexec-job.t
This PR relaxes the flux-security version check from v0.14.0 back to v0.13.0 since v0.14.0 is only required for the sdexec module when used to launch jobs in a system instance.
A test is added to the sdexec module to abort if a sufficient flux-security version isn't found at runtime, and a version check added to affected tests.
This allows flux-core to continue to be built on TOSS systems with flux-security v0.13.0 installed. We'll probably have to run with this version for a month at least, and it is nice to be able to build test versions of flux `--with-flux-security`.
Fixes #6672
> configure: relax flux-security version check

- etc/rc1
- etc/rc3
- src/common/libsdexec/list.c
- src/common/libsdexec/list.h
- src/common/libsdexec/property.c
- src/common/libsdexec/property.h
- src/common/libsdexec/test/list.c
- src/common/libsdexec/test/property.c
- src/modules/Makefile.am
- src/modules/resource/monitor.c
- src/modules/resource/monitor.h
- src/modules/resource/resource.c
- src/modules/resource/resource.h
- src/modules/sdbus/connect.c
- src/modules/sdbus/connect.h
- src/modules/sdbus/main.c
- src/modules/sdbus/sdbus.c
- src/modules/sdbus/sdbus.h
- src/modules/sdbus/subscribe.c
- src/modules/sdexec/sdexec.c
- src/modules/sdmon/sdmon.c
- t/Makefile.am
- t/t2407-sdbus.t
- t/t2412-sdmon.t
- t/t2413-sdmon-resource.t
Problem: after a broker restart, "stuck" housekeeping, epilog, prolog, or job shell tasks might still be running, but flux is unaware and new work may be scheduled there even though there might be a problem, or those tasks might be holding on to resources.
When those things are run under systemd, we have the machinery for finding them and tracking them readily at hand. 
This PR does the following
- modifies `sdbus` so it can be loaded twice, once for user and once for system systemd instances
- add a `sdmon` monitoring module that tracks running flux units on both busses
- have `sdmon` join a `sdmon.idle` broker group at startup, after it has verified that no units are running
- modify the resource module so it monitors `sdmon.idle` instead of  `broker.online` when configured to use …
> avoid scheduling jobs on compute nodes that are not cleaned up

- doc/man7/flux-environment.rst
- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog-per-rank.t
As noted in #6668 it would be useful to supply the job prolog and epilog with enough information for these scripts to determine on what node of the job they're running. 
This PR adds a `FLUX_JOB_RANKS` environment variable for this purpose. While there's no flux utility for manipulating idsets, `FLUX_JOB_RANKS` can be used along with the `hostlist` attribute to get the job hostlist, from which the script can test if it is running on a specific rank. (I plan to add a `-F, --find=HOST` option to `flux hostlist` soon to make this a bit more useful.
> add `FLUX_JOB_RANKS` environment variable to prolog and epilog

- doc/man5/flux-config-job-manager.rst
- src/modules/job-manager/plugins/perilog.c
- t/t2274-manager-perilog-per-rank.t
This PR adds a probable fix for #6644 (epilog doesn't time out), plus some other bits of cleanup.
> fix prolog/epilog timeout handling

- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/job/Jobspec.py
- t/t2712-python-cli-alloc.t
Problem: When submitting a job through the command line, a shell option `-o KEY[=VAL]` is not required to have a value. If one is not provided, then `attributes.system.shell.KEY` is set to 1. If a user later provides a sub-key of this shell option, such as `-o KEY.foo=bar`, the error message returned by Python is not particularly helpful.
Wrap `set_treedict()` in a try/except where user input might provide an invalid key and raise a useful error message.
Fixes #6678
> improve error message on invalid formatting of shell options

- src/cmd/flux-queue.py
- t/t2240-queue-cmd.t
Problem: The default behavior of `flux queue start|stop` to apply to all queues when named queues are configured is confusing and potentially dangerous.
Issue an error instead of a warning when this is the case.
If there are no configured queues, then `flux queue start` and `flux queue stop` will still work as expected.
Update tests.
Fixes #6674
I'm going to submit a separate PR that will further change `flux queue start|stop` to take one more queues in the free arguments (and move the stop "reason" to a `-m, --message` option). Since this is a breaking change I figured it should be considered separately.
> flux-queue: do not default to --all with configured queues

- src/modules/resource/monitor.c
- t/t2317-resource-shrink.t
This PR fixes #6675 and adds a set of tests to ensure torpid/lively events don't cause resource removal (shrink).
Thanks for finding this one @garlick!
> resource: only mark nodes lost that transition from `online` to `offline` 

- doc/Makefile.am
- doc/man5/flux-config-heartbeat.rst
- doc/manpages.py
- etc/rc1
- etc/rc3
- src/broker/overlay.c
- src/modules/heartbeat/heartbeat.c
- t/Makefile.am
- t/rc/rc1-job
- t/rc/rc1-kvs
- t/rc/rc3-job
- t/rc/rc3-kvs
- t/t1107-heartbeat.t
- t/t3310-system-heartbeat.t
As discussed in #6626, this adds a timeout option to the heartbeat module.
- heartbeat is loaded on all ranks
- heartbeat on leader rank publishes heartbeats, as before
- heartbeat on follower ranks subscribes to heartbeats
- if a heartbeat does not arrive within a configurable timeout, follower logs a LOG_CRIT message and calls `_exit(1)`.
- the timeout value and whether to merely log or log+exit is configurable
My initial inclination was to just log (no exit) on timeout by default, but I wasn't sure this would get used if we didn't enable it by default, so in the first proposal it is enabled, the default is to log+exit after a 5m timeout.  I'm happy to change that if it seems inappropriate.  Since it is enabled by default, it applies to all instances including user allocations on el cap …
> heartbeat: add optional timeout

- .github/workflows/main.yml
Problem: codecov-action released v5.4.0 on 2025-02-26, but flux-core is still on v4.
Upgrade the version.
> github: upgrade codecov-action to v5

- src/common/libjob/jj.c
- src/modules/job-list/test/job_data.c
- src/shell/info.c
- src/shell/jobspec.c
- src/shell/test/jobspec.c
- t/t0022-jj-reader.t
- t/t2608-job-shell-log.t
Problem: version checks in libjob and shell trigger fatal errors if jobspec `version != 1` but this interferes with implementing further features of canonical jobspec and (IMHO) should be the remit of the validator.
The version checks are changed to issue warnings about unsupported jobspec versions but otherwise allow execution to continue.
This is separated off from #6632 (with a bit of tweaking/polishing) to hopefully create a more digestible, standalone PR.
> Remove version check from libjob and change to pass with warning in shell

- src/modules/sdmon/sdmon.c
- t/t2408-sdbus-recovery.t
- t/t2412-sdmon.t
Problem: the sdmon module exits if sdbus ever loses its d-bus connection
`sdbus` was designed to support this case and returns EAGAIN when a user should not treat the RPC failure as fatal.  Interpret this error in `sdmon` and reset/re-establish the monitor connection when this error is received.
You might wonder why sdmon doesn't just hide this from users.  It's because events may be lost, so  for correctness, users like sdmon must start over (in this case, establish signal subscription, fetch current unit status, then monitor the subscription).
> sdmon: reconnect when bus is lost

- src/modules/kvs-watch/kvs-watch.c
- src/modules/kvs/kvs.c
Per discussion in #6690 and #6694.  It's a nice job throughput bump.  
Before
```
Running throughput.py 2048 jobs
throughput:     147.0 job/s (script: 142.6 job/s)
Total of 14 seconds
Running throughput.py 4096 jobs
throughput:     131.3 job/s (script: 129.9 job/s)
Total of 32 seconds
Running throughput.py 8192 jobs
throughput:     67.5 job/s (script:  11.6 job/s)
Total of 703 seconds
Running throughput.py 16384 jobs
throughput:     33.3 job/s (script:   6.7 job/s)
Total of 2456 seconds
```
After
```
Running throughput.py 2048 jobs
throughput:     196.4 job/s (script: 191.9 job/s)
Total of 11 seconds for everything
Running throughput.py 4096 jobs
throughput:     169.8 job/s (script: 168.0 job/s)
Total of 25 seconds for everything
Running throughput.py 8192 jobs
throughput:     173.1 job/s …
```
> kvs-watch: subscribe/unsubscribe to events asynchronously

- src/bindings/python/flux/job/event.py
- src/bindings/python/flux/job/executor.py
- t/python/t0023-executor.py
Problem: as reported in #6698, sometimes the `submit_get_id` function can return errors, but the FluxExecutor has no handling for this.
Add exception handling, and for `get_event` as well for safety.
> python: make FluxExecutor catch submission errors

- doc/man1/flux-queue.rst
- src/cmd/flux-queue.py
- t/t2202-job-manager.t
- t/t2219-job-manager-restart.t
- t/t2240-queue-cmd.t
- t/t2241-queue-cmd-list.t
- t/t2804-uptime-cmd.t
- t/t3100-flux-in-flux.t
This PR reworks the argument handling in many `flux queue` subcommands so that the target queue name is given as the first non-option parameter (aka free arguments), since this is probably what most users expect. The `-q, --queue=NAME` options are still supported, but are now hidden and undocumented and could be deprecated in a future release.
The "reason" in `flux queue disable` is now optional, and a new `-m, --message=REASON` option is provided for both `flux queue disable` and `flux queue stop` for specifying the reason now that it is not specified in the free arguments. This should allow old usage to immediately fail with "No such queue" if someone uses the old method `flux queue stop -q batch reason` since queue "reason" won't likely exist.
We should get @kkier and @ryanday36 to …
> accept target queue as non-option parameter in most `flux queue` subcommands

- src/modules/kvs-watch/kvs-watch.c
Per #6690 and #6695, there are two loops in the cancellation path of `kvs-watch`, one that iterates over all namespaces and one over all watchers within a namespace.
This iteration can degrade job throughput when there are a large number of jobs, especially when users may be monitoring jobs through various interfaces, as those interfaces large "watch" the eventlogs.
To improve performance, support a index that maps rpc "matchtags" + uuids to A) the namespace of the watcher and B) the watcher within that namespace.  This allows watch cancellations to go a lot faster.
> kvs-watch: index watchers to avoid search iterations

- src/common/libsubprocess/bulk-exec.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/test/subprocess.c
- src/common/libsubprocess/test/test_fork_sleep.c
This PR fixes the main issue described in #6712. In this case, a child forked from the job shell kept the subprocess "active" (waiting for stdio to close) after the shell was sent SIGTERM (the process was inadvertently ignoring SIGTERM). When the job exec module attempted to SIGKILL, this was a noop since bulk-exec and libsubprocess do not allow sending a signal to a subprocess that has exited.
Fix the issue by allowing signals to be sent to any active subprocess if that subprocess was spawned in a process group.
> fix failure to signal a process group after the process group leader exits

- doc/man1/flux-shell.rst
- src/bindings/python/flux/job/Jobspec.py
- t/issues/t4583-free-range-test.sh
- t/t2317-resource-shrink.t
- t/t2712-python-cli-alloc.t
- t/t2714-python-cli-batch.t
This PR modifies `flux.job.Jobspec.from_nest_command()` to set the shell option `exit-timeout` to `none` by default, the main effect of which is to disable the exit-timeout for `flux batch` and `flux alloc`.  Tests and documentation are updated.
The explanation for this change is documented in #6304.
> set `exit-timeout=none` by default in `flux alloc` and `flux batch`

- src/shell/signals.c
- t/Makefile.am
- t/shell/plugins/fork.c
- t/t2402-job-exec-dummy.t
- t/t2621-job-shell-plugin-fork.t
This PR adds an atfork handler to the job shell that clears the signal mask and resets signal handlers in the case a shell plugin calls `fork()`. This allows SIGTERM sent by the job execution system to terminate these extra child processes of the shell (unless the plugin installs its own handler to deal with SIGTERM more gracefully)
> shell: clear signal mask and handlers in shell for plugins that call `fork(2)`

- src/modules/job-info/guest_watch.c
- src/modules/job-info/guest_watch.h
- src/modules/job-info/job-info.c
- src/modules/job-info/job-info.h
- src/modules/job-info/lookup.c
- src/modules/job-info/lookup.h
- src/modules/job-info/update.c
- src/modules/job-info/update.h
- src/modules/job-info/util.c
- src/modules/job-info/util.h
- src/modules/job-info/watch.c
- src/modules/job-info/watch.h
Problem: In watchers_cancel() and guest_watchers_cancel(), every
watcher is iterated over to try and match a cancellation request.
This can slow down performance when the list grows larger and larger
over time.  For example, when monitoring jobs (i.e. watching
eventlogs of jobs) this can lead to very long lists.
Solution: Create an index that will map request uuids & matchtags
to their respective watchers, which will allow quick lookups for
cancellation requests.
---
With more and more performance fixes up in master, the gap between "master" and my PRs shrinks, we gotta get to 64K jobs to show the big improvement.
Current master
```
Running throughput.py 2048 jobs per iteration, 1 iterations
throughput:     198.6 job/s (script: 192.1 job/s)
1: 11 seconds
Total of 11 seconds for everything …
```
> job-info: index watchers for quick cancels

- src/test/checks-lib.sh
Problem: the checks-lib script has an incorrect `if` statement, leading to errors.
Fix it.
> test: fix checks-lib script

- doc/man7/flux-environment.rst
- src/modules/job-manager/housekeeping.c
- t/t2226-housekeeping.t
This PR addresses #6703 by exporting `FLUX_JOB_RANKS` to housekeeping scripts. Not much more to it than that.
> export `FLUX_JOB_RANKS` to housekeeping scripts

- .typos.toml
- src/bindings/python/flux/Makefile.am
- src/bindings/python/flux/queue.py
- src/bindings/python/flux/resource/list.py
- src/bindings/python/flux/utils/README.md
- src/bindings/python/flux/utils/dataclasses/3.6-notes.txt
- src/bindings/python/flux/utils/dataclasses/LICENSE.txt
- src/bindings/python/flux/utils/dataclasses/MANIFEST.in
- src/bindings/python/flux/utils/dataclasses/README.rst
- src/bindings/python/flux/utils/dataclasses/__init__.py
- src/bindings/python/flux/utils/dataclasses/data-classes.rst
- src/bindings/python/flux/utils/dataclasses/dataclass_tools.py
- src/bindings/python/flux/utils/dataclasses/dataclasses.py
- src/bindings/python/flux/utils/dataclasses/setup.py
- src/bindings/python/flux/utils/dataclasses/test/dataclass_module_1.py
- src/bindings/python/flux/utils/dataclasses/test/dataclass_module_1_str.py
- src/bindings/python/flux/utils/dataclasses/test/dataclass_module_2.py
- src/bindings/python/flux/utils/dataclasses/test/dataclass_module_2_str.py
- src/bindings/python/flux/utils/dataclasses/test/test_dataclasses.py
- src/cmd/flux-queue.py
- t/Makefile.am
- t/python/t0034-queuelist.py
Problem: There's currently no easy way to access Flux queue information from the Python API, and that information is currently distributed between different parts the config, various job-manager RPCs, and resource configuration.
This PR adds a new `flux.queue.QueueList` class which fetches information for all currently configured queues in one go. It then presents as a list of `QueueInfo` objects for each queue, which offer access to status, limits, and even resources counts on a per queue basis. This class is then used to replace similar code in `flux queue list`.
In a follow on PR, `flux queue list` will be extended to allow access to the resource stats.
> python: add `QueueList` class for access to queue config, limits, status and resource counts

- doc/man1/flux-queue.rst
- src/cmd/flux-queue.py
This PR leverages the `resources` attribute of `QueueInfo` in `flux queue list` to support emitting _effective_ queue limits in `flux queue list` as mentioned in #6724. 
Then, headers are added for the other `resources.{all,up,down.free,allocated}.{nnodes,ncores,ngpus}` fields so that these are available in output formats. Because it might be useful, a `nodes` output now shows the states of all nodes in the various queues in `flux queue list`:
```
$ src/cmd/flux queue list -o nodes
QUEUE    EN ST  NODES   NODES:UP NODES:DOWN NODES:ALLOC NODES:FREE
pbatch*   ✔  ✔    972        946         26         911         36
pdebug    ✔  ✔     40         40          0           5         35
pci       ✔  ✔      4          4          0           0          4
pall      ✔  ✗   1144       1118         26 …
```
> support resource counts in `flux queue list` output, display effective limits by default

- doc/man1/flux-job.rst
- src/cmd/job/attach.c
- t/t2500-job-attach.t
It seems like perhaps an oversight that `flux job attach` gets terminated by signals like `SIGTERM`, `SIGHUP`, `SIGALRM` and `SIGUSR[12]` instead of forwarding them to jobs. 
If changes proposed in #6725 and #6729 go into effect, we don't want a `flux job attach` to just exit immediately when a user sends SIGUSR1 to their batch job. Instead, this PR lets `flux job attach` handle the signal and forward it to the job. This is probably the expected behavior for this particular command.
> flux-job: forward some signals to jobs in `flux job attach`

- t/Makefile.am
- t/kvs/loop_append.c
- t/t1012-kvs-checkpoint.t
Problem: There are no tests to ensure that checkpoints work as intended when the broker is killed or it suddenly crashes.
Add some testing in a new t1012-kvs-checkpoint.t test.
Closes #6718
> t: add checkpoint integrity test

- .pre-commit-config.yaml
- src/bindings/python/flux/cli/fortune.py
The pre-commit run in ci recently started complaining that it was using deprecated config with the suggestion to run
```
pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks
```
This PR is the result of that.
Also, a spurious flake8 error starting showing up, so workaround that too with a `# noqa:` comment.
> ci: update pre-commit and fix spurious flake8 error

- src/cmd/flux-queue.py
Problem: A comment about the new QueueLimitsEffectiveRange class has some English typos / grammer issues.
Fix up the comment.
---
Fixing up the typos that were missed in #6726
> flux-queue: correct some comment grammar

- doc/man7/flux-broker-attributes.rst
- doc/test/spell.en.pws
- src/broker/broker.c
- src/broker/runat.c
- src/broker/runat.h
- t/issues/t5105-signal-propagation.sh
This PR addresses #6725 and #6729, which both involve how the broker manages rc2 and associated processes.
The main change here is that rc2 (the broker initial program) is run in the same process group as the broker when the broker is a process group leader. This change addresses #6729 since the job shell uses `killpg(2)`, so signals are delivered to the broker _and_ the initial program/batch script. In case this ends up being a problem for some use cases, the old behavior can be restored by setting the `broker.rc2_pgrp` broker attribute.
#6725 is then addressed by having the broker send `SIGHUP` to its own process group on exit. This is similar to what the kernel would do when a session leader exits to cleanup processes still using a terminal. This effectively terminates any background …
> execute rc2 in same process group as broker and send `SIGHUP` before broker exit

- src/cmd/builtin/proxy.c
- t/t1105-proxy.t
This PR fixes #6737 by having `flux proxy` fall back to `/tmp` with a warning when `TMPDIR` is not a valid directory.
> flux-proxy: fall back to `/tmp` when `TMPDIR` is invalid

- t/issues/t3432-python-sigint.sh
- t/job-exec/imp.sh
- t/kvs/torture.c
- t/t0009-dmesg.t
- t/t0013-config-file.t
- t/t1001-kvs-internals.t
- t/t1004-kvs-namespace.t
- t/t1007-kvs-lookup-watch.t
- t/t1008-kvs-eventlog.t
- t/t1012-kvs-checkpoint.t
- t/t2230-job-info-lookup.t
- t/t2274-manager-perilog-per-rank.t
- t/t2408-sdbus-recovery.t
- t/t2603-job-shell-initrc.t
- t/t2606-job-shell-output-redirection.t
- t/t2612-job-shell-pty.t
- t/t2621-job-shell-plugin-fork.t
- t/t2712-python-cli-alloc.t
- t/t2815-post-job-event.t
- t/test-inception.sh
Problem: The following pattern exists in a number of tests
do-something &&
do-something &&
run_a_process_in_background &
pid=$! &&
...
wait $pid / kill $pid / etc.
This is racy and unsafe.  In bash $! returns the pid of the most
recent backgrounded process, but with the previous line being && chained,
it is possible the backgrounding of the process has not yet occurred and
an incorrect PID is picked up by $!.
Solution:  Remove the && chain for any command before a backgrounded
process.  In one situation, remove the workaround put in place to work
around this.
Fixes #6745
> t: fix potential race in backgrounded processes

- t/t1105-proxy.t
Problem: The test for handling an invalid TMPDIR in flux-proxy contains a race: The batch instance may not have posted the uri memo by the time flux-proxy runs. Not only that, but somehow setting the invalid TMPDIR value was dropped at some point, so the test doesn't even test anything.
Fix the race condition using `flux uri --wait`.
Restore the invalid TMPDIR so the test checks the intended behavior.
> testsuite: fix flux-proxy TMPDIR test

- src/common/libeventlog/eventlogger.c
Problem: If a batch commit fails in the eventlogger the batch is never cleaned up until the eventlogger is destroyed.  It sits on the pending list forever.
Cleanup the batch in eventlogger_batch_error() to reclaim that memory.
Fixes #6754
----
Side note, this was found only via code review.   Also, #6755 is not required to be merged first, as this is independent of that.  However, #6755 will ensure one more case of "batch error" is handled correctly.
> libeventlog: cleanup failed batch in eventlogger

- src/shell/doom.c
Problem: it has been requested that we kindly excise the word "doom" from the exit timeout message because it is "EXTREMELY confusing" [sic].
OK. Rename the doom shell plugin to task-exit so that the log message prefix isn't so distracting.
In case the message was actually unclear for other reasons, add the word "task" before "rank" to make sure we communicate that a task exited and not a broker, shell, or other ranked entity.
Fixes #6749
> task-exit: improve clarity of log message

- etc/Makefile.am
- etc/flux.conf
- etc/kvs-backup.cron
Problem: the kvs and its content storage layer currently have some reliability issues, especially in long running system instances of Flux.
As a stopgap while those issues are being worked, add a nightly KVS dump for the system instance of Flux.  Backups will accumulate in `/var/lib/flux/dump` using the same naming convention as the automatic dumps taken at shutdown.  The existing tmpfiles configuration removes old dump files, keeping storage usage in check.
Fixes #6759
> enable daily backups of system KVS

- src/common/libsubprocess/bulk-exec.c
This PR removes some stray debug `fprintf` calls in bulk-exec, and also prevents calling `flux_future_push()` with a `NULL` future in `bulk_exec_kill()`.
Fixes #6776
> libsubprocess: remove confusing `flux_future_push: Invalid argument` error message in bulk-exec

- src/modules/job-manager/jobtap.c
- src/modules/job-manager/restart.c
- t/Makefile.am
- t/issues/t6773-multiple-dependency-add.sh
This PR addresses the reproducible issues described in #6773 by preventing jobs from being iterated multiple times during job manager restart. 
Also, a commit is added to prevent multiple `dependency-add` events in a job eventlog. This is necessary because dependency plugins are called in the same manner during restart as when the job is submitted. Rather than trying to force dependency plugins to detect this condition, we just make `flux_jobtap_dependency_add(3)` detect existing identical dependencies and prevent the event.
Fixes #6773
> jobtap: fix issues at restart with dependent jobs

- doc/man5/flux-config-exec.rst
This is an alternative to #6788 which just updates the documentation in `flux-config-exec(5)` to match behavior. I feel a bit worried about the extra complexity introduced by the other PR so I think I'll remove it.
> doc: correct description of job termination in flux-config-exec(5)

- doc/man5/flux-config-exec.rst
- src/modules/job-exec/job-exec.c
- t/t2900-job-timelimits.t
Problem: When the job execution system receives a start request for a job with a time limit, it always adjusts the actual job time limit by the difference between the starttime in R and the time at which the start request is received. For jobs that are instances of Flux, this causes a discrepancy between the time at which the execution system will raise a timeout exception and the expiration used by the scheduler in the subinstance. This results in an arbitrary amount of time between when jobs in the instance can no longer run because the resources are expired, and the subinstance itself is finally terminated by the timeout exception.
It is probably unnecessary to provide the grace time in the execution system for the difference between the `alloc` and `start` events for jobs of any …
> job-exec: only adjust timelimit for jobs when start delay exceeds a configurable percent of job duration

- doc/man5/flux-config-job-manager.rst
- src/modules/job-manager/queue.c
- t/t2219-job-manager-restart.t
One more PR to perhaps sneak into this release.
This addresses #6795 in the simplest way possible by adding a config key that, when set, causes any started queues to be stopped with a specific reason message. Admins enabling this config parameter will then need to manually start queues after a Flux restart.
> job-manager: add `stop-queues-on-restart` configuration parameter

- NEWS.md
Release notes for v0.74.0, planned to be tagged today. This assumes #6791 will be merged.
Feel free to push corrections and updates directly.
> NEWS.md: add release notes for v0.74.0

- doc/Makefile.am
- doc/guide/glossary.rst
- doc/guide/workflows.rst
- doc/index.rst
- doc/test/spell.en.pws
Problem: the Flux KVS is a general service that can be used by workflow orchestrators, but its constraints are not well documented.
Add a page to the docs.  This is pretty limited currently, but we can expand on it as time permits.
Sort of fixes #5784
> doc: add workflows page

- src/broker/broker.c
- src/broker/publisher.c
Problem: while thinking about #6806, I found myself confused reading through broker event code.
Add some inline documentation, and correct whitespace  violations.
> broker: document/clean up event publishing code

- t/Makefile.am
- t/t0019-tbon-config.t
This PR adds a couple minor testsuite fixes.
- possible fix/workaround for #6812 
- add a missing test to `Makefile.am`
> testsuite: add one missing test and fix failing test in ci

- doc/Makefile.am
- doc/man1/flux-fsck.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/cmd/Makefile.am
- src/cmd/builtin/dump.c
- src/cmd/builtin/fsck.c
- t/Makefile.am
- t/t2816-fsck-cmd.t
There is no way to check if the data in the content store is valid and doesn't have corruption.  Support a `flux-fsck` tool to check it.
This tool is largely based on `flux-dump`, walking the content store tree and making sure all references are valid and retrievable.
This is very basic start to the `flux-fsck` and it doesn't do much beyond the trivial check.  Future work will include.
A) check different checkpoints (i.e. related to work in #6772)
B) update primary checkpoint if we are "rolling back" to an earlier one
Edit: it's worth noting that this has no dependencies on other recent PRs (#6772, #6775).
> Support new flux-fsck tool to check integrity of content store

- src/bindings/python/flux/kvs.py
This might be a problem other places too.
What renders:
After this PR:
Is this really what we want? RST shoved in our python in-line docs? I'm not sure...
> kvs: add rst format to inline docs

- doc/man1/flux-kvs.rst
- src/cmd/flux-kvs.c
- t/t1010-kvs-commit-sync.t
- t/t2816-fsck-cmd.t
Problem: The only way to perform a sync is through the `flux kvs put` command, which inherently requires the user to
also write data at the same time.  This isn't necessarily always desired.
Support a new `flux kvs sync` command.  It is largely identical to `flux kvs put --sync`, but does not require additional data to be written.
Fixes #6814
> flux-kvs: support sync command

- src/cmd/flux-module.c
- t/t0003-module.t
Problem: The default target for flux module stats points to a RPC
target that no longer exists.
Require a stats target with flux module stats.
Fixes #6636
---
As an aside, the manpage for `flux-module(1)` and the `--help` output already documents this input as required.  So no need to fix those up.
> flux-module: require argument for flux module stats

- doc/man1/flux-jobs.rst
- src/cmd/flux-jobs.py
- t/t2800-jobs-cmd.t
Simple attempt at the issue raised in #6794, all done in `flux-jobs`.
Only interesting oddity is i cheated and used the `no-header` flag to also not output the warning message.  Results in zero need to change any tests in sharness.
> flux-jobs: output message if results truncated

- src/broker/overlay.c
- src/common/libflux/message_route.c
- src/common/libflux/message_route.h
Problem: when the broker distributes event messages to overlay peers, it does a malloc/free per peer as it pushes and pops the peer id onto the message route stack.
This adds a (private) helper function to the message layer to streamline this case, avoiding the dynamic memory allocation.
This might not be worth the extra complexity, so marking WIP for now.
> broker: avoid malloc in event distribution critical path

- src/modules/kvs/kvs.c
- t/Makefile.am
- t/t1013-kvs-initial-rootref.t
Problem: The only way for the KVS to start with a non-default root reference is to read a root reference from the content module's checkpoint service.  There is no way to initialize the KVS with a specific root reference.  Allowing users to select an initial root reference could be useful for debugging and testing, especially when multiple checkpoints exist.
Support a initial-rootref option.
> kvs: support initial-rootref option

- doc/man1/flux-start.rst
- src/broker/Makefile.am
- src/broker/bizcard.c
- src/broker/bizcard.h
- src/broker/boot_config.c
- src/broker/boot_pmi.c
- src/broker/overlay.c
- src/broker/overlay.h
- src/broker/test/bizcard.c
- src/broker/test/overlay.c
- src/cmd/flux-start.c
- t/t0001-basic.t
- t/t0019-tbon-config.t
This allows IPC to be used instead of TCP between brokers when they are co-located on the same node.
Using @grondo's custom taskmap from the description of #6815, this starts a flux instance with several ranks on the first node and the rest on their own nodes:
```
$ flux run -q batch -N4 -n8 --taskmap=manual:"[[0,1,5,1],[1,3,1,1]]" -o pty.interactive flux start
$ flux exec -x 0 --label-io flux getattr tbon.parent-endpoint
5: tcp://[::ffff:192.168.88.246]:45175
6: tcp://[::ffff:192.168.88.246]:45175
7: tcp://[::ffff:192.168.88.246]:45175
2: ipc:///tmp/flux-jWd8Pr/tbon-0
3: ipc:///tmp/flux-jWd8Pr/tbon-0
4: ipc:///tmp/flux-jWd8Pr/tbon-0
1: ipc:///tmp/flux-jWd8Pr/tbon-0
```
WIP because this needs tests and I'm struggling with how that might be done.  Since its EOD I figured I'd get this …
> use local ipc for TBON when brokers are co-located

- src/bindings/python/flux/cli/alloc.py
- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/cli/batch.py
- t/t2714-python-cli-batch.t
This PR is a WIP pending tests. I'm not sure if the solution proposed here is the best we can come up with, but I thought I'd post it now to get feedback.
This PR implements a hidden `--add-brokers=N` option to `flux batch` and `flux alloc` that can be used to force N extra brokers on nodeid 0. This is hidden for now because I'm not sure it is a great long-term approach, but it allows us to give select users a way to supplement their jobs with these extra brokers.
The option should be paired with an appropriate `tbon.topo` such that all critical ranks of the job are placed on node rank 0. The extra ranks are automatically excluded. Users may choose to also exclude or drain rank 0 since it will have more flux-broker processes on it.
Simple example:
```console
$ src/cmd/flux alloc -N4 …
```
> add method to request extra brokers on node 0

- doc/man7/flux-broker-attributes.rst
- doc/test/spell.en.pws
- src/broker/test/topology.c
- src/broker/topology.c
- t/t0019-tbon-config.t
Problem: `kary:0` usefully minimizes critical nodes for batch jobs but may not perform well.
Add a new TBON topology `mincrit[:K]` for defining a 3 level tree where the fanout from leader to routers is K, and the fanout from routers to leaves is dependent on the size.
If K is unspecified, a value is chosen that keeps the fanout to the leaves at or below 1024.  If there are 1025 nodes or less, a flat topology is used.
Example:
```
$ flux start -o,-Stbon.topo=mincrit:2 --test-size=11 flux overlay status
0 system76-pc: full
├─ 1 system76-pc: full
│  ├─ 3 system76-pc: full
│  ├─ 5 system76-pc: full
│  ├─ 7 system76-pc: full
│  └─ 9 system76-pc: full
└─ 2 system76-pc: full
├─ 4 system76-pc: full
├─ 6 system76-pc: full
├─ 8 system76-pc: full
└─ 10 system76-pc: full
```   
Fixes #6807
> broker: add 'mincrit' topology

- doc/man3/flux_future_create.rst
Problem: The documented function prototype for flux_future_set_reactor(3) is incorrect, likely due to a cut and paste error.
Correct the function prototype.
> doc: correct flux_future_set_reactor() prototype

- doc/man1/common/job-dependencies.rst
- src/modules/job-manager/Makefile.am
- src/modules/job-manager/jobtap.c
- src/modules/job-manager/plugins/dependency-singleton.c
- t/Makefile.am
- t/t2277-dependency-singleton.t
This PR adds a very simple implementation of a `singleton` dependency scheme as described in #6804.
In order to support the requirement of "a singleton job is not eligible to run until all jobs of the same userid and job name have become inactive", the plugin has to track a count of _all_ jobs by userid,name pair, even when no singleton jobs are being submitted. In practice, this seems to have little impact on throughput, so perhaps this is ok. Note that, for simplicity, jobs without an explicit name are ignored by the plugin (i.e. first argument does not count as the job name).
Singleton jobs are then placed on a list in submission order and are only released when the count of active jobs with the same userid and job name equal the number of currently held singletons.
> support `singleton` dependency scheme in job submission

- src/cmd/builtin/fsck.c
- t/t2816-fsck-cmd.t
Problem: The values in a valref blobref array are checked synchronously one by one.  This can be quite slow.
Parallelize the valref blobref array verification by making each blobref lookup asynchronous.
> flux-fsck: parallelize valref blobref checks

- README.md
- configure.ac
- scripts/install-deps-macos.sh
- t/README.md
This PR addresses some issues described by @ocaisa in #6835.
We now just go ahead and fail in configure if `luaposix` is not found to avoid confusion.
Also, a couple extra tips re: the testsuite are added to the top-level README.
> require Lua `posix` in `configure` and document some tips for running the testsuite

- scripts/requirements-doc.txt
GitHub dependabot is reporting moderate security vulnerabilities detected with `jinja2 < 3.1.4`, but flux-core has `jinja2<3.1.0` listed in its `requirements-doc.txt` file.
The `requirements-doc.txt` file for flux-core documentation requires `sphinx < 6.0.0`, but we would like to upgrade sphinx to the latest version.
---
This PR drops both the `jinja2` and `sphinx` version requirements from the `requirements-doc.txt` file.
> doc: remove `jinja2<3.1`, `sphinx<6.0.0` requirements

- src/cmd/builtin/fsck.c
- t/t2816-fsck-cmd.t
Problem: An error check inadvertently checks `errno` when it should check the stored errnum in a data structure.  This leads to an invalid error message output.
Fix the error check to ensure the correct error message is output.
Fixes #6860
> flux-fsck: fix error message output

- t/t4000-issues-test-driver.t
Problem: The issues tests in t4000-issues-test-driver.t are run as jobs in a test instance of size=2, but the instance inherits the total number of cores from the system, which means up to 2*ncores issues tests could be run at the same time. On some systems, this causes failures in the tests due to overloading the system.
Switch to the "job" personality of test_under_flux, which will configure the test instance with only 2 fake cores per rank, keeping the parallelism of the tests to 4, which is probably a safe number.
Fixes #6856
> testsuite: reduce parallelism in `t4000-issues-test-driver.t` for test reliability

- src/bindings/python/flux/job/Jobspec.py
- t/python/t0010-job.py
This PR makes a tweak to the behavior of the `Jobspec.getattr` method so that it is consistent with the behavior of `Jobspec.setattr`. That is,  keys that do not start with `user.`, `system.` or `attributes.` default to  `attributes.system.`
> python: unify behavior of `Jobspec` `getattr` and `setattr` methods

- t/t2233-job-info-update.t
Problem: In a test in t2233-job-info-update.t there is a small race possibility.  An update watcher assumes that an update
has "propogated" and that an earlier value of that update cannot be seen.  However, a recent test failure indicates that the earlier
value can be seen.
Solution: Move one of the "waits" earlier in the test to ensure the updated value has fully "propogated".  This ensures later watchers will only get the updated value.
Fixes #6838
> t: fix race in job info update watch test

- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/job/Jobspec.py
- src/bindings/python/flux/util.py
- t/python/t0010-job.py
- t/python/t0024-util.py
This PR adds an `unbuffered` getter and setter property to the Python `Jobspec` class as suggested by @trws in #6858.
based on top of #6874.
> python: add `unbuffered` getter and setter to `Jobspec` class

- src/bindings/python/flux/cli/alloc.py
- src/bindings/python/flux/cli/base.py
- src/bindings/python/flux/cli/batch.py
- src/bindings/python/flux/job/Jobspec.py
- t/python/t0010-job.py
This PR adds some more arguments to the `JobspecV1` factory methods as described in #6833 so that more fully formed jobspec can be instantiated with a single method call.
This PR doesn't go as far as adding _all_ the options offered by the submission CLI commands. However, job parameters that are an annoyance to set after the fact like the environment and cwd are there, as well as output, error, and input paths, etc.
One thing I didn't do was move support for some of the more user-friendly aspects of the CLI into the Python methods. For instance, the `environment` and `rlimits` arguments just take straight mappings, instead the "rule" based expressions supported by the CLI. We could change that, but I wasn't sure if it was necessary in the Python API.
Also, some other missing parameters …
> add more arguments to Python `JobspecV1` factory methods

- src/modules/content-files/content-files.c
- src/modules/content-sqlite/content-sqlite.c
- src/modules/content/checkpoint.c
- t/content/content-helper.sh
- t/t0012-content-sqlite.t
- t/t0018-content-files.t
Problem: In the content backing modules, checkpoints are allowed to take a key.  However, the singular "kvs-primary" key is the
only key used.  Only testing uses alternate keys.  The flexible key makes some future modifications to checkpointing more difficult.
Make "kvs-primary" the only valid key for checkpointing.
> content: remove checkpoint key 

- doc/man3/idset_alloc.rst
- doc/man3/idset_create.rst
- src/common/libidset/idset.c
- src/common/libidset/idset.h
- src/common/libidset/idset_private.h
- src/common/libidset/test/idset.c
Problem: in working on VNI support for flux-coral2, I found it would be handy to have something like `idset_alloc(3)` and `idset_free(3)` to allocate form a configurable VNI pool, except not immediately re-use a VNI after it is freed, in case there are race conditions in VNI cleanup.
This adds a FLUX_IDSET_ALLOC_RR flag to select "round robin" allocation for `idset_alloc(3)`.   If we wanted to we could use this for matchtags, although it does raise the complexity of an allocation from O(1) to O(log(n)) and matchtag handling is pretty well tested at this point.
> idset: add round-robin allocation flag

- doc/man7/flux-environment.rst
- doc/test/spell.en.pws
- src/broker/broker.c
- src/shell/shell.c
- t/t0014-runlevel.t
- t/t3100-flux-in-flux.t
Problem: Flux jobs run in sub-instances do not have a unique ID like slurm's jobid.step.
Add the FLUX_JOB_PATH environment variable to the job environment.  The path consists of job IDs separated by `/` characters, with `/` designating the top level instance.  For example, a job run in a batch job of a system instance might have a FLUX_JOB_PATH of  `/ƒD1oBT5/ƒDCB6RV`.
I hope it is not going too far to put this in the environment of every job.   In #6876 I had proposed just adding a broker attribute and passing it through PMI.  This was simpler and felt more complete.  We can go back to the other plan if there is disagreement on this approach.
> add FLUX_JOB_ID_PATH to the job environment

- src/modules/resource/drain.c
- t/t2311-resource-drain.t
This simple PR adds logging of drain and undrain events to the resource module as requested in #6878.
An open question is probably if the simplistic key=val format of the log message is sufficient for the use case. 
e.g.:
```
2025-06-18T13:18:44.436906-07:00 resource.info[0]: drain idset=0-1 nodelist=tuolumne[1006,1032] overwrite=0 reason=this is a drain reason
2025-06-18T13:18:57.069487-07:00 resource.info[0]: undrain idset=0 nodelist=tuolumne1006 reason=undrain reason 1
2025-06-18T13:19:02.873886-07:00 resource.info[0]: undrain idset=1 nodelist=tuolumne1032 reason=undrain reason 2
```
> resource: log drain/undrain events

- src/broker/broker.c
- t/Makefile.am
- t/t0034-broker-getenv.t
Problem: in nested Flux instances, a shell plugin may need to access environment variable settings for the local broker.
Specifically, a cray-slingshot plugin needs to find inherited CXI services, which may differ on each broker.
Add a new broker RPC: broker.getenv.  A user sends an array of key names and gets back a dict of key/value pairs.  Any environment variables for which getenv(3) returns NULL are omitted from the object.
The RPC is restricted to the instance owner.
> broker: add broker.getenv RPC

- doc/man1/flux-module.rst
- doc/test/spell.en.pws
- src/broker/modhash.c
- src/broker/module.c
- src/cmd/flux-module.c
- t/Makefile.am
- t/module/hang.c
- t/t0003-module.t
This adds an option to remove an ornery module by sending it a `pthread_cancel(3)` instead of politely requesting that it shut down.  That required the addition of a pthread cleanup callback, which triggered a bit of refactoring.
> add flux module remove --cancel option

- src/modules/content-sqlite/content-sqlite.c
- t/Makefile.am
- t/scripts/sqlite-query.py
- t/scripts/sqlite-write.py
- t/t0035-content-sqlite-checkpoints.t
Problem: The content-sqlite backend only stores one checkpoint for each key, overwriting older keys/checkpoints.  If anything
goes wrong with a checkpoint, there is no information stored to allow a recovery from an earlier point in time.
Instead of overwriting checkpoints, store a rolling history of the checkpoints.  Support configuration of the maximum number of checkpoints via a new configuration parameter.  The default maximum number of checkpoints is 100 per key.
Fixes #6629
----
notes:
- for this PR the new tests are in `t0012-content-sqlite-checkpoints.t` b/c I didn't want to create new numbered content-sqlite test files super far away from `t0012-content-sqlite.t` ... but maybe I should.  Or should we do a good re-numbering on tests and shifting everything down.
- you'll notice a …
> content-sqlite: store history of checkpoints

- src/bindings/python/flux/job/Jobspec.py
- t/python/t0010-job.py
As noted in #6890, it is unexpected that the default jobspec environment when not explicitly passing `environment` is empty.
I can't really think of a good reason for this default, and it is easy to fix so let's do that.
This shouldn't break any existing users since setting `jobspec.environment = dict` will still work.
Just in case, we should get a couple reviews of this one.
> set default jobspec jobspec using `os.environ` in `JobspecV1` factory functions

- src/broker/groups.c
- src/cmd/flux-module.c
- t/t0027-broker-groups.t
Problem: while debugging #6909, it might have been handy to be able to look directly at the broker groups memberships, but there is no tool for that.
Just add a `stats-get` handler so `flux module stats groups` can show the group names and membership at the current broker's subtree.  Seeing that a group named `sdmon.online` was missing some ranks may have prompted earlier checking on the state of the  `sdmon` module on the offline nodes.
> make broker groups easier to look at when debugging

- doc/man1/flux-module.rst
- src/broker/broker.c
- src/broker/modhash.c
- src/broker/modhash.h
- src/broker/module.c
- src/broker/module.h
- src/broker/trace.c
- src/cmd/flux-module.c
- t/t3401-module-trace.t
Problem: a module has to be loaded before you can initiate  a trace on it, so early message are missed.
If a module trace request is received with no module name,  trace messages communicated over the broker end of the module  sockets.
This was a bit hasty so I'll mark it WIP until I've had a chance to review it more thoroughly.
> flux-module trace: capture early messages

- src/broker/log.c
Problem: the broker ring buffer implementation is malloc-heavy.
This converts the logging ring buffer from `zlist_t` to a CCAN list so that a list node doesn't need to be allocated each time an entry is appended to the ring.  It also combines two mallocs used to allocate a list entry into one.
This is probably not significant since our log volume is not too crazy, but it was an easy change, so there.
> broker: reduce the number of mallocs in logging path

- src/broker/log.c
Problem: all Flux logs go to the systemd journal (via stderr) at LOG_INFO level, which means they cannot be usefully filtered using the [journalctl(1)](https://www.man7.org/linux/man-pages/man1/journalctl.1.html) `-p` option.
When `log-stderr-mode=local` is selected, use a <level> prefix that can be interpreted by systemd instead of embedding the level name in the log message.  For example:
```
$ flux logger --severity=err help
```
before:
```
logger.err[0]: help
```
after:
```
<3>logger[0]: help
```
Edit: as a bonus, `journalctl` output for flux is now properly colorized by severity.
> broker: preserve log levels in system instance

- src/cmd/builtin/fsck.c
- src/modules/content-files/content-files.c
- src/modules/content-files/filedb.c
- src/modules/content-files/filedb.h
- src/modules/content-sqlite/content-sqlite.c
- t/Makefile.am
- t/content/content_validate.c
- t/kvs/lookup_invalid.c
- t/kvs/setrootevents.c
- t/t0012-content-sqlite.t
- t/t0018-content-files.t
Support a "validate" RPC service in the content backing modules, simply to validate that an blobref hash is valid.  Without it, a "load" has to be used instead, which requires sending over the content data itself.  So it's pretty costly.
Multiple ways to do this of course, but I went with "return empty payload" for validated / success, and ENOENT for "not valid" / "not found".
I elected not to add API functions to `libcontent` and a "forwarder" in the `content` module, as this is only used by `fsck` at the moment.  IMO forwarding through the `content` cache module could suggest that verification within the `content` cache is ok, but that isn't ok.  We only want to validate in the backing module. 
Note, see associated RFC PR: https://github.com/flux-framework/rfc/pull/455
> content-sqlite/files: support validate target

- t/t2712-python-cli-alloc.t
- t/t2802-uri-cmd.t
Problem: Several tests were regularly timing out when doing larger parallel runs of the sharness tests.
Update several timeouts in t2712-python-cli-alloc.t and t2802-uri-cmd.t.
> t: increase test timeouts

- t/t2613-job-shell-batch.t
- t/t3002-pmi.t
Problem: As reported in #6908, some tests fail when `LD_LIBRARY_PATH` is required for proper Flux operation.
In t2613-job-shell-batch.t, update `LD_LIBRARY_PATH` along with other environment variables when modifying "old" jobspec for the tests.
In t3002-pmi.t, prepend to `LD_LIBRARY_PATH` instead of overwriting it.
> testsuite: preserve `LD_LIBRARY_PATH` in some tests

- scripts/fetch-and-build-mpich.sh
- src/test/docker/noble/Dockerfile
In testing some stuff for our upcoming [performance tools and benchmarking tutorial](https://github.com/llnl/benchpark-tutorial) for [HPDC](https://hpdc.sci.utah.edu/2025/workshops.html), I discovered that there are still issues with the Ubuntu Noble Docker image regarding MPICH. The majority of the issue is covered in this [Launchpad bug report](https://bugs.launchpad.net/ubuntu/+source/mpich/+bug/2072338). Long story short, the apt-installed MPICH builds with PMIx support, but still uses the Hydra process manager. This causes issues when trying to run MPI code because Hydra does not provide a PMIx interface.
The Docker image for Ubuntu Noble already tried to work around this by building MPICH from source. However, the image is still installing `libmpich-dev`. This, combined with loader …
> Fix for Ubuntu Noble Docker Image to Prevent PMIx+MPICH Issues

- src/shell/rcalc.c
- t/t2600-job-shell-rcalc.t
Currently `rcalc_distribute()` fails with `ENOSPC` when there are not enough cores given the number of tasks and slot size passed in to the function. However, there are valid cases for this oversubscription, e.g. when options like `--add-brokers` are used when launching a new instance or when a custom taskmap is provided by the user.
This doesn't cause any issues now, but it does affect #6705, because `rcalc_distribute()` is called early with a correct slot size (instead of 1) in this PR. 
This PR modifies `rcalc_distribute()` so it doesn't abort if there are not enough slots available. Instead it repopulates the "alloc info" array and continues, allowing the function to always assign all tasks instead of giving up.
> shell: do not abort early when tasks are oversubscribed to resources

- src/shell/info.c
- src/shell/jobspec.c
- src/shell/jobspec.h
- src/shell/test/jobspec.c
Problem: counts for resources are currently being parsed only from jobspec, but if/once ranges are used then values cannot be determined.
Modify shell init data flow to use the actual allocation from the scheduler in R, if present, to determine resource counts for nodes & cores in `jobspec_parse`.
As a first step, this checks whether a resource set struct was passed to `jobspec_parse`, and otherwise leaves the original codepath unchanged. The slot count must still be parsed from the jobspec regardless, because it is missing from R.
The concept for this is also essentially separated off from #6632, albeit with a fair bit of re-working to keep the changes as minimal as possible. Because `flux-sched` already has basic support for ranges, this PR already allows jobspec with ranges for nodes …
> shell: determine node & core resource counts from R during init

- configure.ac
- src/broker/Makefile.am
- src/broker/broker.c
- src/broker/modhash.c
- src/broker/modhash.h
- src/broker/modservice.c
- src/broker/modservice.h
- src/broker/module.c
- src/broker/module.h
- src/broker/module_dso.c
- src/broker/module_dso.h
- src/broker/module_thread.c
- src/broker/state_machine.c
- src/cmd/flux-module.c
- src/common/libflux/conf.c
- src/common/libflux/conf.h
- src/common/libflux/module.c
- src/common/libflux/module.h
- src/common/libflux/test/conf.c
- src/modules/Makefile.am
- src/modules/connector-local/Makefile.am
- src/modules/connector-local/local.c
- src/modules/content/main.c
- src/modules/sdexec/sdexec.c
- t/t0003-module.t
- t/t1102-cmddriver.t
Last week, I set out to make some headway on adding an option to load broker modules in a separate process address space, but all I ended up accomplishing was some refactoring to disentangle the existing module code.
Regardless of the approach we eventually take for the original goal, I think this refactoring work is probably worth doing.  It was some really old code.
As a bonus, "builtin modules" are implemented, similar to the shell's, and `connector-local` is now compiled in.
> broker: refactor broker module loader and add builtin modules

- doc/man5/flux-config-queues.rst
Problem: the example script included in flux-config-queues(5) will generate a parsing error because the hostlist is not a string. It will additionally error because no resources (cores) are assigned to the created queues. Then, when sched-fluxion-qmanager is reloaded, another error will occur because the "queues" key is unsupported.
Solution: fix the example script in the docs.
> doc: update flux-config-queues(5) with working examples

- doc/man7/flux-broker-attributes.rst
- src/broker/attr.c
- src/broker/attr.h
- src/broker/broker.c
- src/broker/log.c
- t/t0009-dmesg.t
- t/t3401-module-trace.t
Problem: sys admins may want to capture logs from batch  or alloc subinstances.
This adds basic support for copying broker logs to syslog.  For now, this is only configurable with broker attributes.  Two attributes are added:
```
log-syslog-enable=1
log-syslog-level=2
```
The log entries are prefixed with "username@job-path".  Here are a couple of example logs from a test instance and a batch job run within that test instance:
```
Jul 17 17:25:30 system76-pc flux[983068]: garlick@/ job-manager.debug[0]: scheduler: hello +partial-ok
Jul 17 17:25:44 system76-pc flux[983757]: garlick@/ƒ3pBZx4P broker.debug[0]: rmmod barrier
```
Syslog is disabled by default of course.  I was thinking maybe we could add a toml config option that would tell the system instance to enable it for batch/alloc …
> broker: add syslog capability

- doc/guide/debug.rst
- doc/test/spell.en.pws
Problem: mxschmitt/action-tmate@v3 is pretty useful for CI debugging but it's a bit of a pain to remember the details.
Add a link and a tested workflow diff from a recent debug session to the developer debug docs.
> doc: add tmate action to debug notes

- src/modules/kvs/kvs.c
- t/t0090-content-enospc.t
- t/t1010-kvs-commit-sync.t
Problem: When the KVS module is unloaded, a checkpoint of the root
reference is attempted.  However, a content.flush is not done
beforehand.  This could result in an invalid checkpoint reference
as data is not guaranteed to be flushed to the backing store.
Solution: Call content.flush before checkpointing.
Fixes #6237
----
I threw in a few new tests for some extra coverage of FLUX_KVS_SYNC too.
> kvs: call content.flush before checkpoint

- .github/workflows/main.yml
- doc/guide/debug.rst
This PR permanently adds the tmate action to the github workflow. During normal runs, the tmate action is disabled. However, it can easily be enabled by selecting the "Enable debug" flag when re-running jobs.
> ci: add tmate action which can be enabled via debug flag when re-running jobs

- etc/rc1.old
I noticed this one while building RPMs for the latest release. If this gets merged I can just patch the RPM for now. Sorry :facepalm: 
Problem: Commit 87026681211cb175f2998ee00ca4b89691d56f74 moved support for loading crontabs (previously in `etc/rc1.d/02-cron`) to modprobe's rc1.py. However, commit 71efe36762587d312ccec886ef7117ee247ac209, restored the old rc1 as rc1.old without also bringing back suport for crontabs.
Copy the old contents of `02-cron` directly into rc1.old to preserve the default crontab support.
> etc: restore dropped support for `cron.directory` in rc1

- .github/workflows/main.yml
- src/test/docker-manifest.py
Problem: The set of images for which docker manifests are generated is hand edited in the workflows file and so can easily become outdated.
Add a script to run the docker manifest commands based on current output from `src/test/generate-matrix.py`, which contains the exact set of docker tags for each image which then must be combined into a manifest.
> ci: fix docker manifest generation

- .github/workflows/main.yml
I forgot that the generate-manifest job in ci will need to checkout a copy of the repo now that it utilizes a couple scripts. :facepalm: This _should_ fix the current problem, and hopefully no other issues pop up after this is merged. :disappointed:
> ci: add missing checkout step to generate-manifest

- doc/man1/flux-modprobe.rst
- src/bindings/python/flux/modprobe.py
- src/cmd/flux-modprobe.py
- src/modules/sched-simple/sched.c
- t/t0100-modprobe.t
This PR fixes the `modprobe.Context.bash()` helper, which currently is ignoring non-zero exit status from the invoked command(s).
Additionally, a few more tests are added to the modprobe testsuite to check that the `bash()` helper is working properly, and that module load failures (and other `@task` failures) cause `flux modprobe` to fail.
> modprobe: fix handling of `modprobe.Context.bash()` errors and expand testing

- doc/man1/common/job-other-options.rst
Problem: A signal sent to a batch job is delivered both to all the running jobs and the batch script. The latter may be surprising or catch users off guard if they expect only the jobs to be signaled.
Add a note to the submission commands documentation for `--signal` describing signal behavior for batch jobs, and suggesting batch scripts use a `trap` to capture `SIG` to avoid early exit.
Fixes #6964
@ryanday36, does this seem sufficient to close #6964?
> doc: add note about `--signal=SIG@TIME` behavior in batch jobs

- etc/rc1.old
- src/broker/broker.c
- src/broker/modhash.c
- src/broker/modhash.h
- src/broker/state_machine.c
- src/broker/state_machine.h
- t/t0025-broker-state-machine.t
Problem: since the early days, there has a been a race between loading the `connector-local` module and loading other modules, which requires that the local connector be usable.  We have addressed this in CI by increasing connect retries in rc1, but that still can fail on occasion.
This integrates builtin module loading into the broker state machine such that the state does not advance to from NONE to JOIN until after the built-in (`autoload=true`) modules are in RUNNING state.  Since `connector-local` does not enter RUNNING state until it is listening on the socket, this effectively closes the race.
This appears to address the failures that are occurring in CI in #6959, where the broker groups subsystem is converted to an `autoload=true` module.
> broker: wait for built-in plugins to be RUNNING before loading other modules

- scripts/check-macos.sh
- scripts/configure-macos.sh
- src/broker/test/boot_config.c
- src/broker/test/overlay.c
- src/cmd/flux-terminus.c
- src/common/librlist/rhwloc.c
- src/common/libsubprocess/fork.c
- src/common/libsubprocess/local.c
- src/common/libsubprocess/sigchld.c
- src/common/libsubprocess/test/subprocess.c
- src/common/libtap/tap.h
- src/common/libterminus/client.c
- src/common/libterminus/pty.c
- src/common/libterminus/test/pty.c
- src/common/libtestutil/Makefile.am
- src/common/libtestutil/test_file.c
- src/common/libtestutil/test_file.h
- src/shell/Makefile.am
- src/shell/affinity.c
This is stacked on top of #6926, and contains all changes necessary to get all tests in `src` to pass.  I don't have the GHA updates in here yet, but that's coming next.
> More macos fixes

- src/common/libterminus/test/terminus.c
problem: There's what seems to be a race condition in the terminus wait setup that can occur if the spawned process dies too fast. This triggers very frequently on MacOS.
solution: skip these tests there for now.
I'm creating a new issue for the race condition because it seems very likely it's possible on Linux as well under the right conditions. See [this comment](https://github.com/flux-framework/flux-core/pull/6929#issuecomment-3137916572) for more details.
> test/terminus: skip kill tests due to race

- doc/man1/flux-jobs.rst
Problem: flux-jobs(1) has a typo, where contextual_info appears twice, and contextual_time appears undocumented.
The second contextual_info should actually be contextual_time. Fix it.
> doc: fix flux-jobs(1) docs on contextual_time

- src/common/librlist/rlist.c
- src/common/librlist/rlist.h
- src/shell/jobspec.c
- src/shell/rcalc.c
- src/shell/rcalc.h
- src/shell/test/jobspec.c
This is my initial attempt to investigate what is required to enable resource ranges in jobspec à la RFC 14. Very rough at this point (in particular there is lots of work to do on the testsuite) but I am interested in discussion about some potential design considerations that have come up. The code to this point allows jobspec with ranges that is otherwise V1 compliant to be allocated and run successfully, but at least the job-list service still issues a non-fatal error, and I've just ignored sched-simple at this point.
(update: the discussion in this paragraph has now been addressed by #6682)
Firstly, because flux-sched already largely supports ranges, once a couple of explicit version checks are tweaked in libjob and shell, we can already get back a resource set allocation from fluxion. …
> rlist and shell: record nslots in allocated Rv1 for use in shell init

- configure.ac
- doc/guide/admin.rst
- doc/man1/flux-config.rst
- doc/man5/flux-config-job-manager.rst
- doc/test/spell.en.pws
- etc/Makefile.am
- etc/flux-core.pc.in
- etc/flux-epilog@.service.in
- etc/flux-housekeeping@.service.in
- etc/flux-prolog@.service.in
- etc/flux-run-system-scripts.in
- src/common/libflux/conf.c
- src/modules/job-manager/housekeeping.c
- src/modules/job-manager/plugins/perilog.c
- src/test/docker/docker-run-systest.sh
- t/system/0006-perilog.t
- t/t9000-system.t
This PR adds a wrapper script for handling the execution of prolog,epilog,housekeeping instead of executing `/etc/flux/system/{prolog,epilog,housekeeping}` directly from the `flux-{prolog,epilog,housekeeping}@JOBID` systemd units. The wrapper script (installed at `$libexecdir/flux-run-system-scripts`) executes scripts in the following order for `name` in `prolog`, `epilog`, `housekeeping`:
1. All package provided scripts at `$libexecdir/flux/{name}.d`
2. If `/etc/flux/system/{name}` exists, then this script is executed directly for backwards compatibiliy, and step 3. is skipped.
3. All system provided scripts at `/etc/flux/system/{name}.d`
This preserves behavior on existing systems while still allowing packages to install drop-in scripts into the system that will be executed as part of …
> support drop-in scripts in `$libexecdir/flux/{prolog,epilog,housekeeping}.d`

- src/bindings/python/flux/modprobe.py
- t/t0100-modprobe.t
This bug was uncovered while doing some other modprobe work:
Modules that are selected as the current alternative for some service, e.g. `sched`, do not automatically have their `requires` list activated. If the module also has a `needs` on a module it `requires`, this can end up _deactivating_ the selected alternative since its `needs` is not met.
Automatically activate modules in the required list of an activated module. Also, add a couple new tests to check the expected behavior.
> modprobe: ensure required modules of activated alternatives are also active

- t/t2816-fsck-cmd.t
Problem: The test directories in t2816-fsck-cmd.t are simply named "dir", but things can get confusing when comments describe
treeobjs of type "dir".
Rename all "dir" paths to "testdir".
----
splitting off from bigger PR b/c it's quite "noisy" with a lot of search and replace changes.
> t: rename test dirs for fsck tests

- doc/man7/flux-broker-attributes.rst
- src/broker/rundir.c
- t/t0036-broker-rundir.t
Problem: as discussed in #6990, it's somewhat inconvenient to make the user specify a unique path when they submit a job that should use an alternate location for `statedir`.
If  `-Sstatedir=DIR` refers to a `/tmp` like directory (a directory with the sticky bit set), then a unique directory is created with in it.
So on CORAL-2 systems where rabbits are mounted on `/l/ssd`, one could specify `--broker-opts=-Sstatedir=/l/ssd` to ensure the content-sqlite db doesn't eat up memory in the tmpfs ramdisk on rank 0.
> broker: interpret sticky bit in -Sstatedir=DIR

- t/issues/t2492-shell-lost.sh
Problem: The `flux pmi barrier` call in t2492-shell-lost.sh is not functional because Python's `subprocess.run()` is closing the PMI_FD. This causes the barrier to exit prematurely and results in a race where the test job can get killed by SIGINT before it is handling the signal.
Add `close_fds=False` to the `subprocess.run()` call so that the PMI fd is not closed and the barrier functions properly.
> testsuite: fix barrier in shell-lost issues test

- t/t2412-sdmon.t
On my test system I was getting failures in `t2412-sdmon.t` because an old `shell-t412.service` unit was in a failed state in my systemd user unit. The `systemctl --user stop` command didn't seem to clean up the unit, so subsequent tests were failing.
This PR just adds an additional `systemctl --user reset-failed <unit>` to the part of the test that tries to ensure residual units are not running. This seems to resolve the issue on my system, but we'll see if it passes in CI.
> testsuite: improve cleanup in t2412-sdmon.t

- src/cmd/builtin/content.c
- t/Makefile.am
- t/t0035-content-sqlite-checkpoint.t
- t/t0037-content-files-checkpoint.t
Problem: There is no way to update the content's KVS checkpoint
on the command line.
Support a new "flux content checkpoint update" command.
Built on #6981.  based on conversation in #6953..  
I could have supported options to update checkpoint w/ a sequence number or timestamp.  Elected not to for the time being b/c didn't think that was important right now.
> flux-content: support checkpoint update command

- doc/man1/flux-fsck.rst
- src/cmd/builtin/fsck.c
- src/modules/job-manager/restart.c
- t/t2219-job-manager-restart.t
- t/t2816-fsck-cmd.t
Problem: flux-fsck can identify corrupted KVS entries, but does not presently do anything to help users recover data.
Support a --lost-and-found option.  Corrupted KVS entries will be recovered as best as possible and placed into a "lost+found"
directory for users to consider using.
----
notes:
- I struggled with some documentation / verbiage here.  "recover" doesn't seem to be the right word sometimes, as that suggests full recovery.  Perhaps there's a better word I'm not thinking of.
- there is no handling of corrupted treeobjs, like hypothetically a treeobj that is outright bad (fails `treeobj_validate()`).  We could stick "empty values" in `lost+found` for those?
- I chose the directory "lost+found", which is actually what is used by the `job-manager` for its lost and found.  Should …
> flux-fsck: add --repair option

- configure.ac
- src/common/libutil/Makefile.am
- src/common/libutil/cgroup.c
- src/common/libutil/cgroup.h
- src/common/libutil/test/cgroup.c
- src/shell/sysmon.c
- t/t2622-job-shell-sysmon.t
Problem: sysmon assumes the unfied cgroup hierarchy, but some modern systems use the hybrid hierarchy.
Use  cgroup support code pulled in from flux-security, as it handles the hybrid cgroup hierarchy
In addition, use some new cgroup helpers to parse `/sys` files instead of embedding one-offs.
Also, treat missing memory or cpu `/sys` files as non-fatal warnings, simply disabling one or the other with a warning message.
Fixes #7026
As extra credit later on, the oom plugin could be similarly converted.
> sysmon: handle hybrid cgroup hierarchy

- configure.ac
- doc/man1/flux-modprobe.rst
- doc/man7/flux-environment.rst
- doc/test/spell.en.pws
- etc/Makefile.am
- etc/completions/flux.pre
- etc/flux-core.pc.in
- src/bindings/python/flux/modprobe.py
- src/cmd/flux-modprobe.py
- src/common/libflux/conf.c
- t/t0100-modprobe.t
This PR moves internal config and rc files for modprobe out of `/etc/flux/modprobe` and into `/usr/share/flux/modprobe` (datadir) and `/usr/libexec/flux/modprobe` (libexecdir). The two paths are used because `/usr/share` is more appropriate for TOML config files, while `/usr/libexec` is standard for code like the Python `rcX.py` files. (It is an open question whether to just put the two types of configuration for modprobe under the same paths. This is why the PR is currently WIP)
The modprobe default search path now works like this:
- the default `modprobe.toml` or `rcX.py` is read first from `/usr/share/flux/modprobe/modprobe.toml` or `/usr/lbexec/flux/modprobe/rcX.py`
- If `FLUX_MODPROBE_PATH` is set, then it is a colon separated PATH from which `$dir/modprobe.d/*.toml` or …
> modprobe: move package provided files out of `/etc`

- doc/man1/flux-jobs.rst
- src/cmd/flux-jobs.py
- src/cmd/flux-pgrep.py
Last week, on the WSC rounds, a frequent complaint of users was that the default output of `flux jobs` cut off full usernames, and it felt like something they had to constantly work around. With the IdM upgrade last year, now a lot of usernames are longer than 8 characters, and I assume this is something we'd see at other centers as well.
I don't think showing a `+` at the end of the username to indicate the length exceeded 8 characters would really address the usability, since that would still require our users to constantly override the default format. 
This seems like a very reasonable request. I think we should change the default format.
> Show full usernames by default in flux-jobs(1) and flux-pgrep(1) 

- src/cmd/builtin/fsck.c
Problem: In older versions of flux, content.validate isn't available, thus flux-fsck cannot work against older versions of flux.
Divert to content.load if content.validate is not available.
---
just like #7044, hand tested on docker w/ v0.76.0. I don't think we have infrastructure to do a "current master" vs "random older versions", that's perhaps something to consider for another day?
> flux-fsck: use content.load on older versions

- doc/man3/flux_pollevents.rst
- doc/test/spell.en.pws
- src/common/libflux/handle.c
- src/common/libflux/handle.h
- src/common/libflux/test/handle.c
Problem: calling `flux_pollfd()` causes an epoll file descriptor to be created internally, but the file descriptor is not closed when the `flux_t` handle is destroyed.
Since each call to `flux_pollfd()` reuses the internal file descriptor, it is clearly "owned" by the handle.  Close it when the handle is destroyed.
Also:  update the man page to make it clear that the file descriptor belongs to the handle, and while in there, replace a convoluted example with a simple description.
> libflux: fix flux_pollfd() file descriptor leak

- src/common/libflux/handle.c
- src/common/libflux/test/interthread.c
- t/issues/t3503-nofiles-limit.sh
Problem: when `flux_open()` is used with the FLUX_O_NOREQUEUE flag, the connector implementation's pollfd method is returned directly by `flux_pollfd()`, but not all connectors supply an edge-triggered fd, as required by `flux_pollfd()`.
For example, the local connector's pollfd method returns the level-triggered communications socket.
FLUX_O_NOREQUEUE was added to reduce the number of file descriptors used by interthread sockets from 3 (deque, requeue, and epoll wrapper) to 1 (deque).  Since back-to-back interthread pairs are used for each broker module, this allowed more co-located test brokers to be run for a given file descriptor limit.
Compromise: let FLUX_O_NOREQUEUE suppress creation of the requeue deque, saving 1 file descriptor, but unconditionally create the epoll wrapper, for …
> libflux: ensure flux_pollfd() is edge triggered

- etc/modprobe/rc1.py
Problem: The rc1 "restore" task lists loading the "kvs" as a "requires" dependency.  This conflicts with A) "flux restore --checkpoint" cannot be run if the kvs is loaded and B) "kvs" is listed in this task as a "before" dependency
Solution: Remove "kvs" from the list of "requires" for the "restore" task.
> etc/modprobe: remove kvs requires on restore task

- etc/modprobe/rc1.py
Problem: Under the "restore" task, "flux restore" is not called with the --sd-notify option like in "rc1.old".  --sd-notify was added after rc1.py was created, so it was likely just not copied over.
Add the missing --sd-notify option.
> modprobe/rc1: call flux restore with --sd-notify

- doc/man3/flux_pollevents.rst
- src/common/libflux/connector_interthread.c
- src/common/libflux/connector_loop.c
- src/common/libflux/handle.c
- src/common/libflux/handle.h
- src/common/libflux/msg_deque.c
- src/common/libflux/msg_deque.h
- src/common/libflux/test/handle.c
- src/common/libflux/test/interthread.c
Problem: there are extra `flux_pollfd()` wakeups for every real event.
This is explained in more detail in commit messages, but to quickly summarize: the  `msg_deque` class that underlies the `interthread://` and `loop://` connector implementations, and is used to implement `flux_requeue()`, has a quirk where it asserts POLLOUT when its `pollevents` method is called with POLLIN pending.  Unfortunately, the handle pollfd implementation wraps those in an epoll fd that watches POLLIN | POLLOUT, so it gets an extra wakeup per msg_deque on every call to `flux_pollevents()` when it is responding to POLLIN.  The fix is to not watch POLLOUT on the re-queue deque or the connector when we know we don't need it, which is the case with the msg_deques which were designed to use POLLIN signaling.
This …
> libflux: reduce spurious pollfd wake-ups

- doc/man1/flux-module.rst
- etc/completions/flux.pre
- src/broker/modhash.c
- src/broker/module.c
- src/broker/module.h
- src/broker/module_exec.c
- src/cmd/flux-module.c
- t/module/testmod.c
- t/t0006-module-exec.t
Problem: although Flux broker extension modules are only allowed to interact with each other using messages, this isolation is not  enforced and a badly behaved module can crash the broker.
Add support for `flux module [re]load --exec`.   The broker runs `flux module-exec MODULE` as a sub-process instead of a thread, communicating with it over a dedicated sub-process message channel.
This is the final PR of the stack and is built on top of
- #7073
- #7072 
- #7071
- #7068
> add flux module load --exec option

- src/common/libsubprocess/client.c
- src/common/libsubprocess/client.h
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/test/remote.c
- t/t0005-rexec.t
Problem: `flux_rexec()` doesn't allow some flags to be set that were thought to only be useful for local subprocesses, but this is unnecessarily limiting.
For example, since SIGCHLD can only be handled in one thread of a multi-threaded process, local subprocesses must be launched from one thread.  In that context, another thread might need to use the remote subprocess interface to launch "local" processes.
Allow all flags to pass the validity check in `flux_rexec()`. Pass them to the server via a new `lflags` key (RFC 42 update required).
Call `flux_subprocess_kill()` from the server kill handler instead of hardwiring `killpg(2)` for remote subprocesses.
Return better human-readable errors when remote kill fails.
Update unit tests.
N.B. issue #5968 was probably closed prematurely, when …
> libsubprocess: allow all flags to work remotely

- src/common/libsubprocess/client.c
- src/common/libsubprocess/remote.c
- src/common/libsubprocess/server.c
Problem: the 'lflags' key in the subprocess exec request is poorly named.
Rename to 'local_flags'.
> libsubprocess: rename lflags to local_flags

- t/t3203-instance-recovery.t
Problem: a test in t3203-instance-recovery.t hangs in CI.
I'm not sure what's going on but the test is just a cut and paste of the one above when it could be simplified to avoid the need for the runpty wrapper, which might be creating the environment needed for the hang.
Simplify the test.
Not a fix to #7091 but maybe a workaround for now.
> testsuite: simplify test to avoid hang

- src/common/libsubprocess/command.c
Problem: RFC 42 states that the 'msgchans' key in the exec request payload is an array of objects, but it is currently implemented as an array of arrays.
Update implementation to match the RFC.
> adjust subprocess server protocol to conform to RFC 42

- src/broker/overlay.c
- src/common/libflux/event.c
- t/lua/t0003-events.t
- t/t0004-event.t
Problem: `event.subscribe` and `event.unsubscribe` are handled by the broker, but `event.publish` is handled by the overlay code, which might move to a built-in broker module at some point.
Change the RPC target from `event.publish` to `overlay.publish` so the publish method can move outside of the broker with the overlay code.
Update tests.
This follows on and probably should have been submitted with
- #7100
The idea of moving the overlay code to a built-in module was brought up in
- #6967
> broker: rename event.publish to overlay.publish

- doc/man7/flux-broker-attributes.rst
- doc/test/spell.en.pws
Problem: The documentation for conf.shell_initrc and conf.shell_pluginpath use "${prefix}/flux" to describe the defaults. While this is commonly correct, it isn't technically correct.
Update conf.shell_initrc's default with "${sysconfdir}" and conf.shell_pluginpath's default with "${libdir}".
Fixes #7101
---
Per comment in #7101, there was discussion of adding `flux config builtin ....`, but I ended up electing not to.
> doc: update flux-broker-attributes(7) defaults

- doc/man1/flux-modprobe.rst
Problem: A keyword is not consistently quoted, leading to formatting errors.
Fix the backtick quotations.
> doc: fix formatting typo in flux-modprobe(1)

- src/cmd/builtin/fsck.c
- t/t2816-fsck-cmd.t
Per discussion in #7082, minor tweaks for flux-fsck to predominantly support the fact many times fsck will be run out of rc1
> flux-fsck: prefix output when not attached to a tty

- doc/man1/flux-exec.rst
- src/cmd/flux-exec.c
- src/common/libsubprocess/client.c
- src/common/libsubprocess/client.h
- src/common/libsubprocess/server.c
- src/common/libsubprocess/subprocess.c
- src/common/libsubprocess/subprocess.h
- src/common/libsubprocess/subprocess_private.h
- src/common/libsubprocess/test/subprocess.c
- t/t0005-exec.t
This PR adds support for the `SUBPROCESS_REXEC_BACKGROUND` flag proposed in https://github.com/flux-framework/rfc/pull/470. The flag is activated via a new `flux_rexec_bg(3)` API call, which simply returns a `flux_future_t *` instead of a `flux_subprocess_t *`. Once the future is fulfilled, the subprocess has either been launched in the background, or if fulfilled with error, has failed to executed. Note that the RPC is still streaming, so a successful response is always followed by an `ENODATA` response.
Using this new interface, a `--bg` flag is added to `flux exec`. With this flag, `flux exec` exits after all requested processes have started while the processes continue to run as child of the subprocess server until they exit or the server is stopped.
This is a WIP because I'm not sure …
> add `flux_rexec_bg(3)` and `flux exec --bg`

- src/bindings/python/flux/core/handle.py
- t/python/t0001-handle.py
This is a simple PR that adds an explicit `attr_set()` method to the handle class. The method detects non-string arguments and raises more sensible errors than the direct cffi call would, which looks like this:
```
$ flux python -c 'import flux; flux.Flux().attr_set("foo", 1)'
Traceback (most recent call last):
File "/usr/lib/aarch64-linux-gnu/flux/python3.10/flux/wrapper.py", line 194, in __call__
result = self.fun(*args)
TypeError: initializer for ctype 'char *' must be a cdata pointer, not int
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/aarch64-linux-gnu/flux/python3.10/flux/wrapper.py", line 196, in __call__
raise InvalidArguments(
flux.wrapper.InvalidArguments: 
Invalid …
```
> python: add explicit `attr_set()` method to Flux handle class
